Cumbia communication independent controls based on Qt: ScrollZoomer Class Reference
ScrollZoomer Class Reference
#include <scrollzoomer.h>
Public Types
enum ScrollBarPosition { AttachedToScale, OppositeToScale }
Public Member Functions
ScrollZoomer (QWidget *)
virtual ~ScrollZoomer ()
void setZoomBase (bool do_replot=true)
void setZoomBase (const QRectF &r)
ScrollBar * horizontalScrollBar () const
ScrollBar * verticalScrollBar () const
void setHScrollBarMode (Qt::ScrollBarPolicy)
void setVScrollBarMode (Qt::ScrollBarPolicy)
Qt::ScrollBarPolicy vScrollBarMode () const
Qt::ScrollBarPolicy hScrollBarMode () const
void setHScrollBarPosition (ScrollBarPosition)
void setVScrollBarPosition (ScrollBarPosition)
ScrollBarPosition hScrollBarPosition () const
ScrollBarPosition vScrollBarPosition () const
QWidget * cornerWidget () const
virtual void setCornerWidget (QWidget *)
virtual bool eventFilter (QObject *, QEvent *)
virtual void rescale ()
Protected Member Functions
virtual ScrollBar * scrollBar (Qt::Orientation)
virtual void updateScrollBars ()
virtual void layoutScrollBars (const QRect &)
Member Enumeration Documentation
ScrollBarPosition
enum ScrollZoomer::ScrollBarPosition
Enumerator
AttachedToScale
OppositeToScale
Constructor & Destructor Documentation
ScrollZoomer()
ScrollZoomer::ScrollZoomer (QWidget * canvas)
~ScrollZoomer()
ScrollZoomer::~ScrollZoomer () virtual
Member Function Documentation
cornerWidget()
QWidget * ScrollZoomer::cornerWidget () const
eventFilter()
bool ScrollZoomer::eventFilter (QObject * object, QEvent * event) virtual
References layoutScrollBars(), ScrollData::mode, and ScrollData::scrollBar.
horizontalScrollBar()
ScrollBar * ScrollZoomer::horizontalScrollBar () const
References ScrollData::scrollBar.
Referenced by layoutScrollBars(), and updateScrollBars().
hScrollBarMode()
Qt::ScrollBarPolicy ScrollZoomer::hScrollBarMode () const
References ScrollData::mode.
Referenced by setHScrollBarMode().
hScrollBarPosition()
ScrollZoomer::ScrollBarPosition ScrollZoomer::hScrollBarPosition () const
References ScrollData::position.
Referenced by layoutScrollBars(), and updateScrollBars().
layoutScrollBars()
void ScrollZoomer::layoutScrollBars (const QRect & rect) protected virtual
References ScrollBar::extent(), horizontalScrollBar(), hScrollBarPosition(), OppositeToScale, verticalScrollBar(), and vScrollBarPosition().
Referenced by eventFilter(), and updateScrollBars().
rescale()
void ScrollZoomer::rescale () virtual
References updateScrollBars().
scrollBar()
ScrollBar * ScrollZoomer::scrollBar (Qt::Orientation orientation) protected virtual
References ScrollData::scrollBar.
Referenced by updateScrollBars().
setCornerWidget()
void ScrollZoomer::setCornerWidget (QWidget * w) virtual
References updateScrollBars().
setHScrollBarMode()
void ScrollZoomer::setHScrollBarMode (Qt::ScrollBarPolicy mode)
References hScrollBarMode(), ScrollData::mode, and updateScrollBars().
setHScrollBarPosition()
void ScrollZoomer::setHScrollBarPosition (ScrollBarPosition pos)
References ScrollData::position, and updateScrollBars().
setVScrollBarMode()
void ScrollZoomer::setVScrollBarMode (Qt::ScrollBarPolicy mode)
References ScrollData::mode, updateScrollBars(), and vScrollBarMode().
setVScrollBarPosition()
void ScrollZoomer::setVScrollBarPosition (ScrollBarPosition pos)
References ScrollData::position, and updateScrollBars().
setZoomBase() [1/2]
void ScrollZoomer::setZoomBase (bool do_replot = true)
Referenced by QuPlotZoomComponent::changeRect(), QuPlotZoomComponent::name(), and QuPlotZoomComponent::setZoomBase().
setZoomBase() [2/2]
void ScrollZoomer::setZoomBase (const QRectF & r)
updateScrollBars()
void ScrollZoomer::updateScrollBars () protected virtual
References ScrollBar::extent(), horizontalScrollBar(), hScrollBarPosition(), layoutScrollBars(), ScrollBar::moveSlider(), OppositeToScale, scrollBar(), ScrollBar::setBase(), ScrollBar::setInverted(), verticalScrollBar(), and vScrollBarPosition().
Referenced by rescale(), setCornerWidget(), setHScrollBarMode(), setHScrollBarPosition(), setVScrollBarMode(), and setVScrollBarPosition().
verticalScrollBar()
ScrollBar * ScrollZoomer::verticalScrollBar () const
References ScrollData::scrollBar.
Referenced by layoutScrollBars(), and updateScrollBars().
vScrollBarMode()
Qt::ScrollBarPolicy ScrollZoomer::vScrollBarMode () const
References ScrollData::mode.
Referenced by setVScrollBarMode().
vScrollBarPosition()
ScrollZoomer::ScrollBarPosition ScrollZoomer::vScrollBarPosition () const
References ScrollData::position.
Referenced by layoutScrollBars(), and updateScrollBars().
The documentation for this class was generated from the following files:
scrollzoomer.h
scrollzoomer.cpp