Cumbia communication independent controls based on Qt: EPlotLightMarker Class Reference
EPlotLightMarker Class Reference
This class provides a plot based on the efficient EPlotLight, to which it adds markers on the canvas.
#include <eplotlight_marker.h>
Public Slots
virtual void refresh ()
QwtPlotPicker * plotPicker () const
returns the QwtPlotPicker used to intercept the mouse events and display the QwtPlotMarker.
QwtPlotMarker * plotMarker () const
returns the QwtPlotMarker used to draw the curve x and y value when the plot is clicked
Arrow * markerArrow () const
returns the arrow drawn from the curve closest point and the marker.
void moveCurveToYRight (QwtPlotCurve *c, bool yr)
Public Slots inherited from EPlotLight
virtual void setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
Initialize data with x- and y-arrays (explicitly shared)
virtual void appendData (const QString &curveName, double x, double y)
Appends data to the curve with the given curveName, using the efficient draw() method.
virtual void appendData (const QString &curveName, double *x, double *y, int size)
Appends size data to the curve with the given curveName, using the efficient draw() method.
void setXAutoscale (bool a)
the same as setXAxisAutoscaleEnabled, provided for convenience and for backwards compatibility
void setYAutoscale (bool a)
the same as setYAxisAutoscaleEnabled, provided for convenience and for backwards compatibility
void setShowYValuesEnabled (bool show)
toggles y values visibility for each curve on the canvas.
bool showYValuesEnabled () const
returns true if Y values are shown, false otherwise.
void clearPlot ()
Clears data on the plot, removing values from the current curves.
QuPlotCurve * curve (const QString &name)
Returns the curve with the name provided.
QString curveName (QuPlotCurve *curve)
bool hasCurveIgnoreCase (const QString &name) const
Returns true if the plot has the curve with the given name, case insensitive search.
QuPlotCurve * getCurveIgnoreCase (const QString &name)
getCurveIgnoreCase returns the curve with the given name, looking for the name using a case insensitive search. This is the same as the curve method above.
Public Slots inherited from EPlotLightBase
virtual void refresh ()
refreshes the plot, taking care of the zoom state.
void setXAxisAutoscaleEnabled (bool en)
enables or disables x axis autoscale
void setYAxisAutoscaleEnabled (bool en)
enables Y axis autoscale
void extendYLowerBound (double l)
extends the lower bound of the Y axis
void extendYUpperBound (double u)
extends the upper bound of the Y axis
void setYLowerBound (double l)
changes the Y lower bound
void setYUpperBound (double u)
changes the Y upper bound
void setXLowerBound (double l)
sets x axis lower bound
void setXUpperBound (double u)
sets x axis upper bound
void setXAutoscaleAdjustment (double d)
adjusts the x axis scale bounds enlarging it of the percentage d
double xAutoscaleAdjustment ()
void setYAutoscaleAdjustment (double d)
adjusts the y axis scale bounds enlarging it of the percentage d
double yAutoscaleAdjustment ()
bool xAutoscaleAdjustEnabled ()
bool yAutoscaleAdjustEnabled ()
void setTitleOnCanvasEnabled (bool en)
void setXAutoscaleAdjustEnabled (bool a)
void setYAutoscaleAdjustEnabled (bool a)
void setCurvesStyle (CurveStyle curveStyle)
changes all the curves style
void setZoomDisabled (bool)
Enables or disables the zooming capabilities.
void getXBoundsFromCurves (double *xMin, double *xMax)
scans all curves looking for minimum and maximum values among the x values.
double getXScaleInterval (double xMin, double xMax)
returns the scale interval according to the minimum and maximum values passed.
Signals
void plotClicked (const QPoint &pt, QwtPlotCurve *closestCurve, double x, double y, const QPoint &curvePoint)
Signals inherited from EPlotLight
void curveAdded (QuPlotCurve *)
This signal is emitted when a new curve is added to the plot.
void curveRemoved (QuPlotCurve *)
This signal is emitted whenever a curve is removed from the plot via removeCurve.
Public Member Functions
EPlotLightMarker (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities with a plot marker.
EPlotLightMarker (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities with a plot marker.
void setMarkerLabel (const QwtText &text)
Change the aspect of the marker: render flags, color, font, background brush, background pen...
QSet< QwtPlotCurve * > intersectingCurves (const double x, const double y, const QwtPlotCurve *curve)
returns the list of curves that are intersect the curve in the point (x,y)
Public Member Functions inherited from EPlotLight
EPlotLight (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
EPlotLight (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
void addCurve (const QString &curveName, QuPlotCurve *curve)
Registers a new curve with the provided curveName.
void removeCurve (const QString &curveName)
Removes the specified curve from the plot, deleting it.
void setCurveStyle (const QString &curveName, QwtPlotCurve::CurveStyle)
sets a particular curve style for the specified curveName
void createAndAddCurve (const QString &curveName)
creates a curve with name curveName, adds it to the internal map of curves
void removeData ()
void setDataBufferSize (int b)
sets the data buffer size to b elements. When b is reached, data is removed from the front.
int dataBufferSize ()
returns the data buffer size.
int timeInterval () const
void setTimeInterval (int t)
bool yAutoscale ()
Public Member Functions inherited from EPlotLightBase
EPlotLightBase (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
EPlotLightBase (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
void setTimeScaleDrawEnabled (bool enable)
Enables x axis interpretation as a timestamp and produces date/time labels in the axis itself.
bool timeScaleDrawEnabled ()
bool dateOnTimeScaleDrawEnabled () const
returns true if the time scale draw writes the day on the date label
void setDateOnTimeScaleDrawEnabled (bool en)
enables or disables the date on the x axis scale draw
bool adjustScales (double percent=0.0, bool do_replot=true)
calls setAxisScale on the X and Y axis. The bounds are calculated reading the limits from all the curves and expanding both axes of a percentage.
bool adjustXScale (double percent=0.0, bool do_replot=true)
bool adjustYScale (double percent=0.0, bool do_replot=true)
bool setAxisScaleIfNeeded (int axisId, double min, double max, double step=0)
bool titleOnCanvasEnabled ()
void setAlignCanvasToScalesEnabled (bool en)
calls QwtPlotLayout::setAlignCanvasToScales
bool alignCanvasToScalesEnabled ()
bool xAxisAutoscaleEnabled ()
bool yAxisAutoscaleEnabled ()
double yUpperBound ()
double yLowerBound ()
bool xAxisLogScale ()
bool yAxisLogScale ()
void setXAxisLogScale (bool l)
void setYAxisLogScale (bool l)
double xUpperBound ()
double xLowerBound ()
bool zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
QList< QwtPlotCurve * > curves ()
Protected Slots
void showLabel (const QPolygon &)
void updateLabel (QwtPlotCurve *closestCurve, int closestPoint)
int findClosestPoint (QPoint p, QwtPlotCurve **closestCurve)
void hideMarker ()
void plotZoomed (const QRectF &)
Protected Slots inherited from EPlotLight
virtual void dataUpdated ()
Protected Slots inherited from EPlotLightBase
void displayZoomHint ()
void eraseZoomHint ()
Protected Member Functions
virtual QString markerText (const QwtPlotCurve *relatedCurve, const int index)
Personalize the marker text when a user clicks on the plot area.
virtual void mouseReleaseEvent (QMouseEvent *ev)
virtual void keyPressEvent (QKeyEvent *ke)
Protected Member Functions inherited from EPlotLight
virtual QMenu * rightClickMenu ()
void print ()
void snapshot ()
void copyImage ()
void saveData ()
dumps the curves into a csv file.
virtual void configurePlot ()
executes the EPlotConfigurationDialog to configure the appearence of the plot.
Protected Member Functions inherited from EPlotLightBase
virtual QString plotTitle ()
returns the plot title.
virtual void drawCanvas (QPainter *p)
Additional Inherited Members
Public Types inherited from EPlotLightBase
enum CurveStyle {
NoCurve, Lines, Sticks, Steps,
Dots, UserCurve = 100
}
Protected Attributes inherited from EPlotLightBase
Zoomer * zoomer
Properties inherited from EPlotLight
bool timeScaleEnabled
bool dateOnTimeScaleDrawEnabled
int dataBufferSize
Properties inherited from EPlotLightBase
bool xAxisAutoscale
bool yAxisAutoscale
bool alignCanvasToScales
double yUpperBound
double yLowerBound
double xUpperBound
double xLowerBound
bool xAutoscaleAdjustEnabled
bool yAutoscaleAdjustEnabled
double xAutoscaleAdjustment
double yAutoscaleAdjustment
bool titleOnCanvasEnabled
bool xAxisLogScale
bool yAxisLogScale
bool zoomDisabled
CurveStyle curvesStyle
Detailed Description
This class provides a plot based on the efficient EPlotLight, to which it adds markers on the canvas.
Using or inheriting this widget provides markers to your plot. Clicking on a point over the plot canvas produces a marker displaying text in a rectangle. The default text displayed represents the values of the x and y values of the curve closest to the clicked point.
Overwriting markerText() method can be useful (on an inherited plot) to personalize the text displayed on the marker.
Constructor & Destructor Documentation
EPlotLightMarker() [1/2]
EPlotLightMarker::EPlotLightMarker (QWidget * parent)
The constructor of a simple plot with zooming and scrolling capabilities with a plot marker.
Parameters
parent the parent widget
EPlotLightMarker() [2/2]
EPlotLightMarker::EPlotLightMarker (const QwtText & title, QWidget * parent)
The constructor of a simple plot with zooming and scrolling capabilities with a plot marker.
Parameters
parent the parent widget
title the title of the plot
References ALPHAVAL, Elettra::black, KDARKGRAY, plotZoomed(), showLabel(), and EPlotLightBase::zoomer.
Member Function Documentation
findClosestPoint
int EPlotLightMarker::findClosestPoint (QPoint p, QwtPlotCurve ** closestCurve) protected slot
References qstoc.
Referenced by showLabel().
hideMarker
void EPlotLightMarker::hideMarker () protected slot
Referenced by mouseReleaseEvent(), and plotZoomed().
intersectingCurves()
QSet< QwtPlotCurve * > EPlotLightMarker::intersectingCurves (const double x, const double y, const QwtPlotCurve * curve)
returns the list of curves that are intersect the curve in the point (x,y)
Returns
QSet of QwtPlotCurve of the curves that overlap in the point (x,y)
Parameters
x the value of the x axis of the desired point
y the value of the y axis of the desired point
curve the curve we want to test whether it intersects other curves in point x
The return value won't contain the curve passed as second argument. So the returned set might be an empty set.
References EPlotLightBase::curves().
Referenced by markerText().
keyPressEvent()
void EPlotLightMarker::keyPressEvent (QKeyEvent * ke) protected virtual
References moveCurveToYRight().
markerArrow
Arrow* EPlotLightMarker::markerArrow () const inline slot
returns the arrow drawn from the curve closest point and the marker.
See also
plotMarker
plotPicker
markerText()
QString EPlotLightMarker::markerText (const QwtPlotCurve * relatedCurve, const int index) protected virtual
Personalize the marker text when a user clicks on the plot area.
Parameters
relatedCurve the closest curve to the point where the user clicked.
index the index value. To retrieve the x value of the curve, call relatedCurve->x(index) and to obtain the y value, relatedCurve->y(index).
Returns
a QString used by updateLabel() to fill in the marker.
relatedCurve is not null when invoked by updateLabel().
References intersectingCurves().
Referenced by refresh(), and updateLabel().
mouseReleaseEvent()
void EPlotLightMarker::mouseReleaseEvent (QMouseEvent * ev) protected virtual
References hideMarker().
moveCurveToYRight
void EPlotLightMarker::moveCurveToYRight (QwtPlotCurve * c, bool yr) slot
Referenced by keyPressEvent().
plotClicked
void EPlotLightMarker::plotClicked (const QPoint & pt, QwtPlotCurve * closestCurve, double x, double y, const QPoint & curvePoint) signal
Referenced by showLabel().
plotMarker
QwtPlotMarker* EPlotLightMarker::plotMarker () const inline slot
returns the QwtPlotMarker used to draw the curve x and y value when the plot is clicked
See also
markerArrow
plotPicker
Returns
the QwtPlotMarker
plotPicker
QwtPlotPicker* EPlotLightMarker::plotPicker () const inline slot
returns the QwtPlotPicker used to intercept the mouse events and display the QwtPlotMarker.
Returns
the QwtPlotPicker
See also
plotMarker
markerArrow
plotZoomed
void EPlotLightMarker::plotZoomed (const QRectF &) protected slot
References hideMarker().
Referenced by EPlotLightMarker().
refresh
void EPlotLightMarker::refresh () virtual slot
References EPlotLightBase::curves(), markerText(), and EPlotLightBase::refresh().
setMarkerLabel()
void EPlotLightMarker::setMarkerLabel (const QwtText & text)
Change the aspect of the marker: render flags, color, font, background brush, background pen...
Parameters
text the QwtText used to personalize the markers. You might want to reimplement markerText() below to personalize the text each time a marker is updated.
showLabel
void EPlotLightMarker::showLabel (const QPolygon & p) protected slot
References findClosestPoint(), plotClicked(), and updateLabel().
Referenced by EPlotLightMarker().
updateLabel
void EPlotLightMarker::updateLabel (QwtPlotCurve * closestCurve, int closestPoint) protected slot
References markerText(), pwarn, EPlotLightBase::xLowerBound(), EPlotLightBase::xUpperBound(), EPlotLightBase::yLowerBound(), and EPlotLightBase::yUpperBound().
Referenced by showLabel().
The documentation for this class was generated from the following files:
eplotlight_marker.h
eplotlight_marker.cpp