cumbia-qtcontrols: ERW Class Reference
ERW Class Reference
#include <erw.h>
Public Member Functions
ERW (QWidget *parent=0)
~ERW ()
Constructor & Destructor Documentation
ERW()
ERW::ERW (QWidget * parent = 0)
References ENumeric::maximum, ENumeric::minimum, EInputOutputWidget::setInputWidget(), ENumeric::setIntDigits(), ENumeric::setMaximum(), ENumeric::setMinimum(), EInputOutputWidget::setOutputText(), and ENumeric::setValue().
~ERW()
ERW::~ERW ()
The documentation for this class was generated from the following files:
erw.h
erw.cpp