Cumbia communication independent controls based on Qt: CurveData Class Reference
CurveData Class Reference
#include <ecurvedata.h>
Public Member Functions
CurveData ()
void append (double *x, double *y, int count)
void set (const QVector< double > &xData, const QVector< double > &yData)
void removeFirstElements (int n)
int count () const
int size () const
const double * x () const
const double * y () const
const QVector< double > xData ()
const QVector< double > yData ()
Constructor & Destructor Documentation
CurveData()
CurveData::CurveData ()
Member Function Documentation
append()
void CurveData::append (double * x, double * y, int count)
References count(), and size().
Referenced by QuPlotCurve::appendData().
count()
int CurveData::count () const
Referenced by append(), QuPlotCurve::clearData(), QuPlotCurve::count(), QuPlotCurve::popFront(), and QuPlotCurve::updateRawData().
removeFirstElements()
void CurveData::removeFirstElements (int n)
Referenced by QuPlotCurve::clearData(), and QuPlotCurve::popFront().
set()
void CurveData::set (const QVector< double > & xData, const QVector< double > & yData)
References xData(), and yData().
Referenced by QuPlotCurve::setData().
size()
int CurveData::size () const
Referenced by append().
x()
const double * CurveData::x () const
Referenced by QuPlotCurve::updateRawData().
xData()
const QVector<double> CurveData::xData () inline
Referenced by set().
y()
const double * CurveData::y () const
Referenced by QuPlotCurve::updateRawData().
yData()
const QVector<double> CurveData::yData () inline
Referenced by set().
The documentation for this class was generated from the following files:
ecurvedata.h
ecurvedata.cpp