Cumbia communication independent controls based on Qt: ScrollBar Class Reference
ScrollBar Class Reference
#include <scrollbar.h>
Public Slots
virtual void setBase (double min, double max)
virtual void moveSlider (double min, double max)
Signals
void sliderMoved (Qt::Orientation, double, double)
void valueChanged (Qt::Orientation, double, double)
Public Member Functions
ScrollBar (QWidget *parent=NULL)
ScrollBar (Qt::Orientation, QWidget *parent=NULL)
ScrollBar (double minBase, double maxBase, Qt::Orientation o, QWidget *parent=NULL)
void setInverted (bool)
bool isInverted () const
double minBaseValue () const
double maxBaseValue () const
double minSliderValue () const
double maxSliderValue () const
int extent () const
Protected Member Functions
void sliderRange (int value, double &min, double &max) const
int mapToTick (double) const
double mapFromTick (int) const
Constructor & Destructor Documentation
ScrollBar() [1/3]
ScrollBar::ScrollBar (QWidget * parent = NULL)
ScrollBar() [2/3]
ScrollBar::ScrollBar (Qt::Orientation o, QWidget * parent = NULL)
ScrollBar() [3/3]
ScrollBar::ScrollBar (double minBase, double maxBase, Qt::Orientation o, QWidget * parent = NULL)
References moveSlider(), setBase(), sliderMoved(), and valueChanged().
Member Function Documentation
extent()
int ScrollBar::extent () const
Referenced by ScrollZoomer::layoutScrollBars(), and ScrollZoomer::updateScrollBars().
isInverted()
bool ScrollBar::isInverted () const
Referenced by moveSlider(), and sliderRange().
mapFromTick()
double ScrollBar::mapFromTick (int tick) const protected
References sliderMoved(), sliderRange(), and valueChanged().
Referenced by sliderRange().
mapToTick()
int ScrollBar::mapToTick (double v) const protected
Referenced by moveSlider().
maxBaseValue()
double ScrollBar::maxBaseValue () const
maxSliderValue()
double ScrollBar::maxSliderValue () const
References sliderRange().
Referenced by setBase(), and setInverted().
minBaseValue()
double ScrollBar::minBaseValue () const
minSliderValue()
double ScrollBar::minSliderValue () const
References sliderRange().
Referenced by setBase(), and setInverted().
moveSlider
void ScrollBar::moveSlider (double min, double max) virtual slot
References isInverted(), and mapToTick().
Referenced by ScrollBar(), setBase(), setInverted(), and ScrollZoomer::updateScrollBars().
setBase
void ScrollBar::setBase (double min, double max) virtual slot
References maxSliderValue(), minSliderValue(), and moveSlider().
Referenced by ScrollBar(), and ScrollZoomer::updateScrollBars().
setInverted()
void ScrollBar::setInverted (bool inverted)
References maxSliderValue(), minSliderValue(), and moveSlider().
Referenced by ScrollZoomer::updateScrollBars().
sliderMoved
void ScrollBar::sliderMoved (Qt::Orientation , double , double) signal
Referenced by mapFromTick(), and ScrollBar().
sliderRange()
void ScrollBar::sliderRange (int value, double & min, double & max) const protected
References isInverted(), and mapFromTick().
Referenced by mapFromTick(), maxSliderValue(), and minSliderValue().
valueChanged
void ScrollBar::valueChanged (Qt::Orientation , double , double) signal
Referenced by mapFromTick(), and ScrollBar().
The documentation for this class was generated from the following files:
scrollbar.h
scrollbar.cpp