Cumbia communication independent controls based on Qt: NumberDelegate Class Reference
NumberDelegate Class Reference
#include <number_delegate.h>
Public Member Functions
NumberDelegate ()
virtual ~NumberDelegate ()
int integerDigits ()
int decimalDigits ()
void configureNumber (const double min, const double max, const QString &format)
decodes on the basis of the format, correcting integer and decimal digits with minimum and maximum values
bool configureNumber (const QString &format)
decodes on the basis of the format only
Protected Attributes
int d_intDigits
int d_decDigits
Constructor & Destructor Documentation
NumberDelegate()
NumberDelegate::NumberDelegate ()
References d_decDigits, and d_intDigits.
~NumberDelegate()
virtual NumberDelegate::~NumberDelegate () inline virtual
Member Function Documentation
configureNumber() [1/2]
void NumberDelegate::configureNumber (const double min, const double max, const QString & format)
decodes on the basis of the format, correcting integer and decimal digits with minimum and maximum values
References d_intDigits, and pinfo.
Referenced by decimalDigits(), QuInputOutput::onNewData(), and QuApplyNumeric::onUpdate().
configureNumber() [2/2]
bool NumberDelegate::configureNumber (const QString & format)
decodes on the basis of the format only
References d_decDigits, d_intDigits, DecIntFromFormat::decimalDefaults(), DecIntFromFormat::decode(), DecIntFromFormat::integerDefaults(), DecIntFromFormat::numDecDigits(), DecIntFromFormat::numIntDigits(), perr, and qstoc.
decimalDigits()
int NumberDelegate::decimalDigits () inline
References configureNumber(), and d_decDigits.
Referenced by QuApplyNumeric::onUpdate().
integerDigits()
int NumberDelegate::integerDigits () inline
References d_intDigits.
Referenced by QuApplyNumeric::onUpdate().
Member Data Documentation
d_decDigits
int NumberDelegate::d_decDigits protected
Referenced by configureNumber(), decimalDigits(), and NumberDelegate().
d_intDigits
int NumberDelegate::d_intDigits protected
Referenced by configureNumber(), integerDigits(), and NumberDelegate().
The documentation for this class was generated from the following files:
number_delegate.h
number_delegate.cpp