cumbia-qtcontrols: Arrow Class Reference
Arrow Class Reference
#include <quplotmarkercomponent.h>
Public Member Functions
Arrow (const QwtText &title=QwtText())
void draw (QPainter *, const QwtScaleMap &, const QwtScaleMap &, const QRectF &) const
Public Attributes
QPointF begin
QPointF end
Constructor & Destructor Documentation
Arrow()
Arrow::Arrow (const QwtText & title = QwtText()) inline
References draw().
Referenced by QuPlotMarkerComponent::name().
Member Function Documentation
draw()
void Arrow::draw (QPainter * painter, const QwtScaleMap & xMap, const QwtScaleMap & yMap, const QRectF &) const
References begin, Elettra::darkGray, end, and Elettra::lightGray.
Referenced by Arrow().
Member Data Documentation
begin
QPointF Arrow::begin
Referenced by draw(), and QuPlotMarkerComponent::update().
end
QPointF Arrow::end
Referenced by draw(), and QuPlotMarkerComponent::update().
The documentation for this class was generated from the following files:
quplotmarkercomponent.h
quplotmarkercomponent.cpp