Cumbia communication independent controls based on Qt: EPlotLight Class Reference
EPlotLight Class Reference
a plot derived from EPlotLightBase that provides easy curve management.
#include <eplotlight.h>
Public Slots
virtual void setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
Initialize data with x- and y-arrays (explicitly shared)
virtual void appendData (const QString &curveName, double x, double y)
Appends data to the curve with the given curveName, using the efficient draw() method.
virtual void appendData (const QString &curveName, double *x, double *y, int size)
Appends size data to the curve with the given curveName, using the efficient draw() method.
void setXAutoscale (bool a)
the same as setXAxisAutoscaleEnabled, provided for convenience and for backwards compatibility
void setYAutoscale (bool a)
the same as setYAxisAutoscaleEnabled, provided for convenience and for backwards compatibility
void setShowYValuesEnabled (bool show)
toggles y values visibility for each curve on the canvas.
bool showYValuesEnabled () const
returns true if Y values are shown, false otherwise.
void clearPlot ()
Clears data on the plot, removing values from the current curves.
QuPlotCurve * curve (const QString &name)
Returns the curve with the name provided.
QString curveName (QuPlotCurve *curve)
bool hasCurveIgnoreCase (const QString &name) const
Returns true if the plot has the curve with the given name, case insensitive search.
QuPlotCurve * getCurveIgnoreCase (const QString &name)
getCurveIgnoreCase returns the curve with the given name, looking for the name using a case insensitive search. This is the same as the curve method above.
Public Slots inherited from EPlotLightBase
virtual void refresh ()
refreshes the plot, taking care of the zoom state.
void setXAxisAutoscaleEnabled (bool en)
enables or disables x axis autoscale
void setYAxisAutoscaleEnabled (bool en)
enables Y axis autoscale
void extendYLowerBound (double l)
extends the lower bound of the Y axis
void extendYUpperBound (double u)
extends the upper bound of the Y axis
void setYLowerBound (double l)
changes the Y lower bound
void setYUpperBound (double u)
changes the Y upper bound
void setXLowerBound (double l)
sets x axis lower bound
void setXUpperBound (double u)
sets x axis upper bound
void setXAutoscaleAdjustment (double d)
adjusts the x axis scale bounds enlarging it of the percentage d
double xAutoscaleAdjustment ()
void setYAutoscaleAdjustment (double d)
adjusts the y axis scale bounds enlarging it of the percentage d
double yAutoscaleAdjustment ()
bool xAutoscaleAdjustEnabled ()
bool yAutoscaleAdjustEnabled ()
void setTitleOnCanvasEnabled (bool en)
void setXAutoscaleAdjustEnabled (bool a)
void setYAutoscaleAdjustEnabled (bool a)
void setCurvesStyle (CurveStyle curveStyle)
changes all the curves style
void setZoomDisabled (bool)
Enables or disables the zooming capabilities.
void getXBoundsFromCurves (double *xMin, double *xMax)
scans all curves looking for minimum and maximum values among the x values.
double getXScaleInterval (double xMin, double xMax)
returns the scale interval according to the minimum and maximum values passed.
Signals
void curveAdded (QuPlotCurve *)
This signal is emitted when a new curve is added to the plot.
void curveRemoved (QuPlotCurve *)
This signal is emitted whenever a curve is removed from the plot via removeCurve.
Public Member Functions
EPlotLight (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
EPlotLight (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
void addCurve (const QString &curveName, QuPlotCurve *curve)
Registers a new curve with the provided curveName.
void removeCurve (const QString &curveName)
Removes the specified curve from the plot, deleting it.
void setCurveStyle (const QString &curveName, QwtPlotCurve::CurveStyle)
sets a particular curve style for the specified curveName
void createAndAddCurve (const QString &curveName)
creates a curve with name curveName, adds it to the internal map of curves
void removeData ()
void setDataBufferSize (int b)
sets the data buffer size to b elements. When b is reached, data is removed from the front.
int dataBufferSize ()
returns the data buffer size.
int timeInterval () const
void setTimeInterval (int t)
bool yAutoscale ()
Public Member Functions inherited from EPlotLightBase
EPlotLightBase (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
EPlotLightBase (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
void setTimeScaleDrawEnabled (bool enable)
Enables x axis interpretation as a timestamp and produces date/time labels in the axis itself.
bool timeScaleDrawEnabled ()
bool dateOnTimeScaleDrawEnabled () const
returns true if the time scale draw writes the day on the date label
void setDateOnTimeScaleDrawEnabled (bool en)
enables or disables the date on the x axis scale draw
bool adjustScales (double percent=0.0, bool do_replot=true)
calls setAxisScale on the X and Y axis. The bounds are calculated reading the limits from all the curves and expanding both axes of a percentage.
bool adjustXScale (double percent=0.0, bool do_replot=true)
bool adjustYScale (double percent=0.0, bool do_replot=true)
bool setAxisScaleIfNeeded (int axisId, double min, double max, double step=0)
bool titleOnCanvasEnabled ()
void setAlignCanvasToScalesEnabled (bool en)
calls QwtPlotLayout::setAlignCanvasToScales
bool alignCanvasToScalesEnabled ()
bool xAxisAutoscaleEnabled ()
bool yAxisAutoscaleEnabled ()
double yUpperBound ()
double yLowerBound ()
bool xAxisLogScale ()
bool yAxisLogScale ()
void setXAxisLogScale (bool l)
void setYAxisLogScale (bool l)
double xUpperBound ()
double xLowerBound ()
bool zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
QList< QwtPlotCurve * > curves ()
Protected Slots
virtual void dataUpdated ()
Protected Slots inherited from EPlotLightBase
void displayZoomHint ()
void eraseZoomHint ()
Protected Member Functions
virtual QMenu * rightClickMenu ()
void print ()
void snapshot ()
void copyImage ()
void saveData ()
dumps the curves into a csv file.
virtual void configurePlot ()
executes the EPlotConfigurationDialog to configure the appearence of the plot.
Protected Member Functions inherited from EPlotLightBase
virtual QString plotTitle ()
returns the plot title.
virtual void drawCanvas (QPainter *p)
Properties
bool timeScaleEnabled
bool dateOnTimeScaleDrawEnabled
int dataBufferSize
Properties inherited from EPlotLightBase
bool xAxisAutoscale
bool yAxisAutoscale
bool alignCanvasToScales
double yUpperBound
double yLowerBound
double xUpperBound
double xLowerBound
bool xAutoscaleAdjustEnabled
bool yAutoscaleAdjustEnabled
double xAutoscaleAdjustment
double yAutoscaleAdjustment
bool titleOnCanvasEnabled
bool xAxisLogScale
bool yAxisLogScale
bool zoomDisabled
CurveStyle curvesStyle
Additional Inherited Members
Public Types inherited from EPlotLightBase
enum CurveStyle {
NoCurve, Lines, Sticks, Steps,
Dots, UserCurve = 100
}
Protected Attributes inherited from EPlotLightBase
Zoomer * zoomer
Detailed Description
a plot derived from EPlotLightBase that provides easy curve management.
See also
EPlotLightBase base class
EPlotLightBase::refresh() method
Constructor & Destructor Documentation
EPlotLight() [1/2]
EPlotLight::EPlotLight (QWidget * parent)
The constructor of a simple plot with zooming and scrolling capabilities.
Parameters
parent the parent widget
EPlotLight() [2/2]
EPlotLight::EPlotLight (const QwtText & title, QWidget * parent)
The constructor of a simple plot with zooming and scrolling capabilities.
Parameters
parent the parent widget
title the title of the plot
References clearPlot(), configurePlot(), copyImage(), EBLUEGRAY, KBLUE, KDARKCYAN, KDARKGREEN, KDARKMAROON, KDARKVIOLET, KMAROON, KORANGE, KRED, KVERYDARKVIOLET, KYELLOW, print(), saveData(), setShowYValuesEnabled(), and snapshot().
Member Function Documentation
addCurve()
void EPlotLight::addCurve (const QString & curveName, QuPlotCurve * curve)
Registers a new curve with the provided curveName.
Parameters
curveName the name associated to the EPlotCurve curve.
curve the pointer to the EPlotCurve to add to the plot with the given curveName.
Use addCurve() to add the curve to the plot, with the provided curveName. The curveName has to be used to appendData to the EPlotCurve when new points need to be added. If a curve already exists with curveName, then that curve is previously removed.
The method automatically chooses and sets a pen on the curve added. The style is then customizable via the right click dialog available for the plot. If you want to customize the curve pen, remember to call setPen() on the curve after calling addCurve(). A value for the alpha channel of the colour of each curve is taken from the dynamic property curvesAlphaChannel, also available as designer free property.
Important note:
It is recommended that the alpha channel is set to 255 (no transparency at all). Otherwise, a lot of CPU is required to draw curves at high refresh rates and/or with many points.
When the method ends, the curveAdded() signal is emitted, with the just added curve as parameter. On the connected slot you can change the curves appearance and style. To later change the curves style, call the curve() method with the name of the desired curve.
References curve(), curveAdded(), pinfo, and qstoc.
Referenced by createAndAddCurve().
appendData [1/2]
void EPlotLight::appendData (const QString & curveName, double x, double y) virtual slot
Appends data to the curve with the given curveName, using the efficient draw() method.
Parameters
curveName the curve name that identifies the curve you want to append data to. The curveName must be the string you assigned when you called addCurve(). It is not necessary that the curveName is the same name as the curve title provided when the curve was created.
x the x value to append to the x axis.
y the y value to append to the y axis. This method adds one x and y point to the curve with curveName, using the low level draw() method of the QwtPlotCurve, providing an efficient update of the plot.
If axis autoscale is enabled (x or y), each time you call setData() it is necessary to call refresh() to set zoom base with the correct value. Otherwise the zoom might not behave as expected. Plots such as TPlotLightMarker and derived do this for you in their refresh methods.
Referenced by yAutoscale().
appendData [2/2]
void EPlotLight::appendData (const QString & curveName, double * x, double * y, int size) virtual slot
Appends size data to the curve with the given curveName, using the efficient draw() method.
Parameters
curveName the curve name that identifies the curve you want to append data to. The curveName must be the string you assigned when you called addCurve(). It is not necessary that the curveName is the same name as the curve title provided when the curve was created.
x pointer to the x value(s) to append to the x axis.
y pointer to the y value(s) to append to the y axis.
size number of elements contained in the data pointed by x and y.
This method adds size x and y points to the curve with curveName, using the low level draw() method of the QwtPlotCurve, providing an efficient update of the plot.
If axis autoscale is enabled (x or y), each time you call setData() it is necessary to call refresh() to set zoom base with the correct value. Otherwise the zoom might not behave as expected. Plots such as TPlotLightMarker and derived do this for you in their refresh methods.
References QuPlotCurve::appendData(), QuPlotCurve::count(), createAndAddCurve(), curve(), pinfo, QuPlotCurve::popFront(), qstoc, EPlotLightBase::timeScaleDrawEnabled(), QuPlotCurve::updateRawData(), and QuPlotCurve::x().
clearPlot
void EPlotLight::clearPlot () slot
Clears data on the plot, removing values from the current curves.
Clears data on the plot, and the acquisition restarts.
References QuPlotCurve::clearData().
Referenced by EPlotLight(), and setYAutoscale().
configurePlot()
void EPlotLight::configurePlot () protected virtual
executes the EPlotConfigurationDialog to configure the appearence of the plot.
Reimplement this method in subclasses to personalize the behaviour of the configuration action, for instance using another configuration dialog, as done in QTango TRealtimePlot.
Referenced by dataUpdated(), and EPlotLight().
copyImage()
void EPlotLight::copyImage () protected
References EPlotLightBase::setTitleOnCanvasEnabled(), and EPlotLightBase::titleOnCanvasEnabled().
Referenced by dataUpdated(), and EPlotLight().
createAndAddCurve()
void EPlotLight::createAndAddCurve (const QString & curveName)
creates a curve with name curveName, adds it to the internal map of curves
Parameters
curveName the name of the curve, in most cases the tango point.
This method creates a new EPlotCurve, with name curveName. Then it calls addCurve() to add it internally to the list of curves. If the curve already exists, addCurve will remove the already existing curve.
See also
addCurve
References addCurve().
Referenced by appendData(), and setData().
curve
QuPlotCurve * EPlotLight::curve (const QString & name) slot
Returns the curve with the name provided.
Parameters
name the name of the curve you want to obtain. When using TPlotLightMarker subclass, the name of a curve is equal to the name of the tango point. A case insensitive comparison is done between name and the name of the curves.
Returns
the curve with the given name (case insensitive match), NULL if there's no curve with that name.
References getCurveIgnoreCase(), and hasCurveIgnoreCase().
Referenced by addCurve(), appendData(), removeCurve(), setData(), and setYAutoscale().
curveAdded
void EPlotLight::curveAdded (QuPlotCurve *) signal
This signal is emitted when a new curve is added to the plot.
This signal can be useful when you want to catch the creation and adding of a new curve to the plot. You can then modify the characteristics of the curve right after it is added to the plot.
Referenced by addCurve(), and setYAutoscale().
curveName
QString EPlotLight::curveName (QuPlotCurve * curve) slot
Referenced by setYAutoscale(), and yAutoscale().
curveRemoved
void EPlotLight::curveRemoved (QuPlotCurve *) signal
This signal is emitted whenever a curve is removed from the plot via removeCurve.
When a curve is detached from the plot, in the removeCurve() method, this signal is emitted. Right after the signal is emitted, the curve is deleted. So be sure that you connect this signal via a Qt::DirectConnection to your slot.
Referenced by removeCurve(), and setYAutoscale().
dataBufferSize()
int EPlotLight::dataBufferSize () inline
returns the data buffer size.
Returns
the number of elements of the underlying data size.
References setTimeInterval(), and timeInterval().
dataUpdated
virtual void EPlotLight::dataUpdated () inline protected virtual slot
References configurePlot(), copyImage(), print(), saveData(), and snapshot().
getCurveIgnoreCase
QuPlotCurve * EPlotLight::getCurveIgnoreCase (const QString & name) slot
getCurveIgnoreCase returns the curve with the given name, looking for the name using a case insensitive search. This is the same as the curve method above.
Parameters
name the name of the curve to look for
Returns
the curve with the given name, NULL if no curve in the plot has the given name.
Referenced by curve(), and setYAutoscale().
hasCurveIgnoreCase
bool EPlotLight::hasCurveIgnoreCase (const QString & name) const slot
Returns true if the plot has the curve with the given name, case insensitive search.
Returns
true if the plot has the curve with the provided name (case insensitive comparison) false otherwise.
Referenced by curve(), and setYAutoscale().
print()
void EPlotLight::print () protected
Referenced by dataUpdated(), and EPlotLight().
removeCurve()
void EPlotLight::removeCurve (const QString & curveName)
Removes the specified curve from the plot, deleting it.
Parameters
curveName the name of the curve you want to remove.
References curve(), curveRemoved(), perr, pinfo, and qstoc.
removeData()
void EPlotLight::removeData ()
rightClickMenu()
virtual QMenu* EPlotLight::rightClickMenu () inline protected virtual
saveData()
void EPlotLight::saveData () protected
dumps the curves into a csv file.
The columns are in the form xAxisValues1, yAxisValues1, ... xAxisValuesN, yAxisValuesN.
References EPlotLightBase::timeScaleDrawEnabled().
Referenced by dataUpdated(), and EPlotLight().
setCurveStyle()
void EPlotLight::setCurveStyle (const QString & curveName, QwtPlotCurve::CurveStyle style)
sets a particular curve style for the specified curveName
Parameters
curveName the name of the curve you want to change the style to
style the CurveStyle (NoCurve, Lines, Sticks, Steps, Dots, UserCurve) you want to apply to the curve curveName. Should you want to change the style of all the curves in the plot in one shot, consider using EPlotLightBase::setCurvesStyle().
References perr, and qstoc.
setData
void EPlotLight::setData (const QString & curveName, const QVector< double > & xData, const QVector< double > & yData) virtual slot
Initialize data with x- and y-arrays (explicitly shared)
Parameters
curveName the name of the curve you want to set data on
xData x array of data to set on the curve
yData y array of data to set on the curve
Calls QwtPlotCurve's setData() on the curve having the specified name.
If axis autoscale is enabled (x or y), each time you call setData() it is necessary to call refresh() to set zoom base with the correct value. Otherwise the zoom might not behave as expected. Plots such as TPlotLightMarker and derived do this for you in their refresh methods.
References createAndAddCurve(), curve(), pinfo, qstoc, and QuPlotCurve::setData().
Referenced by yAutoscale().
setDataBufferSize()
void EPlotLight::setDataBufferSize (int b)
sets the data buffer size to b elements. When b is reached, data is removed from the front.
Parameters
b the maximum size of the underlying data .
For each curve of the plot, sets the buffer size of the data linked to the curve. This puts a limit on the memory used by the plot.
setShowYValuesEnabled
void EPlotLight::setShowYValuesEnabled (bool show) slot
toggles y values visibility for each curve on the canvas.
Parameters
show true y values are shown on each curve
show false y values are not shown (the default)
Note: this looks for all current curves in the plot and applies the showYValuesEnabled on each of them. Curves that will be created later need to be manually updated with this method.
Referenced by EPlotLight(), and setYAutoscale().
setTimeInterval()
void EPlotLight::setTimeInterval (int t)
Referenced by dataBufferSize().
setXAutoscale
void EPlotLight::setXAutoscale (bool a) inline slot
the same as setXAxisAutoscaleEnabled, provided for convenience and for backwards compatibility
References EPlotLightBase::setXAxisAutoscaleEnabled().
setYAutoscale
void EPlotLight::setYAutoscale (bool a) inline slot
the same as setYAxisAutoscaleEnabled, provided for convenience and for backwards compatibility
References clearPlot(), curve(), curveAdded(), curveName(), curveRemoved(), getCurveIgnoreCase(), hasCurveIgnoreCase(), setShowYValuesEnabled(), EPlotLightBase::setYAxisAutoscaleEnabled(), and showYValuesEnabled().
showYValuesEnabled
bool EPlotLight::showYValuesEnabled () const slot
returns true if Y values are shown, false otherwise.
See also
setShowYValuesEnabled
Referenced by setYAutoscale().
snapshot()
void EPlotLight::snapshot () protected
References EPlotLightBase::setTitleOnCanvasEnabled(), and EPlotLightBase::titleOnCanvasEnabled().
Referenced by dataUpdated(), and EPlotLight().
timeInterval()
int EPlotLight::timeInterval () const
Referenced by dataBufferSize().
yAutoscale()
bool EPlotLight::yAutoscale () inline
References appendData(), curveName(), and setData().
Property Documentation
dataBufferSize
int EPlotLight::dataBufferSize read write
dateOnTimeScaleDrawEnabled
bool EPlotLight::dateOnTimeScaleDrawEnabled read write
timeScaleEnabled
bool EPlotLight::timeScaleEnabled read
The documentation for this class was generated from the following files:
eplotlight.h
eplotlight.cpp