cumbia-qtcontrols: EPlotConfigurationWidget Class Reference
EPlotConfigurationWidget Class Reference
#include <eplot_configuration_widget.h>
Signals
void xAxisAutoscaleEnabled (bool)
void yAxisAutoscaleEnabled (bool)
void yUpperBound (double)
void xUpperBound (double)
void xLowerBound (double)
void yLowerBound (double)
void xAutoscaleAdjustEnabled (bool)
void yAutoscaleAdjustEnabled (bool)
void yAutoscaleAdjustment (double)
void xAutoscaleAdjustment (double)
Public Member Functions
EPlotConfigurationWidget (QWidget *parent)
virtual ~EPlotConfigurationWidget ()
Protected Slots
void xAdjustmentChanged ()
void yAdjustmentChanged ()
void curveStyleChanged ()
void curveSelectionChanged (int)
void writeProperty (const QString &name, const QVariant &val)
void editCurveColor ()
void propertyChanged ()
void saveStyles ()
void apply ()
void restoreYScaleDefault ()
Constructor & Destructor Documentation
EPlotConfigurationWidget()
EPlotConfigurationWidget::EPlotConfigurationWidget (QWidget * parent)
~EPlotConfigurationWidget()
EPlotConfigurationWidget::~EPlotConfigurationWidget () virtual
References apply(), QuPlotBase::curves(), curveSelectionChanged(), editCurveColor(), propertyChanged(), restoreYScaleDefault(), saveStyles(), xAdjustmentChanged(), and yAdjustmentChanged().
Member Function Documentation
apply
void EPlotConfigurationWidget::apply () protected slot
References curveStyleChanged(), QuPlotBase::setDataBufferSize(), QuPlotBase::setXAxisAutoscaleEnabled(), QuPlotBase::setYAxisAutoscaleEnabled(), and writeProperty().
Referenced by ~EPlotConfigurationWidget().
curveSelectionChanged
void EPlotConfigurationWidget::curveSelectionChanged (int) protected slot
References QuPlotBase::curves().
Referenced by ~EPlotConfigurationWidget().
curveStyleChanged
void EPlotConfigurationWidget::curveStyleChanged () protected slot
References QuPlotBase::curve(), perr, qstoc, RTTI_CURVE_OFFSET, and QuPlotBase::setCurveStyle().
Referenced by apply().
editCurveColor
void EPlotConfigurationWidget::editCurveColor () protected slot
Referenced by ~EPlotConfigurationWidget().
propertyChanged
void EPlotConfigurationWidget::propertyChanged () protected slot
Referenced by ~EPlotConfigurationWidget().
restoreYScaleDefault
void EPlotConfigurationWidget::restoreYScaleDefault () protected slot
Referenced by ~EPlotConfigurationWidget().
saveStyles
void EPlotConfigurationWidget::saveStyles () protected slot
References QuPlotBase::curve(), and RTTI_CURVE_OFFSET.
Referenced by ~EPlotConfigurationWidget().
writeProperty
void EPlotConfigurationWidget::writeProperty (const QString & name, const QVariant & val) protected slot
References perr, and qstoc.
Referenced by apply().
xAdjustmentChanged
void EPlotConfigurationWidget::xAdjustmentChanged () protected slot
Referenced by ~EPlotConfigurationWidget().
xAutoscaleAdjustEnabled
void EPlotConfigurationWidget::xAutoscaleAdjustEnabled (bool) signal
xAutoscaleAdjustment
void EPlotConfigurationWidget::xAutoscaleAdjustment (double) signal
xAxisAutoscaleEnabled
void EPlotConfigurationWidget::xAxisAutoscaleEnabled (bool) signal
xLowerBound
void EPlotConfigurationWidget::xLowerBound (double) signal
xUpperBound
void EPlotConfigurationWidget::xUpperBound (double) signal
yAdjustmentChanged
void EPlotConfigurationWidget::yAdjustmentChanged () protected slot
References pwarn, and qstoc.
Referenced by ~EPlotConfigurationWidget().
yAutoscaleAdjustEnabled
void EPlotConfigurationWidget::yAutoscaleAdjustEnabled (bool) signal
yAutoscaleAdjustment
void EPlotConfigurationWidget::yAutoscaleAdjustment (double) signal
yAxisAutoscaleEnabled
void EPlotConfigurationWidget::yAxisAutoscaleEnabled (bool) signal
yLowerBound
void EPlotConfigurationWidget::yLowerBound (double) signal
yUpperBound
void EPlotConfigurationWidget::yUpperBound (double) signal
The documentation for this class was generated from the following files:
eplot_configuration_widget.h
eplot_configuration_widget.cpp