Cumbia communication independent controls based on Qt: ImageMouseEventInterface Class Reference
ImageMouseEventInterface Class Reference abstract
#include <eimagemouseeventinterface.h>
Public Member Functions
ImageMouseEventInterface ()
virtual void imageMousePressEvent (const QPoint &pos, int button)=0
virtual void imageMouseReleaseEvent (const QPoint &pos, int button)=0
virtual void imageMouseMoveEvent (const QPoint &pos, int button)=0
Constructor & Destructor Documentation
ImageMouseEventInterface()
ImageMouseEventInterface::ImageMouseEventInterface ()
Member Function Documentation
imageMouseMoveEvent()
virtual void ImageMouseEventInterface::imageMouseMoveEvent (const QPoint & pos, int button) pure virtual
Referenced by EImageWidgetBase::mouseMove().
imageMousePressEvent()
virtual void ImageMouseEventInterface::imageMousePressEvent (const QPoint & pos, int button) pure virtual
Referenced by EImageWidgetBase::mousePress().
imageMouseReleaseEvent()
virtual void ImageMouseEventInterface::imageMouseReleaseEvent (const QPoint & pos, int button) pure virtual
Referenced by EImageWidgetBase::mouseRelease().
The documentation for this class was generated from the following files:
eimagemouseeventinterface.h
eimagemouseeventinterface.cpp