Cumbia communication independent controls based on Qt: PlotSnapshot Class Reference
PlotSnapshot Class Reference
#include <snapshot.h>
Public Member Functions
PlotSnapshot ()
void copy (QWidget *w)
bool grab (QWidget *w)
Constructor & Destructor Documentation
PlotSnapshot()
PlotSnapshot::PlotSnapshot () inline
References copy(), and grab().
Member Function Documentation
copy()
void PlotSnapshot::copy (QWidget * w)
Referenced by QuPlotContextMenuComponent::copyImage(), EPlotLight::copyImage(), and PlotSnapshot().
grab()
bool PlotSnapshot::grab (QWidget * w)
Referenced by PlotSnapshot(), QuPlotContextMenuComponent::snapshot(), and EPlotLight::snapshot().
The documentation for this class was generated from the following files:
snapshot.h
snapshot.cpp