cumbia-qtcontrols: IntDelegate Class Reference
IntDelegate Class Reference abstract
#include <int_delegate.h>
Public Member Functions
IntDelegate ()
virtual ~IntDelegate ()
virtual void setValue (int)=0
virtual void setMinimum (int)=0
virtual void setMaximum (int)=0
Constructor & Destructor Documentation
IntDelegate()
IntDelegate::IntDelegate () inline
~IntDelegate()
virtual IntDelegate::~IntDelegate () inline virtual
References setMaximum(), setMinimum(), and setValue().
Member Function Documentation
setMaximum()
virtual void IntDelegate::setMaximum (int) pure virtual
Referenced by ~IntDelegate().
setMinimum()
virtual void IntDelegate::setMinimum (int) pure virtual
Referenced by ~IntDelegate().
setValue()
virtual void IntDelegate::setValue (int) pure virtual
Referenced by ~IntDelegate().
The documentation for this class was generated from the following file:
int_delegate.h