cumbia-qtcontrols: Ui_Quinputoutput Class Reference
Ui_Quinputoutput Class Reference
#include <ui_quinputoutput.h>
Public Member Functions
void setupUi (QWidget *Quinputoutput, CumbiaTango *cu_t, const CuTReaderFactory &cu_tango_r_fac, const CuTWriterFactory &cu_tango_w_fac)
void retranslateUi (QWidget *Quinputoutput)
Member Function Documentation
retranslateUi()
void Ui_Quinputoutput::retranslateUi (QWidget * Quinputoutput) inline
Referenced by setupUi().
setupUi()
void Ui_Quinputoutput::setupUi (QWidget * Quinputoutput, CumbiaTango * cu_t, const CuTReaderFactory & cu_tango_r_fac, const CuTWriterFactory & cu_tango_w_fac) inline
References retranslateUi().
Referenced by Quinputoutput::Quinputoutput().
The documentation for this class was generated from the following file:
ui_quinputoutput.h