cumbia-qtcontrols: QuChartConfDialog Class Reference
QuChartConfDialog Class Reference
#include <quchartconfdialog.h>
Public Slots
void applyClicked ()
Signals
void curveAxisChanged (const QString &curve, const QString &axname)
Public Member Functions
QuChartConfDialog (QWidget *parent)
virtual ~QuChartConfDialog ()
void addCurve (QAbstractSeries *s)
Constructor & Destructor Documentation
QuChartConfDialog()
QuChartConfDialog::QuChartConfDialog (QWidget * parent)
~QuChartConfDialog()
QuChartConfDialog::~QuChartConfDialog () virtual
References pdelete.
Member Function Documentation
addCurve()
void QuChartConfDialog::addCurve (QAbstractSeries * s)
References applyClicked().
Referenced by QuSpectrumPlot::onCalloutClicked(), and QuTrendPlot::onCalloutClicked().
applyClicked
void QuChartConfDialog::applyClicked () slot
References curveAxisChanged().
Referenced by addCurve().
curveAxisChanged
void QuChartConfDialog::curveAxisChanged (const QString & curve, const QString & axname) signal
Referenced by applyClicked().
The documentation for this class was generated from the following files:
quchartconfdialog.h
quchartconfdialog.cpp