Cumbia communication independent controls based on Qt: EApplyButton Class Reference
EApplyButton Class Reference
a button to apply a setting
#include <eapplybutton.h>
Public Slots
void valueModified (double)
void clearModified ()
Public Member Functions
EApplyButton (QWidget *parent)
~EApplyButton ()
bool isModified ()
Detailed Description
a button to apply a setting
this is a simple button used to apply a setting, it has to slots that allows the developer to change the color of the displayed text: valueModified sets the color to red and clearModified reverts to the original setting
Constructor & Destructor Documentation
EApplyButton()
EApplyButton::EApplyButton (QWidget * parent)
References clearModified(), and MIN_BUTTON_SIZE.
~EApplyButton()
EApplyButton::~EApplyButton () inline
Member Function Documentation
clearModified
void EApplyButton::clearModified () slot
resets font color to black
Referenced by EApplyNumeric::clearModified(), EApplyButton(), and isModified().
isModified()
bool EApplyButton::isModified () inline
References clearModified(), and valueModified().
Referenced by EApplyNumeric::isModified().
valueModified
void EApplyButton::valueModified (double) slot
tell the widget that the value to which it's associated has changed, so the color of the font changes to red
References Elettra::red.
Referenced by isModified(), and EApplyNumeric::minimumSizeHint().
The documentation for this class was generated from the following files:
eapplybutton.h
eapplybutton.cpp