Cumbia communication independent controls based on Qt: EPlotLightBase Class Reference
EPlotLightBase Class Reference
A simple plot with zooming and scrolling capabilities.
#include <eplotlight_base.h>
Public Types
enum CurveStyle {
NoCurve, Lines, Sticks, Steps,
Dots, UserCurve = 100
}
Public Slots
virtual void refresh ()
refreshes the plot, taking care of the zoom state.
void setXAxisAutoscaleEnabled (bool en)
enables or disables x axis autoscale
void setYAxisAutoscaleEnabled (bool en)
enables Y axis autoscale
void extendYLowerBound (double l)
extends the lower bound of the Y axis
void extendYUpperBound (double u)
extends the upper bound of the Y axis
void setYLowerBound (double l)
changes the Y lower bound
void setYUpperBound (double u)
changes the Y upper bound
void setXLowerBound (double l)
sets x axis lower bound
void setXUpperBound (double u)
sets x axis upper bound
void setXAutoscaleAdjustment (double d)
adjusts the x axis scale bounds enlarging it of the percentage d
double xAutoscaleAdjustment ()
void setYAutoscaleAdjustment (double d)
adjusts the y axis scale bounds enlarging it of the percentage d
double yAutoscaleAdjustment ()
bool xAutoscaleAdjustEnabled ()
bool yAutoscaleAdjustEnabled ()
void setTitleOnCanvasEnabled (bool en)
void setXAutoscaleAdjustEnabled (bool a)
void setYAutoscaleAdjustEnabled (bool a)
void setCurvesStyle (CurveStyle curveStyle)
changes all the curves style
void setZoomDisabled (bool)
Enables or disables the zooming capabilities.
void getXBoundsFromCurves (double *xMin, double *xMax)
scans all curves looking for minimum and maximum values among the x values.
double getXScaleInterval (double xMin, double xMax)
returns the scale interval according to the minimum and maximum values passed.
Public Member Functions
EPlotLightBase (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
EPlotLightBase (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
void setTimeScaleDrawEnabled (bool enable)
Enables x axis interpretation as a timestamp and produces date/time labels in the axis itself.
bool timeScaleDrawEnabled ()
bool dateOnTimeScaleDrawEnabled () const
returns true if the time scale draw writes the day on the date label
void setDateOnTimeScaleDrawEnabled (bool en)
enables or disables the date on the x axis scale draw
bool adjustScales (double percent=0.0, bool do_replot=true)
calls setAxisScale on the X and Y axis. The bounds are calculated reading the limits from all the curves and expanding both axes of a percentage.
bool adjustXScale (double percent=0.0, bool do_replot=true)
bool adjustYScale (double percent=0.0, bool do_replot=true)
bool setAxisScaleIfNeeded (int axisId, double min, double max, double step=0)
bool titleOnCanvasEnabled ()
void setAlignCanvasToScalesEnabled (bool en)
calls QwtPlotLayout::setAlignCanvasToScales
bool alignCanvasToScalesEnabled ()
bool xAxisAutoscaleEnabled ()
bool yAxisAutoscaleEnabled ()
double yUpperBound ()
double yLowerBound ()
bool xAxisLogScale ()
bool yAxisLogScale ()
void setXAxisLogScale (bool l)
void setYAxisLogScale (bool l)
double xUpperBound ()
double xLowerBound ()
bool zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
QList< QwtPlotCurve * > curves ()
Protected Slots
void displayZoomHint ()
void eraseZoomHint ()
Protected Member Functions
virtual QString plotTitle ()
returns the plot title.
virtual void drawCanvas (QPainter *p)
Protected Attributes
Zoomer * zoomer
Properties
bool xAxisAutoscale
bool yAxisAutoscale
bool alignCanvasToScales
double yUpperBound
double yLowerBound
double xUpperBound
double xLowerBound
bool xAutoscaleAdjustEnabled
bool yAutoscaleAdjustEnabled
double xAutoscaleAdjustment
double yAutoscaleAdjustment
bool titleOnCanvasEnabled
bool xAxisLogScale
bool yAxisLogScale
bool zoomDisabled
CurveStyle curvesStyle
Detailed Description
A simple plot with zooming and scrolling capabilities.
This class provides a simple plot able to zoom and scroll the curves. It should be used with the EPlotCurve as curves to take advantage of the zooming features. You might want to look at the refresh() method to learn how zoom works.
EPlotLightBase - based plots only manage an Y left and X bottom axes. Should you need other features, you have to use QwtPlot interface in order to add scales other than xBottom and yLeft.
X axis scaling
X axis scaling is managed internally by EPlotLightBase. This means that you should use EPlotLightBase methods to correctly manage x axis autoscaling. Remember that when you manually set either the upper and/or lower bounds of the x scale, x axis autoscale is disabled. The X axis lower and upper bounds will remain fixed to the values provided. Zoom scrolling is disabled in that scenario.
Y axis scaling
Since Y axis scaling does not affect the zoom behaviour, Y axis autoscaling is managed through QwtPlot setAxisAutoscale() and setAxisScale().
See also
setYLowerBound()
setYUpperBound()
setXLowerBound()
setXUpperBound()
The methods above disable x axis autoscale. To enable it again, you have to call setXAxisAutoscale(true).
Member Enumeration Documentation
CurveStyle
enum EPlotLightBase::CurveStyle
Enumerator
NoCurve
Lines
Sticks
Steps
Dots
UserCurve
Constructor & Destructor Documentation
EPlotLightBase() [1/2]
EPlotLightBase::EPlotLightBase (QWidget * parent)
The constructor of a simple plot with zooming and scrolling capabilities.
Parameters
parent the parent widget
EPlotLightBase() [2/2]
EPlotLightBase::EPlotLightBase (const QwtText & title, QWidget * parent)
The constructor of a simple plot with zooming and scrolling capabilities.
Parameters
parent the parent widget
title the title of the plot
References EPlotLightBasePrivate::curvesStyle, EPlotLightBasePrivate::displayZoomHint, displayZoomHint(), eraseZoomHint(), KDARKGRAY, KGRAY, Lines, EPlotLightBasePrivate::scheduleAdjustScales, setTimeScaleDrawEnabled(), EPlotLightBasePrivate::timeScaleDraw, EPlotLightBasePrivate::titleOnCanvasEnabled, Elettra::white, EPlotLightBasePrivate::xAutoscale, EPlotLightBasePrivate::xAutoscaleAdjustEnabled, EPlotLightBasePrivate::xAutoscaleAdjustment, EPlotLightBasePrivate::yAutoscale, EPlotLightBasePrivate::yAutoscaleAdjustEnabled, EPlotLightBasePrivate::yAutoscaleAdjustment, and zoomer.
Member Function Documentation
adjustScales()
bool EPlotLightBase::adjustScales (double percent = 0.0, bool do_replot = true)
calls setAxisScale on the X and Y axis. The bounds are calculated reading the limits from all the curves and expanding both axes of a percentage.
This method takes all curves, calculates the minimum and maximum values of all the x and y values, then calculates the x and y interval and expands them of the given percentage. replot() is not called at the end.
Parameters
percent the percentage by which the x and y axes will be expanded.
Returns
true if the operation succeeds false if the curve size is 0 or 1 (cannot determine max x and y values)
References adjustXScale(), and adjustYScale().
Referenced by refresh().
adjustXScale()
bool EPlotLightBase::adjustXScale (double percent = 0.0, bool do_replot = true)
References cuprintf, curves(), RTTI_CURVE_OFFSET, TIME_SCALE_LOOKAHEAD, timeScaleDrawEnabled(), xLowerBound(), xUpperBound(), and zoomer.
Referenced by adjustScales(), and refresh().
adjustYScale()
bool EPlotLightBase::adjustYScale (double percent = 0.0, bool do_replot = true)
References cuprintf, curves(), yLowerBound(), yUpperBound(), and zoomer.
Referenced by adjustScales(), and refresh().
alignCanvasToScalesEnabled()
bool EPlotLightBase::alignCanvasToScalesEnabled ()
curves()
QList< QwtPlotCurve * > EPlotLightBase::curves ()
References RTTI_CURVE_OFFSET.
Referenced by adjustXScale(), adjustYScale(), drawCanvas(), getXBoundsFromCurves(), EPlotLightMarker::intersectingCurves(), EPlotLightMarker::refresh(), refresh(), and setCurvesStyle().
dateOnTimeScaleDrawEnabled()
bool EPlotLightBase::dateOnTimeScaleDrawEnabled () const
returns true if the time scale draw writes the day on the date label
displayZoomHint
void EPlotLightBase::displayZoomHint () protected slot
References EPlotLightBasePrivate::displayZoomHint.
Referenced by EPlotLightBase().
drawCanvas()
void EPlotLightBase::drawCanvas (QPainter * p) protected virtual
updates the title on the canvas
References curves(), EPlotLightBasePrivate::displayZoomHint, KDARKGRAY, KDARKGREEN, EPlotLightBasePrivate::titleOnCanvasEnabled, and zoomDisabled().
eraseZoomHint
void EPlotLightBase::eraseZoomHint () protected slot
References EPlotLightBasePrivate::displayZoomHint, and zoomDisabled().
Referenced by EPlotLightBase().
extendYLowerBound
void EPlotLightBase::extendYLowerBound (double l) slot
extends the lower bound of the Y axis
Disables Y axis autoscale on the plot.
References EPlotLightBasePrivate::yAutoscale, and zoomer.
extendYUpperBound
void EPlotLightBase::extendYUpperBound (double u) slot
extends the upper bound of the Y axis
Disables Y axis autoscale on the plot.
References EPlotLightBasePrivate::yAutoscale, and zoomer.
getXBoundsFromCurves
void EPlotLightBase::getXBoundsFromCurves (double * xMin, double * xMax) slot
scans all curves looking for minimum and maximum values among the x values.
scans all curves data and stores in the xMin and xMax pointers the smallest value and the greatest value from all curves. This can be used to retrieve the scale interval via the getScaleInterval method call.
References curves().
getXScaleInterval
double EPlotLightBase::getXScaleInterval (double xMin, double xMax) slot
returns the scale interval according to the minimum and maximum values passed.
If the property xAutoscaleAdjustmentEnabled is true, the interval returned is enlarged according to the value of the property xAutoscaleAdjustment.
If xMax < xMin, -1 is returned.
References EPlotLightBasePrivate::xAutoscaleAdjustEnabled, and EPlotLightBasePrivate::yAutoscaleAdjustment.
plotTitle()
virtual QString EPlotLightBase::plotTitle () inline protected virtual
returns the plot title.
This is called if titleOnCanvasEnabled is true. Subclasses must reimplement this method to provide a title drawn on the plot canvas. For an example, see TPlotLightMarker reimplementation. This default implementation provides no title.
refresh
void EPlotLightBase::refresh () virtual slot
refreshes the plot, taking care of the zoom state.
The default behaviour of the refresh method depends on the setData method of the EPlotCurves:
a. data on the EPlotCurve is refreshed adding only one element at a time (via EPlotCurve::appendData() or via EPlotLight::appendData()):
when zoomed, the zoom rectangle is moved by an offset equal to the delta value between the curve last x value and the second last x value, so that the zoom scrolls when data is updated.
b. data on the EPlotCurve is refreshed by passing an x and y vector each time:
it is assumed that the size of the vectors passed remains constant over time and so the zoom rectangle is not scrolled.
Note
If the curves in the plot are not of type EPlotCurve, then the zoom is never scrolled (case a).
You can reimplement the refresh method if you want to give a different behaviour to your plot.
See also
EPlotLight::setData()
EPlotLight::appendData()
EPlotLightBase::refresh()
never getting inside here
References adjustScales(), adjustXScale(), adjustYScale(), cuprintf, curves(), qstoc, RTTI_CURVE_OFFSET, EPlotLightBasePrivate::scheduleAdjustScales, setAxisScaleIfNeeded(), EPlotLightBasePrivate::xAutoscale, EPlotLightBasePrivate::xAutoscaleAdjustEnabled, EPlotLightBasePrivate::xAutoscaleAdjustment, EPlotLightBasePrivate::yAutoscale, EPlotLightBasePrivate::yAutoscaleAdjustEnabled, EPlotLightBasePrivate::yAutoscaleAdjustment, and zoomer.
Referenced by EPlotLightMarker::refresh().
setAlignCanvasToScalesEnabled()
void EPlotLightBase::setAlignCanvasToScalesEnabled (bool en)
calls QwtPlotLayout::setAlignCanvasToScales
Aligns the plot canvas to the axis scales. By default it is disabled.
setAxisScaleIfNeeded()
bool EPlotLightBase::setAxisScaleIfNeeded (int axisId, double min, double max, double step = 0)
References EPlotLightBasePrivate::curvesStyle, curvesStyle, EPlotLightBasePrivate::titleOnCanvasEnabled, titleOnCanvasEnabled(), xLowerBound(), xUpperBound(), yLowerBound(), and yUpperBound().
Referenced by refresh().
setCurvesStyle
void EPlotLightBase::setCurvesStyle (CurveStyle curveStyle) slot
changes all the curves style
Parameters
curveStyle is taken from Qwt curve styles.
References curves(), and EPlotLightBasePrivate::curvesStyle.
setDateOnTimeScaleDrawEnabled()
void EPlotLightBase::setDateOnTimeScaleDrawEnabled (bool en)
enables or disables the date on the x axis scale draw
Parameters
en true the day is shown on the scale draw.
en false only the time is displayed on the scale.
References EPlotLightBasePrivate::timeScaleDraw.
setTimeScaleDrawEnabled()
void EPlotLightBase::setTimeScaleDrawEnabled (bool enable)
Enables x axis interpretation as a timestamp and produces date/time labels in the axis itself.
Parameters
enable enables date/time interpretation if true.
References EPlotLightBasePrivate::timeScaleDraw, and zoomer.
Referenced by EPlotLightBase().
setTitleOnCanvasEnabled
void EPlotLightBase::setTitleOnCanvasEnabled (bool en) slot
References EPlotLightBasePrivate::titleOnCanvasEnabled.
Referenced by EPlotLight::copyImage(), and EPlotLight::snapshot().
setXAutoscaleAdjustEnabled
void EPlotLightBase::setXAutoscaleAdjustEnabled (bool a) slot
References EPlotLightBasePrivate::xAutoscaleAdjustEnabled.
setXAutoscaleAdjustment
void EPlotLightBase::setXAutoscaleAdjustment (double d) slot
adjusts the x axis scale bounds enlarging it of the percentage d
if d is different from 0.0, then at refresh time the scales are adjusted according to the value of d. Note: inside the refresh() method, this is called for the x axis if and only if xAxisAutoscale is enabled, and for the y axis if and only if the yAxisAutoscale is enabled. You are free to call it wherever in your code to adjust the scales.
References EPlotLightBasePrivate::xAutoscaleAdjustment, and xAutoscaleAdjustment().
setXAxisAutoscaleEnabled
void EPlotLightBase::setXAxisAutoscaleEnabled (bool en) slot
enables or disables x axis autoscale
This is internally managed by EPlotLightBase and you need to call EPlotLightBase::refresh() to correctly replot the graph after you update the curve data.
References EPlotLightBasePrivate::xAutoscale, and zoomer.
Referenced by EPlotLight::setXAutoscale().
setXAxisLogScale()
void EPlotLightBase::setXAxisLogScale (bool l)
setXLowerBound
void EPlotLightBase::setXLowerBound (double l) slot
sets x axis lower bound
NOTE that it disables x axis autoscale. You might consider setting also x upper bound
See also
setXUpperBound
References EPlotLightBasePrivate::xAutoscale, and zoomer.
setXUpperBound
void EPlotLightBase::setXUpperBound (double u) slot
sets x axis upper bound
NOTE that it disables x axis autoscale. You might consider setting also x lower bound
See also
setXLowerBound
References EPlotLightBasePrivate::xAutoscale, and zoomer.
setYAutoscaleAdjustEnabled
void EPlotLightBase::setYAutoscaleAdjustEnabled (bool a) slot
References EPlotLightBasePrivate::yAutoscaleAdjustEnabled.
setYAutoscaleAdjustment
void EPlotLightBase::setYAutoscaleAdjustment (double d) slot
adjusts the y axis scale bounds enlarging it of the percentage d
if yAutoscaleAdjustEnabled is true, then at refresh time the scales are adjusted according to the value of d. Note: inside the refresh() method, this is called for the x axis if and only if xAxisAutoscale is enabled, and for the y axis if and only if the yAxisAutoscale is enabled. You are free to call it wherever in your code to adjust the scales.
See also
setXAutoscaleAdjustEnabled
setYAutoscaleAdjustEnabled
References EPlotLightBasePrivate::xAutoscaleAdjustEnabled, xAutoscaleAdjustEnabled(), xAxisLogScale(), EPlotLightBasePrivate::yAutoscaleAdjustEnabled, yAutoscaleAdjustEnabled(), EPlotLightBasePrivate::yAutoscaleAdjustment, yAutoscaleAdjustment(), and yAxisLogScale().
setYAxisAutoscaleEnabled
void EPlotLightBase::setYAxisAutoscaleEnabled (bool en) slot
enables Y axis autoscale
Parameters
en true calls directly QwtPlot::setAxisAutoscale(QwtPlot::yLeft), letting QwtPlot manage the y axis scale.
en false simply takes the current lower and upper bounds and sets the scales via QwtPlot::setAxisScale() passing to the method the current bounds. You might want to call setYLowerBound and setYUpperBound then. As a valid alternative, call setYLowerBound and setYUpperBound to disable y axis autoscale and set their values at once. Moreover, you can directly use the QwtPlot::setAxisScale(QwtPlot::yLeft, min, max) to change the scales at once. This method is provided for convenience mostly to enable the y axis autoscale.
See also
extendYLowerBound
extendYUpperBound
setYUpperBound
setYLowerBound
References EPlotLightBasePrivate::yAutoscale, yLowerBound(), yUpperBound(), and zoomer.
Referenced by EPlotLight::setYAutoscale().
setYAxisLogScale()
void EPlotLightBase::setYAxisLogScale (bool l)
setYLowerBound
void EPlotLightBase::setYLowerBound (double l) slot
changes the Y lower bound
brings the y lower bound to the value l. Disables Y autoscale.
References EPlotLightBasePrivate::yAutoscale, and zoomer.
setYUpperBound
void EPlotLightBase::setYUpperBound (double u) slot
changes the Y upper bound
brings the y upper bound to the value l. Disables Y autoscale.
References xLowerBound(), xUpperBound(), EPlotLightBasePrivate::yAutoscale, and zoomer.
setZoomDisabled
void EPlotLightBase::setZoomDisabled (bool disable) slot
Enables or disables the zooming capabilities.
Zoom is always enabled in EPlotLight classes. To disable it, call this method with a true parameter. It will install an event filter on the shift-click event.
References pinfo.
timeScaleDrawEnabled()
bool EPlotLightBase::timeScaleDrawEnabled ()
Returns
time scale interpretation in the x axis
References zoomer.
Referenced by adjustXScale(), EPlotLight::appendData(), and EPlotLight::saveData().
titleOnCanvasEnabled()
bool EPlotLightBase::titleOnCanvasEnabled ()
Referenced by EPlotLight::copyImage(), setAxisScaleIfNeeded(), and EPlotLight::snapshot().
xAutoscaleAdjustEnabled
bool EPlotLightBase::xAutoscaleAdjustEnabled () slot
Referenced by setYAutoscaleAdjustment().
xAutoscaleAdjustment
double EPlotLightBase::xAutoscaleAdjustment () slot
Referenced by setXAutoscaleAdjustment().
xAxisAutoscaleEnabled()
bool EPlotLightBase::xAxisAutoscaleEnabled ()
References EPlotLightBasePrivate::xAutoscale.
xAxisLogScale()
bool EPlotLightBase::xAxisLogScale ()
Referenced by setYAutoscaleAdjustment().
xLowerBound()
double EPlotLightBase::xLowerBound ()
Referenced by adjustXScale(), setAxisScaleIfNeeded(), setYUpperBound(), and EPlotLightMarker::updateLabel().
xUpperBound()
double EPlotLightBase::xUpperBound ()
Referenced by adjustXScale(), setAxisScaleIfNeeded(), setYUpperBound(), and EPlotLightMarker::updateLabel().
yAutoscaleAdjustEnabled
bool EPlotLightBase::yAutoscaleAdjustEnabled () slot
Referenced by setYAutoscaleAdjustment().
yAutoscaleAdjustment
double EPlotLightBase::yAutoscaleAdjustment () slot
Referenced by setYAutoscaleAdjustment().
yAxisAutoscaleEnabled()
bool EPlotLightBase::yAxisAutoscaleEnabled ()
References EPlotLightBasePrivate::yAutoscale.
yAxisLogScale()
bool EPlotLightBase::yAxisLogScale ()
Referenced by setYAutoscaleAdjustment().
yLowerBound()
double EPlotLightBase::yLowerBound ()
Referenced by adjustYScale(), setAxisScaleIfNeeded(), setYAxisAutoscaleEnabled(), and EPlotLightMarker::updateLabel().
yUpperBound()
double EPlotLightBase::yUpperBound ()
Referenced by adjustYScale(), setAxisScaleIfNeeded(), setYAxisAutoscaleEnabled(), and EPlotLightMarker::updateLabel().
zoomDisabled()
bool EPlotLightBase::zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
See also
setZoomDisabled
Referenced by drawCanvas(), and eraseZoomHint().
Member Data Documentation
zoomer
Zoomer* EPlotLightBase::zoomer protected
Referenced by adjustXScale(), adjustYScale(), EPlotLightBase(), EPlotLightMarker::EPlotLightMarker(), extendYLowerBound(), extendYUpperBound(), refresh(), setTimeScaleDrawEnabled(), setXAxisAutoscaleEnabled(), setXLowerBound(), setXUpperBound(), setYAxisAutoscaleEnabled(), setYLowerBound(), setYUpperBound(), and timeScaleDrawEnabled().
Property Documentation
alignCanvasToScales
bool EPlotLightBase::alignCanvasToScales read write
curvesStyle
EPlotLightBase::CurveStyle EPlotLightBase::curvesStyle read write
Referenced by setAxisScaleIfNeeded().
titleOnCanvasEnabled
bool EPlotLightBase::titleOnCanvasEnabled read write
xAutoscaleAdjustEnabled
bool EPlotLightBase::xAutoscaleAdjustEnabled read write
xAutoscaleAdjustment
double EPlotLightBase::xAutoscaleAdjustment read write
xAxisAutoscale
bool EPlotLightBase::xAxisAutoscale read write
xAxisLogScale
bool EPlotLightBase::xAxisLogScale read write
xLowerBound
double EPlotLightBase::xLowerBound read write
xUpperBound
double EPlotLightBase::xUpperBound read write
yAutoscaleAdjustEnabled
bool EPlotLightBase::yAutoscaleAdjustEnabled read write
yAutoscaleAdjustment
double EPlotLightBase::yAutoscaleAdjustment read write
yAxisAutoscale
bool EPlotLightBase::yAxisAutoscale read write
yAxisLogScale
bool EPlotLightBase::yAxisLogScale read write
yLowerBound
double EPlotLightBase::yLowerBound read write
yUpperBound
double EPlotLightBase::yUpperBound read write
zoomDisabled
bool EPlotLightBase::zoomDisabled read write
The documentation for this class was generated from the following files:
eplotlight_base.h
eplotlight_base.cpp