cumbia-qtcontrols: FloatDelegate Class Reference
FloatDelegate Class Reference abstract
#include <float_delegate.h>
Public Member Functions
FloatDelegate ()
virtual ~FloatDelegate ()
virtual void setValue (double)=0
virtual void setMinimum (double)=0
virtual void setMaximum (double)=0
virtual void setIntDigits (int)=0
virtual void setDecDigits (int)=0
Constructor & Destructor Documentation
FloatDelegate()
FloatDelegate::FloatDelegate () inline
~FloatDelegate()
virtual FloatDelegate::~FloatDelegate () inline virtual
References setDecDigits(), setIntDigits(), setMaximum(), setMinimum(), and setValue().
Member Function Documentation
setDecDigits()
virtual void FloatDelegate::setDecDigits (int) pure virtual
Implemented in EApplyNumeric, and ENumeric.
Referenced by ~FloatDelegate().
setIntDigits()
virtual void FloatDelegate::setIntDigits (int) pure virtual
Implemented in EApplyNumeric, and ENumeric.
Referenced by ~FloatDelegate().
setMaximum()
virtual void FloatDelegate::setMaximum (double) pure virtual
Implemented in EApplyNumeric, and ENumeric.
Referenced by ~FloatDelegate().
setMinimum()
virtual void FloatDelegate::setMinimum (double) pure virtual
Implemented in EApplyNumeric, and ENumeric.
Referenced by ~FloatDelegate().
setValue()
virtual void FloatDelegate::setValue (double) pure virtual
Implemented in EApplyNumeric, and ENumeric.
Referenced by ~FloatDelegate().
The documentation for this class was generated from the following file:
float_delegate.h