Cumbia communication independent controls based on Qt: PlotSaver Class Reference
PlotSaver Class Reference
#include <plotsaver.h>
Public Member Functions
PlotSaver ()
bool save (const QList< QwtPlotCurve *> curves)
QString errorMessage ()
QString fileName ()
Constructor & Destructor Documentation
PlotSaver()
PlotSaver::PlotSaver ()
Member Function Documentation
errorMessage()
QString PlotSaver::errorMessage () inline
Referenced by QuPlotContextMenuComponent::saveData(), and EPlotLight::saveData().
fileName()
QString PlotSaver::fileName () inline
Referenced by QuPlotContextMenuComponent::saveData(), and EPlotLight::saveData().
save()
bool PlotSaver::save (const QList< QwtPlotCurve *> curves)
References OptionsDialog::dateTimeFormat(), pinfo, qstoc, OptionsDialog::timestampToDateTimeString(), OptionsDialog::xFormat(), and OptionsDialog::yFormat().
Referenced by QuPlotContextMenuComponent::saveData(), and EPlotLight::saveData().
The documentation for this class was generated from the following files:
plotsaver.h
plotsaver.cpp