cumbia-qtcontrols: Callout Class Reference
Callout Class Reference
#include <callout.h>
Public Member Functions
Callout (QChart *parent, bool xDateTime, CalloutListener *cl)
virtual ~Callout ()
void setText (const QString &title)
void setAnchor (QPointF point, bool move_marker=true)
void updateGeometry ()
void show (const QString &title, const QPointF &pos, const QPointF &value, const QColor &color, bool move_marker=true)
Place and show a marker callout on the plot.
void setXDateTime (bool dt)
bool xDateTime () const
QPointF anchor () const
QString title () const
bool isMoving () const
void setMoving (bool m)
bool isPressed () const
void hide ()
void setVisible (bool v)
bool isVisibleFor (const QString &title) const
QRectF boundingRect () const
void paint (QPainter *painter, const QStyleOptionGraphicsItem *option, QWidget *widget)
Protected Member Functions
void mousePressEvent (QGraphicsSceneMouseEvent *event)
void mouseMoveEvent (QGraphicsSceneMouseEvent *event)
void mouseDoubleClickEvent (QGraphicsSceneMouseEvent *)
Constructor & Destructor Documentation
Callout()
Callout::Callout (QChart * parent, bool xDateTime, CalloutListener * cl)
References hide(), and xDateTime().
~Callout()
Callout::~Callout () virtual
Member Function Documentation
anchor()
QPointF Callout::anchor () const
Referenced by boundingRect(), and paint().
boundingRect()
QRectF Callout::boundingRect () const
References anchor().
hide()
void Callout::hide ()
Referenced by Callout().
isMoving()
bool Callout::isMoving () const
isPressed()
bool Callout::isPressed () const
isVisibleFor()
bool Callout::isVisibleFor (const QString & title) const
References title().
mouseDoubleClickEvent()
void Callout::mouseDoubleClickEvent (QGraphicsSceneMouseEvent * e) protected
mouseMoveEvent()
void Callout::mouseMoveEvent (QGraphicsSceneMouseEvent * event) protected
mousePressEvent()
void Callout::mousePressEvent (QGraphicsSceneMouseEvent * event) protected
paint()
void Callout::paint (QPainter * painter, const QStyleOptionGraphicsItem * option, QWidget * widget)
References anchor().
setAnchor()
void Callout::setAnchor (QPointF point, bool move_marker = true)
Referenced by show().
setMoving()
void Callout::setMoving (bool m)
setText()
void Callout::setText (const QString & title)
Referenced by show().
setVisible()
void Callout::setVisible (bool v)
setXDateTime()
void Callout::setXDateTime (bool dt)
show()
void Callout::show (const QString & title, const QPointF & p, const QPointF & value, const QColor & color, bool move_marker = true)
Place and show a marker callout on the plot.
Parameters
title the title
p the position in plot coordinates, x,y
color the background of the callout
move_marker true: move the marker close to the point
move_marker false: keep the marker in the same position, move only the arrow
References setAnchor(), setText(), and title().
title()
QString Callout::title () const
Referenced by isVisibleFor(), and show().
updateGeometry()
void Callout::updateGeometry ()
xDateTime()
bool Callout::xDateTime () const
Referenced by Callout().
The documentation for this class was generated from the following files:
callout.h
callout.cpp