cumbia-tango: CuTAttConfiguration Class Reference
CuTAttConfiguration Class Reference
#include <cutattconfiguration.h>
Public Member Functions
CuTAttConfiguration (const TSource &src, CumbiaTango *ct)
virtual ~CuTAttConfiguration ()
void setDesiredAttributeProperties (const std::vector< std::string > props)
void onProgress (int, int, const CuData &)
void onResult (const CuData &data)
CuData getToken () const
TSource getSource () const
return a TSource object that stores information about the Tango source
Type getType () const
returns the type of CuTangoActionI implemented
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
void sendData (const CuData &data)
subclasses will implement the necessary code to set data on themselves or to the activities
void getData (CuData &d_inout) const
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
size_t dataListenersCount ()
return the number of registered data listeners
void start ()
the method where activities are created and registered
void stop ()
the method where activities are unregistered from Cumbia
bool exiting () const
returns true if the action has been stopped and it's exiting
Public Member Functions inherited from CuTangoActionI
virtual ~CuTangoActionI ()
virtual destructor, to make compilers happy
Additional Inherited Members
Public Types inherited from CuTangoActionI
enum Type {
Reader = 0, Writer, AttConfig, DbReadProp,
DbWriteProp
}
list of types of actions
Constructor & Destructor Documentation
CuTAttConfiguration()
CuTAttConfiguration::CuTAttConfiguration (const TSource & src, CumbiaTango * ct)
~CuTAttConfiguration()
CuTAttConfiguration::~CuTAttConfiguration () virtual
Member Function Documentation
addDataListener()
void CuTAttConfiguration::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuTangoActionI.
dataListenersCount()
size_t CuTAttConfiguration::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuTangoActionI.
exiting()
bool CuTAttConfiguration::exiting () const virtual
returns true if the action has been stopped and it's exiting
Returns
true if the action is exiting (normally, stop has been called), false otherwise
Used by CuActionFactoryService::unregisterAction to check whether the action is still running before unregistering.
Implements CuTangoActionI.
getData()
void CuTAttConfiguration::getData (CuData & d_inout) const virtual
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation as input argument. data will contain additional output fields filled in by the method when it returns.
note
getData must be synchronous: it's called with input arguments (d_inout) and they are filled in within the same method in the same thread. Asynchronous data fetch from an activity executed in a separate thread can be accomplished by sendData in combination with CuDataListener::onUpdate. There, received data will have to be recognised as coming from a specific request and treated accordingly.
Implements CuTangoActionI.
getSource()
TSource CuTAttConfiguration::getSource () const virtual
return a TSource object that stores information about the Tango source
Returns
TSource, an object storing information on the Tango source
Implements CuTangoActionI.
getToken()
CuData CuTAttConfiguration::getToken () const
getType()
CuTangoActionI::Type CuTAttConfiguration::getType () const virtual
returns the type of CuTangoActionI implemented
Returns
one of the values from the Type enum
Implements CuTangoActionI.
References CuTangoActionI::AttConfig.
Referenced by onResult().
onProgress()
void CuTAttConfiguration::onProgress (int step, int total, const CuData & data)
onResult()
void CuTAttConfiguration::onResult (const CuData & data)
References CuActionFactoryService::CuActionFactoryServiceType, getType(), and CuActionFactoryService::unregisterAction().
removeDataListener()
void CuTAttConfiguration::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuTangoActionI.
References stop().
sendData()
void CuTAttConfiguration::sendData (const CuData & data) virtual
subclasses will implement the necessary code to set data on themselves or to the activities
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation
The data can be set locally on the object implementing this interface or can be forwarded to the activity by means of Cumbia::postEvent carrying an argument derived from CuActivityEvent. See CuTReader::sendData for an example
Send a request and receive a response asynchronously
Use sendData in conjunction with CuDataListener::onUpdate, as described in the getData documentation.
Implements CuTangoActionI.
setDesiredAttributeProperties()
void CuTAttConfiguration::setDesiredAttributeProperties (const std::vector< std::string > props)
Referenced by CuTangoAttConfFactory::create(), and start().
start()
void CuTAttConfiguration::start () virtual
the method where activities are created and registered
This is the place where activities are created and registered to Cumbia through the method Cumbia::registerActivity.
Examples
CuTReader::start
CuTWriter::start
See also Cumbia::registerActivity
Implements CuTangoActionI.
References TSource::Cmd, CuDeviceFactoryService::CuDeviceFactoryServiceType, and setDesiredAttributeProperties().
stop()
void CuTAttConfiguration::stop () virtual
the method where activities are unregistered from Cumbia
This is the place where activities are unregistered from Cumbia by the Cumbia::unregisterActivity method
Examples
CuTReader::stop
CuTWriter::stop
See also Cumbia::unregisterActivity
Implements CuTangoActionI.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cutattconfiguration.h
cutattconfiguration.cpp