actions extension plugin: GetTDbPropertyExtension Class Reference
GetTDbPropertyExtension Class Reference
#include <gettdbpropertyextension.h>
Signals
void onDataReady (const CuData &da)
Public Member Functions
GetTDbPropertyExtension (const CuContextI *ctx, QObject *parent=NULL)
virtual ~GetTDbPropertyExtension ()
QString getName () const
CuData execute (const CuData &in, const CuContextI *ctx)
std::vector< CuData > execute (const std::vector< CuData > &in_list, const CuContextI *ctxi)
QObject * get_qobject ()
virtual const CuContextI * getContextI () const
std::string message () const
bool error () const
virtual void onUpdate (const CuData &data)
Constructor & Destructor Documentation
GetTDbPropertyExtension()
GetTDbPropertyExtension::GetTDbPropertyExtension (const CuContextI * ctx, QObject * parent = NULL)
References GetTDbPropertyExtensionPrivate::err.
~GetTDbPropertyExtension()
GetTDbPropertyExtension::~GetTDbPropertyExtension () virtual
Member Function Documentation
error()
bool GetTDbPropertyExtension::error () const
References GetTDbPropertyExtensionPrivate::err.
execute() [1/2]
CuData GetTDbPropertyExtension::execute (const CuData & in, const CuContextI * ctx)
References GetTDbPropertyExtensionPrivate::contexti, and execute().
Referenced by execute().
execute() [2/2]
std::vector< CuData > GetTDbPropertyExtension::execute (const std::vector< CuData > & in_list, const CuContextI * ctxi)
References GetTDbPropertyExtensionPrivate::contexti.
get_qobject()
QObject * GetTDbPropertyExtension::get_qobject ()
getContextI()
const CuContextI * GetTDbPropertyExtension::getContextI () const virtual
References GetTDbPropertyExtensionPrivate::contexti.
getName()
QString GetTDbPropertyExtension::getName () const
message()
std::string GetTDbPropertyExtension::message () const
References GetTDbPropertyExtensionPrivate::msg.
onDataReady
void GetTDbPropertyExtension::onDataReady (const CuData & da) signal
Referenced by onUpdate().
onUpdate()
void GetTDbPropertyExtension::onUpdate (const CuData & data) virtual
References onDataReady().
The documentation for this class was generated from the following files:
gettdbpropertyextension.h
gettdbpropertyextension.cpp