actions extension plugin: CuInfoDialog Class Reference
CuInfoDialog Class Reference
a QDialog used by cumbia-qtcontrols to display statistics and link information about a source or target.
#include <cuinfodialog.h>
Public Types
enum ContentType { Data , Conf }
Public Slots
void showAppDetails (bool show)
void exec (const CuData &in, const CuContextI *ctxi)
Public Member Functions
CuInfoDialog (QWidget *parent)
virtual ~CuInfoDialog ()
QStringList extractSources (const QString &expression, QString &formula)
CuInfoDialog::extractSources if source represents a formula, this method extracts the source names only, comma separated if more than one. The result must be formatted in a way that is compatible with the "src" CuData value that will be provided by the formula reader, for example: test/device/1/double_scalar,test/device/2/double_scalar
QString extractSource (const QString &expression, QString &formula)
CuInfoDialog::extractSource provides the list of strings returned by extractSources joined by commas.
void onObjectChanged (QObject *obj, const CuContextI *ctxi)
Public Member Functions inherited from CuInfoDEventListener
Detailed Description
This dialog window is shown when a cumbia-qtcontrols widget is clicked with the right button and the Link stats action is triggered.
The dialog shows:
the operation count (the number of times a read [write] has been performed)
the error count
the last error message
a green/red bar representing the health of the link (10 read errors over 100 total reads will produce a health of 90%)
the last operation date and time
the value
the write value (if can be applied to the underlying engine)
the name of the activity (e.g. can be polling/event for Tango)
the data format (scalar, vector)
the read mode (e.g. for Tango can be "EVENT" or "POLLED")
the last message from the link
a live reader section where a label reads the same value as the monitored source, but independently.
a plot showing the trend of the value (read live from the info dialog itself)
cumbia-qtcontrols widgets that want to display this dialog when the user right clicks on them, have to reimplement the QWidget::contextMenuEvent method and instantiate a CuContextMenu to delegate the initialization of CuInfoDialog. See QuLabel::contextMenuEvent for an example.
Member Enumeration Documentation
ContentType
enum CuInfoDialog::ContentType
Enumerator
Data
Conf
Constructor & Destructor Documentation
CuInfoDialog()
CuInfoDialog::CuInfoDialog (QWidget * parent)
References CuInfoDialogPrivate::categories, CuInfoDialogPrivate::ctxi, CuInfoDialogPrivate::cu_pool, and CuInfoDialogPrivate::r_fac.
~CuInfoDialog()
CuInfoDialog::~CuInfoDialog () virtual
Member Function Documentation
exec
void CuInfoDialog::exec (const CuData & in, const CuContextI * ctxi) slot
OCCHIO QUI
References CuInfoDialogPrivate::ctxi, extractSource(), CuInfoDialogPrivate::layout_col_cnt, onObjectChanged(), root_obj(), showAppDetails(), and CuInfoDialogPrivate::tree.
Referenced by InfoDialogExtension::execute().
extractSource()
QString CuInfoDialog::extractSource (const QString & expression, QString & formula)
Parameters
expression the expression obtained by the reader's source property (may be a simple source or a complex formula expression)
formula will contain the formula, if any
Returns
a comma separated list of strings that are the names of the sources detected within {}
Please read the cuformula plugin documentation for further details.
If expression is a formula, the list of sources involved are detected within the first *{}* parenthesis group.
Example
If expression is "{$1/double_scalar,$2/double_scalar} function(a,b) { return a-b;}" the method will return a QString "$1/double_scalar,$2/double_scalar" and formula will contain "function(a,b) { return a-b;}"
References extractSources().
Referenced by exec().
extractSources()
QStringList CuInfoDialog::extractSources (const QString & expression, QString & formula)
Parameters
expression the source expression as returned by the source property of the reader
formula will contain the formula, if any
Returns
a list of strings with the sources detected in expr.
Please read the cuformula plugin documentation for further details. If expression is a formula, the list of sources involved are detected within the first *{}* parenthesis group.
Example
If expression is "{$1/double_scalar,$2/double_scalar} function(a,b) { return a-b;}" the method will return a QStringList ("$1/double_scalar","$2/double_scalar") and formula will contain "function(a,b) { return a-b;}"
Referenced by extractSource().
onObjectChanged()
void CuInfoDialog::onObjectChanged (QObject * obj, const CuContextI * ctxi) virtual
Implements CuInfoDEventListener.
References CuInfoDialogPrivate::ctxi, and CuInfoDialogPrivate::tree.
Referenced by exec().
showAppDetails
void CuInfoDialog::showAppDetails (bool show) slot
Referenced by exec().
The documentation for this class was generated from the following files:
cuinfodialog.h
cuinfodialog.cpp