actions extension plugin: CuEngineSwitchDialog Class Reference
CuEngineSwitchDialog Class Reference
#include <cuengineswitchdialog.h>
Public Slots
void switchEngine (bool checked)
Public Member Functions
CuEngineSwitchDialog (QWidget *parent, const CuContextI *ctxi)
virtual ~CuEngineSwitchDialog ()
void exec (const CuData &in, const CuContextI *ctxi)
QObject * root_obj (QObject *leaf)
Constructor & Destructor Documentation
CuEngineSwitchDialog()
CuEngineSwitchDialog::CuEngineSwitchDialog (QWidget * parent, const CuContextI * ctxi)
References CuEngineSwitchDialogPrivate::ctxi.
~CuEngineSwitchDialog()
CuEngineSwitchDialog::~CuEngineSwitchDialog () virtual
Member Function Documentation
exec()
void CuEngineSwitchDialog::exec (const CuData & in, const CuContextI * ctxi)
References CuEngineSwitchDialogPrivate::ctxi, CuEngineSwitchDialogPrivate::owner, root_obj(), and switchEngine().
Referenced by EngineSwitchDialogExtension::execute().
root_obj()
QObject * CuEngineSwitchDialog::root_obj (QObject * leaf)
Referenced by exec(), and switchEngine().
switchEngine
void CuEngineSwitchDialog::switchEngine (bool checked) slot
References CuEngineSwitchDialogPrivate::ctxi, CuEngineSwitchDialogPrivate::owner, and root_obj().
Referenced by exec().
The documentation for this class was generated from the following files:
cuengineswitchdialog.h
cuengineswitchdialog.cpp