#############################################################################
# Makefile for building: libcumbia.so.1.0.0
# Generated by qmake (3.1) (Qt 6.6.1)
# Project:  cumbia/cumbia.pro
# Template: lib
# Command: /usr/bin/qmake6 -o Makefile cumbia/cumbia.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQUMBIATANGOCONTROLS_LIBRARY -DCUMBIA_PRINTINFO -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -Icumbia -I. -Icumbia -Icumbia/src/lib -Icumbia/src/lib/threads -Icumbia/src/lib/services -I/usr/include/qt6 -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtCore -Imoc -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = cumbia1.0.0
DISTDIR = /archivi/devel/utils/git/cppqtclients/cumbia-world/cumbia-libs/obj/cumbia1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib -shared -fPIC -Wl,-soname,libcumbia.so.1
LIBS          = $(SUBLIBS) /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = builddir/meson-private/sanitycheckcpp.cc \
		cumbia/src/lib/cuactivity.cpp \
		cumbia/src/lib/cuactivityevent.cpp \
		src/lib/cucontinuousactivity.cpp \
		cumbia/src/lib/cudata.cpp \
		cumbia/src/lib/cudatalistener.cpp \
		src/lib/cuisolatedactivity.cpp \
		cumbia/src/lib/cumbia.cpp \
		cumbia/src/lib/cumbiapool.cpp \
		cumbia/src/lib/cuvariant.cpp \
		cumbia/src/lib/cuvariantprivate.cpp \
		cumbia/src/lib/services/cuactivitymanager.cpp \
		cumbia/src/lib/services/culog.cpp \
		cumbia/src/lib/services/cuserviceprovider.cpp \
		cumbia/src/lib/services/cuthreadservice.cpp \
		cumbia/src/lib/threads/cuevent.cpp \
		cumbia/src/lib/threads/cueventloop.cpp \
		cumbia/src/lib/threads/cuthread.cpp \
		cumbia/src/lib/threads/cuthreadevents.cpp \
		cumbia/src/lib/threads/cuthreadfactoryimpl.cpp \
		cumbia/src/lib/threads/cuthreadseventbridge.cpp \
		cumbia/src/lib/threads/cutimer.cpp 
OBJECTS       = obj/sanitycheckcpp.o \
		obj/cuactivity.o \
		obj/cuactivityevent.o \
		obj/cucontinuousactivity.o \
		obj/cudata.o \
		obj/cudatalistener.o \
		obj/cuisolatedactivity.o \
		obj/cumbia.o \
		obj/cumbiapool.o \
		obj/cuvariant.o \
		obj/cuvariantprivate.o \
		obj/cuactivitymanager.o \
		obj/culog.o \
		obj/cuserviceprovider.o \
		obj/cuthreadservice.o \
		obj/cuevent.o \
		obj/cueventloop.o \
		obj/cuthread.o \
		obj/cuthreadevents.o \
		obj/cuthreadfactoryimpl.o \
		obj/cuthreadseventbridge.o \
		obj/cutimer.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		cumbia/cumbia/cumbia.pro builddir/config.h \
		cumbia/src/lib/cuactivity.h \
		cumbia/src/lib/cuactivityevent.h \
		src/lib/cucontinuousactivity.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cudatalistener.h \
		src/lib/cuisolatedactivity.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumbia.h \
		cumbia/src/lib/cumbiapool.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/services/cuactivitymanager.h \
		cumbia/src/lib/services/culog.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cuserviceprovider.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/services/cuthreadservice.h \
		cumbia/src/lib/threads/cuevent.h \
		cumbia/src/lib/threads/cueventloop.h \
		cumbia/src/lib/threads/cuthread.h \
		cumbia/src/lib/threads/cuthreadevents.h \
		cumbia/src/lib/threads/cuthreadfactoryimpl.h \
		cumbia/src/lib/threads/cuthreadfactoryimpl_i.h \
		cumbia/src/lib/threads/cuthreadinterface.h \
		cumbia/src/lib/threads/cuthreadlistener.h \
		cumbia/src/lib/threads/cuthreadseventbridge.h \
		cumbia/src/lib/threads/cuthreadseventbridge_i.h \
		cumbia/src/lib/threads/cuthreadseventbridgefactory_i.h \
		cumbia/src/lib/threads/cutimer.h \
		cumbia/src/lib/threads/cutimerlistener.h builddir/meson-private/sanitycheckcpp.cc \
		cumbia/src/lib/cuactivity.cpp \
		cumbia/src/lib/cuactivityevent.cpp \
		src/lib/cucontinuousactivity.cpp \
		cumbia/src/lib/cudata.cpp \
		cumbia/src/lib/cudatalistener.cpp \
		src/lib/cuisolatedactivity.cpp \
		cumbia/src/lib/cumbia.cpp \
		cumbia/src/lib/cumbiapool.cpp \
		cumbia/src/lib/cuvariant.cpp \
		cumbia/src/lib/cuvariantprivate.cpp \
		cumbia/src/lib/services/cuactivitymanager.cpp \
		cumbia/src/lib/services/culog.cpp \
		cumbia/src/lib/services/cuserviceprovider.cpp \
		cumbia/src/lib/services/cuthreadservice.cpp \
		cumbia/src/lib/threads/cuevent.cpp \
		cumbia/src/lib/threads/cueventloop.cpp \
		cumbia/src/lib/threads/cuthread.cpp \
		cumbia/src/lib/threads/cuthreadevents.cpp \
		cumbia/src/lib/threads/cuthreadfactoryimpl.cpp \
		cumbia/src/lib/threads/cuthreadseventbridge.cpp \
		cumbia/src/lib/threads/cutimer.cpp
QMAKE_TARGET  = cumbia
DESTDIR       = 
TARGET        = libcumbia.so.1.0.0
TARGETA       = libcumbia.a
TARGET0       = libcumbia.so
TARGETD       = libcumbia.so.1.0.0
TARGET1       = libcumbia.so.1
TARGET2       = libcumbia.so.1.0


first: all
####### Build rules

libcumbia.so.1.0.0:  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: libcumbia.a

libcumbia.a:  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: cumbia/cumbia.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		cumbia/cumbia.pro \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile cumbia/cumbia.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_linguist_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversionsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgeneratorsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/permissions.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/link_ltcg.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
cumbia/cumbia.pro:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile cumbia/cumbia.pro

qmake_all: FORCE


all: Makefile libcumbia.so.1.0.0

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents builddir/config.h cumbia/src/lib/cuactivity.h cumbia/src/lib/cuactivityevent.h src/lib/cucontinuousactivity.h cumbia/src/lib/cudata.h cumbia/src/lib/cudatalistener.h src/lib/cuisolatedactivity.h cumbia/src/lib/cumacros.h cumbia/src/lib/cumbia.h cumbia/src/lib/cumbiapool.h cumbia/src/lib/cuvariant.h cumbia/src/lib/cuvariant_t.h cumbia/src/lib/cuvariantprivate.h cumbia/src/lib/services/cuactivitymanager.h cumbia/src/lib/services/culog.h cumbia/src/lib/services/cuservicei.h cumbia/src/lib/services/cuserviceprovider.h cumbia/src/lib/services/cuservices.h cumbia/src/lib/services/cuthreadservice.h cumbia/src/lib/threads/cuevent.h cumbia/src/lib/threads/cueventloop.h cumbia/src/lib/threads/cuthread.h cumbia/src/lib/threads/cuthreadevents.h cumbia/src/lib/threads/cuthreadfactoryimpl.h cumbia/src/lib/threads/cuthreadfactoryimpl_i.h cumbia/src/lib/threads/cuthreadinterface.h cumbia/src/lib/threads/cuthreadlistener.h cumbia/src/lib/threads/cuthreadseventbridge.h cumbia/src/lib/threads/cuthreadseventbridge_i.h cumbia/src/lib/threads/cuthreadseventbridgefactory_i.h cumbia/src/lib/threads/cutimer.h cumbia/src/lib/threads/cutimerlistener.h $(DISTDIR)/
	$(COPY_FILE) --parents builddir/meson-private/sanitycheckcpp.cc cumbia/src/lib/cuactivity.cpp cumbia/src/lib/cuactivityevent.cpp src/lib/cucontinuousactivity.cpp cumbia/src/lib/cudata.cpp cumbia/src/lib/cudatalistener.cpp src/lib/cuisolatedactivity.cpp cumbia/src/lib/cumbia.cpp cumbia/src/lib/cumbiapool.cpp cumbia/src/lib/cuvariant.cpp cumbia/src/lib/cuvariantprivate.cpp cumbia/src/lib/services/cuactivitymanager.cpp cumbia/src/lib/services/culog.cpp cumbia/src/lib/services/cuserviceprovider.cpp cumbia/src/lib/services/cuthreadservice.cpp cumbia/src/lib/threads/cuevent.cpp cumbia/src/lib/threads/cueventloop.cpp cumbia/src/lib/threads/cuthread.cpp cumbia/src/lib/threads/cuthreadevents.cpp cumbia/src/lib/threads/cuthreadfactoryimpl.cpp cumbia/src/lib/threads/cuthreadseventbridge.cpp cumbia/src/lib/threads/cutimer.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o moc/moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean 

####### Compile

obj/sanitycheckcpp.o: builddir/meson-private/sanitycheckcpp.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/sanitycheckcpp.o builddir/meson-private/sanitycheckcpp.cc

obj/cuactivity.o: cumbia/src/lib/cuactivity.cpp cumbia/src/lib/cuactivity.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/threads/cuthreadinterface.h \
		cumbia/src/lib/threads/cuthreadseventbridge_i.h \
		cumbia/src/lib/services/cuthreadservice.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cuactivitymanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuactivity.o cumbia/src/lib/cuactivity.cpp

obj/cuactivityevent.o: cumbia/src/lib/cuactivityevent.cpp cumbia/src/lib/cuactivityevent.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuactivityevent.o cumbia/src/lib/cuactivityevent.cpp

obj/cucontinuousactivity.o: src/lib/cucontinuousactivity.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cucontinuousactivity.o src/lib/cucontinuousactivity.cpp

obj/cudata.o: cumbia/src/lib/cudata.cpp cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/cudatatypes_ex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cudata.o cumbia/src/lib/cudata.cpp

obj/cudatalistener.o: cumbia/src/lib/cudatalistener.cpp cumbia/src/lib/cudatalistener.h \
		cumbia/src/lib/cumacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cudatalistener.o cumbia/src/lib/cudatalistener.cpp

obj/cuisolatedactivity.o: src/lib/cuisolatedactivity.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuisolatedactivity.o src/lib/cuisolatedactivity.cpp

obj/cumbia.o: cumbia/src/lib/cumbia.cpp cumbia/src/lib/cumbia.h \
		cumbia/src/lib/services/cuserviceprovider.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/services/cuthreadservice.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cutimerservice.h \
		cumbia/src/lib/threads/cuthreadseventbridgefactory_i.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/services/cuactivitymanager.h \
		cumbia/src/lib/cuperiodicactivity.h \
		cumbia/src/lib/cuactivity.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/threads/cuthreadinterface.h \
		cumbia/src/lib/threads/cuthreadseventbridge_i.h \
		cumbia/src/lib/cuactivityevent.h \
		cumbia/src/lib/threads/cuthreadtokengeni.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cumbia.o cumbia/src/lib/cumbia.cpp

obj/cumbiapool.o: cumbia/src/lib/cumbiapool.cpp cumbia/src/lib/cumbiapool.h \
		cumbia/src/lib/cumbia.h \
		cumbia/src/lib/cumacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cumbiapool.o cumbia/src/lib/cumbiapool.cpp

obj/cuvariant.o: cumbia/src/lib/cuvariant.cpp cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuvariant.o cumbia/src/lib/cuvariant.cpp

obj/cuvariantprivate.o: cumbia/src/lib/cuvariantprivate.cpp cumbia/src/lib/cuvariantprivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuvariantprivate.o cumbia/src/lib/cuvariantprivate.cpp

obj/cuactivitymanager.o: cumbia/src/lib/services/cuactivitymanager.cpp cumbia/src/lib/services/cuactivitymanager.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/cuactivity.h \
		cumbia/src/lib/threads/cuthreadinterface.h \
		cumbia/src/lib/threads/cuthreadseventbridge_i.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuactivitymanager.o cumbia/src/lib/services/cuactivitymanager.cpp

obj/culog.o: cumbia/src/lib/services/culog.cpp cumbia/src/lib/services/culog.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/cumacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/culog.o cumbia/src/lib/services/culog.cpp

obj/cuserviceprovider.o: cumbia/src/lib/services/cuserviceprovider.cpp cumbia/src/lib/services/cuserviceprovider.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/cumacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuserviceprovider.o cumbia/src/lib/services/cuserviceprovider.cpp

obj/cuthreadservice.o: cumbia/src/lib/services/cuthreadservice.cpp cumbia/src/lib/services/cuthreadservice.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/threads/cuthreadfactoryimpl_i.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/threads/cuthreadinterface.h \
		cumbia/src/lib/threads/cuthreadseventbridge_i.h \
		cumbia/src/lib/threads/cuthreadseventbridgefactory_i.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/threads/cuthread.h \
		cumbia/src/lib/cuactivity.h \
		cumbia/src/lib/threads/cutimerlistener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuthreadservice.o cumbia/src/lib/services/cuthreadservice.cpp

obj/cuevent.o: cumbia/src/lib/threads/cuevent.cpp cumbia/src/lib/threads/cuevent.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuevent.o cumbia/src/lib/threads/cuevent.cpp

obj/cueventloop.o: cumbia/src/lib/threads/cueventloop.cpp cumbia/src/lib/threads/cueventloop.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/threads/cuevent.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cueventloop.o cumbia/src/lib/threads/cueventloop.cpp

obj/cuthread.o: cumbia/src/lib/threads/cuthread.cpp cumbia/src/lib/threads/cuthread.h \
		cumbia/src/lib/threads/cuthreadinterface.h \
		cumbia/src/lib/threads/cuthreadseventbridge_i.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cuactivity.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/threads/cutimerlistener.h \
		cumbia/src/lib/threads/cutimer.h \
		cumbia/src/lib/threads/cueventloop.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/threads/cuthreadevents.h \
		cumbia/src/lib/threads/cuevent.h \
		cumbia/src/lib/cuactivityevent.h \
		cumbia/src/lib/threads/cuthreadlistener.h \
		cumbia/src/lib/services/cutimerservice.h \
		cumbia/src/lib/services/cuserviceprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuthread.o cumbia/src/lib/threads/cuthread.cpp

obj/cuthreadevents.o: cumbia/src/lib/threads/cuthreadevents.cpp cumbia/src/lib/threads/cuthreadevents.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cudatatypes.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuthreadevents.o cumbia/src/lib/threads/cuthreadevents.cpp

obj/cuthreadfactoryimpl.o: cumbia/src/lib/threads/cuthreadfactoryimpl.cpp cumbia/src/lib/threads/cuthreadfactoryimpl.h \
		cumbia/src/lib/threads/cuthreadfactoryimpl_i.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/threads/cuthread.h \
		cumbia/src/lib/threads/cuthreadinterface.h \
		cumbia/src/lib/threads/cuthreadseventbridge_i.h \
		cumbia/src/lib/cuactivity.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/threads/cutimerlistener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuthreadfactoryimpl.o cumbia/src/lib/threads/cuthreadfactoryimpl.cpp

obj/cuthreadseventbridge.o: cumbia/src/lib/threads/cuthreadseventbridge.cpp cumbia/src/lib/threads/cuthreadseventbridge.h \
		cumbia/src/lib/threads/cuthreadseventbridgefactory_i.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/threads/cuthreadseventbridge_i.h \
		cumbia/src/lib/threads/cueventloop.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/threads/cuevent.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/services/cuserviceprovider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cuthreadseventbridge.o cumbia/src/lib/threads/cuthreadseventbridge.cpp

obj/cutimer.o: cumbia/src/lib/threads/cutimer.cpp cumbia/src/lib/threads/cutimer.h \
		cumbia/src/lib/threads/cueventloop.h \
		cumbia/src/lib/services/cuservicei.h \
		cumbia/src/lib/services/cuservices.h \
		cumbia/src/lib/threads/cuevent.h \
		cumbia/src/lib/cudata.h \
		cumbia/src/lib/cuvariant.h \
		cumbia/src/lib/cumacros.h \
		cumbia/src/lib/cumatrix.h \
		cumbia/src/lib/cuvariant_t.h \
		cumbia/src/lib/cuvariantprivate.h \
		cumbia/src/lib/cudatatypes.h \
		cumbia/src/lib/threads/cutimerlistener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/cutimer.o cumbia/src/lib/threads/cutimer.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia || mkdir -p $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia
	$(QINSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/giacomo/devel/android/cumbia/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

