#ifndef CUMBIAWEBSOCKET_GLOBAL_H
#define CUMBIAWEBSOCKET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUMBIAWEBSOCKET_LIBRARY)
#  define CUMBIAWEBSOCKETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CUMBIAWEBSOCKETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CUMBIAWEBSOCKET_GLOBAL_H
