cumbia-websocket: CuWsRegisterEngine Class Reference
CuWsRegisterEngine Class Reference
#include <cuwsregisterengine.h>
Public Member Functions
CuWsRegisterEngine ()
virtual ~CuWsRegisterEngine ()
CumbiaWebSocket * registerWithDefaults (CumbiaPool *cu_pool, CuControlsFactoryPool &fpoo)
void setUrl (const QString &url)
QString url () const
bool hasCmdOption (const QStringList &args) const
Constructor & Destructor Documentation
CuWsRegisterEngine()
CuWsRegisterEngine::CuWsRegisterEngine ()
~CuWsRegisterEngine()
CuWsRegisterEngine::~CuWsRegisterEngine () virtual
Member Function Documentation
hasCmdOption()
bool CuWsRegisterEngine::hasCmdOption (const QStringList & args) const
registerWithDefaults()
CumbiaWebSocket * CuWsRegisterEngine::registerWithDefaults (CumbiaPool * cu_pool, CuControlsFactoryPool & fpoo)
References CumbiaWebSocket::addReplaceWildcardI(), and url().
setUrl()
void CuWsRegisterEngine::setUrl (const QString & url)
References url().
url()
QString CuWsRegisterEngine::url () const
Referenced by registerWithDefaults(), and setUrl().
The documentation for this class was generated from the following files:
cuwsregisterengine.h
cuwsregisterengine.cpp