cumbia-websocket: CuWSClient Class Reference
CuWSClient Class Reference
#include <cuwsclient.h>
Public Slots
void suspend ()
shortcut for close. Neeeded by QmlAppStateManager to close the socket when the application becomes inactive/hidden/suspended
void start ()
shortcut for open. Neeeded by QmlAppStateManager to re open the socket after the application is active again
void open ()
void close ()
void sendMessage (const QString &msg)
Signals
void closed ()
Public Member Functions
CuWSClient (const QUrl &url, CuWSClientListener *listener, QObject *parent=nullptr)
~CuWSClient ()
bool isOpen () const
Constructor & Destructor Documentation
CuWSClient()
CuWSClient::CuWSClient (const QUrl & url, CuWSClientListener * listener, QObject * parent = nullptr) explicit
~CuWSClient()
CuWSClient::~CuWSClient ()
References close().
Member Function Documentation
close
void CuWSClient::close () slot
Referenced by suspend(), and ~CuWSClient().
closed
void CuWSClient::closed () signal
isOpen()
bool CuWSClient::isOpen () const
open
void CuWSClient::open () slot
Referenced by start().
sendMessage
void CuWSClient::sendMessage (const QString & msg) slot
start
void CuWSClient::start () slot
shortcut for open. Neeeded by QmlAppStateManager to re open the socket after the application is active again
See also
open
References open().
suspend
void CuWSClient::suspend () slot
shortcut for close. Neeeded by QmlAppStateManager to close the socket when the application becomes inactive/hidden/suspended
See also
close
References close().
The documentation for this class was generated from the following files:
cuwsclient.h
cuwsclient.cpp