cumbia-websocket: CuWSActionReader Class Reference
CuWSActionReader Class Reference
#include <cuwsactionreader.h>
Public Member Functions
CuWSActionReader (const WSSource &src, CuWSClient *wscli, const QString &http_url)
~CuWSActionReader ()
CuData getToken () const
returns the CuData storing the token that identifies this action
WSSource getSource () const
CuWSActionI::Type getType () const
returns the type of CuWSActionI implemented
void start ()
void stop ()
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
size_t dataListenersCount ()
return the number of registered data listeners
void decodeMessage (const QJsonDocument &json)
bool exiting () const
void setOptions (const CuData &o)
Public Member Functions inherited from CuWSActionI
virtual ~CuWSActionI ()
virtual destructor, to make compilers happy
Additional Inherited Members
Public Types inherited from CuWSActionI
enum Type {
Reader = 0, Writer, AttConfig, DbReadProp,
DbWriteProp
}
Constructor & Destructor Documentation
CuWSActionReader()
CuWSActionReader::CuWSActionReader (const WSSource & src, CuWSClient * wscli, const QString & http_url)
References WSSource::getName(), and WSSource::getProtocol().
~CuWSActionReader()
CuWSActionReader::~CuWSActionReader ()
Member Function Documentation
addDataListener()
void CuWSActionReader::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuWSActionI.
dataListenersCount()
size_t CuWSActionReader::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuWSActionI.
decodeMessage()
void CuWSActionReader::decodeMessage (const QJsonDocument & json) virtual
Implements CuWSActionI.
References getToken().
exiting()
bool CuWSActionReader::exiting () const virtual
Implements CuWSActionI.
getSource()
WSSource CuWSActionReader::getSource () const virtual
returns the tango source (TSource)
Returns
a TSource object that describes the Tango source
Implements CuWSActionI.
getToken()
CuData CuWSActionReader::getToken () const
returns the CuData storing the token that identifies this action
Returns
a CuData with the following key/value pairs
"source" --> the name of the source (string)
"type" --> a constant string: "reader"
Referenced by decodeMessage(), and stop().
getType()
CuWSActionI::Type CuWSActionReader::getType () const virtual
returns the type of CuWSActionI implemented
Returns
one of the values from the Type enum
Implements CuWSActionI.
References CuWSActionI::Reader.
removeDataListener()
void CuWSActionReader::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuWSActionI.
References stop().
setOptions()
void CuWSActionReader::setOptions (const CuData & o)
start()
void CuWSActionReader::start () virtual
Implements CuWSActionI.
References WSSourceConfiguration::keys().
stop()
void CuWSActionReader::stop () virtual
Implements CuWSActionI.
References getToken().
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cuwsactionreader.h
cuwsactionreader.cpp