cumbia-websocket: WSSource Class Reference
WSSource Class Reference
#include <ws_source.h>
Public Member Functions
WSSource ()
WSSource (const std::string &src)
WSSource (const WSSource &other)
string getName () const
Returns the full name that was given to the constructor without the cumbia domain engine specification.
string getFullName () const
WSSource::getFullName returns the full name that was given to the constructor.
string getProtocol () const
matches last protocol specification found in the source name, matching the pattern protocol://
std::vector< string > getArgs () const
string toString () const
WSSource & operator= (const WSSource &other)
bool operator== (const WSSource &other) const
std::string getArgsString () const
Constructor & Destructor Documentation
WSSource() [1/3]
WSSource::WSSource ()
WSSource() [2/3]
WSSource::WSSource (const std::string & src)
WSSource() [3/3]
WSSource::WSSource (const WSSource & other)
Member Function Documentation
getArgs()
std::vector< string > WSSource::getArgs () const
References getArgsString().
getArgsString()
std::string WSSource::getArgsString () const
Referenced by getArgs(), and toString().
getFullName()
string WSSource::getFullName () const
WSSource::getFullName returns the full name that was given to the constructor.
Returns
the full name that was given to the constructor, including the cumbia domain engine specification, if provided (either ws:// or wss://)
getName()
string WSSource::getName () const
Returns the full name that was given to the constructor without the cumbia domain engine specification.
Returns
the source that was passed to the constructor, without the cumbia domain engine specification, if specified (either ws:// or wss://)
example
WSSource s("wss://tango://test/device/1/double_scalar");
printf("name: %s\n", s.getName().c_str());
//
// output
// name: tango://test/device/1/double_scalar
//
Referenced by CuWSActionReader::CuWSActionReader().
getProtocol()
string WSSource::getProtocol () const
matches last protocol specification found in the source name, matching the pattern protocol://
example
In the source "https://pwma-dev.elettra.eu:10443/v1/cs/tango://ken.elettra.trieste.it:20000/test/device/1/double_scalar" "tango://" is returned
Referenced by CuWSActionReader::CuWSActionReader().
operator=()
WSSource & WSSource::operator= (const WSSource & other)
operator==()
bool WSSource::operator== (const WSSource & other) const
toString()
std::string WSSource::toString () const
References getArgsString().
The documentation for this class was generated from the following files:
ws_source.h
ws_source.cpp