cumbia-websocket: CuWSReaderFactory Class Reference
CuWSReaderFactory Class Reference
#include <cuwsreader.h>
Public Member Functions
CuWSReaderFactory ()
virtual ~CuWSReaderFactory ()
CuControlsReaderA * create (Cumbia *c, CuDataListener *l) const
virtual void setOptions (const CuData &options)
CuControlsReaderFactoryI * clone () const
Constructor & Destructor Documentation
CuWSReaderFactory()
CuWSReaderFactory::CuWSReaderFactory ()
Referenced by clone().
~CuWSReaderFactory()
CuWSReaderFactory::~CuWSReaderFactory () virtual
Member Function Documentation
clone()
CuControlsReaderFactoryI * CuWSReaderFactory::clone () const
References CuWSReaderFactory(), and setOptions().
create()
CuControlsReaderA * CuWSReaderFactory::create (Cumbia * c, CuDataListener * l) const
References CuWSReader::setOptions().
setOptions()
void CuWSReaderFactory::setOptions (const CuData & options) virtual
Referenced by clone().
The documentation for this class was generated from the following files:
cuwsreader.h
cuwsreader.cpp