cumbia-websocket: CuWSActionFactoryI Class Reference
CuWSActionFactoryI Class Reference abstract
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
#include <cuwsactionfactoryi.h>
Public Member Functions
CuWSActionFactoryI ()
virtual CuWSActionI * create (const std::string &s, CuWSClient *cli, const QString &http_addr) const =0
virtual CuWSActionI::Type getType () const =0
Return the type of action that the factory creates.
Detailed Description
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
Notable implementations
CuTangoReaderFactory
CuTangoWriterFactory
CuTangoAttConfFactory
Constructor & Destructor Documentation
CuWSActionFactoryI()
CuWSActionFactoryI::CuWSActionFactoryI () inline
Member Function Documentation
create()
virtual CuWSActionI * CuWSActionFactoryI::create (const std::string & s, CuWSClient * cli, const QString & http_addr) const pure virtual
Pure virtual method that must be implemented by subclasses to return a valid CuTangoActionI instance.
Parameters
source a string identifying a source to connect to
ct a pointer to a CumbiaWebSocket instance
Implemented in CuWSActionReaderFactory, CuWSActionWriterFactory, and CuWSActionConfFactory.
Referenced by CuWSActionFactoryService::registerAction().
getType()
virtual CuWSActionI::Type CuWSActionFactoryI::getType () const pure virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implemented in CuWSActionReaderFactory, CuWSActionWriterFactory, and CuWSActionConfFactory.
Referenced by CumbiaWebSocket::addAction(), and CuWSActionFactoryService::registerAction().
The documentation for this class was generated from the following file:
cuwsactionfactoryi.h