cumbia-websocket: CuWsControlsReader Class Reference
CuWsControlsReader Class Reference
#include <cuwscontrolsreader.h>
Public Member Functions
CuWsControlsReader (Cumbia *cumbia, CuDataListener *tl)
virtual ~CuWsControlsReader ()
void setSource (const QString &s)
QString source () const
void unsetSource ()
void setOptions (const CuData &o)
CuData getOptions () const
virtual void sendData (const CuData &d)
virtual void getData (CuData &d_ino) const
Constructor & Destructor Documentation
CuWsControlsReader()
CuWsControlsReader::CuWsControlsReader (Cumbia * cumbia, CuDataListener * tl)
References CumbiaWebSocket::CumbiaWSType.
~CuWsControlsReader()
CuWsControlsReader::~CuWsControlsReader () virtual
References unsetSource().
Member Function Documentation
getData()
void CuWsControlsReader::getData (CuData & d_ino) const virtual
getOptions()
CuData CuWsControlsReader::getOptions () const
sendData()
void CuWsControlsReader::sendData (const CuData & d) virtual
setOptions()
void CuWsControlsReader::setOptions (const CuData & o)
Referenced by CuWSReaderFactory::create().
setSource()
void CuWsControlsReader::setSource (const QString & s)
References CuWSActionReaderFactory::setOptions(), and CuWSActionConfFactory::setOptions().
source()
QString CuWsControlsReader::source () const
unsetSource()
void CuWsControlsReader::unsetSource ()
References CuWSActionI::Reader.
Referenced by ~CuWsControlsReader().
The documentation for this class was generated from the following files:
cuwscontrolsreader.h
cuwscontrolsreader.cpp