cumbia-websocket: CuWsActionConf Class Reference
CuWsActionConf Class Reference
#include <cuwsactionconf.h>
Public Member Functions
CuWsActionConf (const WSSource &src, CuWSClient *wscli, const CuWSActionI::Type action_type, const QString &http_url)
~CuWsActionConf ()
WSSource getSource () const
return a WSSource object that stores information about the Tango source
Type getType () const
returns the type of CuWSActionI implemented
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
size_t dataListenersCount ()
return the number of registered data listeners
void start ()
bool exiting () const
void stop ()
void decodeMessage (const QJsonDocument &json)
Public Member Functions inherited from CuWSActionI
virtual ~CuWSActionI ()
virtual destructor, to make compilers happy
Additional Inherited Members
Public Types inherited from CuWSActionI
enum Type {
Reader = 0, Writer, ReaderConfig, WriterConfig,
DbReadProp, DbWriteProp
}
Constructor & Destructor Documentation
CuWsActionConf()
CuWsActionConf::CuWsActionConf (const WSSource & src, CuWSClient * wscli, const CuWSActionI::Type action_type, const QString & http_url)
~CuWsActionConf()
CuWsActionConf::~CuWsActionConf ()
Member Function Documentation
addDataListener()
void CuWsActionConf::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuWSActionI.
dataListenersCount()
size_t CuWsActionConf::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuWSActionI.
decodeMessage()
void CuWsActionConf::decodeMessage (const QJsonDocument & json) virtual
Implements CuWSActionI.
References CumbiaWSWorld::json_decode().
exiting()
bool CuWsActionConf::exiting () const virtual
Implements CuWSActionI.
getSource()
WSSource CuWsActionConf::getSource () const virtual
return a WSSource object that stores information about the Tango source
Returns
WSSource, an object storing information on the Tango source
Implements CuWSActionI.
getType()
CuWSActionI::Type CuWsActionConf::getType () const virtual
returns the type of CuWSActionI implemented
Returns
one of the values from the Type enum
Implements CuWSActionI.
removeDataListener()
void CuWsActionConf::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuWSActionI.
References stop().
start()
void CuWsActionConf::start () virtual
Implements CuWSActionI.
References CuWSActionI::ReaderConfig, and CuWSActionI::WriterConfig.
stop()
void CuWsActionConf::stop () virtual
Implements CuWSActionI.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cuwsactionconf.h
cuwsactionconf.cpp