cumbia-websocket: CuWSActionI Class Reference
CuWSActionI Class Reference abstract
#include <cuwsactioni.h>
Public Types
enum Type {
Reader = 0 , Writer , ReaderConfig , WriterConfig ,
DbReadProp , DbWriteProp
}
Public Member Functions
virtual ~CuWSActionI ()
virtual destructor, to make compilers happy
virtual WSSource getSource () const =0
return a WSSource object that stores information about the Tango source
virtual Type getType () const =0
returns the type of CuWSActionI implemented
virtual void addDataListener (CuDataListener *l)=0
insert a CuDataListener to the list of listeners of data updates
virtual void removeDataListener (CuDataListener *l)=0
remove a CuDataListener from the list of listeners of data updates
virtual size_t dataListenersCount ()=0
return the number of registered data listeners
virtual void start ()=0
virtual bool exiting () const =0
virtual void stop ()=0
virtual void decodeMessage (const QJsonDocument &json)=0
Member Enumeration Documentation
Type
enum CuWSActionI::Type
Enumerator
Reader
Writer
ReaderConfig
WriterConfig
DbReadProp
DbWriteProp
Constructor & Destructor Documentation
~CuWSActionI()
virtual CuWSActionI::~CuWSActionI () inline virtual
virtual destructor, to make compilers happy
Member Function Documentation
addDataListener()
virtual void CuWSActionI::addDataListener (CuDataListener * l) pure virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
Referenced by CumbiaWebSocket::addAction().
dataListenersCount()
virtual size_t CuWSActionI::dataListenersCount () pure virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
decodeMessage()
virtual void CuWSActionI::decodeMessage (const QJsonDocument & json) pure virtual
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
Referenced by CumbiaWebSocket::onUpdate().
exiting()
virtual bool CuWSActionI::exiting () const pure virtual
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
Referenced by CumbiaWebSocket::onUpdate().
getSource()
virtual WSSource CuWSActionI::getSource () const pure virtual
return a WSSource object that stores information about the Tango source
Returns
WSSource, an object storing information on the Tango source
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
getType()
virtual Type CuWSActionI::getType () const pure virtual
returns the type of CuWSActionI implemented
Returns
one of the values from the Type enum
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
removeDataListener()
virtual void CuWSActionI::removeDataListener (CuDataListener * l) pure virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
start()
virtual void CuWSActionI::start () pure virtual
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
Referenced by CumbiaWebSocket::addAction().
stop()
virtual void CuWSActionI::stop () pure virtual
Implemented in CuWsActionWriter, CuWSActionReader, and CuWsActionConf.
The documentation for this class was generated from the following file:
cuwsactioni.h