cumbia-websocket: CuWSActionWriterFactory Class Reference
CuWSActionWriterFactory Class Reference
#include <cuwsactionfactories.h>
Public Member Functions
void setConfiguration (const CuData &conf)
void setWriteValue (const CuVariant &write_val)
virtual ~CuWSActionWriterFactory ()
CuWSActionI * create (const std::string &s, CuWSClient *cli, const QString &http_addr) const
CuWSActionI::Type getType () const
Return the type of action that the factory creates.
Public Member Functions inherited from CuWSActionFactoryI
CuWSActionFactoryI ()
Constructor & Destructor Documentation
~CuWSActionWriterFactory()
CuWSActionWriterFactory::~CuWSActionWriterFactory () virtual
Member Function Documentation
create()
CuWSActionI * CuWSActionWriterFactory::create (const std::string & s, CuWSClient * cli, const QString & http_addr) const virtual
Pure virtual method that must be implemented by subclasses to return a valid CuTangoActionI instance.
Parameters
source a string identifying a source to connect to
ct a pointer to a CumbiaWebSocket instance
Implements CuWSActionFactoryI.
References CuWsActionWriter::setConfiguration(), and CuWsActionWriter::setWriteValue().
getType()
CuWSActionI::Type CuWSActionWriterFactory::getType () const virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implements CuWSActionFactoryI.
References CuWSActionI::Writer.
setConfiguration()
void CuWSActionWriterFactory::setConfiguration (const CuData & conf)
Referenced by CuWsControlsWriter::execute().
setWriteValue()
void CuWSActionWriterFactory::setWriteValue (const CuVariant & write_val)
Referenced by CuWsControlsWriter::execute().
The documentation for this class was generated from the following files:
cuwsactionfactories.h
cuwsactionfactories.cpp