cumbia-websocket: CuWsControlsWriter Class Reference
CuWsControlsWriter Class Reference
implements CuControlsWriterA abstract class and provides an interface to connect a Tango writer to a target.
#include <cuwscontrolswriter.h>
Public Member Functions
CuWsControlsWriter (Cumbia *cumbia_tango, CuDataListener *tl)
class constructor that's configured with CumbiaWebSocket and CuDataListener instances
virtual ~CuWsControlsWriter ()
the class destructor.
QString target () const
returns the configured target, or an empty string
void clearTarget ()
remove the configured target, if any.
void setTarget (const QString &s)
connect the writer to the Tango control system target
virtual void execute ()
execute the target configured with setTarget. The value to write is taken from the return value of getArgs.
void sendData (const CuData &d)
This is not implemented yet.
void getData (CuData &d_ino) const
This is not implemented yet.
void setOptions (const CuData &o)
set the options on the writer (before setTarget)
Detailed Description
implements CuControlsWriterA abstract class and provides an interface to connect a Tango writer to a target.
Built with references to CumbiaTango and CuDataListener, CuWsWriter implements CuControlsWriterA and connects a writer to the Tango control system through the setTarget method. setOptions can discretionary be called before setTarget.
Parameters and configuration can be sent and queried with sendData and getData respectively.
clearTarget can finally be called in order disconnect a writer, and if CuWsWriter is deleted, clearTarget is called automatically.
Constructor & Destructor Documentation
CuWsControlsWriter()
CuWsControlsWriter::CuWsControlsWriter (Cumbia * cu_ws, CuDataListener * tl)
class constructor that's configured with CumbiaWebSocket and CuDataListener instances
Parameters
cu_ws a pointer to a CumbiaWebSocket instance
CuDataListener a pointer to an object implementing the CuDataListener interface
References CumbiaWebSocket::CumbiaWSType.
~CuWsControlsWriter()
CuWsControlsWriter::~CuWsControlsWriter () virtual
the class destructor.
The class destructors sets the invalidate flag on the listener, so that it won't be used later, and calls clearTarget
References clearTarget().
Member Function Documentation
clearTarget()
void CuWsControlsWriter::clearTarget ()
remove the configured target, if any.
unlinks the attribute configuration listener
unlinks the writer listener
References CuWSActionI::ReaderConfig, and CuWSActionI::Writer.
Referenced by ~CuWsControlsWriter().
execute()
void CuWsControlsWriter::execute () virtual
execute the target configured with setTarget. The value to write is taken from the return value of getArgs.
A CuTangoWriterFactory is used to start an activity managed by CumbiaWebSocket. The activity deals with writing the value on an attribute or imparting a command once.
References CuWSActionWriterFactory::setConfiguration(), and CuWSActionWriterFactory::setWriteValue().
getData()
void CuWsControlsWriter::getData (CuData & d_ino) const
This is not implemented yet.
sendData()
void CuWsControlsWriter::sendData (const CuData & d)
This is not implemented yet.
setOptions()
void CuWsControlsWriter::setOptions (const CuData & o)
set the options on the writer (before setTarget)
This is usually called by CuWsWriterFactory::create immediately after CuWsWriter is instantiated.
Referenced by CuWsControlsWriterFactory::create().
setTarget()
void CuWsControlsWriter::setTarget (const QString & s)
connect the writer to the Tango control system target
Parameters
s the name of the writer target
References CuWSActionConfFactory::setOptions().
target()
QString CuWsControlsWriter::target () const
returns the configured target, or an empty string
Returns
the configured target or an empty string if setTarget hasn't been called yet.
note
The returned string will contain the actual target, after wildcards have been replaced.
The documentation for this class was generated from the following files:
cuwscontrolswriter.h
cuwscontrolswriter.cpp