cumbia-websocket: CuWsActionWriter Class Reference
CuWsActionWriter Class Reference
#include <cuwsactionwriter.h>
Public Member Functions
CuWsActionWriter (const WSSource &target, CuWSClient *wscli, const QString &http_url)
~CuWsActionWriter ()
void setWriteValue (const CuVariant &w)
void setConfiguration (const CuData &co)
WSSource getSource () const
return a WSSource object that stores information about the Tango source
Type getType () const
returns the type of CuWSActionI implemented
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
size_t dataListenersCount ()
return the number of registered data listeners
void start ()
bool exiting () const
void stop ()
void decodeMessage (const QJsonDocument &json)
Public Member Functions inherited from CuWSActionI
virtual ~CuWSActionI ()
virtual destructor, to make compilers happy
Additional Inherited Members
Public Types inherited from CuWSActionI
enum Type {
Reader = 0, Writer, WriterConfig, DbReadProp,
DbWriteProp
}
Constructor & Destructor Documentation
CuWsActionWriter()
CuWsActionWriter::CuWsActionWriter (const WSSource & target, CuWSClient * wscli, const QString & http_url)
~CuWsActionWriter()
CuWsActionWriter::~CuWsActionWriter ()
Member Function Documentation
addDataListener()
void CuWsActionWriter::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuWSActionI.
dataListenersCount()
size_t CuWsActionWriter::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuWSActionI.
decodeMessage()
void CuWsActionWriter::decodeMessage (const QJsonDocument & json) virtual
Implements CuWSActionI.
References CumbiaWSWorld::json_decode(), and stop().
exiting()
bool CuWsActionWriter::exiting () const virtual
Implements CuWSActionI.
getSource()
WSSource CuWsActionWriter::getSource () const virtual
return a WSSource object that stores information about the Tango source
Returns
WSSource, an object storing information on the Tango source
Implements CuWSActionI.
getType()
CuWSActionI::Type CuWsActionWriter::getType () const virtual
returns the type of CuWSActionI implemented
Returns
one of the values from the Type enum
Implements CuWSActionI.
References CuWSActionI::Writer.
removeDataListener()
void CuWsActionWriter::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuWSActionI.
References stop().
setConfiguration()
void CuWsActionWriter::setConfiguration (const CuData & co)
Referenced by CuWSActionWriterFactory::create().
setWriteValue()
void CuWsActionWriter::setWriteValue (const CuVariant & w)
Referenced by CuWSActionWriterFactory::create().
start()
void CuWsActionWriter::start () virtual
Implements CuWSActionI.
stop()
void CuWsActionWriter::stop () virtual
Implements CuWSActionI.
Referenced by decodeMessage(), and removeDataListener().
The documentation for this class was generated from the following files:
cuwsactionwriter.h
cuwsactionwriter.cpp