cumbia-websocket: CuWSReader Class Reference
CuWSReader Class Reference
#include <cuwsreader.h>
Public Member Functions
CuWSReader (Cumbia *cumbia_tango, CuDataListener *tl)
virtual ~CuWSReader ()
void setSource (const QString &s)
QString source () const
void unsetSource ()
void setOptions (const CuData &o)
CuData getOptions () const
virtual void sendData (const CuData &d)
virtual void getData (CuData &d_ino) const
Constructor & Destructor Documentation
CuWSReader()
CuWSReader::CuWSReader (Cumbia * cumbia_tango, CuDataListener * tl)
References CumbiaWebSocket::CumbiaWSType.
~CuWSReader()
CuWSReader::~CuWSReader () virtual
References source(), and unsetSource().
Member Function Documentation
getData()
void CuWSReader::getData (CuData & d_ino) const virtual
getOptions()
CuData CuWSReader::getOptions () const
sendData()
void CuWSReader::sendData (const CuData & d) virtual
setOptions()
void CuWSReader::setOptions (const CuData & o)
Referenced by CuWSReaderFactory::create().
setSource()
void CuWSReader::setSource (const QString & s)
References CuWSActionReaderFactory::setOptions().
source()
QString CuWSReader::source () const
Referenced by ~CuWSReader().
unsetSource()
void CuWSReader::unsetSource ()
References CuWSActionI::Reader.
Referenced by ~CuWSReader().
The documentation for this class was generated from the following files:
cuwsreader.h
cuwsreader.cpp