cumbia-websocket: CuWsControlsWriterFactory Class Reference
CuWsControlsWriterFactory Class Reference
implements CuControlsWriterFactoryI and creates Websocket writers Given a pointer to a Cumbia object and a CuDataListener, the create method instantiates and returns a CuWsWriter, that implements CuControlsWriterA interface. If setOptions is called before create, the options are set on the CuControlsWriterA.
#include <cuwscontrolswriter.h>
Public Member Functions
CuWsControlsWriterFactory ()
virtual ~CuWsControlsWriterFactory ()
the class destructor
CuControlsWriterA * create (Cumbia *, CuDataListener *l) const
creates and returns a new CuWsWriter, configured with the given Cumbia and CuDataListener.
CuControlsWriterFactoryI * clone () const
clones the writer factory, allocating a new one with the same options
void setOptions (const CuData &o)
set options through a CuData bundle. They are then passed to the CuWsWriter instantiated and returned by the create method
Detailed Description
implements CuControlsWriterFactoryI and creates Websocket writers Given a pointer to a Cumbia object and a CuDataListener, the create method instantiates and returns a CuWsWriter, that implements CuControlsWriterA interface. If setOptions is called before create, the options are set on the CuControlsWriterA.
CuWsWriterFactory can be cloned by means of the clone method.
Constructor & Destructor Documentation
CuWsControlsWriterFactory()
CuWsControlsWriterFactory::CuWsControlsWriterFactory ()
the class constructor
Referenced by clone().
~CuWsControlsWriterFactory()
CuWsControlsWriterFactory::~CuWsControlsWriterFactory () virtual
the class destructor
Member Function Documentation
clone()
CuControlsWriterFactoryI * CuWsControlsWriterFactory::clone () const
clones the writer factory, allocating a new one with the same options
Returns
a new CuWsWriterFactory with options copied from this object
References CuWsControlsWriterFactory().
create()
CuControlsWriterA * CuWsControlsWriterFactory::create (Cumbia * c, CuDataListener * l) const
creates and returns a new CuWsWriter, configured with the given Cumbia and CuDataListener.
Call setOptions before create to configure the writer. See setOptions for a list of predefined keys.
Parameters
c a pointer to the CumbiaWebSocket object
l a pointer to an object implementing the CuDataListener interface
Returns
a CuWsWriter, an implementation of CuControlsWriterA abstract class
References CuWsControlsWriter::setOptions().
setOptions()
void CuWsControlsWriterFactory::setOptions (const CuData & o)
set options through a CuData bundle. They are then passed to the CuWsWriter instantiated and returned by the create method
Parameters
o a CuData bundle of key/value pairs
Key/value pairs
no-properties [bool, default: false]. If true, skip attribute configuration in setTarget.
fetch_props [std::vector<std::string>, default: empty] list of attribute properties to fetch from the database during configuration. The no-properties key must be left to false (default).
See also
create
The documentation for this class was generated from the following files:
cuwscontrolswriter.h
cuwscontrolswriter.cpp