cumbia-websocket: CumbiaWSWorld Class Reference
CumbiaWSWorld Class Reference
#include <cumbiawsworld.h>
Public Member Functions
CumbiaWSWorld ()
void setSrcPatterns (const std::vector< std::string > &pat_regex)
std::vector< std::string > srcPatterns () const
bool source_valid (const std::string &s)
bool json_decode (const QJsonDocument &json, CuData &out)
Constructor & Destructor Documentation
CumbiaWSWorld()
CumbiaWSWorld::CumbiaWSWorld ()
Member Function Documentation
json_decode()
bool CumbiaWSWorld::json_decode (const QJsonDocument & json, CuData & out)
Referenced by CuWsActionConf::decodeMessage(), CuWsActionWriter::decodeMessage(), and CuWSActionReader::decodeMessage().
setSrcPatterns()
void CumbiaWSWorld::setSrcPatterns (const std::vector< std::string > & pat_regex)
source_valid()
bool CumbiaWSWorld::source_valid (const std::string & s)
Referenced by CumbiaWebSocket::addAction().
srcPatterns()
std::vector< std::string > CumbiaWSWorld::srcPatterns () const
The documentation for this class was generated from the following files:
cumbiawsworld.h
cumbiawsworld.cpp