cumbia-websocket: CumbiaWebSocket Class Reference
CumbiaWebSocket Class Reference
#include <cumbiawebsocket.h>
Public Types
enum Type { CumbiaWSType = Cumbia::CumbiaUserType + 12 }
Public Member Functions
CumbiaWebSocket (const QString &websocket_url, const QString &http_url, CuThreadFactoryImplI *tfi, CuThreadsEventBridgeFactory_I *teb)
~CumbiaWebSocket ()
CuThreadFactoryImplI * getThreadFactoryImpl () const
CuThreadsEventBridgeFactory_I * getThreadEventsBridgeFactory () const
QString httpUrl () const
QString websocketUrl () const
virtual int getType () const
CuWSClient * websocketClient () const
void addAction (const std::string &source, CuDataListener *l, const CuWSActionFactoryI &f)
void unlinkListener (const string &source, CuWSActionI::Type t, CuDataListener *l)
CuWSActionI * findAction (const std::string &source, CuWSActionI::Type t) const
virtual void onUpdate (const QString &message)
Callback invoked by CuWSClient when a new message is received from the websocket.
Member Enumeration Documentation
Type
enum CumbiaWebSocket::Type
Enumerator
CumbiaWSType
Constructor & Destructor Documentation
CumbiaWebSocket()
CumbiaWebSocket::CumbiaWebSocket (const QString & websocket_url, const QString & http_url, CuThreadFactoryImplI * tfi, CuThreadsEventBridgeFactory_I * teb)
~CumbiaWebSocket()
CumbiaWebSocket::~CumbiaWebSocket ()
Member Function Documentation
addAction()
void CumbiaWebSocket::addAction (const std::string & source, CuDataListener * l, const CuWSActionFactoryI & f)
References CuWSActionI::addDataListener(), CuWSActionFactoryService::CuWSActionFactoryServiceType, CuWSActionFactoryService::findActive(), CuWSActionFactoryI::getType(), CuWSActionFactoryService::registerAction(), CumbiaWSWorld::source_valid(), and CuWSActionI::start().
findAction()
CuWSActionI * CumbiaWebSocket::findAction (const std::string & source, CuWSActionI::Type t) const
References CuWSActionFactoryService::CuWSActionFactoryServiceType, and CuWSActionFactoryService::findActive().
Referenced by onUpdate().
getThreadEventsBridgeFactory()
CuThreadsEventBridgeFactory_I * CumbiaWebSocket::getThreadEventsBridgeFactory () const
getThreadFactoryImpl()
CuThreadFactoryImplI * CumbiaWebSocket::getThreadFactoryImpl () const
getType()
int CumbiaWebSocket::getType () const virtual
References CumbiaWSType.
httpUrl()
QString CumbiaWebSocket::httpUrl () const
onUpdate()
void CumbiaWebSocket::onUpdate (const QString & message) virtual
Callback invoked by CuWSClient when a new message is received from the websocket.
The received message is used to build a JSon document in order to extract the source. The decoding of the message is taken over by the CuWSActionI with the given source
See also
CuWSClient::onMessageReceived
Implements CuWSClientListener.
References CuWSActionI::decodeMessage(), findAction(), and CuWSActionI::Reader.
unlinkListener()
void CumbiaWebSocket::unlinkListener (const string & source, CuWSActionI::Type t, CuDataListener * l)
References CuWSActionFactoryService::CuWSActionFactoryServiceType, and CuWSActionFactoryService::find().
websocketClient()
CuWSClient * CumbiaWebSocket::websocketClient () const
websocketUrl()
QString CumbiaWebSocket::websocketUrl () const
The documentation for this class was generated from the following files:
cumbiawebsocket.h
cumbiawebsocket.cpp