cumbia-tango: CuPollingService Class Reference
CuPollingService Class Reference
#include <cupollingservice.h>
Public Types
enum Type { CuPollingServiceType = CuServices::User + 26 }
Public Member Functions
CuPollingService ()
virtual ~CuPollingService ()
CuPoller * getPoller (CumbiaTango *cu_t, int period)
void registerAction (CumbiaTango *ct, const TSource &tsrc, int period, CuTangoActionI *action, const CuData &options)
void unregisterAction (int period, CuTangoActionI *action)
bool actionRegistered (CuTangoActionI *ac, int period)
virtual std::string getName () const
virtual CuServices::Type getType () const
Member Enumeration Documentation
Type
enum CuPollingService::Type
Enumerator
CuPollingServiceType
Constructor & Destructor Documentation
CuPollingService()
CuPollingService::CuPollingService ()
~CuPollingService()
CuPollingService::~CuPollingService () virtual
Member Function Documentation
actionRegistered()
bool CuPollingService::actionRegistered (CuTangoActionI * ac, int period)
References CuPoller::actionRegistered().
Referenced by CuTReader::onResult(), and CuTReader::setRefreshMode().
getName()
std::string CuPollingService::getName () const virtual
getPoller()
CuPoller * CuPollingService::getPoller (CumbiaTango * cu_t, int period)
Referenced by registerAction(), and CuTReader::sendData().
getType()
CuServices::Type CuPollingService::getType () const virtual
References CuPollingServiceType.
registerAction()
void CuPollingService::registerAction (CumbiaTango * ct, const TSource & tsrc, int period, CuTangoActionI * action, const CuData & options)
References getPoller(), and CuPoller::registerAction().
unregisterAction()
void CuPollingService::unregisterAction (int period, CuTangoActionI * action)
References CuPoller::count(), and CuPoller::unregisterAction().
The documentation for this class was generated from the following files:
cupollingservice.h
cupollingservice.cpp