cumbia-tango: TDevice Class Reference
TDevice Class Reference
#include <tdevice.h>
Public Member Functions
~TDevice ()
TDevice (const std::string &name)
void addRef ()
int removeRef ()
Tango::DeviceProxy * getDevice () const
std::string getMessage () const
bool isValid () const
bool operator== (const TDevice &other) const
std::string getName () const
int refCnt () const
Constructor & Destructor Documentation
~TDevice()
TDevice::~TDevice ()
TDevice()
TDevice::TDevice (const std::string & name)
References CuTangoWorld::strerror().
Member Function Documentation
addRef()
void TDevice::addRef ()
Referenced by CuDeviceFactoryService::getDevice(), and CuTThreadDevices::getDevice().
getDevice()
Tango::DeviceProxy * TDevice::getDevice () const
getMessage()
std::string TDevice::getMessage () const
getName()
std::string TDevice::getName () const
isValid()
bool TDevice::isValid () const
operator==()
bool TDevice::operator== (const TDevice & other) const
refCnt()
int TDevice::refCnt () const
removeRef()
int TDevice::removeRef ()
Referenced by CuDeviceFactoryService::removeRef(), and CuTThreadDevices::removeRef().
The documentation for this class was generated from the following files:
tdevice.h
tdevice.cpp