cumbia-tango: CuTangoActionFactoryI Class Reference
CuTangoActionFactoryI Class Reference abstract
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
#include <cutangoactionfactoryi.h>
Public Member Functions
CuTangoActionFactoryI ()
virtual CuTangoActionI * create (const std::string &source, CumbiaTango *ct) const =0
virtual CuTangoActionI::Type getType () const =0
Return the type of action that the factory creates.
Detailed Description
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
Notable implementations
CuTangoReaderFactory
CuTangoWriterFactory
CuTangoAttConfFactory
Constructor & Destructor Documentation
CuTangoActionFactoryI()
CuTangoActionFactoryI::CuTangoActionFactoryI () inline
Member Function Documentation
create()
virtual CuTangoActionI* CuTangoActionFactoryI::create (const std::string & source, CumbiaTango * ct) const pure virtual
Pure virtual method that must be implemented by subclasses to return a valid CuTangoActionI instance.
Parameters
source a string identifying a source to connect to
ct a pointer to a CumbiaTango instance
Implemented in CuTWriterConfFactory, CuTReaderConfFactory, CuTangoWriterFactory, and CuTangoReaderFactory.
Referenced by CuActionFactoryService::registerAction().
getType()
virtual CuTangoActionI::Type CuTangoActionFactoryI::getType () const pure virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implemented in CuTWriterConfFactory, CuTReaderConfFactory, CuTangoWriterFactory, and CuTangoReaderFactory.
Referenced by CumbiaTango::addAction(), and CuActionFactoryService::registerAction().
The documentation for this class was generated from the following file:
cutangoactionfactoryi.h