cumbia-tango: CuTangoWorldConfig Class Reference
CuTangoWorldConfig Class Reference
A class used to store configuration for Tango states color and name, Tango AttrQuality color and name and a color to associate to a successful operation.
#include <cutango-world-config.h>
Public Member Functions
CuTangoWorldConfig ()
virtual ~CuTangoWorldConfig ()
void setStateColors (const std::vector< std::string > &)
void setStateColorName (Tango::DevState, const std::string &)
const std::string stateColorName (Tango::DevState) const
int numStates () const
const std::string qualityColor (Tango::AttrQuality) const
void setQualityColor (Tango::AttrQuality, const std::string &)
int qualityColorCount () const
void setStateString (Tango::DevState, const std::string &)
const std::string stateString (Tango::DevState) const
std::string successColor (bool success) const
void setSuccessColor (bool success, const std::string &colorname)
void setQualityString (Tango::AttrQuality, std::string)
std::string qualityString (Tango::AttrQuality) const
std::map< Tango::DevState, std::string > stateStrings () const
std::map< Tango::DevState, std::string > stateColorNames () const
std::map< Tango::AttrQuality, std::string > qualityStrings () const
std::map< Tango::AttrQuality, std::string > qualityColorNames () const
void setOverrideValuesAttributePropertyName (const std::string &name)
set the attribute property name for the QTangoAutoConfiguration "values" retrieval
std::string valuesAttributePropertyName () const
Detailed Description
A class used to store configuration for Tango states color and name, Tango AttrQuality color and name and a color to associate to a successful operation.
values
State names association table
[Tango::ON] = "ON"; [Tango::OFF] = "OFF"; [Tango::CLOSE] = "CLOSED"; [Tango::OPEN] = "OPENED"; [Tango::INSERT] = "INSERT"; [Tango::EXTRACT] = "EXTRACT"; [Tango::MOVING] = "MOVING"; [Tango::STANDBY] = "STANDBY"; [Tango::FAULT] = "FAULT"; [Tango::INIT] = "INIT"; [Tango::RUNNING] = "RUNNING"; [Tango::ALARM] = "ALARM"; [Tango::DISABLE] = "DISABLE"; [Tango::UNKNOWN] = "UNKNOWN";
State color association table
Several white versions are defined in order to easily map the color name to a different QColor in graphical applications.
[Tango::ON] = "green"; [Tango::OFF] = "white"; [Tango::CLOSE] = "white1"; [Tango::OPEN] = "white2"; [Tango::INSERT] = "white3"; [Tango::EXTRACT] = "white4"; [Tango::MOVING] = "blue"; [Tango::STANDBY] = "yellow"; [Tango::FAULT] = "red"; [Tango::INIT] = "blue"; [Tango::RUNNING] = "green"; [Tango::ALARM] = "orange"; [Tango::DISABLE] = "gray"; [Tango::UNKNOWN] = "darkGray";
Quality names
[Tango::ATTR_VALID] = "ATTR_VALID"; [Tango::ATTR_INVALID] = "ATTR_INVALID"; [Tango::ATTR_ALARM] = "ATTR_ALARM"; [Tango::ATTR_CHANGING] = "ATTR_CHANGING"; [Tango::ATTR_WARNING] = "ATTR_WARNING";
Quality colors
[Tango::ATTR_VALID] = "white"; [Tango::ATTR_INVALID] = "gray"; [Tango::ATTR_ALARM] = "red"; [Tango::ATTR_CHANGING] = "blue"; [Tango::ATTR_WARNING] = "orange";
Constructor & Destructor Documentation
CuTangoWorldConfig()
CuTangoWorldConfig::CuTangoWorldConfig ()
~CuTangoWorldConfig()
CuTangoWorldConfig::~CuTangoWorldConfig () virtual
Member Function Documentation
numStates()
int CuTangoWorldConfig::numStates () const
qualityColor()
const std::string CuTangoWorldConfig::qualityColor (Tango::AttrQuality q) const
qualityColorCount()
int CuTangoWorldConfig::qualityColorCount () const
qualityColorNames()
std::map< Tango::AttrQuality, std::string > CuTangoWorldConfig::qualityColorNames () const
qualityString()
std::string CuTangoWorldConfig::qualityString (Tango::AttrQuality q) const
qualityStrings()
std::map< Tango::AttrQuality, std::string > CuTangoWorldConfig::qualityStrings () const
setOverrideValuesAttributePropertyName()
void CuTangoWorldConfig::setOverrideValuesAttributePropertyName (const std::string & name)
set the attribute property name for the QTangoAutoConfiguration "values" retrieval
This is a work around to let QTangoAutoConfiguration provide the string list associated to the attribute property values, even if the attribute property hasn't got the standard name values.
setQualityColor()
void CuTangoWorldConfig::setQualityColor (Tango::AttrQuality q, const std::string & c)
setQualityString()
void CuTangoWorldConfig::setQualityString (Tango::AttrQuality q, std::string s)
setStateColorName()
void CuTangoWorldConfig::setStateColorName (Tango::DevState s, const std::string & c)
setStateColors()
void CuTangoWorldConfig::setStateColors (const std::vector< std::string > & v)
setStateString()
void CuTangoWorldConfig::setStateString (Tango::DevState s, const std::string & str)
setSuccessColor()
void CuTangoWorldConfig::setSuccessColor (bool success, const std::string & colorname)
stateColorName()
const std::string CuTangoWorldConfig::stateColorName (Tango::DevState s) const
Referenced by CuTangoWorld::extractData(), and CuTangoWorld::extractData().
stateColorNames()
std::map< Tango::DevState, std::string > CuTangoWorldConfig::stateColorNames () const
stateString()
const std::string CuTangoWorldConfig::stateString (Tango::DevState s) const
Referenced by CuTangoWorld::extractData(), and CuTangoWorld::extractData().
stateStrings()
std::map< Tango::DevState, std::string > CuTangoWorldConfig::stateStrings () const
successColor()
std::string CuTangoWorldConfig::successColor (bool success) const
Referenced by CuTangoWorld::get_att_config(), CuTangoWorld::get_att_props(), CuTangoWorld::read_att(), and CuTangoWorld::read_atts().
valuesAttributePropertyName()
std::string CuTangoWorldConfig::valuesAttributePropertyName () const
The documentation for this class was generated from the following files:
cutango-world-config.h
cutango-world-config.cpp