cumbia-tango: CuTAttConfigActivity Class Reference
CuTAttConfigActivity Class Reference
#include <cutattconfigactivity.h>
Public Types
enum Type { CuAttConfigActivityType = CuActivity::User + 5 }
Public Member Functions
CuTAttConfigActivity (const CuData &tok, CuDeviceFactoryService *df)
void setDesiredAttributeProperties (const std::vector< std::string > &props)
virtual ~CuTAttConfigActivity ()
int getType () const
void event (CuActivityEvent *e)
bool matches (const CuData &token) const
int repeat () const
Protected Member Functions
void init ()
void execute ()
void onExit ()
Member Enumeration Documentation
Type
enum CuTAttConfigActivity::Type
Enumerator
CuAttConfigActivityType
Constructor & Destructor Documentation
CuTAttConfigActivity()
CuTAttConfigActivity::CuTAttConfigActivity (const CuData & tok, CuDeviceFactoryService * df)
~CuTAttConfigActivity()
CuTAttConfigActivity::~CuTAttConfigActivity () virtual
Member Function Documentation
event()
void CuTAttConfigActivity::event (CuActivityEvent * e)
execute()
void CuTAttConfigActivity::execute () protected
References CuTangoWorld::error(), CuTangoWorld::fillThreadInfo(), CuTangoWorld::get_att_config(), CuTangoWorld::get_att_props(), CuTangoWorld::get_command_info(), and CuTangoWorld::getLastMessage().
getType()
int CuTAttConfigActivity::getType () const
References CuAttConfigActivityType.
init()
void CuTAttConfigActivity::init () protected
matches()
bool CuTAttConfigActivity::matches (const CuData & token) const
onExit()
void CuTAttConfigActivity::onExit () protected
References CuTangoWorld::fillThreadInfo().
repeat()
int CuTAttConfigActivity::repeat () const
setDesiredAttributeProperties()
void CuTAttConfigActivity::setDesiredAttributeProperties (const std::vector< std::string > & props)
The documentation for this class was generated from the following files:
cutattconfigactivity.h
cutattconfigactivity.cpp