cumbia-tango: CuTReader Class Reference
CuTReader Class Reference
Low level class to read tango attributes and commands with output arguments.
#include <cutreader.h>
Public Types
enum RefreshMode {
PolledRefresh = 0x01, ChangeEventRefresh =0x02, ArchiveEventRefresh =0x04, PeriodicEventRefresh =0x08,
Manual =0x10
}
The reader refresh mode.
Public Types inherited from CuTangoActionI
enum Type {
Reader = 0, Writer, ReaderConfig, WriterConfig,
DbReadProp, DbWriteProp
}
list of types of actions
Public Member Functions
CuTReader (const TSource &src, CumbiaTango *ct)
~CuTReader ()
void onProgress (int step, int total, const CuData &data)
progress notification callback
void onResult (const CuData &data)
void onResult (const std::vector< CuData > &datalist)
CuData getToken () const
returns the CuData storing the token that identifies this action
TSource getSource () const
CuTangoActionI::Type getType () const
returns the type of CuTangoActionI implemented
void sendData (const CuData &data)
Send data with parameters to configure the reader.
void getData (CuData &inout) const
Get parameters from the reader.
void setRefreshMode (RefreshMode rm, int period=-1)
set or change the reader's refresh mode
std::string refreshModeStr () const
RefreshMode refreshMode () const
void setPeriod (int millis)
void setOptions (const CuData &options)
CuTReader::setOptions sets the options on the reader.
int period () const
void start ()
creates and registers a CuEventActivity or a CuPollingActivity to read from the Tango control system
void stop ()
the method where activities are unregistered from Cumbia
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
size_t dataListenersCount ()
return the number of registered data listeners
bool exiting () const
returns true if the action has been stopped and it's exiting
bool isEventRefresh (RefreshMode rm) const
returns true if the parameter is an event driven RefreshMode, false otherwise.
Public Member Functions inherited from CuTangoActionI
virtual ~CuTangoActionI ()
virtual destructor, to make compilers happy
Detailed Description
Low level class to read tango attributes and commands with output arguments.
This class implements the CuTangoActionI interface, which in turn implements CuThreadListener.
Programmers of graphical interfaces should employ cumbia-tango-controls CuTControlsReader higher level class to create and communicate with CuTReader.
Function
Instantiates and registers (i.e. starts) either a CuEventActivity or a CuPollingActivity, according to the desired RefreshMode. If the CuEventActivity fails subscribing to the Tango event system, it is replaced by CuPollingActivity (in CuTReader::onResult). In that case, no error event is delivered to CuDataListeners.
Note
CuTReader holds a pointer to the current activity (CuTReaderPrivate: current_activity). Activity and CuTReader's life are independent from each other: if the CuActivity::CuADeleteOnExit flag is active (as in CuPollingActivity), the activity is deleted by CuThread.
Important
As a consequence of the note above, activities must not exit before CuTReader::stop is called. The proper way to stop the activity associated to the reader is through CuTReader::stop.
Member Enumeration Documentation
RefreshMode
enum CuTReader::RefreshMode
The reader refresh mode.
Each refresh mode reflects the way a tango attribute can be read. Commands are always polled with a given period (default: 1000ms). The preferred read mode for attributes is by events (ChangeEventRefresh). If they are not available, the second choice mode is PolledRefresh.
Manual mode starts (or switches to) a polling activity that is immediately paused. A specific argument must be specified to sendData to trigger a manual reading.
Enumerator
PolledRefresh
ChangeEventRefresh
ArchiveEventRefresh
PeriodicEventRefresh
Manual
Constructor & Destructor Documentation
CuTReader()
CuTReader::CuTReader (const TSource & src, CumbiaTango * ct)
References ChangeEventRefresh.
~CuTReader()
CuTReader::~CuTReader ()
Member Function Documentation
addDataListener()
void CuTReader::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuTangoActionI.
dataListenersCount()
size_t CuTReader::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuTangoActionI.
exiting()
bool CuTReader::exiting () const virtual
returns true if the action has been stopped and it's exiting
Returns
true if the action is exiting (normally, stop has been called), false otherwise
Used by CuActionFactoryService::unregisterAction to check whether the action is still running before unregistering.
Implements CuTangoActionI.
getData()
void CuTReader::getData (CuData & d_inout) const virtual
Get parameters from the reader.
Parameters
d_inout a reference to a CuData bundle containing the parameter names as keys. getData will associate the values to the keys. Unrecognized keys are ignored.
Valid keys
"period": returns an int with the polling period
"refresh_mode": returns a CuTReader::RefreshMode that can be converted to int
"mode": returns a string representation of the CuTReader::RefreshMode
See also
sendData
Implements CuTangoActionI.
References refreshModeStr().
getSource()
TSource CuTReader::getSource () const virtual
returns the tango source (TSource)
Returns
a TSource object that describes the Tango source
Implements CuTangoActionI.
getToken()
CuData CuTReader::getToken () const
returns the CuData storing the token that identifies this action
Returns
a CuData with the following key/value pairs
"source" --> the name of the source (string)
"type" --> a constant string: "reader"
Referenced by sendData().
getType()
CuTangoActionI::Type CuTReader::getType () const virtual
returns the type of CuTangoActionI implemented
Returns
one of the values from the Type enum
Implements CuTangoActionI.
References CuTangoActionI::Reader.
Referenced by onResult().
isEventRefresh()
bool CuTReader::isEventRefresh (CuTReader::RefreshMode rm) const
returns true if the parameter is an event driven RefreshMode, false otherwise.
Parameters
rm a value picked from CuTReader::RefreshMode enumeration
Returns
true if rm is ChangeEventRefresh, PeriodicEventRefresh or ArchiveEventRefresh, false otherwise
References ArchiveEventRefresh, ChangeEventRefresh, and PeriodicEventRefresh.
Referenced by sendData(), and setRefreshMode().
onProgress()
void CuTReader::onProgress (int step, int total, const CuData & data)
progress notification callback
Parameters
step the completed steps in the background
total the total number of steps
data CuData with data from the background activity
The current implementation does nothing
onResult() [1/2]
void CuTReader::onResult (const CuData & data)
References CuPollingService::actionRegistered(), CuActionFactoryService::CuActionFactoryServiceType, CuPollingService::CuPollingServiceType, getType(), PolledRefresh, and CuActionFactoryService::unregisterAction().
onResult() [2/2]
void CuTReader::onResult (const std::vector< CuData > & datalist)
period()
int CuTReader::period () const
Referenced by sendData(), and setRefreshMode().
refreshMode()
CuTReader::RefreshMode CuTReader::refreshMode () const
refreshModeStr()
string CuTReader::refreshModeStr () const
References ArchiveEventRefresh, ChangeEventRefresh, Manual, PeriodicEventRefresh, and PolledRefresh.
Referenced by getData().
removeDataListener()
void CuTReader::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuTangoActionI.
References stop().
sendData()
void CuTReader::sendData (const CuData & data) virtual
Send data with parameters to configure the reader.
Parameters
data a CuData bundle with the settings to apply to the reader.
Valid keys
"period": integer. Change the polling period, if the refresh mode is CuTReader::PolledRefresh
"refresh_mode". A CuTReader::RefreshMode value to change the current refresh mode.
See also
getData
Implements CuTangoActionI.
References CuPollingActivity::CuPollingActivityType, CuPollingService::CuPollingServiceType, CuPollingService::getPoller(), getToken(), isEventRefresh(), period(), PolledRefresh, and setRefreshMode().
setOptions()
void CuTReader::setOptions (const CuData & options)
CuTReader::setOptions sets the options on the reader.
Parameters
options CuData key/value bundle
Called by CuTangoActionI *CuTangoReaderFactory::create
References setPeriod(), and setRefreshMode().
Referenced by CuTangoReaderFactory::create().
setPeriod()
void CuTReader::setPeriod (int millis)
Referenced by setOptions().
setRefreshMode()
void CuTReader::setRefreshMode (CuTReader::RefreshMode rm, int period = -1)
set or change the reader's refresh mode
If the reading activity hasn't been started yet, the mode is saved for later. If an activity is already running and the requested mode is different, the current activity is unregistered and a new one is started.
Parameters
rm a value chosen from CuTReader::RefreshMode.
References CuPollingService::actionRegistered(), CuPollingService::CuPollingServiceType, isEventRefresh(), Manual, period(), and PolledRefresh.
Referenced by sendData(), and setOptions().
start()
void CuTReader::start () virtual
creates and registers a CuEventActivity or a CuPollingActivity to read from the Tango control system
Note
This function is internally used by the library. Clients shouldn't need to deal with it.
This method
fills in a CuData called activity token, that will be passed to the CuWriteActivity
fills in a CuData called thread token, used to register the CuWriteActivity and make the activity shared between writers with the same target.
instantiates and registers (i.e. starts) either a CuEventActivity or a CuPollingActivity, according to the RefreshMode value. If the CuEventActivity fails subscribing to the Tango event system, it is replaced by CuPollingActivity (in CuTReader::onResult)
Note
start is usually called by CumbiaTango::addAction, which in turn is called by qumbia-tango-controls CuTControlsReader::setSource
If the refresh mode is Manual, a CuPollingActivity is started, with a very long period. To trigger a read in Manual mode, use sendData with a CuData containing a key named "*read*". See sendData for further details.
Implements CuTangoActionI.
References ChangeEventRefresh.
stop()
void CuTReader::stop () virtual
the method where activities are unregistered from Cumbia
This is the place where activities are unregistered from Cumbia by the Cumbia::unregisterActivity method
Examples
CuTReader::stop
CuTWriter::stop
See also Cumbia::unregisterActivity
Implements CuTangoActionI.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cutreader.h
cutreader.cpp