cumbia-tango: CuTangoActionI Class Reference
CuTangoActionI Class Reference abstract
an interface for a Tango action, typically a reader or a writer are implementors
#include <cutangoactioni.h>
Public Types
enum Type {
Reader = 0, Writer, ReaderConfig, WriterConfig,
DbReadProp, DbWriteProp
}
list of types of actions
Public Member Functions
virtual ~CuTangoActionI ()
virtual destructor, to make compilers happy
virtual TSource getSource () const =0
return a TSource object that stores information about the Tango source
virtual Type getType () const =0
returns the type of CuTangoActionI implemented
virtual void addDataListener (CuDataListener *l)=0
insert a CuDataListener to the list of listeners of data updates
virtual void removeDataListener (CuDataListener *l)=0
remove a CuDataListener from the list of listeners of data updates
virtual size_t dataListenersCount ()=0
return the number of registered data listeners
virtual void start ()=0
the method where activities are created and registered
virtual void stop ()=0
the method where activities are unregistered from Cumbia
virtual void sendData (const CuData &data)=0
subclasses will implement the necessary code to set data on themselves or to the activities
virtual void getData (CuData &d_inout) const =0
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
virtual bool exiting () const =0
returns true if the action has been stopped and it's exiting
Detailed Description
an interface for a Tango action, typically a reader or a writer are implementors
A CuTangoActionI describes what readers or writers usually do. They do actions, and they must adhere to this interface that requires to
add or remove data listeners, that are updated by CuThreadListener::onProgress and CuThreadListener::onResult
declare the type of action (Reader, Writer, AttConfig, ... - see the Type enum)
provide a start and a stop method where activities are instantiated and registered with Cumbia::registerActivity and finally unregistered with Cumbia::unregisterActivity
provide an exiting method
Examples
CuTReader and CuTWriter implementations.
Member Enumeration Documentation
Type
enum CuTangoActionI::Type
list of types of actions
the implementors must return one of these values in getType
Enumerator
Reader
Writer
ReaderConfig
WriterConfig
DbReadProp
DbWriteProp
Constructor & Destructor Documentation
~CuTangoActionI()
virtual CuTangoActionI::~CuTangoActionI () inline virtual
virtual destructor, to make compilers happy
Member Function Documentation
addDataListener()
virtual void CuTangoActionI::addDataListener (CuDataListener * l) pure virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implemented in CuTReader, CuTConfiguration, and CuTWriter.
Referenced by CumbiaTango::addAction().
dataListenersCount()
virtual size_t CuTangoActionI::dataListenersCount () pure virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implemented in CuTReader, CuTConfiguration, and CuTWriter.
exiting()
virtual bool CuTangoActionI::exiting () const pure virtual
returns true if the action has been stopped and it's exiting
Returns
true if the action is exiting (normally, stop has been called), false otherwise
Used by CuActionFactoryService::unregisterAction to check whether the action is still running before unregistering.
Implemented in CuTReader, CuTConfiguration, and CuTWriter.
getData()
virtual void CuTangoActionI::getData (CuData & d_inout) const pure virtual
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation as input argument. data will contain additional output fields filled in by the method when it returns.
note
getData must be synchronous: it's called with input arguments (d_inout) and they are filled in within the same method in the same thread. Asynchronous data fetch from an activity executed in a separate thread can be accomplished by sendData in combination with CuDataListener::onUpdate. There, received data will have to be recognised as coming from a specific request and treated accordingly.
Implemented in CuTReader, CuTWriter, and CuTConfiguration.
getSource()
virtual TSource CuTangoActionI::getSource () const pure virtual
return a TSource object that stores information about the Tango source
Returns
TSource, an object storing information on the Tango source
Implemented in CuTReader, CuTConfiguration, and CuTWriter.
Referenced by CuPoller::registerAction().
getType()
virtual Type CuTangoActionI::getType () const pure virtual
returns the type of CuTangoActionI implemented
Returns
one of the values from the Type enum
Implemented in CuTReader, CuTConfiguration, and CuTWriter.
removeDataListener()
virtual void CuTangoActionI::removeDataListener (CuDataListener * l) pure virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implemented in CuTReader, CuTConfiguration, and CuTWriter.
sendData()
virtual void CuTangoActionI::sendData (const CuData & data) pure virtual
subclasses will implement the necessary code to set data on themselves or to the activities
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation
The data can be set locally on the object implementing this interface or can be forwarded to the activity by means of Cumbia::postEvent carrying an argument derived from CuActivityEvent. See CuTReader::sendData for an example
Send a request and receive a response asynchronously
Use sendData in conjunction with CuDataListener::onUpdate, as described in the getData documentation.
Implemented in CuTReader, CuTWriter, and CuTConfiguration.
start()
void CuTangoActionI::start () pure virtual
the method where activities are created and registered
This is the place where activities are created and registered to Cumbia through the method Cumbia::registerActivity.
Examples
CuTReader::start
CuTWriter::start
See also Cumbia::registerActivity
Implemented in CuTReader, CuTConfiguration, and CuTWriter.
Referenced by CumbiaTango::addAction().
stop()
void CuTangoActionI::stop () pure virtual
the method where activities are unregistered from Cumbia
This is the place where activities are unregistered from Cumbia by the Cumbia::unregisterActivity method
Examples
CuTReader::stop
CuTWriter::stop
See also Cumbia::unregisterActivity
Implemented in CuTReader, CuTConfiguration, and CuTWriter.
The documentation for this class was generated from the following files:
cutangoactioni.h
cutangoactioni.cpp