cumbia-tango: regexps Class Reference
regexps Class Reference
#include <tsource.h>
Static Public Member Functions
static std::regex & get_dev_re ()
static std::regex & get_host_re ()
static std::regex & get_freeprop_re ()
static std::regex & get_args_re ()
static std::regex & get_separ_re ()
Member Function Documentation
get_args_re()
static std::regex & regexps::get_args_re () inline static
Referenced by TSource::getArgOptions(), and TSource::rem_args().
get_dev_re()
static std::regex & regexps::get_dev_re () inline static
References TG_DEV_RE.
Referenced by TSource::getDeviceName().
get_freeprop_re()
static std::regex & regexps::get_freeprop_re () inline static
Referenced by TSource::getFreePropObj().
get_host_re()
static std::regex & regexps::get_host_re () inline static
References TGHOST_RE.
Referenced by TSource::getTangoHost(), and TSource::remove_tghost().
get_separ_re()
static std::regex & regexps::get_separ_re () inline static
The documentation for this class was generated from the following file:
tsource.h