cumbia-tango: CuTConfigActivity Class Reference
CuTConfigActivity Class Reference
Activity to get attribute configuration or command info. Optionally, it can perform a one shot attribute read (or command inout) if the option value-only is set to true.
#include <cutconfigactivity.h>
Public Types
enum Type { CuReaderConfigActivityType = CuActivity::UserAType + 5 , CuWriterConfigActivityType }
Public Member Functions
CuTConfigActivity (const TSource &ts, CuDeviceFactory_I *df, Type t, const CuTConfigActivityExecutor_I *tx, const CuData &o, const CuData &tag)
virtual ~CuTConfigActivity ()
void setOptions (const CuData &o)
int getType () const
void event (CuActivityEvent *e)
bool matches (const CuData &token) const
int repeat () const
Protected Member Functions
void init ()
void execute ()
void onExit ()
Detailed Description
Activity to get attribute configuration or command info. Optionally, it can perform a one shot attribute read (or command inout) if the option value-only is set to true.
Member Enumeration Documentation
Type
enum CuTConfigActivity::Type
Enumerator
CuReaderConfigActivityType
CuWriterConfigActivityType
Constructor & Destructor Documentation
CuTConfigActivity()
CuTConfigActivity::CuTConfigActivity (const TSource & ts, CuDeviceFactory_I * df, Type t, const CuTConfigActivityExecutor_I * tx, const CuData & o, const CuData & tag)
~CuTConfigActivity()
CuTConfigActivity::~CuTConfigActivity () virtual
Member Function Documentation
event()
void CuTConfigActivity::event (CuActivityEvent * e)
execute()
void CuTConfigActivity::execute () protected
References CuTangoWorld::cmd_inout(), CuReaderConfigActivityType, CuTangoWorld::error(), CuTangoWorld::ExtractDefault, CuTangoWorld::get_att_props(), CuTangoWorld::getLastMessage(), CuTangoWorld::read_att(), and TSource::SrcCmd.
getType()
int CuTConfigActivity::getType () const
init()
void CuTConfigActivity::init () protected
References CuTThread::CuTThreadType.
matches()
bool CuTConfigActivity::matches (const CuData & token) const
onExit()
void CuTConfigActivity::onExit () protected
repeat()
int CuTConfigActivity::repeat () const
setOptions()
void CuTConfigActivity::setOptions (const CuData & o)
The documentation for this class was generated from the following files:
cutconfigactivity.h
cutconfigactivity.cpp