cumbia-tango: CuActionFactoryServiceImpl_Base Class Reference
CuActionFactoryServiceImpl_Base Class Reference
#include <cuactionfactoryservice_impls.h>
Public Types
enum Type { CuActionFactoryServiceType = CuServices::User + 21 }
Public Member Functions
CuActionFactoryServiceImpl_Base ()
virtual ~CuActionFactoryServiceImpl_Base ()
virtual CuTangoActionI * registerAction (const std::string &src, const CuTangoActionFactoryI &f, CumbiaTango *ct, bool *isnew)
virtual CuTangoActionI * find (const std::string &name, CuTangoActionI::Type at)
virtual size_t count () const
virtual void unregisterAction (const std::string &src, CuTangoActionI::Type at)
virtual void cleanup ()
Protected Attributes
CuActionFactoryServiceImplBasePrivate * d
Member Enumeration Documentation
Type
enum CuActionFactoryServiceImpl_Base::Type
Enumerator
CuActionFactoryServiceType
Constructor & Destructor Documentation
CuActionFactoryServiceImpl_Base()
CuActionFactoryServiceImpl_Base::CuActionFactoryServiceImpl_Base ()
References d.
~CuActionFactoryServiceImpl_Base()
CuActionFactoryServiceImpl_Base::~CuActionFactoryServiceImpl_Base () virtual
References d.
Member Function Documentation
cleanup()
void CuActionFactoryServiceImpl_Base::cleanup () virtual
Reimplemented in CuActionFactoryServiceImpl.
References d.
Referenced by CuActionFactoryService::cleanup(), and CuActionFactoryServiceImpl::cleanup().
count()
size_t CuActionFactoryServiceImpl_Base::count () const virtual
Reimplemented in CuActionFactoryServiceImpl.
References d.
Referenced by CuActionFactoryService::count(), and CuActionFactoryServiceImpl::count().
find()
CuTangoActionI * CuActionFactoryServiceImpl_Base::find (const std::string & name, CuTangoActionI::Type at) virtual
Reimplemented in CuActionFactoryServiceImpl.
References d.
Referenced by CuActionFactoryService::find(), and CuActionFactoryServiceImpl::find().
registerAction()
CuTangoActionI * CuActionFactoryServiceImpl_Base::registerAction (const std::string & src, const CuTangoActionFactoryI & f, CumbiaTango * ct, bool * isnew) virtual
Reimplemented in CuActionFactoryServiceImpl.
References CuTangoActionFactoryI::create(), d, and CuTangoActionFactoryI::getType().
Referenced by CuActionFactoryService::registerAction(), and CuActionFactoryServiceImpl::registerAction().
unregisterAction()
void CuActionFactoryServiceImpl_Base::unregisterAction (const std::string & src, CuTangoActionI::Type at) virtual
Reimplemented in CuActionFactoryServiceImpl.
References d.
Referenced by CuActionFactoryService::unregisterAction(), and CuActionFactoryServiceImpl::unregisterAction().
Member Data Documentation
d
CuActionFactoryServiceImplBasePrivate* CuActionFactoryServiceImpl_Base::d protected
Referenced by cleanup(), count(), CuActionFactoryServiceImpl_Base(), find(), registerAction(), unregisterAction(), and ~CuActionFactoryServiceImpl_Base().
The documentation for this class was generated from the following files:
cuactionfactoryservice_impls.h
cuactionfactoryservice_impls.cpp