cumbia-tango: CuTConfiguration Class Reference
CuTConfiguration Class Reference
#include <cutconfiguration.h>
Public Member Functions
CuTConfiguration (const TSource &src, CumbiaTango *ct, CuTangoActionI::Type t)
virtual ~CuTConfiguration ()
void setDesiredAttributeProperties (const std::vector< std::string > props)
void setOptions (const CuData &options)
void onProgress (int, int, const CuData &)
void onResult (const CuData &data)
void onResult (const std::vector< CuData > &datalist)
unused. Complies with CuThreadListener interface
CuData getToken () const
TSource getSource () const
return a TSource object that stores information about the Tango source
Type getType () const
returns the type of CuTangoActionI implemented
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
void sendData (const CuData &data)
subclasses will implement the necessary code to set data on themselves or to the activities
void getData (CuData &d_inout) const
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
size_t dataListenersCount ()
return the number of registered data listeners
void start ()
the method where activities are created and registered
void stop ()
calls unregisterActivity on Cumbia in order to enter the exit state
bool exiting () const
CuActionFactory relies on this returning true to unregister the action.
Public Member Functions inherited from CuTangoActionI
virtual ~CuTangoActionI ()
virtual destructor, to make compilers happy
Additional Inherited Members
Public Types inherited from CuTangoActionI
enum Type {
Reader = 0, Writer, ReaderConfig, WriterConfig,
DbReadProp, DbWriteProp
}
list of types of actions
Constructor & Destructor Documentation
CuTConfiguration()
CuTConfiguration::CuTConfiguration (const TSource & src, CumbiaTango * ct, CuTangoActionI::Type t)
~CuTConfiguration()
CuTConfiguration::~CuTConfiguration () virtual
Member Function Documentation
addDataListener()
void CuTConfiguration::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuTangoActionI.
dataListenersCount()
size_t CuTConfiguration::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuTangoActionI.
exiting()
bool CuTConfiguration::exiting () const virtual
CuActionFactory relies on this returning true to unregister the action.
Implements CuTangoActionI.
getData()
void CuTConfiguration::getData (CuData & d_inout) const virtual
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation as input argument. data will contain additional output fields filled in by the method when it returns.
note
getData must be synchronous: it's called with input arguments (d_inout) and they are filled in within the same method in the same thread. Asynchronous data fetch from an activity executed in a separate thread can be accomplished by sendData in combination with CuDataListener::onUpdate. There, received data will have to be recognised as coming from a specific request and treated accordingly.
Implements CuTangoActionI.
getSource()
TSource CuTConfiguration::getSource () const virtual
return a TSource object that stores information about the Tango source
Returns
TSource, an object storing information on the Tango source
Implements CuTangoActionI.
getToken()
CuData CuTConfiguration::getToken () const
getType()
CuTangoActionI::Type CuTConfiguration::getType () const virtual
returns the type of CuTangoActionI implemented
Returns
one of the values from the Type enum
Implements CuTangoActionI.
Referenced by onResult().
onProgress()
void CuTConfiguration::onProgress (int step, int total, const CuData & data)
onResult() [1/2]
void CuTConfiguration::onResult (const CuData & data)
References CuActionFactoryService::CuActionFactoryServiceType, getType(), and CuActionFactoryService::unregisterAction().
onResult() [2/2]
void CuTConfiguration::onResult (const std::vector< CuData > & datalist)
unused. Complies with CuThreadListener interface
removeDataListener()
void CuTConfiguration::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuTangoActionI.
References stop().
sendData()
void CuTConfiguration::sendData (const CuData & data) virtual
subclasses will implement the necessary code to set data on themselves or to the activities
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation
The data can be set locally on the object implementing this interface or can be forwarded to the activity by means of Cumbia::postEvent carrying an argument derived from CuActivityEvent. See CuTReader::sendData for an example
Send a request and receive a response asynchronously
Use sendData in conjunction with CuDataListener::onUpdate, as described in the getData documentation.
Implements CuTangoActionI.
setDesiredAttributeProperties()
void CuTConfiguration::setDesiredAttributeProperties (const std::vector< std::string > props)
Referenced by CuTWriterConfFactory::create(), setOptions(), and start().
setOptions()
void CuTConfiguration::setOptions (const CuData & options)
References setDesiredAttributeProperties().
Referenced by CuTReaderConfFactory::create().
start()
void CuTConfiguration::start () virtual
the method where activities are created and registered
This is the place where activities are created and registered to Cumbia through the method Cumbia::registerActivity.
Examples
CuTReader::start
CuTWriter::start
See also Cumbia::registerActivity
Implements CuTangoActionI.
References TSource::Cmd, CuDeviceFactoryService::CuDeviceFactoryServiceType, CuTConfigActivity::CuReaderConfigActivityType, CuTConfigActivity::CuWriterConfigActivityType, CuTangoActionI::ReaderConfig, and setDesiredAttributeProperties().
stop()
void CuTConfiguration::stop () virtual
calls unregisterActivity on Cumbia in order to enter the exit state
sets the exiting flag to true
calls Cumbia::unregisterActivity
Implements CuTangoActionI.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cutconfiguration.h
cutconfiguration.cpp