cumbia-tango: CuActionFactoryServiceImpl_TS Class Reference
CuActionFactoryServiceImpl_TS Class Reference
The CuActionFactoryServiceImpl_TS class is the thread safe version of CuActionFactoryServiceImpl for cases registering and unregistering actions from different threads (i.e. complex applications)
#include <cuactionfactoryservice_impls.h>
Public Member Functions
CuActionFactoryServiceImpl_TS ()
virtual ~CuActionFactoryServiceImpl_TS ()
virtual CuTangoActionI * registerAction (const std::string &src, const CuTangoActionFactoryI &f, CumbiaTango *ct)
virtual CuTangoActionI * find (const std::string &name, CuTangoActionI::Type at)
virtual size_t count () const
virtual void unregisterAction (const std::string &src, CuTangoActionI::Type at)
virtual void cleanup ()
Public Member Functions inherited from CuActionFactoryServiceImpl_Base
CuActionFactoryServiceImpl_Base ()
virtual ~CuActionFactoryServiceImpl_Base ()
Additional Inherited Members
Public Types inherited from CuActionFactoryServiceImpl_Base
enum Type { CuActionFactoryServiceType = CuServices::User + 21 }
Protected Attributes inherited from CuActionFactoryServiceImpl_Base
CuActionFactoryServiceImplBasePrivate * d
Detailed Description
The CuActionFactoryServiceImpl_TS class is the thread safe version of CuActionFactoryServiceImpl for cases registering and unregistering actions from different threads (i.e. complex applications)
Constructor & Destructor Documentation
CuActionFactoryServiceImpl_TS()
CuActionFactoryServiceImpl_TS::CuActionFactoryServiceImpl_TS ()
thread safe version
~CuActionFactoryServiceImpl_TS()
CuActionFactoryServiceImpl_TS::~CuActionFactoryServiceImpl_TS () virtual
Member Function Documentation
cleanup()
void CuActionFactoryServiceImpl_TS::cleanup () virtual
Reimplemented from CuActionFactoryServiceImpl_Base.
References CuActionFactoryServiceImpl_Base::cleanup().
count()
size_t CuActionFactoryServiceImpl_TS::count () const virtual
Reimplemented from CuActionFactoryServiceImpl_Base.
References CuActionFactoryServiceImpl_Base::count().
find()
CuTangoActionI * CuActionFactoryServiceImpl_TS::find (const std::string & name, CuTangoActionI::Type at) virtual
Reimplemented from CuActionFactoryServiceImpl_Base.
References CuActionFactoryServiceImpl_Base::find().
registerAction()
CuTangoActionI * CuActionFactoryServiceImpl_TS::registerAction (const std::string & src, const CuTangoActionFactoryI & f, CumbiaTango * ct) virtual
Reimplemented from CuActionFactoryServiceImpl_Base.
References CuActionFactoryServiceImpl_Base::registerAction().
unregisterAction()
void CuActionFactoryServiceImpl_TS::unregisterAction (const std::string & src, CuTangoActionI::Type at) virtual
Reimplemented from CuActionFactoryServiceImpl_Base.
References CuActionFactoryServiceImpl_Base::unregisterAction().
The documentation for this class was generated from the following files:
cuactionfactoryservice_impls.h
cuactionfactoryservice_impls.cpp