cumbia-tango: CuPoller Class Reference
CuPoller Class Reference
#include <cupoller.h>
Public Member Functions
CuPoller (CumbiaTango *cu_t, int period)
virtual ~CuPoller ()
int period () const
void registerAction (const TSource &tsrc, CuTangoActionI *a, const CuData &options)
void unregisterAction (CuTangoActionI *a)
unregister an action from the poller.
bool actionRegistered (const CuTangoActionI *a) const
size_t count () const
counts the number of actions
virtual void onProgress (int step, int total, const CuData &data)
virtual void onResult (const CuData &data)
virtual void onResult (const std::vector< CuData > &datalist)
virtual CuData getToken () const
Constructor & Destructor Documentation
CuPoller()
CuPoller::CuPoller (CumbiaTango * cu_t, int period)
References period().
~CuPoller()
CuPoller::~CuPoller () virtual
Member Function Documentation
actionRegistered()
bool CuPoller::actionRegistered (const CuTangoActionI * a) const
Referenced by CuPollingService::actionRegistered().
count()
size_t CuPoller::count () const
counts the number of actions
Returns
the number of actions
Referenced by CuPollingService::unregisterAction().
getToken()
CuData CuPoller::getToken () const virtual
onProgress()
void CuPoller::onProgress (int step, int total, const CuData & data) virtual
onResult() [1/2]
void CuPoller::onResult (const CuData & data) virtual
onResult() [2/2]
void CuPoller::onResult (const std::vector< CuData > & datalist) virtual
period()
int CuPoller::period () const
Referenced by CuPoller(), and CuTReader::sendData().
registerAction()
void CuPoller::registerAction (const TSource & tsrc, CuTangoActionI * a, const CuData & options)
References CuDeviceFactoryService::CuDeviceFactoryServiceType, TSource::getDeviceName(), TSource::getName(), and CuTangoActionI::getSource().
Referenced by CuPollingService::registerAction().
unregisterAction()
void CuPoller::unregisterAction (CuTangoActionI * a)
unregister an action from the poller.
Parameters
a the action to unregister
A CuTangoActionI can invoke unregisterAction from within CuTangoActionI::onResult. In this case, the operation is delayed after CuPoller::onResult has finished delivering results. If the method is called when CuPoller is not inside CuPoller::onResult, the action is unregistered immediately.
after the last action is removed, this object is removed from the CuActivityManager thread listeners before next step:
a CuRemovePollActionEvent is posted to the CuPollingActivity managing the CuTangoActionI device with the CuPoller::period interval
a dummy CuData with the "exit" flag is delivered through CuTangoActionI::onResult. This is why unregister operations must be enqueued and performed outside result delivery taking place in CuPoller::onResult
Referenced by CuPollingService::unregisterAction().
The documentation for this class was generated from the following files:
cupoller.h
cupoller.cpp