cumbia-tango: CuWriteActivity Class Reference
CuWriteActivity Class Reference
#include <cuwriteactivity.h>
Public Types
enum Type { CuWriteA_Type = CuActivity::UserAType + 32 }
Public Member Functions
CuWriteActivity (const CuData &token, CuDeviceFactory_I *df, const CuData &db_config, const CuData &tag)
virtual ~CuWriteActivity ()
void event (CuActivityEvent *e)
bool matches (const CuData &token) const
int getType () const
int repeat () const
Protected Member Functions
void init ()
void execute ()
void onExit ()
Member Enumeration Documentation
Type
enum CuWriteActivity::Type
Enumerator
CuWriteA_Type
Constructor & Destructor Documentation
CuWriteActivity()
CuWriteActivity::CuWriteActivity (const CuData & token, CuDeviceFactory_I * df, const CuData & db_config, const CuData & tag)
~CuWriteActivity()
CuWriteActivity::~CuWriteActivity () virtual
Member Function Documentation
event()
void CuWriteActivity::event (CuActivityEvent * e)
execute()
void CuWriteActivity::execute () protected
References CuTangoWorld::cmd_inout(), CuTangoWorld::error(), CuTangoWorld::fillThreadInfo(), CuTangoWorld::get_att_config(), CuTangoWorld::get_command_info(), CuTangoWorld::getLastMessage(), CuTangoWorld::toDeviceData(), and CuTangoWorld::write_att().
getType()
int CuWriteActivity::getType () const
References CuWriteA_Type.
init()
void CuWriteActivity::init () protected
References CuTThread::CuTThreadType.
matches()
bool CuWriteActivity::matches (const CuData & token) const
onExit()
void CuWriteActivity::onExit () protected
repeat()
int CuWriteActivity::repeat () const
The documentation for this class was generated from the following files:
cuwriteactivity.h
cuwriteactivity.cpp