cumbia-tango: TSource Class Reference
TSource Class Reference
#include <tsource.h>
Public Types
enum Type {
SrcInvalid = 0 , SrcCmd , SrcAttr , SrcDbDoma ,
SrcDbFam , SrcDbMem , SrcDbAtts , SrcDbClassProps ,
SrcDbCmds , SrcDbAttInfo , SrcDbDevProps , SrcDbAProp ,
SrcDbGetCmdI , SrcDbClassProp , SrcDbDevProp , SrcDbFreeProp ,
SrcExportedDevs , SrcEndTypes
}
Public Member Functions
TSource ()
TSource (const std::string s)
TSource (const TSource &other)
TSource (TSource &&other)
~TSource ()
std::string getDeviceName () const
std::string getDeviceNameOnly () const
std::string getPoint () const
Returns the attribute name if the type is SrcAttr, the command name if the type is SrcCmd, an empty string in all other cases.
std::string getName () const
std::string getTangoHost () const
std::string getFreePropNam () const
Returns whatever follows the "#" character, if present.
std::string getFreePropObj () const
get the object name the free property refers to
std::string getSearchPattern () const
if the type is one of the database search methods, the search pattern
std::string getPropClassNam () const
If the source is a class property, get the class name.
std::string getExportedDevSearchPattern () const
std::string getArgOptions (size_t *pos_start, size_t *pos_end) const
get options that can affect the interpretation of the arguments
bool isDbOp () const
returns true if the source represents an operation on the Tango Database
void setArgs (const std::vector< std::string > &args)
std::vector< string > getArgs () const
Finds and returns the comma separated arguments within parentheses, if present.
std::string getArgsString () const
std::vector< std::string > getPropNames () const
string toString () const
std::string remove_tgproto (const std::string &src) const
std::string remove_tghost (const std::string &src) const
std::string rem_tghostproto (const std::string &src) const
std::string rem_args (const std::string &src) const
const char * getTypeName (Type t) const
Type getType () const
TSource & operator= (const TSource &other)
bool operator== (const TSource &other) const
Public Attributes
const char * tynames [SrcEndTypes+1]
Member Enumeration Documentation
Type
enum TSource::Type
Enumerator
SrcInvalid
SrcCmd
SrcAttr
SrcDbDoma
SrcDbFam
SrcDbMem
SrcDbAtts
SrcDbClassProps
SrcDbCmds
SrcDbAttInfo
SrcDbDevProps
SrcDbAProp
SrcDbGetCmdI
SrcDbClassProp
SrcDbDevProp
SrcDbFreeProp
SrcExportedDevs
SrcEndTypes
Constructor & Destructor Documentation
TSource() [1/4]
TSource::TSource ()
TSource() [2/4]
TSource::TSource (const std::string s)
TSource() [3/4]
TSource::TSource (const TSource & other)
TSource() [4/4]
TSource::TSource (TSource && other)
~TSource()
TSource::~TSource ()
Member Function Documentation
getArgOptions()
std::string TSource::getArgOptions (size_t * pos_start, size_t * pos_end) const
get options that can affect the interpretation of the arguments
Since
1.5.2
  some keyword:value fields can be used at the beginning of the argument
  section to customize the interpretation of the arguments
  The keyword:value list shall be enclosed between square brackets at the
  beginning of the arguments section
Example
test/device/1/double_spectrum([sep(;)]10;20;30)
Returns
a string with the options
References regexps::get_args_re().
Referenced by getArgs().
getArgs()
std::vector< string > TSource::getArgs () const
Finds and returns the comma separated arguments within parentheses, if present.
List of options to individuate and interpret arguments can be specified between square brackets immediately after the opening parenthesis in the source string:
a/b/c->Get([sep(;)]arg1, arg2, arg3)
Returns
vector of the detected arguments, as string
References getArgOptions().
Referenced by CuPollingActivity::execute(), and getPropNames().
getArgsString()
std::string TSource::getArgsString () const
Referenced by toString().
getDeviceName()
string TSource::getDeviceName () const
References regexps::get_dev_re(), and rem_tghostproto().
Referenced by CuTangoWorld::db_get(), getDeviceNameOnly(), CuPoller::registerAction(), toString(), and CuPoller::unregisterAction().
getDeviceNameOnly()
string TSource::getDeviceNameOnly () const
References getDeviceName(), and rem_tghostproto().
Referenced by CuTangoWorld::db_get().
getExportedDevSearchPattern()
string TSource::getExportedDevSearchPattern () const
References rem_tghostproto().
Referenced by CuTangoWorld::db_get().
getFreePropNam()
std::string TSource::getFreePropNam () const
Returns whatever follows the "#" character, if present.
Returns
the subsctring of the source after the # character, if present. It should be a property name. An empty string is returned if no "#" character is found.
Examples
hokuto:20000/test/device/1/double_scalar#values (values attribute property)
test/de/1#dprop (dprop device property)
TangoTest#version (version class property)
#ObjectName#FreePropName (version free property)
See also
getFreePropObj
Referenced by CuTangoWorld::db_get().
getFreePropObj()
string TSource::getFreePropObj () const
get the object name the free property refers to
Returns
the object name or an empty string
Syntax
#MyObject#MyProperty getFreePropObj returns MyObject while getPropNam returns MyProperty
Example
#Sequencer#TestList getFreePropObj returns Sequencer while getPropNam returns TestList
References regexps::get_freeprop_re().
Referenced by CuTangoWorld::db_get().
getName()
std::string TSource::getName () const
Referenced by CuPollingService::actionRegistered(), CuPollingActivity::execute(), CuActionFactoryServiceImpl_Base::registerAction(), CuPoller::registerAction(), CuActionFactoryServiceImpl_Base::unregisterAction(), and CuPoller::unregisterAction().
getPoint()
string TSource::getPoint () const
Returns the attribute name if the type is SrcAttr, the command name if the type is SrcCmd, an empty string in all other cases.
References SrcAttr, SrcCmd, SrcDbAProp, SrcDbAttInfo, and SrcDbGetCmdI.
Referenced by CuTangoWorld::db_get(), CuPollingActivity::execute(), and toString().
getPropClassNam()
string TSource::getPropClassNam () const
If the source is a class property, get the class name.
Returns
the class name found in the source
References rem_tghostproto(), SrcDbClassProp, and SrcDbClassProps.
Referenced by CuTangoWorld::db_get().
getPropNames()
std::vector< std::string > TSource::getPropNames () const
References getArgs().
Referenced by CuTangoWorld::db_get().
getSearchPattern()
string TSource::getSearchPattern () const
if the type is one of the database search methods, the search pattern
Returns
References rem_tghostproto(), SrcDbDevProps, and SrcDbDoma.
Referenced by CuTangoWorld::db_get().
getTangoHost()
std::string TSource::getTangoHost () const
References regexps::get_host_re().
Referenced by CuTangoWorld::db_get().
getType()
TSource::Type TSource::getType () const
Referenced by CuTangoWorld::db_get().
getTypeName()
const char * TSource::getTypeName (Type t) const
References SrcEndTypes, and tynames.
Referenced by CuTangoWorld::db_get(), and toString().
isDbOp()
bool TSource::isDbOp () const
returns true if the source represents an operation on the Tango Database
References SrcAttr, and SrcEndTypes.
operator=()
TSource & TSource::operator= (const TSource & other)
operator==()
bool TSource::operator== (const TSource & other) const
rem_args()
string TSource::rem_args (const std::string & src) const
References regexps::get_args_re().
rem_tghostproto()
string TSource::rem_tghostproto (const std::string & src) const
References remove_tghost(), and remove_tgproto().
Referenced by getDeviceName(), getDeviceNameOnly(), getExportedDevSearchPattern(), getPropClassNam(), and getSearchPattern().
remove_tghost()
string TSource::remove_tghost (const std::string & src) const
References regexps::get_host_re().
Referenced by rem_tghostproto().
remove_tgproto()
string TSource::remove_tgproto (const std::string & src) const
Referenced by rem_tghostproto().
setArgs()
void TSource::setArgs (const std::vector< std::string > & args)
toString()
std::string TSource::toString () const
References getArgsString(), getDeviceName(), getPoint(), and getTypeName().
Member Data Documentation
tynames
const char* TSource::tynames[SrcEndTypes+1]
Initial value:
= { "SrcInvalid", "SrcCmd", "SrcAttr", "SrcDbDoma", "SrcDbFam", "SrcDbMem",
                                            "SrcDbAtts","SrcDbClassProps",  "SrcDbCmds", "SrcDbAProps",  "SrcDbDevProps",
                                            "SrcDbAProp",  "SrcDbGetCmdI",  "SrcDbClassProp", "SrcDbDevProp", "SrcDbFreeProp", "SrcExportedDevs" "SrcEndTypes" }
Referenced by getTypeName().
The documentation for this class was generated from the following files:
tsource.h
tsource.cpp