cumbia-tango: CumbiaTango Class Reference
CumbiaTango Class Reference
#include <cumbiatango.h>
Public Types
enum Type { CumbiaTangoType = Cumbia::CumbiaUserType + 1 }
enum UpdateOptions {
OnPollUpdateAlways = 0x1 , OnPollUnchangedUpdateTimestamp = 0x2 , OnPollUnchangedNoUpdate = 0x4 , SkipFirstReadUpdate = 0x8 ,
EndUpdateOptions = 0x20
}
Public Member Functions
CumbiaTango (CuThreadFactoryImplI *tfi, CuThreadsEventBridgeFactory_I *teb)
CumbiaTango two parameters constructor.
~CumbiaTango ()
void addAction (const TSource &source, CuDataListener *l, const CuTangoActionFactoryI &f)
void unlinkListener (const std::string &source, CuTangoActionI::Type t, CuDataListener *l)
Removes a listener from the action with the given source and type.
void removeAction (const TSource &source, CuTangoActionI::Type t)
CuTangoActionI * findAction (const std::string &source, CuTangoActionI::Type t) const
CuThreadFactoryImplI * getThreadFactoryImpl () const
CuThreadsEventBridgeFactory_I * getThreadEventsBridgeFactory () const
void setReadUpdatePolicy (int p)
int readUpdatePolicy () const
virtual int getType () const
Member Enumeration Documentation
Type
enum CumbiaTango::Type
Enumerator
CumbiaTangoType
UpdateOptions
enum CumbiaTango::UpdateOptions
Enumerator
OnPollUpdateAlways
OnPollUnchangedUpdateTimestamp
OnPollUnchangedNoUpdate
SkipFirstReadUpdate
EndUpdateOptions
Constructor & Destructor Documentation
CumbiaTango()
CumbiaTango::CumbiaTango (CuThreadFactoryImplI * tfi, CuThreadsEventBridgeFactory_I * teb)
CumbiaTango two parameters constructor.
The class constructor accepts a factory providing a thread implementation for cumbia (mainly CuThread) and a bridge to forward events from the secondary threads to the main.
Parameters
tfi a CuThreadFactoryImplI implementation, mainly CuThreadFactoryImpl
teb a CuThreadsEventBridgeFactory_I implementation, for example CuThreadsEventBridgeFactory or cumbia-qtcontrols QThreadsEventBridgeFactory
example
CumbiaTango* cuta = new CumbiaTango(new CuThreadFactoryImpl(), new QThreadsEventBridgeFactory());
~CumbiaTango()
CumbiaTango::~CumbiaTango ()
References CuActionFactoryService::cleanup(), CuActionFactoryService::CuActionFactoryServiceType, and CuTangoWorld::orb_cleanup().
Member Function Documentation
addAction()
void CumbiaTango::addAction (const TSource & source, CuDataListener * l, const CuTangoActionFactoryI & f)
References CuTangoActionI::addDataListener(), CuActionFactoryService::CuActionFactoryServiceType, CuActionFactoryService::registerAction(), and CuTangoActionI::start().
findAction()
CuTangoActionI * CumbiaTango::findAction (const std::string & source, CuTangoActionI::Type t) const
References CuActionFactoryService::CuActionFactoryServiceType, and CuActionFactoryService::find().
getThreadEventsBridgeFactory()
CuThreadsEventBridgeFactory_I * CumbiaTango::getThreadEventsBridgeFactory () const
getThreadFactoryImpl()
CuThreadFactoryImplI * CumbiaTango::getThreadFactoryImpl () const
getType()
int CumbiaTango::getType () const virtual
References CumbiaTangoType.
readUpdatePolicy()
int CumbiaTango::readUpdatePolicy () const
Returns the update policy in use
Default: CuDataUpdatePolicy::PollUpdateAlways
Referenced by CuPollingService::registerAction().
removeAction()
void CumbiaTango::removeAction (const TSource & source, CuTangoActionI::Type t)
References CuActionFactoryService::CuActionFactoryServiceType, and CuActionFactoryService::unregisterAction().
setReadUpdatePolicy()
void CumbiaTango::setReadUpdatePolicy (int p)
Suggest a policy for read updates
Parameters
p a valid combination of values from the enum CuDataUpdatePolicy OnPoll options can be or-ed with SkipFirstReadUpdate
See also
CuDataUpdatePolicy
CuPollingActivity
unlinkListener()
void CumbiaTango::unlinkListener (const std::string & source, CuTangoActionI::Type t, CuDataListener * l)
Removes a listener from the action with the given source and type.
Parameters
source the source of the action
t the CuTangoActionI::Type type (Reader, Writer, ReaderConfig, WriterConfig, TaDb)
l the CuDataListener to be removed from the action identified by source and t
Note
Examples of CuDataListener are objects from the cumbia-qtcontrols module, such as QuLabel, QuTrendPlot, QuLed and the like.
Examples of CuTangoActionI are CuTReader CuTWriter and CuTConfiguration
An action is removed from cumbia when no more listeners reference it
References CuActionFactoryService::CuActionFactoryServiceType, CuActionFactoryService::find(), and CuTangoActionI::removeDataListener().
The documentation for this class was generated from the following files:
cumbiatango.h
cumbiatango.cpp