cumbia-tango: CuTConfFactoryBase Class Reference
CuTConfFactoryBase Class Reference
#include <cutangoactionfactories.h>
Public Member Functions
virtual ~CuTConfFactoryBase ()
void setOptions (const CuData &options)
void setTag (const CuData &tag)
CuData options () const
CuData tag () const
Public Member Functions inherited from CuTangoActionFactoryI
virtual ~CuTangoActionFactoryI ()
virtual CuTangoActionI * create (const std::string &source, CumbiaTango *ct) const =0
virtual CuTangoActionI::Type getType () const =0
Return the type of action that the factory creates.
Public Attributes
CuData opts
CuData dtag
Constructor & Destructor Documentation
~CuTConfFactoryBase()
CuTConfFactoryBase::~CuTConfFactoryBase () virtual
Member Function Documentation
options()
CuData CuTConfFactoryBase::options () const
References opts.
Referenced by setOptions().
setOptions()
void CuTConfFactoryBase::setOptions (const CuData & options)
References options(), and opts.
setTag()
void CuTConfFactoryBase::setTag (const CuData & tag)
References dtag, and tag().
tag()
CuData CuTConfFactoryBase::tag () const
References dtag.
Referenced by setTag().
Member Data Documentation
dtag
CuData CuTConfFactoryBase::dtag
Referenced by CuTReaderConfFactory::create(), CuTWriterConfFactory::create(), setTag(), and tag().
opts
CuData CuTConfFactoryBase::opts
Referenced by CuTReaderConfFactory::create(), CuTWriterConfFactory::create(), options(), and setOptions().
The documentation for this class was generated from the following files:
cutangoactionfactories.h
cutangoactionfactories.cpp