cumbia-tango: CuActionFactoryServiceImpl Class Reference
CuActionFactoryServiceImpl Class Reference
The CuActionFactoryServiceImpl class is the default implementation.
#include <cuactionfactoryservice_impls.h>
Public Member Functions
CuActionFactoryServiceImpl ()
virtual ~CuActionFactoryServiceImpl ()
virtual CuTangoActionI * registerAction (const std::string &src, const CuTangoActionFactoryI &f, CumbiaTango *ct, bool *isnew)
virtual CuTangoActionI * find (const std::string &name, CuTangoActionI::Type at)
virtual size_t count () const
virtual void unregisterAction (const std::string &src, CuTangoActionI::Type at)
virtual void cleanup ()
Public Member Functions inherited from CuActionFactoryServiceImpl_Base
CuActionFactoryServiceImpl_Base ()
virtual ~CuActionFactoryServiceImpl_Base ()
virtual CuTangoActionI * registerAction (const TSource &src, const CuTangoActionFactoryI &f, CumbiaTango *ct, bool *isnew)
virtual void unregisterAction (const TSource &src, CuTangoActionI::Type at)
Additional Inherited Members
Public Types inherited from CuActionFactoryServiceImpl_Base
enum Type { CuActionFactoryServiceType = CuServices::User + 21 }
Protected Attributes inherited from CuActionFactoryServiceImpl_Base
CuActionFactoryServiceImplBasePrivate * d
Detailed Description
The CuActionFactoryServiceImpl class is the default implementation.
Functions shall be called from the same thread.
Constructor & Destructor Documentation
CuActionFactoryServiceImpl()
CuActionFactoryServiceImpl::CuActionFactoryServiceImpl ()
~CuActionFactoryServiceImpl()
CuActionFactoryServiceImpl::~CuActionFactoryServiceImpl () virtual
Member Function Documentation
cleanup()
void CuActionFactoryServiceImpl::cleanup () virtual
Reimplemented from CuActionFactoryServiceImpl_Base.
References CuActionFactoryServiceImpl_Base::cleanup().
count()
size_t CuActionFactoryServiceImpl::count () const virtual
Reimplemented from CuActionFactoryServiceImpl_Base.
References CuActionFactoryServiceImpl_Base::count().
find()
CuTangoActionI * CuActionFactoryServiceImpl::find (const std::string & name, CuTangoActionI::Type at) virtual
Reimplemented from CuActionFactoryServiceImpl_Base.
References CuActionFactoryServiceImpl_Base::find().
registerAction()
CuTangoActionI * CuActionFactoryServiceImpl::registerAction (const std::string & src, const CuTangoActionFactoryI & f, CumbiaTango * ct, bool * isnew) virtual
References CuActionFactoryServiceImpl_Base::registerAction().
unregisterAction()
void CuActionFactoryServiceImpl::unregisterAction (const std::string & src, CuTangoActionI::Type at) virtual
References CuActionFactoryServiceImpl_Base::unregisterAction().
The documentation for this class was generated from the following files:
cuactionfactoryservice_impls.h
cuactionfactoryservice_impls.cpp