qumbiaprojectwizard: ProjectFilesHelper Class Reference
ProjectFilesHelper Class Reference
#include <pro_files_helper.h>
Public Member Functions
ProjectFilesHelper ()
ProjectFilesHelper (const QString &projnam)
bool findMainWidgetProps (const QDir &wdir)
bool findMainProjectFiles (const QDir &wdir)
QFileInfoList findFiles (QDir wdir, const QString &filter, const QString &exclude_regexp=QString()) const
QString findFile (QDir wdir, const QString &name) const
QMap< QString, QString > projectFilesMap () const
QMap< QString, QString > appPropMap () const
bool error () const
QString errorMessage () const
QString uiClassName () const
returns the ClassName in namespace ui
QString mainWidgetClassName () const
QString mainWidgetVarName () const
QString projectName () const
Constructor & Destructor Documentation
ProjectFilesHelper() [1/2]
ProjectFilesHelper::ProjectFilesHelper ()
ProjectFilesHelper() [2/2]
ProjectFilesHelper::ProjectFilesHelper (const QString & projnam)
Member Function Documentation
appPropMap()
QMap<QString, QString> ProjectFilesHelper::appPropMap () const inline
Referenced by QTangoImport::getAppProps().
error()
bool ProjectFilesHelper::error () const inline
errorMessage()
QString ProjectFilesHelper::errorMessage () const inline
findFile()
QString ProjectFilesHelper::findFile (QDir wdir, const QString & name) const
Referenced by findMainWidgetProps().
findFiles()
QFileInfoList ProjectFilesHelper::findFiles (QDir wdir, const QString & filter, const QString & exclude_regexp = QString()) const
Referenced by QTangoImport::convert(), findMainProjectFiles(), and findMainWidgetProps().
findMainProjectFiles()
bool ProjectFilesHelper::findMainProjectFiles (const QDir & wdir)
References findFiles().
Referenced by QTangoImport::open().
findMainWidgetProps()
bool ProjectFilesHelper::findMainWidgetProps (const QDir & wdir)
References findFile(), findFiles(), Main2Cu::findMainWidget(), Main2Cu::mainWidgetVar(), Main2Cu::parseProps(), and Main2Cu::setFileName().
Referenced by QTangoImport::open().
mainWidgetClassName()
QString ProjectFilesHelper::mainWidgetClassName () const inline
Referenced by QTangoImport::convert(), and QTangoImport::mainWidgetClassName().
mainWidgetVarName()
QString ProjectFilesHelper::mainWidgetVarName () const inline
Referenced by QTangoImport::convert(), and QTangoImport::mainWidgetVarName().
projectFilesMap()
QMap<QString, QString> ProjectFilesHelper::projectFilesMap () const inline
Referenced by QTangoImport::convert(), and QTangoImport::getProjectFiles().
projectName()
QString ProjectFilesHelper::projectName () const inline
Referenced by QTangoImport::projectName().
uiClassName()
QString ProjectFilesHelper::uiClassName () const inline
returns the ClassName in namespace ui
example
The PS2605 in the Ui namespace: Ui::PS2605
Referenced by QTangoImport::convert(), and QTangoImport::uiFormClassName().
The documentation for this class was generated from the following files:
pro_files_helper.h
pro_files_helper.cpp