qumbiaprojectwizard: Definitions Class Reference
Definitions Class Reference
load definitions from the qtango.keywords
#include <definitions.h>
Public Member Functions
Definitions ()
bool load (const QString &filename)
QList< Subst > getSubstitutions ()
bool error () const
QString errorMessage () const
Detailed Description
load definitions from the qtango.keywords
Substitutions:
includes TLabel --> qulabel.h
class names TLabel --> QuLabel, TLed --> QuLed...
Constructor & Destructor Documentation
Definitions()
Definitions::Definitions ()
Member Function Documentation
error()
bool Definitions::error () const inline
errorMessage()
QString Definitions::errorMessage () const inline
Referenced by QTangoImport::convert().
getSubstitutions()
QList< Subst > Definitions::getSubstitutions () inline
Referenced by FindReplace::process().
load()
bool Definitions::load (const QString & filename)
Referenced by QTangoImport::convert().
The documentation for this class was generated from the following files:
definitions.h
definitions.cpp