qumbiaprojectwizard: Main2Cu Class Reference
Main2Cu Class Reference
#include <main2cu.h>
Public Member Functions
Main2Cu (const QString &fname)
Main2Cu ()
~Main2Cu ()
void setFileName (const QString &fname)
bool findMainWidget (const QString &classnam)
Main2Cu::findMainWidget finds classnam declaration in main.cpp.
QMap< QString, QString > parseProps ()
bool error () const
QString errorMessage () const
QString mainWidgetVar () const
bool mainWidgetInHeap () const
Constructor & Destructor Documentation
Main2Cu() [1/2]
Main2Cu::Main2Cu (const QString & fname)
Main2Cu() [2/2]
Main2Cu::Main2Cu ()
~Main2Cu()
Main2Cu::~Main2Cu ()
Member Function Documentation
error()
bool Main2Cu::error () const
errorMessage()
QString Main2Cu::errorMessage () const
findMainWidget()
bool Main2Cu::findMainWidget (const QString & classnam)
Main2Cu::findMainWidget finds classnam declaration in main.cpp.
Parameters
classnam the main widget class name to find
Returns
true if the main file was correctly opened AND the main widget class variable names have been detected
Referenced by ProjectFilesHelper::findMainWidgetProps().
mainWidgetInHeap()
bool Main2Cu::mainWidgetInHeap () const
mainWidgetVar()
QString Main2Cu::mainWidgetVar () const
Referenced by ProjectFilesHelper::findMainWidgetProps().
parseProps()
QMap< QString, QString > Main2Cu::parseProps ()
Referenced by ProjectFilesHelper::findMainWidgetProps().
setFileName()
void Main2Cu::setFileName (const QString & fname)
Referenced by ProjectFilesHelper::findMainWidgetProps().
The documentation for this class was generated from the following files:
main2cu.h
main2cu.cpp