qumbiaprojectwizard: MainWidgetHCodeExtractor Class Reference
MainWidgetHCodeExtractor Class Reference
#include <codeextractors.h>
Public Member Functions
virtual CodeExtractorA::Type type () const
virtual QList< Section > extract (CodeExtractorA::Type t)
Public Member Functions inherited from CodeExtractorA
bool error () const
QString errorMessage () const
Additional Inherited Members
Public Types inherited from CodeExtractorA
enum Type { MainCpp , MainWCpp , MainWH , MainWUi , Pro }
Protected Member Functions inherited from CodeExtractorA
QString m_get_file_contents (CodeExtractorA::Type t)
Protected Attributes inherited from CodeExtractorA
bool m_err
QString m_msg
Member Function Documentation
extract()
QList< Section > MainWidgetHCodeExtractor::extract (CodeExtractorA::Type t) virtual
Implements CodeExtractorA.
References Section::EndOfHConstructor, ExtractorHelper::extractCumbiaPoolSections(), Section::Includes, CodeExtractorA::m_err, CodeExtractorA::m_get_file_contents(), and CodeExtractorA::m_msg.
Referenced by CumbiaCodeInjectCmd::process().
type()
CodeExtractorA::Type MainWidgetHCodeExtractor::type () const virtual
Implements CodeExtractorA.
References CodeExtractorA::MainWH.
The documentation for this class was generated from the following files:
codeextractors.h
codeextractors.cpp