qumbiaprojectwizard: TDialRead Class Reference
TDialRead Class Reference
#include <tdialread.h>
Signals
void description (const QString &desc)
void description (const QString &desc)
Public Member Functions
TDialRead (QWidget *parent=nullptr)
TDialRead (QWidget *parent=nullptr)
Protected Slots
virtual void refresh (const TVariant &)
void autoConfigure (const TangoConfigurationParameters *cp)
virtual void refresh (const TVariant &)
void autoConfigure (const TangoConfigurationParameters *cp)
Constructor & Destructor Documentation
TDialRead() [1/2]
TDialRead::TDialRead (QWidget * parent = nullptr) explicit
References autoConfigure(), and refresh().
TDialRead() [2/2]
TDialRead::TDialRead (QWidget * parent = nullptr) explicit
Member Function Documentation
autoConfigure [1/2]
void TDialRead::autoConfigure (const TangoConfigurationParameters * cp) protected slot
References description().
Referenced by TDialRead().
autoConfigure [2/2]
void TDialRead::autoConfigure (const TangoConfigurationParameters * cp) protected slot
description [1/2]
void TDialRead::description (const QString & desc) signal
Referenced by autoConfigure().
description [2/2]
void TDialRead::description (const QString & desc) signal
refresh [1/2]
void TDialRead::refresh (const TVariant & v) protected virtual slot
Referenced by TDialRead().
refresh [2/2]
virtual void TDialRead::refresh (const TVariant &) protected virtual slot
The documentation for this class was generated from the following files:
tdialread.h
to_cumbia/src/tdialread.h
tdialread.cpp
to_cumbia/src/tdialread.cpp