qumbiaprojectwizard: ExtractorHelper Class Reference
ExtractorHelper Class Reference
#include <codeextractors.h>
Public Member Functions
QList< Section > extractCumbiaTangoSections (const QString &s)
QString newline_wrap (const QString &s)
Member Function Documentation
extractCumbiaTangoSections()
QList< Section > ExtractorHelper::extractCumbiaTangoSections (const QString & s)
References newline_wrap(), and Section::NoSection.
Referenced by MainCppCodeExtractor::extract(), MainWidgetCppCodeExtractor::extract(), and MainWidgetHCodeExtractor::extract().
newline_wrap()
QString ExtractorHelper::newline_wrap (const QString & s)
Referenced by extractCumbiaTangoSections().
The documentation for this class was generated from the following files:
codeextractors.h
codeextractors.cpp