qumbiaprojectwizard: CodeExtractorA Class Reference
CodeExtractorA Class Reference abstract
#include <cumbiacodeinjectcmd.h>
Public Types
enum Type { MainCpp , MainWCpp , MainWH , MainWUi , Pro }
Public Member Functions
virtual Type type () const =0
virtual QList< Section > extract (CodeExtractorA::Type t)=0
bool error () const
QString errorMessage () const
Protected Member Functions
QString m_get_file_contents (CodeExtractorA::Type t)
Protected Attributes
bool m_err
QString m_msg
Member Enumeration Documentation
Type
enum CodeExtractorA::Type
Enumerator
MainCpp
MainWCpp
MainWH
Pro
Member Function Documentation
error()
bool CodeExtractorA::error () const inline
References m_err.
Referenced by CumbiaCodeInjectCmd::process().
errorMessage()
QString CodeExtractorA::errorMessage () const inline
References m_msg.
Referenced by CumbiaCodeInjectCmd::process().
extract()
virtual QList< Section > CodeExtractorA::extract (CodeExtractorA::Type t) pure virtual
Implemented in MainCppCodeExtractor, MainWidgetCppCodeExtractor, and MainWidgetHCodeExtractor.
m_get_file_contents()
QString CodeExtractorA::m_get_file_contents (CodeExtractorA::Type t) protected
References m_err, m_msg, MainCpp, MainWCpp, MainWH, and Pro.
Referenced by MainCppCodeExtractor::extract(), MainWidgetCppCodeExtractor::extract(), and MainWidgetHCodeExtractor::extract().
type()
virtual Type CodeExtractorA::type () const pure virtual
Implemented in MainCppCodeExtractor, MainWidgetCppCodeExtractor, and MainWidgetHCodeExtractor.
Member Data Documentation
m_err
bool CodeExtractorA::m_err protected
Referenced by error(), MainCppCodeExtractor::extract(), MainWidgetCppCodeExtractor::extract(), MainWidgetHCodeExtractor::extract(), and m_get_file_contents().
m_msg
QString CodeExtractorA::m_msg protected
Referenced by errorMessage(), MainCppCodeExtractor::extract(), MainWidgetCppCodeExtractor::extract(), MainWidgetHCodeExtractor::extract(), and m_get_file_contents().
The documentation for this class was generated from the following files:
cumbiacodeinjectcmd.h
cumbiacodeinjectcmd.cpp