qumbiaprojectwizard: ConversionDialog Class Reference
ConversionDialog Class Reference
#include <conversiondialog.h>
Public Slots
void addLogs (const QList< OpQuality > &log)
void conversionFinished (bool ok)
void outputFileWritten (const QString &name, const QString &filerelpath, bool ok)
void changeOutPath ()
void slotOkClicked ()
Signals
void okClicked ()
Public Member Functions
ConversionDialog (QWidget *parent, const QString &outpath, bool overwrite=false)
~ConversionDialog ()
QString outputPath () const
Constructor & Destructor Documentation
ConversionDialog()
ConversionDialog::ConversionDialog (QWidget * parent, const QString & outpath, bool overwrite = false)
References changeOutPath(), and slotOkClicked().
~ConversionDialog()
ConversionDialog::~ConversionDialog ()
Member Function Documentation
addLogs
void ConversionDialog::addLogs (const QList< OpQuality > & log) slot
References OpQuality::comment, Quality::Critical, OpQuality::file, OpQuality::lineno, OpQuality::new_e, Quality::Ok, OpQuality::old_e, OpQuality::quality, OpQuality::type, and Quality::Warn.
changeOutPath
void ConversionDialog::changeOutPath () slot
Referenced by ConversionDialog().
conversionFinished
void ConversionDialog::conversionFinished (bool ok) slot
okClicked
void ConversionDialog::okClicked () signal
Referenced by slotOkClicked().
outputFileWritten
void ConversionDialog::outputFileWritten (const QString & name, const QString & filerelpath, bool ok) slot
outputPath()
QString ConversionDialog::outputPath () const
slotOkClicked
void ConversionDialog::slotOkClicked () slot
References okClicked().
Referenced by ConversionDialog().
The documentation for this class was generated from the following files:
conversiondialog.h
conversiondialog.cpp