qumbiaprojectwizard: Quality Class Reference
Quality Class Reference
#include <definitions.h>
Public Types
enum Level { Ok, Warn, Critical }
Public Member Functions
Quality (const QString &_ok)
Quality ()
void setOk (const QString &_ok)
Public Attributes
Level quality
Member Enumeration Documentation
Level
enum Quality::Level
Enumerator
Ok
Warn
Critical
Constructor & Destructor Documentation
Quality() [1/2]
Quality::Quality (const QString & _ok) inline
References setOk().
Quality() [2/2]
Quality::Quality () inline
Member Function Documentation
setOk()
void Quality::setOk (const QString & _ok) inline
References Critical, Ok, quality, and Warn.
Referenced by Quality(), and Subst::Subst().
Member Data Documentation
quality
Level Quality::quality
Referenced by FindReplace::process(), and setOk().
The documentation for this class was generated from the following file:
definitions.h