qumbiaprojectwizard: CppInstantiationExpand Class Reference
CppInstantiationExpand Class Reference
#include <cppinstantiationexpand.h>
Public Member Functions
CppInstantiationExpand (const QString &filenam)
virtual QString process (const QString &input)
virtual QString name ()
returns an identifier for the implementation of FileCmd
Public Member Functions inherited from FileCmd
FileCmd (const QString &filename)
virtual ~FileCmd ()
void setDefinitions (const Definitions &d)
virtual bool error ()
virtual QString errorMessage ()
QList< OpQuality > log () const
QString filename () const
Additional Inherited Members
Protected Attributes inherited from FileCmd
bool m_err
QString m_msg
QList< OpQuality > m_log
Definitions m_defs
Constructor & Destructor Documentation
CppInstantiationExpand()
CppInstantiationExpand::CppInstantiationExpand (const QString & filenam)
Member Function Documentation
name()
QString CppInstantiationExpand::name () virtual
returns an identifier for the implementation of FileCmd
Implements FileCmd.
process()
QString CppInstantiationExpand::process (const QString & input) virtual
Implements FileCmd.
References FileCmd::filename(), Subst::getFirstOutOption(), Subst::m_comment, FileCmd::m_err, Subst::m_in, FileCmd::m_log, FileCmd::m_msg, Quality::Ok, and Subst::typeStr().
The documentation for this class was generated from the following files:
cppinstantiationexpand.h
cppinstantiationexpand.cpp