qumbiaprojectwizard: CumbiaCodeInjectCmd Class Reference
CumbiaCodeInjectCmd Class Reference
#include <cumbiacodeinjectcmd.h>
Public Member Functions
CumbiaCodeInjectCmd (const QString &filename, const QString &mainwidgetclass, const QString &mainwidgetvar, const QString &uiformclass)
virtual QString process (const QString &input)
virtual QString name ()
returns an identifier for the implementation of FileCmd
Public Member Functions inherited from FileCmd
FileCmd (const QString &filename)
virtual ~FileCmd ()
void setDefinitions (const Definitions &d)
virtual bool error ()
virtual QString errorMessage ()
QList< OpQuality > log () const
QString filename () const
Additional Inherited Members
Protected Attributes inherited from FileCmd
bool m_err
QString m_msg
QList< OpQuality > m_log
Definitions m_defs
Constructor & Destructor Documentation
CumbiaCodeInjectCmd()
CumbiaCodeInjectCmd::CumbiaCodeInjectCmd (const QString & filename, const QString & mainwidgetclass, const QString & mainwidgetvar, const QString & uiformclass)
References FileCmd::m_err.
Member Function Documentation
name()
QString CumbiaCodeInjectCmd::name () virtual
returns an identifier for the implementation of FileCmd
Implements FileCmd.
process()
QString CumbiaCodeInjectCmd::process (const QString & input) virtual
Implements FileCmd.
References CodeInjector::error(), CodeExtractorA::error(), CodeInjector::errorMessage(), CodeExtractorA::errorMessage(), MainCppCodeExtractor::extract(), MainWidgetCppCodeExtractor::extract(), MainWidgetHCodeExtractor::extract(), FileCmd::filename(), CodeInjector::getLog(), CodeInjector::inject(), FileCmd::m_err, FileCmd::m_log, FileCmd::m_msg, CodeExtractorA::MainCpp, CodeExtractorA::MainWCpp, and CodeExtractorA::MainWH.
The documentation for this class was generated from the following files:
cumbiacodeinjectcmd.h
cumbiacodeinjectcmd.cpp