qumbiaprojectwizard: QTangoImport Class Reference
QTangoImport Class Reference
#include <qtangoimport.h>
Signals
void newLog (const QList< OpQuality > &log)
void conversionFinished (bool ok)
void outputFileWritten (const QString &name, const QString &relpath, bool ok)
Public Member Functions
QTangoImport ()
bool open (const QString &pro_filepath)
QMap< QString, QString > getAppProps () const
QMap< QString, QString > getProjectFiles () const
QString projectName () const
QString projectDir () const
QString projectFilePath () const
QString mainWidgetVarName () const
QString mainWidgetClassName () const
QString uiFormClassName () const
QString toCumbiaPro (const QString &qtango_pro) const
QString errorMessage () const
bool error () const
bool convert ()
bool findFilesRelPath ()
bool outputFile (const QString &name, const QString &path)
write on path/name the contents of the file specified by name
QString getContents (const QString &filenam) const
QStringList convertedFileList () const
Constructor & Destructor Documentation
QTangoImport()
QTangoImport::QTangoImport ()
Member Function Documentation
conversionFinished
void QTangoImport::conversionFinished (bool ok) signal
Referenced by convert().
convert()
bool QTangoImport::convert ()
References MacroFileCmd::contents(), conversionFinished(), Definitions::errorMessage(), MacroFileCmd::errorMessage(), ProjectFilesHelper::findFiles(), Definitions::load(), MacroFileCmd::log(), mainWidgetClassName(), ProjectFilesHelper::mainWidgetClassName(), mainWidgetVarName(), ProjectFilesHelper::mainWidgetVarName(), newLog(), MacroFileCmd::process(), ProjectFilesHelper::projectFilesMap(), MacroFileCmd::registerCommand(), ProjectFilesHelper::uiClassName(), and uiFormClassName().
convertedFileList()
QStringList QTangoImport::convertedFileList () const
error()
bool QTangoImport::error () const
errorMessage()
QString QTangoImport::errorMessage () const
findFilesRelPath()
bool QTangoImport::findFilesRelPath ()
References ProSectionExtractor::error(), ProSectionExtractor::errorMessage(), and ProSectionExtractor::get().
getAppProps()
QMap< QString, QString > QTangoImport::getAppProps () const
References ProjectFilesHelper::appPropMap().
getContents()
QString QTangoImport::getContents (const QString & filenam) const
getProjectFiles()
QMap< QString, QString > QTangoImport::getProjectFiles () const
References ProjectFilesHelper::projectFilesMap().
mainWidgetClassName()
QString QTangoImport::mainWidgetClassName () const
References ProjectFilesHelper::mainWidgetClassName().
Referenced by convert().
mainWidgetVarName()
QString QTangoImport::mainWidgetVarName () const
References ProjectFilesHelper::mainWidgetVarName().
Referenced by convert().
newLog
void QTangoImport::newLog (const QList< OpQuality > & log) signal
Referenced by convert().
open()
bool QTangoImport::open (const QString & pro_filepath)
References ProjectFilesHelper::findMainProjectFiles(), and ProjectFilesHelper::findMainWidgetProps().
outputFile()
bool QTangoImport::outputFile (const QString & name, const QString & path)
write on path/name the contents of the file specified by name
Warning
call findFilesRelPath first
References outputFileWritten().
outputFileWritten
void QTangoImport::outputFileWritten (const QString & name, const QString & relpath, bool ok) signal
Referenced by outputFile().
projectDir()
QString QTangoImport::projectDir () const
projectFilePath()
QString QTangoImport::projectFilePath () const
projectName()
QString QTangoImport::projectName () const
References ProjectFilesHelper::projectName().
toCumbiaPro()
QString QTangoImport::toCumbiaPro (const QString & qtango_pro) const
uiFormClassName()
QString QTangoImport::uiFormClassName () const
References ProjectFilesHelper::uiClassName().
Referenced by convert().
The documentation for this class was generated from the following files:
qtangoimport.h
qtangoimport.cpp