qumbiaprojectwizard: FileCmd Class Reference
FileCmd Class Reference abstract
#include <fileprocessor_a.h>
Public Member Functions
FileCmd (const QString &filename)
virtual ~FileCmd ()
void setDefinitions (const Definitions &d)
virtual QString process (const QString &input)=0
virtual QString name ()=0
returns an identifier for the implementation of FileCmd
virtual bool error ()
virtual QString errorMessage ()
QList< OpQuality > log () const
QString filename () const
Protected Attributes
bool m_err
QString m_msg
QList< OpQuality > m_log
Definitions m_defs
Constructor & Destructor Documentation
FileCmd()
FileCmd::FileCmd (const QString & filename) inline
References filename().
~FileCmd()
virtual FileCmd::~FileCmd () inline virtual
Member Function Documentation
error()
virtual bool FileCmd::error () inline virtual
References m_err.
Referenced by MacroFileCmd::process().
errorMessage()
virtual QString FileCmd::errorMessage () inline virtual
References m_msg.
Referenced by MacroFileCmd::process().
filename()
QString FileCmd::filename () const inline
Referenced by FileCmd(), CppInstantiationExpand::process(), CumbiaCodeInjectCmd::process(), FindReplace::process(), MainCppExpandCmd::process(), MainCppPrepareCmd::process(), MainWidgetCppConstructProcessCmd::process(), and ProConvertCmd::process().
log()
QList< OpQuality > FileCmd::log () const inline
References m_log.
Referenced by MacroFileCmd::process().
name()
virtual QString FileCmd::name () pure virtual
returns an identifier for the implementation of FileCmd
Implemented in CppInstantiationExpand, CumbiaCodeInjectCmd, FindReplace, MainCppExpandCmd, MainCppPrepareCmd, MainWidgetCppConstructProcessCmd, MainWidgetHProcessCmd, and ProConvertCmd.
Referenced by MacroFileCmd::process().
process()
virtual QString FileCmd::process (const QString & input) pure virtual
Implemented in CppInstantiationExpand, CumbiaCodeInjectCmd, FindReplace, MainCppExpandCmd, MainCppPrepareCmd, MainWidgetCppConstructProcessCmd, MainWidgetHProcessCmd, and ProConvertCmd.
Referenced by MacroFileCmd::process().
setDefinitions()
void FileCmd::setDefinitions (const Definitions & d) inline
References m_defs.
Referenced by MacroFileCmd::process().
Member Data Documentation
m_defs
Definitions FileCmd::m_defs protected
Referenced by FindReplace::process(), and setDefinitions().
m_err
bool FileCmd::m_err protected
Referenced by CumbiaCodeInjectCmd::CumbiaCodeInjectCmd(), error(), CppInstantiationExpand::process(), CumbiaCodeInjectCmd::process(), FindReplace::process(), MainCppExpandCmd::process(), MainCppPrepareCmd::process(), MainWidgetCppConstructProcessCmd::process(), MainWidgetHProcessCmd::process(), and ProConvertCmd::process().
m_log
QList<OpQuality> FileCmd::m_log protected
Referenced by log(), CppInstantiationExpand::process(), CumbiaCodeInjectCmd::process(), FindReplace::process(), MainCppExpandCmd::process(), MainCppPrepareCmd::process(), MainWidgetCppConstructProcessCmd::process(), and ProConvertCmd::process().
m_msg
QString FileCmd::m_msg protected
Referenced by errorMessage(), CppInstantiationExpand::process(), CumbiaCodeInjectCmd::process(), FindReplace::process(), MainCppPrepareCmd::process(), MainWidgetCppConstructProcessCmd::process(), and ProConvertCmd::process().
The documentation for this class was generated from the following file:
fileprocessor_a.h