qumbiaprojectwizard: FindReplace Class Reference
FindReplace Class Reference
#include <findreplace.h>
Public Member Functions
FindReplace (const QString &filename)
~FindReplace ()
QString process (const QString &input)
QString name ()
returns an identifier for the implementation of FileCmd
Public Member Functions inherited from FileCmd
FileCmd (const QString &filename)
virtual ~FileCmd ()
void setDefinitions (const Definitions &d)
virtual bool error ()
virtual QString errorMessage ()
QList< OpQuality > log () const
QString filename () const
Additional Inherited Members
Protected Attributes inherited from FileCmd
bool m_err
QString m_msg
QList< OpQuality > m_log
Definitions m_defs
Constructor & Destructor Documentation
FindReplace()
FindReplace::FindReplace (const QString & filename)
~FindReplace()
FindReplace::~FindReplace ()
Member Function Documentation
name()
QString FindReplace::name () virtual
returns an identifier for the implementation of FileCmd
Implements FileCmd.
process()
QString FindReplace::process (const QString & input) virtual
Implements FileCmd.
References Quality::Critical, FileCmd::filename(), Definitions::getSubstitutions(), Subst::m_comment, FileCmd::m_defs, FileCmd::m_err, Subst::m_file, Subst::m_in, Subst::m_include, FileCmd::m_log, FileCmd::m_msg, Subst::m_out_options, Subst::m_type, Subst::MapClass, Quality::quality, Subst::ReplaceExpr, Subst::ReplaceInclude, Subst::ReplaceLine, and Subst::typeStr().
The documentation for this class was generated from the following files:
findreplace.h
findreplace.cpp