qumbiaprojectwizard: MacroFileCmd Class Reference
MacroFileCmd Class Reference
#include <fileprocessor_a.h>
Public Member Functions
MacroFileCmd (const QString &contents)
virtual ~MacroFileCmd ()
void registerCommand (FileCmd *cmd)
bool error () const
virtual bool process (const Definitions &defs)
QString errorMessage () const
QList< OpQuality > log () const
QString contents () const
Protected Attributes
bool m_err
QString m_msg
Detailed Description
Abstract class for file processors
Constructor & Destructor Documentation
MacroFileCmd()
MacroFileCmd::MacroFileCmd (const QString & contents) inline
References contents(), and m_err.
~MacroFileCmd()
virtual MacroFileCmd::~MacroFileCmd () inline virtual
Member Function Documentation
contents()
QString MacroFileCmd::contents () const inline
Referenced by QTangoImport::convert(), and MacroFileCmd().
error()
bool MacroFileCmd::error () const inline
References m_err.
errorMessage()
QString MacroFileCmd::errorMessage () const inline
References m_msg.
Referenced by QTangoImport::convert().
log()
QList<OpQuality> MacroFileCmd::log () const inline
Referenced by QTangoImport::convert().
process()
virtual bool MacroFileCmd::process (const Definitions & defs) inline virtual
References FileCmd::error(), FileCmd::errorMessage(), FileCmd::log(), m_err, m_msg, FileCmd::name(), FileCmd::process(), and FileCmd::setDefinitions().
Referenced by QTangoImport::convert().
registerCommand()
void MacroFileCmd::registerCommand (FileCmd * cmd) inline
Referenced by QTangoImport::convert().
Member Data Documentation
m_err
bool MacroFileCmd::m_err protected
Referenced by error(), MacroFileCmd(), and process().
m_msg
QString MacroFileCmd::m_msg protected
Referenced by errorMessage(), and process().
The documentation for this class was generated from the following file:
fileprocessor_a.h