cumbia-qtcontrols: EArrow Class Reference
EArrow Class Reference
a class that can be used to draw arrows.
#include <earrow.h>
Public Types
enum ArrowMode { LEFT, RIGTH, DOUBLE, NONE }
enum ArrowDirection { VERTICAL, HORIZONTAL, RIGTHBOTTOM, RIGTHTOP }
Public Member Functions
EArrow (QWidget *)
~EArrow ()
void setLineSize (int size)
int getLineSize ()
void setLineColor (QColor c)
QColor getLineColor ()
void setBrushColor (QColor c)
QColor getBrushColor ()
void setArrowSize (int size)
int getArrowSize ()
void setArrowMode (ArrowMode m)
ArrowMode getArrowMode ()
void setArrowDirection (ArrowDirection m)
ArrowDirection getArrowDirection ()
Protected Member Functions
virtual void paintEvent (QPaintEvent *)
Protected Attributes
QColor m_lineColor
QColor m_brushColor
int m_lineSize
int m_arrowSize
ArrowMode m_arrowMode
ArrowDirection m_arrowDirection
Properties
int lineSize
QColor lineColor
QColor brushColor
int arrowSize
ArrowMode arrowMode
ArrowDirection arrowDirection
Detailed Description
a class that can be used to draw arrows.
This class has a Qt designer plugin.
Member Enumeration Documentation
ArrowDirection
enum EArrow::ArrowDirection
Enumerator
VERTICAL
HORIZONTAL
RIGTHBOTTOM
RIGTHTOP
ArrowMode
enum EArrow::ArrowMode
Enumerator
LEFT
RIGTH
DOUBLE
NONE
Constructor & Destructor Documentation
EArrow()
EArrow::EArrow (QWidget * parent)
References Elettra::black, Elettra::gray, HORIZONTAL, RIGTH, setArrowDirection(), setArrowMode(), setArrowSize(), setBrushColor(), setLineColor(), and setLineSize().
~EArrow()
EArrow::~EArrow () inline
Member Function Documentation
getArrowDirection()
ArrowDirection EArrow::getArrowDirection () inline
References m_arrowDirection.
Referenced by paintEvent().
getArrowMode()
ArrowMode EArrow::getArrowMode () inline
References m_arrowMode.
Referenced by paintEvent().
getArrowSize()
int EArrow::getArrowSize () inline
References m_arrowSize.
getBrushColor()
QColor EArrow::getBrushColor () inline
References m_brushColor.
Referenced by paintEvent().
getLineColor()
QColor EArrow::getLineColor () inline
References m_lineColor.
Referenced by paintEvent().
getLineSize()
int EArrow::getLineSize () inline
References m_lineSize.
Referenced by paintEvent().
paintEvent()
void EArrow::paintEvent (QPaintEvent *) protected virtual
References DOUBLE, getArrowDirection(), getArrowMode(), getBrushColor(), getLineColor(), getLineSize(), LEFT, RIGTH, RIGTHBOTTOM, RIGTHTOP, and VERTICAL.
setArrowDirection()
void EArrow::setArrowDirection (ArrowDirection m)
References m_arrowDirection.
Referenced by EArrow().
setArrowMode()
void EArrow::setArrowMode (ArrowMode m)
References m_arrowMode.
Referenced by EArrow().
setArrowSize()
void EArrow::setArrowSize (int size)
References m_arrowSize.
Referenced by EArrow().
setBrushColor()
void EArrow::setBrushColor (QColor c)
References m_brushColor.
Referenced by EArrow().
setLineColor()
void EArrow::setLineColor (QColor c)
References m_lineColor.
Referenced by EArrow().
setLineSize()
void EArrow::setLineSize (int size)
References m_lineSize.
Referenced by EArrow().
Member Data Documentation
m_arrowDirection
ArrowDirection EArrow::m_arrowDirection protected
Referenced by getArrowDirection(), and setArrowDirection().
m_arrowMode
ArrowMode EArrow::m_arrowMode protected
Referenced by getArrowMode(), and setArrowMode().
m_arrowSize
int EArrow::m_arrowSize protected
Referenced by getArrowSize(), and setArrowSize().
m_brushColor
QColor EArrow::m_brushColor protected
Referenced by getBrushColor(), and setBrushColor().
m_lineColor
QColor EArrow::m_lineColor protected
Referenced by getLineColor(), and setLineColor().
m_lineSize
int EArrow::m_lineSize protected
Referenced by getLineSize(), and setLineSize().
Property Documentation
arrowDirection
ArrowDirection EArrow::arrowDirection read write
arrowMode
ArrowMode EArrow::arrowMode read write
arrowSize
int EArrow::arrowSize read write
brushColor
QColor EArrow::brushColor read write
lineColor
QColor EArrow::lineColor read write
lineSize
int EArrow::lineSize read write
The documentation for this class was generated from the following files:
earrow.h
earrow.cpp