cumbia-qtcontrols: ECircularGauge Class Reference
ECircularGauge Class Reference
a tachometer like widget
#include <egauge.h>
Public Member Functions
ECircularGauge (QWidget *=NULL)
~ECircularGauge ()
void setValueDisplayed (bool b)
bool isValueDisplayed ()
void setLabel (QString l)
QString label ()
ECircularGauge (QWidget *=NULL)
~ECircularGauge ()
void setValueDisplayed (bool b)
bool isValueDisplayed ()
void setLabel (QString l)
QString label ()
Public Member Functions inherited from EAbstractGauge
EAbstractGauge (QWidget *=NULL)
~EAbstractGauge ()
bool logarithmicScale ()
void setLogarithmicScale (bool l)
void setLowWarning (double w)
double lowWarning ()
void setHighWarning (double w)
double highWarning ()
void setLowError (double e)
double lowError ()
void setHighError (double e)
double highError ()
void setMinValue (double v)
double minValue ()
void setMaxValue (double v)
double maxValue ()
double value ()
void setReference (double r)
double reference ()
void setScaleEnabled (bool b)
bool isScaleEnabled ()
void setReferenceEnabled (bool b)
bool isReferenceEnabled ()
void setColorMode (ColorMode m)
ColorMode colorMode ()
DEPRECATED (void setNormalColor(QColor c))
QColor normalColor ()
DEPRECATED (void setWarningColor(QColor c))
QColor warningColor ()
DEPRECATED (void setErrorColor(QColor c))
QColor errorColor ()
void setExternalScale (bool b)
bool externalScale ()
void setNumMajorTicks (int t)
int numMajorTicks ()
void setNumMinorTicks (int t)
int numMinorTicks ()
void setValueFormat (QString s)
QString valueFormat ()
EAbstractGauge (QWidget *=NULL)
~EAbstractGauge ()
bool logarithmicScale ()
void setLogarithmicScale (bool l)
void setLowWarning (double w)
double lowWarning ()
void setHighWarning (double w)
double highWarning ()
void setLowError (double e)
double lowError ()
void setHighError (double e)
double highError ()
void setMinValue (double v)
double minValue ()
void setMaxValue (double v)
double maxValue ()
double value ()
void setReference (double r)
double reference ()
void setScaleEnabled (bool b)
bool isScaleEnabled ()
void setReferenceEnabled (bool b)
bool isReferenceEnabled ()
void setColorMode (ColorMode m)
ColorMode colorMode ()
DEPRECATED (void setNormalColor(QColor c))
QColor normalColor ()
DEPRECATED (void setWarningColor(QColor c))
QColor warningColor ()
DEPRECATED (void setErrorColor(QColor c))
QColor errorColor ()
void setExternalScale (bool b)
bool externalScale ()
void setNumMajorTicks (int t)
int numMajorTicks ()
void setNumMinorTicks (int t)
int numMinorTicks ()
void setValueFormat (QString s)
QString valueFormat ()
Protected Member Functions
void paintEvent (QPaintEvent *)
void drawColorBar (QPainter *)
void drawScale (QPainter *)
void drawNeedle (QPainter *)
void drawLabels (QPainter *)
void drawValue (QPainter *)
virtual void configure ()
void paintEvent (QPaintEvent *)
void drawColorBar (QPainter *)
void drawScale (QPainter *)
void drawNeedle (QPainter *)
void drawLabels (QPainter *)
void drawValue (QPainter *)
virtual void configure ()
Properties
bool valueDisplayed
QString label
Properties inherited from EAbstractGauge
double minValue
double lowError
double lowWarning
double highWarning
double highError
double maxValue
double value
double reference
bool scaleEnabled
bool referenceEnabled
ColorMode colorMode
bool externalScale
bool logarithmicScale
QString valueFormat
int numMajorTicks
int numMinorTicks
Additional Inherited Members
Public Types inherited from EAbstractGauge
enum ColorMode {
GRADIENT, COLORBAR, SINGLECOLOR, GRADIENT,
COLORBAR, SINGLECOLOR
}
enum ColorMode {
GRADIENT, COLORBAR, SINGLECOLOR, GRADIENT,
COLORBAR, SINGLECOLOR
}
Public Slots inherited from EAbstractGauge
void setValue (double)
void setValue (int)
void setValue (double)
void setValue (int)
Protected Attributes inherited from EAbstractGauge
double m_minValue
double m_maxValue
double m_lowWarning
double m_highWarning
double m_lowError
double m_highError
double m_value
double m_reference
double d_naturalMinV
double d_naturalMaxV
double d_naturalLowWarn
double d_naturalHighWarn
double d_naturalLowErr
double d_naturalHighErr
double d_naturalValue
double d_naturalReference
ColorMode m_colorMode
bool m_referenceEnabled
bool m_scaleEnabled
int m_numMajorTicks
int m_numMinorTicks
QStringList labels
int longestLabelIndex
bool m_externalScale
QVector< qreal > v_p
QVector< QColor > v_c
QColor m_normalColor
QColor m_warningColor
QColor m_errorColor
QString m_valueFormat
Detailed Description
a tachometer like widget
A tachometer like widget.
Constructor & Destructor Documentation
ECircularGauge() [1/2]
ECircularGauge::ECircularGauge (QWidget * parent = NULL)
References CIRCULAR_MAJOR_TICKS, NUM_MINOR_TICKS, EAbstractGauge::setExternalScale(), EAbstractGauge::setNumMajorTicks(), and EAbstractGauge::setNumMinorTicks().
~ECircularGauge() [1/2]
ECircularGauge::~ECircularGauge () inline
ECircularGauge() [2/2]
ECircularGauge::ECircularGauge (QWidget * = NULL)
~ECircularGauge() [2/2]
ECircularGauge::~ECircularGauge () inline
Member Function Documentation
configure() [1/2]
virtual void ECircularGauge::configure () protected virtual
Reimplemented from EAbstractGauge.
configure() [2/2]
void ECircularGauge::configure () protected virtual
Reimplemented from EAbstractGauge.
References EAbstractGauge::configure(), EAbstractGauge::m_externalScale, EAbstractGauge::m_referenceEnabled, and EAbstractGauge::m_scaleEnabled.
drawColorBar() [1/2]
void ECircularGauge::drawColorBar (QPainter *) protected
drawColorBar() [2/2]
void ECircularGauge::drawColorBar (QPainter * p) protected
References EAbstractGauge::COLORBAR, EAbstractGauge::GRADIENT, EAbstractGauge::m_colorMode, EAbstractGauge::v_c, and EAbstractGauge::v_p.
Referenced by paintEvent().
drawLabels() [1/2]
void ECircularGauge::drawLabels (QPainter *) protected
drawLabels() [2/2]
void ECircularGauge::drawLabels (QPainter * p) protected
References EAbstractGauge::labels, EAbstractGauge::m_externalScale, and EAbstractGauge::m_numMajorTicks.
Referenced by paintEvent().
drawNeedle() [1/2]
void ECircularGauge::drawNeedle (QPainter *) protected
drawNeedle() [2/2]
void ECircularGauge::drawNeedle (QPainter * p) protected
References Elettra::black, EAbstractGauge::m_maxValue, EAbstractGauge::m_minValue, and EAbstractGauge::m_value.
Referenced by paintEvent().
drawScale() [1/2]
void ECircularGauge::drawScale (QPainter *) protected
drawScale() [2/2]
void ECircularGauge::drawScale (QPainter * p) protected
References Elettra::black, EColor(), EAbstractGauge::m_externalScale, EAbstractGauge::m_maxValue, EAbstractGauge::m_minValue, EAbstractGauge::m_numMajorTicks, EAbstractGauge::m_numMinorTicks, EAbstractGauge::m_reference, EAbstractGauge::m_referenceEnabled, and Elettra::red.
Referenced by paintEvent().
drawValue() [1/2]
void ECircularGauge::drawValue (QPainter *) protected
drawValue() [2/2]
void ECircularGauge::drawValue (QPainter * p) protected
References EAbstractGauge::d_naturalValue, EAbstractGauge::m_scaleEnabled, and EAbstractGauge::m_valueFormat.
Referenced by paintEvent().
isValueDisplayed() [1/2]
bool ECircularGauge::isValueDisplayed () inline
isValueDisplayed() [2/2]
bool ECircularGauge::isValueDisplayed () inline
label() [1/2]
QString ECircularGauge::label () inline
label() [2/2]
QString ECircularGauge::label () inline
paintEvent() [1/2]
void ECircularGauge::paintEvent (QPaintEvent *) protected
paintEvent() [2/2]
void ECircularGauge::paintEvent (QPaintEvent *) protected
References drawColorBar(), drawLabels(), drawNeedle(), drawScale(), drawValue(), and EAbstractGauge::m_scaleEnabled.
setLabel() [1/2]
void ECircularGauge::setLabel (QString l) inline
setLabel() [2/2]
void ECircularGauge::setLabel (QString l) inline
Referenced by QuCircularGauge::onUpdate().
setValueDisplayed() [1/2]
void ECircularGauge::setValueDisplayed (bool b) inline
setValueDisplayed() [2/2]
void ECircularGauge::setValueDisplayed (bool b) inline
Property Documentation
label
QString ECircularGauge::label read write
valueDisplayed
bool ECircularGauge::valueDisplayed read write
The documentation for this class was generated from the following files:
egauge.h
egauge_copy.h
egauge.cpp