cumbia-run: curun_db Namespace Reference
curun_db Namespace Reference
Classes
class Context
class Cmd
class Loader_I
class FileLoader
class DbLoader
class Indexes
class App
class Ctx
class Mode
Functions
def find_bin (path, appnam)
def get_sql_dbf ()
def get_env (argvs)
def get_cmd_args (argvs)
def add (cmdline)
def context (appnam, tbl)
def mkcontexts (res_tup)
def mkcmdlines (cmdls)
def get_cmdparts (argv)
def pick_choice (cmds)
def cmd_insert (cmdli, cmd)
def cmd_unite (cmds, newcmds)
def set_local_exe (exnam, cmdset)
def get_paths (app)
def rem_suffix (path)
def get_abs_path_and_bin (cmd)
def appnam_from_wdir (wdir)
def main ()
Variables
string sqldbf_relpath = '.config/cumbia/cumbia-run/cumbia-run.db'
string devel_dir = 'devel/cs/gui'
string THIS_FILE = 'curun_db.py'
Function Documentation
add()
def curun_db.add (cmdline)
References get_cmd_args(), get_env(), get_sql_dbf(), and rem_suffix().
Referenced by main().
appnam_from_wdir()
def curun_db.appnam_from_wdir (wdir)
Referenced by main().
cmd_insert()
def curun_db.cmd_insert (cmdli, cmd)
Referenced by main().
cmd_unite()
def curun_db.cmd_unite (cmds, newcmds)
Referenced by main().
context()
def curun_db.context (appnam, tbl)
returns the context pertaining to the app 'appnam' in this form:
         (environment_vars=VAR1 VAR2) arg1 arg2 arg3 ...
        If no environment variable is defined:
        () arg1 arg2 arg3
References get_sql_dbf().
Referenced by main().
find_bin()
def curun_db.find_bin (path, appnam)
References get_sql_dbf().
Referenced by main().
get_abs_path_and_bin()
def curun_db.get_abs_path_and_bin (cmd)
Referenced by main().
get_cmd_args()
def curun_db.get_cmd_args (argvs)
Referenced by add(), and main().
get_cmdparts()
def curun_db.get_cmdparts (argv)
get_env()
def curun_db.get_env (argvs)
Referenced by add(), and main().
get_paths()
def curun_db.get_paths (app)
References get_sql_dbf().
Referenced by main().
get_sql_dbf()
def curun_db.get_sql_dbf ()
Referenced by add(), context(), find_bin(), get_paths(), curun_db.DbLoader.load(), and rem_suffix().
main()
def curun_db.main ()
References add(), appnam_from_wdir(), cmd_insert(), cmd_unite(), context(), find_bin(), get_abs_path_and_bin(), get_cmd_args(), get_env(), get_paths(), mkcontexts(), pick_choice(), rem_suffix(), and set_local_exe().
mkcmdlines()
def curun_db.mkcmdlines (cmdls)
mkcontexts()
def curun_db.mkcontexts (res_tup)
Referenced by main().
pick_choice()
def curun_db.pick_choice (cmds)
Referenced by main().
rem_suffix()
def curun_db.rem_suffix (path)
References get_sql_dbf().
Referenced by add(), and main().
set_local_exe()
def curun_db.set_local_exe (exnam, cmdset)
Referenced by main().
Variable Documentation
devel_dir
string curun_db.devel_dir = 'devel/cs/gui'
sqldbf_relpath
string curun_db.sqldbf_relpath = '.config/cumbia/cumbia-run/cumbia-run.db'
THIS_FILE
string curun_db.THIS_FILE = 'curun_db.py'