cumbia: CuIsolatedActivity Class Reference
CuIsolatedActivity Class Reference
A convenient CuActivity designed to be executed only once.
#include <cuisolatedactivity.h>
Public Member Functions
CuIsolatedActivity (const CuData &token=CuData(), CuActivityManager *activityManager=NULL)
class constructor. Takes optional arguments and sets up the isolated activity
~CuIsolatedActivity ()
the class destructor
bool unregisterOnExit () const
returns the value of the CuAUnregisterAfterExec flag (true or false)
bool deleteOnExit () const
returns the value of the CuADeleteOnExit flag (true or false)
int repeat () const
returns -1 to indicate that CuActivity::execute is called only once
int getType () const
returns the value that identifies an isolated activity
Public Member Functions inherited from CuActivity
CuActivity (CuActivityManager *activityManager, const CuData &token=CuData())
CuActivity (const CuData &token=CuData())
virtual ~CuActivity ()
void setActivityManager (CuActivityManager *am)
virtual void event (CuActivityEvent *e)=0
Receive events from the main thread in the CuActivity thread of execution.
virtual int getFlags () const
returns the activity flags
int getStateFlags () const
returns the activity state flags
void setFlags (int f)
set the flags on the activity
void setFlag (Flags f, bool on)
set a specific CuActivity::Flags flag true or false
virtual bool matches (const CuData &token) const =0
virtual void dispose (bool disposable=true)
virtual bool isDisposable () const
void publishResult (const CuData &data)
Publish a result from the activity thread (whence the method is called) to the main thread.
void publishProgress (int step, int total, const CuData &data)
Publish a progress from the activity thread (whence the method is called) to the main thread.
void publishExitResult (const CuData *data)
void publishResult (const std::vector< CuData > *datalist)
CuActivityManager * getActivityManager () const
CuData getToken () const
return the activity token
void doInit ()
void doExecute ()
void doOnExit ()
calls the pure virtual method onExit, gets the thread it belongs and calls CuThreadInterface::publishExitEvent
void exitOnThreadQuit ()
template method. Calls onExit only, without publishing exit event, because the thread is leaving its loop.
Additional Inherited Members
Public Types inherited from CuActivity
enum Flags { CuAUnregisterAfterExec = 0x01, CuADeleteOnExit = 0x02, CuAUserStartFlags = 0x0100, MaxUserFlags = 0x8000 }
enum StateFlags { CuAStateInit = 0x01, CuAStateExecute = 0x02, CuAStateOnExit = 0x04 }
enum ActivityType { Isolated = 0, Continuous, User = 100 }
Protected Member Functions inherited from CuActivity
virtual void init ()=0
virtual void execute ()=0
virtual void onExit ()=0
Detailed Description
A convenient CuActivity designed to be executed only once.
This activity enables the flags CuActivity::CuADeleteOnExit and CuActivity::CuAUnregisterAfterExec and the CuIsolatedActivity::repeat method returns -1 in order to be executed once, automatically unregistered and disposed after its execution.
Two convenience methods unregisterOnExit and deleteOnExit are a shortcut to get the values of the aforementioned flags.
Constructor & Destructor Documentation
CuIsolatedActivity()
CuIsolatedActivity::CuIsolatedActivity (const CuData & token = CuData(), CuActivityManager * activityManager = NULL)
class constructor. Takes optional arguments and sets up the isolated activity
Parameters
token a CuData that will describe this activity (default: empty CuData)
activityManager a pointer to the CuActivityManager (default: NULL and usually set later by Cumbia::registerActivity)
activity flags
The following flags are set to true: CuActivity::CuADeleteOnExit and CuActivity::CuAUnregisterAfterExec. Call CuActivity::setFlags to change the default behaviour.
References CuActivity::CuADeleteOnExit, CuActivity::CuAUnregisterAfterExec, and CuActivity::setFlags().
~CuIsolatedActivity()
CuIsolatedActivity::~CuIsolatedActivity ()
the class destructor
nothing to report
References pdelete.
Member Function Documentation
deleteOnExit()
bool CuIsolatedActivity::deleteOnExit () const
returns the value of the CuADeleteOnExit flag (true or false)
Returns
true if the CuADeleteOnExit flag is set, false otherwise
If this method returns true, the activity is automatically deleted when it finishes.
See also
unregisterOnExit
References CuActivity::CuADeleteOnExit, and CuActivity::getFlags().
getType()
int CuIsolatedActivity::getType () const virtual
returns the value that identifies an isolated activity
Returns
the CuActivity::Isolated value from the CuActivity::ActivityType enum
Implements CuActivity.
References CuActivity::Isolated.
repeat()
int CuIsolatedActivity::repeat () const virtual
returns -1 to indicate that CuActivity::execute is called only once
Returns
-1 to indicate that CuActivity::execute is called only once
See also
CuContinuousActivity
Implements CuActivity.
unregisterOnExit()
bool CuIsolatedActivity::unregisterOnExit () const
returns the value of the CuAUnregisterAfterExec flag (true or false)
Returns
true if the CuAUnregisterAfterExec flag is set, false otherwise
See also
deleteOnExit
References CuActivity::CuAUnregisterAfterExec, and CuActivity::getFlags().
The documentation for this class was generated from the following files:
cuisolatedactivity.h
cuisolatedactivity.cpp