cumbia-qtcontrols: QuXtraWidgetPluginLoader Class Reference
QuXtraWidgetPluginLoader Class Reference
The QuXtraWidgetPluginLoader class finds the plugin that exports a widget with a given file name.
#include <quxtrawidgetpluginloader.h>
Public Member Functions
QuXtraWidgetPluginLoader ()
virtual ~QuXtraWidgetPluginLoader ()
bool isAvailable (const QString &classnam)
QuXtraWidgetPluginLoader::isAvailable returns true if the widget with the given class name is made provided by one of the available extrawidget plugins.
QuXtraWidgetPluginI * getPlugin (const QString &classnam) const
Detailed Description
The QuXtraWidgetPluginLoader class finds the plugin that exports a widget with a given file name.
The plugin file names providing extra widgets (see the QuXtraWidgetPluginI) must be in one of the following forms:
mysetofwidgets-xwidgetplugin.so
mysetofwidgets-extrawidgetplugin.so
mysetofwidgets-xtrawidgetplugin.so
mysetofwidgets-xwidget-plugin.so
mysetofwidgets-xtrawidget-plugin.so
mysetofwidgets-extrawidget-plugin.so
my-xwidgetplugin-set1.so
More generally, the file name must contain the following regular expression:
(?:e){0,1}x(?:tra){0,1}widget[-]{0,1}plugin.*\.so
that matches somewhere in the name one of the keywords xwidgetplugin, xtrawidgetplugin, extrawidgetplugin with an optional dash between widget and plugin.
Constructor & Destructor Documentation
QuXtraWidgetPluginLoader()
QuXtraWidgetPluginLoader::QuXtraWidgetPluginLoader ()
~QuXtraWidgetPluginLoader()
QuXtraWidgetPluginLoader::~QuXtraWidgetPluginLoader () virtual
Member Function Documentation
getPlugin()
QuXtraWidgetPluginI * QuXtraWidgetPluginLoader::getPlugin (const QString & classnam) const
References QuXtraWidgetPluginI::catalogue(), and CuPluginLoader::getPluginAbsoluteFilePaths().
Referenced by isAvailable().
isAvailable()
bool QuXtraWidgetPluginLoader::isAvailable (const QString & classnam)
QuXtraWidgetPluginLoader::isAvailable returns true if the widget with the given class name is made provided by one of the available extrawidget plugins.
Parameters
classnam the widget name (widget class name)
Returns
true if the widget with the given name is available, false otherwise
References getPlugin().
The documentation for this class was generated from the following files:
quxtrawidgetpluginloader.h
quxtrawidgetpluginloader.cpp