cumbia-qtcontrols: CuContextMenuActionsPlugin_I Class Reference
CuContextMenuActionsPlugin_I Class Reference abstract
#include <cucontextmenuactionsplugin_i.h>
Public Member Functions
virtual ~CuContextMenuActionsPlugin_I ()
virtual int order () const =0
virtual void setup (QWidget *widget, const CuContext *cuctx)=0
virtual QList< QAction * > getActions () const =0
Constructor & Destructor Documentation
~CuContextMenuActionsPlugin_I()
virtual CuContextMenuActionsPlugin_I::~CuContextMenuActionsPlugin_I () inline virtual
Member Function Documentation
getActions()
virtual QList<QAction* > CuContextMenuActionsPlugin_I::getActions () const pure virtual
Referenced by CuContextMenu::CuContextMenu().
order()
virtual int CuContextMenuActionsPlugin_I::order () const pure virtual
Referenced by CuContextMenu::CuContextMenu().
setup()
virtual void CuContextMenuActionsPlugin_I::setup (QWidget * widget, const CuContext * cuctx) pure virtual
Referenced by CuContextMenu::CuContextMenu().
The documentation for this class was generated from the following file:
cucontextmenuactionsplugin_i.h