cumbia-qtcontrols: CuControlsFactoryPool Class Reference
CuControlsFactoryPool Class Reference
Core classes
this class, used in conjunction with CumbiaPool allows to connect to different control system frameworks within the same application.
#include <cucontrolsfactorypool.h>
Public Types
enum Type { Reader = 0 , Writer }
Public Member Functions
CuControlsFactoryPool ()
virtual ~CuControlsFactoryPool ()
void registerImpl (const std::string &domain, const CuControlsReaderFactoryI &rf)
register a reader factory for a domain:
void registerImpl (const std::string &domain, const CuControlsWriterFactoryI &wf)
register a writer factory for a domain:
void setSrcPatterns (const std::string &domain, const std::vector< std::string > &regexps)
set or change the source patterns (regular expressions) for the domain
void clearSrcPatterns (const std::string &domain)
remove patterns for the given domain
CuControlsReaderFactoryI * getReadFactory (const std::string &domain) const
returns the reader factory that was registered with the given domain
CuControlsWriterFactoryI * getWriteFactory (const std::string &domain) const
returns the writer factory that was registered with the given domain
CuControlsReaderFactoryI * getRFactoryBySrc (const std::string &src) const
if more than one factory is registered, uses the registered patterns to match the given source and returns a CuControlsReaderFactoryI, in case of pattern match, null otherwise
CuControlsWriterFactoryI * getWFactoryBySrc (const std::string &src) const
uses the registered patterns to match the given source and return a CuControlsWriterFactoryI if a correspondence is found.
std::string guessDomainBySrc (const std::string &src) const
given the source string, , tries to match it with the registered patterns in order to return the associated domain name
bool isEmpty () const
returns true if both the reader factory map and the writer factory map are empty.
std::vector< std::string > getSrcPatternDomains () const
std::vector< std::string > getSrcPatterns (const std::string &domain) const
void setDefaultDomain (const std::string &dom)
std::string defaultDomain () const
CuControlsFactoryPool (const CuControlsFactoryPool &other)
CuControlsFactoryPool (CuControlsFactoryPool &&other)
CuControlsFactoryPool & operator= (const CuControlsFactoryPool &other)
CuControlsFactoryPool & operator= (CuControlsFactoryPool &&other)
bool operator== (const CuControlsFactoryPool &other) const
bool operator!= (const CuControlsFactoryPool &other) const
Detailed Description
this class, used in conjunction with CumbiaPool allows to connect to different control system frameworks within the same application.
Reader and writer factories can be registered with registerImpl, providing a name for the domain they refer to. The following code registers reader and writer factories for epics and tango, making it possible to connect to sources belonging to these two different systems within the same application:
ctrl_factory_pool.registerImpl("tango", CuTWriterFactory());
ctrl_factory_pool.registerImpl("tango", CuTReaderFactory());
m_ctrl_factory_pool.registerImpl("epics", CuEpReaderFactory());
m_ctrl_factory_pool.registerImpl("epics", CuEpWriterFactory());
The setSrcPatterns method can be used to insert rules so that CuControlsFactoryPool can distribute sources among the registered engine implementations according to their syntax pattern:
std::vector<std::string> epics_patterns, tango_patterns;
epics_patterns.push_back(".+:.+"); // e.g. control:ai1 (epics PV)
tango_patterns.push_back(".+/.+"); // e.g. test/device/1/double_scalar
tango_patterns.push_back(".+->.+"); // e.g. test/device/1->DevLong
// associate a domain ("tango" or "epics") to a specific pattern.
ctrl_factory_pool.setSrcPatterns("epics", epics_patterns);
ctrl_factory_pool.setSrcPatterns("tango", tango_patterns);
Member Enumeration Documentation
Type
enum CuControlsFactoryPool::Type
Enumerator
Reader
Writer
Constructor & Destructor Documentation
CuControlsFactoryPool() [1/3]
CuControlsFactoryPool::CuControlsFactoryPool ()
~CuControlsFactoryPool()
CuControlsFactoryPool::~CuControlsFactoryPool () virtual
References CuControlsFactoryPool_P::unref().
CuControlsFactoryPool() [2/3]
CuControlsFactoryPool::CuControlsFactoryPool (const CuControlsFactoryPool & other)
References CuControlsFactoryPool_P::ref().
CuControlsFactoryPool() [3/3]
CuControlsFactoryPool::CuControlsFactoryPool (CuControlsFactoryPool && other)
Member Function Documentation
clearSrcPatterns()
void CuControlsFactoryPool::clearSrcPatterns (const std::string & domain)
remove patterns for the given domain
Parameters
domain a string with the domain name whose patterns are to be removed
References CuControlsFactoryPool_P::m_dom_patterns, and CuControlsFactoryPool_P::re_map.
defaultDomain()
std::string CuControlsFactoryPool::defaultDomain () const
References CuControlsFactoryPool_P::default_domain.
getReadFactory()
CuControlsReaderFactoryI * CuControlsFactoryPool::getReadFactory (const std::string & domain) const
returns the reader factory that was registered with the given domain
Parameters
domain the name of the domain registered with registerImpl
Returns
the CuControlsReaderFactoryI implementation corresponding to the given domain, or NULL if the domain wasn't registered.
References CuControlsFactoryPool_P::rmap.
Referenced by getRFactoryBySrc().
getRFactoryBySrc()
CuControlsReaderFactoryI * CuControlsFactoryPool::getRFactoryBySrc (const std::string & src) const
if more than one factory is registered, uses the registered patterns to match the given source and returns a CuControlsReaderFactoryI, in case of pattern match, null otherwise
Parameters
src the name of the source
Returns
a pointer to a registered CuControlsReaderFactoryI
Domain matching.
If the source src contains the "://" substring, the domain is matched with the string preceding the substring, and the corresponding factory implementation is returned. Otherwise, if only one factory has been registered, it is returned without any further matching, for the sake of performance. (since 1.5.1) Otherwise, the domain is guessed matching src against the regular expression patterns registered with setSrcPatterns.
Note
If no match is found, a null pointer is returned
References getReadFactory(), guessDomainBySrc(), and CuControlsFactoryPool_P::rmap.
getSrcPatternDomains()
std::vector< std::string > CuControlsFactoryPool::getSrcPatternDomains () const
References CuControlsFactoryPool_P::m_dom_patterns.
Referenced by CuEngineAccessor::engine_swap().
getSrcPatterns()
std::vector< std::string > CuControlsFactoryPool::getSrcPatterns (const std::string & domain) const
References CuControlsFactoryPool_P::m_dom_patterns.
getWFactoryBySrc()
CuControlsWriterFactoryI * CuControlsFactoryPool::getWFactoryBySrc (const std::string & src) const
uses the registered patterns to match the given source and return a CuControlsWriterFactoryI if a correspondence is found.
Parameters
src the name of the source
Returns
a CuControlsWriterFactoryI implementation matching the source.
Domain matching.
If the source src contains the "://" substring, the domain is matched with the string preceding the substring, and the corresponding factory implementation is returned. Otherwise, the domain is guessed matching src against the regular expression patterns registered with setSrcPatterns.
Note
If no match is found, a random CuControlsReaderFactoryI implementation may be returned (the first stored in the std::map).
References getWriteFactory(), guessDomainBySrc(), and CuControlsFactoryPool_P::wmap.
getWriteFactory()
CuControlsWriterFactoryI * CuControlsFactoryPool::getWriteFactory (const std::string & domain) const
returns the writer factory that was registered with the given domain
Parameters
domain the name of the domain registered with registerImpl
Returns
the CuControlsWriterFactoryI implementation corresponding to the given domain, or NULL if the domain wasn't registered.
References CuControlsFactoryPool_P::wmap.
Referenced by getWFactoryBySrc().
guessDomainBySrc()
std::string CuControlsFactoryPool::guessDomainBySrc (const std::string & src) const
given the source string, , tries to match it with the registered patterns in order to return the associated domain name
Parameters
src the source name
Returns
a string with the guessed domain or an empty string if no regexp match has been found.
References re(), and CuControlsFactoryPool_P::re_map.
Referenced by getRFactoryBySrc(), and getWFactoryBySrc().
isEmpty()
bool CuControlsFactoryPool::isEmpty () const
returns true if both the reader factory map and the writer factory map are empty.
Returns
true if both the reader factory map and the writer factory map are empty, false otherwise.
References CuControlsFactoryPool_P::rmap, and CuControlsFactoryPool_P::wmap.
Referenced by QmlReaderBackend::init().
operator!=()
bool CuControlsFactoryPool::operator!= (const CuControlsFactoryPool & other) const
operator=() [1/2]
CuControlsFactoryPool & CuControlsFactoryPool::operator= (const CuControlsFactoryPool & other)
References CuControlsFactoryPool_P::ref(), and CuControlsFactoryPool_P::unref().
operator=() [2/2]
CuControlsFactoryPool & CuControlsFactoryPool::operator= (CuControlsFactoryPool && other)
References CuControlsFactoryPool_P::unref().
operator==()
bool CuControlsFactoryPool::operator== (const CuControlsFactoryPool & other) const
References CuControlsFactoryPool_P::default_domain, CuControlsFactoryPool_P::m_dom_patterns, CuControlsFactoryPool_P::rmap, and CuControlsFactoryPool_P::wmap.
registerImpl() [1/2]
void CuControlsFactoryPool::registerImpl (const std::string & domain, const CuControlsReaderFactoryI & rf)
register a reader factory for a domain:
Parameters
domain a string identifying a domain, e.g. "tango" or "epics"
rf an instance of an object implementing CuControlsReaderFactoryI, such as CuTReaderFactory or CuEpReaderFactory
References CuControlsReaderFactoryI::clone(), and CuControlsFactoryPool_P::rmap.
Referenced by main().
registerImpl() [2/2]
void CuControlsFactoryPool::registerImpl (const std::string & domain, const CuControlsWriterFactoryI & wf)
register a writer factory for a domain:
Parameters
domain a string identifying a domain, e.g. "tango" or "epics"
wf an instance of an object implementing CuControlsWriterFactoryI, such as CuTWriterFactory or CuEpWriterFactory
References CuControlsWriterFactoryI::clone(), and CuControlsFactoryPool_P::wmap.
setDefaultDomain()
void CuControlsFactoryPool::setDefaultDomain (const std::string & dom)
References CuControlsFactoryPool_P::default_domain.
setSrcPatterns()
void CuControlsFactoryPool::setSrcPatterns (const std::string & domain, const std::vector< std::string > & regex_patt)
set or change the source patterns (regular expressions) for the domain
Parameters
domain a string identifying a domain, e.g. "tango" or "epics"
regex_patt a vector of string with the set of regular expressions that are used to match and assign sources to engines.
References CuControlsFactoryPool_P::m_dom_patterns, and CuControlsFactoryPool_P::re_map.
Referenced by main().
The documentation for this class was generated from the following files:
cucontrolsfactorypool.h
cucontrolsfactorypool.cpp