cumbia-qtcontrols: QuPlotMarkerComponent Class Reference
QuPlotMarkerComponent Class Reference
Display widgets » Plots
QuPlot component to draw markers on the canvas.
#include <quplotmarkercomponent.h>
Public Member Functions
QuPlotMarkerComponent (QuPlotBase *plot)
virtual ~QuPlotMarkerComponent ()
QString name () const
bool update (const QuPlotBase *plot)
QString xLabel () const
QString yLabel () const
QString label () const
returns the text currently displayed
void setFormatter (QuPlotMarkerFormat_I *pmf)
Use a custom implementation of QuPlotMarkerFormat_I to format the marker text.
QuPlotMarkerFormat_I * formatter () const
return the installed QuPlotMarkerFormat_I formatter or null
void setLabel (const QwtText &text)
set the marker label as QwtText
virtual void update (const QuPlotBase *plot, QwtPlotCurve *closestC, int closestPointIdx)
void hide ()
void show ()
bool isVisible () const
QwtPlotCurve * currentClosestCurve () const
int currentClosestPoint () const
Arrow * getArrow () const
QwtPlotMarker * qwtPlotMarker () const
QwtPlotPicker * qwtPlotPicker () const
void attachToPlot (QuPlotBase *plot)
in this method you would call QwtPlot::attach for the QwtPlotItem items in the component
void connectToPlot (QuPlotBase *plot)
in this method you would create Qt signal/slot connections
virtual QString markerText (const QuPlotBase *plot, const QwtPlotCurve *closest_curve, const int index)
returns a string containing a textual representation of the point on the curve the marker refers to
QList< QwtPlotCurve * > intersectingCurves (const QuPlotBase *plot, const double x, const double y, const QwtPlotCurve *curve)
QuPlotMarkerComponent::intersectingCurves.
Public Member Functions inherited from QuPlotComponent
virtual ~QuPlotComponent ()
Detailed Description
QuPlot component to draw markers on the canvas.
Constructor & Destructor Documentation
QuPlotMarkerComponent()
QuPlotMarkerComponent::QuPlotMarkerComponent (QuPlotBase * plot)
~QuPlotMarkerComponent()
QuPlotMarkerComponent::~QuPlotMarkerComponent () virtual
Member Function Documentation
attachToPlot()
void QuPlotMarkerComponent::attachToPlot (QuPlotBase * plot) virtual
in this method you would call QwtPlot::attach for the QwtPlotItem items in the component
Example
See QuPlotMarkerComponent::attachToPlot
Implements QuPlotComponent.
Referenced by QuPlotBase::init().
connectToPlot()
void QuPlotMarkerComponent::connectToPlot (QuPlotBase * plot) virtual
in this method you would create Qt signal/slot connections
Example
See QuPlotMarkerComponent::connectToPlot and QuPlotZoomComponent::connectToPlot
Implements QuPlotComponent.
Referenced by QuPlotBase::init().
currentClosestCurve()
QwtPlotCurve * QuPlotMarkerComponent::currentClosestCurve () const
Referenced by QuPlotBase::keyPressEvent(), and QuPlotBase::updateMarker().
currentClosestPoint()
int QuPlotMarkerComponent::currentClosestPoint () const
Referenced by QuPlotBase::updateMarker().
formatter()
QuPlotMarkerFormat_I * QuPlotMarkerComponent::formatter () const
return the installed QuPlotMarkerFormat_I formatter or null
See also
setFormatter
getArrow()
Arrow * QuPlotMarkerComponent::getArrow () const
hide()
void QuPlotMarkerComponent::hide ()
Referenced by QuPlotBase::hideMarker(), and QuPlotBase::showMarker().
intersectingCurves()
QList< QwtPlotCurve * > QuPlotMarkerComponent::intersectingCurves (const QuPlotBase * plot, const double x, const double y, const QwtPlotCurve * curve)
QuPlotMarkerComponent::intersectingCurves.
Parameters
plot the plot
x x point to check for any curve crossing x and y
y y point to check for any curve crossing x and y
curve the closest curve, that will not be in the list
Returns
a list of curves that cross curve at (x,y)
Note
The curve passed as input parameter is not included in the returned list
References QuPlotBase::curves().
Referenced by markerText().
isVisible()
bool QuPlotMarkerComponent::isVisible () const
Referenced by QuPlotBase::keyPressEvent(), QuPlotBase::mouseReleaseEvent(), QuPlotBase::plotZoomed(), and QuPlotBase::updateMarker().
label()
QString QuPlotMarkerComponent::label () const
returns the text currently displayed
Returns
the marker label text
markerText()
QString QuPlotMarkerComponent::markerText (const QuPlotBase * plot, const QwtPlotCurve * closest_curve, const int index) virtual
returns a string containing a textual representation of the point on the curve the marker refers to
Parameters
plot the pointer to the plot owning the marker
curve the curve to which the marker refers
index the index of the sample on the curve that the marker refers to
This method can be reimplemented on a custom QuPlotMarkerComponent in order to provide a text different from the default one. An alternative to QuPlotMarkerComponent subclassing is offered by the QuPlotMarkerFormat_I interface: just implement its format method and install the object with setFormatter.
Default text
The default text contains *x: [x value]
[source name]:[source value]*
Note
If you need further customization for the component, reimplement the QuPlotMarkerComponent::update(const QuPlotBase *, QwtPlotCurve *, int) method to provide a different placement strategy, text alignment and so on.
References intersectingCurves(), RTTI_CURVE_OFFSET, and QuPlotCurve::text().
Referenced by update(), and update().
name()
QString QuPlotMarkerComponent::name () const virtual
Implements QuPlotComponent.
Referenced by QuPlotBase::init().
qwtPlotMarker()
QwtPlotMarker * QuPlotMarkerComponent::qwtPlotMarker () const
qwtPlotPicker()
QwtPlotPicker * QuPlotMarkerComponent::qwtPlotPicker () const
setFormatter()
void QuPlotMarkerComponent::setFormatter (QuPlotMarkerFormat_I * pmf)
Use a custom implementation of QuPlotMarkerFormat_I to format the marker text.
This offers an alternative to the reimplementation of QuPlotMarkerComponent::markerText in a subclass
QuPlotMarkerFormat_I subclasses shall implement the QuPlotMarkerFormat_I::format method to provide the marker's text.
Note
Ownership of the passed object is QuPlotMarkerComponent's
Subsequent calls delete previously installed QuPlotMarkerFormat_I
To remove an installed formatter, call this method with a nullptr argument
Parameters
pmf an implementation of the QuPlotMarkerFormat_I interface
Since
1.3.1
setLabel()
void QuPlotMarkerComponent::setLabel (const QwtText & text)
set the marker label as QwtText
Parameters
text the marker label text
show()
void QuPlotMarkerComponent::show ()
Referenced by QuPlotBase::showMarker().
update() [1/2]
bool QuPlotMarkerComponent::update (const QuPlotBase * plot)
References QuPlotBase::curves(), and markerText().
Referenced by QuPlotBase::updateMarker().
update() [2/2]
void QuPlotMarkerComponent::update (const QuPlotBase * plot, QwtPlotCurve * closestC, int closestPointIdx) virtual
References markerText().
xLabel()
QString QuPlotMarkerComponent::xLabel () const
Referenced by QuPlotBase::showMarker(), and QuPlotBase::updateMarker().
yLabel()
QString QuPlotMarkerComponent::yLabel () const
Referenced by QuPlotBase::showMarker(), and QuPlotBase::updateMarker().
The documentation for this class was generated from the following files:
quplotmarkercomponent.h
quplotmarkercomponent.cpp