cumbia-qtcontrols: QuLedBase Class Reference
QuLedBase Class Reference
Base widgets
A color led.
#include <quledbase.h>
Public Member Functions
QuLedBase (QWidget *)
virtual ~QuLedBase ()
void setColor (const QColor &, bool=true)
QColor color ()
int angle ()
void setAngle (int angle)
void setLedWidth (int)
void setLedHeight (int)
int ledWidth ()
int ledHeight ()
bool rectangular ()
void setRectangular (bool re)
void setAlphaChannel (int a)
int alphaChannel ()
bool gradientEnabled ()
void setGradientEnabled (bool grad)
bool linearGradient ()
void setLinearGradient (bool l)
double gradientStop ()
fine tunes the gradient end point.
void setGradientStop (double val)
changes the gradient stop point
double gradientStart ()
fine tunes the gradient end point.
void setGradientStart (double val)
changes the gradient start point
bool scaleContents ()
returns the scaleContents property.
void setScaleContents (bool s)
changes the property scaleContents
void setBorderColor (const QColor &c)
QColor borderColor () const
Protected Member Functions
virtual void paintEvent (QPaintEvent *)
virtual QSize sizeHint () const
virtual QSize minimumSizeHint () const
Properties
bool rectangular
bool gradientEnabled
int ledWidth
int ledHeight
int angle
int alphaChannel
bool linearGradient
bool scaleContents
double gradientStop
double gradientStart
Detailed Description
A color led.
QuLedBase is a widget tailored to show true/false values. It has a color, a width and height that might be different from the container widget's width or height, depending on the scaleContents property being false or true respectively. Moreover, a led can be rectangular or elliptical (circular), according to the rectangular property. The color of the led can be shaded by means of a linear or rectangular gradient, and the start and stop values of the gradient can be fine tuned via the gradientStop and gradientStart properties. An integer between 0 and 255 can be specified to define the alphaChannel property, to add transparency to your led.
scaleContents property and gradientStop and gradientStart properties were introduced in QTango 4.x.
Constructor & Destructor Documentation
QuLedBase()
QuLedBase::QuLedBase (QWidget * parent)
~QuLedBase()
QuLedBase::~QuLedBase () virtual
Member Function Documentation
alphaChannel()
int QuLedBase::alphaChannel ()
angle()
int QuLedBase::angle ()
borderColor()
QColor QuLedBase::borderColor () const
color()
QColor QuLedBase::color ()
gradientEnabled()
bool QuLedBase::gradientEnabled ()
gradientStart()
double QuLedBase::gradientStart ()
fine tunes the gradient end point.
If the gradient is enabled, then it is possible to fine tune the gradient stop point. The accepted values are those in the range 0..1. Gradients have one start and one stop point.
See also
setGradientStop
gradientStop()
double QuLedBase::gradientStop ()
fine tunes the gradient end point.
If the gradient is enabled, then it is possible to fine tune the gradient stop point. The accepted values are those in the range 0..1. Gradients have one start and one stop point.
See also
setGradientStop
ledHeight()
int QuLedBase::ledHeight ()
ledWidth()
int QuLedBase::ledWidth ()
linearGradient()
bool QuLedBase::linearGradient ()
minimumSizeHint()
QSize QuLedBase::minimumSizeHint () const protected virtual
References sizeHint().
paintEvent()
void QuLedBase::paintEvent (QPaintEvent *) protected virtual
References EColor(), Elettra::gray, ledHeight, ledWidth, and Elettra::white.
rectangular()
bool QuLedBase::rectangular ()
scaleContents()
bool QuLedBase::scaleContents ()
returns the scaleContents property.
If the scaleContents property is true, then the led will fit the widget width ignoring the properties ledWidth and ledHeight.
See also
setScaleContents
setAlphaChannel()
void QuLedBase::setAlphaChannel (int a)
setAngle()
void QuLedBase::setAngle (int angle)
setBorderColor()
void QuLedBase::setBorderColor (const QColor & c)
Referenced by QuLed::onUpdate().
setColor()
void QuLedBase::setColor (const QColor & c, bool up = true)
Referenced by QuLed::onUpdate(), and QuLed::setValue().
setGradientEnabled()
void QuLedBase::setGradientEnabled (bool grad)
setGradientStart()
void QuLedBase::setGradientStart (double val)
changes the gradient start point
See also
gradientStart
setGradientStop()
void QuLedBase::setGradientStop (double val)
changes the gradient stop point
See also
gradientStop
setLedHeight()
void QuLedBase::setLedHeight (int h)
setLedWidth()
void QuLedBase::setLedWidth (int w)
setLinearGradient()
void QuLedBase::setLinearGradient (bool l)
setRectangular()
void QuLedBase::setRectangular (bool re)
References re().
setScaleContents()
void QuLedBase::setScaleContents (bool s)
changes the property scaleContents
See also
scaleContents
sizeHint()
QSize QuLedBase::sizeHint () const protected virtual
Referenced by minimumSizeHint().
Property Documentation
alphaChannel
int QuLedBase::alphaChannel read write
angle
int QuLedBase::angle read write
gradientEnabled
bool QuLedBase::gradientEnabled read write
gradientStart
double QuLedBase::gradientStart read write
gradientStop
double QuLedBase::gradientStop read write
ledHeight
int QuLedBase::ledHeight read write
Referenced by paintEvent().
ledWidth
int QuLedBase::ledWidth read write
Referenced by paintEvent().
linearGradient
bool QuLedBase::linearGradient read write
rectangular
bool QuLedBase::rectangular read write
scaleContents
bool QuLedBase::scaleContents read write
The documentation for this class was generated from the following files:
quledbase.h
quledbase.cpp