cumbia-qtcontrols: Qumbiaizer Class Reference
Qumbiaizer Class Reference
QTangoizes anything (not really anything, but...)
#include <qumbiaizer.h>
Public Types
enum Type {
Invalid = -1 , Void , Int , Double ,
UInt , Short , String , Bool ,
BoolVector , DoubleVector , StringVector , IntVector ,
Cu_Data
}
enum AutoConfType {
Min , Max , MinWarn , MaxWarn ,
MinErr , MaxErr , StdUnit , Unit ,
DisplayUnit , Description , Label
}
Supported auto configuration parameters with which you can invoke slots on the attached refreshee.
Signals
void configured (const CuData &)
auto configuration signal.
void connectionOk (bool ok)
emitted when the type of data received within onUpdate is set to property
void connectionErrorMessage (const QString &msg)
a signal that contains the error message related to setSource - or setTargets - failures.
void refreshMessage (const QString &message)
Emitted by the refresh method. The message is taken from the TVariant.
void readOk (bool success)
this signal is emitted by the QuWatcher::onUpdate method and the success parameter indicates whether the reading is successful or not.
void newData (short s)
newData for short data types
void newData (int i)
newData for int data types
void newData (double d)
newData for double data types
void newData (const QString &s)
newData for string data types
void newData ()
void newData (unsigned int ui)
newData for unsigned int data types
void newData (unsigned short us)
newData for unsigned short data types
void newData (bool b)
newData for unsigned bool data types
void newData (const QVector< double > &)
newData for vector of double data types
void newData (const QVector< int > &vi)
newData for vector of int data types
void newData (const QVector< bool > &bv)
newData for vector of boolean
void newData (const QStringList &slv)
newData for string list
void newData (const CuData &data)
newData signal passing the whole data bundle
Public Member Functions
Qumbiaizer (QObject *parent)
virtual ~Qumbiaizer ()
bool error () const
QString message () const
virtual void attach (QObject *object, const char *method, const char *setPointSlot=NULL, Qt::ConnectionType connType=Qt::AutoConnection)
associate a QObject and one or two methods to be invoked by the class on new data arrival (QTWatcher) or on target execution (QTWriter).
void attach (short *s)
void attach (double *d)
void attach (int *i)
void attach (unsigned int *u)
void attach (QString *qs)
void attach (bool *b)
void attach (QStringList *sl)
void attach (QVector< double > *v)
void attach (QVector< int > *vi)
void attach (QVector< bool > *vb)
void attach (CuData *da)
Type type () const
QString slot () const
QString methodName () const
returns the method name, without the full signature.
QString setPointSlot () const
QString setPointMethodName () const
void * data ()
Qt::ConnectionType connectionType () const
void setAutoConfSlot (AutoConfType act, const char *slot)
when minimum and maximum values are available, these slots are invoked.
bool inTypeOfMethod (const QString &method, QObject *obj, char *in_type)
writes into the in_type parameter the type of the input argument of the given method of the object obj.
int extractCode (QString &method)
extracts the signal/slot code at the beginning of the method name
void removeRefreshFilter (QuValueFilter *filter)
removes filter from the object.
void installRefreshFilter (QuValueFilter *filter)
install the QTRefreshFilter filter into the QTangoizer.
QuValueFilter * refreshFilter () const
returns the currently installed refresh filter.
void setSingleShot (bool singleShot)
Call this one before setSource to ensure that only one read is performed.
void setAutoDestroy (bool autoDestroy)
set single shot and then destroy the object right after the execution
bool autoDestroy () const
returns true if the object auto destroys itself after first execution.
bool singleShot () const
returns the singleShot property.
void setToolTipsDisabled (bool disable)
bool toolTipsDisabled () const
const char * type_str (Type t) const
Protected Slots
virtual void configure (const CuData &data)
Configures the attached object, if any.
virtual void updateValue (const CuData &v, bool read=true, const char *customMethod=NULL, QuValueFilter::State updateState=QuValueFilter::Update)
updates the listener with the new value
Protected Attributes
QumbiaizerPrivate * quizer_ptr
Detailed Description
QTangoizes anything (not really anything, but...)
This base class is reimplemented by QTWatcher and QTWriter to use QTangoCore in order to update widgets that are not QTango aware.
Member Enumeration Documentation
AutoConfType
enum Qumbiaizer::AutoConfType
Supported auto configuration parameters with which you can invoke slots on the attached refreshee.
See also
attach
setAutoConfSlot
Enumerator
Min
Max
MinWarn
MaxWarn
MinErr
MaxErr
StdUnit
Unit
DisplayUnit
Description
Label
Type
enum Qumbiaizer::Type
Enumerator
Invalid
Void
Int
Double
UInt
Short
String
Bool
BoolVector
DoubleVector
StringVector
IntVector
Cu_Data
Constructor & Destructor Documentation
Qumbiaizer()
Qumbiaizer::Qumbiaizer (QObject * parent)
References Invalid, and quizer_ptr.
~Qumbiaizer()
Qumbiaizer::~Qumbiaizer () virtual
References quizer_ptr.
Member Function Documentation
attach() [1/12]
void Qumbiaizer::attach (bool * b)
References Bool, and quizer_ptr.
attach() [2/12]
void Qumbiaizer::attach (CuData * da)
References Cu_Data, and quizer_ptr.
attach() [3/12]
void Qumbiaizer::attach (double * d)
References Double, and quizer_ptr.
attach() [4/12]
void Qumbiaizer::attach (int * i)
References Int, and quizer_ptr.
attach() [5/12]
void Qumbiaizer::attach (QObject * refreshee, const char * slot, const char * setPointSlot = NULL, Qt::ConnectionType connType = Qt::AutoConnection) virtual
associate a QObject and one or two methods to be invoked by the class on new data arrival (QTWatcher) or on target execution (QTWriter).
This method associates a QObject on which to invoke a slot when new data arrives (for readers) or a QObject from which to wait for signals to execute a target (for writers).
Parameters
object the QObject pointer
method the SLOT (readers) or SIGNAL (writers) methods to associate
setPointSlot if not NULL, this is the slot to be invoked in auto configuration to initialize the value read first.
connType the Qt::ConnectionType for signals/slots
The type of input parameter is detected on the basis of the method specified. For instance setValue(int) will detect an Int data type. If you specify a setPointSlot, remember that its data type must be the same as the data type of the method.
Reimplemented in QuWriter.
References Bool, BoolVector, Cu_Data, Double, DoubleVector, extractCode(), Int, IntVector, inTypeOfMethod(), quizer_ptr, setPointSlot(), Short, slot(), String, StringVector, TYPELEN, UInt, and Void.
Referenced by QuWriter::attach(), and QuWatcher::QuWatcher().
attach() [6/12]
void Qumbiaizer::attach (QString * qs)
References quizer_ptr, and String.
attach() [7/12]
void Qumbiaizer::attach (QStringList * sl)
References quizer_ptr, and StringVector.
attach() [8/12]
void Qumbiaizer::attach (QVector< bool > * vb)
References BoolVector, and quizer_ptr.
attach() [9/12]
void Qumbiaizer::attach (QVector< double > * v)
References DoubleVector, and quizer_ptr.
attach() [10/12]
void Qumbiaizer::attach (QVector< int > * vi)
References IntVector, and quizer_ptr.
attach() [11/12]
void Qumbiaizer::attach (short * s)
References quizer_ptr, and Short.
attach() [12/12]
void Qumbiaizer::attach (unsigned int * u)
References quizer_ptr, and UInt.
autoDestroy()
bool Qumbiaizer::autoDestroy () const
returns true if the object auto destroys itself after first execution.
See also
setAutoDestroy
References quizer_ptr.
Referenced by setAutoDestroy(), and QuWatcher::unsetSource().
configure
void Qumbiaizer::configure (const CuData & data) protected virtual slot
Configures the attached object, if any.
If setAutoconfSlot has been called for some AutoConfType type, then the matching slots are invoked. If a custom slot has not been specified for the minimum and maximum properties, the method sets the minimum and maximum properties on the object, if they are defined. If attach was called specifying an additional slot to set the set point value, then it is invoked. This can be applied only to read/write quantities, when CuData contains the "w_value" value. Tango and Epics support read/write quantities.
The configured signal is emitted at the end. It can be used by the client to access other configuration parameters in data. The connectionOk signal is also emitted for convenience.
See also
setAutoconfSlot
References QuValueFilter::AutoConfiguration, configured(), connectionOk(), data(), quizer_ptr, and updateValue().
Referenced by QuWatcher::onUpdate(), and QuWriter::onUpdate().
configured
void Qumbiaizer::configured (const CuData &) signal
auto configuration signal.
Emitted once, when the type of data received within onUpdate is set to property, contains the whole configuration data.
Referenced by configure().
connectionErrorMessage
void Qumbiaizer::connectionErrorMessage (const QString & msg) signal
a signal that contains the error message related to setSource - or setTargets - failures.
Connect this signal to any slot accepting a QString as input parameter if you want to know the error message related to the setSource() or setTargets() failure. Mapped from QTangoCommunicationHandle::connectionErrorMessage()
Parameters
msg the error message
connectionOk
void Qumbiaizer::connectionOk (bool ok) signal
emitted when the type of data received within onUpdate is set to property
Parameters
ok true no error occurred
ok false an error occurred
Provided for convenience, connectionOk is emitted after the configured signal.
Referenced by configure().
connectionType()
Qt::ConnectionType Qumbiaizer::connectionType () const
References quizer_ptr.
Referenced by updateValue().
data()
void * Qumbiaizer::data ()
References quizer_ptr.
Referenced by configure(), QuWatcher::onUpdate(), QuWriter::onUpdate(), and updateValue().
error()
bool Qumbiaizer::error () const
References quizer_ptr.
extractCode()
int Qumbiaizer::extractCode (QString & method)
extracts the signal/slot code at the beginning of the method name
methods are specified via SIGNAL and SLOT macros, so we have to remove signals and slots codes from the method. See qt/src/corelib/kernel/qobject.h and qt/src/corelib/kernel/qobject.cpp. Returns the extracted code and removes the code from the method parameter if the code is QSIGNAL_CODE or QSLOT_CODE.
References quizer_ptr.
Referenced by attach(), and QuWriter::attach().
installRefreshFilter()
void Qumbiaizer::installRefreshFilter (QuValueFilter * filter)
install the QTRefreshFilter filter into the QTangoizer.
Whenever data is updated, your implementation of the filter methods is invoked so that the read data can be modified before being displayed on a widget or stored into a variable. For each kind of data there is a method.
See also
QTRefreshFilter
References quizer_ptr.
inTypeOfMethod()
bool Qumbiaizer::inTypeOfMethod (const QString & method, QObject * obj, char * in_type)
writes into the in_type parameter the type of the input argument of the given method of the object obj.
Parameters
the method name, which has to have only one argument, for instance setMinimum(int), setValue(double), setText(QString)
obj the QObject on which to look for the type of input argument.
in_type a char pointing to previously allocated memory.
Returns
true the method succeeded
false the method failed (method signature not found or input argument count greater than one.
References quizer_ptr.
Referenced by attach(), and QuWriter::attach().
message()
QString Qumbiaizer::message () const
References quizer_ptr.
methodName()
QString Qumbiaizer::methodName () const
returns the method name, without the full signature.
For instance if slot() returns setValue(int), this method will return setValue
References quizer_ptr.
Referenced by updateValue().
newData [1/13]
void Qumbiaizer::newData () signal
Referenced by QuWatcher::onUpdate(), QuWriter::onUpdate(), and updateValue().
newData [2/13]
void Qumbiaizer::newData (bool b) signal
newData for unsigned bool data types
Parameters
b value as bool
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to bool // data["value"]
newData [3/13]
void Qumbiaizer::newData (const CuData & data) signal
newData signal passing the whole data bundle
Parameters
data value as full CuData bundle
Note
This signal is always emitted after the type specific version of the method. It can be used in particular cases where the whole information from CuData is required (name of the source, data type, timestamp, message, and so on..)
newData [4/13]
void Qumbiaizer::newData (const QString & s) signal
newData for string data types
Parameters
s value as QString
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to string // data["value"]
newData [5/13]
void Qumbiaizer::newData (const QStringList & slv) signal
newData for string list
Parameters
slv value as QStringList (const reference)
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to a list of strings // data["value"]
newData [6/13]
void Qumbiaizer::newData (const QVector< bool > & bv) signal
newData for vector of boolean
Parameters
bv value as QVector<bool> (const reference)
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to a vector of bool // data["value"]
newData [7/13]
void Qumbiaizer::newData (const QVector< double > &) signal
newData for vector of double data types
Parameters
dv value as QVector<double> (const reference)
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to a vector of double // data["value"]
newData [8/13]
void Qumbiaizer::newData (const QVector< int > & vi) signal
newData for vector of int data types
Parameters
vi value as QVector<int> (const reference)
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to a vector of int // data["value"]
newData [9/13]
void Qumbiaizer::newData (double d) signal
newData for double data types
Parameters
d value as double
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to double // data["value"]
newData [10/13]
void Qumbiaizer::newData (int i) signal
newData for int data types
Parameters
i value as int
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to int // data["value"]
newData [11/13]
void Qumbiaizer::newData (short s) signal
newData for short data types
Parameters
s value as short
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to short // data["value"]
newData [12/13]
void Qumbiaizer::newData (unsigned int ui) signal
newData for unsigned int data types
Parameters
ui value as unsigned
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to unsigned int // data["value"]
newData [13/13]
void Qumbiaizer::newData (unsigned short us) signal
newData for unsigned short data types
Parameters
us value as unsigned short
Note 1
The source must provide this precise data type
Note 2
The method extracts data[TTT::Value] and converts it to unsigned short // data["value"]
readOk
void Qumbiaizer::readOk (bool success) signal
this signal is emitted by the QuWatcher::onUpdate method and the success parameter indicates whether the reading is successful or not.
Parameters
success true if read was successful, false otherwise
Note
success contains the value of
!data[TTT::Err].toBool()
// data["err"]
Referenced by QuWatcher::onUpdate().
refreshFilter()
QuValueFilter * Qumbiaizer::refreshFilter () const
returns the currently installed refresh filter.
Returns
the currently installed refresh filter.
References quizer_ptr.
refreshMessage
void Qumbiaizer::refreshMessage (const QString & message) signal
Emitted by the refresh method. The message is taken from the TVariant.
Parameters
message either the error message or other piece of information from the source (e.g. timestamp)
See also
readOk
Referenced by QuWatcher::onUpdate().
removeRefreshFilter()
void Qumbiaizer::removeRefreshFilter (QuValueFilter * filter)
removes filter from the object.
This method does not delete filter.
References quizer_ptr.
setAutoConfSlot()
void Qumbiaizer::setAutoConfSlot (AutoConfType act, const char * slot)
when minimum and maximum values are available, these slots are invoked.
associate an auto configuration type to a slot to set the auto configuration value
These slots are invoked when the auto configuration is available. The QTWatcher api provides shortcuts to set minimum, maximum, min err, min warn, units. The supported data types for slots to be invoked are the ones enumerated in AutoConfType. Slots must take exactly one argument, and must be of type
int, double, short, unsigned int, QString.
Nothing else is supported.
See also
AutoConfType
Parameters
act an AutoConfType value
a slot that will be invoked at the configuration stage
References quizer_ptr, and slot().
setAutoDestroy()
void Qumbiaizer::setAutoDestroy (bool autoDestroy)
set single shot and then destroy the object right after the execution
Important note
The object is destroyed even if the execution is not successfully accomplished. This goes both for readers and for writers.
Note
Auto destruction for writers is possible only if the QTangoComProxyWriter::ExecutionMode is set to Synchronous (the default)
References autoDestroy(), and quizer_ptr.
Referenced by Qu1TWatcher::Qu1TWatcher(), and Qu1TWatcher::Qu1TWatcher().
setPointMethodName()
QString Qumbiaizer::setPointMethodName () const
References quizer_ptr.
setPointSlot()
QString Qumbiaizer::setPointSlot () const
References quizer_ptr.
Referenced by attach(), QuWriter::attach(), and QuWatcher::QuWatcher().
setSingleShot()
void Qumbiaizer::setSingleShot (bool singleShot)
Call this one before setSource to ensure that only one read is performed.
Parameters
singleShot true a single read is performed, then unsetSource is automatically called and the reader disconnected.
singleShot false the object behaves as usual, with the specified RefreshMode.
Call this method before setSource. Warning: reimplementing QTWatcher::refresh() method bypasses the singleShot property check and so setting singleShot to true will not work as expected.
References quizer_ptr, and singleShot().
Referenced by Qu1TWatcher::Qu1TWatcher(), and Qu1TWatcher::Qu1TWatcher().
setToolTipsDisabled()
void Qumbiaizer::setToolTipsDisabled (bool disable)
References quizer_ptr.
singleShot()
bool Qumbiaizer::singleShot () const
returns the singleShot property.
Returns
true only one read is performed (or was performed)
false the reader behaves as readers usually behave
References quizer_ptr.
Referenced by QuWatcher::onUpdate(), setSingleShot(), and QuWatcher::setSource().
slot()
QString Qumbiaizer::slot () const
References quizer_ptr.
Referenced by attach(), QuWatcher::QuWatcher(), setAutoConfSlot(), and updateValue().
toolTipsDisabled()
bool Qumbiaizer::toolTipsDisabled () const
References quizer_ptr.
type()
Qumbiaizer::Type Qumbiaizer::type () const
References quizer_ptr.
Referenced by updateValue().
type_str()
const char * Qumbiaizer::type_str (Qumbiaizer::Type t) const
References Bool, BoolVector, Cu_Data, Double, DoubleVector, Int, IntVector, Invalid, Short, String, StringVector, UInt, and Void.
Referenced by updateValue().
updateValue
void Qumbiaizer::updateValue (const CuData & v, bool read = true, const char * customMethod = NULL, QuValueFilter::State updateState = QuValueFilter::Update) protected virtual slot
updates the listener with the new value
Parameters
v the new data
read true the update refers to a read value (default: true and newData signals are emitted)
read false the update refers to a set point value. In this case, no newData signal is emitted
customMethod if not null, the customMethod is invoked rather then the methodName
updateState either QuValueFilter::AutoConfiguration or QuValueFilter::Update (default QuValueFilter::Update)
newData signals
A type specific newData signal is emitted if the data v contains a valid value key and no error has occurred.
slot invocation
If an object and a slot were provided through the proper attach method, the slot is invoked on the object.
References Bool, BoolVector, connectionType(), Cu_Data, data(), Double, DoubleVector, Int, IntVector, methodName(), newData(), quizer_ptr, Short, slot(), String, StringVector, type(), type_str(), and UInt.
Referenced by configure(), and QuWatcher::onUpdate().
Member Data Documentation
quizer_ptr
QumbiaizerPrivate* Qumbiaizer::quizer_ptr protected
Referenced by attach(), attach(), attach(), attach(), attach(), attach(), attach(), attach(), attach(), attach(), attach(), attach(), autoDestroy(), configure(), connectionType(), data(), error(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), QuWriter::execute(), extractCode(), installRefreshFilter(), inTypeOfMethod(), message(), methodName(), QuWriter::onUpdate(), QuWriter::postExecute(), Qumbiaizer(), refreshFilter(), removeRefreshFilter(), setAutoConfSlot(), setAutoDestroy(), setPointMethodName(), setPointSlot(), setSingleShot(), setToolTipsDisabled(), singleShot(), slot(), toolTipsDisabled(), type(), updateValue(), and ~Qumbiaizer().
The documentation for this class was generated from the following files:
qumbiaizer.h
qumbiaizer.cpp