cumbia-qtcontrols: QuApplyNumeric Class Reference
QuApplyNumeric Class Reference
Input widgets
A widget to input a number and write it to a target linked to a control system engine.
#include <quapplynumeric.h>
Public Slots
void setTarget (const QString &target)
Set the name of the target that will be executed.
virtual void execute (double val)
executes the target specified with setTarget, writing the value set on the widget.
void onAnimationValueChanged (const QVariant &v)
Public Slots inherited from EApplyNumeric
virtual void applyValue ()
void clearModified ()
virtual void setFont (const QFont &)
void disable ()
Public Member Functions
QuApplyNumeric (QWidget *parent, Cumbia *cumbia, const CuControlsWriterFactoryI &w_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsWriterFactoryI interface.
QuApplyNumeric (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuApplyNumeric ()
class destructor
QString target () const
void onUpdate (const CuData &d)
configures the widget as soon as it is connected and records write errors.
CuContext * getContext () const
returns a pointer to the context
Public Member Functions inherited from EApplyNumeric
EApplyNumeric (QWidget *parent, int i=3, int d=1, Qt::Orientation pos=Qt::Horizontal)
~EApplyNumeric ()
bool applyButtonActive ()
returns the behaviour of the Apply button after a change in the value of the numeric widget
bool digitsFontScaleEnabled ()
void setDigitsFontScaleEnabled (bool en)
void setButtonPosition (Qt::Orientation pos)
Qt::Orientation buttonPosition () const
void setValue (double v)
double value () const
void setMaximum (double v)
double maximum () const
void setMinimum (double v)
double minimum () const
void setIntDigits (int i)
int intDigits () const
void setDecDigits (int d)
int decDigits () const
void setButtonText (const QString &s)
QString buttonText () const
bool isModified ()
returns the state of the ApplyNumeric.
void setApplyButtonActive (bool en)
changes the behaviour of the Apply button.
QFont numericFont () const
void setNumericFont (const QFont f)
QSize sizeHint () const
QSize minimumSizeHint () const
QWidget * getButton () const
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Protected Member Functions
void paintEvent (QPaintEvent *pe)
Properties
QString target
returns the target name.
Properties inherited from EApplyNumeric
double value
double maximum
double minimum
int integerDigits
int decimalDigits
Qt::Orientation buttonPos
QString buttonText
QFont numericFont
bool applyButtonActive
Additional Inherited Members
Signals inherited from EApplyNumeric
void clicked (double)
void valueChanged (double value)
signal emitted when the displayed value changes on the TApplyNumeric.
Detailed Description
A widget to input a number and write it to a target linked to a control system engine.
Constructor & Destructor Documentation
QuApplyNumeric() [1/2]
QuApplyNumeric::QuApplyNumeric (QWidget * parent, Cumbia * cumbia, const CuControlsWriterFactoryI & w_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsWriterFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuApplyNumeric() [2/2]
QuApplyNumeric::QuApplyNumeric (QWidget * parent, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuApplyNumeric()
QuApplyNumeric::~QuApplyNumeric () virtual
class destructor
Deletes the context used to link the widget to the writer.
Member Function Documentation
execute
void QuApplyNumeric::execute (double val) virtual slot
executes the target specified with setTarget, writing the value set on the widget.
The value set on the widget is written on the target when the apply button is clicked. This virtual method can be reimplemented on a subclass.
References QuAnimation::ElasticBottomLine, CuControlsWriterA::execute(), Elettra::gray, and CuControlsWriterA::setArgs().
getContext()
CuContext * QuApplyNumeric::getContext () const virtual
returns a pointer to the context
Returns
a pointer to the CuContext
Implements CuContextI.
onAnimationValueChanged
void QuApplyNumeric::onAnimationValueChanged (const QVariant & v) slot
References EApplyNumeric::getButton().
onUpdate()
void QuApplyNumeric::onUpdate (const CuData & da)
configures the widget as soon as it is connected and records write errors.
Parameters
da CuData containing configuration options upon link creation or write operation results.
References EApplyNumeric::clearModified(), EApplyNumeric::decimalDigits, Elettra::green, EApplyNumeric::integerDigits, Elettra::red, CuControlsWriterA::saveConfiguration(), EApplyNumeric::setDecDigits(), EApplyNumeric::setIntDigits(), EApplyNumeric::setMaximum(), EApplyNumeric::setMinimum(), EApplyNumeric::setValue(), QuAnimation::ShrinkingBottomLine, and target().
paintEvent()
void QuApplyNumeric::paintEvent (QPaintEvent * pe) protected
References EApplyNumeric::getButton().
setTarget
void QuApplyNumeric::setTarget (const QString & target) slot
Set the name of the target that will be executed.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References CuControlsWriterA::setTarget(), and target().
target()
QString QuApplyNumeric::target () const
Referenced by onUpdate(), and setTarget().
Property Documentation
target
QString QuApplyNumeric::target read write
returns the target name.
Returns
the target name, or an empty string if setTarget hasn't been called yet.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
The documentation for this class was generated from the following files:
quapplynumeric.h
quapplynumeric.cpp