cumbia-qtcontrols: QuButton Class Reference
QuButton Class Reference
Input widgets
A push button to write values or send commands to a target.
#include <qubutton.h>
Public Slots
virtual void execute ()
executes the target specified with setTarget
void setTarget (const QString &target)
Set the name of the target that will be executed.
virtual bool ctxSwap (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
void clearTarget ()
void onAnimationValueChanged (const QVariant &v)
This slot is invoked by QuAnimation when the animation value changes. Calls update to draw the animation.
Signals
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
void newData (const CuData &da)
Public Member Functions
QuButton (QWidget *parent, Cumbia *cumbia, const CuControlsWriterFactoryI &w_fac, const QString &text="Apply")
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsWriterFactoryI interface.
QuButton (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool, const QString &text="Apply")
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuButton ()
the class destructor.
QString target () const
get the name of the target
void onUpdate (const CuData &d)
the onUpdate method implementation for QuButton that can be overridden by subclasses.
CuContext * getContext () const
Returns a pointer to the CuContext in use.
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Protected Member Functions
void paintEvent (QPaintEvent *pe)
void contextMenuEvent (QContextMenuEvent *e)
Properties
QString target
Detailed Description
A push button to write values or send commands to a target.
Derives from QPushButton and acts as a writer when clicked. Set up the link with setTarget. When clicked, the execute method is called, the (optional) input arguments are evaluated and the write is performed on the target.
See also md_src_cumbia_qtcontrols_widget_constructors documentation.
Constructor & Destructor Documentation
QuButton() [1/2]
QuButton::QuButton (QWidget * parent, Cumbia * cumbia, const CuControlsWriterFactoryI & w_fac, const QString & text = "Apply")
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsWriterFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuButton() [2/2]
QuButton::QuButton (QWidget * w, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool, const QString & text = "Apply")
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuButton()
QuButton::~QuButton () virtual
the class destructor.
Deletes the context.
Member Function Documentation
clearTarget
void QuButton::clearTarget () slot
contextMenuEvent()
void QuButton::contextMenuEvent (QContextMenuEvent * e) protected
References CuContextMenu::popup().
ctxSwap
bool QuButton::ctxSwap (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool) virtual slot
References CuEngineSwap::ok(), and CuEngineSwap::replace().
execute
void QuButton::execute () virtual slot
executes the target specified with setTarget
If target contains an expression, this is evaluated and then execution is performed.
References CuControlsWriterA::execute(), CuControlsUtils::getArgs(), QuAnimation::RayOfLight, CuControlsWriterA::setArgs(), and target.
getContext()
CuContext * QuButton::getContext () const virtual
Returns a pointer to the CuContext in use.
Returns
a pointer to CuContext
Implements CuContextI.
linkStatsRequest
void QuButton::linkStatsRequest (QWidget * myself, CuContextI * myself_as_cwi) signal
newData
void QuButton::newData (const CuData & da) signal
Referenced by onUpdate().
onAnimationValueChanged
void QuButton::onAnimationValueChanged (const QVariant & v) slot
This slot is invoked by QuAnimation when the animation value changes. Calls update to draw the animation.
See also
QuAnimation::installOn
onUpdate()
void QuButton::onUpdate (const CuData & data)
the onUpdate method implementation for QuButton that can be overridden by subclasses.
This method simply writes a log message if an error occurs.
Implements CuDataListener::onUpdate.
References CuControlsUtils::initObjects(), newData(), CuControlsWriterA::saveConfiguration(), and target.
paintEvent()
void QuButton::paintEvent (QPaintEvent * pe) protected
setTarget
void QuButton::setTarget (const QString & target) slot
Set the name of the target that will be executed.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References CuControlsWriterA::setTarget(), and target.
target()
QString QuButton::target () const
get the name of the target
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
Returns
the target name, or an empty string if setTarget hasn't been called yet.
Property Documentation
target
QString QuButton::target read write
Referenced by execute(), onUpdate(), and setTarget().
The documentation for this class was generated from the following files:
qubutton.h
qubutton.cpp