cumbia-qtcontrols: CuControlsReaderA Class Reference
CuControlsReaderA Class Reference abstract
abstract class defining an interface for cumbia-qtcontrols readers
#include <cucontrolsreader_abs.h>
Public Member Functions
CuControlsReaderA (Cumbia *c, CuDataListener *l)
virtual ~CuControlsReaderA ()
virtual void setSource (const QString &s)=0
connect the specified source to the control system engine and start reading.
virtual QString source () const =0
returns the name of the source
virtual void unsetSource ()=0
disconnect the source
virtual void sendData (const CuData &d)=0
send data to the reader
virtual void getData (CuData &d_ino) const =0
get data from the reader
Cumbia * getCumbia () const
returns a pointer to the Cumbia implementation that was passed to the class constructor
CuDataListener * getDataListener () const
return the CuDataListener that was specified in the constructor.
Detailed Description
abstract class defining an interface for cumbia-qtcontrols readers
This abstract class defines an interface for readers. cumbia-qtcontrols readers do not know about the engine used to connect and read from the control system.
The method getCumbia returns a pointer to the Cumbia engine currently used by the reader. getDataListener returns a pointer to the CuDataListener that is listening for read updates. The CuDataListener and the Cumbia engine are passed to CuControlsReaderA in the constructor.
All the other are pure virtual methods that must be implemented in the subclass.
Constructor & Destructor Documentation
CuControlsReaderA()
CuControlsReaderA::CuControlsReaderA (Cumbia * c, CuDataListener * l) inline
the class constructor initialises the reader.
Parameters
c a pointer to the Cumbia instance in use.
l a CuDataListener that will receive updates.
Note both parameters must be not null
~CuControlsReaderA()
virtual CuControlsReaderA::~CuControlsReaderA () inline virtual
Member Function Documentation
getCumbia()
Cumbia * CuControlsReaderA::getCumbia () const inline
returns a pointer to the Cumbia implementation that was passed to the class constructor
Returns
a pointer to the Cumbia implementation used by the reader
getData()
virtual void CuControlsReaderA::getData (CuData & d_ino) const pure virtual
get data from the reader
Parameters
d_ino a bundle of key/value pairs defining the data to send to the reader and containing the results filled by the reader once the function returns
Referenced by CuContext::getData().
getDataListener()
CuDataListener * CuControlsReaderA::getDataListener () const inline
return the CuDataListener that was specified in the constructor.
Returns
the CuDataListener that receives new data updates.
sendData()
virtual void CuControlsReaderA::sendData (const CuData & d) pure virtual
send data to the reader
Parameters
d a bundle of key/value pairs defining the data to send to the reader
See also
getData
Referenced by CuContext::sendData(), and CuContext::sendData().
setSource()
virtual void CuControlsReaderA::setSource (const QString & s) pure virtual
connect the specified source to the control system engine and start reading.
Parameters
s the name of the source. The syntax depends on the engine.
Subclasses can check the parameter to ensure that its form is valid.
Referenced by QuPlotCommon::addSource(), CuEngineSwap::replace(), QuCheckBox::setSource(), QuCircularGauge::setSource(), QuLabel::setSource(), QuLed::setSource(), QuLinearGauge::setSource(), QuTable::setSource(), QuWatcher::setSource(), and QuPlotCommon::setSources().
source()
virtual QString CuControlsReaderA::source () const pure virtual
returns the name of the source
Returns
the name of the source configured with setSource.
If wildcards were used in setSource, source will return the complete source, with the substitutions.
Referenced by CuContext::disposeReader(), CuContext::findReader(), CuEngineSwap::replace(), QmlReaderBackend::source(), QuPlotCommon::sources(), QuSpectrumPlot::unsetSources(), and QuTrendPlot::unsetSources().
unsetSource()
virtual void CuControlsReaderA::unsetSource () pure virtual
disconnect the source
stop reading.
Referenced by CuContext::disposeReader().
The documentation for this class was generated from the following file:
cucontrolsreader_abs.h