cumbia-qtcontrols: QuPlotPanel Class Reference
QuPlotPanel Class Reference
#include <quplotpanel.h>
Signals
void settingsChanged (const QuPlotSettings &)
Public Member Functions
QuPlotPanel (QWidget *=NULL)
QuPlotSettings settings () const
void setSettings (const QuPlotSettings &)
Constructor & Destructor Documentation
QuPlotPanel()
QuPlotPanel::QuPlotPanel (QWidget * parent = NULL)
References setSettings().
Member Function Documentation
setSettings()
void QuPlotPanel::setSettings (const QuPlotSettings & s)
References QuPlotSettings::curveSettings::brush, QuPlotSettings::canvas, QuPlotSettings::curve, QuPlotSettings::curveSettings::functionType, QuPlotSettings::grid, QuPlotSettings::canvasSettings::immediatePaint, QuPlotSettings::curveSettings::lineSplitting, QuPlotSettings::curveSettings::numPoints, QuPlotSettings::canvasSettings::openGL, QuPlotSettings::curveSettings::paintAttributes, QuPlotSettings::canvasSettings::paintOnScreen, QuPlotSettings::curveSettings::pen, QuPlotSettings::gridSettings::pen, QuPlotSettings::curveSettings::renderHint, QuPlotSettings::updateInterval, QuPlotSettings::updateType, and QuPlotSettings::canvasSettings::useBackingStore.
Referenced by QuPlotPanel().
settings()
QuPlotSettings QuPlotPanel::settings () const
References QuPlotSettings::curveSettings::brush, QuPlotSettings::canvas, QuPlotSettings::curve, QuPlotSettings::curveSettings::functionType, QuPlotSettings::grid, QuPlotSettings::canvasSettings::immediatePaint, QuPlotSettings::curveSettings::lineSplitting, QuPlotSettings::curveSettings::numPoints, QuPlotSettings::canvasSettings::openGL, QuPlotSettings::curveSettings::paintAttributes, QuPlotSettings::canvasSettings::paintOnScreen, QuPlotSettings::curveSettings::pen, QuPlotSettings::gridSettings::pen, QuPlotSettings::curveSettings::renderHint, QuPlotSettings::setDataType, QuPlotSettings::updateInterval, QuPlotSettings::updateType, and QuPlotSettings::canvasSettings::useBackingStore.
Referenced by MainWindow::MainWindow().
settingsChanged
void QuPlotPanel::settingsChanged (const QuPlotSettings &) signal
The documentation for this class was generated from the following files:
quplotpanel.h
quplotpanel.cpp