cumbia-qtcontrols: CuContextMenu Class Reference
CuContextMenu Class Reference
A QObject filter that installs a context menu with actions defined by external plugins
#include <cucontextmenu.h>
Public Member Functions
CuContextMenu (QWidget *parent)
Creates a QMenu with a set of actions loaded from qumbia-plugins (libwidgets-std-context-menu-actions.so) and additional user actions defined in custom plugins.
~CuContextMenu ()
void popup (const QPoint &pos, const CuContext *ctx)
void prepare (const CuContext *ctx)
Detailed Description
A QObject filter that installs a context menu with actions defined by external plugins
A default implementation is provided by the qumbia-plugins/widgets-std-context-menu-actions plugin
See the CuContextMenu constructor documentation for further details.
Constructor & Destructor Documentation
CuContextMenu()
CuContextMenu::CuContextMenu (QWidget * parent) explicit
Creates a QMenu with a set of actions loaded from qumbia-plugins (libwidgets-std-context-menu-actions.so) and additional user actions defined in custom plugins.
Plese refer to the WidgetStdContextMenuActions class defined in qumbia-plugins/widgets-std-context-menu-actions plugin for further details.
The mentioned plugin loads some predefined actions, amongst which:
A Link statistics action, to request information about the underlying link.
A helper application action, if the parent stores a valid helperApplication property
Parameters
parent the parent widget of this menu.
ctx a const pointer to a CuContext (the widget's CuContext)
Custom actions
Custom actions can be provided by one or more additional plugins provided that:
they reside in a folder listed in the CUMBIA_PLUGIN_PATH environment variable (colon separated)
the name of the <cite>.so</cite> plugin library ends with <cite>context-menu-actions.so</cite>. The list of actions is populated starting with those provided by custom plugins within the CUMBIA_PLUGIN_PATH and finally with the ones provided by libwidgets-std-context-menu-actions.so.
~CuContextMenu()
CuContextMenu::~CuContextMenu ()
Member Function Documentation
popup()
void CuContextMenu::popup (const QPoint & pos, const CuContext * ctx)
References prepare().
Referenced by QuButton::contextMenuEvent(), QuCheckBox::contextMenuEvent(), QuCircularGauge::contextMenuEvent(), QuComboBox::contextMenuEvent(), QuLabel::contextMenuEvent(), QuLed::contextMenuEvent(), QuLinearGauge::contextMenuEvent(), and QuTable::contextMenuEvent().
prepare()
void CuContextMenu::prepare (const CuContext * ctx)
References CuContextMenuActionsPlugin_I::getActions(), CuPluginLoader::getPluginAbsoluteFilePaths(), CuContextMenuActionsPlugin_I::order(), and CuContextMenuActionsPlugin_I::setup().
Referenced by QuPlotContextMenuStrategy::createMenu(), and popup().
The documentation for this class was generated from the following files:
cucontextmenu.h
cucontextmenu.cpp