cumbia-qtcontrols: QuPlot Class Reference
QuPlot Class Reference
#include <quplot.h>
Public Slots
void setSettings (const QuPlotSettings &)
Public Slots inherited from QuSpectrumPlot
void setSource (const QString &s)
void setSources (const QStringList &l)
void ctxSwap (CumbiaPool *cp, const CuControlsFactoryPool &fp)
void addSource (const QString &s)
void unsetSource (const QString &s)
void unsetSources ()
void setOptions (const CuData &options)
void setPeriod (int p)
Changes the refresh period on the plot, issuing a setData on every reader with a CuData containing the "period" property set to p.
void requestLinkStats ()
Public Slots inherited from QuPlotBase
virtual void refresh ()
Calls updateMarkers, updateScales and replot, resetting the zoom base in the end.
void setXAxisAutoscaleEnabled (bool en, QwtPlot::Axis axis)
void setYAxisAutoscaleEnabled (bool en, QwtPlot::Axis axis)
void setXTopAxisAutoscaleEnabled (bool autoscale)
void setYRightAxisAutoscaleEnabled (bool autoscale)
void setYLowerBound (double l)
void setYUpperBound (double u)
void setXLowerBound (double l)
void setXUpperBound (double u)
void setXAutoscaleMargin (double d)
void setUpperBoundExtra (int axisId, double e)
add some extra upper bound to the specified axis to optimize replot operations when the refresh rate is fast.
double upperBoundExtra (int axisId) const
double xAutoscaleMargin ()
void setYAutoscaleAdjustment (double d)
double yAutoscaleAdjustment ()
void setTitleOnCanvasEnabled (bool en)
void setCurveStyle (const QString &curveName, QwtPlotCurve::CurveStyle)
void setDataBufferSize (int b)
void setZoomDisabled (bool)
void clearPlot ()
virtual void setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
virtual void setData (const QString &curveName, double *xData, double *yData, int size)
virtual void appendData (const QString &curveName, double x, double y)
virtual void insertData (const QString &curveName, double *xData, double *yData, int size, double default_y=0.0)
insert data into the plot ordered by x values
void setRefreshTimeout (int millis)
void setDefaultBounds (double lb, double ub, Axis axisId=QwtPlot::yLeft)
void restoreDefaultBounds (Axis axisId=QwtPlot::yLeft)
restores the bounds set with setDefaultBounds
void setAxisScaleDefaultEnabled (bool en, Axis axisId=QwtPlot::yLeft)
Restores the bounds of axisId to their default values if en is true, does nothing if en is false.
void setXAxisAutoscaleEnabled (bool autoscale)
void setYAxisAutoscaleEnabled (bool autoscale)
Public Member Functions
QuPlot (QWidget *=NULL)
Public Member Functions inherited from QuSpectrumPlot
QuSpectrumPlot (QWidget *w, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuSpectrumPlot (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
QuSpectrumPlot (QWidget *parent)
single parent-widget constructor. QuApplication properly initialized with cumbia engine objects is compulsory.
virtual ~QuSpectrumPlot ()
QString source () const
QStringList sources () const
int period () const
Get the refresh period of the sources issuing a getData on the first reader in the list.
CuContext * getContext () const
Return a reference to the CuContext in use.
void onUpdate (const CuData &d)
void update (const CuData &d)
Public Member Functions inherited from QuPlotBase
QuPlotBase (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
QuPlotBase (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
virtual ~QuPlotBase ()
CurveStyle curvesStyle ()
bool titleOnCanvasEnabled ()
bool xAxisAutoscaleEnabled (QwtPlot::Axis axis=QwtPlot::xBottom)
bool yAxisAutoscaleEnabled (QwtPlot::Axis axis=QwtPlot::yLeft)
double yUpperBound (QwtPlot::Axis axis=QwtPlot::yLeft)
double yLowerBound (QwtPlot::Axis axis=QwtPlot::yLeft)
double xUpperBound (QwtPlot::Axis axis=QwtPlot::xBottom)
double xLowerBound (QwtPlot::Axis axis=QwtPlot::xBottom)
double defaultLowerBound (QwtPlot::Axis axisId=QwtPlot::yLeft) const
double defaultUpperBound (QwtPlot::Axis axisId=QwtPlot::yLeft) const
bool xAxisLogScale (QwtPlot::Axis axis=QwtPlot::xBottom)
bool yAxisLogScale (QwtPlot::Axis axis=QwtPlot::yLeft)
void setXAxisLogScale (bool l, QwtPlot::Axis axis=QwtPlot::xBottom)
void setYAxisLogScale (bool l, QwtPlot::Axis axis=QwtPlot::yLeft)
bool zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
QList< QwtPlotCurve * > curves () const
void addCurve (const QString &curveName, QuPlotCurve *curve)
void removeCurve (const QString &curveName)
Removes the specified curve from the plot, deleting it.
void addCurve (const QString &curveName)
QuPlotCurve * curve (const QString &name)
int dataBufferSize ()
returns the data buffer size.
void hideMarker ()
void appendData (const QString &curveName, double *x, double *y, int size)
int refreshTimeout () const
void configure (const CuData &da)
void setUpdateStrategy (QuWidgetUpdateStrategyI *updateStrategy)
sets or replaces the update strategy (see the strategy design pattern)
void setContextMenuStrategy (QuWidgetContextMenuStrategyI *ctx_menu_strategy)
sets or replaces the context menu strategy (see the strategy design pattern)
QuWidgetUpdateStrategyI * updateStrategy () const
return the QuWidgetUpdateStrategyI implementation in use.
QuWidgetContextMenuStrategyI * contextMenuStrategy () const
return the QuWidgetContextMenuStrategyI implementation in use.
virtual QDialog * createConfigureDialog ()
virtual bool updateMarker ()
updates the marker, if visible, and returns true if it's visible, false otherwise
virtual bool updateScales ()
Updates the axes bounds for which autoscale is enabled.
void resetZoom ()
bool inZoom () const
QuPlotComponent * getComponent (const QString &name) const
returns the QuPlotComponent corresponding to the given name, nullptr if name is not valid
void registerComponent (QuPlotComponent *, const QString &name)
QuPlotComponent * unregisterComponent (const QString &name)
QuPlotBase::unregisterComponent unregister the component with the given name.
Public Member Functions inherited from QuWidgetInterface
virtual ~QuWidgetInterface ()
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Protected Member Functions
virtual void timerEvent (QTimerEvent *) QWT_OVERRIDE
Protected Member Functions inherited from QuPlotBase
virtual QString plotTitle ()
returns the plot title.
virtual void drawCanvas (QPainter *p)
void mouseReleaseEvent (QMouseEvent *ev)
void keyPressEvent (QKeyEvent *ke)
void moveCurveToYRight (QwtPlotCurve *c, bool yr)
virtual void init ()
void contextMenuEvent (QContextMenuEvent *)
QuPlotBase::contextMenuEvent executes a contextual menu when the plot is right clicked.
void us_to_ms (std::vector< double > &ts_us) const
convert input vector of timestamps in microseconds to a vector of timestamps in milliseconds
Additional Inherited Members
Public Types inherited from QuPlotBase
enum CurveStyle {
NoCurve , Lines , Sticks , Steps ,
Dots , UserCurve = 100
}
Signals inherited from QuSpectrumPlot
void newData (const CuData &)
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
Signals inherited from QuPlotBase
void plotClicked (const QPoint &pt, QwtPlotCurve *closestCurve, double x, double y, const QPoint &curvePoint)
void curveAdded (QuPlotCurve *)
This signal is emitted when a new curve is added to the plot.
void curveRemoved (QuPlotCurve *)
This signal is emitted whenever a curve is removed from the plot via removeCurve.
void markerTextChanged (const QString &yText, const QString &xText="", double x=0.0, double y=0.0)
void markerVisibilityChanged (bool visible)
Protected Slots inherited from QuPlotBase
void displayZoomHint ()
void eraseZoomHint ()
void plotZoomed (const QRectF &)
void showMarker (const QPolygon &p)
void print ()
void snapshot ()
void copyImage ()
virtual void configurePlot ()
void saveData ()
dumps the curves into a csv file.
Properties inherited from QuSpectrumPlot
QStringList sources
QString source
int period
Properties inherited from QuPlotBase
bool xAxisAutoscale
bool yAxisAutoscale
double yUpperBound
double yLowerBound
double xUpperBound
double xLowerBound
double xAutoscaleMargin
double yAutoscaleAdjustment
bool titleOnCanvasEnabled
bool yAxisLogScale
bool zoomDisabled
int dataBufferSize
int refreshTimeout
Constructor & Destructor Documentation
QuPlot()
QuPlot::QuPlot (QWidget * parent = NULL)
remove this section. Use QuPlotBase configuration
References QuPlotBase::addCurve(), and QuPlotBase::curve().
Member Function Documentation
setSettings
void QuPlot::setSettings (const QuPlotSettings & s) slot
References QuPlotSettings::curveSettings::brush, QuPlotSettings::canvas, QuPlotSettings::curve, CircularBuffer::fill(), QuPlotSettings::curveSettings::functionType, QuPlotSettings::grid, QuPlotSettings::canvasSettings::immediatePaint, QuPlotSettings::curveSettings::lineSplitting, QuPlotSettings::Noise, noise(), QuPlotSettings::curveSettings::numPoints, QuPlotSettings::canvasSettings::openGL, QuPlotSettings::curveSettings::paintAttributes, QuPlotSettings::canvasSettings::paintOnScreen, QuPlotSettings::curveSettings::pen, QuPlotSettings::gridSettings::pen, QuPlotSettings::curveSettings::renderHint, QuPlotSettings::setDataType, CircularBuffer::setFunction(), CircularBuffer::size(), QuPlotSettings::updateInterval, QuPlotSettings::canvasSettings::useBackingStore, QuPlotSettings::VectorSetData, QuPlotSettings::Wave, and wave().
timerEvent()
void QuPlot::timerEvent (QTimerEvent *) protected virtual
References CircularBuffer::getData(), QuPlotSettings::QuPlotRefresh, QuPlotBase::refresh(), QuPlotSettings::RepaintCanvas, QuPlotBase::setData(), QuPlotSettings::setDataType, CircularBuffer::setReferenceTime(), QuPlotSettings::updateType, and QuPlotSettings::VectorSetData.
The documentation for this class was generated from the following files:
quplot.h
quplot.cpp