cumbia-qtcontrols: QuLabelBase Class Reference
QuLabelBase Class Reference
Base widgets
A QLabel that in addition decorates its border and background.
#include <qulabelbase.h>
Public Slots
void setBorderWidth (double w)
sets the width of the border(s) drawn with the chosen color
void setDrawInternalBorder (bool draw)
virtual bool decode (const CuVariant &d, QColor &background) const
set the value to display on the label. Optionally check if the background color has been modified by the method
void setFormat (const QString &fmt)
void setMaximumLength (int len)
if the data shown is a string, truncate it to the given length
Public Member Functions
QuLabelBase (QWidget *parent)
QuLabelBase (const QString &text, QWidget *parent)
virtual ~QuLabelBase ()
void setBackground (const QColor &background)
set the background color of the label
void setBorderColor (const QColor &border)
changes the border color
void setDecoration (const QColor &background, const QColor &border)
changes the colors for the decoration of the label
double borderWidth () const
returns the width, in pixels, of the colored border that is drawn around the label
void setEnumDisplay (int val, const QString &text, const QColor &c)
int maximumLength () const
returns the maximum length of the displayed string
QSize minimumSizeHint () const override
reimplements QLabel::minimumSizeHint to ensure there is enough space to draw the decorations on the border
QSize sizeHint () const override
int heightForWidth (int w) const override
bool hasHeightForWidth () const override
bool drawInternalBorder () const
if enabled, an external and an internal border are drawn
QString format () const
returns the format used to represent a number, or an empty string if no format is specified
Protected Member Functions
void paintEvent (QPaintEvent *pe) override
Reimplements QLabel::paintEvent.
Properties
double borderWidth
bool drawInternalBorder
QString format
Friends
class QuLabel
Detailed Description
A QLabel that in addition decorates its border and background.
Constructor & Destructor Documentation
QuLabelBase() [1/2]
QuLabelBase::QuLabelBase (QWidget * parent)
References QuLabelBaseData::borderWidth, QuLabelBaseData::draw_internal_border, QuLabelBaseData::format, QuLabelBaseData::max_len, and QuLabelBaseData::size_scale.
QuLabelBase() [2/2]
QuLabelBase::QuLabelBase (const QString & text, QWidget * parent)
References QuLabelBaseData::borderWidth.
~QuLabelBase()
QuLabelBase::~QuLabelBase () virtual
Member Function Documentation
borderWidth()
double QuLabelBase::borderWidth () const
returns the width, in pixels, of the colored border that is drawn around the label
Please read setBorderWidth documentation for further details
References QuLabelBaseData::borderWidth.
decode
bool QuLabelBase::decode (const CuVariant & v, QColor & background) const virtual slot
set the value to display on the label. Optionally check if the background color has been modified by the method
Parameters
v the value as CuVariant.
background_modified,if not NULL, it will be set to
true if setValue changed the background of the label
false if setValue didn't change the background
The background of the label can be changed by set value if either
the type of data is boolean and the "trueColor" and "falseColor" properties are set to a valid QColor or
setEnumDisplay was used to associate integer values to a strings and a colors
Number formatting
If QuLabel::format is not empty, it is used to format the number. The format is forwarded to CuVariant::toString. If the latter method is called with an empty format, a default format is used within snprintf according to the data type in use.
See CuVariant::toString for further details.
References QuLabelBaseData::enum_d, QuLabelBaseData::format, QULABEL_MAXLEN, and QuLabelBaseData::text.
Referenced by QuLabel::onUpdate().
drawInternalBorder()
bool QuLabelBase::drawInternalBorder () const
if enabled, an external and an internal border are drawn
Returns
true two borders are drawn
false only the external border is drawn
Note
If the drawInternalBorder property is false, the external border color will represent the result of the reading (green: successful, red: unsuccessful)
See also
setDrawInternalBorder
References QuLabelBaseData::draw_internal_border.
format()
QString QuLabelBase::format () const
returns the format used to represent a number, or an empty string if no format is specified
Returns
the format to use for number representation
See also
setFormat
Note
QuLabelBase::setValue forwards the format to CuVariant::toString conversion method.
References QuLabelBaseData::format.
hasHeightForWidth()
bool QuLabelBase::hasHeightForWidth () const override
heightForWidth()
int QuLabelBase::heightForWidth (int w) const override
References QuLabelBaseData::borderWidth, and QuLabelBaseData::size_scale.
maximumLength()
int QuLabelBase::maximumLength () const
returns the maximum length of the displayed string
Applies to CuVariant::String data type only
See also
setMaximumLength
References QuLabelBaseData::max_len.
minimumSizeHint()
QSize QuLabelBase::minimumSizeHint () const override
reimplements QLabel::minimumSizeHint to ensure there is enough space to draw the decorations on the border
Returns
the minimum size hint for the label
References QuLabelBaseData::borderWidth, and QuLabelBaseData::size_scale.
paintEvent()
void QuLabelBase::paintEvent (QPaintEvent * pe) override protected
Reimplements QLabel::paintEvent.
Draws a decoration on the widget:
one pixel gray outer border
one pixel white border
borderWidth pixel with the color chosen for the border with the setDecoration method
one pixel inner white border
Note
the background color, set with the setDecoration method, is applied through the QLabel palette for the background role
References QuLabelBaseData::borderWidth, QuLabelBaseData::draw_internal_border, and QuLabelBaseData::result_border_color.
setBackground()
void QuLabelBase::setBackground (const QColor & background)
set the background color of the label
Parameters
background the background color
Note
The background is applied only if the color is valid. If the new background is equal to the former one, the label's palette is left untouched.
See also
setDecoration
References QuLabelBaseData::backgroundColor.
Referenced by QuLabel::onUpdate(), and setDecoration().
setBorderColor()
void QuLabelBase::setBorderColor (const QColor & border)
changes the border color
Parameters
border a QColor
Note
If either border is not valid or the new color is the same as the current one, nothing is done.
References QuLabelBaseData::result_border_color.
Referenced by QuLabel::onUpdate().
setBorderWidth
void QuLabelBase::setBorderWidth (double w) slot
sets the width of the border(s) drawn with the chosen color
Parameters
w the desired width of the border
By default, two borders are drawn:
a light gray external border;
an green interior border if the read is successful, a red one otherwise
The interior border drawing can be turned off with setDrawInternalBorder
See also
setDecoration
References QuLabelBaseData::borderWidth.
setDecoration()
void QuLabelBase::setDecoration (const QColor & background, const QColor & border)
changes the colors for the decoration of the label
Parameters
background sets the background color
border sets the border color
See also
borderWidth
setBackground
setDrawInternalBorder
References QuLabelBaseData::backgroundColor, QuLabelBaseData::result_border_color, and setBackground().
Referenced by ELabel::display(), and QuTable::onUpdate().
setDrawInternalBorder
void QuLabelBase::setDrawInternalBorder (bool draw) slot
References QuLabelBaseData::draw_internal_border.
Referenced by QuInputOutput::QuInputOutput(), and QuInputOutput::QuInputOutput().
setEnumDisplay()
void QuLabelBase::setEnumDisplay (int val, const QString & text, const QColor & c)
References QuLabelBaseData::enum_d.
setFormat
void QuLabelBase::setFormat (const QString & fmt) slot
References QuLabelBaseData::format.
setMaximumLength
void QuLabelBase::setMaximumLength (int len) slot
if the data shown is a string, truncate it to the given length
Parameters
len the maximum length of the string displayed by the label or -1 to let the string unmodified.
If the string is longer than len, it is truncated to len characters. The full string is appended to the label tooltip.
See also
maximumLength
References QuLabelBaseData::max_len.
sizeHint()
QSize QuLabelBase::sizeHint () const override
References QuLabelBaseData::borderWidth, and QuLabelBaseData::size_scale.
Friends And Related Symbol Documentation
QuLabel
friend class QuLabel friend
Property Documentation
borderWidth
double QuLabelBase::borderWidth read write
drawInternalBorder
bool QuLabelBase::drawInternalBorder read write
format
QString QuLabelBase::format read write
The documentation for this class was generated from the following files:
qulabelbase.h
qulabelbase.cpp