cumbia-qtcontrols: QuLineEdit Class Reference
QuLineEdit Class Reference
#include <qulineedit.h>
Public Slots
void setTarget (const QString &targets)
Set the name of the target that will be executed.
virtual bool ctxSwap (CumbiaPool *cu_p, const CuControlsFactoryPool &fpool)
Public Member Functions
QuLineEdit (QWidget *parent, Cumbia *cumbia, const CuControlsWriterFactoryI &w_fac)
QuLineEdit (QWidget *parent, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
QuLineEdit (QWidget *parent)
Classical, single parent-widget constructor. QuApplication properly initialized with cumbia engine objects is compulsory.
virtual ~QuLineEdit ()
virtual CuContext * getContext () const
Return a reference to the CuContext in use.
virtual void onUpdate (const CuData &data)
QString target () const
returns the target name.
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
QString target
Constructor & Destructor Documentation
QuLineEdit() [1/3]
QuLineEdit::QuLineEdit (QWidget * parent, Cumbia * cumbia, const CuControlsWriterFactoryI & w_fac)
QuLineEdit() [2/3]
QuLineEdit::QuLineEdit (QWidget * parent, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
QuLineEdit() [3/3]
QuLineEdit::QuLineEdit (QWidget * parent)
Classical, single parent-widget constructor. QuApplication properly initialized with cumbia engine objects is compulsory.
Parameters
parent widget
Important note: cumbia engine references are obtained from the QuApplication instance.
For best performance, static cast of QCoreApplication::instance() to QuApplication is used.
Since
cumbia 2.1
References QuApplication::cumbiaPool(), and QuApplication::fpool().
~QuLineEdit()
QuLineEdit::~QuLineEdit () virtual
Member Function Documentation
ctxSwap
bool QuLineEdit::ctxSwap (CumbiaPool * cu_p, const CuControlsFactoryPool & fpool) virtual slot
References CuEngineSwap::ok(), and CuEngineSwap::replace().
getContext()
CuContext * QuLineEdit::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
onUpdate()
void QuLineEdit::onUpdate (const CuData & data) virtual
References QuLogImpl::showPopupOnMessage().
setTarget
void QuLineEdit::setTarget (const QString & targets) slot
Set the name of the target that will be executed.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References CuControlsWriterA::setTarget().
target()
QString QuLineEdit::target () const
returns the target name.
Returns
the target name, or an empty string if setTarget hasn't been called yet.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References CuControlsWriterA::target().
Property Documentation
target
QString QuLineEdit::target read write
The documentation for this class was generated from the following files:
qulineedit.h
qulineedit.cpp