cumbia-qtcontrols: QuPlotContextMenuComponent Class Reference
QuPlotContextMenuComponent Class Reference
A QuPlotComponent managing the context menu for a plot.
#include <quplotcontextmenucomponent.h>
Public Member Functions
QuPlotContextMenuComponent ()
QString name () const
void attachToPlot (QuPlotBase *plot)
in this method you would call QwtPlot::attach for the QwtPlotItem items in the component
void connectToPlot (QuPlotBase *plot)
in this method you would create Qt signal/slot connections
QMenu * getMenu (QuPlotBase *plot, QuWidgetContextMenuStrategyI *ctxMenuStrategy) const
void execute (QuPlotBase *plot, QuWidgetContextMenuStrategyI *ctxMenuStrategy, const QPoint &pos)
void print (QuPlotBase *p)
void snapshot (QuPlotBase *p)
void copyImage (QuPlotBase *p)
void saveData (QuPlotBase *p)
void configurePlot (QuPlotBase *p)
Public Member Functions inherited from QuPlotComponent
virtual ~QuPlotComponent ()
Detailed Description
A QuPlotComponent managing the context menu for a plot.
This class, used by cumbia-qtcontrols plots, provides a context menu with default methods to:
print the plot
copy the plot as image
do a snapshot of the plot
save the data shown in the graph at that moment
configure the graph parameters (upper, lower bounds, curve colors, and so on)
The plot must have a QuWidgetContextMenuStrategyI installed. In this case, the execute method shows the menu populated according to the menu strategy under the mouse pointer.
Constructor & Destructor Documentation
QuPlotContextMenuComponent()
QuPlotContextMenuComponent::QuPlotContextMenuComponent ()
Member Function Documentation
attachToPlot()
void QuPlotContextMenuComponent::attachToPlot (QuPlotBase * plot) virtual
in this method you would call QwtPlot::attach for the QwtPlotItem items in the component
Example
See QuPlotMarkerComponent::attachToPlot
Implements QuPlotComponent.
Referenced by QuPlotBase::init().
configurePlot()
void QuPlotContextMenuComponent::configurePlot (QuPlotBase * p)
References QuPlotBase::createConfigureDialog().
connectToPlot()
void QuPlotContextMenuComponent::connectToPlot (QuPlotBase * plot) virtual
in this method you would create Qt signal/slot connections
Example
See QuPlotMarkerComponent::connectToPlot and QuPlotZoomComponent::connectToPlot
Implements QuPlotComponent.
Referenced by QuPlotBase::init().
copyImage()
void QuPlotContextMenuComponent::copyImage (QuPlotBase * p)
References QuPlotBase::setTitleOnCanvasEnabled(), and QuPlotBase::titleOnCanvasEnabled.
execute()
void QuPlotContextMenuComponent::execute (QuPlotBase * plot, QuWidgetContextMenuStrategyI * ctxMenuStrategy, const QPoint & pos)
References getMenu().
getMenu()
QMenu * QuPlotContextMenuComponent::getMenu (QuPlotBase * plot, QuWidgetContextMenuStrategyI * ctxMenuStrategy) const
References QuWidgetContextMenuStrategyI::createMenu().
Referenced by execute().
name()
QString QuPlotContextMenuComponent::name () const virtual
Implements QuPlotComponent.
Referenced by QuPlotBase::init().
print()
void QuPlotContextMenuComponent::print (QuPlotBase * p)
saveData()
void QuPlotContextMenuComponent::saveData (QuPlotBase * p)
References QuPlotBase::curves().
snapshot()
void QuPlotContextMenuComponent::snapshot (QuPlotBase * p)
References QuPlotBase::setTitleOnCanvasEnabled(), and QuPlotBase::titleOnCanvasEnabled.
The documentation for this class was generated from the following files:
quplotcontextmenucomponent.h
quplotcontextmenucomponent.cpp