cumbia-qtcontrols: EInputOutputWidget Class Reference
EInputOutputWidget Class Reference
base class to display values through an output widget and receive input values by means of an input widget.
#include <einputoutputwidget.h>
Public Slots
void setInputValue (double val)
Tries to write the "value" property on the input widget.
void setInputValue (int val)
void setInputText (const QString &text)
Tries to write the "text" property on the input widget.
void setOutputValue (int val)
sets the "value" property on the output widget.
void setOutputValue (double val)
sets the "value" property on the output widget.
void setOutputText (const QString &text)
Tries to write the "text" property on the output widget.
Signals
void editButtonToggled (bool toggled)
void applyClicked ()
void applyClicked (double val)
void applyClicked (const QString &text)
void editButtonClicked ()
Public Member Functions
EInputOutputWidget (QWidget *outputw, QWidget *parent)
A container to organize an output (display) widget and an input (writer) widget.
EInputOutputWidget (QWidget *parent)
single parameter constructor.
void setInputWidget (QWidget *inputw)
sets a QWidget as input widget
void setOutputWidget (QWidget *outputw)
sets the output widget that's used to display a value
QSize minimumSizeHint () const
QSize sizeHint () const
QWidget * outputWidget () const
returns the output widget
QWidget * inputWidget () const
returns the input widget
QFrame * getContainer () const
Returns the QFrame containing the writer.
virtual QPushButton * getApplyButton ()
Provide an apply push button.
Detailed Description
base class to display values through an output widget and receive input values by means of an input widget.
Relevant implementation: QuInputOutput
Constructor & Destructor Documentation
EInputOutputWidget() [1/2]
EInputOutputWidget::EInputOutputWidget (QWidget * outputw, QWidget * parent)
A container to organize an output (display) widget and an input (writer) widget.
EInputOutputWidget is initialised with an output widget and a parent. The output widget is used to display data (read value).
setInputWidget must be called with an input widget as parameter. The input widget is normally hidden until the "<em>...</em>" button on the right of the output widget is clicked. The input widget is shown through a popup below the output widget. Clicking anywhere out of the input widget makes it disappear, as in a combo box.
Apply the input value
When the "<em>OK</em>" button is clicked on the input (popup) container, one to three signals can be emitted:
an empty applyClicked signal is always emitted before attempting to read the value and text properties.
If the input widget has the "value" property, the applyClicked(double) signal is emitted with the value converted to double
If the input widget has the "text" property, the applyClicked(QString) signal is emitted with the text
If the input widget has the "value" property, the applyClicked(QString) signal is emitted with the value converted to string with the QString::number() method.
Note:
If no "value" nor "text" properties are defined for the input widget, then only the empty applyClicked() signal is emitted, at the beginning of the method.
Note:
The minimumSizeHint.width of the input widget is used to provide the minimumSizeHint.width of the EInputOutputWidget.
Object names and relationships
Input widget object name is set to objectName() + "_inputWidget"
Output widget object name is set to objectName() + "_outputWidget"
To find the apply button, use getContainer()->findChild<QPushButton *>() or the getApplyButton method
To find the edit button, use findChild<QPushButton *>("pbEdit")
References setOutputWidget().
EInputOutputWidget() [2/2]
EInputOutputWidget::EInputOutputWidget (QWidget * parent)
single parameter constructor.
setOutputWidget must be called manually later.
See also
EInputOutputWidget::EInputOutputWidget(QWidget* outputw, QWidget *parent)
Member Function Documentation
applyClicked [1/3]
void EInputOutputWidget::applyClicked () signal
applyClicked [2/3]
void EInputOutputWidget::applyClicked (double val) signal
applyClicked [3/3]
void EInputOutputWidget::applyClicked (const QString & text) signal
editButtonClicked
void EInputOutputWidget::editButtonClicked () signal
editButtonToggled
void EInputOutputWidget::editButtonToggled (bool toggled) signal
getApplyButton()
QPushButton * EInputOutputWidget::getApplyButton () virtual
Provide an apply push button.
The base implementation makes a QPushButton. The apply button, when clicked, emits the applyClicked signals.
Note
The apply button must be created only once.
Reimplemented in QuInputOutput.
Referenced by setInputWidget().
getContainer()
QFrame * EInputOutputWidget::getContainer () const
Returns the QFrame containing the writer.
Returns
QFrame containing the writer
Referenced by QuInputOutput::QuInputOutput().
inputWidget()
QWidget * EInputOutputWidget::inputWidget () const
returns the input widget
Returns
the input widget
Referenced by QuInputOutput::setObjectName(), and QuInputOutput::setWriterType().
minimumSizeHint()
QSize EInputOutputWidget::minimumSizeHint () const
calculates the minimum size hint for the widget
Returns
the minimum size hint for the widget
See also
sizeHint
outputWidget()
QWidget * EInputOutputWidget::outputWidget () const
returns the output widget
Returns
the output widget as QWidget
Referenced by QuInputOutput::getOutputContext(), QuInputOutput::setObjectName(), QuInputOutput::setSource(), and QuInputOutput::unsetSource().
setInputText
void EInputOutputWidget::setInputText (const QString & text) slot
Tries to write the "text" property on the input widget.
Parameters
s the value to display on the input widget
Note
The input widget must declare the text Q_PROPERTY
setInputValue [1/2]
void EInputOutputWidget::setInputValue (double val) slot
Tries to write the "value" property on the input widget.
Parameters
s the value to display on the input widget
Note
The input widget must declare the value Q_PROPERTY
setInputValue [2/2]
void EInputOutputWidget::setInputValue (int val) slot
setInputWidget()
void EInputOutputWidget::setInputWidget (QWidget * inputw)
sets a QWidget as input widget
Parameters
inputw a QWidget that will be used as input widget
References getApplyButton().
Referenced by QuInputOutput::setWriterType().
setOutputText
void EInputOutputWidget::setOutputText (const QString & text) slot
Tries to write the "text" property on the output widget.
Parameters
s the value to display on the output widget
Note
The output widget must declare the text Q_PROPERTY
setOutputValue [1/2]
void EInputOutputWidget::setOutputValue (int val) slot
sets the "value" property on the output widget.
Parameters
s the value to display on the output widget
Note
The output widget must declare the value Q_PROPERTY
setOutputValue [2/2]
void EInputOutputWidget::setOutputValue (double val) slot
sets the "value" property on the output widget.
Parameters
s the value to display on the output widget
Note
The output widget must declare the value Q_PROPERTY
setOutputWidget()
void EInputOutputWidget::setOutputWidget (QWidget * outputw)
sets the output widget that's used to display a value
Parameters
outputw an output widget, with either the value or text
Referenced by EInputOutputWidget(), and QuInputOutput::QuInputOutput().
sizeHint()
QSize EInputOutputWidget::sizeHint () const
calculates the size hint for the widget
Returns
the size hint for the widget, calculated according to the input widget and apply button size hint widths and the output widget's height
See also
minimumSizeHint
The documentation for this class was generated from the following files:
einputoutputwidget.h
einputoutputwidget.cpp