cumbia-qtcontrols: QuLogImpl Class Reference
QuLogImpl Class Reference
Logging
cumbia-qtcontrols CuLogImplI log implementation
#include <qulogimpl.h>
Public Types
enum MsgType { Info = 0, Warn, Error, User = 100 }
Public Member Functions
QuLogImpl ()
void showPopupOnMessage (int log_class_type, bool show)
Enable/disable popup for the given log_class_type.
virtual ~QuLogImpl ()
void onDialogDeleted ()
void write (const std::string &origin, const std::string &write, CuLog::Level l, CuLog::Class c)
void write (const std::string &origin, CuLog::Level l, CuLog::Class c, const char *fmt,...)
std::string getName () const
Detailed Description
cumbia-qtcontrols CuLogImplI log implementation
Member Enumeration Documentation
MsgType
enum QuLogImpl::MsgType
Enumerator
Info
Warn
Error
User
Constructor & Destructor Documentation
QuLogImpl()
QuLogImpl::QuLogImpl ()
~QuLogImpl()
QuLogImpl::~QuLogImpl () virtual
Member Function Documentation
getName()
std::string QuLogImpl::getName () const
onDialogDeleted()
void QuLogImpl::onDialogDeleted ()
showPopupOnMessage()
void QuLogImpl::showPopupOnMessage (int log_class_type, bool show)
Enable/disable popup for the given log_class_type.
Parameters
log_class_type a value from CuLogClass::Type enum or its extension
show show a popup when a new error occurse for the given CuLogClass::Type type
write() [1/2]
void QuLogImpl::write (const std::string & origin, const std::string & write, CuLog::Level l, CuLog::Class c)
Referenced by QuDoubleSpinBox::onUpdate(), QuSpinBox::onUpdate(), QuLineEdit::onUpdate(), QuButton::onUpdate(), QuApplyNumeric::onUpdate(), QuCheckBox::onUpdate(), and QmlWriterBackend::onUpdate().
write() [2/2]
void QuLogImpl::write (const std::string & origin, CuLog::Level l, CuLog::Class c, const char * fmt, ...)
The documentation for this class was generated from the following files:
qulogimpl.h
qulogimpl.cpp