cumbia-qtcontrols: ELinearGauge Class Reference
ELinearGauge Class Reference
a thermometer like widget
#include <egauge.h>
Public Types
enum FillMode {
ALL, FROM_MIN, FROM_ZERO, FROM_REF,
ALL, FROM_MIN, FROM_ZERO, FROM_REF
}
enum FillMode {
ALL, FROM_MIN, FROM_ZERO, FROM_REF,
ALL, FROM_MIN, FROM_ZERO, FROM_REF
}
Public Types inherited from EAbstractGauge
enum ColorMode {
GRADIENT, COLORBAR, SINGLECOLOR, GRADIENT,
COLORBAR, SINGLECOLOR
}
enum ColorMode {
GRADIENT, COLORBAR, SINGLECOLOR, GRADIENT,
COLORBAR, SINGLECOLOR
}
Public Member Functions
ELinearGauge (QWidget *=NULL, Qt::Orientation=Qt::Vertical)
~ELinearGauge ()
void setOrientation (Qt::Orientation o)
Qt::Orientation orientation ()
void setFillMode (FillMode m)
FillMode fillMode ()
ELinearGauge (QWidget *=NULL, Qt::Orientation=Qt::Vertical)
~ELinearGauge ()
void setOrientation (Qt::Orientation o)
Qt::Orientation orientation ()
void setFillMode (FillMode m)
FillMode fillMode ()
Public Member Functions inherited from EAbstractGauge
EAbstractGauge (QWidget *=NULL)
~EAbstractGauge ()
bool logarithmicScale ()
void setLogarithmicScale (bool l)
void setLowWarning (double w)
double lowWarning ()
void setHighWarning (double w)
double highWarning ()
void setLowError (double e)
double lowError ()
void setHighError (double e)
double highError ()
void setMinValue (double v)
double minValue ()
void setMaxValue (double v)
double maxValue ()
double value ()
void setReference (double r)
double reference ()
void setScaleEnabled (bool b)
bool isScaleEnabled ()
void setReferenceEnabled (bool b)
bool isReferenceEnabled ()
void setColorMode (ColorMode m)
ColorMode colorMode ()
DEPRECATED (void setNormalColor(QColor c))
QColor normalColor ()
DEPRECATED (void setWarningColor(QColor c))
QColor warningColor ()
DEPRECATED (void setErrorColor(QColor c))
QColor errorColor ()
void setExternalScale (bool b)
bool externalScale ()
void setNumMajorTicks (int t)
int numMajorTicks ()
void setNumMinorTicks (int t)
int numMinorTicks ()
void setValueFormat (QString s)
QString valueFormat ()
EAbstractGauge (QWidget *=NULL)
~EAbstractGauge ()
bool logarithmicScale ()
void setLogarithmicScale (bool l)
void setLowWarning (double w)
double lowWarning ()
void setHighWarning (double w)
double highWarning ()
void setLowError (double e)
double lowError ()
void setHighError (double e)
double highError ()
void setMinValue (double v)
double minValue ()
void setMaxValue (double v)
double maxValue ()
double value ()
void setReference (double r)
double reference ()
void setScaleEnabled (bool b)
bool isScaleEnabled ()
void setReferenceEnabled (bool b)
bool isReferenceEnabled ()
void setColorMode (ColorMode m)
ColorMode colorMode ()
DEPRECATED (void setNormalColor(QColor c))
QColor normalColor ()
DEPRECATED (void setWarningColor(QColor c))
QColor warningColor ()
DEPRECATED (void setErrorColor(QColor c))
QColor errorColor ()
void setExternalScale (bool b)
bool externalScale ()
void setNumMajorTicks (int t)
int numMajorTicks ()
void setNumMinorTicks (int t)
int numMinorTicks ()
void setValueFormat (QString s)
QString valueFormat ()
Protected Member Functions
void paintEvent (QPaintEvent *)
void drawColorBar (QPainter *)
void drawScale (QPainter *)
void drawMarker (QPainter *, bool)
void drawLabels (QPainter *)
virtual void configure ()
void paintEvent (QPaintEvent *)
void drawColorBar (QPainter *)
void drawScale (QPainter *)
void drawMarker (QPainter *, bool)
void drawLabels (QPainter *)
virtual void configure ()
Properties
Qt::Orientation orientation
FillMode fillMode
Properties inherited from EAbstractGauge
double minValue
double lowError
double lowWarning
double highWarning
double highError
double maxValue
double value
double reference
bool scaleEnabled
bool referenceEnabled
ColorMode colorMode
bool externalScale
bool logarithmicScale
QString valueFormat
int numMajorTicks
int numMinorTicks
Additional Inherited Members
Public Slots inherited from EAbstractGauge
void setValue (double)
void setValue (int)
void setValue (double)
void setValue (int)
Protected Attributes inherited from EAbstractGauge
double m_minValue
double m_maxValue
double m_lowWarning
double m_highWarning
double m_lowError
double m_highError
double m_value
double m_reference
double d_naturalMinV
double d_naturalMaxV
double d_naturalLowWarn
double d_naturalHighWarn
double d_naturalLowErr
double d_naturalHighErr
double d_naturalValue
double d_naturalReference
ColorMode m_colorMode
bool m_referenceEnabled
bool m_scaleEnabled
int m_numMajorTicks
int m_numMinorTicks
QStringList labels
int longestLabelIndex
bool m_externalScale
QVector< qreal > v_p
QVector< QColor > v_c
QColor m_normalColor
QColor m_warningColor
QColor m_errorColor
QString m_valueFormat
Detailed Description
a thermometer like widget
Member Enumeration Documentation
FillMode [1/2]
enum ELinearGauge::FillMode
How the value is displayed on the bar
Enumerator
ALL
FROM_MIN
fill the whole bar, moving marker
FROM_ZERO
bar filled from min value to value
FROM_REF
bar filled from zero to value bar filled from reference to value
ALL
FROM_MIN
fill the whole bar, moving marker
FROM_ZERO
bar filled from min value to value
FROM_REF
bar filled from zero to value bar filled from reference to value
FillMode [2/2]
enum ELinearGauge::FillMode
How the value is displayed on the bar
Enumerator
ALL
FROM_MIN
fill the whole bar, moving marker
FROM_ZERO
bar filled from min value to value
FROM_REF
bar filled from zero to value bar filled from reference to value
ALL
FROM_MIN
fill the whole bar, moving marker
FROM_ZERO
bar filled from min value to value
FROM_REF
bar filled from zero to value bar filled from reference to value
Constructor & Destructor Documentation
ELinearGauge() [1/2]
ELinearGauge::ELinearGauge (QWidget * parent = NULL, Qt::Orientation o = Qt::Vertical)
References LINEAR_MAJOR_TICKS, NUM_MINOR_TICKS, EAbstractGauge::setNumMajorTicks(), and EAbstractGauge::setNumMinorTicks().
~ELinearGauge() [1/2]
ELinearGauge::~ELinearGauge () inline
ELinearGauge() [2/2]
ELinearGauge::ELinearGauge (QWidget * = NULL, Qt::Orientation = Qt::Vertical)
~ELinearGauge() [2/2]
ELinearGauge::~ELinearGauge () inline
Member Function Documentation
configure() [1/2]
virtual void ELinearGauge::configure () protected virtual
Reimplemented from EAbstractGauge.
configure() [2/2]
void ELinearGauge::configure () protected virtual
Reimplemented from EAbstractGauge.
References EAbstractGauge::configure(), and EAbstractGauge::m_scaleEnabled.
Referenced by setFillMode(), and setOrientation().
drawColorBar() [1/2]
void ELinearGauge::drawColorBar (QPainter *) protected
drawColorBar() [2/2]
void ELinearGauge::drawColorBar (QPainter * p) protected
References ALL, Elettra::black, EAbstractGauge::COLORBAR, FROM_MIN, FROM_REF, FROM_ZERO, EAbstractGauge::GRADIENT, EAbstractGauge::m_colorMode, EAbstractGauge::m_maxValue, EAbstractGauge::m_minValue, EAbstractGauge::m_reference, EAbstractGauge::m_value, EAbstractGauge::SINGLECOLOR, EAbstractGauge::v_c, and EAbstractGauge::v_p.
Referenced by paintEvent().
drawLabels() [1/2]
void ELinearGauge::drawLabels (QPainter *) protected
drawLabels() [2/2]
void ELinearGauge::drawLabels (QPainter * p) protected
References EAbstractGauge::labels, EAbstractGauge::longestLabelIndex, and EAbstractGauge::m_numMajorTicks.
Referenced by paintEvent().
drawMarker() [1/2]
void ELinearGauge::drawMarker (QPainter * , bool) protected
drawMarker() [2/2]
void ELinearGauge::drawMarker (QPainter * p, bool drawValue) protected
References Elettra::black, Elettra::darkBlue, EColor(), EAbstractGauge::m_maxValue, EAbstractGauge::m_minValue, EAbstractGauge::m_reference, EAbstractGauge::m_value, and Elettra::red.
Referenced by drawScale(), and paintEvent().
drawScale() [1/2]
void ELinearGauge::drawScale (QPainter *) protected
drawScale() [2/2]
void ELinearGauge::drawScale (QPainter * p) protected
References drawMarker(), EAbstractGauge::m_numMajorTicks, EAbstractGauge::m_numMinorTicks, and EAbstractGauge::m_referenceEnabled.
Referenced by paintEvent().
fillMode() [1/2]
FillMode ELinearGauge::fillMode () inline
fillMode() [2/2]
FillMode ELinearGauge::fillMode () inline
orientation() [1/2]
Qt::Orientation ELinearGauge::orientation () inline
orientation() [2/2]
Qt::Orientation ELinearGauge::orientation () inline
paintEvent() [1/2]
void ELinearGauge::paintEvent (QPaintEvent *) protected
paintEvent() [2/2]
void ELinearGauge::paintEvent (QPaintEvent *) protected
References ALL, drawColorBar(), drawLabels(), drawMarker(), drawScale(), EAbstractGauge::labels, EAbstractGauge::longestLabelIndex, and EAbstractGauge::m_scaleEnabled.
setFillMode() [1/2]
void ELinearGauge::setFillMode (FillMode m) inline
References configure().
setFillMode() [2/2]
void ELinearGauge::setFillMode (FillMode m) inline
References configure().
setOrientation() [1/2]
void ELinearGauge::setOrientation (Qt::Orientation o) inline
References configure().
setOrientation() [2/2]
void ELinearGauge::setOrientation (Qt::Orientation o) inline
References configure().
Property Documentation
fillMode
FillMode ELinearGauge::fillMode read write
orientation
Qt::Orientation ELinearGauge::orientation read write
The documentation for this class was generated from the following files:
egauge.h
egauge_copy.h
egauge.cpp