cumbia-qtcontrols: EFlag Class Reference
EFlag Class Reference
A widget composed by a matrix of ELabel.
#include <eflag.h>
Public Member Functions
EFlag (QWidget *parent)
void setValue (QVariant v, bool ref=true)
QList< QVariant > readValue () const
void setDisplayMask (QString var)
const QString getDisplayMask ()
void setDisplayMask (QList< unsigned int > m)
void setDisplayMask (QList< QList< unsigned int > > qlql)
void initDisplayMask (void)
QList< QList< unsigned int > > displayMask () const
void setNumRows (int rows)
int readNumRows () const
void setNumColumns (int columns)
int readNumColumns () const
void setBooleanDisplay (int i, QString falseString, QString trueString, QColor falseColor, QColor trueColor)
void setEnumDisplay (int cell, unsigned int value, QString corresponding_str, QColor corresponding_color)
void setTrueStrings (QString s)
QString trueStrings ()
void setFalseStrings (QString s)
QString falseStrings ()
void setTrueColors (QString c)
QString trueColors ()
void setFalseColors (QString c)
QString falseColors ()
void setTrueColorList (const QList< QColor > &cl)
set the list of true colours specifying a QList of QColor elements
QList< QColor > trueColorList () const
returns the list of true colours, made up of QColor elements.
void setFalseColorList (const QList< QColor > &cl)
set the list of false colours specifying a QList of QColor elements
QList< QColor > falseColorList () const
returns the list of false colours, made up of QColor elements.
void setMouseTracking (bool en)
Public Attributes
QList< ELabel * > cells
Protected Member Functions
void arrangeCells ()
void configureCells ()
Properties
int numRows
int numColumns
QString trueColors
QString falseColors
QString trueStrings
QString falseStrings
QString displayMask
Detailed Description
A widget composed by a matrix of ELabel.
this object displays a matrix of boolean values. you can configure the color and the text of each cell. The input value is a vector of boolean values or an integer which is interpreted as a bitmask. the function setDisplayMask allows you to decide which bits must be displayed and in which cell
Constructor & Destructor Documentation
EFlag()
EFlag::EFlag (QWidget * parent)
References arrangeCells(), numColumns, and numRows.
Member Function Documentation
arrangeCells()
void EFlag::arrangeCells () protected
References cells, configureCells(), EColor(), Elettra::green, numColumns, numRows, and Elettra::red.
Referenced by EFlag(), setNumColumns(), and setNumRows().
configureCells()
void EFlag::configureCells () protected
References cells, and setBooleanDisplay().
Referenced by arrangeCells(), setFalseColorList(), setFalseColors(), setFalseStrings(), setTrueColorList(), setTrueColors(), and setTrueStrings().
displayMask()
QList< QList<unsigned int> > EFlag::displayMask () const inline
Returns the nested lists which made up the display mask
Referenced by QuTable::configure().
falseColorList()
QList< QColor > EFlag::falseColorList () const
returns the list of false colours, made up of QColor elements.
See also
setFalseColorList
setTrueColorList
falseColors()
QString EFlag::falseColors ()
Referenced by QuTable::configure().
falseStrings()
QString EFlag::falseStrings ()
getDisplayMask()
const QString EFlag::getDisplayMask () inline
Returns the generic mask expressed as QList<QVariant>
initDisplayMask()
void EFlag::initDisplayMask (void)
References numColumns, and numRows.
readNumColumns()
int EFlag::readNumColumns () const inline
returns the current number of columns of the widget
Returns
number of columns
References numColumns.
readNumRows()
int EFlag::readNumRows () const inline
returns the current number of rows of the widget
Returns
number of rows
References numRows.
readValue()
QList<QVariant> EFlag::readValue () const inline
sets the value of the widget
Parameters
v the value to be displayed
ref whether to refresh the widget or notreturns the value of the widget
Returns
the displayed value
setBooleanDisplay()
void EFlag::setBooleanDisplay (int i, QString falseString, QString trueString, QColor falseColor, QColor trueColor)
configure colors and labels to be displayed in each cell
Parameters
i cell to be configured
falseString string to be displayed when te value is false
trueString string to be displayed when te value is true
falseColor color to be displayed when te value is false
trueColor color to be displayed when te value is true
References cells, EColor(), Elettra::green, and Elettra::red.
Referenced by configureCells().
setDisplayMask() [1/3]
void EFlag::setDisplayMask (QString var)
This one is used on behalf of the designer. A string is splitted and then each element is put in an unsigned int vector finally passed to setDisplayMask(QList<unsigned int>). The format of the string must be a sequence of unsigned int separated by a comma.
Referenced by QuTable::configure().
setDisplayMask() [2/3]
void EFlag::setDisplayMask (QList< unsigned int > m)
configures which bits have to be displayed and where In this version, which accepts a list of unsigned, a subsequent call to setValue() will mask its value with the bitmask specified here. For instance, if we write a piece of code like this:
    QList<unsigned int >  uintlist;
    uintlist << 2; uintlist << 0; uintlist << 1;
 f->setDisplayMask(uintlist);
a call to setValue(5) will produce:
true, true, false
since the value 5, which is 101 binary coded, is first masked with 100 (the element 2 in the list sets the 3rd bit to 1 leaving the others to 0), then 001 (the element 0 in the list sets to 1 the first bit), then 010 (the last element in the list, 1).
Parameters
m a vector, which i-th value contains the position of the bit to be displayed in the i-th cell
setDisplayMask() [3/3]
void EFlag::setDisplayMask (QList< QList< unsigned int > > qlql)
configures which bits are to be displayed
Parameters
qlql a list of a list containing the desired bit mask. For instance, qlql could be a list containing the values <3,4>, <15,16>, <8,11,12> if we are interested in reading the bits 3 and 4 and the bits 15 and 16 and the bit 8 together with 11 and 12. The bits suggested in each list will mask the value (e.g. ‘val’) passed as argument to setValue(val) and extract the value represented by them inside ‘val’.
For instance, a mask of <0, 1> and <0, 2> applied to the value 5 (binary: 101) will produce:
<0, 1> 5 becomes 1 (101 is ANDed with 011) <0, 2>
setEnumDisplay()
void EFlag::setEnumDisplay (int cell, unsigned int value, QString corresponding_str, QColor corresponding_color)
The extended version associates a color and a string to a value.
Parameters
cell the cell to be configured
value the value to which one associates a color and a string on the cell ‘cell’
corresponding_string the string to be shown when the value is ‘value’
corresponding_color the color that characterizes the value ‘value’
References cells.
setFalseColorList()
void EFlag::setFalseColorList (const QList< QColor > & cl)
set the list of false colours specifying a QList of QColor elements
Used to auto configure the TTable. You may use it with the designer too.
References configureCells().
Referenced by QuTable::configure().
setFalseColors()
void EFlag::setFalseColors (QString c)
References configureCells().
setFalseStrings()
void EFlag::setFalseStrings (QString s)
References configureCells().
Referenced by QuTable::configure().
setMouseTracking()
void EFlag::setMouseTracking (bool en)
References cells.
setNumColumns()
void EFlag::setNumColumns (int columns) inline
configures the number of columns of the widget
Parameters
columns the number of columns
References arrangeCells(), and numColumns.
Referenced by QuTable::configure().
setNumRows()
void EFlag::setNumRows (int rows) inline
configures the number of rows of the widget
Parameters
rows the number of rows
References arrangeCells(), and numRows.
Referenced by QuTable::configure().
setTrueColorList()
void EFlag::setTrueColorList (const QList< QColor > & cl)
set the list of true colours specifying a QList of QColor elements
Used to auto configure the TTable. You may use it with the designer too.
References configureCells().
Referenced by QuTable::configure().
setTrueColors()
void EFlag::setTrueColors (QString c)
References configureCells().
setTrueStrings()
void EFlag::setTrueStrings (QString s)
References configureCells().
Referenced by QuTable::configure().
setValue()
void EFlag::setValue (QVariant v, bool ref = true)
sets the value of the widget
Parameters
v the value to be displayed
ref whether to refresh the widget or not The parameter ‘v’ can be a list of boolean values or an unsigned int to which the display mask will be applied in order to extract the wanted fields.
References cells.
Referenced by QuTable::onUpdate().
trueColorList()
QList< QColor > EFlag::trueColorList () const
returns the list of true colours, made up of QColor elements.
See also
setTrueColorList
setFalseColorList
trueColors()
QString EFlag::trueColors ()
Referenced by QuTable::configure().
trueStrings()
QString EFlag::trueStrings ()
Member Data Documentation
cells
QList<ELabel*> EFlag::cells
Referenced by arrangeCells(), configureCells(), QuTable::onUpdate(), setBooleanDisplay(), setEnumDisplay(), setMouseTracking(), and setValue().
Property Documentation
displayMask
QString EFlag::displayMask read write
falseColors
QString EFlag::falseColors read write
falseStrings
QString EFlag::falseStrings read write
numColumns
int EFlag::numColumns read write
Referenced by arrangeCells(), QuTable::configure(), EFlag(), initDisplayMask(), readNumColumns(), and setNumColumns().
numRows
int EFlag::numRows read write
Referenced by arrangeCells(), QuTable::configure(), EFlag(), initDisplayMask(), readNumRows(), and setNumRows().
trueColors
QString EFlag::trueColors read write
trueStrings
QString EFlag::trueStrings read write
The documentation for this class was generated from the following files:
eflag.h
eflag.cpp