cumbia-qtcontrols: CuEngineSwap Class Reference
CuEngineSwap Class Reference
Helper class to switch context on a controls reader (writer)
#include <cuengine_swap.h>
Public Types
enum Engines {
NoEngine = 0 , Tango , Epics , Http ,
Random , Websocket , MaxEngines
}
Public Member Functions
CuEngineSwap ()
~CuEngineSwap ()
CuContext * replace (CuDataListener *l, CuContext *ctx, CumbiaPool *p, const CuControlsFactoryPool &fpoo)
Perform the actual engine switch on either the reader or writer behind the given context. The old context will be deleted. The returned context shall be used by the caller to update its reference to its own context.
bool check_objs_have_ctx_swap (const QObject *root, QString *oclass, QString *onam) const
bool check_root_has_engine_accessor (const QObject *root) const
int ctx_swap (const QObject *root, CumbiaPool *cu_pool, const CuControlsFactoryPool &m_ctrl_factory_pool)
swap engine on all children of root having either a source or target property and implementing the ctxSwap qt slot
bool app_engine_swap (const QObject *root, CumbiaPool *cu_pool, const CuControlsFactoryPool &fp)
int engine_type (const CuContext *ctx) const
bool same_engine (CumbiaPool *cu_pool, int engine) const
bool log_move (const std::vector< Cumbia * > &vc, CumbiaPool *new_p) const
std::vector< Cumbia * > cumbia_clear (CumbiaPool *cu_pool, CuControlsFactoryPool &fp)
int cumbias_delete (const std::vector< Cumbia * > &vc)
bool ok () const
bool error () const
const QString & msg () const
Detailed Description
Helper class to switch context on a controls reader (writer)
Since
1.5.2
Member Enumeration Documentation
Engines
enum CuEngineSwap::Engines
Enumerator
NoEngine
Epics
Http
Random
Websocket
MaxEngines
Constructor & Destructor Documentation
CuEngineSwap()
CuEngineSwap::CuEngineSwap ()
~CuEngineSwap()
CuEngineSwap::~CuEngineSwap ()
Member Function Documentation
app_engine_swap()
bool CuEngineSwap::app_engine_swap (const QObject * root, CumbiaPool * cu_pool, const CuControlsFactoryPool & fp)
References CuEngineAccessor::engine_swap().
check_objs_have_ctx_swap()
bool CuEngineSwap::check_objs_have_ctx_swap (const QObject * root, QString * oclass, QString * onam) const
References ok().
check_root_has_engine_accessor()
bool CuEngineSwap::check_root_has_engine_accessor (const QObject * root) const
ctx_swap()
int CuEngineSwap::ctx_swap (const QObject * root, CumbiaPool * cu_pool, const CuControlsFactoryPool & m_ctrl_factory_pool)
swap engine on all children of root having either a source or target property and implementing the ctxSwap qt slot
Parameters
root the parent object used to find children having either a source or target property
cu_pool a pointer to the CumbiaPool with the target engine
m_ctrl_factory_pool a const reference to a factory pool with the target engine configured
Returns
the number of objects whose engine has been successfully replaced
You may want to check for error and msg for diagnostic purposes
References ok().
cumbia_clear()
std::vector< Cumbia * > CuEngineSwap::cumbia_clear (CumbiaPool * cu_pool, CuControlsFactoryPool & fp)
cumbias_delete()
int CuEngineSwap::cumbias_delete (const std::vector< Cumbia * > & vc)
engine_type()
int CuEngineSwap::engine_type (const CuContext * ctx) const
References CuContext::getReader(), CuContext::readers(), and CuContext::writers().
error()
bool CuEngineSwap::error () const
log_move()
bool CuEngineSwap::log_move (const std::vector< Cumbia * > & vc, CumbiaPool * new_p) const
msg()
const QString & CuEngineSwap::msg () const
ok()
bool CuEngineSwap::ok () const
Referenced by check_objs_have_ctx_swap(), ctx_swap(), QuApplyNumeric::ctxSwap(), QuButton::ctxSwap(), QuComboBox::ctxSwap(), QuDoubleSpinBox::ctxSwap(), QuLabel::ctxSwap(), QuLed::ctxSwap(), QuLineEdit::ctxSwap(), QuSpinBox::ctxSwap(), QuTable::ctxSwap(), QuWatcher::ctxSwap(), and QuWriter::ctxSwap().
replace()
CuContext * CuEngineSwap::replace (CuDataListener * l, CuContext * ctx, CumbiaPool * p, const CuControlsFactoryPool & fpoo)
Perform the actual engine switch on either the reader or writer behind the given context. The old context will be deleted. The returned context shall be used by the caller to update its reference to its own context.
Parameters
l the data listener to which the new context with the new engine will be linked
ctx the current context of the reader (or writer) to be replaced
p a pointer to the CumbiaPool holding the new engine configuration
fpoo a const reference to the pool holding the new engine configuration
Returns
the new context holding a new reader (writer) belonging to the new engine
This method is mainly used by the library components (or by custom cumbia components) when a context switch (i.e. engine switch) is required by the application.
Example: QuLabel::ctxSwitch(CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
References CuContext::disposeReader(), CuContext::disposeWriter(), CuContext::getReader(), CuContext::getWriter(), CuContext::replace_reader(), CuContext::replace_writer(), CuControlsReaderA::setSource(), CuControlsWriterA::setTarget(), CuControlsReaderA::source(), and CuControlsWriterA::target().
Referenced by QuApplyNumeric::ctxSwap(), QuButton::ctxSwap(), QuComboBox::ctxSwap(), QuDoubleSpinBox::ctxSwap(), QuLabel::ctxSwap(), QuLed::ctxSwap(), QuLinearGauge::ctxSwap(), QuLineEdit::ctxSwap(), QuSpinBox::ctxSwap(), QuTable::ctxSwap(), QuWatcher::ctxSwap(), and QuWriter::ctxSwap().
same_engine()
bool CuEngineSwap::same_engine (CumbiaPool * cu_pool, int engine) const
The documentation for this class was generated from the following files:
cuengine_swap.h
cuengine_swap.cpp