cumbia-qtcontrols: QuInputOutput Class Reference
QuInputOutput Class Reference
Display widgets | Input widgets
This element is a graphical interface to integrate a reader and a writer into one single object that saves space in the user interface.
#include <quinputoutput.h>
Public Types
enum WriterType {
None, LineEdit, Numeric, SpinBox,
DoubleSpinBox, ComboBox
}
this enum describes the type of available writers
Public Slots
virtual void onNewData (const CuData &d)
void setSource (const QString &s)
Link the reader/writer to the specified source.
void unsetSource ()
unlink the QuInputOutput
Public Slots inherited from EInputOutputWidget
void setInputValue (double val)
Tries to write the "value" property on the input widget.
void setInputValue (int val)
void setInputText (const QString &text)
Tries to write the "text" property on the input widget.
void setOutputValue (int val)
sets the "value" property on the output widget.
void setOutputValue (double val)
sets the "value" property on the output widget.
void setOutputText (const QString &text)
Tries to write the "text" property on the output widget.
Public Member Functions
QuInputOutput (QWidget *_parent, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac, const CuControlsWriterFactoryI &w_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuInputOutput (QWidget *parent, CumbiaPool *cu_poo, const CuControlsFactoryPool &f_poo)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
~QuInputOutput ()
void setWriterType (WriterType t)
sets the writer type to t
WriterType writerType () const
QPushButton * getApplyButton ()
returns the apply button (of type QuButton)
QString source () const
CuContext * getContext () const
Provided to implement CuContextI interface, returns getOutputContext.
CuContext * getOutputContext () const
Returns the context of the output widget.
CuContext * getInputContext () const
Returns the context of the input widget.
void setObjectName (const QString &name)
Set the object name and the name of the input and output widget as well.
Public Member Functions inherited from EInputOutputWidget
EInputOutputWidget (QWidget *outputw, QWidget *parent)
A container to organize an output (display) widget and an input (writer) widget.
EInputOutputWidget (QWidget *parent)
single parameter constructor.
void setInputWidget (QWidget *inputw)
sets a QWidget as input widget
void setOutputWidget (QWidget *outputw)
sets the output widget that's used to display a value
QSize minimumSizeHint () const
QSize sizeHint () const
QWidget * outputWidget () const
returns the output widget
QWidget * inputWidget () const
returns the input widget
QFrame * getContainer () const
Returns the QFrame containing the writer.
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
QString source
Returns the name of the link.
Additional Inherited Members
Signals inherited from EInputOutputWidget
void editButtonToggled (bool toggled)
void applyClicked ()
void applyClicked (double val)
void applyClicked (const QString &text)
void editButtonClicked ()
Detailed Description
This element is a graphical interface to integrate a reader and a writer into one single object that saves space in the user interface.
The source linked to this object is read and displayed on an outputWidget and can be written by an inputWidget. Two contexts are available for this element, an input and an output context. The first is the output widget's context, the second is the input widget's. getOutputContext and getInputContext return a reference to them respectively.
By default a QuLabel is used as output widget. A QuButton is used to apply the value edited in the input widget. It can be retrieved with getApplyButton. The input widget is chosen automatically. setWriterType can be manually used to set it manually.
QuInputOutput is composed by output and input widgets that are already part of the cumbia widget. It does not use a CuContext of its own.
Output widget's newData(const CuData&) signal can be connected to a consistent receiver's slot if this needs to be notified:
connect(qu_io->outputWidget(), SIGNAL(newData(const CuData&)), receiver, SLOT(onNewData(const CuData &)));
Member Enumeration Documentation
WriterType
enum QuInputOutput::WriterType
this enum describes the type of available writers
Enumerator
None
LineEdit
Numeric
SpinBox
DoubleSpinBox
ComboBox
Constructor & Destructor Documentation
QuInputOutput() [1/2]
QuInputOutput::QuInputOutput (QWidget * parent, Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac, const CuControlsWriterFactoryI & w_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References CuControlsReaderFactoryI::clone(), EInputOutputWidget::getContainer(), None, onNewData(), QuLabelBase::setDrawInternalBorder(), CuControlsReaderFactoryI::setOptions(), and EInputOutputWidget::setOutputWidget().
QuInputOutput() [2/2]
QuInputOutput::QuInputOutput (QWidget * parent, CumbiaPool * cu_poo, const CuControlsFactoryPool & f_poo)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References EInputOutputWidget::getContainer(), None, onNewData(), QuLabelBase::setDrawInternalBorder(), and EInputOutputWidget::setOutputWidget().
~QuInputOutput()
QuInputOutput::~QuInputOutput ()
Member Function Documentation
getApplyButton()
QPushButton * QuInputOutput::getApplyButton () virtual
returns the apply button (of type QuButton)
Returns
the QuButton used as apply button
Reimplemented from EInputOutputWidget.
getContext()
CuContext * QuInputOutput::getContext () const virtual
Provided to implement CuContextI interface, returns getOutputContext.
Returns
the output widget's context
See also
getOutputContext
Implements CuContextI.
References getOutputContext().
getInputContext()
CuContext * QuInputOutput::getInputContext () const
Returns the context of the input widget.
Returns
a pointer to the QuContext of the input widget.
getOutputContext()
CuContext * QuInputOutput::getOutputContext () const
Returns the context of the output widget.
Returns
a pointer to the QuContext of the output widget.
Note
The current implementation works only if the reader is a QuLabel.
References QuLabel::getContext(), and EInputOutputWidget::outputWidget().
Referenced by getContext().
onNewData
void QuInputOutput::onNewData (const CuData & d) virtual slot
Referenced by QuInputOutput().
setObjectName()
void QuInputOutput::setObjectName (const QString & name)
Set the object name and the name of the input and output widget as well.
Parameters
name the object name.
If you set the object name, you will be able to find the input and output widgets with the following names:
name + "_inputWidget"
name + "_outputWidget"
References EInputOutputWidget::inputWidget(), and EInputOutputWidget::outputWidget().
setSource
void QuInputOutput::setSource (const QString & s) slot
Link the reader/writer to the specified source.
Parameters
s the name of the source of the connection.
Note
The QuInputOutput reads and writes from the same source specified in s.
Any cumbia widget with the source property can be used as output widget.
See md_src_cumbia_qtcontrols_widget_constructors documentation.
References EInputOutputWidget::outputWidget().
setWriterType()
void QuInputOutput::setWriterType (QuInputOutput::WriterType t)
sets the writer type to t
Parameters
t the writer type, one of the values of the QuInputOutput::WriterType enum
The current input widget is destroyed and replaced if necessary.
References ComboBox, DoubleSpinBox, EInputOutputWidget::inputWidget(), LineEdit, Numeric, EInputOutputWidget::setInputWidget(), and SpinBox.
source()
QString QuInputOutput::source () const
unsetSource
void QuInputOutput::unsetSource () slot
unlink the QuInputOutput
The unsetSource method is invoked on the outputWidget.
References EInputOutputWidget::outputWidget().
writerType()
WriterType QuInputOutput::writerType () const
Property Documentation
source
QString QuInputOutput::source read write
Returns the name of the link.
Returns
a string with the name of the link.
Note
This method returns the source property of the output widget
See md_src_cumbia_qtcontrols_widget_constructors documentation.
The documentation for this class was generated from the following files:
quinputoutput.h
quinputoutput.cpp