cumbia-qtcontrols: ImageGL Class Reference
ImageGL Class Reference
Display widgets » Image widget
A QGLWidget to display two dimensional arrays as an image.
#include <eimagegl.h>
Public Member Functions
ImageGL (QWidget *parent=0)
void setImage (const QImage &image)
Public Member Functions inherited from EImageWidgetBase
EImageWidgetBase (QWidget *widget, bool isOpenGL)
virtual ~EImageWidgetBase ()
QImage & image () const
void setImageMouseEventInterface (ImageMouseEventInterface *ifa)
void setError (bool error)
void setColorTable (const QVector< QRgb > &rgb)
void setErrorMessage (const QString &msg)
void setZoom (int n)
void setZoomEnabled (bool en)
bool isOpenGL () const
void setErrorImage (const QImage &i)
QVector< QRgb > & colorTable () const
bool zoomEnabled () const
float zoom () const
void setImage (const QImage &image)
QImage errorImage () const
Protected Member Functions
void paintEvent (QPaintEvent *)
void mousePressEvent (QMouseEvent *ev)
void mouseMoveEvent (QMouseEvent *ev)
void mouseReleaseEvent (QMouseEvent *ev)
Protected Member Functions inherited from EImageWidgetBase
void mouseMove (QMouseEvent *e)
void mousePress (QMouseEvent *e)
void mouseRelease (QMouseEvent *e)
void wheelEvent (QWheelEvent *event)
void paint (QPaintEvent *e, QWidget *paintDevice)
void execConfigDialog ()
Detailed Description
A QGLWidget to display two dimensional arrays as an image.
Constructor & Destructor Documentation
ImageGL()
ImageGL::ImageGL (QWidget * parent = 0) explicit
Member Function Documentation
mouseMoveEvent()
void ImageGL::mouseMoveEvent (QMouseEvent * ev) protected
References EImageWidgetBase::mouseMove().
mousePressEvent()
void ImageGL::mousePressEvent (QMouseEvent * ev) protected
References EImageWidgetBase::mousePress().
mouseReleaseEvent()
void ImageGL::mouseReleaseEvent (QMouseEvent * ev) protected
References EImageWidgetBase::mouseRelease().
paintEvent()
void ImageGL::paintEvent (QPaintEvent * e) protected
References EImageWidgetBase::paint().
setImage()
void ImageGL::setImage (const QImage & image)
References EImageWidgetBase::setImage().
The documentation for this class was generated from the following files:
eimagegl.h
eimagegl.cpp