cumbia-qtcontrols: QmlChartBackend Class Reference
QmlChartBackend Class Reference
#include <qmlchartbackend.h>
Public Slots
void setSources (const QString &sl)
void unsetSources ()
void replaceData (QtCharts::QAbstractSeries *series)
void appendPoint (QtCharts::QAbstractSeries *series)
void setXMin (qreal xm)
void setXMax (qreal xM)
void setYMin (qreal ym)
void setYMax (qreal yM)
void setXAutoscale (bool a)
void setYAutoscale (bool a)
void setBufsiz (int b)
void setPeriod (int millis)
Signals
void sourcesChanged (const QStringList &srcs)
void readOkChanged ()
void xMinChanged ()
void yMinChanged ()
void xMaxChanged ()
void yMaxChanged ()
void scalarTrendChanged (bool isTrend)
void bufsizChanged ()
void xAutoscaleChanged ()
void yAutoscaleChanged ()
void newPoint (const QString &src)
void newSpectrum (const QString &src)
void periodChanged ()
void t1Changed ()
void t2Changed ()
Public Member Functions
QmlChartBackend (QObject *parent=nullptr)
virtual ~QmlChartBackend ()
Q_INVOKABLE void init (CumbiaPool_O *poo_o)
Q_INVOKABLE void suspend ()
Q_INVOKABLE void start ()
QString sources () const
bool readOk () const
qreal xMin () const
qreal xMax () const
qreal yMin () const
qreal yMax () const
bool timeScale () const
bool scalarTrend () const
bool xAutoscale () const
bool yAutoscale () const
int period () const
int bufsiz () const
QDateTime t1 () const
QDateTime t2 () const
virtual CuContext * getContext () const
Return a reference to the CuContext in use.
virtual void onUpdate (const CuData &data)
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
QString sources
int period
bool readOk
bool xAutoscale
bool yAutoscale
qreal xMin
qreal yMin
qreal xMax
qreal yMax
QDateTime t1
QDateTime t2
int bufsiz
bool scalarTrend
Constructor & Destructor Documentation
QmlChartBackend()
QmlChartBackend::QmlChartBackend (QObject * parent = nullptr) explicit
~QmlChartBackend()
QmlChartBackend::~QmlChartBackend () virtual
Member Function Documentation
appendPoint
void QmlChartBackend::appendPoint (QtCharts::QAbstractSeries * series) slot
bufsiz()
int QmlChartBackend::bufsiz () const
bufsizChanged
void QmlChartBackend::bufsizChanged () signal
Referenced by setBufsiz().
getContext()
CuContext * QmlChartBackend::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
init()
void QmlChartBackend::init (CumbiaPool_O * poo_o)
References CumbiaPool_O::getFactory(), and CumbiaPool_O::getPool().
newPoint
void QmlChartBackend::newPoint (const QString & src) signal
Referenced by onUpdate().
newSpectrum
void QmlChartBackend::newSpectrum (const QString & src) signal
Referenced by onUpdate().
onUpdate()
void QmlChartBackend::onUpdate (const CuData & data) virtual
References CuLinkStats::addError(), CuLinkStats::addOperation(), newPoint(), newSpectrum(), readOk(), readOkChanged(), t1Changed(), t2Changed(), xMaxChanged(), and xMinChanged().
period()
int QmlChartBackend::period () const
periodChanged
void QmlChartBackend::periodChanged () signal
Referenced by setPeriod().
readOk()
bool QmlChartBackend::readOk () const
Referenced by onUpdate().
readOkChanged
void QmlChartBackend::readOkChanged () signal
Referenced by onUpdate().
replaceData
void QmlChartBackend::replaceData (QtCharts::QAbstractSeries * series) slot
scalarTrend()
bool QmlChartBackend::scalarTrend () const
scalarTrendChanged
void QmlChartBackend::scalarTrendChanged (bool isTrend) signal
setBufsiz
void QmlChartBackend::setBufsiz (int b) slot
References bufsizChanged().
setPeriod
void QmlChartBackend::setPeriod (int millis) slot
References periodChanged().
setSources
void QmlChartBackend::setSources (const QString & sl) slot
setXAutoscale
void QmlChartBackend::setXAutoscale (bool a) slot
References xAutoscaleChanged().
setXMax
void QmlChartBackend::setXMax (qreal xM) slot
References xAutoscaleChanged(), and xMaxChanged().
setXMin
void QmlChartBackend::setXMin (qreal xm) slot
References xAutoscaleChanged(), and xMinChanged().
setYAutoscale
void QmlChartBackend::setYAutoscale (bool a) slot
References yAutoscaleChanged().
setYMax
void QmlChartBackend::setYMax (qreal yM) slot
References yAutoscaleChanged(), and yMaxChanged().
setYMin
void QmlChartBackend::setYMin (qreal ym) slot
References yAutoscaleChanged(), and yMinChanged().
sources()
QString QmlChartBackend::sources () const
sourcesChanged
void QmlChartBackend::sourcesChanged (const QStringList & srcs) signal
start()
void QmlChartBackend::start ()
suspend()
void QmlChartBackend::suspend ()
References unsetSources().
t1()
QDateTime QmlChartBackend::t1 () const
t1Changed
void QmlChartBackend::t1Changed () signal
Referenced by onUpdate().
t2()
QDateTime QmlChartBackend::t2 () const
t2Changed
void QmlChartBackend::t2Changed () signal
Referenced by onUpdate().
timeScale()
bool QmlChartBackend::timeScale () const
unsetSources
void QmlChartBackend::unsetSources () slot
Referenced by suspend().
xAutoscale()
bool QmlChartBackend::xAutoscale () const
xAutoscaleChanged
void QmlChartBackend::xAutoscaleChanged () signal
Referenced by setXAutoscale(), setXMax(), and setXMin().
xMax()
qreal QmlChartBackend::xMax () const
xMaxChanged
void QmlChartBackend::xMaxChanged () signal
Referenced by onUpdate(), and setXMax().
xMin()
qreal QmlChartBackend::xMin () const
xMinChanged
void QmlChartBackend::xMinChanged () signal
Referenced by onUpdate(), and setXMin().
yAutoscale()
bool QmlChartBackend::yAutoscale () const
yAutoscaleChanged
void QmlChartBackend::yAutoscaleChanged () signal
Referenced by setYAutoscale(), setYMax(), and setYMin().
yMax()
qreal QmlChartBackend::yMax () const
yMaxChanged
void QmlChartBackend::yMaxChanged () signal
Referenced by setYMax().
yMin()
qreal QmlChartBackend::yMin () const
yMinChanged
void QmlChartBackend::yMinChanged () signal
Referenced by setYMin().
Property Documentation
bufsiz
int QmlChartBackend::bufsiz read write
period
int QmlChartBackend::period read write
readOk
bool QmlChartBackend::readOk read
scalarTrend
bool QmlChartBackend::scalarTrend read
sources
QString QmlChartBackend::sources read write
t1
QDateTime QmlChartBackend::t1 read
t2
QDateTime QmlChartBackend::t2 read
xAutoscale
bool QmlChartBackend::xAutoscale read write
xMax
qreal QmlChartBackend::xMax read write
xMin
qreal QmlChartBackend::xMin read write
yAutoscale
bool QmlChartBackend::yAutoscale read write
yMax
qreal QmlChartBackend::yMax read write
yMin
qreal QmlChartBackend::yMin read write
The documentation for this class was generated from the following files:
qmlchartbackend.h
qmlchartbackend.cpp