cumbia-qtcontrols: QuAppInfo Class Reference
QuAppInfo Class Reference
Plugins
a class that groups information about a QuApplication
#include <qudbusplugininterface.h>
Public Member Functions
virtual ~QuAppInfo ()
QuAppInfo ()
QuAppInfo (const QStringList &_args, const QString &dbus_servnam, const QString &display_host, const int display_number, const int screen_number, bool is_plat_x11)
QuAppInfo constructor that accepts the full command line as provided by QApplication::arguments, including argv[0].
QuAppInfo (const QString &exenam, const QStringList &argums, const QString &dbus_servicenam, const QString &display_host, const int display_number, const int screen_number, bool is_plat_x11)
bool isEmpty () const
QuAppInfo is empty if argv[0] is empty.
QString exename () const
Returns the executable name, that is argv[0] without the path.
QString path () const
Returns the path of the executable, if provided in the constructor.
QString argv0 () const
Returns argv[0].
QStringList args () const
QString dbusServiceName () const
QString display_host () const
int display_number () const
int screen_number () const
bool isPlatformX11 () const
Detailed Description
a class that groups information about a QuApplication
Constructor & Destructor Documentation
~QuAppInfo()
virtual QuAppInfo::~QuAppInfo () inline virtual
QuAppInfo() [1/3]
QuAppInfo::QuAppInfo () inline
QuAppInfo() [2/3]
QuAppInfo::QuAppInfo (const QStringList & _args, const QString & dbus_servnam, const QString & display_host, const int display_number, const int screen_number, bool is_plat_x11) inline
QuAppInfo constructor that accepts the full command line as provided by QApplication::arguments, including argv[0].
Parameters
_args the value returned by QApplication::arguments, argv[0] included.
Initializes the fields of the QuAppInfo structure. This will separate the application name and the command line options provided with the input parameter.
The exename method returns the argv[0]
args field (public) contains the command line options, without the argv[0]
path returns the application path, if provided, that is argv[0] - exename
argv0 returns the argv[0]
References display_host(), display_number(), and screen_number().
QuAppInfo() [3/3]
QuAppInfo::QuAppInfo (const QString & exenam, const QStringList & argums, const QString & dbus_servicenam, const QString & display_host, const int display_number, const int screen_number, bool is_plat_x11) inline
References display_host(), display_number(), and screen_number().
Member Function Documentation
args()
QStringList QuAppInfo::args () const inline
argv0()
QString QuAppInfo::argv0 () const inline
Returns argv[0].
dbusServiceName()
QString QuAppInfo::dbusServiceName () const inline
display_host()
QString QuAppInfo::display_host () const inline
Referenced by QuAppInfo().
display_number()
int QuAppInfo::display_number () const inline
Referenced by QuAppInfo().
exename()
QString QuAppInfo::exename () const inline
Returns the executable name, that is argv[0] without the path.
Referenced by path().
isEmpty()
bool QuAppInfo::isEmpty () const inline
QuAppInfo is empty if argv[0] is empty.
isPlatformX11()
bool QuAppInfo::isPlatformX11 () const inline
path()
QString QuAppInfo::path () const inline
Returns the path of the executable, if provided in the constructor.
If the QuApplication has been build without the path, an empty string must be expected.
References exename().
screen_number()
int QuAppInfo::screen_number () const inline
Referenced by QuAppInfo().
The documentation for this class was generated from the following file:
qudbusplugininterface.h