cumbia-qtcontrols: QuPlotZoomComponent Class Reference
QuPlotZoomComponent Class Reference
Display widgets » Plots
QuPlot component to zoom the plot.
#include <quplotzoomcomponent.h>
Public Member Functions
QuPlotZoomComponent (QuPlotBase *plot)
virtual ~QuPlotZoomComponent ()
bool inZoom () const
void changeRect (int axisId, double delta_lower, double delta_upper)
void setZoomBase (bool do_replot=false)
void setZoomBase (const QRectF &r)
QRectF zoomBase () const
QRectF zoomRect () const
QString name () const
void attachToPlot (QuPlotBase *plot)
in this method you would call QwtPlot::attach for the QwtPlotItem items in the component
void connectToPlot (QuPlotBase *plot)
in this method you would create Qt signal/slot connections
Public Member Functions inherited from QuPlotComponent
virtual ~QuPlotComponent ()
Detailed Description
QuPlot component to zoom the plot.
Constructor & Destructor Documentation
QuPlotZoomComponent()
QuPlotZoomComponent::QuPlotZoomComponent (QuPlotBase * plot)
~QuPlotZoomComponent()
QuPlotZoomComponent::~QuPlotZoomComponent () virtual
Member Function Documentation
attachToPlot()
void QuPlotZoomComponent::attachToPlot (QuPlotBase * plot) virtual
in this method you would call QwtPlot::attach for the QwtPlotItem items in the component
Example
See QuPlotMarkerComponent::attachToPlot
Implements QuPlotComponent.
Referenced by QuPlotBase::setZoomDisabled().
changeRect()
void QuPlotZoomComponent::changeRect (int axisId, double delta_lower, double delta_upper)
Referenced by QuPlotBase::updateScales().
connectToPlot()
void QuPlotZoomComponent::connectToPlot (QuPlotBase * plot) virtual
in this method you would create Qt signal/slot connections
Example
See QuPlotMarkerComponent::connectToPlot and QuPlotZoomComponent::connectToPlot
Implements QuPlotComponent.
Referenced by QuPlotBase::setZoomDisabled().
inZoom()
bool QuPlotZoomComponent::inZoom () const
Referenced by QuPlotBase::inZoom(), QuPlotBase::resetZoom(), and QuPlotBase::updateScales().
name()
QString QuPlotZoomComponent::name () const virtual
Implements QuPlotComponent.
Referenced by QuPlotBase::setZoomDisabled().
setZoomBase() [1/2]
void QuPlotZoomComponent::setZoomBase (bool do_replot = false)
Referenced by QuPlotBase::resetZoom().
setZoomBase() [2/2]
void QuPlotZoomComponent::setZoomBase (const QRectF & r)
zoomBase()
QRectF QuPlotZoomComponent::zoomBase () const
zoomRect()
QRectF QuPlotZoomComponent::zoomRect () const
The documentation for this class was generated from the following files:
quplotzoomcomponent.h
quplotzoomcomponent.cpp