cumbia-qtcontrols: QuCircularGauge Class Reference
QuCircularGauge Class Reference
Display widgets
A label derived from Qt QLabel to display boolean values, strings, scalars and even vectors.
#include <qucirculargauge.h>
Public Slots
void setSource (const QString &s)
Connect the reader to the specified source.
void unsetSource ()
Public Slots inherited from QuCircularGaugeBase
void setValue (double v)
void setReadError (bool err)
void setValue_anim (double v)
void setAngleStart (int as)
set the start angle of the arc, in degrees, from 6 o'clock
void setAngleSpan (int a)
set the span of the arc of the gauge
void setMinValue (double min)
void setMaxValue (double max)
void setLabel (const QString &l)
void setTicksCount (int t)
void setMinorTicksCount (int t)
void setTickLen (double tl)
Set the tick len as percentage of the radius of the circle.
void setGaugeWidth (double w)
void setPivotCircleRadius (double percent)
void setDrawBackgroundEnabled (bool en)
void setHighWarning (double w)
void setLowWarning (double w)
void setHighError (double e)
void setLowError (double e)
void setTextColor (const QColor &c)
void setErrorColor (const QColor &ec)
void setWarningColor (const QColor &wc)
void setNormalColor (const QColor &nc)
void setReadErrorColor (const QColor &rec)
void setBackgroundColor (const QColor &bc)
void setNeedleColor (const QColor &c)
void setTickCoreColor (const QColor &c)
void setBackgroundGradientSpread (double s)
If background drawing is enabled, the spread determines the stop point of the gradient from the current value color (normal, warning or error) and the background color.
void setBackgroundColorAlpha (int a)
void setDrawTickCore1 (bool t)
void setDrawTickCore2 (bool t)
void setDrawColoredTicks (bool dr)
void setDrawText (bool dt)
void setAnimationEnabled (bool ae)
void setMaxAnimationDuration (qint64 millis)
void setLabelPosition (LabelPosition p)
void setLabelDistFromCenter (double radius_percent)
void setLabelValueFormat (const QString &f)
void setUnit (const QString &u)
void setLabelFontScale (double factor)
changes the label font size respect to the automatically calculated size
void setFormat (const QString &f)
sets the format to be used on the text along the gauge if the property formatFromProperty enabled is false
void setFormatFromPropertyEnabled (bool ffp)
enables or disables applying format from the configuration CuData
void setFormatProperty (const QString &fp)
sets the format of the text along the gauge to be used when formatFromPropertyEnabled is true
QList< int > updateLabelsDistrib () const
get the labels distribution according to the shape of the gauge
void updateLabelsCache ()
void regenerateCache ()
void updatePaintArea ()
void updateLabelsFontSize ()
Public Slots inherited from EAbstractGauge
void setValue (double)
void setValue (int)
void setValue (double)
void setValue (int)
Signals
void newData (const CuData &)
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
Public Member Functions
QuCircularGauge ()
QuCircularGauge (QWidget *w, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuCircularGauge (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuCircularGauge ()
QString source () const
CuContext * getContext () const
returns the pointer to the CuContext
void onUpdate (const CuData &d)
Public Member Functions inherited from QuCircularGaugeBase
QuCircularGaugeBase (QWidget *parent=nullptr)
virtual ~QuCircularGaugeBase ()
double value () const
double value_anim () const
double maxValue () const
double minValue () const
int angleSpan () const
int angleStart () const
int ticksCount () const
int minorTicksCount () const
double tickLen () const
double gaugeWidth () const
double pivotCircleRadius () const
bool drawBackgroundEnabled () const
returns true if a background is drawn, false otherwise
bool drawText () const
bool drawTickCore1 () const
bool drawTickCore2 () const
bool drawColoredTicks () const
bool animationEnabled () const
bool readError () const
qint64 maxAnimationDuration () const
LabelPosition labelPosition () const
double labelDistFromCenter () const
double labelFontScale () const
double lowWarning ()
double highWarning ()
double lowError ()
double highError ()
QColor textColor () const
QColor warningColor () const
QColor errorColor () const
QColor normalColor () const
QColor readErrorColor () const
QColor backgroundColor () const
QColor needleColor () const
QColor tickCoreColor () const
double backgroundGradientSpread () const
int backgroundColorAlpha () const
double getPivotRadius ()
QString label () const
QString format () const
bool formatFromPropertyEnabled () const
QString getAppliedFormat () const
QString labelValueFormat () const
QString unit () const
QPointF mapTo (double val, int *angleSpan, double radius=-1.0, const QRectF &paint_area=QRectF())
maps a value to a point close to the arc of the gauge
QRectF textRect (int tick, double radius)
double labelFontSize ()
virtual QString formatLabel (double val, const QString &format) const
QString label (int i) const
QRectF paintArea ()
QSize sizeHint () const
QSize minimumSizeHint () const
bool inWarningRange (double val) const
Returns true if the value is within the warning range.
bool inErrorRange (double val) const
Returns true if the value is within the error range.
QColor valueColor (double val) const
returns the color associated to a value
void setCacheRegenerationDisabled (bool dis)
disables cache regeneration
bool cacheRegenerationDisabled () const
returns true if regenerateCache is disabled, false otherwise
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Public Member Functions inherited from ECircularGauge
ECircularGauge (QWidget *=NULL)
~ECircularGauge ()
void setValueDisplayed (bool b)
bool isValueDisplayed ()
void setLabel (QString l)
QString label ()
ECircularGauge (QWidget *=NULL)
~ECircularGauge ()
void setValueDisplayed (bool b)
bool isValueDisplayed ()
void setLabel (QString l)
QString label ()
Public Member Functions inherited from EAbstractGauge
EAbstractGauge (QWidget *=NULL)
~EAbstractGauge ()
bool logarithmicScale ()
void setLogarithmicScale (bool l)
void setLowWarning (double w)
double lowWarning ()
void setHighWarning (double w)
double highWarning ()
void setLowError (double e)
double lowError ()
void setHighError (double e)
double highError ()
void setMinValue (double v)
double minValue ()
void setMaxValue (double v)
double maxValue ()
double value ()
void setReference (double r)
double reference ()
void setScaleEnabled (bool b)
bool isScaleEnabled ()
void setReferenceEnabled (bool b)
bool isReferenceEnabled ()
void setColorMode (ColorMode m)
ColorMode colorMode ()
DEPRECATED (void setNormalColor(QColor c))
QColor normalColor ()
DEPRECATED (void setWarningColor(QColor c))
QColor warningColor ()
DEPRECATED (void setErrorColor(QColor c))
QColor errorColor ()
void setExternalScale (bool b)
bool externalScale ()
void setNumMajorTicks (int t)
int numMajorTicks ()
void setNumMinorTicks (int t)
int numMinorTicks ()
void setValueFormat (QString s)
QString valueFormat ()
EAbstractGauge (QWidget *=NULL)
~EAbstractGauge ()
bool logarithmicScale ()
void setLogarithmicScale (bool l)
void setLowWarning (double w)
double lowWarning ()
void setHighWarning (double w)
double highWarning ()
void setLowError (double e)
double lowError ()
void setHighError (double e)
double highError ()
void setMinValue (double v)
double minValue ()
void setMaxValue (double v)
double maxValue ()
double value ()
void setReference (double r)
double reference ()
void setScaleEnabled (bool b)
bool isScaleEnabled ()
void setReferenceEnabled (bool b)
bool isReferenceEnabled ()
void setColorMode (ColorMode m)
ColorMode colorMode ()
DEPRECATED (void setNormalColor(QColor c))
QColor normalColor ()
DEPRECATED (void setWarningColor(QColor c))
QColor warningColor ()
DEPRECATED (void setErrorColor(QColor c))
QColor errorColor ()
void setExternalScale (bool b)
bool externalScale ()
void setNumMajorTicks (int t)
int numMajorTicks ()
void setNumMinorTicks (int t)
int numMinorTicks ()
void setValueFormat (QString s)
QString valueFormat ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e)
Protected Member Functions inherited from QuCircularGaugeBase
void paintEvent (QPaintEvent *pe)
virtual void drawText (const QRectF &rect, int idx, QPainter &p)
virtual void drawNeedle (const QPointF &end, int angleSpan, const QRectF &rect, QPainter &p)
Draw the needle.
virtual void drawGauge (const QRectF &rect, int startAngle, int span, QPainter &p)
virtual void drawPivot (const QRectF &rect, QPainter &p)
virtual void drawTicks (const QRectF &rect, QPainter &p)
virtual void drawBackground (const QRectF &rect, QPainter &p)
virtual void drawLabel (const QRectF &rect, QPainter &p)
void changeEvent (QEvent *e)
void resizeEvent (QResizeEvent *re)
Protected Member Functions inherited from ECircularGauge
void paintEvent (QPaintEvent *)
void drawColorBar (QPainter *)
void drawScale (QPainter *)
void drawNeedle (QPainter *)
void drawLabels (QPainter *)
void drawValue (QPainter *)
virtual void configure ()
void paintEvent (QPaintEvent *)
void drawColorBar (QPainter *)
void drawScale (QPainter *)
void drawNeedle (QPainter *)
void drawLabels (QPainter *)
void drawValue (QPainter *)
virtual void configure ()
Properties
QString source
Properties inherited from QuCircularGaugeBase
double value
double value_anim
returns the value during the animation
double minValue
returns the minimum value represented by this gauge
double maxValue
returns the maximum value represented by this gauge
bool drawText
either draw or not the labels with the values associated to each major tick
bool animationEnabled
if true, an animation is used to draw the transition between two subsequent setValue calls
qint64 maxAnimationDuration
The maximum duration of an animation between two setValue calls.
double lowWarning
double highWarning
double lowError
double highError
int angleStart
returns the angle from which the gauge arc starts
int angleSpan
returns the span of the angle of the circular gauge, in degrees
int ticksCount
returns the number of major ticks drawn in the arc
int minorTicksCount
returns the number of minor ticks drawn between each couple of major ticks
double tickLen
returns the tick length
double pivotCircleRadius
If greater than zero, a circle is drawn on the pivot of the needle.
double gaugeWidth
returns the pen width used to draw the gauge arc
bool drawBackground
bool drawTickCore1
draw a tick inside the gauge arc
bool drawTickCore2
draw a tick from the inner border of the gauge arc
bool drawColoredTicks
draw colored ticks
QString format
bool formatFromPropertyEnabled
QColor textColor
QColor warningColor
QColor tickCoreColor
QColor errorColor
QColor normalColor
QColor readErrorColor
QColor backgroundColor
double backgroundGradientSpread
QColor needleColor
int backgroundColorAlpha
QString label
LabelPosition labelPosition
double labelDistFromCenter
QString labelValueFormat
QString unit
double labelFontScale
scales the label font respect to the automatically calculated size
Properties inherited from ECircularGauge
bool valueDisplayed
QString label
Properties inherited from EAbstractGauge
double minValue
double lowError
double lowWarning
double highWarning
double highError
double maxValue
double value
double reference
bool scaleEnabled
bool referenceEnabled
ColorMode colorMode
bool externalScale
bool logarithmicScale
QString valueFormat
int numMajorTicks
int numMinorTicks
Additional Inherited Members
Public Types inherited from QuCircularGaugeBase
enum Quads {
q1, q2, q3, q4,
q21, q43, q32, q14,
q432, q321, q214, q143,
q4321, q3214, q2143, q1432
}
enum LabelPosition {
NoLabel, North, NorthEast, East,
SouthEast, South, SouthWest, West,
NorthWest
}
Public Types inherited from EAbstractGauge
enum ColorMode {
GRADIENT, COLORBAR, SINGLECOLOR, GRADIENT,
COLORBAR, SINGLECOLOR
}
enum ColorMode {
GRADIENT, COLORBAR, SINGLECOLOR, GRADIENT,
COLORBAR, SINGLECOLOR
}
Protected Attributes inherited from QuCircularGaugeBase
QuGaugeConfig * g_config
Protected Attributes inherited from EAbstractGauge
double m_minValue
double m_maxValue
double m_lowWarning
double m_highWarning
double m_lowError
double m_highError
double m_value
double m_reference
double d_naturalMinV
double d_naturalMaxV
double d_naturalLowWarn
double d_naturalHighWarn
double d_naturalLowErr
double d_naturalHighErr
double d_naturalValue
double d_naturalReference
ColorMode m_colorMode
bool m_referenceEnabled
bool m_scaleEnabled
int m_numMajorTicks
int m_numMinorTicks
QStringList labels
int longestLabelIndex
bool m_externalScale
QVector< qreal > v_p
QVector< QColor > v_c
QColor m_normalColor
QColor m_warningColor
QColor m_errorColor
QString m_valueFormat
Detailed Description
A label derived from Qt QLabel to display boolean values, strings, scalars and even vectors.
Colors and strings can be associated to boolean values.
Scalar numbers and strings can be displayed by QuCircularGauge.
Vectors are usually displayed only partially, according to the number of maximum characters allowed by setMaximumLength
Connection is initiated with setSource. When new data arrives, it is displayed and the newData convenience signal is emitted.
getContext returns a pointer to the CuContext used as a delegate for the connection.
Constructor & Destructor Documentation
QuCircularGauge() [1/3]
QuCircularGauge::QuCircularGauge ()
QuCircularGauge() [2/3]
QuCircularGauge::QuCircularGauge (QWidget * w, Cumbia * cumbia, const CuControlsReaderFactoryI & r_factory)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuCircularGauge() [3/3]
QuCircularGauge::QuCircularGauge (QWidget * w, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuCircularGauge()
QuCircularGauge::~QuCircularGauge () virtual
Member Function Documentation
contextMenuEvent()
void QuCircularGauge::contextMenuEvent (QContextMenuEvent * e) protected
getContext()
CuContext * QuCircularGauge::getContext () const virtual
returns the pointer to the CuContext
CuContext sets up the connection and is used as a mediator to send and get data to and from the reader.
See also
CuContext
Implements CuContextI.
linkStatsRequest
void QuCircularGauge::linkStatsRequest (QWidget * myself, CuContextI * myself_as_cwi) signal
newData
void QuCircularGauge::newData (const CuData &) signal
Referenced by onUpdate().
onUpdate()
void QuCircularGauge::onUpdate (const CuData & d)
References newData(), ECircularGauge::setLabel(), and QuCircularGaugeBase::setReadError().
setSource
void QuCircularGauge::setSource (const QString & s) slot
Connect the reader to the specified source.
If a reader with a different source is configured, it is deleted. If options have been set with QuContext::setOptions, they are used to set up the reader as desired.
See also
QuContext::setOptions
source
References CuControlsReaderA::setSource().
source()
QString QuCircularGauge::source () const
unsetSource
void QuCircularGauge::unsetSource () slot
Property Documentation
source
QString QuCircularGauge::source read write
The documentation for this class was generated from the following files:
qucirculargauge.h
qucirculargauge.cpp