cumbia-qtcontrols: QuSpinBox Class Reference
QuSpinBox Class Reference
#include <quspinbox.h>
Public Slots
void setTarget (const QString &targets)
Set the name of the target that will be executed.
Public Member Functions
QuSpinBox (QWidget *parent, Cumbia *cumbia, const CuControlsWriterFactoryI &w_fac)
QuSpinBox (QWidget *parent, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
virtual ~QuSpinBox ()
virtual CuContext * getContext () const
Return a reference to the CuContext in use.
virtual void onUpdate (const CuData &data)
QString target () const
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
QString target
returns the target name.
Constructor & Destructor Documentation
QuSpinBox() [1/2]
QuSpinBox::QuSpinBox (QWidget * parent, Cumbia * cumbia, const CuControlsWriterFactoryI & w_fac)
QuSpinBox() [2/2]
QuSpinBox::QuSpinBox (QWidget * parent, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
~QuSpinBox()
QuSpinBox::~QuSpinBox () virtual
Member Function Documentation
getContext()
CuContext * QuSpinBox::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
onUpdate()
void QuSpinBox::onUpdate (const CuData & data) virtual
References target().
setTarget
void QuSpinBox::setTarget (const QString & targets) slot
Set the name of the target that will be executed.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References CuControlsWriterA::setTarget().
target()
QString QuSpinBox::target () const
Referenced by onUpdate().
Property Documentation
target
QString QuSpinBox::target read write
returns the target name.
Returns
the target name, or an empty string if setTarget hasn't been called yet.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
The documentation for this class was generated from the following files:
quspinbox.h
quspinbox.cpp