cumbia-qtcontrols: QuPlotAxesComponent Class Reference
QuPlotAxesComponent Class Reference
Display widgets » Plots
Plot component that manages the axes.
#include <quplotaxescomponent.h>
Public Types
enum ScaleMode { AutoScale = 0x0 , SemiAutoScale = 0x01 , Manual = 0x02 }
Public Member Functions
QuPlotAxesComponent (QuPlotBase *plot)
~QuPlotAxesComponent ()
QString name () const
void attachToPlot (QuPlotBase *plot)
in this method you would call QwtPlot::attach for the QwtPlotItem items in the component
void connectToPlot (QuPlotBase *plot)
in this method you would create Qt signal/slot connections
void setBounds (QuPlotBase *plot, int axisId, double lb, double ub)
void setManualBounds (QuPlotBase *plot, int axisId, double lb, double ub)
void setDefaultBounds (QuPlotBase *plot, int axisId, double lb, double ub)
void restoreDefaultBounds (QuPlotBase *plot, int axisId)
bool applyScaleFromCurveBounds (QuPlotBase *plot, int axisId)
Calls setAxisScale on the plot.
bool setBoundsFromCurves (double min, double max, int axisId)
bool getBoundsFromCurves (const QuPlotBase *plot, double *xmin, double *xmax, double *ymin, double *ymax, bool calc_x, bool calc_y) const
bool autoscale (int axisId) const
ScaleMode scaleMode (int axisId) const
void setAutoscale (int axisId, bool a)
double autoscaleMargin (int axisId) const
void setAutoscaleMargin (int axisId, double m)
double lowerBoundFromCurves (int axisId) const
double upperBoundFromCurves (int axisId) const
double defaultLowerBound (int axisId) const
double defaultUpperBound (int axisId) const
void setUpperBoundExtra (int axisId, double ube)
double upperBoundExtra (int axisId) const
Public Member Functions inherited from QuPlotComponent
virtual ~QuPlotComponent ()
Detailed Description
Plot component that manages the axes.
Member Enumeration Documentation
ScaleMode
enum QuPlotAxesComponent::ScaleMode
Enumerator
AutoScale
SemiAutoScale
Manual
Constructor & Destructor Documentation
QuPlotAxesComponent()
QuPlotAxesComponent::QuPlotAxesComponent (QuPlotBase * plot)
References AutoScale, and SemiAutoScale.
~QuPlotAxesComponent()
QuPlotAxesComponent::~QuPlotAxesComponent ()
Member Function Documentation
applyScaleFromCurveBounds()
bool QuPlotAxesComponent::applyScaleFromCurveBounds (QuPlotBase * plot, int axisId)
Calls setAxisScale on the plot.
Returns true if the axis scale has changed, false otherwise
Referenced by QuPlotBase::updateScales().
attachToPlot()
void QuPlotAxesComponent::attachToPlot (QuPlotBase * plot) virtual
in this method you would call QwtPlot::attach for the QwtPlotItem items in the component
Example
See QuPlotMarkerComponent::attachToPlot
Implements QuPlotComponent.
autoscale()
bool QuPlotAxesComponent::autoscale (int axisId) const
References AutoScale.
Referenced by QuPlotBase::updateScales(), QuPlotBase::xAxisAutoscaleEnabled(), and QuPlotBase::yAxisAutoscaleEnabled().
autoscaleMargin()
double QuPlotAxesComponent::autoscaleMargin (int axisId) const
connectToPlot()
void QuPlotAxesComponent::connectToPlot (QuPlotBase * plot) virtual
in this method you would create Qt signal/slot connections
Example
See QuPlotMarkerComponent::connectToPlot and QuPlotZoomComponent::connectToPlot
Implements QuPlotComponent.
defaultLowerBound()
double QuPlotAxesComponent::defaultLowerBound (int axisId) const
Referenced by QuPlotBase::defaultLowerBound().
defaultUpperBound()
double QuPlotAxesComponent::defaultUpperBound (int axisId) const
Referenced by QuPlotBase::defaultUpperBound().
getBoundsFromCurves()
bool QuPlotAxesComponent::getBoundsFromCurves (const QuPlotBase * plot, double * xmin, double * xmax, double * ymin, double * ymax, bool calc_x, bool calc_y) const
References QuPlotBase::curves().
Referenced by QuPlotBase::updateScales().
lowerBoundFromCurves()
double QuPlotAxesComponent::lowerBoundFromCurves (int axisId) const
Referenced by QuPlotBase::configure(), and QuPlotBase::updateScales().
name()
QString QuPlotAxesComponent::name () const virtual
Implements QuPlotComponent.
Referenced by QuPlotBase::init().
restoreDefaultBounds()
void QuPlotAxesComponent::restoreDefaultBounds (QuPlotBase * plot, int axisId)
References SemiAutoScale.
Referenced by QuPlotBase::restoreDefaultBounds().
scaleMode()
QuPlotAxesComponent::ScaleMode QuPlotAxesComponent::scaleMode (int axisId) const
Referenced by QuPlotBase::configure().
setAutoscale()
void QuPlotAxesComponent::setAutoscale (int axisId, bool a)
References AutoScale, and Manual.
Referenced by QuPlotBase::setAxisScaleDefaultEnabled(), QuPlotBase::setXAxisAutoscaleEnabled(), QuPlotBase::setXTopAxisAutoscaleEnabled(), QuPlotBase::setYAxisAutoscaleEnabled(), and QuPlotBase::setYRightAxisAutoscaleEnabled().
setAutoscaleMargin()
void QuPlotAxesComponent::setAutoscaleMargin (int axisId, double m)
Referenced by QuPlotBase::setXAutoscaleMargin(), and QuPlotBase::setYAutoscaleAdjustment().
setBounds()
void QuPlotAxesComponent::setBounds (QuPlotBase * plot, int axisId, double lb, double ub)
Referenced by QuPlotBase::setXAxisAutoscaleEnabled(), QuPlotBase::setXTopAxisAutoscaleEnabled(), QuPlotBase::setYAxisAutoscaleEnabled(), and QuPlotBase::setYRightAxisAutoscaleEnabled().
setBoundsFromCurves()
bool QuPlotAxesComponent::setBoundsFromCurves (double min, double max, int axisId)
Referenced by QuPlotBase::updateScales().
setDefaultBounds()
void QuPlotAxesComponent::setDefaultBounds (QuPlotBase * plot, int axisId, double lb, double ub)
Referenced by QuPlotBase::setDefaultBounds().
setManualBounds()
void QuPlotAxesComponent::setManualBounds (QuPlotBase * plot, int axisId, double lb, double ub)
References Manual.
Referenced by QuPlotConfigurator::configure(), QuPlotBase::setXLowerBound(), QuPlotBase::setXUpperBound(), QuPlotBase::setYLowerBound(), and QuPlotBase::setYUpperBound().
setUpperBoundExtra()
void QuPlotAxesComponent::setUpperBoundExtra (int axisId, double ube)
Referenced by QuPlotBase::setUpperBoundExtra().
upperBoundExtra()
double QuPlotAxesComponent::upperBoundExtra (int axisId) const
Referenced by QuPlotBase::upperBoundExtra().
upperBoundFromCurves()
double QuPlotAxesComponent::upperBoundFromCurves (int axisId) const
Referenced by QuPlotBase::configure(), and QuPlotBase::updateScales().
The documentation for this class was generated from the following files:
quplotaxescomponent.h
quplotaxescomponent.cpp