cumbia-qtcontrols: EImageWidgetBase Class Reference
EImageWidgetBase Class Reference
Display widgets » Image widget
a class inherited by EImageWidget to provide common functionalities to QWidget objects drawing an image
#include <eimagewidgetbase.h>
Public Member Functions
EImageWidgetBase (QWidget *widget, bool isOpenGL)
virtual ~EImageWidgetBase ()
QImage & image () const
void setImageMouseEventInterface (ImageMouseEventInterface *ifa)
void setError (bool error)
void setColorTable (const QVector< QRgb > &rgb)
void setErrorMessage (const QString &msg)
void setZoom (int n)
void setZoomEnabled (bool en)
bool isOpenGL () const
void setErrorImage (const QImage &i)
QVector< QRgb > & colorTable () const
bool zoomEnabled () const
float zoom () const
void setImage (const QImage &image)
QImage errorImage () const
Protected Member Functions
void mouseMove (QMouseEvent *e)
void mousePress (QMouseEvent *e)
void mouseRelease (QMouseEvent *e)
void wheelEvent (QWheelEvent *event)
void paint (QPaintEvent *e, QWidget *paintDevice)
void execConfigDialog ()
Detailed Description
a class inherited by EImageWidget to provide common functionalities to QWidget objects drawing an image
Two dimensional data can be displayed on an image through a color table
Constructor & Destructor Documentation
EImageWidgetBase()
EImageWidgetBase::EImageWidgetBase (QWidget * widget, bool isOpenGL)
References isOpenGL().
~EImageWidgetBase()
EImageWidgetBase::~EImageWidgetBase () virtual
Member Function Documentation
colorTable()
QVector< QRgb > & EImageWidgetBase::colorTable () const
errorImage()
QImage EImageWidgetBase::errorImage () const
execConfigDialog()
void EImageWidgetBase::execConfigDialog () protected
Referenced by EImageWidget::execConfigDialog().
image()
QImage & EImageWidgetBase::image () const
Referenced by EImageWidget::minimumSizeHint(), EImageWidget::setImage(), setImage(), EImageWidget::sizeHint(), and EImageWidget::wheelEvent().
isOpenGL()
bool EImageWidgetBase::isOpenGL () const inline
Referenced by EImageWidgetBase().
mouseMove()
void EImageWidgetBase::mouseMove (QMouseEvent * e) protected
Referenced by ImageGL::mouseMoveEvent(), and EImageWidget::mouseMoveEvent().
mousePress()
void EImageWidgetBase::mousePress (QMouseEvent * e) protected
Referenced by ImageGL::mousePressEvent(), and EImageWidget::mousePressEvent().
mouseRelease()
void EImageWidgetBase::mouseRelease (QMouseEvent * e) protected
Referenced by ImageGL::mouseReleaseEvent(), and EImageWidget::mouseReleaseEvent().
paint()
void EImageWidgetBase::paint (QPaintEvent * e, QWidget * paintDevice) protected
References Elettra::black, Elettra::green, KDARKRED, Elettra::red, and Elettra::white.
Referenced by ImageGL::paintEvent(), and EImageWidget::paintEvent().
setColorTable()
void EImageWidgetBase::setColorTable (const QVector< QRgb > & rgb)
setError()
void EImageWidgetBase::setError (bool error) inline
Referenced by EImageWidget::setError().
setErrorImage()
void EImageWidgetBase::setErrorImage (const QImage & i)
Referenced by EImageWidget::setErrorImage().
setErrorMessage()
void EImageWidgetBase::setErrorMessage (const QString & msg) inline
Referenced by EImageWidget::setErrorMessage().
setImage()
void EImageWidgetBase::setImage (const QImage & image)
References image().
Referenced by ImageGL::setImage(), and EImageWidget::setImage().
setImageMouseEventInterface()
void EImageWidgetBase::setImageMouseEventInterface (ImageMouseEventInterface * ifa)
setZoom()
void EImageWidgetBase::setZoom (int n) inline
setZoomEnabled()
void EImageWidgetBase::setZoomEnabled (bool en)
wheelEvent()
void EImageWidgetBase::wheelEvent (QWheelEvent * event) protected
Referenced by EImageWidget::wheelEvent().
zoom()
float EImageWidgetBase::zoom () const
Referenced by EImageWidget::setImage().
zoomEnabled()
bool EImageWidgetBase::zoomEnabled () const
The documentation for this class was generated from the following files:
eimagewidgetbase.h
eimagewidgetbase.cpp