cumbia-qtcontrols: QuLinearGauge Class Reference
QuLinearGauge Class Reference
Display widgets
A label derived from Qt QLabel to display boolean values, strings, scalars and even vectors.
#include <qulineargauge.h>
Public Slots
void setSource (const QString &s)
Connect the reader to the specified source.
void unsetSource ()
Public Slots inherited from QuLinearGaugeBase
void setLabelPosition (LabelPosition p)
void setIndicatorType (IndicatorType t)
void setScaleMode (ScaleMode sm)
void setValue (double v)
void setReadError (bool re)
void setValue_anim (double v)
void setMinValue (double min)
void setMaxValue (double max)
void setLabel (const QString &l)
void setTicksCount (int t)
void setMinorTicksCount (int t)
void setTickLen (double tl)
Set the tick len as percentage of the radius of the circle.
void setGaugeWidth (double w)
void setArrowSize (double s)
sets the arrow size property
void setThermoWidth (double tw)
sets the thermoWidth property
void setPivotCircleRadius (double percent)
void setDrawBackgroundEnabled (bool en)
void setHighWarning (double w)
void setLowWarning (double w)
void setHighError (double e)
void setLowError (double e)
void setTextColor (const QColor &c)
void setErrorColor (const QColor &ec)
void setWarningColor (const QColor &wc)
void setNormalColor (const QColor &nc)
void setReadErrorColor (const QColor &rec)
void setBackgroundColor (const QColor &bc)
void setNeedleColor (const QColor &c)
void setNeedleGuideColor (const QColor &c)
void setArrowColor (const QColor &c)
sets the arrow fill color
void setThermoColor1 (const QColor &c)
changes the color 1 of the gradient used to draw the bar of a Thermo indicator
void setThermoColor2 (const QColor &c)
changes the color 2 of the gradient used to draw the bar of a Thermo indicator
void setThermoPenColor (const QColor &c)
changes the color used to outline the thermometer bar
void setArrowPenWidth (double pw)
void setTickCoreColor (const QColor &c)
void setBackgroundGradientSpread (double s)
If background drawing is enabled, the spread determines the stop point of the gradient from the current value color (normal, warning or error) and the background color.
void setBackgroundColorAlpha (int a)
void setDrawTickCore1 (bool t)
void setDrawTickCore2 (bool t)
void setDrawColoredTicks (bool dr)
void setDrawText (bool dt)
void setAnimationEnabled (bool ae)
void setMaxAnimationDuration (qint64 millis)
void setLabelValueFormat (const QString &f)
void setUnit (const QString &u)
void setLabelFontScale (double factor)
changes the label font size respect to the size of the text on the gauge
void setFormat (const QString &f)
sets the format to be used on the text along the gauge if the property formatFromProperty enabled is false
void setFormatFromPropertyEnabled (bool ffp)
enables or disables applying format from the configuration CuData
void setFormatProperty (const QString &fp)
sets the format of the text along the gauge to be used when formatFromPropertyEnabled is true
void updateLabelsCache ()
void regenerateCache ()
void updatePaintArea ()
void updateLabelsFontSize ()
Signals
void newData (const CuData &)
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
Public Member Functions
QuLinearGauge (QWidget *w, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuLinearGauge (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuLinearGauge ()
QString source () const
CuContext * getContext () const
returns the pointer to the CuContext
void onUpdate (const CuData &d)
Public Member Functions inherited from QuLinearGaugeBase
QuLinearGaugeBase (QWidget *parent=nullptr)
virtual ~QuLinearGaugeBase ()
LabelPosition labelPosition () const
IndicatorType indicatorType () const
ScaleMode scaleMode () const
double value () const
bool readError () const
double value_anim () const
double maxValue () const
double minValue () const
int ticksCount () const
int minorTicksCount () const
double tickLen () const
double gaugeWidth () const
double arrowSize () const
double thermoWidth () const
double pivotCircleRadius () const
bool drawBackgroundEnabled () const
returns true if a background is drawn, false otherwise
bool drawText () const
bool drawTickCore1 () const
bool drawTickCore2 () const
bool drawColoredTicks () const
bool animationEnabled () const
qint64 maxAnimationDuration () const
double labelFontScale () const
double lowWarning ()
double highWarning ()
double lowError ()
double highError ()
QColor textColor () const
QColor warningColor () const
QColor errorColor () const
QColor normalColor () const
QColor readErrorColor () const
QColor backgroundColor () const
QColor needleColor () const
QColor needleGuideColor () const
QColor tickCoreColor () const
QColor arrowColor () const
QColor thermoColor1 () const
QColor thermoColor2 () const
QColor thermoPenColor () const
double arrowPenWidth () const
double backgroundGradientSpread () const
int backgroundColorAlpha () const
Qt::Orientation orientation () const
QString label () const
QString format () const
bool formatFromPropertyEnabled () const
QString getAppliedFormat () const
QString labelValueFormat () const
QString unit () const
double mapTo (double val, const QRectF &paint_area=QRectF())
maps a value to a point along the longest side of the widget rectangle
QRectF textRect (const QRectF &paintArea, int tick)
double labelFontSize ()
virtual QString formatLabel (double val, const char *format) const
QString label (int i) const
QRectF paintArea ()
QSize sizeHint () const
QSize minimumSizeHint () const
bool inWarningRange (double val) const
bool inErrorRange (double val) const
QColor valueColor (double val) const
QRectF labelRect () const
returns the bounding rect of the label or an empty rectangle if the label is not visible
double getGaugeWidth (const QRectF &paint_area) const
returns the gauge width in pixels
double getThermoWidth (const QRectF &paint_area) const
returns the thermometer bar width in pixels
double getTickLen (const QRectF &paint_area) const
returns the (major) tick length, in pixels
QRectF freeSpace (const QRectF &paint_area) const
returns the free area available for custom drawings within the widget
QRectF gaugeRect (const QRectF &paint_area) const
returns the bounding rect of the gauge (union of gauge bar, ticks and text labels)
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e)
Protected Member Functions inherited from QuLinearGaugeBase
void paintEvent (QPaintEvent *pe)
virtual void drawText (const QRectF &re, int idx, QPainter &p)
virtual void drawNeedle (double pos, const QRectF &rect, QPainter &p)
Draw the needle.
virtual void drawGauge (const QRectF &rect, QPainter &p)
virtual void drawTicks (const QRectF &rect, QPainter &p)
virtual void drawBackground (const QRectF &rect, QPainter &p)
virtual void drawLabel (const QRectF &rect, QPainter &p)
void resizeEvent (QResizeEvent *re)
void changeEvent (QEvent *e)
Properties
QString source
Properties inherited from QuLinearGaugeBase
ScaleMode scaleMode
IndicatorType indicatorType
double value
double value_anim
returns the value during the animation
double minValue
returns the minimum value represented by this gauge
double maxValue
returns the maximum value represented by this gauge
bool drawText
either draw or not the labels with the values associated to each major tick
bool animationEnabled
if true, an animation is used to draw the transition between two subsequent setValue calls
qint64 maxAnimationDuration
The maximum duration of an animation between two setValue calls.
double lowWarning
double highWarning
double lowError
double highError
int ticksCount
returns the number of major ticks drawn in the arc
int minorTicksCount
returns the number of minor ticks drawn between each couple of major ticks
double tickLen
returns the tick length
double pivotCircleRadius
the factor multiplies tickLen to obtain the radius for the circle drawn at the base of the needle.
double gaugeWidth
returns the width of the gauge strip
bool drawBackground
bool drawTickCore1
draw a tick inside the gauge arc
bool drawTickCore2
draw a tick from the inner border of the gauge arc
bool drawColoredTicks
draw colored ticks
double arrowSize
returns the arrow size, percentage
double thermoWidth
returns the width of the thermometer bar, when indicatorMode is set to Thermo
QString format
bool formatFromPropertyEnabled
QColor textColor
QColor warningColor
QColor tickCoreColor
QColor errorColor
QColor normalColor
QColor readErrorColor
QColor backgroundColor
QColor needleColor
QColor needleGuideColor
returns the color of the needle guide, that is drawn along the longest widget side and crosses the needle pivot center
QColor arrowColor
returns the arrow fill color.
QColor thermoColor1
Sets the color 1 (inner color) used to draw the gradient for the thermo bar.
QColor thermoColor2
Sets the color 2 (outer color) used to draw the gradient for the thermo bar.
QColor thermoPenColor
returns the pen color used to outline the thermometer bar in the gauge indicator
double arrowPenWidth
int backgroundColorAlpha
double backgroundGradientSpread
QString label
LabelPosition labelPosition
QString labelValueFormat
QString unit
double labelFontScale
scales the label font respect to the font size of the text on the gauge
Additional Inherited Members
Public Types inherited from QuLinearGaugeBase
enum LabelPosition { NoLabel, East, Center, West }
enum ScaleMode { Normal, Inverted }
enum IndicatorType { Needle, Thermo }
Detailed Description
A label derived from Qt QLabel to display boolean values, strings, scalars and even vectors.
Colors and strings can be associated to boolean values.
Scalar numbers and strings can be displayed by QuLinearGauge.
Vectors are usually displayed only partially, according to the number of maximum characters allowed by setMaximumLength
Connection is initiated with setSource. When new data arrives, it is displayed and the newData convenience signal is emitted.
getContext returns a pointer to the CuContext used as a delegate for the connection.
Constructor & Destructor Documentation
QuLinearGauge() [1/2]
QuLinearGauge::QuLinearGauge (QWidget * w, Cumbia * cumbia, const CuControlsReaderFactoryI & r_factory)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuLinearGauge() [2/2]
QuLinearGauge::QuLinearGauge (QWidget * w, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuLinearGauge()
QuLinearGauge::~QuLinearGauge () virtual
Member Function Documentation
contextMenuEvent()
void QuLinearGauge::contextMenuEvent (QContextMenuEvent * e) protected
getContext()
CuContext * QuLinearGauge::getContext () const virtual
returns the pointer to the CuContext
CuContext sets up the connection and is used as a mediator to send and get data to and from the reader.
See also
CuContext
Implements CuContextI.
linkStatsRequest
void QuLinearGauge::linkStatsRequest (QWidget * myself, CuContextI * myself_as_cwi) signal
newData
void QuLinearGauge::newData (const CuData &) signal
Referenced by onUpdate().
onUpdate()
void QuLinearGauge::onUpdate (const CuData & d)
References newData(), and QuLinearGaugeBase::setReadError().
setSource
void QuLinearGauge::setSource (const QString & s) slot
Connect the reader to the specified source.
If a reader with a different source is configured, it is deleted. If options have been set with QuContext::setOptions, they are used to set up the reader as desired.
See also
QuContext::setOptions
source
References CuControlsReaderA::setSource().
source()
QString QuLinearGauge::source () const
unsetSource
void QuLinearGauge::unsetSource () slot
Property Documentation
source
QString QuLinearGauge::source read write
The documentation for this class was generated from the following files:
qulineargauge.h
qulineargauge.cpp