cumbia-qtcontrols: QmlReaderBackend Class Reference
QmlReaderBackend Class Reference
#include <qmlreaderbackend.h>
Public Types
enum DataType { Int , Double , String , Boolean }
enum DataFormat { Scalar , Vector }
Public Slots
void setSource (const QString &s)
void unsetSource ()
Signals
void newData (const CuData &)
void valueChanged ()
void sourceChanged ()
void minChanged ()
void maxChanged ()
void min_warningChanged ()
void max_warningChanged ()
void min_alarmChanged ()
void max_alarmChanged ()
void labelChanged ()
void stateColorChanged (const QString &color)
void qualityColorChanged (const QString &color)
Public Member Functions
QmlReaderBackend (QObject *parent=nullptr)
Q_INVOKABLE void init (CumbiaPool_O *poo_o)
Q_INVOKABLE void setConversionMode (DataType dt, DataFormat fmt)
Q_INVOKABLE QString getQualityColor (double val)
Q_INVOKABLE void suspend ()
Q_INVOKABLE void start ()
virtual ~QmlReaderBackend ()
QString source () const
CuContext * getContext () const
Return a reference to the CuContext in use.
QVariant value () const
QVariant min () const
QVariant max () const
QVariant min_warning () const
QVariant max_warning () const
QVariant min_alarm () const
QVariant max_alarm () const
QString label () const
QString stateColor () const
QString qualityColor () const
void onUpdate (const CuData &d)
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
QVariant value
QVariant min
QVariant max
QVariant min_warning
QVariant max_warning
QVariant min_alarm
QVariant max_alarm
QString source
QString label
QString stateColor
QString qualityColor
Member Enumeration Documentation
DataFormat
enum QmlReaderBackend::DataFormat
Enumerator
Scalar
Vector
DataType
enum QmlReaderBackend::DataType
Enumerator
Int
Double
String
Boolean
Constructor & Destructor Documentation
QmlReaderBackend()
QmlReaderBackend::QmlReaderBackend (QObject * parent = nullptr)
~QmlReaderBackend()
QmlReaderBackend::~QmlReaderBackend () virtual
Member Function Documentation
getContext()
CuContext * QmlReaderBackend::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
getQualityColor()
QString QmlReaderBackend::getQualityColor (double val)
References min_alarm, and min_warning.
init()
void QmlReaderBackend::init (CumbiaPool_O * poo_o)
References CumbiaPool_O::getFactory(), CumbiaPool_O::getPool(), CuControlsFactoryPool::isEmpty(), and setSource().
label()
QString QmlReaderBackend::label () const
labelChanged
void QmlReaderBackend::labelChanged () signal
max()
QVariant QmlReaderBackend::max () const
max_alarm()
QVariant QmlReaderBackend::max_alarm () const
max_alarmChanged
void QmlReaderBackend::max_alarmChanged () signal
max_warning()
QVariant QmlReaderBackend::max_warning () const
max_warningChanged
void QmlReaderBackend::max_warningChanged () signal
maxChanged
void QmlReaderBackend::maxChanged () signal
min()
QVariant QmlReaderBackend::min () const
min_alarm()
QVariant QmlReaderBackend::min_alarm () const
min_alarmChanged
void QmlReaderBackend::min_alarmChanged () signal
min_warning()
QVariant QmlReaderBackend::min_warning () const
min_warningChanged
void QmlReaderBackend::min_warningChanged () signal
minChanged
void QmlReaderBackend::minChanged () signal
newData
void QmlReaderBackend::newData (const CuData &) signal
Referenced by onUpdate().
onUpdate()
void QmlReaderBackend::onUpdate (const CuData & d)
References newData(), qualityColorChanged(), and stateColorChanged().
qualityColor()
QString QmlReaderBackend::qualityColor () const
qualityColorChanged
void QmlReaderBackend::qualityColorChanged (const QString & color) signal
Referenced by onUpdate().
setConversionMode()
void QmlReaderBackend::setConversionMode (QmlReaderBackend::DataType dt, QmlReaderBackend::DataFormat fmt)
setSource
void QmlReaderBackend::setSource (const QString & s) slot
References sourceChanged().
Referenced by init().
source()
QString QmlReaderBackend::source () const
References CuControlsReaderA::source().
sourceChanged
void QmlReaderBackend::sourceChanged () signal
Referenced by setSource().
start()
void QmlReaderBackend::start ()
stateColor()
QString QmlReaderBackend::stateColor () const
stateColorChanged
void QmlReaderBackend::stateColorChanged (const QString & color) signal
Referenced by onUpdate().
suspend()
void QmlReaderBackend::suspend ()
unsetSource
void QmlReaderBackend::unsetSource () slot
value()
QVariant QmlReaderBackend::value () const
valueChanged
void QmlReaderBackend::valueChanged () signal
Property Documentation
label
QString QmlReaderBackend::label read
max
QVariant QmlReaderBackend::max read
max_alarm
QVariant QmlReaderBackend::max_alarm read
max_warning
QVariant QmlReaderBackend::max_warning read
min
QVariant QmlReaderBackend::min read
min_alarm
QVariant QmlReaderBackend::min_alarm read
Referenced by getQualityColor().
min_warning
QVariant QmlReaderBackend::min_warning read
Referenced by getQualityColor().
qualityColor
QString QmlReaderBackend::qualityColor read
source
QString QmlReaderBackend::source read write
stateColor
QString QmlReaderBackend::stateColor read
value
QVariant QmlReaderBackend::value read
The documentation for this class was generated from the following files:
qmlreaderbackend.h
qmlreaderbackend.cpp