cumbia-qtcontrols: EImageWidget Class Reference
EImageWidget Class Reference
Display widgets » Image widget
A QWidget to display two dimensional arrays as an image.
#include <eimagewidget.h>
Public Slots
void setImage (const QImage &image)
sets the image img on the widget.
void setErrorImage (const QImage &img)
sets an image that is displayed if an error occurs
void setErrorMessage (const QString &msg)
set an error string
void setError (bool error)
set the error flag
void setOk (bool ok)
sets the ok flag
void execConfigDialog ()
void setScaleWithZoom (bool scale)
Public Member Functions
EImageWidget (QWidget *parent=0)
the class constructor
virtual ~EImageWidget ()
bool scaleWithZoom () const
QImage errorImage () const
Public Member Functions inherited from EImageWidgetBase
EImageWidgetBase (QWidget *widget, bool isOpenGL)
virtual ~EImageWidgetBase ()
QImage & image () const
void setImageMouseEventInterface (ImageMouseEventInterface *ifa)
void setError (bool error)
void setColorTable (const QVector< QRgb > &rgb)
void setErrorMessage (const QString &msg)
void setZoom (int n)
void setZoomEnabled (bool en)
bool isOpenGL () const
void setErrorImage (const QImage &i)
QVector< QRgb > & colorTable () const
bool zoomEnabled () const
float zoom () const
void setImage (const QImage &image)
QImage errorImage () const
Protected Member Functions
QSize minimumSizeHint () const
QSize sizeHint () const
void paintEvent (QPaintEvent *)
void mousePressEvent (QMouseEvent *ev)
void mouseMoveEvent (QMouseEvent *ev)
void mouseReleaseEvent (QMouseEvent *ev)
void wheelEvent (QWheelEvent *we)
virtual QMenu * rightClickMenu ()
the right click menu allows to execute a configuration dialog.
Protected Member Functions inherited from EImageWidgetBase
void mouseMove (QMouseEvent *e)
void mousePress (QMouseEvent *e)
void mouseRelease (QMouseEvent *e)
void wheelEvent (QWheelEvent *event)
void paint (QPaintEvent *e, QWidget *paintDevice)
void execConfigDialog ()
Properties
bool scaleWithZoom
QImage errorImage
returns the QImage used as error image
Detailed Description
A QWidget to display two dimensional arrays as an image.
Constructor & Destructor Documentation
EImageWidget()
EImageWidget::EImageWidget (QWidget * parent = 0) explicit
the class constructor
Parameters
parent a QWidget as a parent of this widget
~EImageWidget()
EImageWidget::~EImageWidget () virtual
Member Function Documentation
errorImage()
QImage EImageWidget::errorImage () const
execConfigDialog
void EImageWidget::execConfigDialog () slot
References EImageWidgetBase::execConfigDialog().
Referenced by rightClickMenu().
minimumSizeHint()
QSize EImageWidget::minimumSizeHint () const protected
References EImageWidgetBase::image().
mouseMoveEvent()
void EImageWidget::mouseMoveEvent (QMouseEvent * ev) protected
References EImageWidgetBase::mouseMove().
mousePressEvent()
void EImageWidget::mousePressEvent (QMouseEvent * ev) protected
References EImageWidgetBase::mousePress().
mouseReleaseEvent()
void EImageWidget::mouseReleaseEvent (QMouseEvent * ev) protected
References EImageWidgetBase::mouseRelease().
paintEvent()
void EImageWidget::paintEvent (QPaintEvent * e) protected
References EImageWidgetBase::paint().
rightClickMenu()
QMenu * EImageWidget::rightClickMenu () protected virtual
the right click menu allows to execute a configuration dialog.
Returns
a QMenu with a "Change color map" action that executes execConfigDialog when triggered.
References execConfigDialog().
scaleWithZoom()
bool EImageWidget::scaleWithZoom () const
setError
void EImageWidget::setError (bool error) slot
set the error flag
Parameters
error sets an error condition
References EImageWidgetBase::setError().
Referenced by setOk().
setErrorImage
void EImageWidget::setErrorImage (const QImage & img) slot
sets an image that is displayed if an error occurs
Parameters
img an image displayed when an error occurs
References EImageWidgetBase::setErrorImage().
setErrorMessage
void EImageWidget::setErrorMessage (const QString & msg) slot
set an error string
Parameters
msg an error string that will be displayed on the image if an error occurs
References EImageWidgetBase::setErrorMessage().
setImage
void EImageWidget::setImage (const QImage & img) slot
sets the image img on the widget.
Parameters
img the image that will be displayed.
If the scaleWithZoom property is true, the geometry of the widget is scaled according to the image size multiplied by the zoom factor (zoom / 100.0)
References EImageWidgetBase::image(), EImageWidgetBase::setImage(), and EImageWidgetBase::zoom().
Referenced by wheelEvent().
setOk
void EImageWidget::setOk (bool ok) slot
sets the ok flag
calls setError with !ok
References setError().
setScaleWithZoom
void EImageWidget::setScaleWithZoom (bool scale) slot
sizeHint()
QSize EImageWidget::sizeHint () const protected
References EImageWidgetBase::image().
wheelEvent()
void EImageWidget::wheelEvent (QWheelEvent * we) protected
References EImageWidgetBase::image(), setImage(), and EImageWidgetBase::wheelEvent().
Property Documentation
errorImage
QImage EImageWidget::errorImage read write
returns the QImage used as error image
Returns
a QImage that is displayed when an error occurs
The error image can be changed with setErrorImage
scaleWithZoom
bool EImageWidget::scaleWithZoom read write
The documentation for this class was generated from the following files:
eimagewidget.h
eimagewidget.cpp