cumbia-qtcontrols: ENumeric Class Reference
ENumeric Class Reference
a widget to set a value
#include <enumeric.h>
Public Slots
virtual void setEnabled (bool)
virtual void setDisabled (bool)
Signals
void valueChanged (double)
Public Member Functions
ENumeric (QWidget *parent, int intDigits=3, int decDigits=1)
~ENumeric ()
void setValue (double v)
void silentSetValue (double v)
double value () const
void setMaximum (double v)
double maximum () const
void setMinimum (double v)
double minimum () const
void setIntDigits (int i)
int intDigits () const
void setDecDigits (int d)
int decDigits () const
virtual QSize sizeHint () const
virtual QSize minimumSizeHint () const
int neededWidth () const
int neededHeight () const
Protected Slots
void resizeEvent (QResizeEvent *)
Protected Member Functions
virtual void showEvent (QShowEvent *)
Properties
int integerDigits
int decimalDigits
double value
double maximum
double minimum
Detailed Description
a widget to set a value
this widget is used to set a value, whenever the displayed value changes the signal valueChanged(double) is emitted
Constructor & Destructor Documentation
ENumeric()
ENumeric::ENumeric (QWidget * parent, int intDigits = 3, int decDigits = 1)
constructor
Parameters
intDigits number of integer digits
decDigits number of decimal digits
~ENumeric()
ENumeric::~ENumeric () inline
Member Function Documentation
decDigits()
int ENumeric::decDigits () const inline
returns number of decimal digits displayed
Returns
d number of digits
Referenced by EApplyNumeric::decDigits().
intDigits()
int ENumeric::intDigits () const inline
returns number of integer digits displayed
Returns
i number of digits
Referenced by EApplyNumeric::intDigits().
maximum()
double ENumeric::maximum () const inline
returns the maximum value of the widget
Returns
max val
minimum()
double ENumeric::minimum () const inline
returns the minimum value of the widget
Returns
min val
minimumSizeHint()
QSize ENumeric::minimumSizeHint () const virtual
References neededHeight(), and neededWidth().
Referenced by EApplyNumeric::minimumSizeHint().
neededHeight()
int ENumeric::neededHeight () const
Referenced by minimumSizeHint(), and sizeHint().
neededWidth()
int ENumeric::neededWidth () const
Referenced by minimumSizeHint(), and sizeHint().
resizeEvent
void ENumeric::resizeEvent (QResizeEvent * e) protected slot
References MARGIN, and MIN_MARGIN.
setDecDigits()
void ENumeric::setDecDigits (int d)
sets number of deciam digits to be displayed
Parameters
d number of digits
References setMaximum(), and setMinimum().
Referenced by EApplyNumeric::setDecDigits().
setDisabled
void ENumeric::setDisabled (bool b) virtual slot
setEnabled
void ENumeric::setEnabled (bool b) virtual slot
setIntDigits()
void ENumeric::setIntDigits (int i)
sets number of integer digits to be displayed
Parameters
i number of digits
Referenced by EApplyNumeric::setIntDigits().
setMaximum()
void ENumeric::setMaximum (double v)
sets the maximum value of the widget
Parameters
v max val
Referenced by setDecDigits(), and EApplyNumeric::setMaximum().
setMinimum()
void ENumeric::setMinimum (double v)
sets the minimum value of the widget
Parameters
v min val
Referenced by setDecDigits(), and EApplyNumeric::setMinimum().
setValue()
void ENumeric::setValue (double v)
sets value displayed by the widget
Parameters
v the value to be displayed
References valueChanged().
Referenced by EApplyNumeric::setValue().
showEvent()
void ENumeric::showEvent (QShowEvent * e) protected virtual
silentSetValue()
void ENumeric::silentSetValue (double v)
same as setValue(), but does not emit valueChanged() signal. Used by QTango TNumeric widget when automatically configured, to initialize a value on the apply numeric widget without causing a signal to be emitted.
sizeHint()
QSize ENumeric::sizeHint () const virtual
References neededHeight(), and neededWidth().
Referenced by EApplyNumeric::sizeHint().
value()
double ENumeric::value () const inline
returns the value displayed by the widget
Returns
the value displayed
valueChanged
void ENumeric::valueChanged (double) signal
Referenced by setValue().
Property Documentation
decimalDigits
int ENumeric::decimalDigits read write
integerDigits
int ENumeric::integerDigits read write
maximum
double ENumeric::maximum read write
Referenced by EApplyNumeric::maximum().
minimum
double ENumeric::minimum read write
Referenced by EApplyNumeric::minimum().
value
double ENumeric::value read write
Referenced by EApplyNumeric::applyValue(), and EApplyNumeric::value().
The documentation for this class was generated from the following files:
enumeric.h
enumeric.cpp