cumbia-qtcontrols: QuPlotCurve Class Reference
QuPlotCurve Class Reference
Display widgets » Plots
QwtPlot derived curve used in QuPlotBase.
#include <quplotcurve.h>
Public Types
enum State { Normal, Invalid }
Public Member Functions
QuPlotCurve ()
QuPlotCurve (const QwtText &title)
Constructor of EPlotCurve.
QuPlotCurve (const QString &title)
Constructor of EPlotCurve.
~QuPlotCurve ()
void appendData (double *x, double *y, int count)
appends x axis data and y axis data of a given size to the curve data.
void insertData (double *x, double *y, int count, double default_y=0.0)
insert data ordered by x
void setData (const QVector< double > &xData, const QVector< double > &yData)
void popFront ()
void updateRawData ()
takes its data and sets it as raw data on the curve for subsequent drawing
void setVectorUpdateMode (bool vum)
void clearData ()
int count () const
State state () const
void setState (State s)
QString text (const double &x) const
void setText (const double &x, const QString &txt)
void drawCurve (QPainter *p, int style, const QwtScaleMap &xMap, const QwtScaleMap &yMap, const QRectF &canvasRect, int from, int to) const
one of the drawing methods.
virtual int rtti () const
double x (int index) const
double y (int index) const
size_t size () const
double lastValue () const
Detailed Description
QwtPlot derived curve used in QuPlotBase.
Member Enumeration Documentation
State
enum QuPlotCurve::State
Enumerator
Normal
Invalid
Constructor & Destructor Documentation
QuPlotCurve() [1/3]
QuPlotCurve::QuPlotCurve ()
Constructor
QuPlotCurve() [2/3]
QuPlotCurve::QuPlotCurve (const QwtText & title)
Constructor of EPlotCurve.
Parameters
title the title of the curve.
QuPlotCurve() [3/3]
QuPlotCurve::QuPlotCurve (const QString & title)
Constructor of EPlotCurve.
Parameters
title the title of the curve.
~QuPlotCurve()
QuPlotCurve::~QuPlotCurve ()
Member Function Documentation
appendData()
void QuPlotCurve::appendData (double * x, double * y, int count)
appends x axis data and y axis data of a given size to the curve data.
Parameters
x pointer to a double array of x axis data of size count
y pointer to a double array of y axis data of size count
count number of elements of the x and y arrays
One may consider calling updateRawData() before drawing the curve
References count(), size(), x(), and y().
Referenced by QuPlotBase::appendData().
clearData()
void QuPlotCurve::clearData ()
Referenced by QuPlotBase::clearPlot().
count()
int QuPlotCurve::count () const
Referenced by appendData(), QuPlotBase::appendData(), drawCurve(), insertData(), and QuPlotBase::insertData().
drawCurve()
void QuPlotCurve::drawCurve (QPainter * p, int style, const QwtScaleMap & xMap, const QwtScaleMap & yMap, const QRectF & canvasRect, int from, int to) const
one of the drawing methods.
This method is invoked to draw the curve from the point from to the point to. When data is appended, the method is normally called with from and to reflecting the distance between the point added and the previous point. When from == 0 and to == -1, then a full redraw is requested. When the state of the curve is Invalid, a certain number of markers, according to the value of the defined MAX_STATE_SYMBOLS, is drawn. In the case of the invalid state, all the symbols are redrawn on the full curve, whether a full draw is requested or not. On the other side, when d->showYValuesEnabled is true, only the requested labels are drawn, according to the value of from and to, eventually all the labels in case of from == 0 and to == -1.
References Elettra::black, count(), Invalid, KDARKRED, MAX_STATE_SYMBOLS, Elettra::red, STATE_SYMBOL_SIZE, Elettra::white, x(), and y().
insertData()
void QuPlotCurve::insertData (double * x, double * y, int count, double default_y = 0.0)
insert data ordered by x
Parameters
x vector of x values (typically time scale values)
y vector of values
count number of elements of x and y
References count(), size(), x(), and y().
Referenced by QuPlotBase::insertData().
lastValue()
double QuPlotCurve::lastValue () const
Referenced by QuTrendPlot::update().
popFront()
void QuPlotCurve::popFront ()
Referenced by QuPlotBase::appendData(), and QuPlotBase::insertData().
rtti()
virtual int QuPlotCurve::rtti () const inline virtual
References RTTI_CURVE_OFFSET.
setData()
void QuPlotCurve::setData (const QVector< double > & xData, const QVector< double > & yData)
Referenced by QuPlotBase::setData().
setState()
void QuPlotCurve::setState (QuPlotCurve::State s)
Referenced by QuSpectrumPlot::update(), and QuTrendPlot::update().
setText()
void QuPlotCurve::setText (const double & x, const QString & txt)
References x().
Referenced by QuTrendPlot::update().
setVectorUpdateMode()
void QuPlotCurve::setVectorUpdateMode (bool vum)
to force vector update mode
size()
size_t QuPlotCurve::size () const
Referenced by appendData(), insertData(), and QuTrendPlot::update().
state()
QuPlotCurve::State QuPlotCurve::state () const
text()
QString QuPlotCurve::text (const double & x) const
References x().
Referenced by QuPlotMarkerComponent::markerText().
updateRawData()
void QuPlotCurve::updateRawData ()
takes its data and sets it as raw data on the curve for subsequent drawing
Referenced by QuPlotBase::appendData(), and QuPlotBase::insertData().
x()
double QuPlotCurve::x (int index) const
Referenced by appendData(), drawCurve(), insertData(), setText(), text(), and QuTrendPlot::update().
y()
double QuPlotCurve::y (int index) const
Referenced by appendData(), drawCurve(), insertData(), and QuPlotMarkerComponent::markerText().
The documentation for this class was generated from the following files:
quplotcurve.h
quplotcurve.cpp