cumbia-qtcontrols: QuLed Class Reference
QuLed Class Reference
Display widgets
a led that takes a color according to a value read from a source.
#include <quled.h>
Public Slots
void setSource (const QString &s)
void unsetSource ()
Signals
void newData (const CuData &)
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
Public Member Functions
QuLed (QWidget *w, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuLed (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuLed ()
the class destructor
QString source () const
CuContext * getContext () const
Return a reference to the CuContext in use.
void setQuPalette (const QuPalette &colors)
change the association between color names and color values
QuPalette quPalette () const
returns the QuPalette in use
void onUpdate (const CuData &d)
Public Member Functions inherited from QuLedBase
QuLedBase (QWidget *)
virtual ~QuLedBase ()
void setColor (const QColor &, bool=true)
QColor color ()
int angle ()
void setAngle (int angle)
void setLedWidth (int)
void setLedHeight (int)
int ledWidth ()
int ledHeight ()
bool rectangular ()
void setRectangular (bool re)
void setAlphaChannel (int a)
int alphaChannel ()
bool gradientEnabled ()
void setGradientEnabled (bool grad)
bool linearGradient ()
void setLinearGradient (bool l)
double gradientStop ()
fine tunes the gradient end point.
void setGradientStop (double val)
changes the gradient stop point
double gradientStart ()
fine tunes the gradient end point.
void setGradientStart (double val)
changes the gradient start point
bool scaleContents ()
returns the scaleContents property.
void setScaleContents (bool s)
changes the property scaleContents
void setBorderColor (const QColor &c)
QColor borderColor () const
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e)
Protected Member Functions inherited from QuLedBase
virtual void paintEvent (QPaintEvent *)
virtual QSize sizeHint () const
virtual QSize minimumSizeHint () const
Properties
QString source
Properties inherited from QuLedBase
bool rectangular
bool gradientEnabled
int ledWidth
int ledHeight
int angle
int alphaChannel
bool linearGradient
bool scaleContents
double gradientStop
double gradientStart
Detailed Description
a led that takes a color according to a value read from a source.
The class derives from QuLedBase. Several configuration options for the shape and color mode of the led can be set through QuLedBase interface.
CuContext is used to communicate through a given engine with the source of data.
Constructor & Destructor Documentation
QuLed() [1/2]
QuLed::QuLed (QWidget * w, Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuLed() [2/2]
QuLed::QuLed (QWidget * w, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuLed()
QuLed::~QuLed () virtual
the class destructor
deletes the CuContext
Member Function Documentation
contextMenuEvent()
void QuLed::contextMenuEvent (QContextMenuEvent * e) protected
getContext()
CuContext * QuLed::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
linkStatsRequest
void QuLed::linkStatsRequest (QWidget * myself, CuContextI * myself_as_cwi) signal
newData
void QuLed::newData (const CuData &) signal
Referenced by onUpdate().
onUpdate()
void QuLed::onUpdate (const CuData & d)
References Elettra::gray, newData(), QuLedBase::setBorderColor(), and QuLedBase::setColor().
quPalette()
QuPalette QuLed::quPalette () const
returns the QuPalette in use
See also
QuLabel::quPalette
setQuPalette
setQuPalette()
void QuLed::setQuPalette (const QuPalette & colors)
change the association between color names and color values
The QuLed behavior is equivalent to QuLabel's
See also
QuLabel::setQuPalette
quPalette
setSource
void QuLed::setSource (const QString & s) slot
References CuControlsReaderA::setSource().
source()
QString QuLed::source () const
unsetSource
void QuLed::unsetSource () slot
Property Documentation
source
QString QuLed::source read write
The documentation for this class was generated from the following files:
quled.h
quled.cpp