cumbia-qtcontrols: QuCircularGaugeBase Class Reference
QuCircularGaugeBase Class Reference
#include <qucirculargaugebase.h>
Public Types
enum Quads {
q1, q2, q3, q4,
q21, q43, q32, q14,
q432, q321, q214, q143,
q4321, q3214, q2143, q1432
}
enum LabelPosition {
NoLabel, North, NorthEast, East,
SouthEast, South, SouthWest, West,
NorthWest
}
Public Slots
void setValue (double v)
void setReadError (bool err)
void setValue_anim (double v)
void setAngleStart (int as)
set the start angle of the arc, in degrees, from 6 o'clock
void setAngleSpan (int a)
set the span of the arc of the gauge
void setMinValue (double min)
void setMaxValue (double max)
void setLabel (const QString &l)
void setTicksCount (int t)
void setMinorTicksCount (int t)
void setTickLen (double tl)
Set the tick len as percentage of the radius of the circle.
void setGaugeWidth (double w)
void setPivotCircleRadius (double percent)
void setDrawBackgroundEnabled (bool en)
void setHighWarning (double w)
void setLowWarning (double w)
void setHighError (double e)
void setLowError (double e)
void setTextColor (const QColor &c)
void setErrorColor (const QColor &ec)
void setWarningColor (const QColor &wc)
void setNormalColor (const QColor &nc)
void setReadErrorColor (const QColor &rec)
void setBackgroundColor (const QColor &bc)
void setNeedleColor (const QColor &c)
void setTickCoreColor (const QColor &c)
void setBackgroundGradientSpread (double s)
If background drawing is enabled, the spread determines the stop point of the gradient from the current value color (normal, warning or error) and the background color.
void setBackgroundColorAlpha (int a)
void setDrawTickCore1 (bool t)
void setDrawTickCore2 (bool t)
void setDrawColoredTicks (bool dr)
void setDrawText (bool dt)
void setAnimationEnabled (bool ae)
void setMaxAnimationDuration (qint64 millis)
void setLabelPosition (LabelPosition p)
void setLabelDistFromCenter (double radius_percent)
void setLabelValueFormat (const QString &f)
void setUnit (const QString &u)
void setLabelFontScale (double factor)
changes the label font size respect to the automatically calculated size
void setFormat (const QString &f)
sets the format to be used on the text along the gauge if the property formatFromProperty enabled is false
void setFormatFromPropertyEnabled (bool ffp)
enables or disables applying format from the configuration CuData
void setFormatProperty (const QString &fp)
sets the format of the text along the gauge to be used when formatFromPropertyEnabled is true
QList< int > updateLabelsDistrib () const
get the labels distribution according to the shape of the gauge
void updateLabelsCache ()
void regenerateCache ()
void updatePaintArea ()
void updateLabelsFontSize ()
Public Member Functions
QuCircularGaugeBase (QWidget *parent=nullptr)
virtual ~QuCircularGaugeBase ()
double value () const
double value_anim () const
double maxValue () const
double minValue () const
int angleSpan () const
int angleStart () const
int ticksCount () const
int minorTicksCount () const
double tickLen () const
double gaugeWidth () const
double pivotCircleRadius () const
bool drawBackgroundEnabled () const
returns true if a background is drawn, false otherwise
bool drawText () const
bool drawTickCore1 () const
bool drawTickCore2 () const
bool drawColoredTicks () const
bool animationEnabled () const
bool readError () const
qint64 maxAnimationDuration () const
LabelPosition labelPosition () const
double labelDistFromCenter () const
double labelFontScale () const
double lowWarning ()
double highWarning ()
double lowError ()
double highError ()
QColor textColor () const
QColor warningColor () const
QColor errorColor () const
QColor normalColor () const
QColor readErrorColor () const
QColor backgroundColor () const
QColor needleColor () const
QColor tickCoreColor () const
double backgroundGradientSpread () const
int backgroundColorAlpha () const
double getPivotRadius ()
QString label () const
QString format () const
bool formatFromPropertyEnabled () const
QString getAppliedFormat () const
QString labelValueFormat () const
QString unit () const
QPointF mapTo (double val, int *angleSpan, double radius=-1.0, const QRectF &paint_area=QRectF())
maps a value to a point close to the arc of the gauge
QRectF textRect (int tick, double radius)
double labelFontSize ()
virtual QString formatLabel (double val, const QString &format) const
QString label (int i) const
QRectF paintArea ()
QSize sizeHint () const
QSize minimumSizeHint () const
bool inWarningRange (double val) const
Returns true if the value is within the warning range.
bool inErrorRange (double val) const
Returns true if the value is within the error range.
QColor valueColor (double val) const
returns the color associated to a value
void setCacheRegenerationDisabled (bool dis)
disables cache regeneration
bool cacheRegenerationDisabled () const
returns true if regenerateCache is disabled, false otherwise
Protected Member Functions
void paintEvent (QPaintEvent *pe)
virtual void drawText (const QRectF &rect, int idx, QPainter &p)
virtual void drawNeedle (const QPointF &end, int angleSpan, const QRectF &rect, QPainter &p)
Draw the needle.
virtual void drawGauge (const QRectF &rect, int startAngle, int span, QPainter &p)
virtual void drawPivot (const QRectF &rect, QPainter &p)
virtual void drawTicks (const QRectF &rect, QPainter &p)
virtual void drawBackground (const QRectF &rect, QPainter &p)
virtual void drawLabel (const QRectF &rect, QPainter &p)
void changeEvent (QEvent *e)
void resizeEvent (QResizeEvent *re)
Protected Attributes
QuGaugeConfig * g_config
Properties
double value
double value_anim
returns the value during the animation
double minValue
returns the minimum value represented by this gauge
double maxValue
returns the maximum value represented by this gauge
bool drawText
either draw or not the labels with the values associated to each major tick
bool animationEnabled
if true, an animation is used to draw the transition between two subsequent setValue calls
qint64 maxAnimationDuration
The maximum duration of an animation between two setValue calls.
double lowWarning
double highWarning
double lowError
double highError
int angleStart
returns the angle from which the gauge arc starts
int angleSpan
returns the span of the angle of the circular gauge, in degrees
int ticksCount
returns the number of major ticks drawn in the arc
int minorTicksCount
returns the number of minor ticks drawn between each couple of major ticks
double tickLen
returns the tick length
double pivotCircleRadius
If greater than zero, a circle is drawn on the pivot of the needle.
double gaugeWidth
returns the pen width used to draw the gauge arc
bool drawBackground
bool drawTickCore1
draw a tick inside the gauge arc
bool drawTickCore2
draw a tick from the inner border of the gauge arc
bool drawColoredTicks
draw colored ticks
QString format
bool formatFromPropertyEnabled
QColor textColor
QColor warningColor
QColor tickCoreColor
QColor errorColor
QColor normalColor
QColor readErrorColor
QColor backgroundColor
double backgroundGradientSpread
QColor needleColor
int backgroundColorAlpha
QString label
LabelPosition labelPosition
double labelDistFromCenter
QString labelValueFormat
QString unit
double labelFontScale
scales the label font respect to the automatically calculated size
Member Enumeration Documentation
LabelPosition
enum QuCircularGaugeBase::LabelPosition
Enumerator
NoLabel
North
NorthEast
East
SouthEast
South
SouthWest
West
NorthWest
Quads
enum QuCircularGaugeBase::Quads
Enumerator
q1
q2
q3
q4
q21
q43
q32
q14
q432
q321
q214
q143
q4321
q3214
q2143
q1432
Constructor & Destructor Documentation
QuCircularGaugeBase()
QuCircularGaugeBase::QuCircularGaugeBase (QWidget * parent = nullptr) explicit
References g_config, QuGaugeConfig::pivotRadius, and South.
~QuCircularGaugeBase()
QuCircularGaugeBase::~QuCircularGaugeBase () virtual
References g_config.
Member Function Documentation
angleSpan()
int QuCircularGaugeBase::angleSpan () const
angleStart()
int QuCircularGaugeBase::angleStart () const
animationEnabled()
bool QuCircularGaugeBase::animationEnabled () const
backgroundColor()
QColor QuCircularGaugeBase::backgroundColor () const
backgroundColorAlpha()
int QuCircularGaugeBase::backgroundColorAlpha () const
backgroundGradientSpread()
double QuCircularGaugeBase::backgroundGradientSpread () const
cacheRegenerationDisabled()
bool QuCircularGaugeBase::cacheRegenerationDisabled () const
returns true if regenerateCache is disabled, false otherwise
See also
setCacheRegenerationDisabled
changeEvent()
void QuCircularGaugeBase::changeEvent (QEvent * e) protected
References regenerateCache().
drawBackground()
void QuCircularGaugeBase::drawBackground (const QRectF & rect, QPainter & p) protected virtual
References QuGaugeConfig::backgroundColor, QuGaugeConfig::backgroundColorAlpha, QuGaugeConfig::backgroundGradientSpread, g_config, QuGaugeConfig::readErrorColor, QuGaugeConfig::value, and valueColor().
drawBackgroundEnabled()
bool QuCircularGaugeBase::drawBackgroundEnabled () const
returns true if a background is drawn, false otherwise
Returns
true the gauge draws a background with a radial gradient between the color associated the current value (see inErrorRange, inWarningRange, inNormalRange) and the color chosen with setBackgroundColor.
Three warning levels can be displayed by the gauge arc:
normal
warning
alarm (error)
Setting the drawBackgroundEnabled property to true enhances the detection of the current value quality.
See also
backgroundColor
References QuGaugeConfig::drawBackground, and g_config.
drawColoredTicks()
bool QuCircularGaugeBase::drawColoredTicks () const
drawGauge()
void QuCircularGaugeBase::drawGauge (const QRectF & rect, int startAngle, int span, QPainter & p) protected virtual
References QuGaugeConfig::errorColor, g_config, QuGaugeConfig::gaugeWidth, QuGaugeConfig::high_e, QuGaugeConfig::high_w, QuGaugeConfig::low_e, QuGaugeConfig::low_w, mapTo(), QuGaugeConfig::max, QuGaugeConfig::min, QuGaugeConfig::normalColor, QuGaugeConfig::readErrorColor, and QuGaugeConfig::warningColor.
Referenced by paintEvent().
drawLabel()
void QuCircularGaugeBase::drawLabel (const QRectF & rect, QPainter & p) protected virtual
References Elettra::black, East, formatLabel(), g_config, Elettra::gray, labelFontSize(), North, NorthEast, NorthWest, paintArea(), South, SouthEast, SouthWest, QuGaugeConfig::unit, QuGaugeConfig::value, and West.
Referenced by paintEvent().
drawNeedle()
void QuCircularGaugeBase::drawNeedle (const QPointF & end, int angle, const QRectF & rect, QPainter & p) protected virtual
Draw the needle.
This method can be reimplemented to draw custom needles
Parameters
end the end of the needle
angle the angle of the needle, zero at three o'clock
rect the bounding rect of the drawing area
p the painter
Note
In the default implementation, the needle starts from the center of the rect
References Elettra::darkGray, g_config, getPivotRadius(), QuGaugeConfig::needleColor, QuGaugeConfig::pivotRadius, and Elettra::white.
Referenced by paintEvent().
drawPivot()
void QuCircularGaugeBase::drawPivot (const QRectF & rect, QPainter & p) protected virtual
References Elettra::black, Elettra::darkGray, g_config, getPivotRadius(), and QuGaugeConfig::pivotRadius.
Referenced by paintEvent().
drawText() [1/2]
bool QuCircularGaugeBase::drawText () const
Referenced by paintEvent().
drawText() [2/2]
void QuCircularGaugeBase::drawText (const QRectF & rect, int idx, QPainter & p) protected virtual
References g_config, label(), labelFontSize(), paintArea(), QuGaugeConfig::textColor, textRect(), and QuGaugeConfig::tickLen.
drawTickCore1()
bool QuCircularGaugeBase::drawTickCore1 () const
drawTickCore2()
bool QuCircularGaugeBase::drawTickCore2 () const
drawTicks()
void QuCircularGaugeBase::drawTicks (const QRectF & rect, QPainter & p) protected virtual
References QuGaugeConfig::drawColoredTicks, QuGaugeConfig::drawTickCore1, QuGaugeConfig::drawTickCore2, QuGaugeConfig::errorColor, g_config, QuGaugeConfig::gaugeWidth, inErrorRange(), inWarningRange(), QuGaugeConfig::max, QuGaugeConfig::min, QuGaugeConfig::minorTicksCount, QuGaugeConfig::normalColor, QuGaugeConfig::tickCoreColor, QuGaugeConfig::tickLen, tickLen(), QuGaugeConfig::ticksCount, ticksCount(), and QuGaugeConfig::warningColor.
Referenced by paintEvent().
errorColor()
QColor QuCircularGaugeBase::errorColor () const
format()
QString QuCircularGaugeBase::format () const
Referenced by formatLabel().
formatFromPropertyEnabled()
bool QuCircularGaugeBase::formatFromPropertyEnabled () const
formatLabel()
QString QuCircularGaugeBase::formatLabel (double val, const QString & format) const virtual
References format(), and value().
Referenced by drawLabel(), and updateLabelsCache().
gaugeWidth()
double QuCircularGaugeBase::gaugeWidth () const
getAppliedFormat()
QString QuCircularGaugeBase::getAppliedFormat () const
References QuGaugeConfig::format, QuGaugeConfig::format_from_property, QuGaugeConfig::format_prop, and g_config.
Referenced by updateLabelsCache().
getPivotRadius()
double QuCircularGaugeBase::getPivotRadius ()
References g_config, paintArea(), and QuGaugeConfig::pivotRadius.
Referenced by drawNeedle(), and drawPivot().
highError()
double QuCircularGaugeBase::highError ()
highWarning()
double QuCircularGaugeBase::highWarning ()
inErrorRange()
bool QuCircularGaugeBase::inErrorRange (double val) const
Returns true if the value is within the error range.
Parameters
val the value
Returns
true if the val is within the error range, false otherwise
References g_config, QuGaugeConfig::high_e, and QuGaugeConfig::low_e.
Referenced by drawTicks(), and valueColor().
inWarningRange()
bool QuCircularGaugeBase::inWarningRange (double val) const
Returns true if the value is within the warning range.
Parameters
val the value
Returns
true if the val is within the warning range, false otherwise
References g_config, QuGaugeConfig::high_e, QuGaugeConfig::high_w, QuGaugeConfig::low_e, and QuGaugeConfig::low_w.
Referenced by drawTicks(), and valueColor().
label() [1/2]
QString QuCircularGaugeBase::label () const
Referenced by drawText().
label() [2/2]
QString QuCircularGaugeBase::label (int i) const
labelDistFromCenter()
double QuCircularGaugeBase::labelDistFromCenter () const
labelFontScale()
double QuCircularGaugeBase::labelFontScale () const
labelFontSize()
double QuCircularGaugeBase::labelFontSize ()
References regenerateCache().
Referenced by drawLabel(), and drawText().
labelPosition()
LabelPosition QuCircularGaugeBase::labelPosition () const
labelValueFormat()
QString QuCircularGaugeBase::labelValueFormat () const
lowError()
double QuCircularGaugeBase::lowError ()
lowWarning()
double QuCircularGaugeBase::lowWarning ()
mapTo()
QPointF QuCircularGaugeBase::mapTo (double val, int * angle, double radius = -1.0, const QRectF & paint_area = QRectF())
maps a value to a point close to the arc of the gauge
Returns
a QPointF close to the arc of the gauge. How close it is to the arc is determined by tickLen: the point will be distant 1.2 * tickLen from the arc
Parameters
val the value set on the widget
angle a pointer to a double that will store the angle, in degrees, from the 3 o'clock axis to the needle (if angle is not NULL)
radius if greater than 0, the parameter is used to return a point with such distance from the center. Otherwise, radius is assumed to be equal to the paint area width divided by two.
paint_area if valid, it is used for the calculation. Otherwise the paintArea method is used to recalculate the paint area
References g_config, QuGaugeConfig::max, QuGaugeConfig::min, paintArea(), and QuGaugeConfig::tickLen.
Referenced by drawGauge(), paintEvent(), and textRect().
maxAnimationDuration()
qint64 QuCircularGaugeBase::maxAnimationDuration () const
maxValue()
double QuCircularGaugeBase::maxValue () const
minimumSizeHint()
QSize QuCircularGaugeBase::minimumSizeHint () const
minorTicksCount()
int QuCircularGaugeBase::minorTicksCount () const
minValue()
double QuCircularGaugeBase::minValue () const
needleColor()
QColor QuCircularGaugeBase::needleColor () const
normalColor()
QColor QuCircularGaugeBase::normalColor () const
paintArea()
QRectF QuCircularGaugeBase::paintArea ()
References updatePaintArea().
Referenced by drawLabel(), drawText(), getPivotRadius(), mapTo(), paintEvent(), and updateLabelsFontSize().
paintEvent()
void QuCircularGaugeBase::paintEvent (QPaintEvent * pe) protected
References QuGaugeConfig::drawBackground, drawBackground, drawGauge(), drawLabel(), drawNeedle(), drawPivot(), QuGaugeConfig::drawText, drawText(), drawTicks(), g_config, Elettra::lightGray, mapTo(), NoLabel, paintArea(), and QuGaugeConfig::value_anim.
pivotCircleRadius()
double QuCircularGaugeBase::pivotCircleRadius () const
readError()
bool QuCircularGaugeBase::readError () const
readErrorColor()
QColor QuCircularGaugeBase::readErrorColor () const
regenerateCache
void QuCircularGaugeBase::regenerateCache () slot
References updateLabelsCache(), updateLabelsDistrib(), and updateLabelsFontSize().
Referenced by changeEvent(), labelFontSize(), setAngleSpan(), setAngleStart(), setFormat(), setFormatFromPropertyEnabled(), setFormatProperty(), setLabel(), setMaxValue(), setMinValue(), setPivotCircleRadius(), setTickLen(), and setTicksCount().
resizeEvent()
void QuCircularGaugeBase::resizeEvent (QResizeEvent * re) protected
References updateLabelsFontSize(), and updatePaintArea().
setAngleSpan
void QuCircularGaugeBase::setAngleSpan (int a) slot
set the span of the arc of the gauge
Parameters
the angle span, in degrees. The default is 300 degrees from angleStart (zero at 3 o'clock)
See also
setAngleStart
References regenerateCache().
setAngleStart
void QuCircularGaugeBase::setAngleStart (int as) slot
set the start angle of the arc, in degrees, from 6 o'clock
Parameters
as the value of the angle to use as starting point for the drawing of the gauge's arc, in degrees, from 6 o'clock. By default, the span angle is 300 degrees and the start is set to 30 degrees from 3 o'clock
See also
setAngleSpan
References regenerateCache().
setAnimationEnabled
void QuCircularGaugeBase::setAnimationEnabled (bool ae) slot
References QuGaugeConfig::animationEnabled, and g_config.
setBackgroundColor
void QuCircularGaugeBase::setBackgroundColor (const QColor & bc) slot
References QuGaugeConfig::backgroundColor, and g_config.
setBackgroundColorAlpha
void QuCircularGaugeBase::setBackgroundColorAlpha (int a) slot
References QuGaugeConfig::backgroundColorAlpha, and g_config.
setBackgroundGradientSpread
void QuCircularGaugeBase::setBackgroundGradientSpread (double s) slot
If background drawing is enabled, the spread determines the stop point of the gradient from the current value color (normal, warning or error) and the background color.
Parameters
s the gradient stop, greater than 0 and less than or equal to 1
See also
setBackgroundColor
drawBackgroundEnabled
backgroundColor
References QuGaugeConfig::backgroundGradientSpread, and g_config.
setCacheRegenerationDisabled()
void QuCircularGaugeBase::setCacheRegenerationDisabled (bool dis)
disables cache regeneration
Parameters
dis true regenerateCache does nothing
Some property changes trigger a call to regenerateCache If you plan to update several properties at once, you can consider disabling cache regeneration temporarily and enable it again after the updates.
Warning
Enabling cache regeneration does not call regenerateCache automatically. The programmer must take care of it.
setDrawBackgroundEnabled
void QuCircularGaugeBase::setDrawBackgroundEnabled (bool en) slot
References QuGaugeConfig::drawBackground, and g_config.
setDrawColoredTicks
void QuCircularGaugeBase::setDrawColoredTicks (bool dr) slot
References QuGaugeConfig::drawColoredTicks, and g_config.
setDrawText
void QuCircularGaugeBase::setDrawText (bool dt) slot
References QuGaugeConfig::drawText, and g_config.
setDrawTickCore1
void QuCircularGaugeBase::setDrawTickCore1 (bool t) slot
References QuGaugeConfig::drawTickCore1, and g_config.
setDrawTickCore2
void QuCircularGaugeBase::setDrawTickCore2 (bool t) slot
References QuGaugeConfig::drawTickCore2, and g_config.
setErrorColor
void QuCircularGaugeBase::setErrorColor (const QColor & ec) slot
References QuGaugeConfig::errorColor, and g_config.
setFormat
void QuCircularGaugeBase::setFormat (const QString & f) slot
sets the format to be used on the text along the gauge if the property formatFromProperty enabled is false
Parameters
f the format used if formatFromProperty is false
If formatFromProperty is true, the format is applied according to the value of the "format" key in the configuration CuData for the given source.
note
This method is called by QuCircularGauge when a CuData has the value "property" associated to the key "type" (configuration (or property) data).
See also
setFormatFromPropertyEnabled
References QuGaugeConfig::format, g_config, and regenerateCache().
setFormatFromPropertyEnabled
void QuCircularGaugeBase::setFormatFromPropertyEnabled (bool ffp) slot
enables or disables applying format from the configuration CuData
Parameters
ffp true the format of the text along the gauge is taken by the source properties.
ffp false the format of the text along the gauge is taken by the format property
See also
format
formatFromPropertyEnabled
References QuGaugeConfig::format_from_property, g_config, and regenerateCache().
setFormatProperty
void QuCircularGaugeBase::setFormatProperty (const QString & fp) slot
sets the format of the text along the gauge to be used when formatFromPropertyEnabled is true
Parameters
fp the format to be applied to the numbers along the gauge when formatFromPropertyEnabled is true
note
This method is called by QuCircularGauge when a CuData which key "type" has the "property" value.
See also
setFormatFromPropertyEnabled
References QuGaugeConfig::format_prop, g_config, and regenerateCache().
setGaugeWidth
void QuCircularGaugeBase::setGaugeWidth (double w) slot
References g_config, and QuGaugeConfig::gaugeWidth.
setHighError
void QuCircularGaugeBase::setHighError (double e) slot
References g_config, and QuGaugeConfig::high_e.
setHighWarning
void QuCircularGaugeBase::setHighWarning (double w) slot
References g_config, and QuGaugeConfig::high_w.
setLabel
void QuCircularGaugeBase::setLabel (const QString & l) slot
References regenerateCache().
setLabelDistFromCenter
void QuCircularGaugeBase::setLabelDistFromCenter (double radius_percent) slot
setLabelFontScale
void QuCircularGaugeBase::setLabelFontScale (double factor) slot
changes the label font size respect to the automatically calculated size
Parameters
factor the label font scale value
The font size of the text on the gauge is scaled by this factor respect to the automatically calculated size
Note
The default value is -1
setLabelPosition
void QuCircularGaugeBase::setLabelPosition (QuCircularGaugeBase::LabelPosition p) slot
setLabelValueFormat
void QuCircularGaugeBase::setLabelValueFormat (const QString & f) slot
setLowError
void QuCircularGaugeBase::setLowError (double e) slot
References g_config, and QuGaugeConfig::low_e.
setLowWarning
void QuCircularGaugeBase::setLowWarning (double w) slot
References g_config, and QuGaugeConfig::low_w.
setMaxAnimationDuration
void QuCircularGaugeBase::setMaxAnimationDuration (qint64 millis) slot
References g_config, and QuGaugeConfig::maximumAnimDuration.
setMaxValue
void QuCircularGaugeBase::setMaxValue (double max) slot
References g_config, QuGaugeConfig::max, and regenerateCache().
setMinorTicksCount
void QuCircularGaugeBase::setMinorTicksCount (int t) slot
References g_config, and QuGaugeConfig::minorTicksCount.
setMinValue
void QuCircularGaugeBase::setMinValue (double min) slot
References g_config, QuGaugeConfig::min, and regenerateCache().
setNeedleColor
void QuCircularGaugeBase::setNeedleColor (const QColor & c) slot
References g_config, and QuGaugeConfig::needleColor.
setNormalColor
void QuCircularGaugeBase::setNormalColor (const QColor & nc) slot
References g_config, and QuGaugeConfig::normalColor.
setPivotCircleRadius
void QuCircularGaugeBase::setPivotCircleRadius (double percent) slot
References g_config, QuGaugeConfig::pivotRadius, regenerateCache(), and updatePaintArea().
setReadError
void QuCircularGaugeBase::setReadError (bool err) slot
Referenced by QuCircularGauge::onUpdate().
setReadErrorColor
void QuCircularGaugeBase::setReadErrorColor (const QColor & rec) slot
References g_config, and QuGaugeConfig::readErrorColor.
setTextColor
void QuCircularGaugeBase::setTextColor (const QColor & c) slot
References g_config, and QuGaugeConfig::textColor.
setTickCoreColor
void QuCircularGaugeBase::setTickCoreColor (const QColor & c) slot
References g_config, and QuGaugeConfig::tickCoreColor.
setTickLen
void QuCircularGaugeBase::setTickLen (double tl) slot
Set the tick len as percentage of the radius of the circle.
Parameters
tl a value between 0 and 1 representing the length of a tick with respect to the length of the radius
References g_config, regenerateCache(), and QuGaugeConfig::tickLen.
setTicksCount
void QuCircularGaugeBase::setTicksCount (int t) slot
References g_config, regenerateCache(), and QuGaugeConfig::ticksCount.
setUnit
void QuCircularGaugeBase::setUnit (const QString & u) slot
References g_config, and QuGaugeConfig::unit.
setValue
void QuCircularGaugeBase::setValue (double v) slot
References QuGaugeConfig::animationEnabled, g_config, QuGaugeConfig::max, QuGaugeConfig::maximumAnimDuration, QuGaugeConfig::min, QuGaugeConfig::value, and QuGaugeConfig::value_anim.
setValue_anim
void QuCircularGaugeBase::setValue_anim (double v) slot
References g_config, and QuGaugeConfig::value_anim.
setWarningColor
void QuCircularGaugeBase::setWarningColor (const QColor & wc) slot
References g_config, and QuGaugeConfig::warningColor.
sizeHint()
QSize QuCircularGaugeBase::sizeHint () const
textColor()
QColor QuCircularGaugeBase::textColor () const
textRect()
QRectF QuCircularGaugeBase::textRect (int tick, double radius)
References g_config, mapTo(), QuGaugeConfig::max, QuGaugeConfig::min, and QuGaugeConfig::ticksCount.
Referenced by drawText().
tickCoreColor()
QColor QuCircularGaugeBase::tickCoreColor () const
tickLen()
double QuCircularGaugeBase::tickLen () const
Referenced by drawTicks().
ticksCount()
int QuCircularGaugeBase::ticksCount () const
Referenced by drawTicks(), and updateLabelsDistrib().
unit()
QString QuCircularGaugeBase::unit () const
updateLabelsCache
void QuCircularGaugeBase::updateLabelsCache () slot
References formatLabel(), g_config, getAppliedFormat(), QuGaugeConfig::max, QuGaugeConfig::min, and QuGaugeConfig::ticksCount.
Referenced by regenerateCache().
updateLabelsDistrib
QList< int > QuCircularGaugeBase::updateLabelsDistrib () const slot
get the labels distribution according to the shape of the gauge
Returns
a list of integers as follows
index 0: number of labels from 6:01 to 9:00 o'clock
index 1: number of labels from 9:01 to 12:00 o'clock
index 2: number of labels from 12:01 to 3.00 o'clock
index 3: number of labels from 3:01 to 6:00
References g_config, QuGaugeConfig::ticksCount, and ticksCount().
Referenced by regenerateCache().
updateLabelsFontSize
void QuCircularGaugeBase::updateLabelsFontSize () slot
References paintArea().
Referenced by regenerateCache(), and resizeEvent().
updatePaintArea
void QuCircularGaugeBase::updatePaintArea () slot
References q1, q14, q143, q1432, q2, q21, q214, q2143, q3, q32, q321, q3214, q4, q43, q432, and q4321.
Referenced by paintArea(), resizeEvent(), and setPivotCircleRadius().
value()
double QuCircularGaugeBase::value () const
Referenced by formatLabel().
value_anim()
double QuCircularGaugeBase::value_anim () const
valueColor()
QColor QuCircularGaugeBase::valueColor (double val) const
returns the color associated to a value
Parameters
val the value
Returns
the associated color, according to warning and error ranges.
References QuGaugeConfig::errorColor, g_config, inErrorRange(), inWarningRange(), QuGaugeConfig::normalColor, and QuGaugeConfig::warningColor.
Referenced by drawBackground().
warningColor()
QColor QuCircularGaugeBase::warningColor () const
Member Data Documentation
g_config
QuGaugeConfig* QuCircularGaugeBase::g_config protected
Referenced by drawBackground(), drawBackgroundEnabled(), drawGauge(), drawLabel(), drawNeedle(), drawPivot(), drawText(), drawTicks(), getAppliedFormat(), getPivotRadius(), inErrorRange(), inWarningRange(), mapTo(), paintEvent(), QuCircularGaugeBase(), setAnimationEnabled(), setBackgroundColor(), setBackgroundColorAlpha(), setBackgroundGradientSpread(), setDrawBackgroundEnabled(), setDrawColoredTicks(), setDrawText(), setDrawTickCore1(), setDrawTickCore2(), setErrorColor(), setFormat(), setFormatFromPropertyEnabled(), setFormatProperty(), setGaugeWidth(), setHighError(), setHighWarning(), setLowError(), setLowWarning(), setMaxAnimationDuration(), setMaxValue(), setMinorTicksCount(), setMinValue(), setNeedleColor(), setNormalColor(), setPivotCircleRadius(), setReadErrorColor(), setTextColor(), setTickCoreColor(), setTickLen(), setTicksCount(), setUnit(), setValue(), setValue_anim(), setWarningColor(), textRect(), updateLabelsCache(), updateLabelsDistrib(), valueColor(), and ~QuCircularGaugeBase().
Property Documentation
angleSpan
int QuCircularGaugeBase::angleSpan read write
returns the span of the angle of the circular gauge, in degrees
Returns
the span angle in degrees.
Note
According to Qt documentation, negative values draw the arc clockwise
See also
angleStart
setAngleSpan
angleStart
int QuCircularGaugeBase::angleStart read write
returns the angle from which the gauge arc starts
Returns
the angle, in degrees, where the gauge arc starts
See also
angleSpan
setAngleStart
animationEnabled
bool QuCircularGaugeBase::animationEnabled read write
if true, an animation is used to draw the transition between two subsequent setValue calls
Returns
true the needle is animated when moving from its current position to the new position specified with setValue false the needle abruptly moves to the new value
Special note
The maximum duration of the animation is determined by the value, in milliseconds, of the maxAnimationDuration property. If two setValue calls take place within a shorter interval, that interval is used to animate the transition instead.
See also
maxAnimationDuration
backgroundColor
QColor QuCircularGaugeBase::backgroundColor read write
backgroundColorAlpha
int QuCircularGaugeBase::backgroundColorAlpha read write
backgroundGradientSpread
double QuCircularGaugeBase::backgroundGradientSpread read write
drawBackground
bool QuCircularGaugeBase::drawBackground read write
Referenced by paintEvent().
drawColoredTicks
bool QuCircularGaugeBase::drawColoredTicks read write
draw colored ticks
This property can also be enabled in association with drawTickCore1 or drawTickCore2 if the effect is welcome.
If enabled, the colored ticks length is equal to radius multiplied by (1.0 - tickLen).
drawText
bool QuCircularGaugeBase::drawText read write
either draw or not the labels with the values associated to each major tick
Returns
true the value of each major tick is drawn false no values are drawn on the gauge
Note
if you want the current value to be displayed on a separate bigger label somewhere in the widget area, use the labelPosition property and set it to a value different from QuCircularBase::NoLabel. At the same time, the label property must be set to an empty string.
See also
label
setLabelPosition
setLabel
drawTickCore1
bool QuCircularGaugeBase::drawTickCore1 read write
draw a tick inside the gauge arc
Returns
true a tick is drawn within the gauge arc. Its width is equal to the gaugeWidth property (in pixels)
See also
drawTickCore2
drawColoredTicks
drawTickCore2
bool QuCircularGaugeBase::drawTickCore2 read write
draw a tick from the inner border of the gauge arc
Returns
true a tick is drawn from the inner border of the gauge arc. Its width is equal to the gaugeWidth property (in pixels)
See also
drawTickCore1
drawColoredTicks
errorColor
QColor QuCircularGaugeBase::errorColor read write
format
QString QuCircularGaugeBase::format read write
formatFromPropertyEnabled
bool QuCircularGaugeBase::formatFromPropertyEnabled read write
gaugeWidth
double QuCircularGaugeBase::gaugeWidth read write
returns the pen width used to draw the gauge arc
Returns
the pen width, in pixels, floating point, used to draw the arc
Notes
If the drawTickCore1 property is enabled, a tick is drawn inside the arc and its length is equal to gaugeWidth.
If the drawTickCore2 property is enabled a tick is drawn from the arc bottom side and it will be gaugeWidth pixels long
See also
drawTickCore1
drawTickCore2
drawColoredTicks
highError
double QuCircularGaugeBase::highError read write
highWarning
double QuCircularGaugeBase::highWarning read write
label
QString QuCircularGaugeBase::label read write
labelDistFromCenter
double QuCircularGaugeBase::labelDistFromCenter read write
labelFontScale
double QuCircularGaugeBase::labelFontScale read write
scales the label font respect to the automatically calculated size
Returns
the label font scale value, between 0 and 2.
The font size of the text on the gauge is scaled by this factor respect to the automatically calculated size
Note
The default value is -1, meaning label font is automatically calculated
labelPosition
QuCircularGaugeBase::LabelPosition QuCircularGaugeBase::labelPosition read write
labelValueFormat
QString QuCircularGaugeBase::labelValueFormat read write
lowError
double QuCircularGaugeBase::lowError read write
lowWarning
double QuCircularGaugeBase::lowWarning read write
maxAnimationDuration
qint64 QuCircularGaugeBase::maxAnimationDuration read write
The maximum duration of an animation between two setValue calls.
Returns
the value, in milliseconds, of the maximum duration of an animation between two setValue calls
note
If two setValue calls take place within a shorter interval, that interval is used to animate the transition instead.
See also
animationEnabled
maxValue
double QuCircularGaugeBase::maxValue read write
returns the maximum value represented by this gauge
Returns
the maximum value of this gauge's scale
minorTicksCount
int QuCircularGaugeBase::minorTicksCount read write
returns the number of minor ticks drawn between each couple of major ticks
Returns
the number of minor ticks between two subsequent major ticks
See also
ticksCount
setMinorTicksCount
minValue
double QuCircularGaugeBase::minValue read write
returns the minimum value represented by this gauge
Returns
the minimum value of this gauge's scale
needleColor
QColor QuCircularGaugeBase::needleColor read write
normalColor
QColor QuCircularGaugeBase::normalColor read write
pivotCircleRadius
double QuCircularGaugeBase::pivotCircleRadius read write
If greater than zero, a circle is drawn on the pivot of the needle.
This number, a floating point in the interval [0.0, 1.0], represents the fraction of the length of the radius used to draw a circle on the pivot of the needle.
The formula used to calculate the pivot circle radius is:
qMin(paintArea().width(), paintArea().height())/2.0 * g_config->pivotRadius
See also
getPivotRadius
readErrorColor
QColor QuCircularGaugeBase::readErrorColor read write
textColor
QColor QuCircularGaugeBase::textColor read write
tickCoreColor
QColor QuCircularGaugeBase::tickCoreColor read write
tickLen
double QuCircularGaugeBase::tickLen read write
returns the tick length
The value, expressed within the interval [0.0, 1.0] is intended as fraction of the lenght of the gauge arc's radius.
Default value
The default value is 0.08. The major tick length is thus equal to 2% of the radius by default.
ticksCount
int QuCircularGaugeBase::ticksCount read write
returns the number of major ticks drawn in the arc
Returns
the number of major ticks drawn
See also
minorTicksCount
unit
QString QuCircularGaugeBase::unit read write
value
double QuCircularGaugeBase::value read write
value_anim
double QuCircularGaugeBase::value_anim read write
returns the value during the animation
To get the actual value, please refer to the QuCircularGaugeBase::value method
warningColor
QColor QuCircularGaugeBase::warningColor read write
The documentation for this class was generated from the following files:
qucirculargaugebase.h
qucirculargaugebase.cpp