cumbia-qtcontrols: QuCheckBox Class Reference
QuCheckBox Class Reference
Input widgets | Display widgets
A check box that reads, displays and writes a boolean value.
#include <qucheckbox.h>
Public Slots
void setSource (const QString &s)
Connect the reader and the writer to the specified source name.
void setTarget (const QString &t)
provided for convenience/compatibility, calls setSource
void setTextFromLabel (bool tfl)
set the textFromLabel property to true
Signals
void newData (const CuData &)
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
Public Member Functions
QuCheckBox (QWidget *parent, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac, const CuControlsWriterFactoryI &w_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuCheckBox (QWidget *parent, CumbiaPool *cu_poo, const CuControlsFactoryPool &f_poo)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuCheckBox ()
the class destructor
QString source () const
QString target () const
provided for convenience/compatibility, returns source
CuContext * getContext () const
Provided to implement CuContextI interface, returns getOutputContext.
CuContext * getOutputContext () const
Returns the reader's context.
CuContext * getInputContext () const
Returns the writer's context.
bool textFromLabel () const
returns the textFromLabel property value
void onUpdate (const CuData &d)
determines the behaviour of the checkbox as a reader
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Protected Slots
virtual void checkboxClicked (bool checked)
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *e)
Reimplemented from QWidget's contextMenuEvent, emits a signal to request statistics on the link.
Properties
QString source
QString target
bool textFromLabel
Detailed Description
A check box that reads, displays and writes a boolean value.
Derives from QCheckBox, acts as a reader to display a boolean value and as a writer when it is checked. When checked, the current value read from the source is inverted and written on the same source.
setSource creates the link to the specified source. The textFromLabel property, if true, reads the "label" value from the CuData delivered at configuration time and sets the text on the check box accordingly (Tango attributes have a label attribute property that can be used, see CuData bundle description for data exchange with the Tango world.). Otherwise, provide a text as you would do for a Qt QCheckBox.
Constructor & Destructor Documentation
QuCheckBox() [1/2]
QuCheckBox::QuCheckBox (QWidget * parent, Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac, const CuControlsWriterFactoryI & w_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuCheckBox() [2/2]
QuCheckBox::QuCheckBox (QWidget * parent, CumbiaPool * cu_poo, const CuControlsFactoryPool & f_poo)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuCheckBox()
QuCheckBox::~QuCheckBox () virtual
the class destructor
Deletes the input and output contexts
Member Function Documentation
checkboxClicked
void QuCheckBox::checkboxClicked (bool checked) protected virtual slot
References CuControlsWriterA::execute(), and CuControlsWriterA::setArgs().
contextMenuEvent()
void QuCheckBox::contextMenuEvent (QContextMenuEvent * e) protected
Reimplemented from QWidget's contextMenuEvent, emits a signal to request statistics on the link.
A pop up menu appears and an action to view link statistics is made available.
References CuContextMenu::popup().
getContext()
CuContext * QuCheckBox::getContext () const virtual
Provided to implement CuContextI interface, returns getOutputContext.
Returns
the output widget's context
See also
getOutputContext
Implements CuContextI.
getInputContext()
CuContext * QuCheckBox::getInputContext () const
Returns the writer's context.
Returns
a pointer to the input CuContext used to write.
getOutputContext()
CuContext * QuCheckBox::getOutputContext () const
Returns the reader's context.
Returns
a pointer to the output CuContext used to read.
linkStatsRequest
void QuCheckBox::linkStatsRequest (QWidget * myself, CuContextI * myself_as_cwi) signal
newData
void QuCheckBox::newData (const CuData &) signal
onUpdate()
void QuCheckBox::onUpdate (const CuData & da)
determines the behaviour of the checkbox as a reader
Implements CuDataListener::onUpdate
if data is of type "property", the checkbox text is configured according to the "label" value, if available
if an error occurred, the widget is disabled
a message is set as a tooltip according to the "msg" value of da.
if the "value" contained in da can be converted to a boolean, the checkbox is set accordingly. If not, it is set as partially checked.
References QuLogImpl::showPopupOnMessage().
setSource
void QuCheckBox::setSource (const QString & s) slot
Connect the reader and the writer to the specified source name.
If a reader with a different source is configured, it is deleted. The same goes for the writer. If options have been set with CuContext::setOptions, they are used to set up the reader as desired.
Note
the reader and the writer are connected to the same source.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
See also
CuContext::setOptions
source
References CuControlsReaderA::setSource(), and CuControlsWriterA::setTarget().
Referenced by setTarget().
setTarget
void QuCheckBox::setTarget (const QString & t) slot
provided for convenience/compatibility, calls setSource
Calls setSource. Source and target are the same for QuCheckBox
See also
setSource
source
target
References setSource().
setTextFromLabel
void QuCheckBox::setTextFromLabel (bool tfl) slot
set the textFromLabel property to true
Parameters
tfl true the text of the check box is taken from the configuration data, taking the "label" value stored on the CuData (this is done within onUpdate)
tfl false the "label" value possibly stored in the configuration data is ignored.
source()
QString QuCheckBox::source () const
target()
QString QuCheckBox::target () const
provided for convenience/compatibility, returns source
Source and target are the same for QuCheckBox
Returns
the value returned by source
See also
source
setSource
setTarget
References source.
textFromLabel()
bool QuCheckBox::textFromLabel () const
returns the textFromLabel property value
Returns
true: enabled
false: disabled
See also
setTextFromLabel
Property Documentation
source
QString QuCheckBox::source read write
Referenced by target().
target
QString QuCheckBox::target read write
textFromLabel
bool QuCheckBox::textFromLabel read write
The documentation for this class was generated from the following files:
qucheckbox.h
qucheckbox.cpp