cumbia-qtcontrols: QuSpectrumPlot Class Reference
QuSpectrumPlot Class Reference
Display widgets » Plots
Draw a line for each data source over time.
#include <quspectrumplot.h>
Public Slots
void setSource (const QString &s)
void setSources (const QStringList &l)
void addSource (const QString &s)
void unsetSource (const QString &s)
void unsetSources ()
void setOptions (const CuData &options)
void setPeriod (int p)
Changes the refresh period on the plot, issuing a setData on every reader with a CuData containing the "period" property set to p.
void requestLinkStats ()
Public Slots inherited from QuPlotBase
virtual void refresh ()
Calls updateMarkers, updateScales and replot, resetting the zoom base in the end.
void setXAxisAutoscaleEnabled (bool en)
void setYAxisAutoscaleEnabled (bool en)
void setYLowerBound (double l)
void setYUpperBound (double u)
void setXLowerBound (double l)
void setXUpperBound (double u)
void setXAutoscaleMargin (double d)
void setUpperBoundExtra (int axisId, double e)
double upperBoundExtra (int axisId) const
double xAutoscaleMargin ()
void setYAutoscaleAdjustment (double d)
double yAutoscaleAdjustment ()
void setTitleOnCanvasEnabled (bool en)
void setCurveStyle (const QString &curveName, QwtPlotCurve::CurveStyle)
void setDataBufferSize (int b)
void setZoomDisabled (bool)
void clearPlot ()
virtual void setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
virtual void appendData (const QString &curveName, double x, double y)
void setRefreshTimeout (int millis)
void setDefaultBounds (double lb, double ub, Axis axisId=QwtPlot::yLeft)
void restoreDefaultBounds (Axis axisId=QwtPlot::yLeft)
void setAxisScaleDefaultEnabled (bool en, Axis axisId=QwtPlot::yLeft)
Signals
void newData (const CuData &)
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
Signals inherited from QuPlotBase
void plotClicked (const QPoint &pt, QwtPlotCurve *closestCurve, double x, double y, const QPoint &curvePoint)
void curveAdded (QuPlotCurve *)
This signal is emitted when a new curve is added to the plot.
void curveRemoved (QuPlotCurve *)
This signal is emitted whenever a curve is removed from the plot via removeCurve.
Public Member Functions
QuSpectrumPlot (QWidget *w, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuSpectrumPlot (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuSpectrumPlot ()
QString source () const
QStringList sources () const
int period () const
CuContext * getContext () const
Return a reference to the CuContext in use.
void onUpdate (const CuData &d)
void update (const CuData &d)
Public Member Functions inherited from QuPlotBase
QuPlotBase (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
QuPlotBase (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
virtual ~QuPlotBase ()
CurveStyle curvesStyle ()
bool titleOnCanvasEnabled ()
bool xAxisAutoscaleEnabled ()
bool yAxisAutoscaleEnabled ()
double yUpperBound ()
double yLowerBound ()
bool xAxisLogScale ()
bool yAxisLogScale ()
void setXAxisLogScale (bool l)
void setYAxisLogScale (bool l)
double xUpperBound ()
double xLowerBound ()
bool zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
QList< QwtPlotCurve * > curves () const
void addCurve (const QString &curveName, QuPlotCurve *curve)
void removeCurve (const QString &curveName)
Removes the specified curve from the plot, deleting it.
void addCurve (const QString &curveName)
QuPlotCurve * curve (const QString &name)
int dataBufferSize ()
returns the data buffer size.
void hideMarker ()
void appendData (const QString &curveName, double *x, double *y, int size)
int refreshTimeout () const
double defaultLowerBound (QwtPlot::Axis axisId=QwtPlot::yLeft) const
double defaultUpperBound (QwtPlot::Axis axisId=QwtPlot::yLeft) const
void update (const CuData &)
void configure (const CuData &da)
void setUpdateStrategy (QuWidgetUpdateStrategyI *updateStrategy)
sets or replaces the update strategy (see the strategy design pattern)
void setContextMenuStrategy (QuWidgetContextMenuStrategyI *ctx_menu_strategy)
sets or replaces the context menu strategy (see the strategy design pattern)
QuWidgetUpdateStrategyI * updateStrategy () const
return the QuWidgetUpdateStrategyI implementation in use.
QuWidgetContextMenuStrategyI * contextMenuStrategy () const
return the QuWidgetContextMenuStrategyI implementation in use.
virtual QDialog * createConfigureDialog ()
virtual bool updateMarker ()
updates the marker, if visible, and returns true if it's visible, false otherwise
virtual bool updateScales ()
Updates the axes bounds for which autoscale is enabled.
void resetZoom ()
bool inZoom () const
Public Member Functions inherited from QuWidgetInterface
virtual ~QuWidgetInterface ()
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
QString source
int period
Get the refresh period of the sources issuing a getData on the first reader in the list.
Properties inherited from QuPlotBase
bool xAxisAutoscale
bool yAxisAutoscale
double yUpperBound
double yLowerBound
double xUpperBound
double xLowerBound
double xAutoscaleMargin
double yAutoscaleAdjustment
bool titleOnCanvasEnabled
bool yAxisLogScale
bool zoomDisabled
int dataBufferSize
int refreshTimeout
Additional Inherited Members
Public Types inherited from QuPlotBase
enum CurveStyle {
NoCurve, Lines, Sticks, Steps,
Dots, UserCurve = 100
}
Protected Slots inherited from QuPlotBase
void displayZoomHint ()
void eraseZoomHint ()
void plotZoomed (const QRectF &)
void showMarker (const QPolygon &p)
void print ()
void snapshot ()
void copyImage ()
virtual void configurePlot ()
void saveData ()
dumps the curves into a csv file.
Protected Member Functions inherited from QuPlotBase
virtual QString plotTitle ()
returns the plot title.
virtual void drawCanvas (QPainter *p)
void mouseReleaseEvent (QMouseEvent *ev)
void keyPressEvent (QKeyEvent *ke)
void moveCurveToYRight (QwtPlotCurve *c, bool yr)
void updateLabel (QwtPlotCurve *closestCurve, int closestPointIdx)
virtual void init ()
void contextMenuEvent (QContextMenuEvent *e)
QuPlotBase::contextMenuEvent executes a contextual menu when the plot is right clicked.
Detailed Description
Draw a line for each data source over time.
QuSpectrumPlot is designed to accept a list of data sources. Each data source is represented by a curve in the plot, which is updated according to the CuData "value" and "timestamp_ms" properties. If CuData "err" boolean is true or the "value" data format is not a scalar, the plot is disabled.
Plot update strategies.
Any implementation-specific data update is delegated to an update strategy through setUpdateStrategy. If no update strategy is set, then the update method is called from within onUpdate and the base operations aforementioned are performed. Strategies must implement QuWidgetUpdateStrategyI interface.
Constructor & Destructor Documentation
QuSpectrumPlot() [1/2]
QuSpectrumPlot::QuSpectrumPlot (QWidget * w, Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuSpectrumPlot() [2/2]
QuSpectrumPlot::QuSpectrumPlot (QWidget * w, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuSpectrumPlot()
QuSpectrumPlot::~QuSpectrumPlot () virtual
Member Function Documentation
addSource
void QuSpectrumPlot::addSource (const QString & s) slot
getContext()
CuContext * QuSpectrumPlot::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
linkStatsRequest
void QuSpectrumPlot::linkStatsRequest (QWidget * myself, CuContextI * myself_as_cwi) signal
Referenced by requestLinkStats().
newData
void QuSpectrumPlot::newData (const CuData &) signal
Referenced by onUpdate().
onUpdate()
void QuSpectrumPlot::onUpdate (const CuData & d)
References newData(), QuWidgetUpdateStrategyI::update(), update(), and QuPlotBase::updateStrategy().
period()
int QuSpectrumPlot::period () const
requestLinkStats
void QuSpectrumPlot::requestLinkStats () slot
References linkStatsRequest().
setOptions
void QuSpectrumPlot::setOptions (const CuData & options) slot
setPeriod
void QuSpectrumPlot::setPeriod (int p) slot
Changes the refresh period on the plot, issuing a setData on every reader with a CuData containing the "period" property set to p.
QuContext options are left unchanged.
Note
The effect on the refresh period of the sources depends on the CuControlsReaderA implementation. For example, in the context of the Tango control system, you should expect that a reader managed by events is not affected by a period change.
setSource
void QuSpectrumPlot::setSource (const QString & s) slot
References setSources(), and unsetSources().
setSources
void QuSpectrumPlot::setSources (const QStringList & l) slot
References unsetSources().
Referenced by setSource().
source()
QString QuSpectrumPlot::source () const
sources()
QStringList QuSpectrumPlot::sources () const
unsetSource
void QuSpectrumPlot::unsetSource (const QString & s) slot
unsetSources
void QuSpectrumPlot::unsetSources () slot
Referenced by setSource(), and setSources().
update()
void QuSpectrumPlot::update (const CuData & d) virtual
Implements QuWidgetInterface.
References QuPlotBase::addCurve(), CuLinkStats::addError(), CuLinkStats::addOperation(), QuPlotBase::configure(), QuPlotBase::curve(), QuPlotCurve::Invalid, QuPlotCurve::Normal, QuPlotBase::setData(), and QuPlotCurve::setState().
Referenced by onUpdate().
Property Documentation
period
int QuSpectrumPlot::period read write
Get the refresh period of the sources issuing a getData on the first reader in the list.
Note 1
The effective period of the reader is returned, not the "period" property stored in the CuData options.
Note 2
If each source has been configured with different periods, you should call getContext()->getData with a list of CuData as parameter.
source
QString QuSpectrumPlot::source read write
The documentation for this class was generated from the following files:
quspectrumplot.h
quspectrumplot.cpp