cumbia-qtcontrols: CuEngineAccessor Class Reference
CuEngineAccessor Class Reference
#include <cuengineaccessor.h>
Signals
void engineSwapped ()
void engineChanged (const QStringList &from, const QStringList &to)
Public Member Functions
CuEngineAccessor (QObject *parent, CumbiaPool **cu_p_p, CuControlsFactoryPool *fp_p)
virtual ~CuEngineAccessor ()
virtual void engine_swap (CumbiaPool *cu_p, const CuControlsFactoryPool &fp)
CumbiaPool * cu_pool () const
CuControlsFactoryPool * f_pool () const
Constructor & Destructor Documentation
CuEngineAccessor()
CuEngineAccessor::CuEngineAccessor (QObject * parent, CumbiaPool ** cu_p_p, CuControlsFactoryPool * fp_p) explicit
~CuEngineAccessor()
CuEngineAccessor::~CuEngineAccessor () virtual
Member Function Documentation
cu_pool()
CumbiaPool * CuEngineAccessor::cu_pool () const
Referenced by CuContext::CuContext(), and main().
engine_swap()
void CuEngineAccessor::engine_swap (CumbiaPool * cu_p, const CuControlsFactoryPool & fp) virtual
References engineChanged(), engineSwapped(), and CuControlsFactoryPool::getSrcPatternDomains().
Referenced by CuEngineSwap::app_engine_swap().
engineChanged
void CuEngineAccessor::engineChanged (const QStringList & from, const QStringList & to) signal
Referenced by engine_swap().
engineSwapped
void CuEngineAccessor::engineSwapped () signal
Referenced by engine_swap().
f_pool()
CuControlsFactoryPool * CuEngineAccessor::f_pool () const
Referenced by CuContext::CuContext().
The documentation for this class was generated from the following files:
cuengineaccessor.h
cuengineaccessor.cpp