cumbia-qtcontrols: CuControlsReaderFactoryI Class Reference
CuControlsReaderFactoryI Class Reference abstract
Core classes
cumbia-qtcontrols reader factory. Creates an instance of a CuControlsReaderA implementation.
#include <cucontrolsfactories_i.h>
Public Member Functions
virtual ~CuControlsReaderFactoryI ()
virtual CuControlsReaderA * create (Cumbia *, CuDataListener *) const =0
Subclasses implement the create method to return an instance of a CuControlsReaderA implementation.
virtual CuControlsReaderFactoryI * clone () const =0
clone an instance.
virtual void setOptions (const CuData &options)=0
set options to be used when creating the reader.
Detailed Description
cumbia-qtcontrols reader factory. Creates an instance of a CuControlsReaderA implementation.
CuTReaderFactory and CuEpReaderFactory implement CuControlsReaderFactoryI for Tango and Epics respectively;
CuTControlsReader and CuEpControlsReader implement CuControlsReaderA for Tango and Epics respectively.
Subclasses must implement the create, clone and setOptions pure virtual methods.
Constructor & Destructor Documentation
~CuControlsReaderFactoryI()
virtual CuControlsReaderFactoryI::~CuControlsReaderFactoryI () inline virtual
Member Function Documentation
clone()
virtual CuControlsReaderFactoryI * CuControlsReaderFactoryI::clone () const pure virtual
clone an instance.
Clones the current instance
Referenced by CuContext::CuContext(), QuInputOutput::QuInputOutput(), and CuControlsFactoryPool::registerImpl().
create()
virtual CuControlsReaderA * CuControlsReaderFactoryI::create (Cumbia * , CuDataListener *) const pure virtual
Subclasses implement the create method to return an instance of a CuControlsReaderA implementation.
Returns
a pointer to an instance of a CuControlsWriterA implementation
setOptions()
virtual void CuControlsReaderFactoryI::setOptions (const CuData & options) pure virtual
set options to be used when creating the reader.
This is engine dependent.
Parameters
options a CuData containing key/value pairs that are specific of an engine.
Options are normally set within the create method, when a CuControlsReaderA is instantiated.
Referenced by QuInputOutput::QuInputOutput().
The documentation for this class was generated from the following file:
cucontrolsfactories_i.h