cumbia-qtcontrols: QuPlotConfigurator Class Reference
QuPlotConfigurator Class Reference
#include <quplotconfigurator.h>
Public Member Functions
QuPlotConfigurator ()
bool hasCustomConf (const QString &plotnam, const QuPlotCurve *c) const
void save (const QString &plot_name, const QuPlotCurve *c)
void save (QuPlotBase *plot)
void configure_curve (const QuPlotBase *plot, QuPlotCurve *c, int curves_cnt)
void configure (QuPlotBase *plot)
void clearSettings (QuPlotBase *plot) const
Constructor & Destructor Documentation
QuPlotConfigurator()
QuPlotConfigurator::QuPlotConfigurator ()
Member Function Documentation
clearSettings()
void QuPlotConfigurator::clearSettings (QuPlotBase * plot) const
configure()
void QuPlotConfigurator::configure (QuPlotBase * plot)
References QuPlotBase::getComponent(), QuPlotAxesComponent::setManualBounds(), QuPlotBase::setXAxisLogScale(), QuPlotBase::setYAutoscaleAdjustment(), QuPlotBase::setYAxisAutoscaleEnabled(), QuPlotBase::setYAxisLogScale(), QuPlotBase::xAxisAutoscaleEnabled(), QuPlotBase::xAxisLogScale(), QuPlotBase::xLowerBound, QuPlotBase::xUpperBound, QuPlotBase::yAutoscaleAdjustment, QuPlotBase::yAxisAutoscaleEnabled(), QuPlotBase::yAxisLogScale, QuPlotBase::yLowerBound, and QuPlotBase::yUpperBound.
Referenced by QuPlotBase::init().
configure_curve()
void QuPlotConfigurator::configure_curve (const QuPlotBase * plot, QuPlotCurve * c, int curves_cnt)
Referenced by QuPlotBase::addCurve().
hasCustomConf()
bool QuPlotConfigurator::hasCustomConf (const QString & plotnam, const QuPlotCurve * c) const
save() [1/2]
void QuPlotConfigurator::save (const QString & plot_name, const QuPlotCurve * c)
save() [2/2]
void QuPlotConfigurator::save (QuPlotBase * plot)
References QuPlotBase::xAxisAutoscaleEnabled(), QuPlotBase::xAxisLogScale(), QuPlotBase::xLowerBound, QuPlotBase::xUpperBound, QuPlotBase::yAutoscaleAdjustment, QuPlotBase::yAxisAutoscaleEnabled(), QuPlotBase::yAxisLogScale, QuPlotBase::yLowerBound, and QuPlotBase::yUpperBound.
The documentation for this class was generated from the following files:
quplotconfigurator.h
quplotconfigurator.cpp