cumbia-qtcontrols: CuControlsUtils Class Reference
CuControlsUtils Class Reference
utility class to find input arguments from objects with text or value properties
#include <cucontrolsutils.h>
Public Member Functions
CuControlsUtils ()
virtual ~CuControlsUtils ()
QString findInput (const QString &objectName, const QObject *leaf, bool *found) const
QObject * findObject (const QString &objectName, const QObject *leaf) const
CuVariant getArgs (const QString &target, const QObject *leaf) const
finds the arguments in the source or target. If they are object names it finds the objects with those names and get the input from them, otherwise they are directly converted to CuVariant and returned.
QList< QObject * > findObjects (const QString &target, const QObject *leaf)
bool initObjects (const QString &target, const QObject *leaf, const CuData &data, const char *value_key)
initialize objects setting range (min, max, if relevant) and the value according to value_key
QString msg (const CuData &da) const
return a string with a message derived from the da input parameter
void msg_short (const CuData &da, char buf[MSGLEN])
msg_short is intended to fill the provided buffer long at most MSGLEN as quickly as possible
void ts_to_s (const long int &millis, char dt[TIMESTAMPLEN]) const
void ts_to_s (const double &ts, char dt[TIMESTAMPLEN]) const
void m_elapsed (time_t secs, const long int &millis, char buf[MSGLEN], int offset) const
void m_elapsed (const double &us, char buf[MSGLEN], int offset) const
Detailed Description
utility class to find input arguments from objects with text or value properties
This class is used to search input arguments for sources or targets from widgets exposing text or value properties. Text or values are edited within the widget and can be passed as input arguments to readers or writers.
Please refer to the findInput method documentation for more details.
Constructor & Destructor Documentation
CuControlsUtils()
CuControlsUtils::CuControlsUtils ()
find the input argument from an object and return it in the shape of a string.
Parameters
objectName the name of the object to search for
leaf the parent object under which the object providing input is searched for
Returns
a string with the argument.
Note
The object providing input arguments must implement one of the following properties, that are searched and evaluated in this order:
data (e.g. QuComboBox: data represented as string, either currentText or currentIndex according to QuComboBox indexMode property)
text (e.g. QLabel, QLineEdit, ...)
value (e.g. QSpinBox, QDoubleSpinBox, ENumeric)
currentIndex (e.g. QComboBox)
Note
The first property found in the list above is used. If you write a custom widget that displays data that may be internally represented by different types (e.g. a combo box that can be used to either change a numerical index or a text), make sure to provide a data property that can be converted to QString regardless of the internal storage type.
~CuControlsUtils()
CuControlsUtils::~CuControlsUtils () virtual
Member Function Documentation
findInput()
QString CuControlsUtils::findInput (const QString & objectName, const QObject * leaf, bool * found) const
Referenced by getArgs().
findObject()
QObject * CuControlsUtils::findObject (const QString & objectName, const QObject * leaf) const
Referenced by findObjects().
findObjects()
QList< QObject * > CuControlsUtils::findObjects (const QString & target, const QObject * leaf)
References findObject(), and re().
Referenced by initObjects().
getArgs()
CuVariant CuControlsUtils::getArgs (const QString & target, const QObject * leaf) const
finds the arguments in the source or target. If they are object names it finds the objects with those names and get the input from them, otherwise they are directly converted to CuVariant and returned.
Parameters
target the source or target string
leaf under this object getArgs searches for a child (children) with the object name(s) specified in the argument (s).
Returns
a CuVariant with the detected argument(s), or an empty CuVariant.
The child is searched by the findInput method.
References findInput(), and re().
Referenced by QuButton::execute(), and QuWriter::execute().
initObjects()
bool CuControlsUtils::initObjects (const QString & target, const QObject * leaf, const CuData & data, const char * value_key)
initialize objects setting range (min, max, if relevant) and the value according to value_key
Parameters
target the name of the target
leaf the parent object under which children are searched by findObjects
data the CuData holding configuration values (min, max, if present), and a value to display on the object
value_key the key to look for the value that must be displayed (example: "value" or "w_value")
Returns
true if the operation was successful, false otherwise
References findObjects().
Referenced by QuButton::onUpdate().
m_elapsed() [1/2]
void CuControlsUtils::m_elapsed (const double & us, char buf[MSGLEN], int offset) const inline
References m_elapsed().
m_elapsed() [2/2]
void CuControlsUtils::m_elapsed (time_t secs, const long int & millis, char buf[MSGLEN], int offset) const inline
Referenced by m_elapsed(), and msg_short().
msg()
QString CuControlsUtils::msg (const CuData & da) const
return a string with a message derived from the da input parameter
Parameters
da CuData
date_time_fmt a custom timestamp date / time format. Default: "yyyy-MM-dd HH:mm:ss.zzz"
Returns
the message stored in da[TTT::Message] if da[TTT::Err] evaluates to true or // da["msg"], da["err"] a new message with the source name, the value of da[TTT::Mode] (or da[TTT::Activity], if TTT::Mode is empty) and the timestamp. // da["mode"], da["activity"] da[TTT::Time_ms] or da[TTT::Time_us] are used to provide a date /time in the format "yyyy-MM-dd HH:mm:ss.zzz". // da["timestamp_ms"], da["timestamp_us"]
References msg(), and ts_to_s().
Referenced by msg(), and msg_short().
msg_short()
void CuControlsUtils::msg_short (const CuData & da, char buf[MSGLEN])
msg_short is intended to fill the provided buffer long at most MSGLEN as quickly as possible
Parameters
da a const reference to data
buf a buffer allocated by the caller
Unlike msg, there is no timestamp to date/time string conversion. Instead, the current time is taken (which has a lower cost) and a difference (in ms, secs or mins) with the previous timestamp is given instead.
References m_elapsed(), msg(), and MSGLEN.
ts_to_s() [1/2]
void CuControlsUtils::ts_to_s (const double & ts, char dt[TIMESTAMPLEN]) const inline
ts_to_s() [2/2]
void CuControlsUtils::ts_to_s (const long int & millis, char dt[TIMESTAMPLEN]) const inline
Referenced by msg().
The documentation for this class was generated from the following files:
cucontrolsutils.h
cucontrolsutils.cpp