cumbia-qtcontrols: CircularBuffer Class Reference
CircularBuffer Class Reference
#include <circularbuffer.h>
Public Member Functions
CircularBuffer (double interval=10.0, size_t numPoints=1000)
void fill (double interval, size_t numPoints)
void setReferenceTime (double)
double referenceTime () const
virtual size_t size () const QWT_OVERRIDE
virtual QPointF sample (size_t index) const QWT_OVERRIDE
void getData (QVector< double > &x, QVector< double > &y) const
virtual QRectF boundingRect () const QWT_OVERRIDE
void setFunction (double(*y)(double))
Constructor & Destructor Documentation
CircularBuffer()
CircularBuffer::CircularBuffer (double interval = 10.0, size_t numPoints = 1000)
References fill().
Member Function Documentation
boundingRect()
QRectF CircularBuffer::boundingRect () const virtual
fill()
void CircularBuffer::fill (double interval, size_t numPoints)
Referenced by CircularBuffer(), and QuPlot::setSettings().
getData()
void CircularBuffer::getData (QVector< double > & x, QVector< double > & y) const
References sample(), and size().
Referenced by QuPlot::timerEvent().
referenceTime()
double CircularBuffer::referenceTime () const
sample()
QPointF CircularBuffer::sample (size_t index) const virtual
References size().
Referenced by getData().
setFunction()
void CircularBuffer::setFunction (double(* y)(double))
Referenced by QuPlot::setSettings().
setReferenceTime()
void CircularBuffer::setReferenceTime (double timeStamp)
Referenced by QuPlot::timerEvent().
size()
size_t CircularBuffer::size () const virtual
Referenced by getData(), sample(), and QuPlot::setSettings().
The documentation for this class was generated from the following files:
circularbuffer.h
circularbuffer.cpp