cumbia-qtcontrols: QuTrendPlot Class Reference
QuTrendPlot Class Reference
Display widgets » Plots
Draw a line for each data source over time.
#include <qutrendplot.h>
Public Slots
void setSource (const QString &s)
Set the source name. Replcace currently configured sources, if any.
void setSources (const QStringList &l)
Set a list of sources to display on the plot. Replace currently configured ones, if any.
virtual bool ctxSwap (CumbiaPool *cu_p, const CuControlsFactoryPool &fpool)
void addSource (const QString &s)
void unsetSource (const QString &s)
void unsetSources ()
void setPeriod (int p)
void setTimeScaleDrawEnabled (bool enable)
void setShowDateOnTimeAxis (bool en)
void refresh ()
Updates the marker and the scales. If the scales are not changed and the marker is not viisble, then the replot is performed incrementally.
void requestLinkStats ()
Public Slots inherited from QuPlotBase
virtual void refresh ()
Calls updateMarkers, updateScales and replot, resetting the zoom base in the end.
void setXAxisAutoscaleEnabled (bool en, QwtPlot::Axis axis)
void setYAxisAutoscaleEnabled (bool en, QwtPlot::Axis axis)
void setXTopAxisAutoscaleEnabled (bool autoscale)
void setYRightAxisAutoscaleEnabled (bool autoscale)
void setYLowerBound (double l)
void setYUpperBound (double u)
void setXLowerBound (double l)
void setXUpperBound (double u)
void setXAutoscaleMargin (double d)
void setUpperBoundExtra (int axisId, double e)
add some extra upper bound to the specified axis to optimize replot operations when the refresh rate is fast.
double upperBoundExtra (int axisId) const
double xAutoscaleMargin ()
void setYAutoscaleAdjustment (double d)
double yAutoscaleAdjustment ()
void setTitleOnCanvasEnabled (bool en)
void setCurveStyle (const QString &curveName, QwtPlotCurve::CurveStyle)
void setDataBufferSize (int b)
void setZoomDisabled (bool)
void clearPlot ()
virtual void setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
virtual void setData (const QString &curveName, double *xData, double *yData, int size)
virtual void appendData (const QString &curveName, double x, double y)
virtual void insertData (const QString &curveName, double *xData, double *yData, int size, double default_y=0.0)
insert data into the plot ordered by x values
void setRefreshTimeout (int millis)
void setDefaultBounds (double lb, double ub, Axis axisId=QwtPlot::yLeft)
void restoreDefaultBounds (Axis axisId=QwtPlot::yLeft)
restores the bounds set with setDefaultBounds
void setAxisScaleDefaultEnabled (bool en, Axis axisId=QwtPlot::yLeft)
Restores the bounds of axisId to their default values if en is true, does nothing if en is false.
void setXAxisAutoscaleEnabled (bool autoscale)
void setYAxisAutoscaleEnabled (bool autoscale)
Signals
void newData (const CuData &)
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
Signals inherited from QuPlotBase
void plotClicked (const QPoint &pt, QwtPlotCurve *closestCurve, double x, double y, const QPoint &curvePoint)
void curveAdded (QuPlotCurve *)
This signal is emitted when a new curve is added to the plot.
void curveRemoved (QuPlotCurve *)
This signal is emitted whenever a curve is removed from the plot via removeCurve.
void markerTextChanged (const QString &yText, const QString &xText="", double x=0.0, double y=0.0)
void markerVisibilityChanged (bool visible)
Public Member Functions
QuTrendPlot (QWidget *w, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuTrendPlot (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
QuTrendPlot (QWidget *parent)
classical constructor with parent widget.
virtual ~QuTrendPlot ()
QString source () const
QStringList sources () const
bool timeScaleDrawEnabled ()
bool showDateOnTimeAxis () const
int period () const
returns the refresh period in milliseconds.
CuContext * getContext () const
Return a reference to the CuContext in use.
void onUpdate (const CuData &d)
void update (const CuData &d)
Public Member Functions inherited from QuPlotBase
QuPlotBase (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
QuPlotBase (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
virtual ~QuPlotBase ()
CurveStyle curvesStyle ()
bool titleOnCanvasEnabled ()
bool xAxisAutoscaleEnabled (QwtPlot::Axis axis=QwtPlot::xBottom)
bool yAxisAutoscaleEnabled (QwtPlot::Axis axis=QwtPlot::yLeft)
double yUpperBound (QwtPlot::Axis axis=QwtPlot::yLeft)
double yLowerBound (QwtPlot::Axis axis=QwtPlot::yLeft)
double xUpperBound (QwtPlot::Axis axis=QwtPlot::xBottom)
double xLowerBound (QwtPlot::Axis axis=QwtPlot::xBottom)
double defaultLowerBound (QwtPlot::Axis axisId=QwtPlot::yLeft) const
double defaultUpperBound (QwtPlot::Axis axisId=QwtPlot::yLeft) const
bool xAxisLogScale (QwtPlot::Axis axis=QwtPlot::xBottom)
bool yAxisLogScale (QwtPlot::Axis axis=QwtPlot::yLeft)
void setXAxisLogScale (bool l, QwtPlot::Axis axis=QwtPlot::xBottom)
void setYAxisLogScale (bool l, QwtPlot::Axis axis=QwtPlot::yLeft)
bool zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
QList< QwtPlotCurve * > curves () const
void addCurve (const QString &curveName, QuPlotCurve *curve)
void removeCurve (const QString &curveName)
Removes the specified curve from the plot, deleting it.
void addCurve (const QString &curveName)
QuPlotCurve * curve (const QString &name)
int dataBufferSize ()
returns the data buffer size.
void hideMarker ()
void appendData (const QString &curveName, double *x, double *y, int size)
int refreshTimeout () const
void configure (const CuData &da)
void setUpdateStrategy (QuWidgetUpdateStrategyI *updateStrategy)
sets or replaces the update strategy (see the strategy design pattern)
void setContextMenuStrategy (QuWidgetContextMenuStrategyI *ctx_menu_strategy)
sets or replaces the context menu strategy (see the strategy design pattern)
QuWidgetUpdateStrategyI * updateStrategy () const
return the QuWidgetUpdateStrategyI implementation in use.
QuWidgetContextMenuStrategyI * contextMenuStrategy () const
return the QuWidgetContextMenuStrategyI implementation in use.
virtual QDialog * createConfigureDialog ()
virtual bool updateMarker ()
updates the marker, if visible, and returns true if it's visible, false otherwise
virtual bool updateScales ()
Updates the axes bounds for which autoscale is enabled.
void resetZoom ()
bool inZoom () const
QuPlotComponent * getComponent (const QString &name) const
returns the QuPlotComponent corresponding to the given name, nullptr if name is not valid
void registerComponent (QuPlotComponent *, const QString &name)
QuPlotComponent * unregisterComponent (const QString &name)
QuPlotBase::unregisterComponent unregister the component with the given name.
Public Member Functions inherited from QuWidgetInterface
virtual ~QuWidgetInterface ()
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
QString source
QStringList sources
int period
bool timeScaleDrawEnabled
bool showDateOnTimeAxis
Properties inherited from QuPlotBase
bool xAxisAutoscale
bool yAxisAutoscale
double yUpperBound
double yLowerBound
double xUpperBound
double xLowerBound
double xAutoscaleMargin
double yAutoscaleAdjustment
bool titleOnCanvasEnabled
bool yAxisLogScale
bool zoomDisabled
int dataBufferSize
int refreshTimeout
Additional Inherited Members
Public Types inherited from QuPlotBase
enum CurveStyle {
NoCurve , Lines , Sticks , Steps ,
Dots , UserCurve = 100
}
Protected Slots inherited from QuPlotBase
void displayZoomHint ()
void eraseZoomHint ()
void plotZoomed (const QRectF &)
void showMarker (const QPolygon &p)
void print ()
void snapshot ()
void copyImage ()
virtual void configurePlot ()
void saveData ()
dumps the curves into a csv file.
Protected Member Functions inherited from QuPlotBase
virtual QString plotTitle ()
returns the plot title.
virtual void drawCanvas (QPainter *p)
void mouseReleaseEvent (QMouseEvent *ev)
void keyPressEvent (QKeyEvent *ke)
void moveCurveToYRight (QwtPlotCurve *c, bool yr)
virtual void init ()
void contextMenuEvent (QContextMenuEvent *)
QuPlotBase::contextMenuEvent executes a contextual menu when the plot is right clicked.
void us_to_ms (std::vector< double > &ts_us) const
convert input vector of timestamps in microseconds to a vector of timestamps in milliseconds
Detailed Description
Draw a line for each data source over time.
QuTrendPlot is designed to accept a list of data sources. Each data source is represented by a curve in the plot, which is updated according to the CuData "value" and "timestamp_ms" properties. If CuData "err" flag is true, the associated curve will be decorated accordingly.
Plot update strategies.
Any implementation-specific data update is delegated to an update strategy through setUpdateStrategy. If no update strategy is set, then the update method is called from within onUpdate and the base operations aforementioned are performed. Strategies must implement QuWidgetUpdateStrategyI interface.
Attach notes to specific x values on the plot \since v1.1
If data received by the onUpdate method contains the following keys
notes_time_scale_ms (scalar or vector of timestamps as double)
notes (string scalar or vector) and the size of the two values is equal, a note is associated to each
See also
QuPlotBase
Constructor & Destructor Documentation
QuTrendPlot() [1/3]
QuTrendPlot::QuTrendPlot (QWidget * w, Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuTrendPlot() [2/3]
QuTrendPlot::QuTrendPlot (QWidget * w, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuTrendPlot() [3/3]
QuTrendPlot::QuTrendPlot (QWidget * parent)
classical constructor with parent widget.
Note
QuApplication is mandatory.
References QuApplication::cumbiaPool(), and QuApplication::fpool().
~QuTrendPlot()
QuTrendPlot::~QuTrendPlot () virtual
Member Function Documentation
addSource
void QuTrendPlot::addSource (const QString & s) slot
ctxSwap
bool QuTrendPlot::ctxSwap (CumbiaPool * cu_p, const CuControlsFactoryPool & fpool) virtual slot
getContext()
CuContext * QuTrendPlot::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
Referenced by unsetSources().
linkStatsRequest
void QuTrendPlot::linkStatsRequest (QWidget * myself, CuContextI * myself_as_cwi) signal
Referenced by requestLinkStats().
newData
void QuTrendPlot::newData (const CuData &) signal
Referenced by onUpdate().
onUpdate()
void QuTrendPlot::onUpdate (const CuData & d)
References newData(), update(), QuWidgetUpdateStrategyI::update(), and QuPlotBase::updateStrategy().
period()
int QuTrendPlot::period () const
returns the refresh period in milliseconds.
Returns
the refresh period, in milliseconds.
Note
The value is taken from the CuContext::options "period" key.
Get period: method II
An alternative way to get the actual period used by the poller is the following
CuData d_inout(TTT::Period, -1);  // CuData d_inout("period", -1)
int period = d->plot_common->getContext()->getData(d_inout);
This second method requires an initialized CuContext link (i.e. after setSource).
refresh
void QuTrendPlot::refresh () slot
Updates the marker and the scales. If the scales are not changed and the marker is not viisble, then the replot is performed incrementally.
If a full replot is needed (a marker is visible or a scale has changed), QwtPlot::replot is called. An incremental draw is performed otherwise.
References QuPlotBase::curves(), QuPlotBase::resetZoom(), QuPlotBase::updateMarker(), and QuPlotBase::updateScales().
requestLinkStats
void QuTrendPlot::requestLinkStats () slot
References linkStatsRequest().
setPeriod
void QuTrendPlot::setPeriod (int p) slot
setShowDateOnTimeAxis
void QuTrendPlot::setShowDateOnTimeAxis (bool en) slot
setSource
void QuTrendPlot::setSource (const QString & s) slot
Set the source name. Replcace currently configured sources, if any.
Connect the plot to the source (or sources) specified. More than one source can be set using a ";" separator.
See also
setSources
References setSources(), and unsetSources().
setSources
void QuTrendPlot::setSources (const QStringList & l) slot
Set a list of sources to display on the plot. Replace currently configured ones, if any.
Parameters
l a list of strings with the source names.
References unsetSources().
Referenced by setSource().
setTimeScaleDrawEnabled
void QuTrendPlot::setTimeScaleDrawEnabled (bool enable) slot
showDateOnTimeAxis()
bool QuTrendPlot::showDateOnTimeAxis () const
source()
QString QuTrendPlot::source () const
References sources.
sources()
QStringList QuTrendPlot::sources () const
timeScaleDrawEnabled()
bool QuTrendPlot::timeScaleDrawEnabled ()
unsetSource
void QuTrendPlot::unsetSource (const QString & s) slot
References QuPlotBase::removeCurve().
unsetSources
void QuTrendPlot::unsetSources () slot
References getContext(), QuPlotBase::removeCurve(), and CuControlsReaderA::source().
Referenced by setSource(), and setSources().
update()
void QuTrendPlot::update (const CuData & d) virtual
Reimplemented from QuPlotBase.
References QuPlotBase::addCurve(), CuLinkStats::addError(), CuLinkStats::addOperation(), QuPlotBase::appendData(), QuPlotBase::configure(), QuPlotBase::curve(), QuPlotBase::insertData(), QuPlotCurve::Invalid, QuPlotCurve::lastValue(), QuPlotCurve::Normal, QuPlotCurve::setState(), QuPlotCurve::setText(), QuPlotCurve::size(), QuPlotBase::us_to_ms(), QuPlotCurve::x(), and QuPlotBase::yLowerBound.
Referenced by onUpdate().
Property Documentation
period
int QuTrendPlot::period read write
showDateOnTimeAxis
bool QuTrendPlot::showDateOnTimeAxis read write
source
QString QuTrendPlot::source read write
sources
QStringList QuTrendPlot::sources read write
Referenced by source().
timeScaleDrawEnabled
bool QuTrendPlot::timeScaleDrawEnabled read write
The documentation for this class was generated from the following files:
qutrendplot.h
qutrendplot.cpp