cumbia-qtcontrols: QuTable Class Reference
QuTable Class Reference
Display widgets
A widget to organise data in a table.
#include <qutable.h>
Public Slots
void setSource (const QString &s)
void unsetSource ()
Signals
void linkStatsRequest (QWidget *myself, CuContextI *myself_as_cwi)
void newData (const CuData &da)
Public Member Functions
QuTable (QWidget *w, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
QuTable (QWidget *w, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
virtual ~QuTable ()
QString source () const
int maximumLength () const
void getData (CuData &d_inout) const
CuContext * getContext () const
Return a reference to the CuContext in use.
void setOptions (const CuData &data)
void onUpdate (const CuData &d)
Public Member Functions inherited from EFlag
EFlag (QWidget *parent)
void setValue (QVariant v, bool ref=true)
QList< QVariant > readValue () const
void setDisplayMask (QString var)
const QString getDisplayMask ()
void setDisplayMask (QList< unsigned int > m)
void setDisplayMask (QList< QList< unsigned int > > qlql)
void initDisplayMask (void)
QList< QList< unsigned int > > displayMask () const
void setNumRows (int rows)
int readNumRows () const
void setNumColumns (int columns)
int readNumColumns () const
void setBooleanDisplay (int i, QString falseString, QString trueString, QColor falseColor, QColor trueColor)
void setEnumDisplay (int cell, unsigned int value, QString corresponding_str, QColor corresponding_color)
void setTrueStrings (QString s)
QString trueStrings ()
void setFalseStrings (QString s)
QString falseStrings ()
void setTrueColors (QString c)
QString trueColors ()
void setFalseColors (QString c)
QString falseColors ()
void setTrueColorList (const QList< QColor > &cl)
set the list of true colours specifying a QList of QColor elements
QList< QColor > trueColorList () const
returns the list of true colours, made up of QColor elements.
void setFalseColorList (const QList< QColor > &cl)
set the list of false colours specifying a QList of QColor elements
QList< QColor > falseColorList () const
returns the list of false colours, made up of QColor elements.
void setMouseTracking (bool en)
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Protected Member Functions
void configure (const CuData &da)
void contextMenuEvent (QContextMenuEvent *e)
Protected Member Functions inherited from EFlag
void arrangeCells ()
void configureCells ()
Properties
QString source
Properties inherited from EFlag
int numRows
int numColumns
QString trueColors
QString falseColors
QString trueStrings
QString falseStrings
QString displayMask
Additional Inherited Members
Public Attributes inherited from EFlag
QList< ELabel * > cells
Detailed Description
A widget to organise data in a table.
A default set of options for the object is configured when QuTable is initialised. It includes numRows, numColumns, displayMask, trueColours, falseColours, trueStrings, falseStrings. If they are provided by the underline engine, they are used to configure the table.
Constructor & Destructor Documentation
QuTable() [1/2]
QuTable::QuTable (QWidget * parent, Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac)
Constructor with the parent widget, an engine specific Cumbia implementation and a CuControlsReaderFactoryI interface.
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
QuTable() [2/2]
QuTable::QuTable (QWidget * w, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
Constructor with the parent widget, CumbiaPool and CuControlsFactoryPool
Please refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
~QuTable()
QuTable::~QuTable () virtual
Member Function Documentation
configure()
void QuTable::configure (const CuData & da) protected
References EFlag::displayMask(), EFlag::falseColors(), EFlag::numColumns, EFlag::numRows, EFlag::setDisplayMask(), EFlag::setFalseColorList(), EFlag::setFalseStrings(), EFlag::setNumColumns(), EFlag::setNumRows(), EFlag::setTrueColorList(), EFlag::setTrueStrings(), source(), and EFlag::trueColors().
Referenced by onUpdate().
contextMenuEvent()
void QuTable::contextMenuEvent (QContextMenuEvent * e) protected
getContext()
CuContext * QuTable::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
getData()
void QuTable::getData (CuData & d_inout) const
linkStatsRequest
void QuTable::linkStatsRequest (QWidget * myself, CuContextI * myself_as_cwi) signal
maximumLength()
int QuTable::maximumLength () const
newData
void QuTable::newData (const CuData & da) signal
Referenced by onUpdate().
onUpdate()
void QuTable::onUpdate (const CuData & d)
References EFlag::cells, configure(), newData(), QuLabelBase::setDecoration(), and EFlag::setValue().
setOptions()
void QuTable::setOptions (const CuData & data)
setSource
void QuTable::setSource (const QString & s) slot
References CuControlsReaderA::setSource().
source()
QString QuTable::source () const
Referenced by configure().
unsetSource
void QuTable::unsetSource () slot
Property Documentation
source
QString QuTable::source read write
The documentation for this class was generated from the following files:
qutable.h
qutable.cpp