cumbia-qtcontrols: QuPlotCommon Class Reference
QuPlotCommon Class Reference
Display widgets » Plots
common object owned by cumbia plots used to link and configure a plot.
#include <quplotcommon.h>
Public Member Functions
QuPlotCommon (Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
QuPlotCommon (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
virtual ~QuPlotCommon ()
QColor pick_color (int i)
void setSources (const QStringList &l, CuDataListener *data_listener)
void setSources (const QStringList &l, CuDataListener *data_listener, CuContext *ctx)
void addSource (const QString &s, CuDataListener *dl)
void unsetSource (const QString &src)
QStringList sources () const
void unsetSources ()
void configure (const QString &curveName, const QPointF &pxy)
CuContext * getContext () const
Detailed Description
common object owned by cumbia plots used to link and configure a plot.
Constructor & Destructor Documentation
QuPlotCommon() [1/2]
QuPlotCommon::QuPlotCommon (Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac)
QuPlotCommon() [2/2]
QuPlotCommon::QuPlotCommon (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
~QuPlotCommon()
QuPlotCommon::~QuPlotCommon () virtual
Member Function Documentation
addSource()
void QuPlotCommon::addSource (const QString & s, CuDataListener * dl)
References CuControlsReaderA::setSource().
configure()
void QuPlotCommon::configure (const QString & curveName, const QPointF & pxy)
getContext()
CuContext * QuPlotCommon::getContext () const
pick_color()
QColor QuPlotCommon::pick_color (int i)
setSources() [1/2]
void QuPlotCommon::setSources (const QStringList & l, CuDataListener * data_listener)
References CuControlsReaderA::setSource(), and sources().
Referenced by setSources().
setSources() [2/2]
void QuPlotCommon::setSources (const QStringList & l, CuDataListener * data_listener, CuContext * ctx)
References setSources().
sources()
QStringList QuPlotCommon::sources () const
References CuControlsReaderA::source().
Referenced by setSources().
unsetSource()
void QuPlotCommon::unsetSource (const QString & src)
unsetSources()
void QuPlotCommon::unsetSources ()
The documentation for this class was generated from the following files:
quplotcommon.h
quplotcommon.cpp