cumbia-qtcontrols: QuLinearGaugeBase Class Reference
QuLinearGaugeBase Class Reference
#include <qulineargaugebase.h>
Public Types
enum LabelPosition { NoLabel, East, Center, West }
enum ScaleMode { Normal, Inverted }
enum IndicatorType { Needle, Thermo }
Public Slots
void setLabelPosition (LabelPosition p)
void setIndicatorType (IndicatorType t)
void setScaleMode (ScaleMode sm)
void setValue (double v)
void setReadError (bool re)
void setValue_anim (double v)
void setMinValue (double min)
void setMaxValue (double max)
void setLabel (const QString &l)
void setTicksCount (int t)
void setMinorTicksCount (int t)
void setTickLen (double tl)
Set the tick len as percentage of the radius of the circle.
void setGaugeWidth (double w)
void setArrowSize (double s)
sets the arrow size property
void setThermoWidth (double tw)
sets the thermoWidth property
void setPivotCircleRadius (double percent)
void setDrawBackgroundEnabled (bool en)
void setHighWarning (double w)
void setLowWarning (double w)
void setHighError (double e)
void setLowError (double e)
void setTextColor (const QColor &c)
void setErrorColor (const QColor &ec)
void setWarningColor (const QColor &wc)
void setNormalColor (const QColor &nc)
void setReadErrorColor (const QColor &rec)
void setBackgroundColor (const QColor &bc)
void setNeedleColor (const QColor &c)
void setNeedleGuideColor (const QColor &c)
void setArrowColor (const QColor &c)
sets the arrow fill color
void setThermoColor1 (const QColor &c)
changes the color 1 of the gradient used to draw the bar of a Thermo indicator
void setThermoColor2 (const QColor &c)
changes the color 2 of the gradient used to draw the bar of a Thermo indicator
void setThermoPenColor (const QColor &c)
changes the color used to outline the thermometer bar
void setArrowPenWidth (double pw)
void setTickCoreColor (const QColor &c)
void setBackgroundGradientSpread (double s)
If background drawing is enabled, the spread determines the stop point of the gradient from the current value color (normal, warning or error) and the background color.
void setBackgroundColorAlpha (int a)
void setDrawTickCore1 (bool t)
void setDrawTickCore2 (bool t)
void setDrawColoredTicks (bool dr)
void setDrawText (bool dt)
void setAnimationEnabled (bool ae)
void setMaxAnimationDuration (qint64 millis)
void setLabelValueFormat (const QString &f)
void setUnit (const QString &u)
void setLabelFontScale (double factor)
changes the label font size respect to the size of the text on the gauge
void setFormat (const QString &f)
sets the format to be used on the text along the gauge if the property formatFromProperty enabled is false
void setFormatFromPropertyEnabled (bool ffp)
enables or disables applying format from the configuration CuData
void setFormatProperty (const QString &fp)
sets the format of the text along the gauge to be used when formatFromPropertyEnabled is true
void updateLabelsCache ()
void regenerateCache ()
void updatePaintArea ()
void updateLabelsFontSize ()
Public Member Functions
QuLinearGaugeBase (QWidget *parent=nullptr)
virtual ~QuLinearGaugeBase ()
LabelPosition labelPosition () const
IndicatorType indicatorType () const
ScaleMode scaleMode () const
double value () const
bool readError () const
double value_anim () const
double maxValue () const
double minValue () const
int ticksCount () const
int minorTicksCount () const
double tickLen () const
double gaugeWidth () const
double arrowSize () const
double thermoWidth () const
double pivotCircleRadius () const
bool drawBackgroundEnabled () const
returns true if a background is drawn, false otherwise
bool drawText () const
bool drawTickCore1 () const
bool drawTickCore2 () const
bool drawColoredTicks () const
bool animationEnabled () const
qint64 maxAnimationDuration () const
double labelFontScale () const
double lowWarning ()
double highWarning ()
double lowError ()
double highError ()
QColor textColor () const
QColor warningColor () const
QColor errorColor () const
QColor normalColor () const
QColor readErrorColor () const
QColor backgroundColor () const
QColor needleColor () const
QColor needleGuideColor () const
QColor tickCoreColor () const
QColor arrowColor () const
QColor thermoColor1 () const
QColor thermoColor2 () const
QColor thermoPenColor () const
double arrowPenWidth () const
double backgroundGradientSpread () const
int backgroundColorAlpha () const
Qt::Orientation orientation () const
QString label () const
QString format () const
bool formatFromPropertyEnabled () const
QString getAppliedFormat () const
QString labelValueFormat () const
QString unit () const
double mapTo (double val, const QRectF &paint_area=QRectF())
maps a value to a point along the longest side of the widget rectangle
QRectF textRect (const QRectF &paintArea, int tick)
double labelFontSize ()
virtual QString formatLabel (double val, const char *format) const
QString label (int i) const
QRectF paintArea ()
QSize sizeHint () const
QSize minimumSizeHint () const
bool inWarningRange (double val) const
bool inErrorRange (double val) const
QColor valueColor (double val) const
QRectF labelRect () const
returns the bounding rect of the label or an empty rectangle if the label is not visible
double getGaugeWidth (const QRectF &paint_area) const
returns the gauge width in pixels
double getThermoWidth (const QRectF &paint_area) const
returns the thermometer bar width in pixels
double getTickLen (const QRectF &paint_area) const
returns the (major) tick length, in pixels
QRectF freeSpace (const QRectF &paint_area) const
returns the free area available for custom drawings within the widget
QRectF gaugeRect (const QRectF &paint_area) const
returns the bounding rect of the gauge (union of gauge bar, ticks and text labels)
Protected Member Functions
void paintEvent (QPaintEvent *pe)
virtual void drawText (const QRectF &re, int idx, QPainter &p)
virtual void drawNeedle (double pos, const QRectF &rect, QPainter &p)
Draw the needle.
virtual void drawGauge (const QRectF &rect, QPainter &p)
virtual void drawTicks (const QRectF &rect, QPainter &p)
virtual void drawBackground (const QRectF &rect, QPainter &p)
virtual void drawLabel (const QRectF &rect, QPainter &p)
void resizeEvent (QResizeEvent *re)
void changeEvent (QEvent *e)
Properties
ScaleMode scaleMode
IndicatorType indicatorType
double value
double value_anim
returns the value during the animation
double minValue
returns the minimum value represented by this gauge
double maxValue
returns the maximum value represented by this gauge
bool drawText
either draw or not the labels with the values associated to each major tick
bool animationEnabled
if true, an animation is used to draw the transition between two subsequent setValue calls
qint64 maxAnimationDuration
The maximum duration of an animation between two setValue calls.
double lowWarning
double highWarning
double lowError
double highError
int ticksCount
returns the number of major ticks drawn in the arc
int minorTicksCount
returns the number of minor ticks drawn between each couple of major ticks
double tickLen
returns the tick length
double pivotCircleRadius
the factor multiplies tickLen to obtain the radius for the circle drawn at the base of the needle.
double gaugeWidth
returns the width of the gauge strip
bool drawBackground
bool drawTickCore1
draw a tick inside the gauge arc
bool drawTickCore2
draw a tick from the inner border of the gauge arc
bool drawColoredTicks
draw colored ticks
double arrowSize
returns the arrow size, percentage
double thermoWidth
returns the width of the thermometer bar, when indicatorMode is set to Thermo
QString format
bool formatFromPropertyEnabled
QColor textColor
QColor warningColor
QColor tickCoreColor
QColor errorColor
QColor normalColor
QColor readErrorColor
QColor backgroundColor
QColor needleColor
QColor needleGuideColor
returns the color of the needle guide, that is drawn along the longest widget side and crosses the needle pivot center
QColor arrowColor
returns the arrow fill color.
QColor thermoColor1
Sets the color 1 (inner color) used to draw the gradient for the thermo bar.
QColor thermoColor2
Sets the color 2 (outer color) used to draw the gradient for the thermo bar.
QColor thermoPenColor
returns the pen color used to outline the thermometer bar in the gauge indicator
double arrowPenWidth
int backgroundColorAlpha
double backgroundGradientSpread
QString label
LabelPosition labelPosition
QString labelValueFormat
QString unit
double labelFontScale
scales the label font respect to the font size of the text on the gauge
Member Enumeration Documentation
IndicatorType
enum QuLinearGaugeBase::IndicatorType
Enumerator
Needle
Thermo
LabelPosition
enum QuLinearGaugeBase::LabelPosition
Enumerator
NoLabel
East
Center
West
ScaleMode
enum QuLinearGaugeBase::ScaleMode
Enumerator
Normal
Inverted
Constructor & Destructor Documentation
QuLinearGaugeBase()
QuLinearGaugeBase::QuLinearGaugeBase (QWidget * parent = nullptr) explicit
References QuGaugeConfig::gaugeWidth, Needle, NoLabel, Normal, QuGaugeConfig::pivotRadius, QuGaugeConfig::tickLen, and QuGaugeConfig::ticksCount.
~QuLinearGaugeBase()
QuLinearGaugeBase::~QuLinearGaugeBase () virtual
Member Function Documentation
animationEnabled()
bool QuLinearGaugeBase::animationEnabled () const
arrowColor()
QColor QuLinearGaugeBase::arrowColor () const
arrowPenWidth()
double QuLinearGaugeBase::arrowPenWidth () const
arrowSize()
double QuLinearGaugeBase::arrowSize () const
backgroundColor()
QColor QuLinearGaugeBase::backgroundColor () const
backgroundColorAlpha()
int QuLinearGaugeBase::backgroundColorAlpha () const
backgroundGradientSpread()
double QuLinearGaugeBase::backgroundGradientSpread () const
changeEvent()
void QuLinearGaugeBase::changeEvent (QEvent * e) protected
References regenerateCache().
drawBackground()
void QuLinearGaugeBase::drawBackground (const QRectF & rect, QPainter & p) protected virtual
References QuGaugeConfig::backgroundColor, QuGaugeConfig::backgroundColorAlpha, QuGaugeConfig::backgroundGradientSpread, QuGaugeConfig::value, and valueColor().
drawBackgroundEnabled()
bool QuLinearGaugeBase::drawBackgroundEnabled () const
returns true if a background is drawn, false otherwise
Returns
true the gauge draws a background with a radial gradient between the color associated the current value (see inErrorRange, inWarningRange, inNormalRange) and the color chosen with setBackgroundColor.
Three warning levels can be displayed by the gauge arc:
normal
warning
alarm (error)
Setting the drawBackgroundEnabled property to true enhances the detection of the current value quality.
See also
backgroundColor
References QuGaugeConfig::drawBackground.
drawColoredTicks()
bool QuLinearGaugeBase::drawColoredTicks () const
drawGauge()
void QuLinearGaugeBase::drawGauge (const QRectF & rect, QPainter & p) protected virtual
References QuGaugeConfig::errorColor, QuGaugeConfig::gaugeWidth, QuGaugeConfig::high_e, QuGaugeConfig::high_w, QuGaugeConfig::low_e, QuGaugeConfig::low_w, mapTo(), QuGaugeConfig::max, QuGaugeConfig::min, QuGaugeConfig::normalColor, QuGaugeConfig::readErrorColor, and QuGaugeConfig::warningColor.
Referenced by paintEvent().
drawLabel()
void QuLinearGaugeBase::drawLabel (const QRectF & rect, QPainter & p) protected virtual
References Elettra::black, Center, East, formatLabel(), freeSpace(), getThermoWidth(), QuGaugeConfig::unit, QuGaugeConfig::value, and West.
Referenced by paintEvent().
drawNeedle()
void QuLinearGaugeBase::drawNeedle (double pos, const QRectF & rect, QPainter & p) protected virtual
Draw the needle.
This method can be reimplemented to draw custom needles
Parameters
end the end of the needle
angle the angle of the needle, zero at three o'clock
rect the bounding rect of the drawing area
p the painter
Note
In the default implementation, the needle starts from the center of the rect
References QuGaugeConfig::arrowColor, QuGaugeConfig::arrowPenWidth, QuGaugeConfig::arrowSize, Elettra::darkGray, gaugeRect(), getThermoWidth(), indicatorType(), Inverted, Needle, QuGaugeConfig::needleColor, QuGaugeConfig::needleGuideColor, NoLabel, QuGaugeConfig::pivotRadius, Thermo, QuGaugeConfig::thermoColor1, QuGaugeConfig::thermoColor2, QuGaugeConfig::thermoPenColor, QuGaugeConfig::tickLen, and Elettra::white.
Referenced by paintEvent().
drawText() [1/2]
bool QuLinearGaugeBase::drawText () const
Referenced by paintEvent().
drawText() [2/2]
void QuLinearGaugeBase::drawText (const QRectF & re, int idx, QPainter & p) protected virtual
References label(), labelFontSize(), QuGaugeConfig::textColor, and textRect().
drawTickCore1()
bool QuLinearGaugeBase::drawTickCore1 () const
drawTickCore2()
bool QuLinearGaugeBase::drawTickCore2 () const
drawTicks()
void QuLinearGaugeBase::drawTicks (const QRectF & rect, QPainter & p) protected virtual
References QuGaugeConfig::drawColoredTicks, QuGaugeConfig::drawTickCore1, QuGaugeConfig::drawTickCore2, QuGaugeConfig::errorColor, QuGaugeConfig::gaugeWidth, inErrorRange(), Inverted, inWarningRange(), QuGaugeConfig::max, QuGaugeConfig::min, QuGaugeConfig::minorTicksCount, Normal, QuGaugeConfig::normalColor, QuGaugeConfig::tickCoreColor, QuGaugeConfig::tickLen, tickLen(), QuGaugeConfig::ticksCount, ticksCount(), and QuGaugeConfig::warningColor.
Referenced by paintEvent().
errorColor()
QColor QuLinearGaugeBase::errorColor () const
format()
QString QuLinearGaugeBase::format () const
Referenced by formatLabel().
formatFromPropertyEnabled()
bool QuLinearGaugeBase::formatFromPropertyEnabled () const
formatLabel()
QString QuLinearGaugeBase::formatLabel (double val, const char * format) const virtual
References format(), and value().
Referenced by drawLabel(), and updateLabelsCache().
freeSpace()
QRectF QuLinearGaugeBase::freeSpace (const QRectF & paint_area) const
returns the free area available for custom drawings within the widget
Returns
the the free area available for custom drawings within the widget
Parameters
paint_area const reference to the current paint area
See also
paintArea
Note
If the labelPosition property is different from LabelPosition::None, the label will be drawn inside the freeSpaceRect area. You must call labelRect before adding custom drawings to the widget to be sure your drawing does not collide with the label.
References gaugeRect().
Referenced by drawLabel().
gaugeRect()
QRectF QuLinearGaugeBase::gaugeRect (const QRectF & paint_area) const
returns the bounding rect of the gauge (union of gauge bar, ticks and text labels)
Parameters
paint_area const reference to the current paint area
See also
paintArea
Returns
the rectangle including the union of the areas occupied by the gauge bar, the ticks and the text labels of the scale
References getGaugeWidth(), Inverted, Normal, and QuGaugeConfig::tickLen.
Referenced by drawNeedle(), freeSpace(), and updateLabelsFontSize().
gaugeWidth()
double QuLinearGaugeBase::gaugeWidth () const
getAppliedFormat()
QString QuLinearGaugeBase::getAppliedFormat () const
References QuGaugeConfig::format, QuGaugeConfig::format_from_property, and QuGaugeConfig::format_prop.
getGaugeWidth()
double QuLinearGaugeBase::getGaugeWidth (const QRectF & paint_area) const
returns the gauge width in pixels
Returns
the gauge width, in pixels, calculated with the expression <cite>gaugeWidth * (paintArea height)</cite>
Parameters
paint_area const reference to the current paint area
See also
paintArea
References QuGaugeConfig::gaugeWidth.
Referenced by gaugeRect(), and textRect().
getThermoWidth()
double QuLinearGaugeBase::getThermoWidth (const QRectF & paint_area) const
returns the thermometer bar width in pixels
Returns
the thermometer bar width in pixels or 0 if the indicatorType is not Thermo
Parameters
paint_area const reference to the current paint area
See also
paintArea
References Thermo, and QuGaugeConfig::thermo_width.
Referenced by drawLabel(), and drawNeedle().
getTickLen()
double QuLinearGaugeBase::getTickLen (const QRectF & paint_area) const
returns the (major) tick length, in pixels
Returns
the length in pixels of the major ticks, calculated with the formula <cite>tickLen * (paint_area.height)</cite>
Parameters
paint_area const reference to the current paint area
See also
paintArea
References QuGaugeConfig::tickLen.
Referenced by updateLabelsFontSize().
highError()
double QuLinearGaugeBase::highError ()
highWarning()
double QuLinearGaugeBase::highWarning ()
indicatorType()
IndicatorType QuLinearGaugeBase::indicatorType () const
Referenced by drawNeedle().
inErrorRange()
bool QuLinearGaugeBase::inErrorRange (double val) const
References QuGaugeConfig::high_e, and QuGaugeConfig::low_e.
Referenced by drawTicks(), and valueColor().
inWarningRange()
bool QuLinearGaugeBase::inWarningRange (double val) const
References QuGaugeConfig::high_e, QuGaugeConfig::high_w, QuGaugeConfig::low_e, and QuGaugeConfig::low_w.
Referenced by drawTicks(), and valueColor().
label() [1/2]
QString QuLinearGaugeBase::label () const
Referenced by drawText().
label() [2/2]
QString QuLinearGaugeBase::label (int i) const
labelFontScale()
double QuLinearGaugeBase::labelFontScale () const
labelFontSize()
double QuLinearGaugeBase::labelFontSize ()
References regenerateCache().
Referenced by drawText().
labelPosition()
LabelPosition QuLinearGaugeBase::labelPosition () const
labelRect()
QRectF QuLinearGaugeBase::labelRect () const
returns the bounding rect of the label or an empty rectangle if the label is not visible
labelValueFormat()
QString QuLinearGaugeBase::labelValueFormat () const
lowError()
double QuLinearGaugeBase::lowError ()
lowWarning()
double QuLinearGaugeBase::lowWarning ()
mapTo()
double QuLinearGaugeBase::mapTo (double val, const QRectF & paint_area = QRectF())
maps a value to a point along the longest side of the widget rectangle
Returns
a QPointF close to the arc of the gauge. How close it is to the arc is determined by tickLen: the point will be distant 1.2 * tickLen from the arc
Parameters
val the value set on the widget
angle a pointer to a double that will store the angle, in degrees, from the 3 o'clock axis to the needle (if angle is not NULL)
radius if greater than 0, the parameter is used to return a point with such distance from the center. Otherwise, radius is assumed to be equal to the paint area width divided by two.
paint_area if valid, it is used for the calculation. Otherwise the paintArea method is used to recalculate the paint area
References QuGaugeConfig::max, QuGaugeConfig::min, and paintArea().
Referenced by drawGauge(), paintEvent(), and textRect().
maxAnimationDuration()
qint64 QuLinearGaugeBase::maxAnimationDuration () const
maxValue()
double QuLinearGaugeBase::maxValue () const
minimumSizeHint()
QSize QuLinearGaugeBase::minimumSizeHint () const
References QuGaugeConfig::minFontSize, NoLabel, orientation(), and QuGaugeConfig::ticksCount.
minorTicksCount()
int QuLinearGaugeBase::minorTicksCount () const
minValue()
double QuLinearGaugeBase::minValue () const
needleColor()
QColor QuLinearGaugeBase::needleColor () const
needleGuideColor()
QColor QuLinearGaugeBase::needleGuideColor () const
normalColor()
QColor QuLinearGaugeBase::normalColor () const
orientation()
Qt::Orientation QuLinearGaugeBase::orientation () const
Referenced by minimumSizeHint(), and updatePaintArea().
paintArea()
QRectF QuLinearGaugeBase::paintArea ()
References updatePaintArea().
Referenced by mapTo(), paintEvent(), textRect(), and updateLabelsFontSize().
paintEvent()
void QuLinearGaugeBase::paintEvent (QPaintEvent * pe) protected
References QuGaugeConfig::drawBackground, drawBackground, drawGauge(), drawLabel(), drawNeedle(), QuGaugeConfig::drawText, drawText(), drawTicks(), Elettra::lightGray, mapTo(), NoLabel, paintArea(), and QuGaugeConfig::value_anim.
pivotCircleRadius()
double QuLinearGaugeBase::pivotCircleRadius () const
readError()
bool QuLinearGaugeBase::readError () const
readErrorColor()
QColor QuLinearGaugeBase::readErrorColor () const
regenerateCache
void QuLinearGaugeBase::regenerateCache () slot
References updateLabelsCache(), updateLabelsFontSize(), and updatePaintArea().
Referenced by changeEvent(), labelFontSize(), resizeEvent(), setFormat(), setFormatFromPropertyEnabled(), setFormatProperty(), setLabel(), setMaxValue(), setMinValue(), setTickLen(), and setTicksCount().
resizeEvent()
void QuLinearGaugeBase::resizeEvent (QResizeEvent * re) protected
References regenerateCache().
scaleMode()
ScaleMode QuLinearGaugeBase::scaleMode () const
setAnimationEnabled
void QuLinearGaugeBase::setAnimationEnabled (bool ae) slot
References QuGaugeConfig::animationEnabled.
setArrowColor
void QuLinearGaugeBase::setArrowColor (const QColor & c) slot
sets the arrow fill color
See also
arrowColor
References QuGaugeConfig::arrowColor.
setArrowPenWidth
void QuLinearGaugeBase::setArrowPenWidth (double pw) slot
References QuGaugeConfig::arrowPenWidth.
setArrowSize
void QuLinearGaugeBase::setArrowSize (double s) slot
sets the arrow size property
The arrow size will be propotional to the major tick length (tickLen property) A value of 1.0 will produce an arrow which side is equal to the tick length
See also
arrowSize
References QuGaugeConfig::arrowSize.
setBackgroundColor
void QuLinearGaugeBase::setBackgroundColor (const QColor & bc) slot
References QuGaugeConfig::backgroundColor.
setBackgroundColorAlpha
void QuLinearGaugeBase::setBackgroundColorAlpha (int a) slot
References QuGaugeConfig::backgroundColorAlpha.
setBackgroundGradientSpread
void QuLinearGaugeBase::setBackgroundGradientSpread (double s) slot
If background drawing is enabled, the spread determines the stop point of the gradient from the current value color (normal, warning or error) and the background color.
Parameters
s the gradient stop, greater than 0 and less than or equal to 1
See also
setBackgroundColor
drawBackgroundEnabled
backgroundColor
References QuGaugeConfig::backgroundGradientSpread.
setDrawBackgroundEnabled
void QuLinearGaugeBase::setDrawBackgroundEnabled (bool en) slot
References QuGaugeConfig::drawBackground.
setDrawColoredTicks
void QuLinearGaugeBase::setDrawColoredTicks (bool dr) slot
References QuGaugeConfig::drawColoredTicks.
setDrawText
void QuLinearGaugeBase::setDrawText (bool dt) slot
References QuGaugeConfig::drawText.
setDrawTickCore1
void QuLinearGaugeBase::setDrawTickCore1 (bool t) slot
References QuGaugeConfig::drawTickCore1.
setDrawTickCore2
void QuLinearGaugeBase::setDrawTickCore2 (bool t) slot
References QuGaugeConfig::drawTickCore2.
setErrorColor
void QuLinearGaugeBase::setErrorColor (const QColor & ec) slot
References QuGaugeConfig::errorColor.
setFormat
void QuLinearGaugeBase::setFormat (const QString & f) slot
sets the format to be used on the text along the gauge if the property formatFromProperty enabled is false
Parameters
f the format used if formatFromProperty is false
If formatFromProperty is true, the format is applied according to the value of the "format" key in the configuration CuData for the given source.
Note
The configuration CuData is the one where the type key has the property value
See also
setFormatFromPropertyEnabled
References QuGaugeConfig::format, and regenerateCache().
setFormatFromPropertyEnabled
void QuLinearGaugeBase::setFormatFromPropertyEnabled (bool ffp) slot
enables or disables applying format from the configuration CuData
Parameters
ffp true the format of the text along the gauge is taken by the source properties.
ffp false the format of the text along the gauge is taken by the format property
See also
format
formatFromPropertyEnabled
References QuGaugeConfig::format_from_property, and regenerateCache().
setFormatProperty
void QuLinearGaugeBase::setFormatProperty (const QString & fp) slot
sets the format of the text along the gauge to be used when formatFromPropertyEnabled is true
Parameters
fp the format to be applied to the numbers along the gauge when formatFromPropertyEnabled is true
note
This method is called by QuLinearGauge when a CuData has the value "property" associated to the key "type"
See also
setFormatFromPropertyEnabled
References QuGaugeConfig::format_prop, and regenerateCache().
setGaugeWidth
void QuLinearGaugeBase::setGaugeWidth (double w) slot
References QuGaugeConfig::gaugeWidth.
setHighError
void QuLinearGaugeBase::setHighError (double e) slot
References QuGaugeConfig::high_e.
setHighWarning
void QuLinearGaugeBase::setHighWarning (double w) slot
References QuGaugeConfig::high_w.
setIndicatorType
void QuLinearGaugeBase::setIndicatorType (QuLinearGaugeBase::IndicatorType t) slot
setLabel
void QuLinearGaugeBase::setLabel (const QString & l) slot
References regenerateCache().
setLabelFontScale
void QuLinearGaugeBase::setLabelFontScale (double factor) slot
changes the label font size respect to the size of the text on the gauge
Parameters
factor the label font scale value, > 0 and <= 2.
The font size of the text on the gauge is scaled by this factor.
Note
The default value is 0.9
setLabelPosition
void QuLinearGaugeBase::setLabelPosition (QuLinearGaugeBase::LabelPosition p) slot
setLabelValueFormat
void QuLinearGaugeBase::setLabelValueFormat (const QString & f) slot
setLowError
void QuLinearGaugeBase::setLowError (double e) slot
References QuGaugeConfig::low_e.
setLowWarning
void QuLinearGaugeBase::setLowWarning (double w) slot
References QuGaugeConfig::low_w.
setMaxAnimationDuration
void QuLinearGaugeBase::setMaxAnimationDuration (qint64 millis) slot
References QuGaugeConfig::maximumAnimDuration.
setMaxValue
void QuLinearGaugeBase::setMaxValue (double max) slot
References QuGaugeConfig::max, QuGaugeConfig::min, and regenerateCache().
setMinorTicksCount
void QuLinearGaugeBase::setMinorTicksCount (int t) slot
References QuGaugeConfig::minorTicksCount.
setMinValue
void QuLinearGaugeBase::setMinValue (double min) slot
References QuGaugeConfig::min, and regenerateCache().
setNeedleColor
void QuLinearGaugeBase::setNeedleColor (const QColor & c) slot
References QuGaugeConfig::needleColor.
setNeedleGuideColor
void QuLinearGaugeBase::setNeedleGuideColor (const QColor & c) slot
References QuGaugeConfig::needleGuideColor.
setNormalColor
void QuLinearGaugeBase::setNormalColor (const QColor & nc) slot
References QuGaugeConfig::normalColor.
setPivotCircleRadius
void QuLinearGaugeBase::setPivotCircleRadius (double percent) slot
References QuGaugeConfig::pivotRadius.
setReadError
void QuLinearGaugeBase::setReadError (bool re) slot
Referenced by QuLinearGauge::onUpdate().
setReadErrorColor
void QuLinearGaugeBase::setReadErrorColor (const QColor & rec) slot
References QuGaugeConfig::readErrorColor.
setScaleMode
void QuLinearGaugeBase::setScaleMode (QuLinearGaugeBase::ScaleMode sm) slot
setTextColor
void QuLinearGaugeBase::setTextColor (const QColor & c) slot
References QuGaugeConfig::textColor.
setThermoColor1
void QuLinearGaugeBase::setThermoColor1 (const QColor & c) slot
changes the color 1 of the gradient used to draw the bar of a Thermo indicator
See also
thermoColor1
References QuGaugeConfig::thermoColor1.
setThermoColor2
void QuLinearGaugeBase::setThermoColor2 (const QColor & c) slot
changes the color 2 of the gradient used to draw the bar of a Thermo indicator
See also
thermoColor2
References QuGaugeConfig::thermoColor2.
setThermoPenColor
void QuLinearGaugeBase::setThermoPenColor (const QColor & c) slot
changes the color used to outline the thermometer bar
Note
applies to QuLineargauge with the property indicatorMode equal to QuLinearGaugeBase::Thermo
References QuGaugeConfig::thermoPenColor.
setThermoWidth
void QuLinearGaugeBase::setThermoWidth (double tw) slot
sets the thermoWidth property
Parameters
tw the new thermoWidth value, fraction of the widget's smallest side
Note
This applies to linear gauges with indicatorMode property equal to Thermo
See also
thermoWidth
References QuGaugeConfig::thermo_width.
setTickCoreColor
void QuLinearGaugeBase::setTickCoreColor (const QColor & c) slot
References QuGaugeConfig::tickCoreColor.
setTickLen
void QuLinearGaugeBase::setTickLen (double tl) slot
Set the tick len as percentage of the radius of the circle.
Parameters
tl a value between 0 and 1 representing the length of a tick with respect to the length of the radius
References regenerateCache(), and QuGaugeConfig::tickLen.
setTicksCount
void QuLinearGaugeBase::setTicksCount (int t) slot
References regenerateCache(), and QuGaugeConfig::ticksCount.
setUnit
void QuLinearGaugeBase::setUnit (const QString & u) slot
References QuGaugeConfig::unit.
setValue
void QuLinearGaugeBase::setValue (double v) slot
References QuGaugeConfig::animationEnabled, QuGaugeConfig::maximumAnimDuration, QuGaugeConfig::value, and QuGaugeConfig::value_anim.
setValue_anim
void QuLinearGaugeBase::setValue_anim (double v) slot
References QuGaugeConfig::value_anim.
setWarningColor
void QuLinearGaugeBase::setWarningColor (const QColor & wc) slot
References QuGaugeConfig::warningColor.
sizeHint()
QSize QuLinearGaugeBase::sizeHint () const
textColor()
QColor QuLinearGaugeBase::textColor () const
textRect()
QRectF QuLinearGaugeBase::textRect (const QRectF & paintArea, int tick)
FARE thermo indicator controllare minimum size (+ hint)
References getGaugeWidth(), mapTo(), QuGaugeConfig::max, QuGaugeConfig::min, Normal, paintArea(), QuGaugeConfig::tickLen, tickLen(), and QuGaugeConfig::ticksCount.
Referenced by drawText().
thermoColor1()
QColor QuLinearGaugeBase::thermoColor1 () const
thermoColor2()
QColor QuLinearGaugeBase::thermoColor2 () const
thermoPenColor()
QColor QuLinearGaugeBase::thermoPenColor () const
thermoWidth()
double QuLinearGaugeBase::thermoWidth () const
tickCoreColor()
QColor QuLinearGaugeBase::tickCoreColor () const
tickLen()
double QuLinearGaugeBase::tickLen () const
Referenced by drawTicks(), and textRect().
ticksCount()
int QuLinearGaugeBase::ticksCount () const
Referenced by drawTicks().
unit()
QString QuLinearGaugeBase::unit () const
updateLabelsCache
void QuLinearGaugeBase::updateLabelsCache () slot
References QuGaugeConfig::format, formatLabel(), QuGaugeConfig::max, QuGaugeConfig::min, and QuGaugeConfig::ticksCount.
Referenced by regenerateCache().
updateLabelsFontSize
void QuLinearGaugeBase::updateLabelsFontSize () slot
References gaugeRect(), getTickLen(), Normal, paintArea(), and QuGaugeConfig::ticksCount.
Referenced by regenerateCache().
updatePaintArea
void QuLinearGaugeBase::updatePaintArea () slot
References orientation().
Referenced by paintArea(), and regenerateCache().
value()
double QuLinearGaugeBase::value () const
Referenced by formatLabel().
value_anim()
double QuLinearGaugeBase::value_anim () const
valueColor()
QColor QuLinearGaugeBase::valueColor (double val) const
References QuGaugeConfig::errorColor, inErrorRange(), inWarningRange(), QuGaugeConfig::normalColor, and QuGaugeConfig::warningColor.
Referenced by drawBackground().
warningColor()
QColor QuLinearGaugeBase::warningColor () const
Property Documentation
animationEnabled
bool QuLinearGaugeBase::animationEnabled read write
if true, an animation is used to draw the transition between two subsequent setValue calls
Returns
true the needle is animated when moving from its current position to the new position specified with setValue false the needle abruptly moves to the new value
Special note
The maximum duration of the animation is determined by the value, in milliseconds, of the maxAnimationDuration property. If two setValue calls take place within a shorter interval, that interval is used to animate the transition instead.
See also
maxAnimationDuration
arrowColor
QColor QuLinearGaugeBase::arrowColor read write
returns the arrow fill color.
The arrow is filled with the arrowColor color. Its outline is drawn with the needleColor
Note
The default colour is white for the arrow fill with an alpha of 150
See also
needleColor
arrowSize
arrowPenWidth
double QuLinearGaugeBase::arrowPenWidth read write
arrowSize
double QuLinearGaugeBase::arrowSize read write
returns the arrow size, percentage
arrowSize property expresses the size of the arrow respect to the tickLen An arrowSize of 1.0 will produce an arrow with the side equal to the (major) tickLen
See also
setArrowSize
backgroundColor
QColor QuLinearGaugeBase::backgroundColor read write
backgroundColorAlpha
int QuLinearGaugeBase::backgroundColorAlpha read write
backgroundGradientSpread
double QuLinearGaugeBase::backgroundGradientSpread read write
drawBackground
bool QuLinearGaugeBase::drawBackground read write
Referenced by paintEvent().
drawColoredTicks
bool QuLinearGaugeBase::drawColoredTicks read write
draw colored ticks
This property can also be enabled in association with drawTickCore1 or drawTickCore2 if the effect is welcome.
If enabled, the colored ticks length is equal to radius multiplied by (1.0 - tickLen).
drawText
bool QuLinearGaugeBase::drawText read write
either draw or not the labels with the values associated to each major tick
Returns
true the value of each major tick is drawn false no values are drawn on the gauge
Note
if you want the current value to be displayed on a separate bigger label somewhere in the widget area, use the labelPosition property and set it to a value different from QuLinearBase::NoLabel. At the same time, the label property must be set to an empty string.
See also
label
setLabelPosition
setLabel
drawTickCore1
bool QuLinearGaugeBase::drawTickCore1 read write
draw a tick inside the gauge arc
Returns
true a tick is drawn within the gauge arc. Its width is equal to the gaugeWidth property (in pixels)
See also
drawTickCore2
drawColoredTicks
drawTickCore2
bool QuLinearGaugeBase::drawTickCore2 read write
draw a tick from the inner border of the gauge arc
Returns
true a tick is drawn from the inner border of the gauge arc. Its width is equal to the gaugeWidth property (in pixels)
See also
drawTickCore1
drawColoredTicks
errorColor
QColor QuLinearGaugeBase::errorColor read write
format
QString QuLinearGaugeBase::format read write
formatFromPropertyEnabled
bool QuLinearGaugeBase::formatFromPropertyEnabled read write
gaugeWidth
double QuLinearGaugeBase::gaugeWidth read write
returns the width of the gauge strip
Returns
the width, in pixels, floating point, used to draw the line
highError
double QuLinearGaugeBase::highError read write
highWarning
double QuLinearGaugeBase::highWarning read write
indicatorType
QuLinearGaugeBase::IndicatorType QuLinearGaugeBase::indicatorType read write
label
QString QuLinearGaugeBase::label read write
labelFontScale
double QuLinearGaugeBase::labelFontScale read write
scales the label font respect to the font size of the text on the gauge
Returns
the label font scale value, between 0 and 2.
The font size of the text on the gauge is scaled by this factor.
Note
The default value is 0.9
labelPosition
QuLinearGaugeBase::LabelPosition QuLinearGaugeBase::labelPosition read write
labelValueFormat
QString QuLinearGaugeBase::labelValueFormat read write
lowError
double QuLinearGaugeBase::lowError read write
lowWarning
double QuLinearGaugeBase::lowWarning read write
maxAnimationDuration
qint64 QuLinearGaugeBase::maxAnimationDuration read write
The maximum duration of an animation between two setValue calls.
Returns
the value, in milliseconds, of the maximum duration of an animation between two setValue calls
note
If two setValue calls take place within a shorter interval, that interval is used to animate the transition instead.
See also
animationEnabled
maxValue
double QuLinearGaugeBase::maxValue read write
returns the maximum value represented by this gauge
Returns
the maximum value of this gauge's scale
minorTicksCount
int QuLinearGaugeBase::minorTicksCount read write
returns the number of minor ticks drawn between each couple of major ticks
Returns
the number of minor ticks between two subsequent major ticks
See also
ticksCount
setMinorTicksCount
minValue
double QuLinearGaugeBase::minValue read write
returns the minimum value represented by this gauge
Returns
the minimum value of this gauge's scale
needleColor
QColor QuLinearGaugeBase::needleColor read write
needleGuideColor
QColor QuLinearGaugeBase::needleGuideColor read write
returns the color of the needle guide, that is drawn along the longest widget side and crosses the needle pivot center
Returns
the color of the <cite>needle guide</cite>
normalColor
QColor QuLinearGaugeBase::normalColor read write
pivotCircleRadius
double QuLinearGaugeBase::pivotCircleRadius read write
the factor multiplies tickLen to obtain the radius for the circle drawn at the base of the needle.
Returns
a factor determining the radius of the circle drawn as pivot of the needle.
See also
setPivotCircleRadius
readErrorColor
QColor QuLinearGaugeBase::readErrorColor read write
scaleMode
QuLinearGaugeBase::ScaleMode QuLinearGaugeBase::scaleMode read write
textColor
QColor QuLinearGaugeBase::textColor read write
thermoColor1
QColor QuLinearGaugeBase::thermoColor1 read write
Sets the color 1 (inner color) used to draw the gradient for the thermo bar.
If the gauge indicator is Thermo, a thermometer like bar is drawn using a linear gradient. This property holds the color 1 of the gradient, used to fill the inner section of the bar.
See also
thermoColor2
setThermoColor1
setIndicatorMode
thermoColor2
QColor QuLinearGaugeBase::thermoColor2 read write
Sets the color 2 (outer color) used to draw the gradient for the thermo bar.
If the gauge indicator is Thermo, a thermometer like bar is drawn using a linear gradient. This property holds the color 2 of the gradient, used to colr the outer sides of the bar.
See also
thermoColor1
setThermoColor2
setIndicatorMode
thermoPenColor
QColor QuLinearGaugeBase::thermoPenColor read write
returns the pen color used to outline the thermometer bar in the gauge indicator
Returns
the pen color
Note
applies to QuLinearGauge elements which indicatorProperty is set to QuLinearGaugeBase::Thermo
See also
thermoColor1
thermoColor2
setThermoPenColor
indicatorMode
thermoWidth
double QuLinearGaugeBase::thermoWidth read write
returns the width of the thermometer bar, when indicatorMode is set to Thermo
The width of the thermometer is expressed as fraction of the widget's smallest size. The default value of 0.3 will draw a bar of 30 pixels on a gauge with a size 200x90
Note
This property applies only to linear gauges with the indicatorMode property set to Thermo
See also
setThermoWidth
setIndicatorMode
tickCoreColor
QColor QuLinearGaugeBase::tickCoreColor read write
tickLen
double QuLinearGaugeBase::tickLen read write
returns the tick length
The value, expressed within the interval [0.0, 1.0] is intended as fraction of the lenght of the gauge arc's radius.
Default value
The default value is 0.08. The major tick length is thus equal to 2% of the radius by default.
ticksCount
int QuLinearGaugeBase::ticksCount read write
returns the number of major ticks drawn in the arc
Returns
the number of major ticks drawn
See also
minorTicksCount
unit
QString QuLinearGaugeBase::unit read write
value
double QuLinearGaugeBase::value read write
value_anim
double QuLinearGaugeBase::value_anim read write
returns the value during the animation
To get the actual value, please refer to the QuLinearGaugeBase::value method
warningColor
QColor QuLinearGaugeBase::warningColor read write
The documentation for this class was generated from the following files:
qulineargaugebase.h
qulineargaugebase.cpp