cumbia-qtcontrols: QmlWriterBackend Class Reference
QmlWriterBackend Class Reference
QmlWriterBackend is an object that can be used as a backend for QMLwriters.
#include <qmlwriterbackend.h>
Public Slots
void setTarget (const QString &target)
set the target
void write (QVariant i)
write an integer to the target
Signals
void newData (const CuData &)
void labelChanged ()
void minChanged ()
void maxChanged ()
void valueChanged ()
void unitChanged ()
void targetChanged ()
void descriptionChanged ()
void okChanged ()
Public Member Functions
QmlWriterBackend (QObject *parent=nullptr)
virtual ~QmlWriterBackend ()
Q_INVOKABLE void init (CumbiaPool_O *poo_o)
QString target () const
returns the target of the writer
CuContext * getContext () const
returns a pointer to the CuContext used as a delegate for the connection.
QVariant min () const
QVariant max () const
QVariant value () const
QString label () const
QString unit () const
QString description () const
bool ok () const
void onUpdate (const CuData &d)
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
bool ok
QString target
QVariant min
QVariant max
QVariant value
QString label
QString unit
QString description
Detailed Description
QmlWriterBackend is an object that can be used as a backend for QMLwriters.
Constructor & Destructor Documentation
QmlWriterBackend()
QmlWriterBackend::QmlWriterBackend (QObject * parent = nullptr)
~QmlWriterBackend()
QmlWriterBackend::~QmlWriterBackend () virtual
Member Function Documentation
description()
QString QmlWriterBackend::description () const
descriptionChanged
void QmlWriterBackend::descriptionChanged () signal
getContext()
CuContext * QmlWriterBackend::getContext () const virtual
returns a pointer to the CuContext used as a delegate for the connection.
returns the pointer to the CuContext
Returns
CuContext
CuContext sets up the connection and is used as a mediator to send and get data to and from the reader.
See also
CuContext
Implements CuContextI.
init()
void QmlWriterBackend::init (CumbiaPool_O * poo_o)
References CumbiaPool_O::getFactory(), CumbiaPool_O::getPool(), and setTarget().
label()
QString QmlWriterBackend::label () const
labelChanged
void QmlWriterBackend::labelChanged () signal
max()
QVariant QmlWriterBackend::max () const
maxChanged
void QmlWriterBackend::maxChanged () signal
min()
QVariant QmlWriterBackend::min () const
minChanged
void QmlWriterBackend::minChanged () signal
newData
void QmlWriterBackend::newData (const CuData &) signal
Referenced by onUpdate().
ok()
bool QmlWriterBackend::ok () const
Referenced by onUpdate().
okChanged
void QmlWriterBackend::okChanged () signal
Referenced by onUpdate().
onUpdate()
void QmlWriterBackend::onUpdate (const CuData & d)
References newData(), ok(), and okChanged().
setTarget
void QmlWriterBackend::setTarget (const QString & target) slot
set the target
Connect the reader to the specified source.
Parameters
the name of the target
If a reader with a different source is configured, it is deleted. If options have been set with QuContext::setOptions, they are used to set up the reader as desired.
See also
QuContext::setOptions
source
References CuControlsWriterA::setTarget(), target(), CuControlsWriterA::target(), and targetChanged().
Referenced by init().
target()
QString QmlWriterBackend::target () const
returns the target of the writer
Returns
a QString with the name of the target
Referenced by setTarget().
targetChanged
void QmlWriterBackend::targetChanged () signal
Referenced by setTarget().
unit()
QString QmlWriterBackend::unit () const
unitChanged
void QmlWriterBackend::unitChanged () signal
value()
QVariant QmlWriterBackend::value () const
valueChanged
void QmlWriterBackend::valueChanged () signal
write
void QmlWriterBackend::write (QVariant ival) slot
write an integer to the target
Parameters
i the value to be written on the target
Property Documentation
description
QString QmlWriterBackend::description read
label
QString QmlWriterBackend::label read
max
QVariant QmlWriterBackend::max read
min
QVariant QmlWriterBackend::min read
ok
bool QmlWriterBackend::ok read
target
QString QmlWriterBackend::target read write
unit
QString QmlWriterBackend::unit read
value
QVariant QmlWriterBackend::value read
The documentation for this class was generated from the following files:
qmlwriterbackend.h
qmlwriterbackend.cpp