cumbia-qtcontrols: QuDoubleSpinBox Class Reference
QuDoubleSpinBox Class Reference
#include <qudoublespinbox.h>
Public Slots
void setTarget (const QString &targets, CuContext *ctx=nullptr)
Set the name of the target that will be executed.
void clearTarget ()
virtual bool ctxSwap (CumbiaPool *cu_p, const CuControlsFactoryPool &fpool)
Public Member Functions
QuDoubleSpinBox (QWidget *parent, Cumbia *cumbia, const CuControlsWriterFactoryI &w_fac)
QuDoubleSpinBox (QWidget *parent, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
virtual ~QuDoubleSpinBox ()
virtual CuContext * getContext () const
Return a reference to the CuContext in use.
virtual void onUpdate (const CuData &data)
QString target () const
returns the target name.
Public Member Functions inherited from CuContextI
virtual ~CuContextI ()
Properties
QString target
Constructor & Destructor Documentation
QuDoubleSpinBox() [1/2]
QuDoubleSpinBox::QuDoubleSpinBox (QWidget * parent, Cumbia * cumbia, const CuControlsWriterFactoryI & w_fac)
QuDoubleSpinBox() [2/2]
QuDoubleSpinBox::QuDoubleSpinBox (QWidget * parent, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
~QuDoubleSpinBox()
QuDoubleSpinBox::~QuDoubleSpinBox () virtual
Member Function Documentation
clearTarget
void QuDoubleSpinBox::clearTarget () slot
ctxSwap
bool QuDoubleSpinBox::ctxSwap (CumbiaPool * cu_p, const CuControlsFactoryPool & fpool) virtual slot
References CuEngineSwap::ok(), and CuEngineSwap::replace().
getContext()
CuContext * QuDoubleSpinBox::getContext () const virtual
Return a reference to the CuContext in use.
Returns
a pointer to the CuContext used by the subclass.
Implements CuContextI.
onUpdate()
void QuDoubleSpinBox::onUpdate (const CuData & data) virtual
References QuLogImpl::showPopupOnMessage(), and target.
setTarget
void QuDoubleSpinBox::setTarget (const QString & targets, CuContext * ctx = nullptr) slot
Set the name of the target that will be executed.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References CuControlsWriterA::setTarget().
target()
QString QuDoubleSpinBox::target () const
returns the target name.
Returns
the target name, or an empty string if setTarget hasn't been called yet.
Refer to md_src_cumbia_qtcontrols_widget_constructors documentation.
References CuControlsWriterA::target().
Property Documentation
target
QString QuDoubleSpinBox::target read write
Referenced by onUpdate().
The documentation for this class was generated from the following files:
qudoublespinbox.h
qudoublespinbox.cpp