cumbia-qtcontrols: QuApplication Class Reference
QuApplication Class Reference
Utilities
A QApplication with additional functions, such as to register with dbus, minimize and raise the main widget.
#include <quapplication.h>
Public Slots
void raise ()
raises the top level windows
void minimize ()
minimizes the top level windows
void quit ()
simply calls QApplication::quit
QStringList arguments () const
returns QApplication::arguments()
QString exename () const
returns the executable name
QStringList cmdOpt () const
QString display_host () const
int display_number () const
int screen_number () const
bool isPlatformX11 () const
Signals
void dbusRegistered (const QString &exename, const QStringList &args, const QString &dbus_servicenam, const QString &display_host, int display_number, int screen_number, bool is_plat_x11)
void dbusUnregistered (const QString &exename, const QStringList &args, const QString &dbus_servicenam, const QString &display_host, int display_number, int screen_number, bool is_plat_x11)
Public Member Functions
QuApplication (int &argc, char **argv)
The class constructor.
QuApplication (int &argc, char **argv, CumbiaPool *cu_p, CuControlsFactoryPool *fp)
int exec ()
calls exec on QApplication after registering with the DBus session bus if the qumbia-dbus plugin is available.
CumbiaPool * cumbiaPool () const
CuControlsFactoryPool * fpool () const
Detailed Description
A QApplication with additional functions, such as to register with dbus, minimize and raise the main widget.
QuApplication derives from QApplication. If the cumbia-dbus plugin is available, it is used to register the application with the DBus session bus. This allows the application to receive and send messages, so that it can be used with an application browser that raises the window of a running application rather than launching a new instance.
See QuDBusPluginInterface documentation and the cumbia-dbus plugin
Constructor & Destructor Documentation
QuApplication() [1/2]
QuApplication::QuApplication (int & argc, char ** argv)
The class constructor.
NOTE
Changes to this file require running $ qdbuscpp2xml src/quapplication.h -o ../qumbia-plugins/cumbia-dbus/src/cumbiadbus.xml Then rebuild cumbia-dbus
QuApplication is build the very same way as QApplication. Just replace QApplication with QuApplication in your main.cpp
QuApplication() [2/2]
QuApplication::QuApplication (int & argc, char ** argv, CumbiaPool * cu_p, CuControlsFactoryPool * fp)
Member Function Documentation
arguments
QStringList QuApplication::arguments () const slot
returns QApplication::arguments()
Returns
QApplication::arguments()
cmdOpt
QStringList QuApplication::cmdOpt () const slot
returns the list of the command line options
Returns
a QStringList taken from QApplication::arguments without the first element.
Referenced by exec().
cumbiaPool()
CumbiaPool * QuApplication::cumbiaPool () const
Referenced by QuLabel::QuLabel(), QuLed::QuLed(), QuLinearGauge::QuLinearGauge(), QuLineEdit::QuLineEdit(), QuSpectrumPlot::QuSpectrumPlot(), QuSpinBox::QuSpinBox(), QuTable::QuTable(), QuTrendPlot::QuTrendPlot(), QuWatcher::QuWatcher(), and QuWriter::QuWriter().
dbusRegistered
void QuApplication::dbusRegistered (const QString & exename, const QStringList & args, const QString & dbus_servicenam, const QString & display_host, int display_number, int screen_number, bool is_plat_x11) signal
Referenced by exec().
dbusUnregistered
void QuApplication::dbusUnregistered (const QString & exename, const QStringList & args, const QString & dbus_servicenam, const QString & display_host, int display_number, int screen_number, bool is_plat_x11) signal
Referenced by exec().
display_host
QString QuApplication::display_host () const slot
References rege.
display_number
int QuApplication::display_number () const slot
References rege.
exec()
int QuApplication::exec ()
calls exec on QApplication after registering with the DBus session bus if the qumbia-dbus plugin is available.
Returns
the result returned by QApplication::exec
If the QPluginLoader can load the QuDBusPluginInterface plugin, then the application is registered with DBus. The dbusRegistered signal is emitted, then QApplication::exec is called. After QApplication::exec returns, dbusUnregistered signal is emitted, the plugin is released and the result of QApplication::exec is returned.
See QApplication::exec
References cmdOpt(), dbusRegistered(), dbusUnregistered(), exename(), and isPlatformX11().
Referenced by main().
exename
QString QuApplication::exename () const slot
returns the executable name
Returns
the executable name obtained by QApplication::arguments().first() from where the path is removed.
example
If the application is /usr/local/bin/qumbiaprojectwizard, exename returns qumbiaprojectwizard.
Referenced by exec().
fpool()
CuControlsFactoryPool * QuApplication::fpool () const
Referenced by QuLabel::QuLabel(), QuLed::QuLed(), QuLinearGauge::QuLinearGauge(), QuLineEdit::QuLineEdit(), QuSpectrumPlot::QuSpectrumPlot(), QuSpinBox::QuSpinBox(), QuTable::QuTable(), QuTrendPlot::QuTrendPlot(), QuWatcher::QuWatcher(), and QuWriter::QuWriter().
isPlatformX11
bool QuApplication::isPlatformX11 () const slot
Referenced by exec().
minimize
void QuApplication::minimize () slot
minimizes the top level windows
Foreach QWindow w, calls w->showMinimized
quit
void QuApplication::quit () slot
simply calls QApplication::quit
raise
void QuApplication::raise () slot
raises the top level windows
Foreach QWindow w, calls w->raise
screen_number
int QuApplication::screen_number () const slot
References rege.
The documentation for this class was generated from the following files:
quapplication.h
quapplication.cpp