cumbia-qtcontrols: cucontrolsutils.cpp File Reference
cucontrolsutils.cpp File Reference
#include "cucontrolsutils.h"
#include "qustring.h"
#include <QVariant>
#include <QString>
#include <QWidget>
#include <QtDebug>
#include <QApplication>
#include <QMetaProperty>
#include <string>
#include <cumacros.h>
#include <cudata.h>
#include <QRegularExpression>
#include <QDateTime>
#include <QStringBuilder>
#include <QStringLiteral>
#include <chrono>
#include <unistd.h>
Macros
#define SHORT_TSLEN 20
Functions
QRegularExpression re ("\\‍((.*)\\‍)")
Macro Definition Documentation
SHORT_TSLEN
#define SHORT_TSLEN 20
Function Documentation
re()
QRegularExpression re ("\\‍((.*)\\‍)")
Referenced by QuLinearGaugeBase::drawText(), QThreadsEventBridge::event(), CuControlsUtils::findObjects(), CuControlsUtils::getArgs(), CuControlsFactoryPool::guessDomainBySrc(), QuCircularGaugeBase::resizeEvent(), QuLinearGaugeBase::resizeEvent(), QuLinearGaugeBase::setReadError(), and QuLedBase::setRectangular().