cumbia-qtcontrols: elettracolors.cpp File Reference
elettracolors.cpp File Reference
#include <QtDebug>
#include <QLabel>
#include <QLineEdit>
#include <QGridLayout>
#include <QToolTip>
#include <QApplication>
#include "elettracolors.h"
#include <cumacros.h>
Namespaces
Elettra
Functions
QColor EColor (const QString &colorString)
QColor EColor (int colorcode)
QPalette EPalette (QString def)
void Elettra::showColorPalette ()
Variables
const char * colorStrings []
Function Documentation
EColor() [1/2]
QColor EColor (const QString & colorString)
References colorStrings, EColor(), Elettra::fermiAlternateBase, and Elettra::white.
Referenced by EFlag::arrangeCells(), ELinearGauge::drawMarker(), ECircularGauge::drawScale(), EColor(), ELabel::ELabel(), EPalette(), QuLedBase::paintEvent(), and EFlag::setBooleanDisplay().
EColor() [2/2]
QColor EColor (int colorcode)
This one returns the colour corresponding to the code passed as argument.
References Elettra::almostBlack, Elettra::black, Elettra::blue, Elettra::blueGray, Elettra::boosterAlternateBase, BOOSTERCOLOR, Elettra::boosterColor, Elettra::boosterHighlight, Elettra::camel, Elettra::cyan, Elettra::darkBlue, Elettra::darkCyan, Elettra::darkGray, Elettra::darkGreen, Elettra::darkMaroon, Elettra::darkPink, Elettra::darkRed, Elettra::darkViolet, Elettra::darkWater, Elettra::darkYellow, Elettra::dirtyYellow, EBLACK, EBLUEGRAY, EDIRTYYELLOW, EFUCHSIA, EGREEN, EGREENWATER, Elettra::elettraAlternateBase, ELETTRACOLOR, Elettra::elettraColor, Elettra::elettraHighlight, EYELLOW, Elettra::fermiAlternateBase, FERMICOLOR, Elettra::fermiColor, Elettra::fermiHighlight, Elettra::fuchsia, Elettra::gray, Elettra::green, Elettra::greenWater, KALMOSTBLACK, KBLUE, KBOOSTERALTERNATEBASE, KBOOSTERHIGHLIGHT, KCAMEL, KCYAN, KDARKBLUE, KDARKCYAN, KDARKGRAY, KDARKGREEN, KDARKMAROON, KDARKPINK, KDARKRED, KDARKVIOLET, KDARKWATER, KDARKYELLOW, KELETTRAALTERNATEBASE, KELETTRAHIGHLIGHT, KGRAY, KGRAYFERMIALTERNATEBASE, KGRAYFERMIHIGHLIGHT, KLIGHTGRAY, KMAROON, KORANGE, KPINK, KPINKPIG, KRED90SAT, KVERYDARKBLUE, KVIOLET, Elettra::lightGray, Elettra::maroon, Elettra::orange, Elettra::pink, Elettra::pinkPig, Elettra::red, Elettra::veryDarkBlue, Elettra::violet, Elettra::white, and Elettra::yellow.
EPalette()
QPalette EPalette (QString def)
References Elettra::boosterColor, EColor(), Elettra::elettraColor, Elettra::fermiColor, KBOOSTERALTERNATEBASE, KBOOSTERHIGHLIGHT, KELETTRAALTERNATEBASE, KELETTRAHIGHLIGHT, KGRAYFERMIALTERNATEBASE, and KGRAYFERMIHIGHLIGHT.
Variable Documentation
colorStrings
const char* colorStrings[]
Initial value:
= { "white",   "darkGray",  "gray",  "lightGray",  "red",  "darkRed",  "darkMaroon",  "maroon",  "camel",
                 "orange",   "yellow",   "dirtyYellow",  "darkYellow",  "green",   "greenWater",  "darkGreen",
                "cyan",  "darkCyan",  "darkWater",  "blue",  "darkBlue",  "veryDarkBlue",
                "blueGray",  "violet",  "darkViolet",
                "darkPink",  "pink",  "pinkPig",   "fuchsia",  "almostBlack",  "black",  "boosterColor",  "elettraColor",  "fermiColor",  "elettraHighlight",
                "elettraAlternateBase",  "boosterHighlight",  "boosterAlternateBase",  "fermiHighlight",
                 "fermiAlternateBase"}
Referenced by EColor().