cumbia-qtcontrols: qrc_qml.cpp File Reference
qrc_qml.cpp File Reference
Macros
#define QT_RCC_PREPEND_NAMESPACE(name)
#define QT_RCC_MANGLE_NAMESPACE(name)
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int QT_RCC_MANGLE_NAMESPACE qInitResources_qml ()
int QT_RCC_MANGLE_NAMESPACE qCleanupResources_qml ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
QT_RCC_MANGLE_NAMESPACE
#define QT_RCC_MANGLE_NAMESPACE (name)
Value:
name
QT_RCC_PREPEND_NAMESPACE
#define QT_RCC_PREPEND_NAMESPACE (name)
Value:
name
Referenced by qCleanupResources_qml(), and qInitResources_qml().
Function Documentation
qCleanupResources_qml()
int QT_RCC_MANGLE_NAMESPACE qCleanupResources_qml ()
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
qInitResources_qml()
int QT_RCC_MANGLE_NAMESPACE qInitResources_qml ()
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
qRegisterResourceData()
bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
References qRegisterResourceData().
Referenced by qInitResources_qml().
qUnregisterResourceData()
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
References qUnregisterResourceData().
Referenced by qCleanupResources_qml().
Variable Documentation
qt_resource_data
const unsigned char qt_resource_data[] static
Referenced by qCleanupResources_qml(), and qInitResources_qml().
qt_resource_name
const unsigned char qt_resource_name[] static
Initial value:
= {
  0x0,0x8,
  0x8,0x1,0x5a,0x5c,
  0x0,0x6d,
  0x0,0x61,0x0,0x69,0x0,0x6e,0x0,0x2e,0x0,0x71,0x0,0x6d,0x0,0x6c,
}
Referenced by qCleanupResources_qml(), and qInitResources_qml().
qt_resource_struct
const unsigned char qt_resource_struct[] static
Initial value:
= {
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,
  0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
0x0,0x0,0x1,0x64,0x8d,0xad,0x4a,0x4e,
}
Referenced by qCleanupResources_qml(), and qInitResources_qml().