cumbia-qtcontrols: main.cpp File Reference
examples/qmlandroidpwma/main.cpp File Reference
#include <QApplication>
#include <QQmlApplicationEngine>
#include <QQuickView>
#include <QQmlContext>
#include <cucontrolsfactorypool.h>
#include <cumbiapool_o.h>
#include <cumbiapool.h>
#include <cumbiawebsocket.h>
#include <cuwsreader.h>
#include <qmlappstatemanager.h>
#include <cuthreadfactoryimpl.h>
#include <qthreadseventbridgefactory.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References CuAppStateManager::addSuspendable(), CumbiaPool_O::init(), CuControlsFactoryPool::registerImpl(), and CuControlsFactoryPool::setSrcPatterns().