cumbia-qtcontrols: qrc_qml.cpp File Reference
examples/build-qmlandroidpwma-GentooQT-Debug/qrc_qml.cpp File Reference
Macros
#define QT_RCC_PREPEND_NAMESPACE(name) name
#define QT_RCC_MANGLE_NAMESPACE(name) name
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int QT_RCC_MANGLE_NAMESPACE() qInitResources_qml ()
int QT_RCC_MANGLE_NAMESPACE() qCleanupResources_qml ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
QT_RCC_MANGLE_NAMESPACE
#define QT_RCC_MANGLE_NAMESPACE (name) name
QT_RCC_PREPEND_NAMESPACE
#define QT_RCC_PREPEND_NAMESPACE (name) name
Function Documentation
qCleanupResources_qml()
int QT_RCC_MANGLE_NAMESPACE() qCleanupResources_qml ()
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
qInitResources_qml()
int QT_RCC_MANGLE_NAMESPACE() qInitResources_qml ()
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
qRegisterResourceData()
bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_qml().
qUnregisterResourceData()
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qCleanupResources_qml().
Variable Documentation
qt_resource_data
const unsigned char qt_resource_data[] static
Referenced by qCleanupResources_qml(), and qInitResources_qml().
qt_resource_name
const unsigned char qt_resource_name[] static
Initial value:
= {
  0x0,0x9,
  0xd,0x86,0xfc,0xdc,
  0x0,0x50,
  0x0,0x61,0x0,0x67,0x0,0x65,0x0,0x33,0x0,0x2e,0x0,0x71,0x0,0x6d,0x0,0x6c,
  0x0,0x9,
  0xd,0x85,0xfc,0xdc,
  0x0,0x50,
  0x0,0x61,0x0,0x67,0x0,0x65,0x0,0x32,0x0,0x2e,0x0,0x71,0x0,0x6d,0x0,0x6c,
  0x0,0x9,
  0xd,0x84,0xfc,0xdc,
  0x0,0x50,
  0x0,0x61,0x0,0x67,0x0,0x65,0x0,0x31,0x0,0x2e,0x0,0x71,0x0,0x6d,0x0,0x6c,
  0x0,0x8,
  0x8,0x1,0x5a,0x5c,
  0x0,0x6d,
  0x0,0x61,0x0,0x69,0x0,0x6e,0x0,0x2e,0x0,0x71,0x0,0x6d,0x0,0x6c,
}
Referenced by qCleanupResources_qml(), and qInitResources_qml().
qt_resource_struct
const unsigned char qt_resource_struct[] static
Initial value:
= {
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x4,0x0,0x0,0x0,0x1,
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,
  0x0,0x0,0x0,0x48,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x4,0x63,
0x0,0x0,0x1,0x64,0xfe,0xe6,0x45,0x4d,
  0x0,0x0,0x0,0x30,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x3,0x12,
0x0,0x0,0x1,0x65,0x0,0xc,0x67,0x1c,
  0x0,0x0,0x0,0x18,0x0,0x1,0x0,0x0,0x0,0x1,0x0,0x0,0x1,0x7e,
0x0,0x0,0x1,0x64,0xff,0x10,0xe6,0x29,
  0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
0x0,0x0,0x1,0x64,0xfb,0x8c,0xbf,0x1d,
}
Referenced by qCleanupResources_qml(), and qInitResources_qml().