cumbia-qtcontrols: Plots
Plots
Display widgets
Classes
class QuPlotCommon
common object owned by cumbia plots used to link and configure a plot.
class QuSpectrumPlot
Draw a line for each data source over time.
class QuTrendPlot
Draw a line for each data source over time.
class QuPlotBase
A simple plot with zooming and scrolling capabilities.
class QuPlotAxesComponent
Plot component that manages the axes.
class QuPlotBaseContextMenuStrategy
a context menu strategy to create a context menu for QuPlotBase (strategy pattern)
class QuPlotCurve
QwtPlot derived curve used in QuPlotBase.
class QuPlotMarkerComponent
QuPlot component to draw markers on the canvas.
class QuPlotZoomComponent
QuPlot component to zoom the plot.
class QuTimeScaleDraw
QuPlot component to provide a date/time based scale.
Enumerations
enum QuPlotBase::CurveStyle {
QuPlotBase::NoCurve, QuPlotBase::Lines, QuPlotBase::Sticks, QuPlotBase::Steps,
QuPlotBase::Dots, QuPlotBase::UserCurve = 100
}
Functions
ShiftClickEater::ShiftClickEater (QObject *parent)
bool ShiftClickEater::eventFilter (QObject *obj, QEvent *event)
QuPlotBase::QuPlotBase (QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
QuPlotBase::QuPlotBase (const QwtText &title, QWidget *parent)
The constructor of a simple plot with zooming and scrolling capabilities.
virtual QuPlotBase::~QuPlotBase ()
CurveStyle QuPlotBase::curvesStyle ()
bool QuPlotBase::titleOnCanvasEnabled ()
bool QuPlotBase::xAxisAutoscaleEnabled ()
bool QuPlotBase::yAxisAutoscaleEnabled ()
double QuPlotBase::yUpperBound ()
double QuPlotBase::yLowerBound ()
bool QuPlotBase::xAxisLogScale ()
bool QuPlotBase::yAxisLogScale ()
void QuPlotBase::setXAxisLogScale (bool l)
void QuPlotBase::setYAxisLogScale (bool l)
double QuPlotBase::xUpperBound ()
double QuPlotBase::xLowerBound ()
bool QuPlotBase::zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
QList< QwtPlotCurve * > QuPlotBase::curves () const
void QuPlotBase::addCurve (const QString &curveName, QuPlotCurve *curve)
void QuPlotBase::removeCurve (const QString &curveName)
Removes the specified curve from the plot, deleting it.
void QuPlotBase::addCurve (const QString &curveName)
QuPlotCurve * QuPlotBase::curve (const QString &name)
int QuPlotBase::dataBufferSize ()
returns the data buffer size.
void QuPlotBase::hideMarker ()
void QuPlotBase::appendData (const QString &curveName, double *x, double *y, int size)
int QuPlotBase::refreshTimeout () const
double QuPlotBase::defaultLowerBound (QwtPlot::Axis axisId=QwtPlot::yLeft) const
double QuPlotBase::defaultUpperBound (QwtPlot::Axis axisId=QwtPlot::yLeft) const
void QuPlotBase::update (const CuData &)
void QuPlotBase::configure (const CuData &da)
void QuPlotBase::setUpdateStrategy (QuWidgetUpdateStrategyI *updateStrategy)
sets or replaces the update strategy (see the strategy design pattern)
void QuPlotBase::setContextMenuStrategy (QuWidgetContextMenuStrategyI *ctx_menu_strategy)
sets or replaces the context menu strategy (see the strategy design pattern)
QuWidgetUpdateStrategyI * QuPlotBase::updateStrategy () const
return the QuWidgetUpdateStrategyI implementation in use.
QuWidgetContextMenuStrategyI * QuPlotBase::contextMenuStrategy () const
return the QuWidgetContextMenuStrategyI implementation in use.
virtual QDialog * QuPlotBase::createConfigureDialog ()
virtual bool QuPlotBase::updateMarker ()
updates the marker, if visible, and returns true if it's visible, false otherwise
virtual bool QuPlotBase::updateScales ()
Updates the axes bounds for which autoscale is enabled.
void QuPlotBase::resetZoom ()
bool QuPlotBase::inZoom () const
QuPlotComponent * QuPlotBase::getComponent (const QString &name) const
returns the QuPlotComponent corresponding to the given name, nullptr if name is not valid
void QuPlotBase::registerComponent (QuPlotComponent *, const QString &name)
virtual QString QuPlotBase::plotTitle ()
returns the plot title.
virtual void QuPlotBase::drawCanvas (QPainter *p)
void QuPlotBase::mouseReleaseEvent (QMouseEvent *ev)
void QuPlotBase::keyPressEvent (QKeyEvent *ke)
void QuPlotBase::moveCurveToYRight (QwtPlotCurve *c, bool yr)
void QuPlotBase::updateLabel (QwtPlotCurve *closestCurve, int closestPointIdx)
virtual void QuPlotBase::init ()
void QuPlotBase::contextMenuEvent (QContextMenuEvent *e)
QuPlotBase::contextMenuEvent executes a contextual menu when the plot is right clicked.
Signals
void QuPlotBase::plotClicked (const QPoint &pt, QwtPlotCurve *closestCurve, double x, double y, const QPoint &curvePoint)
void QuPlotBase::curveAdded (QuPlotCurve *)
This signal is emitted when a new curve is added to the plot.
void QuPlotBase::curveRemoved (QuPlotCurve *)
This signal is emitted whenever a curve is removed from the plot via removeCurve.
Public Slots
virtual void QuPlotBase::refresh ()
Calls updateMarkers, updateScales and replot, resetting the zoom base in the end.
void QuPlotBase::setXAxisAutoscaleEnabled (bool en)
void QuPlotBase::setYAxisAutoscaleEnabled (bool en)
void QuPlotBase::setYLowerBound (double l)
void QuPlotBase::setYUpperBound (double u)
void QuPlotBase::setXLowerBound (double l)
void QuPlotBase::setXUpperBound (double u)
void QuPlotBase::setXAutoscaleMargin (double d)
void QuPlotBase::setUpperBoundExtra (int axisId, double e)
add some extra upper bound to the specified axis to optimize replot operations when the refresh rate is fast.
double QuPlotBase::upperBoundExtra (int axisId) const
double QuPlotBase::xAutoscaleMargin ()
void QuPlotBase::setYAutoscaleAdjustment (double d)
double QuPlotBase::yAutoscaleAdjustment ()
void QuPlotBase::setTitleOnCanvasEnabled (bool en)
void QuPlotBase::setCurveStyle (const QString &curveName, QwtPlotCurve::CurveStyle)
void QuPlotBase::setDataBufferSize (int b)
void QuPlotBase::setZoomDisabled (bool)
void QuPlotBase::clearPlot ()
virtual void QuPlotBase::setData (const QString &curveName, const QVector< double > &xData, const QVector< double > &yData)
virtual void QuPlotBase::appendData (const QString &curveName, double x, double y)
void QuPlotBase::setRefreshTimeout (int millis)
void QuPlotBase::setDefaultBounds (double lb, double ub, Axis axisId=QwtPlot::yLeft)
void QuPlotBase::restoreDefaultBounds (Axis axisId=QwtPlot::yLeft)
restores the bounds set with setDefaultBounds
void QuPlotBase::setAxisScaleDefaultEnabled (bool en, Axis axisId=QwtPlot::yLeft)
Restores the bounds of axisId to their default values if en is true, does nothing if en is false.
Protected Slots
void QuPlotBase::displayZoomHint ()
void QuPlotBase::eraseZoomHint ()
void QuPlotBase::plotZoomed (const QRectF &)
void QuPlotBase::showMarker (const QPolygon &p)
void QuPlotBase::print ()
void QuPlotBase::snapshot ()
void QuPlotBase::copyImage ()
virtual void QuPlotBase::configurePlot ()
void QuPlotBase::saveData ()
dumps the curves into a csv file.
Properties
bool QuPlotBase::xAxisAutoscale
bool QuPlotBase::yAxisAutoscale
double QuPlotBase::yUpperBound
double QuPlotBase::yLowerBound
double QuPlotBase::xUpperBound
double QuPlotBase::xLowerBound
double QuPlotBase::xAutoscaleMargin
double QuPlotBase::yAutoscaleAdjustment
bool QuPlotBase::titleOnCanvasEnabled
bool QuPlotBase::yAxisLogScale
bool QuPlotBase::zoomDisabled
int QuPlotBase::dataBufferSize
int QuPlotBase::refreshTimeout
Detailed Description
Enumeration Type Documentation
CurveStyle
enum QuPlotBase::CurveStyle
Enumerator
NoCurve
Lines
Sticks
Steps
Dots
UserCurve
Function Documentation
addCurve() [1/2]
void QuPlotBase::addCurve (const QString & curveName, QuPlotCurve * curve)
References QuPlotBase::curve(), and QuPlotBase::curveAdded().
Referenced by QuPlotBase::addCurve(), QuSpectrumPlot::update(), and QuTrendPlot::update().
addCurve() [2/2]
void QuPlotBase::addCurve (const QString & curveName)
References QuPlotBase::addCurve().
appendData()
void QuPlotBase::appendData (const QString & curveName, double * x, double * y, int size)
References QuPlotCurve::appendData(), QuPlotCurve::count(), QuPlotBase::curve(), QuPlotBase::dataBufferSize(), QuPlotCurve::popFront(), QuPlotBase::refresh(), and QuPlotCurve::updateRawData().
Referenced by QuPlotBase::appendData(), and QuTrendPlot::update().
configure()
void QuPlotBase::configure (const CuData & da)
configure upper and lower bounds according to data set in the input CuData
Parameters
da a CuData with suggested minimum and maximum values to automatically adjust upper and lower bounds
Note
CuData must contain valid std::string minimum and maximum values that can be converted to double. The required keys are "min" and "max", respectively.
References QuPlotBase::defaultLowerBound(), QuPlotBase::defaultUpperBound(), QuPlotAxesComponent::lowerBoundFromCurves(), QuPlotAxesComponent::scaleMode(), QuPlotAxesComponent::SemiAutoScale, QuPlotBase::setDefaultBounds(), and QuPlotAxesComponent::upperBoundFromCurves().
Referenced by QuSpectrumPlot::update(), and QuTrendPlot::update().
contextMenuEvent()
void QuPlotBase::contextMenuEvent (QContextMenuEvent * e) protected
QuPlotBase::contextMenuEvent executes a contextual menu when the plot is right clicked.
A QuWidgetContextMenuStrategyI implementation must be provided. A default strategy for QuPlotBase is provided by QuPlotBaseContextMenuStrategy, Install it calling QuPlotBase::setContextMenuStrategy.
Note
No strategy is installed by default.
The ownership of the context menu strategy is taken by QuPlotBase and destroyed within the class destructor.
contextMenuStrategy()
QuWidgetContextMenuStrategyI * QuPlotBase::contextMenuStrategy () const
return the QuWidgetContextMenuStrategyI implementation in use.
Returns
QuWidgetContextMenuStrategyI set with setContextMenuStrategy
createConfigureDialog()
QDialog * QuPlotBase::createConfigureDialog () virtual
Referenced by QuPlotContextMenuComponent::configurePlot().
curve()
QuPlotCurve * QuPlotBase::curve (const QString & name)
Referenced by QuPlotBase::addCurve(), QuPlotBase::appendData(), QuPlotBase::removeCurve(), QuPlotBase::setCurveStyle(), QuPlotBase::setData(), QuSpectrumPlot::update(), and QuTrendPlot::update().
curves()
QList< QwtPlotCurve * > QuPlotBase::curves () const
References RTTI_CURVE_OFFSET.
Referenced by QuPlotBase::drawCanvas(), QuPlotAxesComponent::getBoundsFromCurves(), QuPlotMarkerComponent::intersectingCurves(), QuTrendPlot::refresh(), QuPlotContextMenuComponent::saveData(), and QuPlotMarkerComponent::update().
curvesStyle()
CurveStyle QuPlotBase::curvesStyle ()
dataBufferSize()
int QuPlotBase::dataBufferSize ()
returns the data buffer size.
Returns
the number of elements of the underlying data size.
Referenced by QuPlotBase::appendData().
defaultLowerBound()
double QuPlotBase::defaultLowerBound (QwtPlot::Axis axisId = QwtPlot::yLeft) const
References QuPlotAxesComponent::defaultLowerBound().
Referenced by QuPlotBase::configure().
defaultUpperBound()
double QuPlotBase::defaultUpperBound (QwtPlot::Axis axisId = QwtPlot::yLeft) const
References QuPlotAxesComponent::defaultUpperBound().
Referenced by QuPlotBase::configure().
drawCanvas()
void QuPlotBase::drawCanvas (QPainter * p) protected virtual
updates the title on the canvas
References QuPlotBase::curves(), QuPlotBase::titleOnCanvasEnabled(), QuPlotCanvasPainterComponent::update(), and QuPlotBase::zoomDisabled().
eventFilter()
bool ShiftClickEater::eventFilter (QObject * obj, QEvent * event) protected
getComponent()
QuPlotComponent * QuPlotBase::getComponent (const QString & name) const
returns the QuPlotComponent corresponding to the given name, nullptr if name is not valid
Component list
"context_menu" returns QuPlotContextMenuComponent
"axes" returns QuPlotAxesComponent
"zoom" returns QuPlotZoomComponent
"marker" returns QuPlotMarkerComponent
"canvas_painter" QuPlotCanvasPainterComponent
hideMarker()
void QuPlotBase::hideMarker ()
Referenced by QuPlotBase::mouseReleaseEvent(), and QuPlotBase::plotZoomed().
init()
void QuPlotBase::init () protected virtual
References QuPlotContextMenuComponent::attachToPlot(), QuPlotZoomComponent::attachToPlot(), QuPlotMarkerComponent::attachToPlot(), QuPlotContextMenuComponent::connectToPlot(), QuPlotZoomComponent::connectToPlot(), QuPlotMarkerComponent::connectToPlot(), QuPlotBase::Lines, QuPlotCanvasPainterComponent::name(), QuPlotAxesComponent::name(), QuPlotMarkerComponent::name(), QuPlotContextMenuComponent::name(), QuPlotZoomComponent::name(), and Elettra::white.
Referenced by QuPlotBase::QuPlotBase().
inZoom()
bool QuPlotBase::inZoom () const
keyPressEvent()
void QuPlotBase::keyPressEvent (QKeyEvent * ke) protected
References QuPlotMarkerComponent::currentClosestCurve(), QuPlotMarkerComponent::isVisible(), and QuPlotBase::moveCurveToYRight().
mouseReleaseEvent()
void QuPlotBase::mouseReleaseEvent (QMouseEvent * ev) protected
References QuPlotBase::hideMarker(), and QuPlotMarkerComponent::isVisible().
moveCurveToYRight()
void QuPlotBase::moveCurveToYRight (QwtPlotCurve * c, bool yr) protected
Referenced by QuPlotBase::keyPressEvent().
plotTitle()
virtual QString QuPlotBase::plotTitle () inline protected virtual
returns the plot title.
This is called if titleOnCanvasEnabled is true. Subclasses must reimplement this method to provide a title drawn on the plot canvas. For an example, see TPlotLightMarker reimplementation. This default implementation provides no title.
QuPlotBase() [1/2]
QuPlotBase::QuPlotBase (QWidget * parent)
The constructor of a simple plot with zooming and scrolling capabilities.
Parameters
parent the parent widget
References QuPlotBase::init().
QuPlotBase() [2/2]
QuPlotBase::QuPlotBase (const QwtText & title, QWidget * parent)
The constructor of a simple plot with zooming and scrolling capabilities.
Parameters
parent the parent widget
title the title of the plot
References QuPlotBase::init().
refreshTimeout()
int QuPlotBase::refreshTimeout () const
registerComponent()
void QuPlotBase::registerComponent (QuPlotComponent * c, const QString & name)
removeCurve()
void QuPlotBase::removeCurve (const QString & curveName)
Removes the specified curve from the plot, deleting it.
Parameters
curveName the name of the curve you want to remove.
References QuPlotBase::curve(), and QuPlotBase::curveRemoved().
Referenced by QuSpectrumPlot::unsetSource(), QuTrendPlot::unsetSource(), QuSpectrumPlot::unsetSources(), and QuTrendPlot::unsetSources().
resetZoom()
void QuPlotBase::resetZoom ()
References QuPlotZoomComponent::inZoom(), and QuPlotZoomComponent::setZoomBase().
Referenced by QuTrendPlot::refresh(), and QuPlotBase::refresh().
setContextMenuStrategy()
void QuPlotBase::setContextMenuStrategy (QuWidgetContextMenuStrategyI * ctx_menu_strategy) virtual
sets or replaces the context menu strategy (see the strategy design pattern)
Set or replace the current QuWidgetContextMenuStrategyI implementation.
Parameters
updateStrategy an implementation of QuWidgetContextMenuStrategyI
If a strategy is already in use, it is deleted and the new one is set.
Implements QuWidgetInterface.
setUpdateStrategy()
void QuPlotBase::setUpdateStrategy (QuWidgetUpdateStrategyI * updateStrategy) virtual
sets or replaces the update strategy (see the strategy design pattern)
Set or replace the current QuWidgetUpdateStrategyI implementation.
Parameters
updateStrategy an implementation of QuWidgetUpdateStrategyI
If a strategy is already in use, it is deleted and the new one is set.
Implements QuWidgetInterface.
References QuPlotBase::updateStrategy().
setXAxisLogScale()
void QuPlotBase::setXAxisLogScale (bool l)
setYAxisLogScale()
void QuPlotBase::setYAxisLogScale (bool l)
ShiftClickEater()
ShiftClickEater::ShiftClickEater (QObject * parent) inline
titleOnCanvasEnabled()
bool QuPlotBase::titleOnCanvasEnabled ()
Referenced by QuPlotBase::drawCanvas().
update()
void QuPlotBase::update (const CuData &) virtual
Implements QuWidgetInterface.
updateLabel()
void QuPlotBase::updateLabel (QwtPlotCurve * closestCurve, int closestPointIdx) protected
References QuPlotMarkerComponent::isVisible(), and QuPlotMarkerComponent::update().
Referenced by QuPlotBase::showMarker().
updateMarker()
bool QuPlotBase::updateMarker () virtual
updates the marker, if visible, and returns true if it's visible, false otherwise
See also
refresh
updateScales
References QuPlotMarkerComponent::isVisible(), and QuPlotMarkerComponent::update().
Referenced by QuTrendPlot::refresh(), and QuPlotBase::refresh().
updateScales()
bool QuPlotBase::updateScales () virtual
Updates the axes bounds for which autoscale is enabled.
Note
replot is not called
Returns
true if the one or more axes bounds have changed, false otherwise.
See also
refresh
References QuPlotZoomComponent::changeRect(), QuPlotAxesComponent::getBoundsFromCurves(), and QuPlotZoomComponent::inZoom().
Referenced by QuTrendPlot::refresh(), and QuPlotBase::refresh().
updateStrategy()
QuWidgetUpdateStrategyI * QuPlotBase::updateStrategy () const
return the QuWidgetUpdateStrategyI implementation in use.
Returns
QuWidgetUpdateStrategyI set with setUpdateStrategy
Referenced by QuSpectrumPlot::onUpdate(), QuTrendPlot::onUpdate(), and QuPlotBase::setUpdateStrategy().
xAxisAutoscaleEnabled()
bool QuPlotBase::xAxisAutoscaleEnabled ()
References QuPlotAxesComponent::autoscale().
xAxisLogScale()
bool QuPlotBase::xAxisLogScale ()
xLowerBound()
double QuPlotBase::xLowerBound ()
xUpperBound()
double QuPlotBase::xUpperBound ()
yAxisAutoscaleEnabled()
bool QuPlotBase::yAxisAutoscaleEnabled ()
References QuPlotAxesComponent::autoscale().
yAxisLogScale()
bool QuPlotBase::yAxisLogScale ()
yLowerBound()
double QuPlotBase::yLowerBound ()
yUpperBound()
double QuPlotBase::yUpperBound ()
zoomDisabled()
bool QuPlotBase::zoomDisabled () const
returns false if the zoom is enabled (the default), true otherwise.
See also
setZoomDisabled
Referenced by QuPlotBase::drawCanvas().
~QuPlotBase()
QuPlotBase::~QuPlotBase () virtual
Signals
curveAdded
void QuPlotBase::curveAdded (QuPlotCurve *) signal
This signal is emitted when a new curve is added to the plot.
This signal can be useful when you want to catch the creation and adding of a new curve to the plot. You can then modify the characteristics of the curve right after it is added to the plot.
Referenced by QuPlotBase::addCurve().
curveRemoved
void QuPlotBase::curveRemoved (QuPlotCurve *) signal
This signal is emitted whenever a curve is removed from the plot via removeCurve.
When a curve is detached from the plot, in the removeCurve() method, this signal is emitted. Right after the signal is emitted, the curve is deleted. So be sure that you connect this signal via a Qt::DirectConnection to your slot.
Referenced by QuPlotBase::removeCurve().
plotClicked
void QuPlotBase::plotClicked (const QPoint & pt, QwtPlotCurve * closestCurve, double x, double y, const QPoint & curvePoint) signal
Referenced by QuPlotBase::showMarker().
Public Slots
appendData
void QuPlotBase::appendData (const QString & curveName, double x, double y) virtual slot
References QuPlotBase::appendData().
clearPlot
void QuPlotBase::clearPlot () slot
References QuPlotCurve::clearData().
refresh
void QuPlotBase::refresh () virtual slot
Calls updateMarkers, updateScales and replot, resetting the zoom base in the end.
Note
reimplement in subclasses to customise the behaviour (for example, to perform an incremental replot)
See also
TrendPlot::refresh
updateMarkers
updateScales
References QuPlotBase::resetZoom(), QuPlotBase::updateMarker(), and QuPlotBase::updateScales().
Referenced by QuPlotBase::appendData(), QuPlotBase::setData(), QuPlotBase::setRefreshTimeout(), QuPlotBase::setYLowerBound(), and QuPlotBase::setYUpperBound().
restoreDefaultBounds
void QuPlotBase::restoreDefaultBounds (Axis axisId = QwtPlot::yLeft) slot
restores the bounds set with setDefaultBounds
Note
The QuPlotAxesComponent::ScaleMode flag is set to SemiAutomatic if en is true
While scale mode is semi automatic, the axis can be (re)configured by subclasses, for example with bounds associated to a source obtained from a file or database
References QuPlotAxesComponent::restoreDefaultBounds().
Referenced by QuPlotBase::setAxisScaleDefaultEnabled().
setAxisScaleDefaultEnabled
void QuPlotBase::setAxisScaleDefaultEnabled (bool en, Axis axisId = QwtPlot::yLeft) slot
Restores the bounds of axisId to their default values if en is true, does nothing if en is false.
Note
The QuPlotAxesComponent::ScaleMode flag is set to SemiAutomatic if en is true
Parameters
en true the default bounds of the axisId are reset to their default values
en false the function does nothing
axisId the id of the axis which boundaries are to be restored
References QuPlotBase::restoreDefaultBounds(), and QuPlotAxesComponent::setAutoscale().
setCurveStyle
void QuPlotBase::setCurveStyle (const QString & curveName, QwtPlotCurve::CurveStyle style) slot
References QuPlotBase::curve().
setData
void QuPlotBase::setData (const QString & curveName, const QVector< double > & xData, const QVector< double > & yData) virtual slot
References QuPlotBase::curve(), QuPlotBase::refresh(), and QuPlotCurve::setData().
Referenced by QuSpectrumPlot::update().
setDataBufferSize
void QuPlotBase::setDataBufferSize (int b) slot
setDefaultBounds
void QuPlotBase::setDefaultBounds (double lb, double ub, Axis axisId = QwtPlot::yLeft) slot
References QuPlotAxesComponent::setDefaultBounds().
Referenced by QuPlotBase::configure().
setRefreshTimeout
void QuPlotBase::setRefreshTimeout (int millis) slot
References QuPlotBase::refresh().
setTitleOnCanvasEnabled
void QuPlotBase::setTitleOnCanvasEnabled (bool en) slot
Referenced by QuPlotContextMenuComponent::copyImage(), and QuPlotContextMenuComponent::snapshot().
setUpperBoundExtra
void QuPlotBase::setUpperBoundExtra (int axisId, double e) slot
add some extra upper bound to the specified axis to optimize replot operations when the refresh rate is fast.
Parameters
axisId the axis id, one of QwtPlot::xBottom, QwtPlot::xTop, QwtPlot::yLeft, QwtPlot::yRight
e the extra bound to add to the scale, percentage expressed from 0 to 1
References QuPlotAxesComponent::setUpperBoundExtra().
setXAutoscaleMargin
void QuPlotBase::setXAutoscaleMargin (double d) slot
References QuPlotAxesComponent::setAutoscaleMargin().
setXAxisAutoscaleEnabled
void QuPlotBase::setXAxisAutoscaleEnabled (bool en) slot
References QuPlotAxesComponent::setAutoscale(), and QuPlotAxesComponent::setBounds().
setXLowerBound
void QuPlotBase::setXLowerBound (double l) slot
References QuPlotAxesComponent::setManualBounds().
setXUpperBound
void QuPlotBase::setXUpperBound (double u) slot
References QuPlotAxesComponent::setManualBounds().
setYAutoscaleAdjustment
void QuPlotBase::setYAutoscaleAdjustment (double d) slot
References QuPlotAxesComponent::setAutoscaleMargin().
setYAxisAutoscaleEnabled
void QuPlotBase::setYAxisAutoscaleEnabled (bool en) slot
References QuPlotAxesComponent::setAutoscale(), and QuPlotAxesComponent::setBounds().
setYLowerBound
void QuPlotBase::setYLowerBound (double l) slot
References QuPlotBase::refresh(), and QuPlotAxesComponent::setManualBounds().
setYUpperBound
void QuPlotBase::setYUpperBound (double u) slot
References QuPlotBase::refresh(), and QuPlotAxesComponent::setManualBounds().
setZoomDisabled
void QuPlotBase::setZoomDisabled (bool disable) slot
upperBoundExtra
double QuPlotBase::upperBoundExtra (int axisId) const slot
References QuPlotAxesComponent::upperBoundExtra().
xAutoscaleMargin
double QuPlotBase::xAutoscaleMargin () slot
yAutoscaleAdjustment
double QuPlotBase::yAutoscaleAdjustment () slot
Protected Slots
configurePlot
void QuPlotBase::configurePlot () protected virtual slot
copyImage
void QuPlotBase::copyImage () protected slot
displayZoomHint
void QuPlotBase::displayZoomHint () protected slot
eraseZoomHint
void QuPlotBase::eraseZoomHint () protected slot
plotZoomed
void QuPlotBase::plotZoomed (const QRectF &) protected slot
References QuPlotBase::hideMarker(), and QuPlotMarkerComponent::isVisible().
print
void QuPlotBase::print () protected slot
saveData
void QuPlotBase::saveData () protected slot
dumps the curves into a csv file.
The columns are in the form xAxisValues1, yAxisValues1, ... xAxisValuesN, yAxisValuesN.
showMarker
void QuPlotBase::showMarker (const QPolygon & p) protected slot
References QuPlotMarkerComponent::hide(), QuPlotBase::plotClicked(), QuPlotMarkerComponent::show(), and QuPlotBase::updateLabel().
snapshot
void QuPlotBase::snapshot () protected slot
Properties
dataBufferSize
int QuPlotBase::dataBufferSize read write
refreshTimeout
int QuPlotBase::refreshTimeout read write
titleOnCanvasEnabled
bool QuPlotBase::titleOnCanvasEnabled read write
Referenced by QuPlotContextMenuComponent::copyImage(), and QuPlotContextMenuComponent::snapshot().
xAutoscaleMargin
double QuPlotBase::xAutoscaleMargin read write
xAxisAutoscale
bool QuPlotBase::xAxisAutoscale read write
xLowerBound
double QuPlotBase::xLowerBound read write
xUpperBound
double QuPlotBase::xUpperBound read write
yAutoscaleAdjustment
double QuPlotBase::yAutoscaleAdjustment read write
yAxisAutoscale
bool QuPlotBase::yAxisAutoscale read write
yAxisLogScale
bool QuPlotBase::yAxisLogScale read write
yLowerBound
double QuPlotBase::yLowerBound read write
yUpperBound
double QuPlotBase::yUpperBound read write
zoomDisabled
bool QuPlotBase::zoomDisabled read write