cumbia-qtcontrols: main.cpp File Reference
main.cpp File Reference
#include <QApplication>
#include <QQmlApplicationEngine>
#include <QQuickView>
#include <QQmlContext>
#include <QQuickItem>
#include <cucontrolsfactorypool.h>
#include <cumbiapool_o.h>
#include <cutreader.h>
#include <cutwriter.h>
#include <cumbiapool.h>
#include <cumbiatango.h>
#include <cutango-world.h>
#include <cumbiaepics.h>
#include <cuepics-world.h>
#include <cuepcontrolsreader.h>
#include <cuepcontrolswriter.h>
#include <cutcontrolsreader.h>
#include <cutcontrolswriter.h>
#include <cuthreadfactoryimpl.h>
#include <qthreadseventbridgefactory.h>
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
References CumbiaPool_O::init(), CuControlsFactoryPool::registerImpl(), and CuControlsFactoryPool::setSrcPatterns().