cumbia-qtcontrols: qrc_confdialog.cpp File Reference
qrc_confdialog.cpp File Reference
Macros
#define QT_RCC_PREPEND_NAMESPACE(name)
#define QT_RCC_MANGLE_NAMESPACE(name)
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int QT_RCC_MANGLE_NAMESPACE qInitResources_confdialog ()
int QT_RCC_MANGLE_NAMESPACE qCleanupResources_confdialog ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
QT_RCC_MANGLE_NAMESPACE
#define QT_RCC_MANGLE_NAMESPACE (name)
Value:
name
QT_RCC_PREPEND_NAMESPACE
#define QT_RCC_PREPEND_NAMESPACE (name)
Value:
name
Referenced by qCleanupResources_confdialog(), and qInitResources_confdialog().
Function Documentation
qCleanupResources_confdialog()
int QT_RCC_MANGLE_NAMESPACE qCleanupResources_confdialog ()
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
qInitResources_confdialog()
int QT_RCC_MANGLE_NAMESPACE qInitResources_confdialog ()
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
qRegisterResourceData()
bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
References qRegisterResourceData().
Referenced by qInitResources_confdialog(), and qRegisterResourceData().
qUnregisterResourceData()
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
References qUnregisterResourceData().
Referenced by qCleanupResources_confdialog(), and qUnregisterResourceData().
Variable Documentation
qt_resource_data
const unsigned char qt_resource_data[] static
Referenced by qCleanupResources_confdialog(), and qInitResources_confdialog().
qt_resource_name
const unsigned char qt_resource_name[] static
Referenced by qCleanupResources_confdialog(), and qInitResources_confdialog().
qt_resource_struct
const unsigned char qt_resource_struct[] static
Initial value:
= {
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x7,0x0,0x0,0x0,0x2,
0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,
  0x0,0x0,0x0,0x14,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
0x0,0x0,0x1,0x90,0x30,0xb2,0xff,0x8,
  0x0,0x0,0x0,0x7e,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x1,0x7c,0xa5,
0x0,0x0,0x1,0x90,0x30,0xb2,0xff,0x8,
  0x0,0x0,0x0,0x30,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0xe0,0x49,
0x0,0x0,0x1,0x90,0x30,0xb2,0xff,0x8,
  0x0,0x0,0x0,0xa0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x1,0x7d,0x86,
0x0,0x0,0x1,0x90,0x30,0xb2,0xff,0x8,
  0x0,0x0,0x0,0x4e,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0xe1,0x69,
0x0,0x0,0x1,0x90,0x30,0xb2,0xff,0x8,
  0x0,0x0,0x0,0xe2,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x1,0x7f,0x31,
0x0,0x0,0x1,0x90,0x30,0xb2,0xff,0x8,
  0x0,0x0,0x0,0xc0,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x1,0x7e,0x57,
0x0,0x0,0x1,0x90,0x30,0xb2,0xff,0x8,
}
Referenced by qCleanupResources_confdialog(), and qInitResources_confdialog().