qumbia-tango-controls: QuTRealtimePlot Class Reference
QuTRealtimePlot Class Reference
A TPlotLightMarker specialized in managing real time commands.
#include <qutrealtimeplot.h>
Public Slots
void setNumberOfPoints (int n)
Change the number of points (applies to Last N Samples mode)
void setDate1 (const QDateTime &d1)
set the start date (applies to timestamp mode)
void setDate2 (const QDateTime &d2)
set the stop date (applies to timestamp mode)
void setBunch1 (int b)
set bunch 1 (in bunch mode)
void setBunch2 (int b2)
set bunch N (applies to bunch mode)
void updateParams ()
Update the source of the plot according to mode, period, number of points.
Public Member Functions
QuTRealtimePlot (QWidget *parent, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
void setSource (const QString &s)
void setSources (const QStringList &srcs)
virtual QString plotTitle ()
returns the sources configured, together with information about frequency, mode and number of points
int numberOfPoints ()
int mode ()
QDateTime date1 ()
QDateTime date2 ()
int bunch1 ()
int bunch2 ()
void setMode (int m)
changes the mode of the configured sources
Properties
int numberOfPoints
int mode
int bunch1
int bunch2
QDateTime date1
QDateTime date2
Detailed Description
A TPlotLightMarker specialized in managing real time commands.
This class inherits from TPLotLightMarker and is tailored to work with commands. Command syntax only is accepted by setSources, and the configuration dialog available through the right click menu allows the configuration of the real time parameters that caracterize the real time commands. The expected argout returned by the command is of type spectrum.
Constructor & Destructor Documentation
QuTRealtimePlot()
QuTRealtimePlot::QuTRealtimePlot (QWidget * parent, Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac)
Member Function Documentation
bunch1()
int QuTRealtimePlot::bunch1 () inline
bunch2()
int QuTRealtimePlot::bunch2 () inline
date1()
QDateTime QuTRealtimePlot::date1 () inline
date2()
QDateTime QuTRealtimePlot::date2 () inline
mode()
int QuTRealtimePlot::mode () inline
numberOfPoints()
int QuTRealtimePlot::numberOfPoints () inline
plotTitle()
QString QuTRealtimePlot::plotTitle () virtual
returns the sources configured, together with information about frequency, mode and number of points
Reimplemented from EPlotLightBase::plotTitle()
setBunch1
void QuTRealtimePlot::setBunch1 (int b) slot
set bunch 1 (in bunch mode)
See also
setBunch2
References updateParams().
setBunch2
void QuTRealtimePlot::setBunch2 (int b2) slot
set bunch N (applies to bunch mode)
See also
setBunch1
References updateParams().
setDate1
void QuTRealtimePlot::setDate1 (const QDateTime & d1) slot
set the start date (applies to timestamp mode)
References updateParams().
setDate2
void QuTRealtimePlot::setDate2 (const QDateTime & d2) slot
set the stop date (applies to timestamp mode)
See also
setDate1
References updateParams().
setMode()
void QuTRealtimePlot::setMode (int m)
changes the mode of the configured sources
Note: call this after all the following methods, since setMode really changes the read mode of the plot (unsets the sources and sets them again), taking the parameters from the other properties.
modes 0: number of points mode: the configured number of points is read every refresh; 1: bunch1 to bunch N mode; 2: timestamp mode. The configuration parameters for the chosen mode (bunch1, bunch2, date1, date2) are Qt properties. They can be changed programmatically by the corresponding set... methods or by the right click dialog.
References updateParams().
setNumberOfPoints
void QuTRealtimePlot::setNumberOfPoints (int n) slot
Change the number of points (applies to Last N Samples mode)
Note
After calling setMode and (or) setNumberOfPoints remember to apply changes with updateParams
References updateParams().
setSource()
void QuTRealtimePlot::setSource (const QString & s)
References setSources().
setSources()
void QuTRealtimePlot::setSources (const QStringList & srcs)
Referenced by setSource(), and updateParams().
updateParams
void QuTRealtimePlot::updateParams () slot
Update the source of the plot according to mode, period, number of points.
This method is called from numberOfPoints, mode, bunch1, bunchN, date1 or date2
See also
setNumberOfPoints
setMode
setBunch1
setBunch2
setDate1
setDate2
References setSources().
Referenced by setBunch1(), setBunch2(), setDate1(), setDate2(), setMode(), and setNumberOfPoints().
Property Documentation
bunch1
int QuTRealtimePlot::bunch1 read write
bunch2
int QuTRealtimePlot::bunch2 read write
date1
QDateTime QuTRealtimePlot::date1 read write
date2
QDateTime QuTRealtimePlot::date2 read write
mode
int QuTRealtimePlot::mode read write
numberOfPoints
int QuTRealtimePlot::numberOfPoints read write
The documentation for this class was generated from the following files:
qutrealtimeplot.h
qutrealtimeplot.cpp