qumbia-tango-controls: QuTPlotSettings Class Reference
QuTPlotSettings Class Reference
an object (QObject) that applies settings to a plot
#include <qutplotcontextmenustrategy.h>
Public Slots
void configure ()
configuration slot that creates a QDialog and populates it with configuration elements
void apply (const CuData &da)
the CuData passed as parameter is forwarded to the plot through its CuContext
Public Member Functions
QuTPlotSettings (QuPlotBase *plot, bool realtime=false)
creates the QuTPlotSettings (QObject)
virtual ~QuTPlotSettings ()
the class destructor
Detailed Description
an object (QObject) that applies settings to a plot
A pointer to a plot is passed in the constructor and the configure method creates a dialog to change its settings.
Constructor & Destructor Documentation
QuTPlotSettings()
QuTPlotSettings::QuTPlotSettings (QuPlotBase * plot, bool realtime = false)
creates the QuTPlotSettings (QObject)
Parameters
plot a pointer to the QuPlotBase that will be configured
realtime true if the plot is a real time plot, false otherwise. Default: false (real time plot configuration widget unimplemented yet)
Note
the real time plot configuration widget has not yet been made compatible with cumbia-qtcontrols plots
~QuTPlotSettings()
QuTPlotSettings::~QuTPlotSettings () virtual
the class destructor
Member Function Documentation
apply
void QuTPlotSettings::apply (const CuData & da) slot
the CuData passed as parameter is forwarded to the plot through its CuContext
Parameters
da the CuData to be forwarded to the plot in order to change its configuration
Note
The input CuData comes from a signal emitted by a QuConnectionSettingsWidget and will typically store settings to change the period and refresh mode of a Tango source.
Referenced by configure().
configure
void QuTPlotSettings::configure () slot
configuration slot that creates a QDialog and populates it with configuration elements
The dialog contains two tabs:
one configures the plot aspect through EPlotConfigurationWidget
one configures the Tango connection through either RtConfWidget or QuConnectionSettingsWidget, according to the real time parameter being true or false respectively.
The dialog is executed at the end of the method
Note
the real time plot configuration widget has not yet been made compatible with cumbia-qtcontrols plots
References apply().
Referenced by QuTPlotContextMenuStrategy::createMenu().
The documentation for this class was generated from the following files:
qutplotcontextmenustrategy.h
qutplotcontextmenustrategy.cpp