qumbia-tango-controls: CuTControlsUtils Class Reference
CuTControlsUtils Class Reference
utility class offering some functionalities useful to qumbia-tango-controls components.
#include <cutcontrols-utils.h>
Public Member Functions
CuTControlsUtils ()
class constructor
QString replaceWildcards (const QString &s, const QStringList &args)
Replace wildcard arguments ($1, $2, ... $N) in tango sources with the command line arguments.
Detailed Description
utility class offering some functionalities useful to qumbia-tango-controls components.
Currently, the following functions are offered:
replace wildcards from sources and targets
Constructor & Destructor Documentation
CuTControlsUtils()
CuTControlsUtils::CuTControlsUtils ()
class constructor
Just instantiate the object with this empty constructor and then use its methods
Member Function Documentation
replaceWildcards()
QString CuTControlsUtils::replaceWildcards (const QString & s, const QStringList & args)
Replace wildcard arguments ($1, $2, ... $N) in tango sources with the command line arguments.
Parameters
the list of the application arguments (qApp->arguments). The first one (the application name) will be ignored.
s the source which wildcards will be replaced.
examples
source: $1/double_scalar args: ./bin/my_app 2 test/device/1 --> ./bin/my_app and 2 will be ignored. test/device/1 will replace $1
source: $2/double_scalar args: ./bin/app 1 –verbose test/dev/1 test/dev/c --> will be test/dev/c/double_scalar
Referenced by CuTangoReplaceWildcards::replaceWildcards(), CuTControlsReader::setSource(), and CuTControlsWriter::setTarget().
The documentation for this class was generated from the following files:
cutcontrols-utils.h
cutcontrols-utils.cpp