qumbia-tango-controls: QuConnectionSettingsWidget Class Reference
QuConnectionSettingsWidget Class Reference
a QWidget that emits a settingsChanged signal when tango connection settings are changed.
#include <quconnectionsettingswidget.h>
Public Slots
void changeRefresh ()
Signals
void settingsChanged (const CuData &s)
Public Member Functions
QuConnectionSettingsWidget (QWidget *w)
~QuConnectionSettingsWidget ()
Detailed Description
a QWidget that emits a settingsChanged signal when tango connection settings are changed.
Period and refresh mode can be changed.
Constructor & Destructor Documentation
QuConnectionSettingsWidget()
QuConnectionSettingsWidget::QuConnectionSettingsWidget (QWidget * w) explicit
References changeRefresh().
~QuConnectionSettingsWidget()
QuConnectionSettingsWidget::~QuConnectionSettingsWidget ()
Member Function Documentation
changeRefresh
void QuConnectionSettingsWidget::changeRefresh () slot
References settingsChanged().
Referenced by QuConnectionSettingsWidget().
settingsChanged
void QuConnectionSettingsWidget::settingsChanged (const CuData & s) signal
Referenced by changeRefresh().
The documentation for this class was generated from the following files:
quconnectionsettingswidget.h
quconnectionsettingswidget.cpp