qumbia-tango-controls: CuTReaderFactory Class Reference
CuTReaderFactory Class Reference
this factory creates Tango readers. Options can be set.
#include <cutcontrolsreader.h>
Public Member Functions
CuTReaderFactory ()
virtual ~CuTReaderFactory ()
the class destructor
CuControlsReaderA * create (Cumbia *c, CuDataListener *l) const
creates and returns a new CuTControlsReader, configured with the given Cumbia and CuDataListener.
void setOptions (const CuData &o)
CuData getOptions () const
returns the options set with setOptions, or an empty CuData.
CuControlsReaderFactoryI * clone () const
clones the reader factory, allocating a new one with the same options
Detailed Description
this factory creates Tango readers. Options can be set.
Given a pointer to a Cumbia object and a CuDataListener, the create method instantiates and returns a CuTControlsReader, that implements CuControlsReaderA interface. If setOptions is called before create, the options are set on the CuTControlsReader.
Constructor & Destructor Documentation
CuTReaderFactory()
CuTReaderFactory::CuTReaderFactory ()
the class constructor
Referenced by clone().
~CuTReaderFactory()
CuTReaderFactory::~CuTReaderFactory () virtual
the class destructor
Member Function Documentation
clone()
CuControlsReaderFactoryI * CuTReaderFactory::clone () const
clones the reader factory, allocating a new one with the same options
Returns
a new CuTReaderFactory with options copied from this object
References CuTReaderFactory().
create()
CuControlsReaderA * CuTReaderFactory::create (Cumbia * c, CuDataListener * l) const
creates and returns a new CuTControlsReader, configured with the given Cumbia and CuDataListener.
Call setOptions before create to configure the reader.
Parameters
c a pointer to the Cumbia object
l a pointer to an object implementing the CuDataListener interface
Returns
a CuTControlsReader, an implementation of CuControlsReaderA abstract class
References CuTControlsReader::setOptions().
getOptions()
CuData CuTReaderFactory::getOptions () const
returns the options set with setOptions, or an empty CuData.
Returns
CuData with the options set with setOptions, or an empty CuData
setOptions()
void CuTReaderFactory::setOptions (const CuData & o)
call this before create to configure the reader
Parameters
o a CuData compiled with the following options:
"period" an integer, in milliseconds, for the polling period. Converted with: CuVariant::toInt
"refresh_mode": an integer defining the Tango refresh mode. Converted with: CuVariant::toInt
note
Please use the CuTangoOptBuilder class rather than filling in the options manually.
Note
this method must be called before create in order to transfer the options to the Tango CuTControlsReader.
See also
CuTangoOptBuilder
The documentation for this class was generated from the following files:
cutcontrolsreader.h
cutcontrolsreader.cpp
cutcontrolsreader_copy_copy.cpp