qumbia-reader: QumbiaReader Class Reference
QumbiaReader Class Reference
#include <qumbia-reader.h>
Public Types
enum Verbosity { Low, Medium, High, Debug }
Public Slots
void onNewDouble (const QString &src, double ts, double val, const CuData &da)
void onNewFloat (const QString &src, double ts, float val, const CuData &da)
void onNewShort (const QString &src, double ts, short val, const CuData &da)
void onNewBool (const QString &src, double ts, bool val, const CuData &da)
void onNewUShort (const QString &src, double ts, unsigned short val, const CuData &da)
void onNewLong (const QString &src, double ts, long val, const CuData &da)
void onNewULong (const QString &src, double ts, unsigned long val, const CuData &da)
void onNewString (const QString &src, double ts, const QString &val, const CuData &da)
void onStringConversion (const QString &src, const QString &fromType, double timestamp_us, const QString &v, const CuData &da)
void onNewDoubleVector (const QString &src, double ts, const QVector< double > &v, const CuData &da)
void onNewFloatVector (const QString &src, double ts, const QVector< float > &v, const CuData &da)
void onNewBoolVector (const QString &src, double ts, const QVector< bool > &v, const CuData &da)
void onNewShortVector (const QString &src, double ts, const QVector< short > &v, const CuData &da)
void onNewUShortVector (const QString &src, double ts, const QVector< unsigned short > &v, const CuData &da)
void onNewLongVector (const QString &src, double ts, const QVector< long > &v, const CuData &da)
void onNewULongVector (const QString &src, double ts, const QVector< unsigned long > &v, const CuData &da)
void onNewStringList (const QString &src, double ts, const QStringList &val, const CuData &da)
void onStringListConversion (const QString &src, const QString &fromType, double timestamp_us, const QStringList &v, const CuData &da)
void onPropertyReady (const QString &src, double ts, const CuData &p)
void onError (const QString &src, double ts, const QString &msg, const CuData &da)
Public Member Functions
QumbiaReader (CumbiaPool *cu_p, QWidget *parent=0)
~QumbiaReader ()
QString makeTimestamp (const double d) const
bool usage_only () const
Member Enumeration Documentation
Verbosity
enum QumbiaReader::Verbosity
Enumerator
Low
Medium
High
Debug
Constructor & Destructor Documentation
QumbiaReader()
QumbiaReader::QumbiaReader (CumbiaPool * cu_p, QWidget * parent = 0) explicit
References RConfig::list_options, CmdLineOptions::list_options(), Low, RConfig::max_timers, Medium, CmdLineOptions::parse(), RConfig::refresh_limit, RConfig::sources, RConfig::usage, and CmdLineOptions::usage().
~QumbiaReader()
QumbiaReader::~QumbiaReader ()
Member Function Documentation
makeTimestamp()
QString QumbiaReader::makeTimestamp (const double d) const
Referenced by onError(), onNewBool(), onNewBoolVector(), onNewDouble(), onNewDoubleVector(), onNewFloat(), onNewFloatVector(), onNewLong(), onNewLongVector(), onNewShort(), onNewShortVector(), onNewString(), onNewStringList(), onNewULong(), onNewULongVector(), onNewUShort(), onNewUShortVector(), onPropertyReady(), onStringConversion(), and onStringListConversion().
onError
void QumbiaReader::onError (const QString & src, double ts, const QString & msg, const CuData & da) slot
References makeTimestamp().
onNewBool
void QumbiaReader::onNewBool (const QString & src, double ts, bool val, const CuData & da) slot
References makeTimestamp().
onNewBoolVector
void QumbiaReader::onNewBoolVector (const QString & src, double ts, const QVector< bool > & v, const CuData & da) slot
References makeTimestamp(), and RConfig::truncate.
onNewDouble
void QumbiaReader::onNewDouble (const QString & src, double ts, double val, const CuData & da) slot
References makeTimestamp().
onNewDoubleVector
void QumbiaReader::onNewDoubleVector (const QString & src, double ts, const QVector< double > & v, const CuData & da) slot
References makeTimestamp(), and RConfig::truncate.
onNewFloat
void QumbiaReader::onNewFloat (const QString & src, double ts, float val, const CuData & da) slot
References makeTimestamp().
onNewFloatVector
void QumbiaReader::onNewFloatVector (const QString & src, double ts, const QVector< float > & v, const CuData & da) slot
References makeTimestamp(), and RConfig::truncate.
onNewLong
void QumbiaReader::onNewLong (const QString & src, double ts, long val, const CuData & da) slot
References makeTimestamp().
onNewLongVector
void QumbiaReader::onNewLongVector (const QString & src, double ts, const QVector< long > & v, const CuData & da) slot
References makeTimestamp(), and RConfig::truncate.
onNewShort
void QumbiaReader::onNewShort (const QString & src, double ts, short val, const CuData & da) slot
References makeTimestamp().
onNewShortVector
void QumbiaReader::onNewShortVector (const QString & src, double ts, const QVector< short > & v, const CuData & da) slot
References makeTimestamp(), and RConfig::truncate.
onNewString
void QumbiaReader::onNewString (const QString & src, double ts, const QString & val, const CuData & da) slot
References makeTimestamp().
onNewStringList
void QumbiaReader::onNewStringList (const QString & src, double ts, const QStringList & val, const CuData & da) slot
References makeTimestamp(), and RConfig::truncate.
onNewULong
void QumbiaReader::onNewULong (const QString & src, double ts, unsigned long val, const CuData & da) slot
References makeTimestamp().
onNewULongVector
void QumbiaReader::onNewULongVector (const QString & src, double ts, const QVector< unsigned long > & v, const CuData & da) slot
References makeTimestamp(), and RConfig::truncate.
onNewUShort
void QumbiaReader::onNewUShort (const QString & src, double ts, unsigned short val, const CuData & da) slot
References makeTimestamp().
onNewUShortVector
void QumbiaReader::onNewUShortVector (const QString & src, double ts, const QVector< unsigned short > & v, const CuData & da) slot
References makeTimestamp(), and RConfig::truncate.
onPropertyReady
void QumbiaReader::onPropertyReady (const QString & src, double ts, const CuData & p) slot
References Debug, Low, makeTimestamp(), and RConfig::verbosity.
onStringConversion
void QumbiaReader::onStringConversion (const QString & src, const QString & fromType, double timestamp_us, const QString & v, const CuData & da) slot
References makeTimestamp().
onStringListConversion
void QumbiaReader::onStringListConversion (const QString & src, const QString & fromType, double timestamp_us, const QStringList & v, const CuData & da) slot
References makeTimestamp().
usage_only()
bool QumbiaReader::usage_only () const
References RConfig::list_options, and RConfig::usage.
Referenced by main().
The documentation for this class was generated from the following files:
qumbia-reader.h
qumbia-reader.cpp