qumbia-reader: QuR_HdbHelper Class Reference
QuR_HdbHelper Class Reference
#include <qur_hdbhelper.h>
Public Member Functions
QuR_HdbHelper ()
void mergeResult (const QString &src, const CuData &data)
bool isComplete (const QString &name) const
bool allComplete () const
CuData take (const QString &src)
QList< CuData > takeAll ()
void print_all (const QList< CuData > &dl, const QString &out_filenam=QString(), bool color=true)
void print_note (FILE *fp, const std::vector< double > &notes_ts, const std::vector< std::string > &notes, size_t index, bool on_file)
Constructor & Destructor Documentation
QuR_HdbHelper()
QuR_HdbHelper::QuR_HdbHelper ()
Member Function Documentation
allComplete()
bool QuR_HdbHelper::allComplete () const
References isComplete().
Referenced by QumbiaReader::onNewHdbData().
isComplete()
bool QuR_HdbHelper::isComplete (const QString & name) const
Referenced by allComplete().
mergeResult()
void QuR_HdbHelper::mergeResult (const QString & src, const CuData & data)
References data.
Referenced by QumbiaReader::onNewHdbData().
print_all()
void QuR_HdbHelper::print_all (const QList< CuData > & dl, const QString & out_filenam = QString(), bool color = true)
References print_note().
Referenced by QumbiaReader::onNewHdbData().
print_note()
void QuR_HdbHelper::print_note (FILE * fp, const std::vector< double > & notes_ts, const std::vector< std::string > & notes, size_t index, bool on_file)
Referenced by print_all().
take()
CuData QuR_HdbHelper::take (const QString & src)
takeAll()
QList< CuData > QuR_HdbHelper::takeAll ()
Referenced by QumbiaReader::onNewHdbData().
The documentation for this class was generated from the following files:
qur_hdbhelper.h
qur_hdbhelper.cpp