qumbia-reader: CmdLineOptions Class Reference
CmdLineOptions Class Reference
#include <cmdlineoptions.h>
Public Member Functions
CmdLineOptions ()
RConfig parse (const QStringList &args) const
void usage (const QString &appname) const
void help (const QString &appname, const QString &modulenam) const
void list_options () const
Constructor & Destructor Documentation
CmdLineOptions()
CmdLineOptions::CmdLineOptions ()
Member Function Documentation
help()
void CmdLineOptions::help (const QString & appname, const QString & modulenam) const
References QUMBIA_READER_DOC_URL.
Referenced by parse().
list_options()
void CmdLineOptions::list_options () const
Referenced by QumbiaReader::QumbiaReader().
parse()
RConfig CmdLineOptions::parse (const QStringList & args) const
References QumbiaReader::Debug, RConfig::format, help(), QumbiaReader::High, RConfig::list_options, RConfig::max_timers, QumbiaReader::Medium, RConfig::period, RConfig::refresh_limit, RConfig::setPropertyOnly(), RConfig::setTangoProperty(), RConfig::sources, RConfig::truncate, RConfig::usage, and RConfig::verbosity.
Referenced by QumbiaReader::QumbiaReader().
usage()
void CmdLineOptions::usage (const QString & appname) const
Referenced by QumbiaReader::QumbiaReader().
The documentation for this class was generated from the following files:
cmdlineoptions.h
cmdlineoptions.cpp