qumbia-reader: Qu_Reader Class Reference
Qu_Reader Class Reference
#include <qureader.h>
Public Slots
void setSource (const QString &s)
void getTgProps ()
Signals
void newDouble (const QString &src, double timestamp_us, double val, const CuData &da)
void newFloat (const QString &src, double timestamp_us, float val, const CuData &da)
void newBool (const QString &src, double timestamp_us, bool val, const CuData &da)
void newLong (const QString &src, double timestamp_us, long val, const CuData &da)
void newShort (const QString &src, double timestamp_us, short val, const CuData &da)
void newUShort (const QString &src, double timestamp_us, unsigned short val, const CuData &da)
void newULong (const QString &src, double timestamp_us, unsigned long val, const CuData &da)
void newString (const QString &src, double timestamp_us, const QString &val, const CuData &da)
void toString (const QString &src, const QString &fromType, double timestamp_us, const QString &val, const CuData &da)
void newDoubleVector (const QString &src, double timestamp_us, const QVector< double > &v, const CuData &da)
void newFloatVector (const QString &src, double timestamp_us, const QVector< float > &v, const CuData &da)
void newBoolVector (const QString &src, double timestamp_us, const QVector< bool > &v, const CuData &da)
void newShortVector (const QString &src, double timestamp_us, const QVector< short > &v, const CuData &da)
void newLongVector (const QString &src, double timestamp_us, const QVector< long > &v, const CuData &da)
void newULongVector (const QString &src, double timestamp_us, const QVector< unsigned long > &v, const CuData &da)
void newUShortVector (const QString &src, double timestamp_us, const QVector< unsigned short > &v, const CuData &da)
void newStringList (const QString &src, double timestamp_us, const QStringList &v, const CuData &da)
void toStringList (const QString &src, const QString &fromType, double timestamp_us, const QStringList &v, const CuData &da)
void newError (const QString &src, double timestamp_us, const QString &msg, const CuData &da)
void propertyReady (const QString &src, double timestamp_us, const CuData &p)
Public Member Functions
Qu_Reader (QObject *parent, CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool)
~Qu_Reader ()
void propertyOnly ()
void saveProperty ()
void setTgPropertyList (const QStringList &props)
void setContextOptions (const CuData &options)
virtual void onUpdate (const CuData &data)
QString source () const
void stop ()
void setPeriod (int ms)
Constructor & Destructor Documentation
Qu_Reader()
Qu_Reader::Qu_Reader (QObject * parent, CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool)
~Qu_Reader()
Qu_Reader::~Qu_Reader ()
Member Function Documentation
getTgProps
void Qu_Reader::getTgProps () slot
newBool
void Qu_Reader::newBool (const QString & src, double timestamp_us, bool val, const CuData & da) signal
Referenced by onUpdate().
newBoolVector
void Qu_Reader::newBoolVector (const QString & src, double timestamp_us, const QVector< bool > & v, const CuData & da) signal
Referenced by onUpdate().
newDouble
void Qu_Reader::newDouble (const QString & src, double timestamp_us, double val, const CuData & da) signal
Referenced by onUpdate().
newDoubleVector
void Qu_Reader::newDoubleVector (const QString & src, double timestamp_us, const QVector< double > & v, const CuData & da) signal
Referenced by onUpdate().
newError
void Qu_Reader::newError (const QString & src, double timestamp_us, const QString & msg, const CuData & da) signal
Referenced by onUpdate().
newFloat
void Qu_Reader::newFloat (const QString & src, double timestamp_us, float val, const CuData & da) signal
Referenced by onUpdate().
newFloatVector
void Qu_Reader::newFloatVector (const QString & src, double timestamp_us, const QVector< float > & v, const CuData & da) signal
Referenced by onUpdate().
newLong
void Qu_Reader::newLong (const QString & src, double timestamp_us, long val, const CuData & da) signal
Referenced by onUpdate().
newLongVector
void Qu_Reader::newLongVector (const QString & src, double timestamp_us, const QVector< long > & v, const CuData & da) signal
Referenced by onUpdate().
newShort
void Qu_Reader::newShort (const QString & src, double timestamp_us, short val, const CuData & da) signal
Referenced by onUpdate().
newShortVector
void Qu_Reader::newShortVector (const QString & src, double timestamp_us, const QVector< short > & v, const CuData & da) signal
Referenced by onUpdate().
newString
void Qu_Reader::newString (const QString & src, double timestamp_us, const QString & val, const CuData & da) signal
Referenced by onUpdate().
newStringList
void Qu_Reader::newStringList (const QString & src, double timestamp_us, const QStringList & v, const CuData & da) signal
Referenced by onUpdate().
newULong
void Qu_Reader::newULong (const QString & src, double timestamp_us, unsigned long val, const CuData & da) signal
Referenced by onUpdate().
newULongVector
void Qu_Reader::newULongVector (const QString & src, double timestamp_us, const QVector< unsigned long > & v, const CuData & da) signal
Referenced by onUpdate().
newUShort
void Qu_Reader::newUShort (const QString & src, double timestamp_us, unsigned short val, const CuData & da) signal
Referenced by onUpdate().
newUShortVector
void Qu_Reader::newUShortVector (const QString & src, double timestamp_us, const QVector< unsigned short > & v, const CuData & da) signal
Referenced by onUpdate().
onUpdate()
void Qu_Reader::onUpdate (const CuData & data) virtual
References newBool(), newBoolVector(), newDouble(), newDoubleVector(), newError(), newFloat(), newFloatVector(), newLong(), newLongVector(), newShort(), newShortVector(), newString(), newStringList(), newULong(), newULongVector(), newUShort(), newUShortVector(), propertyReady(), toString(), and toStringList().
propertyOnly()
void Qu_Reader::propertyOnly ()
propertyReady
void Qu_Reader::propertyReady (const QString & src, double timestamp_us, const CuData & p) signal
Referenced by onUpdate().
saveProperty()
void Qu_Reader::saveProperty ()
setContextOptions()
void Qu_Reader::setContextOptions (const CuData & options)
setPeriod()
void Qu_Reader::setPeriod (int ms)
setSource
void Qu_Reader::setSource (const QString & s) slot
setTgPropertyList()
void Qu_Reader::setTgPropertyList (const QStringList & props)
source()
QString Qu_Reader::source () const
stop()
void Qu_Reader::stop ()
toString
void Qu_Reader::toString (const QString & src, const QString & fromType, double timestamp_us, const QString & val, const CuData & da) signal
Referenced by onUpdate().
toStringList
void Qu_Reader::toStringList (const QString & src, const QString & fromType, double timestamp_us, const QStringList & v, const CuData & da) signal
Referenced by onUpdate().
The documentation for this class was generated from the following files:
qureader.h
qureader.cpp