#ifndef QUMBIAEPICSCONTROLS_GLOBAL_H
#define QUMBIAEPICSCONTROLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUMBIAEPICSCONTROLS_LIBRARY)
#  define QUMBIAEPICSCONTROLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QUMBIAEPICSCONTROLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QUMBIAEPICSCONTROLS_GLOBAL_H
