cuuimake: Substitutions Class Reference
Substitutions Class Reference
#include <defs.h>
Public Member Functions
void selectMode (const QString &m)
QString selectedMode () const
void insertSubstitution (const QString &className, const QString &var_name)
QString getSubstitution (const QString &className) const
QString toString () const
Member Function Documentation
getSubstitution()
QString Substitutions::getSubstitution (const QString & className) const inline
Referenced by Processor::expand().
insertSubstitution()
void Substitutions::insertSubstitution (const QString & className, const QString & var_name) inline
Referenced by Parser::detect().
selectedMode()
QString Substitutions::selectedMode () const inline
Referenced by Parser::detect(), and Processor::expand().
selectMode()
void Substitutions::selectMode (const QString & m) inline
Referenced by Parser::detect().
toString()
QString Substitutions::toString () const inline
Referenced by Parser::detect().
The documentation for this class was generated from the following file:
defs.h