cuuimake: SearchDirInfo Class Reference
SearchDirInfo Class Reference
#include <defs.h>
Public Member Functions
SearchDirInfo (const QString &dirnam, const QString &filters)
QString name () const
QStringList filters () const
SearchDirInfo ()
QString toString () const
Constructor & Destructor Documentation
SearchDirInfo() [1/2]
SearchDirInfo::SearchDirInfo (const QString & dirnam, const QString & filters) inline
References filters().
SearchDirInfo() [2/2]
SearchDirInfo::SearchDirInfo () inline
Member Function Documentation
filters()
QStringList SearchDirInfo::filters () const inline
Referenced by Parser::detect(), Processor::findUI_H(), Defs::guessFromSources(), Processor::remove_UI_H(), and SearchDirInfo().
name()
QString SearchDirInfo::name () const inline
Referenced by Parser::detect(), Processor::findUI_H(), SearchDirInfoSet::getDirInfoList(), Defs::guessFromSources(), and Processor::remove_UI_H().
toString()
QString SearchDirInfo::toString () const inline
The documentation for this class was generated from the following file:
defs.h