cuuimake: Defs Class Reference
Defs Class Reference
#include <defs.h>
Public Member Functions
Defs ()
bool loadConf (const QString &default_conf, const QString &localfname)
bool guessFromSources ()
QString lastError () const
bool error () const
void m_getParams (const QDomNode &parent, Params &params)
void setDebug (bool db)
QMap< QString, Expand > getObjectMap () const
QList< Search > getSearchList () const
SearchDirInfoSet srcDirsInfo () const
Public Attributes
QStringList messages
Constructor & Destructor Documentation
Defs()
Defs::Defs ()
Member Function Documentation
error()
bool Defs::error () const
getObjectMap()
QMap< QString, Expand > Defs::getObjectMap () const
getSearchList()
QList< Search > Defs::getSearchList () const
guessFromSources()
bool Defs::guessFromSources ()
References Expand::autoDetect(), Expand::autoDetectRegexp(), SearchDirInfo::filters(), SearchDirInfoSet::getDirInfoList(), messages, SearchDirInfo::name(), Expand::object, and SearchDirInfoSet::Source.
lastError()
QString Defs::lastError () const
loadConf()
bool Defs::loadConf (const QString & default_conf, const QString & localfname)
References Search::toString().
m_getParams()
void Defs::m_getParams (const QDomNode & parent, Params & params)
References Params::add(), and Par::pardef.
setDebug()
void Defs::setDebug (bool db)
srcDirsInfo()
SearchDirInfoSet Defs::srcDirsInfo () const
Member Data Documentation
messages
QStringList Defs::messages
Referenced by guessFromSources().
The documentation for this class was generated from the following files:
defs.h
defs.cpp
src/defs.cpp