cuuimake: Processor Class Reference
Processor Class Reference
#include <processor.h>
Public Member Functions
Processor ()
bool expand (const Substitutions &subs, const QMap< QString, Expand > &widgetExpMap, const QString &ui_h_fname, const SearchDirInfoSet &dirInfoSet)
QMap< QString, bool > findUI_H (const SearchDirInfoSet &dirInfoSet)
int remove_UI_H (const SearchDirInfoSet &dirInfoSet)
void setDebug (bool d)
bool error () const
QString lastError () const
Constructor & Destructor Documentation
Processor()
Processor::Processor ()
Member Function Documentation
error()
bool Processor::error () const inline
expand()
bool Processor::expand (const Substitutions & subs, const QMap< QString, Expand > & widgetExpMap, const QString & ui_h_fname, const SearchDirInfoSet & dirInfoSet)
References Par::classname, Substitutions::getSubstitution(), Par::pardef, Substitutions::selectedMode(), and Par::toString().
findUI_H()
QMap< QString, bool > Processor::findUI_H (const SearchDirInfoSet & dirInfoSet)
References SearchDirInfo::filters(), SearchDirInfoSet::getDirInfoList(), SearchDirInfo::name(), and SearchDirInfoSet::Source.
lastError()
QString Processor::lastError () const inline
remove_UI_H()
int Processor::remove_UI_H (const SearchDirInfoSet & dirInfoSet)
References SearchDirInfo::filters(), SearchDirInfoSet::getDirInfoList(), SearchDirInfo::name(), and qstoc.
setDebug()
void Processor::setDebug (bool d) inline
The documentation for this class was generated from the following files:
processor.h
processor.cpp