cuuimake: SearchDirInfoSet Class Reference
SearchDirInfoSet Class Reference
#include <defs.h>
Public Types
enum Type { Source , Ui , Ui_H }
Public Member Functions
SearchDirInfoSet ()
void add (const QString &dirnm, const QString &filters, Type t)
QList< SearchDirInfo > getDirInfoList (Type t) const
bool isEmpty () const
Member Enumeration Documentation
Type
enum SearchDirInfoSet::Type
Enumerator
Source
Constructor & Destructor Documentation
SearchDirInfoSet()
SearchDirInfoSet::SearchDirInfoSet () inline
Member Function Documentation
add()
void SearchDirInfoSet::add (const QString & dirnm, const QString & filters, Type t) inline
getDirInfoList()
QList< SearchDirInfo > SearchDirInfoSet::getDirInfoList (Type t) const inline
References SearchDirInfo::name().
Referenced by Parser::detect(), Processor::findUI_H(), Defs::guessFromSources(), and Processor::remove_UI_H().
isEmpty()
bool SearchDirInfoSet::isEmpty () const inline
Referenced by Parser::detect().
The documentation for this class was generated from the following file:
defs.h