cuuimake: Params Class Reference
Params Class Reference
#include <defs.h>
Public Member Functions
Params ()
void add (const QString &mode, const QList< Par > &p)
QString getType (const QString &mode, const QString &name)
QString getName (const QString &mode, const QString &type)
QList< Par > getParList (const QString &mode) const
bool isValid () const
QString toString () const
Constructor & Destructor Documentation
Params()
Params::Params () inline
Member Function Documentation
add()
void Params::add (const QString & mode, const QList< Par > & p) inline
Referenced by Defs::m_getParams().
getName()
QString Params::getName (const QString & mode, const QString & type) inline
References Par::classname, and Par::pardef.
getParList()
QList<Par> Params::getParList (const QString & mode) const inline
getType()
QString Params::getType (const QString & mode, const QString & name) inline
References Par::classname, and Par::pardef.
isValid()
bool Params::isValid () const inline
toString()
QString Params::toString () const inline
References Par::toString().
Referenced by Expand::toString().
The documentation for this class was generated from the following file:
defs.h