cuuimake: Parser Class Reference
Parser Class Reference
#include <parser.h>
Public Member Functions
Parser (const QString &force_mode="")
QString detect (const SearchDirInfoSet &dirInfoSet, const QList< Search > &searchlist, Substitutions &subs)
bool error () const
QString lastError () const
void setDebug (bool dbg)
const char * tos (const QString &s)
bool find_match (const QString &contents, const QString &classname, QString &varname) const
Constructor & Destructor Documentation
Parser()
Parser::Parser (const QString & force_mode = "")
Member Function Documentation
detect()
QString Parser::detect (const SearchDirInfoSet & dirInfoSet, const QList< Search > & searchlist, Substitutions & subs)
References error(), Search::factory, SearchDirInfo::filters(), find_match(), SearchDirInfoSet::getDirInfoList(), Substitutions::insertSubstitution(), SearchDirInfoSet::isEmpty(), SearchDirInfo::name(), qstoc, Search::searches, Substitutions::selectedMode(), Substitutions::selectMode(), SearchDirInfoSet::Source, and Substitutions::toString().
error()
bool Parser::error () const
Referenced by detect().
find_match()
bool Parser::find_match (const QString & contents, const QString & classname, QString & varname) const
Referenced by detect().
lastError()
QString Parser::lastError () const
setDebug()
void Parser::setDebug (bool dbg)
tos()
const char * Parser::tos (const QString & s)
The documentation for this class was generated from the following files:
parser.h
parser.cpp