cuuimake: Options Class Reference
Options Class Reference
#include <options.h>
Public Member Functions
Options (const QStringList &args)
QVariant getopt (const QString &name)
QStringList help (const QString &param)
bool error () const
QString lastError () const
void printHelp (const CuUiMake &cm) const
void printOptionsList (const CuUiMake &cm) const
void printOptions (const CuUiMake &cm, const QStringList &theseOptions=QStringList()) const
QString make_j () const
bool configure (const CuUiMake &cm)
Constructor & Destructor Documentation
Options()
Options::Options (const QStringList & args)
References LIST_PARAM_RE.
Member Function Documentation
configure()
bool Options::configure (const CuUiMake & cm)
References qstoc.
error()
bool Options::error () const inline
getopt()
QVariant Options::getopt (const QString & name)
help()
QStringList Options::help (const QString & param)
Referenced by printHelp(), and printOptions().
lastError()
QString Options::lastError () const inline
make_j()
QString Options::make_j () const
printHelp()
void Options::printHelp (const CuUiMake & cm) const
References help(), and qstoc.
printOptions()
void Options::printOptions (const CuUiMake & cm, const QStringList & theseOptions = QStringList()) const
References help(), LIST_PARAM_RE, and qstoc.
printOptionsList()
void Options::printOptionsList (const CuUiMake & cm) const
The documentation for this class was generated from the following files:
options.h
options.cpp