cuuimake: Expand Class Reference
Expand Class Reference
#include <defs.h>
Public Member Functions
Expand (const QString &wnam, const Params &par, bool from_local_file)
Expand (const QString &wnam, const Params &par, bool from_local_file, bool method)
Expand ()
void setAutoDetectRegexp (const QString &pattern)
QString autoDetectRegexp () const
void setAutoDetect (bool ad)
bool autoDetect () const
bool fromLocalConf () const
bool isMethod () const
QString toString () const
Public Attributes
QString object
Params params
Constructor & Destructor Documentation
Expand() [1/3]
Expand::Expand (const QString & wnam, const Params & par, bool from_local_file) inline
References params.
Expand() [2/3]
Expand::Expand (const QString & wnam, const Params & par, bool from_local_file, bool method) inline
References params.
Expand() [3/3]
Expand::Expand () inline
Member Function Documentation
autoDetect()
bool Expand::autoDetect () const inline
Referenced by Defs::guessFromSources().
autoDetectRegexp()
QString Expand::autoDetectRegexp () const inline
Referenced by Defs::guessFromSources().
fromLocalConf()
bool Expand::fromLocalConf () const inline
isMethod()
bool Expand::isMethod () const inline
setAutoDetect()
void Expand::setAutoDetect (bool ad) inline
setAutoDetectRegexp()
void Expand::setAutoDetectRegexp (const QString & pattern) inline
toString()
QString Expand::toString () const inline
References params, and Params::toString().
Member Data Documentation
object
QString Expand::object
Referenced by Defs::guessFromSources().
params
Params Expand::params
Referenced by Expand(), Expand(), Processor::expand(), and toString().
The documentation for this class was generated from the following file:
defs.h