cumbia: CuContinuousActivity Class Reference
CuContinuousActivity Class Reference
an implementation of CuActivity that calls CuActivity::execute repeatedly at a certain interval of time expressed in milliseconds.
#include <cucontinuousactivity.h>
Public Member Functions
CuContinuousActivity (const CuData &token=CuData(), int interval=1000, CuActivityManager *activityManager=NULL)
the class constructor. Initializes a continuous activity with an interval in milliseconds.
virtual ~CuContinuousActivity ()
the class destructor
void setInterval (int millis)
sets the time, in milliseconds, between two subsequent calls of the execute method
int getTimeout () const
returns the time, in milliseconds, between two subsequent calls of the execute method
int repeat () const
returns the interval of time, in milliseconds, before the next CuActivity::execute call, or zero or negative in order to not execute again
int getType () const
returns the activity type
void event (CuActivityEvent *e)
received in the CuActivity thread from the main thread, it can change the execution timeout, pause, resume and trigger an execution
Public Member Functions inherited from CuActivity
CuActivity (CuActivityManager *activityManager, const CuData &token=CuData())
CuActivity (const CuData &token=CuData())
virtual ~CuActivity ()
void setActivityManager (CuActivityManager *am)
virtual int getFlags () const
returns the activity flags
int getStateFlags () const
returns the activity state flags
void setFlags (int f)
set the flags on the activity
void setFlag (Flags f, bool on)
set a specific CuActivity::Flags flag true or false
virtual bool matches (const CuData &token) const =0
virtual void dispose (bool disposable=true)
virtual bool isDisposable () const
void publishResult (const CuData &data)
Publish a result from the activity thread (whence the method is called) to the main thread.
void publishProgress (int step, int total, const CuData &data)
Publish a progress from the activity thread (whence the method is called) to the main thread.
void publishExitResult (const CuData *data)
void publishResult (const std::vector< CuData > *datalist)
CuActivityManager * getActivityManager () const
CuData getToken () const
return the activity token
void setThreadToken (const CuData &tt)
const CuData & threadToken () const
void doInit ()
void doExecute ()
void doOnExit ()
calls the pure virtual method onExit, gets the thread it belongs and calls CuThreadInterface::publishExitEvent
void exitOnThreadQuit ()
template method. Calls onExit only, without publishing exit event, because the thread is leaving its loop.
Additional Inherited Members
Public Types inherited from CuActivity
enum Flags { CuAUnregisterAfterExec = 0x01, CuADeleteOnExit = 0x02, CuAUserStartFlags = 0x0100, MaxUserFlags = 0x8000 }
enum StateFlags { CuAStateInit = 0x01, CuAStateExecute = 0x02, CuAStateOnExit = 0x04 }
enum ActivityType { Isolated = 0, Continuous, User = 100 }
Protected Member Functions inherited from CuActivity
virtual void init ()=0
virtual void execute ()=0
virtual void onExit ()=0
Detailed Description
an implementation of CuActivity that calls CuActivity::execute repeatedly at a certain interval of time expressed in milliseconds.
This is a convenience class to implement a poller that executes code in a separate thread with a period expressed in milliseconds. setInterval can be used to change the period, also at runtime.
The CuContinuousActivity::repeat method can be used (i.e. reimplemented) to suspend the call to the CuActivity::execute method. The default implementation returns the period (see setInterval, getTimeout) or zero if a CuActivityEvent::Pause event has been received (see CuContinuousActivity::event)
The cumbia-tango module defines an implementation of CuContinuousActivity named CuPollingActivity that reads Tango attributes or commands periodically.
Constructor & Destructor Documentation
CuContinuousActivity()
CuContinuousActivity::CuContinuousActivity (const CuData & token = CuData(), int interval = 1000, CuActivityManager * activityManager = NULL)
the class constructor. Initializes a continuous activity with an interval in milliseconds.
Parameters
token a CuData used to characterise the activity. It is used by the CuActivity::matches method to match similar activities. The meaning of similar is determined by the nature of the activity and within the CuActivity::matches method. (Default: empty CuData)
interval an integer, in milliseconds, that determines the time between two subsequent CuActivity::execute calls (default: 1000)
activityManager a pointer to a CuActivityManager (default: NULL and usually set later by Cumbia::registerActivity)
The constructor sets the activity flags to CuADeleteOnExit | CuAUnregisterAfterExec, so that the activity is deleted after it finishes and automatically unregister after the execution. The flags can be changed with CuActivity:setFlags or CuActivity::setFlags
The interval can be changed with setInterval
References CuActivity::CuADeleteOnExit, CuActivity::CuAUnregisterAfterExec, and CuActivity::setFlags().
~CuContinuousActivity()
CuContinuousActivity::~CuContinuousActivity () virtual
the class destructor
Member Function Documentation
event()
void CuContinuousActivity::event (CuActivityEvent * e) virtual
received in the CuActivity thread from the main thread, it can change the execution timeout, pause, resume and trigger an execution
Parameters
e an event implementing the CuActivityEvent interface
Four kind of events are recognised and processed:
timeout change (CuActivityEvent::TimeoutChange)
pause the execution of the continuous activity (CuActivityEvent::Pause)
resume the execution of the activity (CuActivityEvent::Resume)
trigger an execution (CuEventActivity::Execute)
Implements CuActivity.
References CuActivityEvent::Execute, CuActivity::execute(), CuActivityEvent::getType(), CuActivityEvent::Pause, CuActivityEvent::Resume, and CuActivityEvent::TimeoutChange.
getTimeout()
int CuContinuousActivity::getTimeout () const
returns the time, in milliseconds, between two subsequent calls of the execute method
Returns
the interval between two execute calls in a continuous activity (milliseconds)
getType()
int CuContinuousActivity::getType () const virtual
returns the activity type
Returns
the activity type: CuActivity::Continuous
Implements CuActivity.
References CuActivity::Continuous.
repeat()
int CuContinuousActivity::repeat () const virtual
returns the interval of time, in milliseconds, before the next CuActivity::execute call, or zero or negative in order to not execute again
Returns
an integer greater than zero representing the interval, in milliseconds, before next execution or zero (or negative) to prevent CuActivity::execute to be called again
This implementation returns the value of CuContinuousActivity::getTimeout if the activity is not paused, zero otherwise
Implements CuActivity.
setInterval()
void CuContinuousActivity::setInterval (int millis)
sets the time, in milliseconds, between two subsequent calls of the execute method
Parameters
millis the interval between two CuActivity::execute calls in a continuous activity (milliseconds)
The documentation for this class was generated from the following files:
cucontinuousactivity.h
cucontinuousactivity.cpp