cumbia: CuTimer Class Reference
CuTimer Class Reference
a timer used by CuThread for periodic execution of an activity
#include <cutimer.h>
Public Member Functions
CuTimer (CuTimerListener *l)
create the timer and install the listener
~CuTimer ()
class destructor
void setTimeout (int millis)
change the timeout
void setSingleShot (bool single)
enable or disable the single shot mode
int timeout () const
return the timeout in milliseconds
bool isSingleShot () const
returns true if the single shot mode is enabled.
void pause ()
pause the timer is paused
void start (int millis)
start the timer with the given interval in milliseconds
void resume ()
the timer is resumed if paused, started if not running
void stop ()
stops the timer, if active
Protected Member Functions
void run ()
the timer loop
Detailed Description
a timer used by CuThread for periodic execution of an activity
This class is used internally by the cumbia library.
When the timer is started, it creates a new std::thread that calls CuTimerListener::onTimeout each time the timeout expires. CuTimerListener is installed in the CuTimer constructor.
In the cumbia library CuTimer is used by CuThread. CuThread is a CuTimerListener and, within CuThread::onTimeout a timer event is pushed into the CuThread's event queue.
A timer can be started, stopped, paused and resumed. Timeout can be changed. The timer can also be used in the single shot mode, and in this case it is run only once. The timeout is in milliseconds. CuThread uses the timer in single shot mode.
CuThread creates and runs a CuTimer after an activity is registered. CuTimer is created in the CuThread's background thread if the CuActivity::repeat method returns greater than zero (in the private member CuThread::mActivityInit).
Constructor & Destructor Documentation
CuTimer()
CuTimer::CuTimer (CuTimerListener * l)
create the timer and install the listener
Parameters
l a CuTimerListener
CuThread is a CuTimerListener
By default, the timeout is set to 1000 milliseconds, and the single shot property is true.
~CuTimer()
CuTimer::~CuTimer ()
class destructor
If still running, CuTimer::stop is called to interrupt the timer and join the thread
References pdelete, and stop().
Member Function Documentation
isSingleShot()
bool CuTimer::isSingleShot () const
returns true if the single shot mode is enabled.
Returns
true: the timer is running once
false: the timer is run repeatedly
pause()
void CuTimer::pause ()
pause the timer is paused
A timeout of ULONG_MAX (limits.h) is set on the timer
References pbblue.
Referenced by CuThread::run().
resume()
void CuTimer::resume ()
the timer is resumed if paused, started if not running
The timer is resumed if the timer thread is still running, started otherwise
References pbblue, and start().
Referenced by CuThread::run().
run()
void CuTimer::run () protected
the timer loop
Note
internally used by the library
The timer loop waits for the timeout to expire before quitting (if single shot) or waiting again
References timeout().
Referenced by start().
setSingleShot()
void CuTimer::setSingleShot (bool single)
enable or disable the single shot mode
Parameters
single true the timer is run once
single false the timer is run continuously
setTimeout()
void CuTimer::setTimeout (int millis)
change the timeout
Parameters
millis the new timeout
References pbblue.
Referenced by CuThread::run().
start()
void CuTimer::start (int millis)
start the timer with the given interval in milliseconds
Parameters
millis the desired timeout
If the timer is still running, CuTimer waits for it to finish before starting another one
References run().
Referenced by resume(), and CuThread::run().
stop()
void CuTimer::stop ()
stops the timer, if active
stops the timer, joins the timer thread and deletes it
References pbblue, and pgreen.
Referenced by ~CuTimer().
timeout()
int CuTimer::timeout () const
return the timeout in milliseconds
Returns
the timeout in milliseconds
Referenced by run().
The documentation for this class was generated from the following files:
cutimer.h
cutimer.cpp