cumbia: CuThreadsEventBridge Class Reference
CuThreadsEventBridge Class Reference
cumbia basic thread event bridge
#include <cuthreadseventbridge.h>
Public Member Functions
CuThreadsEventBridge (const CuServiceProvider *sp)
the class constructor
virtual ~CuThreadsEventBridge ()
void postEvent (CuEventI *e)
post the event to the event loop
void setCuThreadsEventBridgeListener (CuThreadsEventBridgeListener *l)
sets the CuThreadsEventBridgeListener on this event bridge
void onEvent (CuEventI *e)
invokes onEventPosted on the bridge listener
Public Member Functions inherited from CuThreadsEventBridge_I
virtual ~CuThreadsEventBridge_I ()
class destructor
Public Member Functions inherited from CuEventLoopListener
virtual ~CuEventLoopListener ()
Detailed Description
cumbia basic thread event bridge
A thread event bridge provides an interface to deliver events from a background thread to an event loop running in another thread.
This class is usually instantiated by a CuThreadsEventBridgeFactory_I threads bridge factory implementation. A CuThreadsEventBridgeFactory_I implementation is passed as argument in Cumbia::registerActivity.
If you are developing graphical applications using qt, you should consider adopting the Qt implementation in the cumbia-qtcontrols module:
QThreadsEventBridge: Qt bridge that relies on QApplication and QApplication::postEvent. This is the first choice for Qt applications. The factory that is used in Cumbia::registerActivity is QThreadsEventBridgeFactory.
Example
m_cumbia = new Cumbia();
CuData thread_token(TTT::Thread, "athread");  // CuData thread_token("thread", "athread")
Activity *a = new Activity(CuData("name", "my_activity"));
m_cumbia->registerActivity(a, this, thread_token,
                           CuThreadFactoryImpl(),
                           QThreadsEventBridgeFactory());
Constructor & Destructor Documentation
CuThreadsEventBridge()
CuThreadsEventBridge::CuThreadsEventBridge (const CuServiceProvider * sp)
the class constructor
Parameters
sp the CuServiceProvider that is used to get the event loop implementation offered by the cumbia base module
A CuEventLoopService must have been previously created and registered to the CuServiceProvider
References CuEventLoopService::addCuEventLoopListener(), CuServices::EventLoop, CuServiceProvider::get(), and perr.
~CuThreadsEventBridge()
CuThreadsEventBridge::~CuThreadsEventBridge () virtual
References cuprintf, and CuEventLoopService::removeCuEventLoopListener().
Member Function Documentation
onEvent()
void CuThreadsEventBridge::onEvent (CuEventI * e) virtual
invokes onEventPosted on the bridge listener
Parameters
e an implementation of CuEventI
The method simply calls CuThreadsEventBridgeListener::onEventPosted. For example, CuThread implements CuThreadsEventBridgeListener through CuThreadInterface, that in turn inherits from CuThreadsEventBridgeListener. CuThread::onEventPosted gets the activity that generated the event and the thread listener associated to that activity (when Cumbia::registerActivity had been called) CuThreadListener::onProgress and CuThreadListener::onResult are called. See CuThread::onEventPosted
Implements CuEventLoopListener.
References CuThreadsEventBridgeListener::onEventPosted().
postEvent()
void CuThreadsEventBridge::postEvent (CuEventI * e) virtual
post the event to the event loop
calls postEvent on the event loop service (CuEventLoopService) with this as a listener
Implements CuThreadsEventBridge_I.
References CuEventLoopService::postEvent().
setCuThreadsEventBridgeListener()
void CuThreadsEventBridge::setCuThreadsEventBridgeListener (CuThreadsEventBridgeListener * l) virtual
sets the CuThreadsEventBridgeListener on this event bridge
Parameters
l an instance of CuThreadsEventBridgeListener
Implements CuThreadsEventBridge_I.
The documentation for this class was generated from the following files:
cuthreadseventbridge.h
cuthreadseventbridge.cpp