cumbia: CuHLTimer Class Reference
CuHLTimer Class Reference
The CuHLTimer class offers a higher level interface to CuTimer.
#include <cuhltimer.h>
Public Member Functions
CuHLTimer (Cumbia *c, CuHLTimerListener *tl)
CuHLTimer (Cumbia *c)
virtual ~CuHLTimer ()
void start ()
start executing the timer after one or more listeners have been configured with addTimerListener
void stop ()
bool isRunning () const
bool addTimerListener (CuHLTimerListener *tl, unsigned int timeout)
add a timer listener and a notification period (called timeout)
void removeTimerListener (CuHLTimerListener *tl)
remove a listener from this timer
bool checkTimeout (unsigned int t) const
void onTimeout (CuTimer *t)
Detailed Description
The CuHLTimer class offers a higher level interface to CuTimer.
CuHLTimer timeouts are notified through a CuHLTimerListener Notifications carry an integer value representing the period (timeout). With this strategy, a single CuHLTimer can deliver timeouts at different periods, configured with addTimerListener.
Constructor & Destructor Documentation
CuHLTimer() [1/2]
CuHLTimer::CuHLTimer (Cumbia * c, CuHLTimerListener * tl)
CuHLTimer() [2/2]
CuHLTimer::CuHLTimer (Cumbia * c)
References c.
~CuHLTimer()
CuHLTimer::~CuHLTimer () virtual
Member Function Documentation
addTimerListener()
bool CuHLTimer::addTimerListener (CuHLTimerListener * tl, unsigned int timeout)
add a timer listener and a notification period (called timeout)
Parameters
tl a CuHLTimerListener
timeout period (>0) in milliseconds for the periodic invocation of CuHLTimerListener::onTimeout
After adding listeners with their timeouts, call CuHLTimer::start This method can be called after the timer is started.
References checkTimeout(), and CuHLTimer_P::limap.
checkTimeout()
bool CuHLTimer::checkTimeout (unsigned int t) const
References CuHLTimer_P::limap, and perr.
Referenced by addTimerListener().
isRunning()
bool CuHLTimer::isRunning () const
References CuHLTimer_P::period.
onTimeout()
void CuHLTimer::onTimeout (CuTimer * t)
References i, CuHLTimer_P::limap, CuHLTimer_P::period, CuTimerService::restart(), CuTimer::setTimeout(), CuHLTimer_P::ticks, CuTimer::timeout(), and CuHLTimer_P::tserv.
removeTimerListener()
void CuHLTimer::removeTimerListener (CuHLTimerListener * tl)
remove a listener from this timer
If the number of listeners drops to zero, the timer is stopped, and needs to be started again after adding new listeners.
References CuHLTimer_P::limap, and stop().
start()
void CuHLTimer::start ()
start executing the timer after one or more listeners have been configured with addTimerListener
In case of multiple timeouts, they are rounded up so as to be multiples of the smallest timeout. Duplicated couples (timeout, listener) are removed.
References CuHLTimer_P::cu, CuServices::EventLoop, Cumbia::getServiceProvider(), CuHLTimer_P::limap, CuHLTimer_P::period, perr, CuTimerService::registerListener(), CuServiceProvider::registerService(), CuServices::Timer, and CuHLTimer_P::tserv.
stop()
void CuHLTimer::stop ()
References CuHLTimer_P::period, CuHLTimer_P::tserv, and CuTimerService::unregisterListener().
Referenced by removeTimerListener().
The documentation for this class was generated from the following files:
cuhltimer.h
cuhltimer.cpp