cumbia: CuThread Class Reference
CuThread Class Reference
cumbia thread implementation
#include <cuthread.h>
Public Member Functions
CuThread (const CuData &token, CuThreadsEventBridge_I *threadEventsBridge, const CuServiceProvider *service_provider)
builds a new CuThread
virtual ~CuThread ()
the class destructor, deletes the thread and the event bridge
void registerActivity (CuActivity *l)
Register a new activity on this thread.
void unregisterActivity (CuActivity *l)
unregister the activity passed as argument from this thread.
void publishProgress (const CuActivity *activity, int step, int total, const CuData &data)
invoked in CuThread's thread, posts a progress event to the main thread
void publishResult (const CuActivity *activity, const CuData &data)
invoked in CuThread's thread, posts a result event to main thread
void publishResult (const CuActivity *activity, const std::vector< CuData > *data_list)
post a result event from the background thread to the main thread
void publishExitEvent (CuActivity *a)
invoked in CuThread's thread, posts an activity exit event to the main thread
bool isEquivalent (const CuData &other_thread_token) const
returns true if this thread token is equal to other_thread_token
CuData getToken () const
returns the thread token that was specified at construction time
void cleanup ()
int type () const
returns 0
void start ()
internally used, allocates a new std::thread
bool isRunning ()
returns true if the thread is running
void onTimeout (CuTimer *sender)
void wait ()
wait for the thread to exit
void exit ()
exit the thread loop gracefully
void postEvent (CuActivity *a, CuActivityEvent *e)
sends the event e to the activity a from the main thread to the background
int getActivityTimerPeriod (CuActivity *a) const
returns the period of the timer running for the given activity
void onEventPosted (CuEventI *event)
implements onEventPosted from CuThreadsEventBridgeListener interface. Invokes onProgress or onResult on the registered CuThreadListener objects.
Public Member Functions inherited from CuThreadInterface
virtual ~CuThreadInterface ()
interface virtual destructor
Public Member Functions inherited from CuThreadsEventBridgeListener
virtual ~CuThreadsEventBridgeListener ()
Protected Member Functions
virtual void run ()
Detailed Description
cumbia thread implementation
CuThread offers a C++11 thread implementation that can be used with cumbia. Threads in cumbia applications are usually instantiated and managed by the CuThreadService cumbia service. Please read the introduction to CuThreadService documentation to understand how cumbia deals with them in an application (cuthread_service).
Registering and unregistering activities
One or more activities are registered to the thread with CuThread::registerActivity. Usually, CuThread::registerActivity is not called by the clients. Clients should rely on Cumbia::registerActivity instead. The same goes for CuThread::unregisterActivity and Cumbia::unregisterActivity.
Note
CuThreads are used internally by the library. Clients should not directly deal with them. They would rather write activities.
Publishing results from the background to the foreground
CuThread::publishProgress and CuThread::publishResult, invoked in CuThread's thread, post a progress event and a result event to the main thread, respectively. They are called by clients through CuActivity::publishProgress and CuActivity::publishResult, normally from the init, execute and onExit hooks (see CuActivity documentation)
Thread management
The CuThread::isEquivalent method decides whether this thread's token is equivalent to another token. If so, Cumbia assigns a new activity to this thread, otherwise a new thread is created for the new activity (see also Cumbia::registerActivity, cuthread_service and CuThreadService::getThread). The thread token can be obtained by CuThread::getToken. A token is assigned in the CuThread constructor and cannot be changed later. The CuThread::start method instantiates a new C++11 std::thread. To gracefully terminate a CuThread, CuThread::exit must be called, followed by CuThread::wait, as done inside Cumbia::finish method.
Thread disposal
When the last activity exits (there are no more activities registered with this thread), the thread leaves its run loop, joins and auto destroys itself.
See also
Please read the documentation of the CuThreadInterface for more details.
Constructor & Destructor Documentation
CuThread()
CuThread::CuThread (const CuData & token, CuThreadsEventBridge_I * teb, const CuServiceProvider * serviceProvider)
builds a new CuThread
Parameters
thread_token the token associated to the thread
eventsBridge a CuThreadsEventBridge_I implementation, for example CuThreadsEventBridge (see CuThreadsEventBridgeFactory::createEventBridge) or QThreadsEventBridge, recommended for Qt applications (see QThreadsEventBridgeFactory::createEventBridge)
service_provider the CuServiceProvider of the application
Thread token
The thread token is used as an id for the thread. When Cumbia::registerActivity is called, the thread token passed as argument is compared to all tokens of all the running CuThreadInterface threads. If two tokens match, the thread with that token is reused for the new activity, otherwise a new thread is dedicated to run the new activity.
~CuThread()
CuThread::~CuThread () virtual
the class destructor, deletes the thread and the event bridge
The CuThread destructor deletes the thread (std::thread) and the event bridge
References perr, and predtmp.
Member Function Documentation
cleanup()
void CuThread::cleanup () virtual
does nothing
Implements CuThreadInterface.
exit()
void CuThread::exit () virtual
exit the thread loop gracefully
an ExitThreadEvent is queued to the event queue to exit the thread
Implements CuThreadInterface.
getActivityTimerPeriod()
int CuThread::getActivityTimerPeriod (CuActivity * a) const virtual
returns the period of the timer running for the given activity
Parameters
a the CuActivity which timer period you want to get
Returns
milliseconds of the timer running for that activity or -1 if no timer is associated to the given activity
Implements CuThreadInterface.
References pbblue.
getToken()
CuData CuThread::getToken () const
returns the thread token that was specified at construction time
Returns
the CuData specified in the class constructor at creation time
See also
CuThread::CuThread
isEquivalent()
bool CuThread::isEquivalent (const CuData & other_thread_token) const virtual
returns true if this thread token is equal to other_thread_token
Parameters
other_thread_token a CuData that's the token of another thread
Returns
true if this thread was created with a token that equals other_thread_token, false otherwise.
Note
The CuData::operator== is used to perform the comparison between the tokens
Usage
CuThreadService::getThread calls this method to decide wheter to reuse the current thread (if the tokens are equivalent) or create a new one to run a new activity (if this method returns false).
When Cumbia::registerActivity is used to execute a new activity, the thread token passed as input argument is relevant to decide whether the new registered activity must be run in a running thread (if one is found with the same token) or in a new one (no threads found with the token given to CuActivity::registerActivity).
See also getToken
Implements CuThreadInterface.
isRunning()
bool CuThread::isRunning () virtual
returns true if the thread is running
Returns
true if the thread is running
Implements CuThreadInterface.
onEventPosted()
void CuThread::onEventPosted (CuEventI * event) virtual
implements onEventPosted from CuThreadsEventBridgeListener interface. Invokes onProgress or onResult on the registered CuThreadListener objects.
This method gets a reference to a CuActivityManager through the service provider.
if either a CuEventI::Result or CuEventI::Progress is received, then the addressed CuActivity is extracted by the CuResultEvent and the list of CuThreadListener objects is obtained through CuActivityManager::getThreadListeners. At last either CuThreadListener::onProgress or CuThreadListener::onResult is called.
if CuEventI::CuActivityExitEvent event type is received, CuThread becomes aware that a CuActivity has finished, and deletes it if its CuActivity::CuADeleteOnExit flag is set to true.
note
The association between activities, threads and CuThreadListener objects is defined by Cumbia::registerActivity. Please read Cumbia::registerActivity documentation for more details.
Implements CuThreadInterface.
References CuServices::ActivityManager, CuEventI::CuActivityExitEvent, cuprintf, CuResultEvent::getActivity(), CuResultEvent::getData(), CuResultEvent::getDataList(), CuResultEvent::getStep(), CuActivityManager::getThreadListeners(), CuResultEvent::getTotal(), CuEventI::getType(), CuActivityManager::getType(), CuResultEvent::getType(), CuResultEvent::isList(), CuThreadListener::onProgress(), CuThreadListener::onResult(), pbblue, CuEventI::Progress, CuEventI::Result, CuEventI::ThreadAutoDestroy, and wait().
onTimeout()
void CuThread::onTimeout (CuTimer * sender)
postEvent()
void CuThread::postEvent (CuActivity * a, CuActivityEvent * e) virtual
sends the event e to the activity a from the main thread to the background
Note
This method is used to send an event from the main thread to the background Events from the background are posted to the main thread through the thread event bridge (CuThreadsEventBridge_I)
Parameters
a the CuActivity that sends the event
e the CuActivityEvent
Examples
Cumbia calls CuThread::postEvent several times:
Cumbia::setActivityPeriod sends a CuTimeoutChangeEvent event
Cumbia::pauseActivity sends a CuPauseEvent
Cumbia::resumeActivity sends a CuResumeEvent
Cumbia::postEvent barely forwards a user defined CuActivityEvent to the specified activity
There can be situations where clients can call the above listed Cumbia methods. On the other hand, CuThread::postEvent is not normally intended for direct use by clients of this library.
Implements CuThreadInterface.
publishExitEvent()
void CuThread::publishExitEvent (CuActivity * a) virtual
invoked in CuThread's thread, posts an activity exit event to the main thread
Note
used internally
Called from CuActivity::doOnExit (background thread), delivers an exit event to the main thread from the background, using CuThreadsEventBridge_I::postEvent with a CuActivityExitEvent as parameter. When the event is received and processed back in the main thread (in CuThread::onEventPosted) the activity is deleted if the CuActivity::CuADeleteOnExit flag is enabled.
Implements CuThreadInterface.
References pbblue.
publishProgress()
void CuThread::publishProgress (const CuActivity * activity, int step, int total, const CuData & data) virtual
invoked in CuThread's thread, posts a progress event to the main thread
Parameters
activity the addressee of the event
step the current step of the progress
total the total number of steps making up the whole work
data the data to be delivered with the progress event
CuResultEvent is used in conjunction with CuThreadsEventBridge_I::postEvent
Implements CuThreadInterface.
publishResult() [1/2]
void CuThread::publishResult (const CuActivity * a, const CuData & da) virtual
invoked in CuThread's thread, posts a result event to main thread
Parameters
a the addressee of the event
data the data to be delivered with the result
CuResultEvent is used in conjunction with CuThreadsEventBridge_I::postEvent
Implements CuThreadInterface.
publishResult() [2/2]
void CuThread::publishResult (const CuActivity * activity, const std::vector< CuData > * data_list) virtual
post a result event from the background thread to the main thread
This lets you send events to the main thread that account for a list of results computed in the background
See CuThread::publishProgress for details
Implements CuThreadInterface.
registerActivity()
void CuThread::registerActivity (CuActivity * l) virtual
Register a new activity on this thread.
This is invoked from the main thread. As soon as registerActivity is called, a RegisterActivityEvent is added to the thread event queue and the CuActivity will be soon initialised and executed in the background. (CuActivity::init and CuActivity::execute)
Parameters
l a CuActivity that is the worker, whose methods are invoked in this background thread.
Implements CuThreadInterface.
run()
void CuThread::run () protected virtual
Thread loop
References CuActivityManager::activitiesForThread(), CuServices::ActivityManager, CuActivity::CuAUnregisterAfterExec, CuActivity::event(), CuActivityEvent::getType(), CuActivityEvent::Pause, CuTimer::pause(), pbgreen, pbred2, CuActivityManager::removeConnections(), CuActivityEvent::Resume, CuTimer::resume(), CuTimer::setTimeout(), CuActivityEvent::TimeoutChange, and unregisterActivity().
Referenced by start().
start()
void CuThread::start () virtual
internally used, allocates a new std::thread
Note
used internally
return a new instance of std::thread
Implements CuThreadInterface.
References run().
type()
int CuThread::type () const virtual
returns 0
Returns
0
Implements CuThreadInterface.
unregisterActivity()
void CuThread::unregisterActivity (CuActivity * l) virtual
unregister the activity passed as argument from this thread.
Parameters
l the CuActivity to unregister from this thread.
An UnRegisterActivityEvent is queued to the thread event queue. When processed, CuActivity::doOnExit is called which in turn calls CuActivity::onExit (in the CuActivity background thread). If the flag CuActivity::CuADeleteOnExit is true, the activity is later deleted (back in the main thread)
Called from
This method is called from the CuThread's thread only if CuActivity::CuAUnregisterAfterExec is set on the activity. Otherwise, activities must be unregistered through Cumbia::unregisterActivity (in that case, invocation occurs from the main thread).
Implements CuThreadInterface.
References pbblue.
Referenced by run().
wait()
void CuThread::wait () virtual
wait for the thread to exit
call join on the thread
Implements CuThreadInterface.
References pbviolet.
Referenced by onEventPosted().
The documentation for this class was generated from the following files:
cuthread.h
cuthread.cpp