cumbia: CuData Class Reference
CuData Class Reference
container for data exchange for the cumbia library and its clients
#include <cudata.h>
Public Member Functions
virtual ~CuData ()
the class destructor
CuData ()
constructor of an empty CuData
CuData (const CuVariant &v)
constructor of a CuData initialised with one value (key: emtpy string)
CuData (const size_t key, const CuVariant &v)
CuData (const std::string &key, const CuVariant &v)
constructor initialising a CuData with one key-value pair
CuData (const CuData &other)
the copy constructor
CuData (CuData &&other)
c++11 move constructor
virtual CuData & operator= (const CuData &other)
assignment operator, copies data from another source
virtual CuData & operator= (CuData &&other)
move assignment operator, moves contents from another source
CuData & set (const TTT::Key &key, const CuVariant &value)
CuData & set (const std::string &key, const CuVariant &value)
CuData & merge (const CuData &other)
CuData & merge (const CuData &&other)
merge other data into this data, moving contents from other
CuData clone () const
clone this data, without sharing
CuData & remove (const std::string &key)
CuData & remove (const TTT::Key &key)
CuData remove (const TTT::Key &key) const
CuData remove (const std::string &key) const
CuData & remove (const std::vector< std::string > &keys)
CuData & remove (const std::vector< size_t > &keys)
CuData remove (const std::vector< size_t > &keys) const
CuData remove (const std::vector< std::string > &keys) const
size_t size () const
returns the number of key-value pairs stored
CuVariant value () const
return the value associated to the empty key
CuVariant value (const std::string &key) const
return a copy of the value associated with the given key, or an invalid and null CuVariant
CuVariant value (const TTT::Key &key) const
void add (const TTT::Key &key, const CuVariant &value)
void add (const std::string &key, const CuVariant &value)
insert the key/value into the bundle
bool containsKey (const std::string &key) const
returns true if the bundle contains the given key
bool containsKey (const TTT::Key &key) const
bool has (const TTT::Key &key, const std::string &value) const
bool has (const std::string &key, const std::string &value) const
returns true if the specified key has the given string value
CuVariant & operator[] (const TTT::Key &key)
const CuVariant & operator[] (const TTT::Key &key) const
CuData::operator [] with index.
CuVariant & operator[] (const std::string &key)
array subscript write operator; pushes a new key-value pair into the bundle
const CuVariant & operator[] (const std::string &key) const
array subscript read operator: get a reference to a value given the key
virtual bool operator== (const CuData &other) const
equality relational operator. Returns true if this CuData equals another
virtual bool operator!= (const CuData &other) const
inequality relational operator. Returns true if the equality operator CuData::operator == returns false
bool isEmpty () const
returns true if there are no key-value pairs stored
void print () const
prints the representation of the object provided by toString using printf
std::string toString (bool color=true) const
write a representation of this object into a std::string
void putTimestamp ()
put date and time information into this object
std::vector< std::string > keys () const
std::vector< size_t > idx_keys () const
std::string s (const TTT::Key &key) const
std::string s (const std::string &key) const
const char * c_str (const TTT::Key &key) const
interprets and returns the value stored at position key into a const char pointer
const char * c_str (const std::string &key) const
interprets and returns the value stored at position key into a const char pointer
double d (const TTT::Key &key) const
double d (const std::string &key) const
int i (const TTT::Key &key) const
int i (const std::string &key) const
unsigned int u (const TTT::Key &key) const
unsigned int u (const std::string &key) const
bool b (const TTT::Key &key) const
bool b (const std::string &key) const
double D (const TTT::Key &key) const
double D (const std::string &key) const
int I (const TTT::Key &key) const
int I (const std::string &key) const
unsigned int U (const TTT::Key &key) const
unsigned int U (const std::string &key) const
bool B (const TTT::Key &key) const
bool B (const std::string &key) const
std::vector< double > DV (const TTT::Key &key) const
std::vector< double > DV (const std::string &key) const
std::vector< int > IV (const TTT::Key &key) const
std::vector< int > IV (const std::string &key) const
std::vector< long long > LLV (const TTT::Key &key) const
std::vector< long long > LLV (const std::string &key) const
std::vector< unsigned int > UV (const TTT::Key &key) const
std::vector< unsigned int > UV (const std::string &key) const
std::vector< unsigned long int > ULV (const TTT::Key &key) const
std::vector< unsigned long int > ULV (const std::string &key) const
std::vector< unsigned long long int > ULLV (const TTT::Key &key) const
std::vector< unsigned long long int > ULLV (const std::string &key) const
std::vector< bool > BV (const TTT::Key &key) const
std::vector< bool > BV (const std::string &key) const
Detailed Description
container for data exchange for the cumbia library and its clients
CuData is a bundle that stores key-value pairs. The key is a std::string, the value is of type CuVariant. A copy of the value associated to a key can be obtained with CuData::value(const std::string& key). A value can be accessed with the [] operator. [] operators are defined in the const and non const flavours. The non const version allows to insert new CuVariant values with a string key within the square brackets.
The parameterless CuData::value version returns the value associated to an empty key, if there is one, created for example with the CuData::CuData(const CuVariant &v) constructor.
The number of key-value pairs stored by CuData can be queried with CuData::size. CuData::isEmpty returns true if the CuData has no key/value pair. CuData::containsKey tells whether a given key is or not in the bundle. CuData::add can be used to add a key-value pair. The result is equivalent to using the [] operator.
Two CuData can be compared with the == and != operators. The == operator returns true if the two bundles contain the same keys and each of their values correspond. The operator != returns the opposite value of the operator ==
The CuData::toString method returns a std::string representation of its contents. The contents of a CuData can be printed on the console by means of CuData::print
The CuVariant variant type
Please read the CuVariant documentation to understand the cumbia CuVariant type.
Implicit sharing
Since
1.4.0
Data is implicitly shared, enabling copy on write. Atomic reference counters make the class reentrant, meaning that methods can be called from multiple threads, but only if each invocation uses its own data. Atomic reference counting is used to ensure the integrity of the shared data. Since cumbia 1.4.0, CuData uses implicit sharing as well.
Constructor & Destructor Documentation
~CuData()
CuData::~CuData () virtual
the class destructor
CuData class destructor
CuData() [1/6]
CuData::CuData ()
constructor of an empty CuData
builds a CuData with no key/value
Referenced by remove(), remove(), remove(), and remove().
CuData() [2/6]
CuData::CuData (const CuVariant & v)
constructor of a CuData initialised with one value (key: emtpy string)
Parameters
v a CuVariant used to initialise a key/value pair where the key is an empty string.
The parameter-less of CuData::value can be used to get the value associated to an empty key
CuData() [3/6]
CuData::CuData (const size_t key, const CuVariant & v)
CuData() [4/6]
CuData::CuData (const std::string & key, const CuVariant & v)
constructor initialising a CuData with one key-value pair
Parameters
key a string used as a key
v the value, as CuVariant
The new CuData will be initialised with a key/v pair
CuData() [5/6]
CuData::CuData (const CuData & other)
the copy constructor
Parameters
other another CuData used as the source of the copy
copies all the contents from the other CuData into the new object
CuData() [6/6]
CuData::CuData (CuData && other)
c++11 move constructor
Parameters
other another CuData used as the source of the move operation
Contents of other are moved into this CuData
Member Function Documentation
add() [1/2]
void CuData::add (const std::string & key, const CuVariant & value)
insert the key/value into the bundle
Parameters
key the new key, as a std::string
value the new value bound to key
Note
The effect is exactly the same as using the operator [] (const std::string& key)
References value().
add() [2/2]
void CuData::add (const TTT::Key & key, const CuVariant & value)
References value().
Referenced by putTimestamp().
B() [1/2]
bool CuData::B (const std::string & key) const
References b(), containsKey(), operator[](), and CuVariant::to().
B() [2/2]
bool CuData::B (const TTT::Key & key) const
References b(), and CuVariant::to().
Referenced by CuDataSerializer::serialize().
b() [1/2]
bool CuData::b (const std::string & key) const
References containsKey(), CuVariant::d(), and operator[]().
b() [2/2]
bool CuData::b (const TTT::Key & key) const
References CuVariant::b(), and CuVariant::isValid().
Referenced by B(), and B().
BV() [1/2]
std::vector< bool > CuData::BV (const std::string & key) const
References containsKey(), operator[](), and CuVariant::toVector().
BV() [2/2]
std::vector< bool > CuData::BV (const TTT::Key & key) const
References CuVariant::toVector().
c_str() [1/2]
const char * CuData::c_str (const std::string & key) const
interprets and returns the value stored at position key into a const char pointer
Parameters
key,the key as string
Returns
const char * (plain C string)
See also
c_str(const TTT::Key &key)
References CuVariant::c_str(), and operator[]().
c_str() [2/2]
const char * CuData::c_str (const TTT::Key & key) const
interprets and returns the value stored at position key into a const char pointer
Parameters
key the key
Returns
a const char pointer to the C string stored at position key or nullptr if the corresponding value at position key is invalid
This method, introduced in v2.0, provides the fastest conversion possible for strings, and does not perform any check on the internal data type other than non null.
Note
call this conversion method only when absolutely sure that the native type stored is a scalar string. Call CuData::s or CuData::toString() otherwise.
Alyays check for non null return value before operating on the returned char pointer
See also
s
toString
References CuVariant::c_str().
Referenced by print(), and CuDataSerializer::serialize().
clone()
CuData CuData::clone () const
clone this data, without sharing
Returns
a clone of this data, bypassing the copy-on-write share
References d().
containsKey() [1/2]
bool CuData::containsKey (const std::string & key) const
returns true if the bundle contains the given key
Parameters
key the key to be searched, std::string
Returns
true if the bundle contains the given key, false otherwise
Referenced by B(), b(), BV(), D(), DV(), I(), IV(), LLV(), CuDataSerializer::serialize(), U(), ULLV(), ULV(), and UV().
containsKey() [2/2]
bool CuData::containsKey (const TTT::Key & key) const
References CuVariant::isValid().
D() [1/2]
double CuData::D (const std::string & key) const
References containsKey(), operator[](), and CuVariant::to().
D() [2/2]
double CuData::D (const TTT::Key & key) const
References CuVariant::to().
d() [1/2]
double CuData::d (const std::string & key) const
References CuVariant::d(), and operator[]().
d() [2/2]
double CuData::d (const TTT::Key & key) const
References CuVariant::d().
Referenced by clone().
DV() [1/2]
std::vector< double > CuData::DV (const std::string & key) const
References containsKey(), operator[](), and CuVariant::toVector().
DV() [2/2]
std::vector< double > CuData::DV (const TTT::Key & key) const
References CuVariant::toVector().
has() [1/2]
bool CuData::has (const std::string & key, const std::string & value) const
returns true if the specified key has the given string value
This method is a shortcut to test if to a given key is associated a string with the given value.
Parameters
key the key
value the value as string
Returns
true if data[key].toString() == value false otherwise
References value().
has() [2/2]
bool CuData::has (const TTT::Key & key, const std::string & value) const
References CuVariant::isValid(), CuVariant::s(), and value().
I() [1/2]
int CuData::I (const std::string & key) const
References containsKey(), i, operator[](), and CuVariant::to().
I() [2/2]
int CuData::I (const TTT::Key & key) const
References i, and CuVariant::to().
i() [1/2]
int CuData::i (const std::string & key) const
References CuVariant::i(), and operator[]().
i() [2/2]
int CuData::i (const TTT::Key & key) const
References CuVariant::i().
idx_keys()
std::vector< size_t > CuData::idx_keys () const
References i, and CuVariant::isValid().
isEmpty()
bool CuData::isEmpty () const
returns true if there are no key-value pairs stored
Returns
true there is no data stored, false if there is at least one key-value pair
See also
size
References i, and CuVariant::isValid().
IV() [1/2]
std::vector< int > CuData::IV (const std::string & key) const
References containsKey(), operator[](), and CuVariant::toVector().
IV() [2/2]
std::vector< int > CuData::IV (const TTT::Key & key) const
References CuVariant::toVector().
keys()
std::vector< std::string > CuData::keys () const
Referenced by merge(), remove(), remove(), remove(), and remove().
LLV() [1/2]
std::vector< long long > CuData::LLV (const std::string & key) const
References containsKey(), operator[](), and CuVariant::toVector().
LLV() [2/2]
std::vector< long long > CuData::LLV (const TTT::Key & key) const
References CuVariant::toVector().
merge() [1/2]
CuData & CuData::merge (const CuData && other)
merge other data into this data, moving contents from other
Parameters
other another CuData whose contents will be merged into this data with a move operation
Returns
this CuData with values merged with other CuData
Note
the other CuData contents are moved into this data.
References i, and CuVariant::isValid().
merge() [2/2]
CuData & CuData::merge (const CuData & other)
References keys(), and value().
operator!=()
bool CuData::operator!= (const CuData & other) const virtual
inequality relational operator. Returns true if the equality operator CuData::operator == returns false
Returns
true if the equality operator CuData::operator== returns false, false otherwise
References operator==().
operator=() [1/2]
CuData & CuData::operator= (const CuData & other) virtual
assignment operator, copies data from another source
Parameters
other another CuData which values will be copied into this
operator=() [2/2]
CuData & CuData::operator= (CuData && other) virtual
move assignment operator, moves contents from another source
Parameters
other another CuData which values will be moved into this
operator==()
bool CuData::operator== (const CuData & other) const virtual
equality relational operator. Returns true if this CuData equals another
Parameters
other another CuData (const reference)
Returns
true if other contains the same keys as this and every key of other has the same value as the corresponding key in this
the inequality operator is also defined
References CuVariant::data(), and i.
Referenced by operator!=().
operator[]() [1/4]
CuVariant & CuData::operator[] (const std::string & key)
array subscript write operator; pushes a new key-value pair into the bundle
Use the insert operator to add a new key/value pair to the bundle
Example
CuData at("src", source.getName()); // string
at["device"] = source.getDeviceName(); // string
at["activity"] = "E"; // string
at["period"] = source.period(); // integer
at["err"] = false; // bool
operator[]() [2/4]
const CuVariant & CuData::operator[] (const std::string & key) const
array subscript read operator: get a reference to a value given the key
Parameters
key the key to search for
Returns
reference to the value for the given key or a reference to an empty CuVariant if the key is not found.
Note
An empty CuVariant::isValid method returns false and CuVariant::isNull returns true
operator[]() [3/4]
CuVariant & CuData::operator[] (const TTT::Key & key)
Referenced by B(), b(), BV(), c_str(), D(), d(), DV(), I(), i(), IV(), LLV(), s(), U(), u(), ULLV(), ULV(), and UV().
operator[]() [4/4]
const CuVariant & CuData::operator[] (const TTT::Key & key) const
CuData::operator [] with index.
Parameters
key index
Returns
the CuVariant at the index position
print()
void CuData::print () const
prints the representation of the object provided by toString using printf
Prints a string representation of the contents of this object on the console, using printf.
See also
toString
References c_str(), and toString().
putTimestamp()
void CuData::putTimestamp ()
put date and time information into this object
writes the following keys into this object, taking the system clock time from the gettimeofday call.
"timestamp_ms" timestamp in milliseconds, convert with CuVariant::toLongInt
"timestamp_us" timestamp in microseconds, convert with CuVariant::toLongInt
References add().
remove() [1/8]
CuData & CuData::remove (const std::string & key)
Referenced by remove(), remove(), remove(), and remove().
remove() [2/8]
CuData CuData::remove (const std::string & key) const
References CuData(), and remove().
remove() [3/8]
CuData & CuData::remove (const std::vector< size_t > & keys)
References keys().
remove() [4/8]
CuData CuData::remove (const std::vector< size_t > & keys) const
References CuData(), keys(), and remove().
remove() [5/8]
CuData & CuData::remove (const std::vector< std::string > & keys)
References keys().
remove() [6/8]
CuData CuData::remove (const std::vector< std::string > & keys) const
References CuData(), keys(), and remove().
remove() [7/8]
CuData & CuData::remove (const TTT::Key & key)
remove() [8/8]
CuData CuData::remove (const TTT::Key & key) const
References CuData(), and remove().
s() [1/2]
std::string CuData::s (const std::string & key) const
References operator[](), and CuVariant::s().
s() [2/2]
std::string CuData::s (const TTT::Key & key) const
References CuVariant::s().
Referenced by CuDataSerializer::deserialize(), and size().
set() [1/2]
CuData & CuData::set (const std::string & key, const CuVariant & value)
References value().
set() [2/2]
CuData & CuData::set (const TTT::Key & key, const CuVariant & value)
References value().
Referenced by CuDataSerializer::deserialize().
size()
size_t CuData::size () const
returns the number of key-value pairs stored
Returns
the number of key-value pairs stored within this object
See also
isEmpty
References i, CuVariant::isValid(), and s().
toString()
std::string CuData::toString (bool color = true) const
write a representation of this object into a std::string
Returns
a std::string with a representation of this object.
All keys are printed with their values (CuVariant is always converted to string with CuVariant::toString). At last, the number of key/values stored and the flag returned by CuData::isEmpty are printed.
See also
print
References CuVariant::data_type_short_str(), i, CuVariant::isValid(), CuXDTypeUtils::keyName(), and CuVariant::toString().
Referenced by print().
U() [1/2]
unsigned int CuData::U (const std::string & key) const
References containsKey(), i, operator[](), and CuVariant::to().
U() [2/2]
unsigned int CuData::U (const TTT::Key & key) const
References CuVariant::to().
u() [1/2]
unsigned int CuData::u (const std::string & key) const
References operator[](), and CuVariant::u().
u() [2/2]
unsigned int CuData::u (const TTT::Key & key) const
References CuVariant::u().
ULLV() [1/2]
std::vector< unsigned long long > CuData::ULLV (const std::string & key) const
References containsKey(), operator[](), and CuVariant::toVector().
ULLV() [2/2]
std::vector< unsigned long long > CuData::ULLV (const TTT::Key & key) const
References CuVariant::toVector().
ULV() [1/2]
std::vector< unsigned long > CuData::ULV (const std::string & key) const
References containsKey(), operator[](), and CuVariant::toVector().
ULV() [2/2]
std::vector< unsigned long > CuData::ULV (const TTT::Key & key) const
References CuVariant::toVector().
UV() [1/2]
std::vector< unsigned int > CuData::UV (const std::string & key) const
References containsKey(), operator[](), and CuVariant::toVector().
UV() [2/2]
std::vector< unsigned int > CuData::UV (const TTT::Key & key) const
References CuVariant::toVector().
value() [1/3]
CuVariant CuData::value () const
return the value associated to the empty key
Returns
the value associated to an empty key, if there's one empty key with a value (for example, created with the CuData::CuData(const CuVariant &v)) constructor, or an empty CuVariant
If there's no value associated to an empty key (i.e. an emtpy string, ""), an invalid and null CuVariant is returned. See CuVariant::isValid and CuVariant::isNull
Referenced by add(), add(), has(), has(), merge(), set(), and set().
value() [2/3]
CuVariant CuData::value (const std::string & key) const
return a copy of the value associated with the given key, or an invalid and null CuVariant
Returns
a copy of the value associated with the given key, or an invalid and null CuVariant. See CuVariant::isValid and CuVariant::isNull
See also CuData::operator [](const std::string &key) const
value() [3/3]
CuVariant CuData::value (const TTT::Key & key) const
The documentation for this class was generated from the following files:
cudata.h
cudata.cpp