cumbia: CuEventLoopService Class Reference
CuEventLoopService Class Reference
service that implements a simple event loop for cumbia applications.
#include <cueventloop.h>
Public Member Functions
CuEventLoopService (CuEventLoopListener *l=NULL)
virtual ~CuEventLoopService ()
the class destructor
void exec (bool threaded)
executes the event loop
void postEvent (CuEventI *e)
post an event to the internal thread event queue
void setCuEventLoopListener (CuEventLoopListener *l)
set the CuEventLoopListener that will receive events from this service
void exit ()
exit the event loop cleanly
void wait ()
wait for the secondary thread to leave the event loop
std::string getName () const
return the name of the service
CuServices::Type getType () const
return the type of the service
Public Member Functions inherited from CuServiceI
virtual ~CuServiceI ()
Protected Member Functions
virtual void run ()
run the event loop waiting for events on a queue
Detailed Description
service that implements a simple event loop for cumbia applications.
CuEventLoopService is a cumbia service (CuServiceI) that offers a simple event loop for an application. Please note that if you are developing a Qt application you should employ Qt's QApplication event loop (read CuThreadsEventBridge and Cumbia::registerActivity documentation).
See also the CuServiceProvider documentation.
Constructor & Destructor Documentation
CuEventLoopService()
CuEventLoopService::CuEventLoopService (CuEventLoopListener * l = NULL)
The class constructor
Parameters
l a CuEventLoopListener
~CuEventLoopService()
CuEventLoopService::~CuEventLoopService () virtual
the class destructor
Note
CuEventLoopService must not be destroyed while its thread is still running. Instead, CuEventLoopService::exit and CuEventLoopService::wait must be called.
References perr.
Member Function Documentation
exec()
void CuEventLoopService::exec (bool threaded)
executes the event loop
Parameters
threaded true if the CuEventLoopService::run method has to be run in a separate thread, false if CuEventLoopService::run has to be run in the caller's same thread.
References pblue, perr, pr_thread, and run().
exit()
void CuEventLoopService::exit ()
exit the event loop cleanly
an appropriate event is queued to the event queue of the event loop service. As soon as it is received, the event loop exits.
Note
call CuEventLoop::wait to wait for the secondary thread (if CuEventLoopService::exec was called with a true parameter) to leave the event loop
getName()
std::string CuEventLoopService::getName () const virtual
return the name of the service
Returns
a std::string with the name of the service
Implements CuServiceI.
getType()
CuServices::Type CuEventLoopService::getType () const virtual
return the type of the service
Returns
a CuServices::Type defining the type of service
Implements CuServiceI.
References CuServices::EventLoop.
postEvent()
void CuEventLoopService::postEvent (CuEventI * e)
post an event to the internal thread event queue
This class is used internally.
Parameters
e the event to be delivered
Referenced by CuThreadsEventBridge::postEvent().
run()
void CuEventLoopService::run () protected virtual
run the event loop waiting for events on a queue
Runs the event loop in the same caller's thread or in a background one, according to how CuEventLoopService::exec was called
References cuprintf, CuEventI::ExitLoop, and pblue.
Referenced by exec().
setCuEventLoopListener()
void CuEventLoopService::setCuEventLoopListener (CuEventLoopListener * l)
set the CuEventLoopListener that will receive events from this service
Parameters
l a CuEventLoopListener that will receive events from the event loop
Referenced by CuThreadsEventBridge::CuThreadsEventBridge().
wait()
void CuEventLoopService::wait ()
wait for the secondary thread to leave the event loop
Wait for the secondary thread to leave the event loop (if CuEventLoopService::exec was called with a true parameter)
References pbgreen2.
The documentation for this class was generated from the following files:
cueventloop.h
cueventloop.cpp