cumbia: CuThreadsEventBridge_I Class Reference
CuThreadsEventBridge_I Class Reference abstract
interface to a threads event bridge
#include <cuthreadseventbridge_i.h>
Public Member Functions
virtual ~CuThreadsEventBridge_I ()
class destructor
virtual void postEvent (CuEventI *e)=0
bridge's method to forward an event from the background thread to the main thread.
virtual void setCuThreadsEventBridgeListener (CuThreadsEventBridgeListener *l)=0
set a CuThreadsEventBridgeListener for this CuThreadsEventBridge_I
Detailed Description
interface to a threads event bridge
This interface defines two methods that must be implemented by a threads event bridge:
postEvent, used to deliver an event from a background thread to the application event loop
setCuThreadsEventBridgeListener: set the CuThreadsEventBridgeListener on the CuThreadsEventBridge_I
CuThreadsEventBridgeListener
This interface is implemented by the CuThreadInterface and then CuThread. CuThread::onEventPosted receives the event in the main thread and calls CuThreadListener::onProgress or CuThreadListener::onResult on the thread listeners associated to the activity that generated the event. Remember that Cumbia::registerActivity associates an activity (CuActivity) to a thread listener (CuThreadListener).
Constructor & Destructor Documentation
~CuThreadsEventBridge_I()
virtual CuThreadsEventBridge_I::~CuThreadsEventBridge_I () inline virtual
class destructor
virtual class destructor
References pdelete.
Member Function Documentation
postEvent()
virtual void CuThreadsEventBridge_I::postEvent (CuEventI * e) pure virtual
bridge's method to forward an event from the background thread to the main thread.
A thread event bridge provides an interface to deliver events from a background thread to an event loop running in another thread.
Example implementations:
CuThreadsEventBridge
QThreadsEventBridge (cumbia-qtcontrols module, used for Qt applications)
Implemented in CuThreadsEventBridge.
Referenced by CuThread::publishProgress(), CuThread::publishResult(), CuThread::publishResult(), CuThread::publishResult(), and CuThread::run().
setCuThreadsEventBridgeListener()
virtual void CuThreadsEventBridge_I::setCuThreadsEventBridgeListener (CuThreadsEventBridgeListener * l) pure virtual
set a CuThreadsEventBridgeListener for this CuThreadsEventBridge_I
Parameters
l a CuThreadsEventBridgeListener
CuThreadsEventBridgeListener
CuThreadInterface is a CuThreadsEventBridgeListener CuThread is a CuThreadInterface and so it is also a CuThreadsEventBridgeListener
Please read CuThread::onEventPosted for more details
Implemented in CuThreadsEventBridge.
Referenced by CuThread::CuThread().
The documentation for this class was generated from the following file:
cuthreadseventbridge_i.h