cumbia: CuMatrix< T > Class Template Reference
CuMatrix< T > Class Template Reference
#include <cumatrix.h>
Public Member Functions
CuMatrix (const std::vector< T > &v, size_t dimx, size_t dimy)
CuMatrix (T *v, size_t dimx, size_t dimy)
CuMatrix (const T *v, size_t dimx, size_t dimy)
Matrix constructor accepting pointer and sizes. const version.
CuMatrix (const CuMatrix< T > &other)
CuMatrix (CuMatrix< T > &&other)
CuMatrix ()
~CuMatrix ()
T * operator[] (size_t idx)
const T * operator[] (size_t idx) const
bool operator== (const CuMatrix< T > &other) const
CuMatrix< T > & operator= (const CuMatrix< T > &other)
bool operator!= (const CuMatrix< T > &other) const
CuMatrix * clone () const
std::vector< T > data () const
T * raw_data () const
size_t size () const
size_t nrows () const
size_t ncols () const
bool isValid () const
std::string repr_str (size_t maxlen=-1) const
repr return a string representation of the matrix
std::string repr (size_t maxlen=-1) const
Static Public Member Functions
static CuMatrix * from_string_matrix (const CuMatrix< std::string > &from)
Constructor & Destructor Documentation
CuMatrix() [1/6]
template<typename T > CuMatrix< T >::CuMatrix (const std::vector< T > & v, size_t dimx, size_t dimy) inline
CuMatrix() [2/6]
template<typename T > CuMatrix< T >::CuMatrix (T * v, size_t dimx, size_t dimy) inline
CuMatrix() [3/6]
template<typename T > CuMatrix< T >::CuMatrix (const T * v, size_t dimx, size_t dimy) inline
Matrix constructor accepting pointer and sizes. const version.
CuMatrix() [4/6]
template<typename T > CuMatrix< T >::CuMatrix (const CuMatrix< T > & other) inline
CuMatrix() [5/6]
template<typename T > CuMatrix< T >::CuMatrix (CuMatrix< T > && other) inline
CuMatrix() [6/6]
template<typename T > CuMatrix< T >::CuMatrix () inline
Referenced by CuMatrix< T >::clone(), and CuMatrix< T >::from_string_matrix().
~CuMatrix()
template<typename T > CuMatrix< T >::~CuMatrix () inline
Member Function Documentation
clone()
template<typename T > CuMatrix * CuMatrix< T >::clone () const inline
References CuMatrix< T >::CuMatrix().
data()
template<typename T > std::vector< T > CuMatrix< T >::data () const inline
Referenced by CuMatrix< T >::from_string_matrix().
from_string_matrix()
template<typename T > static CuMatrix * CuMatrix< T >::from_string_matrix (const CuMatrix< std::string > & from) inline static
References CuMatrix< T >::CuMatrix(), CuMatrix< T >::data(), CuMatrix< T >::ncols(), and CuMatrix< T >::nrows().
isValid()
template<typename T > bool CuMatrix< T >::isValid () const inline
ncols()
template<typename T > size_t CuMatrix< T >::ncols () const inline
Referenced by CuMatrix< T >::from_string_matrix().
nrows()
template<typename T > size_t CuMatrix< T >::nrows () const inline
Referenced by CuMatrix< T >::from_string_matrix().
operator!=()
template<typename T > bool CuMatrix< T >::operator!= (const CuMatrix< T > & other) const inline
References CuMatrix< T >::operator==().
operator=()
template<typename T > CuMatrix< T > & CuMatrix< T >::operator= (const CuMatrix< T > & other) inline
operator==()
template<typename T > bool CuMatrix< T >::operator== (const CuMatrix< T > & other) const inline
Referenced by CuMatrix< T >::operator!=().
operator[]() [1/2]
template<typename T > T * CuMatrix< T >::operator[] (size_t idx) inline
Referenced by CuMatrix< T >::repr_str().
operator[]() [2/2]
template<typename T > const T * CuMatrix< T >::operator[] (size_t idx) const inline
raw_data()
template<typename T > T * CuMatrix< T >::raw_data () const inline
repr()
template<typename T > std::string CuMatrix< T >::repr (size_t maxlen = -1) const inline
References c.
Referenced by CuVariant::toString().
repr_str()
template<typename T > std::string CuMatrix< T >::repr_str (size_t maxlen = -1) const inline
repr return a string representation of the matrix
Parameters
maxlen truncate the output after about maxlen characters
Returns
a string representation of the matrix in the form [a,b,c] [d,e,f] [...]
Note
maxlen is an indication of the maximum desired length: the last row in output is not truncated.
References c, and CuMatrix< T >::operator[]().
Referenced by CuVariant::toString().
size()
template<typename T > size_t CuMatrix< T >::size () const inline
The documentation for this class was generated from the following file:
cumatrix.h