cumbia: CuDataSerializer Class Reference
CuDataSerializer Class Reference
serialize CuData to send it over the network or save it into a file
#include <cudataserializer.h>
Public Member Functions
char * serialize (const CuData &da) const
uint32_t size (const char *data) const
uint32_t data_size (const char *data) const
uint32_t rows (const char *data) const
uint8_t version (const char *data) const
const char * data_ptr (const char *data) const
const char * src (const char *data) const
const char * msg_ptr (const char *data) const
std::string message (const char *data) const
uint32_t msg_len (const char *data) const
CuData deserialize (const char *data, size_t len) const
deserialize from binary data
Detailed Description
serialize CuData to send it over the network or save it into a file
Member Function Documentation
data_ptr()
const char * CuDataSerializer::data_ptr (const char * data) const
References size().
Referenced by deserialize().
data_size()
uint32_t CuDataSerializer::data_size (const char * data) const
References repr_offsets::datasiz, and roffsets.
Referenced by msg_ptr(), and serialize().
deserialize()
CuData CuDataSerializer::deserialize (const char * data, size_t len) const
deserialize from binary data
struct repr version check
extracted information: src: the source of data, at most CUDATASER_MAXSRCLEN long dt: data type, see CuVariant::DataType, f.e. CuVariant::Scalar, CuVariant::Vector df: data format see CuVariant::DataFormat, f.e. CuVariant::Double, CuVariant::String err: the error flag. if true an error message is normally available. You can check if struct repr.msgsiz is nonzero in any case timestamp_us: timestamp as double: seconds.microseconds timestamp_ms: timestamp as double: milliseconds.microseconds value: if present, check the data size in struct repr.datasiz. Data starts after sizeof(struct repr) bytes in the binary data and is long struct repr.datasiz bytes
Data presence is indicated by a non zero struct repr.datasiz and a non null data_ptr return value.
Data may optionally be followed by a message, unless err is true. In the latter case, an error message is always foreseen.
struct repr. msgsiz indicates the size of the message, in bytes, that starts after the data bulk. You can check if a message is present either testing for msgsiz > 0 or a non null msg_ptr.
Convenience functions help accessing data:
msg_ptr provides a pointer to the first byte of the message string, long struct repr. msgsiz
References CuVariant::Boolean, CuVariant::Char, data_ptr(), repr_offsets::datasiz, CuVariant::Double, CuVariant::Float, repr::format, CuVariant::Int, CuVariant::LongDouble, CuVariant::LongInt, CuVariant::LongLongInt, CuVariant::LongLongUInt, CuVariant::LongUInt, message(), msg_ptr(), perr, roffsets, repr_offsets::rows, CuData::s(), CuData::set(), CuVariant::Short, size(), repr::src, repr::stat, CuVariant::String, repr::timestamp, repr::type, CuVariant::UChar, CuVariant::UInt, CuVariant::UShort, VERSION, version(), and CuVariant::VoidPtr.
message()
std::string CuDataSerializer::message (const char * data) const
Referenced by deserialize().
msg_len()
uint32_t CuDataSerializer::msg_len (const char * data) const
References repr_offsets::msgsiz, and roffsets.
msg_ptr()
const char * CuDataSerializer::msg_ptr (const char * data) const
References data_size(), and size().
Referenced by deserialize().
rows()
uint32_t CuDataSerializer::rows (const char * data) const
References roffsets, and repr_offsets::rows.
serialize()
char * CuDataSerializer::serialize (const CuData & da) const
References CuData::B(), be, CuVariant::Boolean, CuData::c_str(), CuVariant::Char, CuData::containsKey(), data_size(), datos, CuVariant::Double, CuVariant::Float, repr::format, CuVariant::get_dim_x(), CuVariant::getFormat(), CuVariant::getSize(), CuVariant::getType(), CuVariant::Int, CuVariant::LongDouble, CuVariant::LongInt, CuVariant::LongLongInt, CuVariant::LongLongUInt, CuVariant::LongUInt, CuVariant::Matrix, repr::msgsiz, CuVariant::Short, repr::src, repr::stat, CuVariant::String, repr::timestamp, CuVariant::to_C_charP(), CuVariant::toBoolP(), CuVariant::toCharP(), CuVariant::toDoubleP(), CuVariant::toFloatP(), CuVariant::toIntP(), CuVariant::toLongDoubleP(), CuVariant::toLongIntP(), CuVariant::toLongLongIntP(), CuVariant::toShortP(), CuVariant::toUCharP(), CuVariant::toUIntP(), CuVariant::toULongIntP(), CuVariant::toULongLongIntP(), CuVariant::toUShortP(), repr::type, CuVariant::UChar, CuVariant::UInt, CuVariant::UShort, VERSION, repr::version, and CuVariant::VoidPtr.
size()
uint32_t CuDataSerializer::size (const char * data) const
References roffsets, and repr_offsets::size.
Referenced by data_ptr(), deserialize(), and msg_ptr().
src()
const char * CuDataSerializer::src (const char * data) const
References roffsets, and repr_offsets::src.
version()
uint8_t CuDataSerializer::version (const char * data) const
References roffsets, and repr_offsets::version.
Referenced by deserialize().
The documentation for this class was generated from the following files:
cudataserializer.h
cudataserializer.cpp