cumbia: CuThreadService Class Reference
CuThreadService Class Reference
cumbia service that creates threads and keeps references of the threads running within the application
#include <cuthreadservice.h>
Public Member Functions
CuThreadService ()
class constructor
CuThreadInterface * getThread (const CuData &token, const CuThreadsEventBridgeFactory_I &eventsBridgeFactory, const CuServiceProvider *service_provider, const CuThreadFactoryImplI &thread_factory_impl)
returns a new thread if the token passed as argument does not match any token from any other recorded thread in the service, an existing thread if a match is found
virtual ~CuThreadService ()
the class destructor
int count () const
returns the number of threads recorded by the service
void removeThread (CuThreadInterface *thread)
remove the specified thread from the service without deleting it
std::list< CuThreadInterface * > getThreads () const
returns the list of CuThreadInterface recorded in the service
std::string getName () const
returns the name of this service
CuServices::Type getType () const
returns the type of this service
Public Member Functions inherited from CuServiceI
virtual ~CuServiceI ()
Detailed Description
cumbia service that creates threads and keeps references of the threads running within the application
The cumbia thread service
The most important function in this service is CuThreadService::getThread. It returns a pointer to a CuThreadInterface implementation as instantiated by the CuThreadFactoryImplI class factory specified in the last input argument. This happens when the token passed to getThread does not match any token of any other running thread. In this case, a thread with a matching token is used (or an equivalent thread, since the CuThread::isEquivalent method is used for comparison). It is client responsibility to delete the thread returned by getThread: CuThreadService::removeThread erases the reference to the object from the internal list without deleting it.
The count method returns the number of threads currently managed by the service
The removeThread function removes the thread from the list without deleting it CuThreadService::removeThread is currently called from Cumbia::finish (Cumbia's class destructor).
The getThreads method returns the list of all the threads currently managed by the service. It is called by Cumbia::finish to ask every thread to exit (calls CuThread::exit) and then let the background thread join the main one (calling CuThread::wait)
See also
Cumbia::registerActivity
Cumbia::finish
Constructor & Destructor Documentation
CuThreadService()
CuThreadService::CuThreadService ()
class constructor
Class constructor.
Within the library, the service is created by the Cumbia constructor, where it's also registered to the CuServiceProvider.
~CuThreadService()
CuThreadService::~CuThreadService () virtual
the class destructor
class destructor, empties the list of threads
References pdelete.
Member Function Documentation
count()
int CuThreadService::count () const
returns the number of threads recorded by the service
Returns
the number of threads the service is currently aware of.
getName()
std::string CuThreadService::getName () const virtual
returns the name of this service
Returns
the const std::string "CuThreadService"
See also
getType
Implements CuServiceI.
getThread()
CuThreadInterface * CuThreadService::getThread (const CuData & token, const CuThreadsEventBridgeFactory_I & eventsBridgeFactory, const CuServiceProvider * service_provider, const CuThreadFactoryImplI & thread_factory_impl)
returns a new thread if the token passed as argument does not match any token from any other recorded thread in the service, an existing thread if a match is found
Parameters
token a CuData used to determine whether a new activity is run in a new thread or an existing thread is reused. If a new thread is created, the given token will be the new thread's token
thread_factory an implementation of the CuThreadFactoryImplI interface that creates specific instances of CuThreadInterface, normally CuThread.
Returns
a new thread or an existing one, according to the contents in the token discussed above.
Note
if token is empty, a new thread is returned.
Reusing threads
An existing thread is reused if the token parameter to getThread is equivalent to the existing thread's token. Whether threads (or tokens) are equivalent or not is decided by CuThread::isEquivalent.
The service provider passed as parameter to getThread is directly handed to the CuThreadFactoryImplI::createThread. If the CuThreadFactoryImplI implementation is CuThreadFactoryImpl (that creates CuThread objects), the service provider is forwarded to the CuThread's constructor.
The CuThreadsEventBridgeFactory_I parameter is used to pass to CuThreadFactoryImplI::createThread an instance of CuThreadsEventBridge_I, that is a CuThreadsEventBridge for a basic cumbia thread event bridge, or a QThreadsEventBridge (cumbia-qtcontrols module) for Qt applications.
References CuThreadsEventBridgeFactory_I::createEventBridge(), and CuThreadFactoryImplI::createThread().
Referenced by Cumbia::registerActivity().
getThreads()
std::list< CuThreadInterface * > CuThreadService::getThreads () const
returns the list of CuThreadInterface recorded in the service
Returns
a std::vector of CuThreadInterface containing the pointers to the threads currently managed by the service
Called by Cumbia::finish
Referenced by Cumbia::finish().
getType()
CuServices::Type CuThreadService::getType () const virtual
returns the type of this service
Returns
the value CuServices::Thread defined in CuServices
Implements CuServiceI.
References CuServices::Thread.
removeThread()
void CuThreadService::removeThread (CuThreadInterface * thread)
remove the specified thread from the service without deleting it
Parameters
thread the CuThread to remove from the service
Note
the thread is not deleted. Responsibility for threads created by CuThreadService::getThread is handed to the client of the service.
Referenced by Cumbia::finish().
The documentation for this class was generated from the following files:
cuthreadservice.h
cuthreadservice.cpp