cumbia: CuResultEvent Class Reference
CuResultEvent Class Reference
The CuResultEvent class stores a result that a CuActivity (sender) wants to deliver from the background to the main thread.
#include <cuevent.h>
Public Member Functions
CuResultEvent (const CuActivity *sender, const CuData &data, CuEventType t=Result)
CuResultEvent::CuResultEvent the class constructor.
CuResultEvent (const CuActivity *sender, const std::vector< CuData > *data_list, CuEventType t=Result)
CuResultEvent::CuResultEvent the class constructor.
CuResultEvent (const CuActivity *sender, int step, int total, const CuData &data)
CuResultEvent::CuResultEvent class constructor with progress information.
virtual ~CuResultEvent ()
the class destructor
void setType (CuEventType t)
CuResultEvent::setType sets the event type.
CuEventType getType () const
CuResultEvent::getType returns the event type.
int getStep () const
returns the current step, if this event represents a progress event
int getTotal () const
returns the total number of steps, if this event represents a progress event
const CuData & getData () const
returns the CuData stored in the event
const CuActivity * getActivity () const
returns a pointer to the CuActivity that generated the event
bool isList () const
const std::vector< CuData > * getDataList () const
Public Member Functions inherited from CuEventI
virtual ~CuEventI ()
Protected Attributes
CuResultEventPrivate * d_p
Additional Inherited Members
Public Types inherited from CuEventI
enum CuEventType {
Progress = 0, Result, CuActivityExitEvent, ExitLoop,
ThreadAutoDestroy, User = 100
}
Detailed Description
The CuResultEvent class stores a result that a CuActivity (sender) wants to deliver from the background to the main thread.
This is used internally by the library
The CuResultEvent is usually extracted in the CuThread::onEventPosted method. It is used to get the exchanged data and the pointer to the activity that sent the event
Constructor & Destructor Documentation
CuResultEvent() [1/3]
CuResultEvent::CuResultEvent (const CuActivity * sender, const CuData & data, CuEventI::CuEventType t = Result)
CuResultEvent::CuResultEvent the class constructor.
Parameters
sender the CuActivity that originates the event
data the data to be delivered
t the type of event
References d_p.
CuResultEvent() [2/3]
CuResultEvent::CuResultEvent (const CuActivity * sender, const std::vector< CuData > * data_list, CuEventType t = Result)
CuResultEvent::CuResultEvent the class constructor.
Parameters
sender the CuActivity that originates the event
data_list a vector of data to be delivered
t the type of event
References d_p.
CuResultEvent() [3/3]
CuResultEvent::CuResultEvent (const CuActivity * sender, int step, int total, const CuData & data)
CuResultEvent::CuResultEvent class constructor with progress information.
Parameters
sender the CuActivity that originated the event (sender)
step the current step of a multi-step data processing
total the total steps of a multi-step data processing
data the data to be delivered
References d_p, and CuEventI::Progress.
~CuResultEvent()
CuResultEvent::~CuResultEvent () virtual
the class destructor
Event destruction
The event is destroyed after QApplication::postEvent if QThreadsEventBridge is used (see QThreadsEventBridge::postEvent and CuEvent_Qt::~CuEvent_Qt)
References d_p.
Member Function Documentation
getActivity()
const CuActivity * CuResultEvent::getActivity () const
returns a pointer to the CuActivity that generated the event
Returns
a pointer to the CuActivity that generated the event
References d_p.
Referenced by CuThread::onEventPosted().
getData()
const CuData & CuResultEvent::getData () const
returns the CuData stored in the event
Returns
CuData bundle carrying the event data
References d_p.
Referenced by CuThread::onEventPosted().
getDataList()
const std::vector< CuData > * CuResultEvent::getDataList () const
References d_p.
Referenced by CuThread::onEventPosted().
getStep()
int CuResultEvent::getStep () const
returns the current step, if this event represents a progress event
Returns
the current step if the type is CuResultEvent::Progress
References d_p.
Referenced by CuThread::onEventPosted().
getTotal()
int CuResultEvent::getTotal () const
returns the total number of steps, if this event represents a progress event
Returns
the number of total steps if the type is CuResultEvent::Progress
References d_p.
Referenced by CuThread::onEventPosted().
getType()
CuEventI::CuEventType CuResultEvent::getType () const virtual
CuResultEvent::getType returns the event type.
Returns
the event type as CuEventI::CuEventType
Implements CuEventI.
References d_p.
Referenced by CuThread::onEventPosted().
isList()
bool CuResultEvent::isList () const
References d_p.
Referenced by CuThread::onEventPosted().
setType()
void CuResultEvent::setType (CuEventI::CuEventType t)
CuResultEvent::setType sets the event type.
Parameters
t the event type as CuEventI::CuEventType
References d_p.
Member Data Documentation
d_p
CuResultEventPrivate* CuResultEvent::d_p protected
Referenced by CuResultEvent(), getActivity(), getData(), getDataList(), getStep(), getTotal(), getType(), isList(), setType(), and ~CuResultEvent().
The documentation for this class was generated from the following files:
cuevent.h
cuevent.cpp