cumbia: CuTimerService Class Reference
CuTimerService Class Reference
The CuTimerService class provides access to cumbia timers. It is normally used internally by the library itself, but it can be occasionally employed by applications to limit the maximum number of allocated timers, for optimization purposes.
#include <cutimerservice.h>
Public Member Functions
CuTimerService ()
Class constructor Initializes timerMaxCount to 25.
~CuTimerService ()
CuTimer * registerListener (CuTimerListener *timer_listener, int timeout)
Register a new CuTimerListener with a given timeout. Reuse existing timers if possible.
std::list< CuTimer * > getTimers ()
returns all the timers managed by the service
std::list< CuTimerListener * > getListeners (CuTimer *t) const
Returns the list of CuTimerListener registered to the timer t.
void unregisterListener (CuTimerListener *th, int timeout)
Unregister a listener with the given timeout from the service.
CuTimer * changeTimeout (CuTimerListener *th, int timeout)
Changet the timeout of the timer that serves the given listener.
bool isRegistered (CuTimerListener *th, int timeout)
CuTimerService::isRegistered returns true if a timer is registered for the given listener and timeout.
void setTimerMaxCount (int count)
Set the maximum number of timers that are allowed (per period)
int timerMaxCount () const
void restart (CuTimer *t, int millis)
restart the timer t with interval millis
std::string getName () const
Returns the name of the service.
CuServices::Type getType () const
CuTimerService::getType returns the service type.
Public Member Functions inherited from CuServiceI
virtual ~CuServiceI ()
Detailed Description
The CuTimerService class provides access to cumbia timers. It is normally used internally by the library itself, but it can be occasionally employed by applications to limit the maximum number of allocated timers, for optimization purposes.
CuTimerService implements CuServiceI in order to provide access to CuTimer objects. They are not directly available to clients. Use registerListener to either get a fresh timer or reuse an existing one, according to setTimerMaxCount. unregisterListener is called when a timer is no more needed. CuTimer is single shot: CuTimerService::restart method must then be called when the client needs to wait for a new timeout. Finally, it is possible to get the list of CuTimerListener for a given timer and the list of all timers. The timerMaxCount method returns the upper limit on the timers count set with setTimerMaxCount or the default value, which is
Each timer runs in a separate thread. That's why library offers the possibility to curb the number of timers. It makes sense if the thread creation policy of the engine in use promotes distributing sources across different threads.
Changing the max timers count.
From an application, get a handle to the CuTimerService from Cumbia and then call CuTimerService::setTimerMaxCount
CuTimerService *ts = static_cast<CuTimerService *>(cumbia_ptr->getServiceProvider()->get(CuServices::Timer));
ts->setTimerMaxCount(m_conf.max_timers);
Constructor & Destructor Documentation
CuTimerService()
CuTimerService::CuTimerService ()
Class constructor Initializes timerMaxCount to 25.
References CuTimerServicePrivate::timer_max_count.
~CuTimerService()
CuTimerService::~CuTimerService ()
References CuTimerServicePrivate::ti_cache, and CuTimerServicePrivate::ti_map.
Member Function Documentation
changeTimeout()
CuTimer * CuTimerService::changeTimeout (CuTimerListener * tl, int timeout)
Changet the timeout of the timer that serves the given listener.
Parameters
tl the CuTimerListener requiring a change in timeout
timeout the new timeout, in milliseconds
Returns
A fresh or existing timer satisfying the requirements in terms of timeout.
Note
Internally, unregisterListener and registerListener are called
References perr, registerListener(), CuTimerServicePrivate::shared_mutex, CuTimer::timeout(), and unregisterListener().
Referenced by CuThread::run().
getListeners()
std::list< CuTimerListener * > CuTimerService::getListeners (CuTimer * t) const
Returns the list of CuTimerListener registered to the timer t.
Parameters
t the timer whose listeners the caller is seeking for
Returns
the list of listeners of the timer t
getName()
std::string CuTimerService::getName () const virtual
Returns the name of the service.
Returns
"CuTimerService"
Implements CuServiceI.
getTimers()
std::list< CuTimer * > CuTimerService::getTimers ()
returns all the timers managed by the service
Returns
a list of the registered CuTimer instances
References CuTimerServicePrivate::shared_mutex, and CuTimerServicePrivate::ti_map.
getType()
CuServices::Type CuTimerService::getType () const virtual
CuTimerService::getType returns the service type.
Returns
CuServices::Timer
Implements CuServiceI.
References CuServices::Timer.
isRegistered()
bool CuTimerService::isRegistered (CuTimerListener * tlis, int timeout)
CuTimerService::isRegistered returns true if a timer is registered for the given listener and timeout.
Parameters
tlis the CuTimerListener
timeout the timeout
Returns
true if there is a timer registered for the given listener and timeout, false otherwise
References CuTimerServicePrivate::shared_mutex, and CuTimerServicePrivate::ti_cache.
registerListener()
CuTimer * CuTimerService::registerListener (CuTimerListener * timer_listener, int timeout)
Register a new CuTimerListener with a given timeout. Reuse existing timers if possible.
Parameters
timer_listener a CuTimerListener (e.g. CuThread)
timeout the desired timeout
Returns
a new CuTimer or a CuTimer already in use
Timer registration
If a timer associated to the given listener and timeout is already registered, it is reused. If timer_listener is new, the behaviour depends on the number of timers for the given timeout and the value of timerMaxCount:
number of timers <= timersMaxCount: a new timer is returned
an existing timer with the given timeout is reused
See also
timerMaxCount
setTimerMaxCount
References pgreen, CuTimer::setTimeout(), CuTimerServicePrivate::shared_mutex, CuTimerServicePrivate::ti_cache, CuTimerServicePrivate::ti_map, and CuTimerServicePrivate::timer_max_count.
Referenced by changeTimeout().
restart()
void CuTimerService::restart (CuTimer * t, int millis)
restart the timer t with interval millis
Parameters
t the timer to restart
millis the desired interval
Normally, CuThread asks CuTimerService to restart a timer after activity execution, to prevent timer event accumulation on the queue
Referenced by CuThread::run().
setTimerMaxCount()
void CuTimerService::setTimerMaxCount (int count)
Set the maximum number of timers that are allowed (per period)
Parameters
count the desired maximum number of timers for each period.
After timerMaxCount number of timers is reached, timers are reused
Default value
The default value is 25.
Note
Please configure this number before registering activities: changing this number later does not redistribute already registered timers.
References CuTimerServicePrivate::timer_max_count.
timerMaxCount()
int CuTimerService::timerMaxCount () const
References CuTimerServicePrivate::timer_max_count.
unregisterListener()
void CuTimerService::unregisterListener (CuTimerListener * tl, int timeout)
Unregister a listener with the given timeout from the service.
Parameters
tl the CuTimerListner to unregister
timeout the to remove listener's timeout
If the timer associated to tl has no more listeners after unregistration, it will be stopped and deleted.
References perr, and CuTimerServicePrivate::shared_mutex.
Referenced by changeTimeout().
The documentation for this class was generated from the following files:
cutimerservice.h
cutimerservice.cpp