cumbia: CuThreadInterface Class Reference
CuThreadInterface Class Reference abstract
interface to write thread implementations that can be used with the cumbia library
#include <cuthreadinterface.h>
Public Member Functions
virtual ~CuThreadInterface ()
interface virtual destructor
virtual void registerActivity (CuActivity *l)=0
register and start a new activity
virtual void unregisterActivity (CuActivity *l)=0
unregister and, if required, automatically delete an activity
virtual void publishProgress (const CuActivity *activity, int step, int total, const CuData &d)=0
post a progress event from the background thread to the main thread
virtual void publishResult (const CuActivity *activity, const CuData &d)=0
post a result event from the background thread to the main thread
virtual void publishResult (const CuActivity *activity, const std::vector< CuData > *data_list)=0
post a result event from the background thread to the main thread
virtual void publishExitEvent (CuActivity *a)=0
publish an exit event from the background thread to the main thread
virtual bool isEquivalent (const CuData &other_thread_token) const =0
Used by the thread factory, this function, given an input data, determines whether this thread is ecuivalent to another thread of the same class for the data.
virtual void cleanup ()=0
perform clean operations on the class members
virtual int type () const =0
return an integer to allow rtti
virtual void start ()=0
method to start the thread in the background
virtual bool isRunning ()=0
returns true if the thread is running, false otherwise
virtual void wait ()=0
wait for the thread to exit
virtual void exit ()=0
gracefully exit the thread
virtual int getActivityTimerPeriod (CuActivity *a) const =0
return the period of the timer running for the given activity
virtual void postEvent (CuActivity *, CuActivityEvent *)=0
forward an event to an activity
virtual void onEventPosted (CuEventI *event)=0
onEventPosted from CuThreadsEventBridgeListener interface.
Public Member Functions inherited from CuThreadsEventBridgeListener
virtual ~CuThreadsEventBridgeListener ()
Detailed Description
interface to write thread implementations that can be used with the cumbia library
This interface defines the necessary functionalities required to write thread implementations compatible with the cumbia library. CuThread adheres to this interface and is the default thread implementation in cumbia.
CuThread starts an activity (CuActivity), calls the CuActivity::init, CuActivity::execute and CuActivity::onExit hooks on the activity in a background thread (c++ 11 std::thread). Publishes progress and result events to the main thread when required by the activity (CuActivity::publishProgress and CuActivity::publishResult).
The required methods are as follows:
registerActivity: start an activity. See CuThread::registerActivity
unregisterActivity: stop an activity and delete it, if required. See CuThread::unregisterActivity
publishProgress: deliver an event accounting for a progress on the background work (see CuThread::publishProgress)
publishResult: deliver an event accounting for a result computed in the background thread
publishExitEvent: deliver an activity exit event to the activity
isEquivalent: determines whether a thread is equivalent to another thread. Equivalent threads run activities in the same thread.
cleanup: clean thread objects
type: return an integer describing the type of thread (for rtti conversion, if needed)
start: start the thread (allocate a new std::thread)
isRunning: return whether a thread is running or not
wait: join the std::thread
exit: use a proper event to exit the background thread
getActivityTimerPeriod: return the period of the timer running for the given activity
postEvent: post an event from the thread to an activity
As a CuThreadsEventBridgeListener, CuThreadInterface implementations will have to write an onEventPosted method from which all registered CuThreadListener instances will receive data (CuThreadListener::onProgress, CuThreadListener::onResult). The list of CuThreadListener objects is obtained calling CuActivityManager::getThreadListeners
Thread disposal
The interface does not define a specific behavior for thread disposal. CuThread implementation auto destroys itself when the last activity is unregistered.
Constructor & Destructor Documentation
~CuThreadInterface()
virtual CuThreadInterface::~CuThreadInterface () inline virtual
interface virtual destructor
virtual interface destructor
Member Function Documentation
cleanup()
virtual void CuThreadInterface::cleanup () pure virtual
perform clean operations on the class members
delete class members
Implemented in CuThread, and CuThread.
exit()
virtual void CuThreadInterface::exit () pure virtual
gracefully exit the thread
exit the thread loop gracefully
See also CuThread::exit
Implemented in CuThread, and CuThread.
Referenced by Cumbia::finish().
getActivityTimerPeriod()
virtual int CuThreadInterface::getActivityTimerPeriod (CuActivity * a) const pure virtual
return the period of the timer running for the given activity
see CuThread::getActivityTimerPeriod for a more complete description
Implemented in CuThread, and CuThread.
Referenced by Cumbia::getActivityPeriod().
isEquivalent()
virtual bool CuThreadInterface::isEquivalent (const CuData & other_thread_token) const pure virtual
Used by the thread factory, this function, given an input data, determines whether this thread is ecuivalent to another thread of the same class for the data.
Returns
true this thread is equivalent to another thread of the same implementation for the given data
false this thread is not ecuivalent to another thread dealing with other_thread_token
Parameters
other_thread_token generic data stored in a CuData container.
CuThreadService uses this method to decide whether to instantiate a new thread or return an existing one if the existing one can be reused according to other_thread_token. For example, a string representing a network URL can be a key to determine if the same thread can be reused for the same connection.
Implemented in CuThread, and CuThread.
isRunning()
virtual bool CuThreadInterface::isRunning () pure virtual
returns true if the thread is running, false otherwise
Returns
true the thread is running, false otherwise
Implemented in CuThread, and CuThread.
onEventPosted()
virtual void CuThreadInterface::onEventPosted (CuEventI * event) pure virtual
onEventPosted from CuThreadsEventBridgeListener interface.
Implements CuThreadsEventBridgeListener.
Implemented in CuThread, and CuThread.
postEvent()
virtual void CuThreadInterface::postEvent (CuActivity * , CuActivityEvent *) pure virtual
forward an event to an activity
This method must send an event of type CuActivityEvent to a CuActivity from the
Implemented in CuThread, and CuThread.
Referenced by Cumbia::pauseActivity(), Cumbia::postEvent(), Cumbia::resumeActivity(), and Cumbia::setActivityPeriod().
publishExitEvent()
virtual void CuThreadInterface::publishExitEvent (CuActivity * a) pure virtual
publish an exit event from the background thread to the main thread
The activity
Implemented in CuThread, and CuThread.
Referenced by CuActivity::doOnExit().
publishProgress()
virtual void CuThreadInterface::publishProgress (const CuActivity * activity, int step, int total, const CuData & d) pure virtual
post a progress event from the background thread to the main thread
This lets you send events to the main thread that account for an accomplished step over a total number of stages foreseen in the background
See CuThread::publishProgress for details
Implemented in CuThread, and CuThread.
Referenced by CuActivity::publishProgress().
publishResult() [1/2]
virtual void CuThreadInterface::publishResult (const CuActivity * activity, const CuData & d) pure virtual
post a result event from the background thread to the main thread
This lets you send events to the main thread that account for a result computed in the background
See CuThread::publishProgress for details
Implemented in CuThread, and CuThread.
Referenced by CuActivity::publishResult().
publishResult() [2/2]
virtual void CuThreadInterface::publishResult (const CuActivity * activity, const std::vector< CuData > * data_list) pure virtual
post a result event from the background thread to the main thread
This lets you send events to the main thread that account for a list of results computed in the background
See CuThread::publishProgress for details
Implemented in CuThread, and CuThread.
registerActivity()
virtual void CuThreadInterface::registerActivity (CuActivity * l) pure virtual
register and start a new activity
See CuThread::registerActivity for details
Implemented in CuThread, and CuThread.
start()
virtual void CuThreadInterface::start () pure virtual
method to start the thread in the background
starts the background thread where activities are run
Implemented in CuThread, and CuThread.
type()
virtual int CuThreadInterface::type () const pure virtual
return an integer to allow rtti
Returns
an integer identifying the kind of thread implementation
Implemented in CuThread, and CuThread.
unregisterActivity()
virtual void CuThreadInterface::unregisterActivity (CuActivity * l) pure virtual
unregister and, if required, automatically delete an activity
See CuThread::unregisterActivity for details
Implemented in CuThread, and CuThread.
Referenced by Cumbia::unregisterActivity().
wait()
virtual void CuThreadInterface::wait () pure virtual
wait for the thread to exit
call join on the thread
Implemented in CuThread, and CuThread.
Referenced by Cumbia::finish().
The documentation for this class was generated from the following file:
cuthreadinterface.h