cumbia: repr_offsets Struct Reference
repr_offsets Struct Reference
#include <cudataserializer.h>
Public Attributes
int size = 0
int version = size + sizeof(uint32_t)
int type = version + sizeof(uint8_t)
int format = type + sizeof(uint8_t)
int stat = format + sizeof(uint8_t)
int src = stat + sizeof(uint8_t)
int timestamp = src + sizeof(char) * CUDATASER_MAXSRCLEN
int datasiz = timestamp + sizeof(uint64_t)
int rows = datasiz + sizeof(uint32_t)
int msgsiz = rows + sizeof(uint32_t)
int totlen = msgsiz + sizeof(uint32_t)
Member Data Documentation
datasiz
int repr_offsets::datasiz = timestamp + sizeof(uint64_t)
Referenced by CuDataSerializer::data_size(), and CuDataSerializer::deserialize().
format
int repr_offsets::format = type + sizeof(uint8_t)
msgsiz
int repr_offsets::msgsiz = rows + sizeof(uint32_t)
Referenced by CuDataSerializer::msg_len().
rows
int repr_offsets::rows = datasiz + sizeof(uint32_t)
Referenced by CuDataSerializer::deserialize(), and CuDataSerializer::rows().
size
int repr_offsets::size = 0
Referenced by CuDataSerializer::size().
src
int repr_offsets::src = stat + sizeof(uint8_t)
Referenced by CuDataSerializer::src().
stat
int repr_offsets::stat = format + sizeof(uint8_t)
timestamp
int repr_offsets::timestamp = src + sizeof(char) * CUDATASER_MAXSRCLEN
totlen
int repr_offsets::totlen = msgsiz + sizeof(uint32_t)
type
int repr_offsets::type = version + sizeof(uint8_t)
version
int repr_offsets::version = size + sizeof(uint32_t)
Referenced by CuDataSerializer::version().
The documentation for this struct was generated from the following file:
cudataserializer.h