cumbia-http: CuHTTPActionReaderFactory Class Reference
CuHTTPActionReaderFactory Class Reference
#include <cuhttpactionfactories.h>
Public Member Functions
CuHTTPActionReaderFactory (bool single_shot)
virtual ~CuHTTPActionReaderFactory ()
void mergeOptions (const CuData &o)
CuHTTPActionA * create (const CuHTTPSrc &s, QNetworkAccessManager *nam, const QString &http_addr, CuHttpAuthManager *authman, CuHttpChannelReceiver *cr) const
std::string getMethod () const
Return the type of action that the factory creates.
CuHTTPActionFactoryI * clone () const
CuData options () const
Public Member Functions inherited from CuHTTPActionFactoryI
CuHTTPActionFactoryI ()
Constructor & Destructor Documentation
CuHTTPActionReaderFactory()
CuHTTPActionReaderFactory::CuHTTPActionReaderFactory (bool single_shot)
Referenced by clone().
~CuHTTPActionReaderFactory()
CuHTTPActionReaderFactory::~CuHTTPActionReaderFactory () virtual
Member Function Documentation
clone()
CuHTTPActionFactoryI * CuHTTPActionReaderFactory::clone () const virtual
Implements CuHTTPActionFactoryI.
References CuHTTPActionReaderFactory().
create()
CuHTTPActionA* CuHTTPActionReaderFactory::create (const CuHTTPSrc & s, QNetworkAccessManager * nam, const QString & http_addr, CuHttpAuthManager * authman, CuHttpChannelReceiver * cr) const
getMethod()
std::string CuHTTPActionReaderFactory::getMethod () const virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implements CuHTTPActionFactoryI.
mergeOptions()
void CuHTTPActionReaderFactory::mergeOptions (const CuData & o)
Referenced by CuHttpControlsReader::setSource().
options()
CuData CuHTTPActionReaderFactory::options () const virtual
Implements CuHTTPActionFactoryI.
The documentation for this class was generated from the following files:
cuhttpactionfactories.h
cuhttpactionfactories.cpp