cumbia-http: CumbiaHttp Class Reference
CumbiaHttp Class Reference
#include <cumbiahttp.h>
Public Types
enum Type { CumbiaHTTPType = Cumbia::CumbiaUserType + 18 }
Public Member Functions
CumbiaHttp (const QString &url, const QString &channel, CuThreadFactoryImplI *tfi, CuThreadsEventBridgeFactory_I *teb)
CumbiaHttp.
~CumbiaHttp ()
void setTag (const QString &tag)
CuThreadFactoryImplI * getThreadFactoryImpl () const
CuThreadsEventBridgeFactory_I * getThreadEventsBridgeFactory () const
QString url () const
virtual int getType () const
void readEnqueue (const CuHTTPSrc &source, CuDataListener *l, const CuHTTPActionFactoryI &f)
void unsubscribeEnqueue (const CuHTTPSrc &httpsrc, CuDataListener *l)
void executeWrite (const CuHTTPSrc &source, CuDataListener *l, const CuHTTPActionFactoryI &f)
void unlinkListener (CuDataListener *l)
disconnect the listener l of the given source
void addReplaceWildcardI (QuReplaceWildcards_I *rwi)
add a QuReplaceWildcards_I instance
void addSrcHelper (CuHttpSrcHelper_I *srch)
Add an implementation of CuHttpSrcHelper_I to help processing and preparing the sources before sending them through the http module.
QList< QuReplaceWildcards_I * > getReplaceWildcard_Ifaces () const
QList< CuHttpSrcHelper_I * > getSrcHelpers () const
void onSrcBundleReqReady (const QList< SrcItem > &rsrcs, const QList< SrcItem > &wsrcs)
void onSrcBundleReplyReady (const QByteArray &json)
void onSrcBundleReplyError (const CuData &errd)
notify every listener of a http server/gateway general error
void onCredsReady (const QString &user, const QString &passwd)
void onAuthReply (bool authorised, const QString &user, const QString &message, bool encrypted)
void onAuthError (const QString &errm)
Public Member Functions inherited from CuHttpBundledSrcReqListener
Public Member Functions inherited from CuHttpCliIdManListener
Public Member Functions inherited from CuHttpSrcQueueManListener
Public Member Functions inherited from CuHttpAuthManListener
Member Enumeration Documentation
Type
enum CumbiaHttp::Type
Enumerator
CumbiaHTTPType
Constructor & Destructor Documentation
CumbiaHttp()
CumbiaHttp::CumbiaHttp (const QString & url, const QString & channel, CuThreadFactoryImplI * tfi, CuThreadsEventBridgeFactory_I * teb)
CumbiaHttp.
Parameters
http_url the url to be used for http incoming data
http_url the http (https) url to be used to send requests to the server (output)
tfi thread factory implementation
teb thread events bridge factory
TEST
References url().
~CumbiaHttp()
CumbiaHttp::~CumbiaHttp ()
Member Function Documentation
addReplaceWildcardI()
void CumbiaHttp::addReplaceWildcardI (QuReplaceWildcards_I * rwi)
add a QuReplaceWildcards_I instance
Note
Ownership is handed to CumbiaHttp and objects are deleted in ~CumbiaHttp
Referenced by CuHttpRegisterEngine::registerWithDefaults().
addSrcHelper()
void CumbiaHttp::addSrcHelper (CuHttpSrcHelper_I * srch)
Add an implementation of CuHttpSrcHelper_I to help processing and preparing the sources before sending them through the http module.
Parameters
srch a pointer to a valid CuHttpSrcHelper_I instance.
Ownership
Ownership is handed to CumbiaHttp and CuHttpSrcHelper_I is deleted within the CumbiaHttp destructor.
Referenced by CuHttpRegisterEngine::registerWithDefaults().
executeWrite()
void CumbiaHttp::executeWrite (const CuHTTPSrc & source, CuDataListener * l, const CuHTTPActionFactoryI & f)
References CuHTTPActionFactoryI::getMethod(), and CuHTTPActionFactoryI::options().
getReplaceWildcard_Ifaces()
QList< QuReplaceWildcards_I * > CumbiaHttp::getReplaceWildcard_Ifaces () const
getSrcHelpers()
QList< CuHttpSrcHelper_I * > CumbiaHttp::getSrcHelpers () const
getThreadEventsBridgeFactory()
CuThreadsEventBridgeFactory_I * CumbiaHttp::getThreadEventsBridgeFactory () const
getThreadFactoryImpl()
CuThreadFactoryImplI * CumbiaHttp::getThreadFactoryImpl () const
getType()
int CumbiaHttp::getType () const virtual
References CumbiaHTTPType.
onAuthError()
void CumbiaHttp::onAuthError (const QString & errm) virtual
Implements CuHttpAuthManListener.
onAuthReply()
void CumbiaHttp::onAuthReply (bool authorised, const QString & user, const QString & message, bool encrypted) virtual
Implements CuHttpAuthManListener.
References CuHttpBundledSrcReq::start().
onCredsReady()
void CumbiaHttp::onCredsReady (const QString & user, const QString & passwd) virtual
Implements CuHttpAuthManListener.
onSrcBundleReplyError()
void CumbiaHttp::onSrcBundleReplyError (const CuData & errd) virtual
notify every listener of a http server/gateway general error
Parameters
errd data provided by CuHttpBundledSrcReq::onError after getting an error from an http request
For each listener of a given source (or target), an error message is built and delivered. It will be made up of
the error from the http server
the "data" (web page) received by the web server
the portion of the original request for the listener, extracted from the whole request payload, which in principle contains a JSon array of requests bundled together.
Implements CuHttpBundledSrcReqListener.
References SrcData::lis, and CumbiaHTTPWorld::request_reverse_eng().
onSrcBundleReplyReady()
void CumbiaHttp::onSrcBundleReplyReady (const QByteArray & json) virtual
Implements CuHttpBundledSrcReqListener.
References CumbiaHTTPWorld::json_decode().
onSrcBundleReqReady()
void CumbiaHttp::onSrcBundleReqReady (const QList< SrcItem > & rsrcs, const QList< SrcItem > & wsrcs) virtual
Implements CuHttpSrcQueueManListener.
readEnqueue()
void CumbiaHttp::readEnqueue (const CuHTTPSrc & source, CuDataListener * l, const CuHTTPActionFactoryI & f)
References CuHTTPActionFactoryI::getMethod(), and CuHTTPActionFactoryI::options().
setTag()
void CumbiaHttp::setTag (const QString & tag)
unlinkListener()
void CumbiaHttp::unlinkListener (CuDataListener * l)
disconnect the listener l of the given source
Parameters
source the full name of the source, as from CuHTTPSrc.prepare
l the CuDataListener to disconnect
Note
Disconnect the listener from a pending sync reply (onSrcBundleReplyReady), a pending error (onSrcBundleReplyError) and the channel receiver
called by CuHttpControlsR
unsubscribeEnqueue()
void CumbiaHttp::unsubscribeEnqueue (const CuHTTPSrc & httpsrc, CuDataListener * l)
References CuHTTPSrc::toString().
url()
QString CumbiaHttp::url () const
Referenced by CumbiaHttp().
The documentation for this class was generated from the following files:
cumbiahttp.h
cumbiahttp.cpp