cumbia-http: CuHttpBundledSrcReq Class Reference
CuHttpBundledSrcReq Class Reference
#include <cuhttpbundledsrcreq.h>
Public Member Functions
CuHttpBundledSrcReq (const QList< SrcItem > &srcs, CuHttpBundledSrcReqListener *l, unsigned long long client_id=0, QObject *parent=nullptr)
CuHttpBundledSrcReq (const QMap< QString, SrcData > &targetmap, CuHttpBundledSrcReqListener *l, const QByteArray &cookie=QByteArray(), QObject *parent=nullptr)
virtual ~CuHttpBundledSrcReq ()
void start (const QUrl &url, QNetworkAccessManager *nam)
void setBlocking (bool b)
Protected Slots
virtual void onNewData ()
virtual void onReplyFinished ()
virtual void onReplyDestroyed (QObject *)
virtual void onSslErrors (const QList< QSslError > &errors)
virtual void onError (QNetworkReply::NetworkError code)
void m_test_check_reply ()
Constructor & Destructor Documentation
CuHttpBundledSrcReq() [1/2]
CuHttpBundledSrcReq::CuHttpBundledSrcReq (const QList< SrcItem > & srcs, CuHttpBundledSrcReqListener * l, unsigned long long client_id = 0, QObject * parent = nullptr) explicit
CuHttpBundledSrcReq() [2/2]
CuHttpBundledSrcReq::CuHttpBundledSrcReq (const QMap< QString, SrcData > & targetmap, CuHttpBundledSrcReqListener * l, const QByteArray & cookie = QByteArray(), QObject * parent = nullptr) explicit
~CuHttpBundledSrcReq()
CuHttpBundledSrcReq::~CuHttpBundledSrcReq () virtual
Member Function Documentation
m_test_check_reply
void CuHttpBundledSrcReq::m_test_check_reply () protected slot
onError
void CuHttpBundledSrcReq::onError (QNetworkReply::NetworkError code) protected virtual slot
Referenced by start().
onNewData
void CuHttpBundledSrcReq::onNewData () protected virtual slot
Referenced by start().
onReplyDestroyed
void CuHttpBundledSrcReq::onReplyDestroyed (QObject * o) protected virtual slot
Referenced by start().
onReplyFinished
void CuHttpBundledSrcReq::onReplyFinished () protected virtual slot
Referenced by start().
onSslErrors
void CuHttpBundledSrcReq::onSslErrors (const QList< QSslError > & errors) protected virtual slot
Referenced by start().
setBlocking()
void CuHttpBundledSrcReq::setBlocking (bool b)
start()
void CuHttpBundledSrcReq::start (const QUrl & url, QNetworkAccessManager * nam)
TEST
References onError(), onNewData(), onReplyDestroyed(), onReplyFinished(), and onSslErrors().
Referenced by CumbiaHttp::onAuthReply().
The documentation for this class was generated from the following files:
cuhttpbundledsrcreq.h
cuhttpbundledsrcreq.cpp