cumbia-http: CuHttpActionConf Class Reference
CuHttpActionConf Class Reference
#include <cuhtttpactionconf.h>
Public Member Functions
CuHttpActionConf (const HTTPSource &src, QNetworkAccessManager *qnam, const QString &http_url)
~CuHttpActionConf ()
HTTPSource getSource () const
return a HTTPSource object that stores information about the Tango source
Type getType () const
returns the type of CuHTTPActionI implemented
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
size_t dataListenersCount ()
return the number of registered data listeners
void start ()
bool exiting () const
void stop ()
void decodeMessage (const QJsonDocument &json)
Public Member Functions inherited from CuHTTPActionA
CuHTTPActionA (QNetworkAccessManager *nam)
virtual ~CuHTTPActionA ()
virtual destructor, to make compilers happy
virtual void setHttpActionListener (CuHTTPActionListener *l)
virtual QNetworkRequest prepareRequest (const QUrl &url) const
Additional Inherited Members
Public Types inherited from CuHTTPActionA
enum Type { Reader = 0, Writer, Config, ChannelReceiver }
Protected Slots inherited from CuHTTPActionA
virtual void onNewData ()
virtual void onReplyFinished ()
virtual void onReplyDestroyed (QObject *)
virtual void onSslErrors (const QList< QSslError > &errors)
virtual void onError (QNetworkReply::NetworkError code)
virtual void startRequest (const QUrl &src)
virtual void stopRequest ()
CuHTTPActionListener * getHttpActionListener () const
QNetworkAccessManager * getNetworkAccessManager () const
Constructor & Destructor Documentation
CuHttpActionConf()
CuHttpActionConf::CuHttpActionConf (const HTTPSource & src, QNetworkAccessManager * qnam, const QString & http_url)
~CuHttpActionConf()
CuHttpActionConf::~CuHttpActionConf ()
Member Function Documentation
addDataListener()
void CuHttpActionConf::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuHTTPActionA.
dataListenersCount()
size_t CuHttpActionConf::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuHTTPActionA.
decodeMessage()
void CuHttpActionConf::decodeMessage (const QJsonDocument & json) virtual
Implements CuHTTPActionA.
References CumbiaHTTPWorld::json_decode().
exiting()
bool CuHttpActionConf::exiting () const virtual
Implements CuHTTPActionA.
getSource()
HTTPSource CuHttpActionConf::getSource () const virtual
return a HTTPSource object that stores information about the Tango source
Returns
HTTPSource, an object storing information on the Tango source
Implements CuHTTPActionA.
getType()
CuHTTPActionA::Type CuHttpActionConf::getType () const virtual
returns the type of CuHTTPActionI implemented
Returns
one of the values from the Type enum
Implements CuHTTPActionA.
References CuHTTPActionA::Config.
removeDataListener()
void CuHttpActionConf::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuHTTPActionA.
References stop().
start()
void CuHttpActionConf::start () virtual
Implements CuHTTPActionA.
References CuHTTPActionA::startRequest().
stop()
void CuHttpActionConf::stop () virtual
Implements CuHTTPActionA.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cuhtttpactionconf.h
cuhtttpactionconf.cpp