cumbia-http: CuHttpControlsWriterFactory Class Reference
CuHttpControlsWriterFactory Class Reference
implements CuControlsWriterFactoryI and creates Http writers Given a pointer to a Cumbia object and a CuDataListener, the create method instantiates and returns a CuHttpWriter, that implements CuControlsWriterA interface. If setOptions is called before create, the options are set on the CuControlsWriterA.
#include <cuhttpcontrolswriter.h>
Public Member Functions
CuHttpControlsWriterFactory ()
virtual ~CuHttpControlsWriterFactory ()
the class destructor
CuControlsWriterA * create (Cumbia *, CuDataListener *l) const
creates and returns a new CuHttpWriter, configured with the given Cumbia and CuDataListener.
CuControlsWriterFactoryI * clone () const
clones the writer factory, allocating a new one with the same options
void setOptions (const CuData &o)
set options through a CuData bundle. They are then passed to the CuHttpWriter instantiated and returned by the create method
Detailed Description
implements CuControlsWriterFactoryI and creates Http writers Given a pointer to a Cumbia object and a CuDataListener, the create method instantiates and returns a CuHttpWriter, that implements CuControlsWriterA interface. If setOptions is called before create, the options are set on the CuControlsWriterA.
CuHttpWriterFactory can be cloned by means of the clone method.
Constructor & Destructor Documentation
CuHttpControlsWriterFactory()
CuHttpControlsWriterFactory::CuHttpControlsWriterFactory ()
the class constructor
Referenced by clone().
~CuHttpControlsWriterFactory()
CuHttpControlsWriterFactory::~CuHttpControlsWriterFactory () virtual
the class destructor
Member Function Documentation
clone()
CuControlsWriterFactoryI * CuHttpControlsWriterFactory::clone () const
clones the writer factory, allocating a new one with the same options
Returns
a new CuHttpWriterFactory with options copied from this object
References CuHttpControlsWriterFactory().
create()
CuControlsWriterA * CuHttpControlsWriterFactory::create (Cumbia * c, CuDataListener * l) const
creates and returns a new CuHttpWriter, configured with the given Cumbia and CuDataListener.
Call setOptions before create to configure the writer. See setOptions for a list of predefined keys.
Parameters
c a pointer to the CumbiaHttp object
l a pointer to an object implementing the CuDataListener interface
Returns
a CuHttpWriter, an implementation of CuControlsWriterA abstract class
References CuHttpControlsWriter::setOptions().
setOptions()
void CuHttpControlsWriterFactory::setOptions (const CuData & o)
set options through a CuData bundle. They are then passed to the CuHttpWriter instantiated and returned by the create method
Parameters
o a CuData bundle of key/value pairs
Key/value pairs
no-properties [bool, default: false]. If true, skip attribute configuration in setTarget.
fetch_props [std::vector<std::string>, default: empty] list of attribute properties to fetch from the database during configuration. The no-properties key must be left to false (default).
See also
create
The documentation for this class was generated from the following files:
cuhttpcontrolswriter.h
cuhttpcontrolswriter.cpp