cumbia-http: HTTPSource Class Reference
HTTPSource Class Reference
#include <cuhttp_source.h>
Public Member Functions
HTTPSource ()
HTTPSource (const std::string &src)
HTTPSource (const HTTPSource &other)
string getName () const
Returns the full name that was given to the constructor without the cumbia domain engine specification.
string getNameNoArgs () const
Returns the source name as given to the constructor without arguments or placeholders.
string getProtocol () const
matches last protocol specification found in the source name, matching the pattern protocol://
std::vector< string > getArgs () const
string toString () const
HTTPSource & operator= (const HTTPSource &other)
bool operator== (const HTTPSource &other) const
std::string getArgsString () const
Constructor & Destructor Documentation
HTTPSource() [1/3]
HTTPSource::HTTPSource ()
HTTPSource() [2/3]
HTTPSource::HTTPSource (const std::string & src)
HTTPSource() [3/3]
HTTPSource::HTTPSource (const HTTPSource & other)
Member Function Documentation
getArgs()
std::vector< string > HTTPSource::getArgs () const
References getArgsString().
getArgsString()
std::string HTTPSource::getArgsString () const
Referenced by getArgs(), and toString().
getName()
string HTTPSource::getName () const
Returns the full name that was given to the constructor without the cumbia domain engine specification.
Returns
the source that was passed to the constructor
Referenced by CuHTTPActionReader::CuHTTPActionReader().
getNameNoArgs()
string HTTPSource::getNameNoArgs () const
Returns the source name as given to the constructor without arguments or placeholders.
Returns
source name without arguments or placeholders
Example
HTTPSource s("myhost:20000/ab/cd/ef/hi(200)");
HTTPSource s2("myhost:20000/ab/cd/ef/hello(&hello_spinbox)");
s.getName(); // "myhost:20000/ab/cd/ef/hi(200)"
s.getNameNoArgs(); // "myhost:20000/ab/cd/ef/hi"
s2.getNameNoArgs(); // "myhost:20000/ab/cd/ef/hello"
getProtocol()
string HTTPSource::getProtocol () const
matches last protocol specification found in the source name, matching the pattern protocol://
example
In the source "https://pwma-dev.elettra.eu:10443/v1/cs/tango://ken.elettra.trieste.it:20000/test/device/1/double_scalar" "tango://" is returned
Referenced by CuHTTPActionReader::CuHTTPActionReader().
operator=()
HTTPSource & HTTPSource::operator= (const HTTPSource & other)
operator==()
bool HTTPSource::operator== (const HTTPSource & other) const
toString()
std::string HTTPSource::toString () const
References getArgsString().
The documentation for this class was generated from the following files:
cuhttp_source.h
cuhttp_source.cpp