cumbia-http: CuHttpActionWriter Class Reference
CuHttpActionWriter Class Reference
#include <cuhttpactionwriter.h>
Public Member Functions
CuHttpActionWriter (const HTTPSource &target, QNetworkAccessManager *qnam, const QString &http_url, CuHttpAuthManager *authman)
~CuHttpActionWriter ()
void setWriteValue (const CuVariant &w)
void setConfiguration (const CuData &co)
HTTPSource getSource () const
return a HTTPSource object that stores information about the Tango source
Type getType () const
returns the type of CuHTTPActionI implemented
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
size_t dataListenersCount ()
return the number of registered data listeners
void start ()
bool exiting () const
void stop ()
void decodeMessage (const QJsonDocument &json)
void notifyActionFinished ()
the default implementation calls onActionFinished on the registered CuHttpListener
QNetworkRequest prepareRequest (const QUrl &url) const
Public Member Functions inherited from CuHTTPActionA
CuHTTPActionA (QNetworkAccessManager *nam)
virtual ~CuHTTPActionA ()
virtual destructor, to make compilers happy
virtual void setHttpActionListener (CuHTTPActionListener *l)
Additional Inherited Members
Public Types inherited from CuHTTPActionA
enum Type { Reader = 0, Writer, Config, ChannelReceiver }
Protected Slots inherited from CuHTTPActionA
virtual void onNewData ()
virtual void onReplyFinished ()
virtual void onReplyDestroyed (QObject *)
virtual void onSslErrors (const QList< QSslError > &errors)
virtual void onError (QNetworkReply::NetworkError code)
virtual void startRequest (const QUrl &src)
virtual void stopRequest ()
CuHTTPActionListener * getHttpActionListener () const
QNetworkAccessManager * getNetworkAccessManager () const
Constructor & Destructor Documentation
CuHttpActionWriter()
CuHttpActionWriter::CuHttpActionWriter (const HTTPSource & target, QNetworkAccessManager * qnam, const QString & http_url, CuHttpAuthManager * authman)
~CuHttpActionWriter()
CuHttpActionWriter::~CuHttpActionWriter ()
Member Function Documentation
addDataListener()
void CuHttpActionWriter::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuHTTPActionA.
dataListenersCount()
size_t CuHttpActionWriter::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuHTTPActionA.
decodeMessage()
void CuHttpActionWriter::decodeMessage (const QJsonDocument & json) virtual
Implements CuHTTPActionA.
References CumbiaHTTPWorld::json_decode().
exiting()
bool CuHttpActionWriter::exiting () const virtual
Implements CuHTTPActionA.
getSource()
HTTPSource CuHttpActionWriter::getSource () const virtual
return a HTTPSource object that stores information about the Tango source
Returns
HTTPSource, an object storing information on the Tango source
Implements CuHTTPActionA.
getType()
CuHTTPActionA::Type CuHttpActionWriter::getType () const virtual
returns the type of CuHTTPActionI implemented
Returns
one of the values from the Type enum
Implements CuHTTPActionA.
References CuHTTPActionA::Writer.
notifyActionFinished()
void CuHttpActionWriter::notifyActionFinished () virtual
the default implementation calls onActionFinished on the registered CuHttpListener
This is normally called from onReplyDestroyed, but CuHttpActionWriter can call this method to unregister tha action after the authentication fails
Reimplemented from CuHTTPActionA.
References CuHTTPActionA::notifyActionFinished(), and stop().
prepareRequest()
QNetworkRequest CuHttpActionWriter::prepareRequest (const QUrl & url) const virtual
Reimplemented from CuHTTPActionA.
removeDataListener()
void CuHttpActionWriter::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuHTTPActionA.
References stop().
setConfiguration()
void CuHttpActionWriter::setConfiguration (const CuData & co)
Referenced by CuHTTPActionWriterFactory::create().
setWriteValue()
void CuHttpActionWriter::setWriteValue (const CuVariant & w)
Referenced by CuHTTPActionWriterFactory::create().
start()
void CuHttpActionWriter::start () virtual
Implements CuHTTPActionA.
References CuHTTPActionA::startRequest().
stop()
void CuHttpActionWriter::stop () virtual
Implements CuHTTPActionA.
Referenced by notifyActionFinished(), and removeDataListener().
The documentation for this class was generated from the following files:
cuhttpactionwriter.h
cuhttpactionwriter.cpp