cumbia-http: CuHTTPActionWriterFactory Class Reference
CuHTTPActionWriterFactory Class Reference
#include <cuhttpactionfactories.h>
Public Member Functions
virtual ~CuHTTPActionWriterFactory ()
void setConfiguration (const CuData &conf)
void setWriteValue (const CuVariant &write_val)
CuHTTPActionA * create (const std::string &s, QNetworkAccessManager *qnam, const QString &http_addr, CuHttpAuthManager *authman, CuHttpChannelReceiver *cr=nullptr) const
CuHTTPActionA::Type getType () const
Return the type of action that the factory creates.
Public Member Functions inherited from CuHTTPActionFactoryI
CuHTTPActionFactoryI ()
Constructor & Destructor Documentation
~CuHTTPActionWriterFactory()
CuHTTPActionWriterFactory::~CuHTTPActionWriterFactory () virtual
Member Function Documentation
create()
CuHTTPActionA * CuHTTPActionWriterFactory::create (const std::string & s, QNetworkAccessManager * nam, const QString & http_addr, CuHttpAuthManager * authman, CuHttpChannelReceiver * cr = nullptr) const virtual
Pure virtual method that must be implemented by subclasses to return a valid CuHTTPActionA instance.
Implements CuHTTPActionFactoryI.
References CuHttpActionWriter::setConfiguration(), and CuHttpActionWriter::setWriteValue().
getType()
CuHTTPActionA::Type CuHTTPActionWriterFactory::getType () const virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implements CuHTTPActionFactoryI.
References CuHTTPActionA::Writer.
setConfiguration()
void CuHTTPActionWriterFactory::setConfiguration (const CuData & conf)
Referenced by CuHttpControlsWriter::execute().
setWriteValue()
void CuHTTPActionWriterFactory::setWriteValue (const CuVariant & write_val)
Referenced by CuHttpControlsWriter::execute().
The documentation for this class was generated from the following files:
cuhttpactionfactories.h
cuhttpactionfactories.cpp