cumbia-http: CuHttpRegisterEngine Class Reference
CuHttpRegisterEngine Class Reference
#include <cuhttpregisterengine.h>
Public Member Functions
CuHttpRegisterEngine ()
virtual ~CuHttpRegisterEngine ()
CumbiaHttp * registerWithDefaults (CumbiaPool *cu_pool, CuControlsFactoryPool &fpoo)
Setup CumbiaHttp with some default options.
void setUrl (const QString &url)
void setChannel (const QString &chan)
QString url () const
QString channel () const
bool load (const QStringList &args, bool force_load=false) const
load the http engine: parse the arguments and set the URL, channel, ttl, if possible either from args or cumbia module-default user settings
bool hasCmdOption (const QStringList &args) const
QString urlDefault (bool oldv=false) const
bool httpModeDefault (bool *oldv) const
Constructor & Destructor Documentation
CuHttpRegisterEngine()
CuHttpRegisterEngine::CuHttpRegisterEngine ()
~CuHttpRegisterEngine()
CuHttpRegisterEngine::~CuHttpRegisterEngine () virtual
Member Function Documentation
channel()
QString CuHttpRegisterEngine::channel () const
Referenced by registerWithDefaults().
hasCmdOption()
bool CuHttpRegisterEngine::hasCmdOption (const QStringList & args) const
for cumbia < 1.5.0 compatibility. calls load(args)
References load().
httpModeDefault()
bool CuHttpRegisterEngine::httpModeDefault (bool * oldv) const
Referenced by load().
load()
bool CuHttpRegisterEngine::load (const QStringList & args, bool force_load = false) const
load the http engine: parse the arguments and set the URL, channel, ttl, if possible either from args or cumbia module-default user settings
Parameters
args the command line arguments
force_load if true, try to load the engine also if args does not contain "-u" (for example, if an URL is configured by cumbia module-default and we are hot switching the engine to http at runtime)
Returns
true if loading is successful ('-u' or force_load and it was possible to get an URL from either '-u' option or the user settings)
References httpModeDefault(), url(), and urlDefault().
Referenced by hasCmdOption().
registerWithDefaults()
CumbiaHttp * CuHttpRegisterEngine::registerWithDefaults (CumbiaPool * cu_pool, CuControlsFactoryPool & fpoo)
Setup CumbiaHttp with some default options.
Parameters
cu_pool a pointer to a valid CumbiaPool. A new CumbiaHttp instance will be registered with name "http"
fpoo a reference to a CuControlsFactoryPool that will be initialized with registerImpl, name "http"
Returns
a pointer to a newly allocated CumbiaHttp registered into cu_pool with name "http"
Default operations
The following helpers are installed on CumbiaHttp:
CuHttpTangoReplaceWildcards to replace wildcards in the command line arguments as the native tango engine would do;
CuHttpTangoHelper is used to get Tango source patterns
CuHttpTangoSrcHelper is registered to CumbiaHttp so that attribute and command readings suitable to be monitored over time can be distinguished from single-shot database operations and the TANGO_HOST is prepended to the source name if missing. See CuHttpTangoSrcHelper::setOperation
References CumbiaHttp::addReplaceWildcardI(), CumbiaHttp::addSrcHelper(), channel(), and url().
setChannel()
void CuHttpRegisterEngine::setChannel (const QString & chan)
setUrl()
void CuHttpRegisterEngine::setUrl (const QString & url)
References url().
url()
QString CuHttpRegisterEngine::url () const
Referenced by load(), registerWithDefaults(), setUrl(), and urlDefault().
urlDefault()
QString CuHttpRegisterEngine::urlDefault (bool oldv = false) const
References url().
Referenced by load().
The documentation for this class was generated from the following files:
cuhttpregisterengine.h
cuhttpregisterengine.cpp