cumbia-http: CuHTTPSrc Class Reference
CuHTTPSrc Class Reference
#include <cuhttp_source.h>
Public Member Functions
CuHTTPSrc ()
virtual ~CuHTTPSrc ()
CuHTTPSrc (const std::string &src, const QList< CuHttpSrcHelper_I * > &srchs)
CuHTTPSrc (const CuHTTPSrc &other)
std::string getProtocol () const
matches last protocol specification found in the source name, matching the pattern protocol://
std::string toString () const
CuHTTPSrc & operator= (const CuHTTPSrc &other)
bool operator== (const CuHTTPSrc &other) const
returns true if this source raw name equals other's
bool canMonitor () const
returns true if the source is suitable to be monitored
std::string getName () const
Returns the full name that was given to the constructor without the cumbia domain engine specification.
std::string native_type () const
std::string prepare () const
std::string get (const char *what) const
Constructor & Destructor Documentation
CuHTTPSrc() [1/3]
CuHTTPSrc::CuHTTPSrc ()
~CuHTTPSrc()
CuHTTPSrc::~CuHTTPSrc () virtual
CuHTTPSrc() [2/3]
CuHTTPSrc::CuHTTPSrc (const std::string & src, const QList< CuHttpSrcHelper_I * > & srchs)
CuHTTPSrc() [3/3]
CuHTTPSrc::CuHTTPSrc (const CuHTTPSrc & other)
Member Function Documentation
canMonitor()
bool CuHTTPSrc::canMonitor () const
returns true if the source is suitable to be monitored
Returns
true if the source is a reader that can be monitored over time or if no helpers are installed. false if an installed helper's CuHttpSrcHelper_I::can_monitor returns negative for the given source.
Example
if CuHttpTangoSrcHelper is installed, canMonitor will return true if a source is an attribute or a command. They are indeed suitable to monitor values over time. The method returns false if the Tango helper detects a database data fetch related source, which shall be a one shot operation.
Default behaviour
If no helpers are installed, it is assumed that a source can monitor and true is returned
get()
string CuHTTPSrc::get (const char * what) const
getName()
string CuHTTPSrc::getName () const
Returns the full name that was given to the constructor without the cumbia domain engine specification.
Returns
the source that was passed to the constructor
Referenced by CuHttpActionConf::CuHttpActionConf(), and CumbiaHttp::unlinkListener().
getProtocol()
string CuHTTPSrc::getProtocol () const
matches last protocol specification found in the source name, matching the pattern protocol://
example
In the source "https://pwma-dev.elettra.eu:10443/v1/cs/tango://ken.elettra.trieste.it:20000/test/device/1/double_scalar" "tango://" is returned
native_type()
string CuHTTPSrc::native_type () const
operator=()
CuHTTPSrc & CuHTTPSrc::operator= (const CuHTTPSrc & other)
operator==()
bool CuHTTPSrc::operator== (const CuHTTPSrc & other) const
returns true if this source raw name equals other's
Parameters
other another CuHTTPSrc
Returns
true if raw names are the same
prepare()
string CuHTTPSrc::prepare () const
Referenced by CuHttpSrcMan::cancelSrc(), CuHttpActionConf::CuHttpActionConf(), CuHttpSrcMan::enqueueSrc(), CuHttpControlsReader::setSource(), and CuHttpControlsWriter::setTarget().
toString()
std::string CuHTTPSrc::toString () const
The documentation for this class was generated from the following files:
cuhttp_source.h
cuhttp_source.cpp