cumbia-http: CuHttpControlsWriter Class Reference
CuHttpControlsWriter Class Reference
implements CuControlsWriterA abstract class and provides an interface to connect a Tango writer to a target.
#include <cuhttpcontrolswriter.h>
Public Member Functions
CuHttpControlsWriter (Cumbia *cumbia_tango, CuDataListener *tl)
class constructor that's configured with CumbiaHttp and CuDataListener instances
virtual ~CuHttpControlsWriter ()
the class destructor.
QString target () const
returns the configured target, or an empty string
void clearTarget ()
remove the configured target, if any.
void setTarget (const QString &s)
connect the writer to the Tango control system target
virtual void execute ()
execute the target configured with setTarget. The value to write is taken from the return value of getArgs.
void sendData (const CuData &d)
This is not implemented yet.
void getData (CuData &d_ino) const
This is not implemented yet.
void setOptions (const CuData &o)
set the options on the writer (before setTarget)
Detailed Description
implements CuControlsWriterA abstract class and provides an interface to connect a Tango writer to a target.
Built with references to CumbiaTango and CuDataListener, CuHttpWriter implements CuControlsWriterA and connects a writer to the Tango control system through the setTarget method. setOptions can discretionary be called before setTarget.
Parameters and configuration can be sent and queried with sendData and getData respectively.
clearTarget can finally be called in order disconnect a writer, and if CuHttpWriter is deleted, clearTarget is called automatically.
Constructor & Destructor Documentation
CuHttpControlsWriter()
CuHttpControlsWriter::CuHttpControlsWriter (Cumbia * cu_http, CuDataListener * tl)
class constructor that's configured with CumbiaHttp and CuDataListener instances
Parameters
cu_http a pointer to a CumbiaHttp instance
CuDataListener a pointer to an object implementing the CuDataListener interface
References CumbiaHttp::CumbiaHTTPType.
~CuHttpControlsWriter()
CuHttpControlsWriter::~CuHttpControlsWriter () virtual
the class destructor.
The class destructors sets the invalidate flag on the listener, so that it won't be used later, and calls clearTarget
References clearTarget().
Member Function Documentation
clearTarget()
void CuHttpControlsWriter::clearTarget ()
remove the configured target, if any.
unlinks the attribute configuration listener
unlinks the writer listener
References CuHTTPActionA::Config, and CuHTTPActionA::Writer.
Referenced by ~CuHttpControlsWriter().
execute()
void CuHttpControlsWriter::execute () virtual
execute the target configured with setTarget. The value to write is taken from the return value of getArgs.
A CuTangoWriterFactory is used to start an activity managed by CumbiaHttp. The activity deals with writing the value on an attribute or imparting a command once.
References CuHTTPActionWriterFactory::setConfiguration(), and CuHTTPActionWriterFactory::setWriteValue().
getData()
void CuHttpControlsWriter::getData (CuData & d_ino) const
This is not implemented yet.
sendData()
void CuHttpControlsWriter::sendData (const CuData & d)
This is not implemented yet.
setOptions()
void CuHttpControlsWriter::setOptions (const CuData & o)
set the options on the writer (before setTarget)
This is usually called by CuHttpWriterFactory::create immediately after CuHttpWriter is instantiated.
Referenced by CuHttpControlsWriterFactory::create().
setTarget()
void CuHttpControlsWriter::setTarget (const QString & s)
connect the writer to the Tango control system target
Parameters
s the name of the writer target
References CuHTTPActionConfFactory::setOptions().
target()
QString CuHttpControlsWriter::target () const
returns the configured target, or an empty string
Returns
the configured target or an empty string if setTarget hasn't been called yet.
note
The returned string will contain the actual target, after wildcards have been replaced.
The documentation for this class was generated from the following files:
cuhttpcontrolswriter.h
cuhttpcontrolswriter.cpp