cumbia-http: CuHttpChannelReceiver Class Reference
CuHttpChannelReceiver Class Reference
Receive messages on the channel and distributes them.
#include <cuhttpchannelreceiver.h>
Public Member Functions
CuHttpChannelReceiver (const QString &url, const QString &chan, QNetworkAccessManager *nam)
QString channel () const
void registerReader (const QString &src, CuHTTPActionReader *r)
void unregisterReader (const QString &src)
QString url () const
QString ws_url () const
void addDataListener (const QString &src, CuDataListener *l)
void removeDataListener (CuDataListener *l)
size_t dataListenersCount ()
void start ()
void stop ()
void decodeMessage (const QJsonValue &json)
CuHttpChannelReceiver::decodeMessage decodes the json array passed as QJsonValue and updates the listeners of the involved sources.
QNetworkRequest prepareRequest (const QUrl &url) const
Protected Slots
virtual void onNewData ()
virtual void onWsMessageReceived (const QString &m)
virtual void onWsBinaryMessageReceived (const QByteArray &ba)
virtual void onReplyFinished ()
virtual void onReplyDestroyed (QObject *)
virtual void onSslErrors (const QList< QSslError > &errors)
virtual void onWsConnected ()
virtual void onWsSslErrors (const QList< QSslError > &errors)
virtual void onWsError (QAbstractSocket::SocketError socketError)
virtual void onError (QNetworkReply::NetworkError code)
virtual void cancelRequest ()
Detailed Description
Receive messages on the channel and distributes them.
Constructor & Destructor Documentation
CuHttpChannelReceiver()
CuHttpChannelReceiver::CuHttpChannelReceiver (const QString & url, const QString & chan, QNetworkAccessManager * nam) explicit
References url().
Member Function Documentation
addDataListener()
void CuHttpChannelReceiver::addDataListener (const QString & src, CuDataListener * l)
cancelRequest
void CuHttpChannelReceiver::cancelRequest () protected virtual slot
channel()
QString CuHttpChannelReceiver::channel () const
Referenced by url().
dataListenersCount()
size_t CuHttpChannelReceiver::dataListenersCount ()
decodeMessage()
void CuHttpChannelReceiver::decodeMessage (const QJsonValue & v)
CuHttpChannelReceiver::decodeMessage decodes the json array passed as QJsonValue and updates the listeners of the involved sources.
Parameters
v Json array.
Invoked by CuHTTPActionA.
Note
To avoid receiving older messages which were published before subscribing to channel, use the directive nchan_subscriber_first_message newest; * in the *sub section of nginx.conf
References CumbiaHTTPWorld::json_decode().
Referenced by onError(), onSslErrors(), onWsError(), and onWsSslErrors().
onError
void CuHttpChannelReceiver::onError (QNetworkReply::NetworkError code) protected virtual slot
References decodeMessage().
Referenced by start().
onNewData
void CuHttpChannelReceiver::onNewData () protected virtual slot
Referenced by start().
onReplyDestroyed
void CuHttpChannelReceiver::onReplyDestroyed (QObject *) protected virtual slot
Referenced by start().
onReplyFinished
void CuHttpChannelReceiver::onReplyFinished () protected virtual slot
References reqs_ended.
Referenced by start().
onSslErrors
void CuHttpChannelReceiver::onSslErrors (const QList< QSslError > & errors) protected virtual slot
References decodeMessage().
Referenced by start().
onWsBinaryMessageReceived
void CuHttpChannelReceiver::onWsBinaryMessageReceived (const QByteArray & ba) protected virtual slot
TEST
end test
Referenced by onWsConnected().
onWsConnected
void CuHttpChannelReceiver::onWsConnected () protected virtual slot
References onWsBinaryMessageReceived(), and onWsMessageReceived().
Referenced by start().
onWsError
void CuHttpChannelReceiver::onWsError (QAbstractSocket::SocketError socketError) protected virtual slot
References decodeMessage().
Referenced by start().
onWsMessageReceived
void CuHttpChannelReceiver::onWsMessageReceived (const QString & m) protected virtual slot
Referenced by onWsConnected().
onWsSslErrors
void CuHttpChannelReceiver::onWsSslErrors (const QList< QSslError > & errors) protected virtual slot
References decodeMessage().
prepareRequest()
QNetworkRequest CuHttpChannelReceiver::prepareRequest (const QUrl & url) const
References url().
Referenced by start().
registerReader()
void CuHttpChannelReceiver::registerReader (const QString & src, CuHTTPActionReader * r)
removeDataListener()
void CuHttpChannelReceiver::removeDataListener (CuDataListener * l)
start()
void CuHttpChannelReceiver::start ()
References onError(), onNewData(), onReplyDestroyed(), onReplyFinished(), onSslErrors(), onWsConnected(), onWsError(), prepareRequest(), reqs_started, url(), and ws_url().
stop()
void CuHttpChannelReceiver::stop ()
unregisterReader()
void CuHttpChannelReceiver::unregisterReader (const QString & src)
url()
QString CuHttpChannelReceiver::url () const
References channel().
Referenced by CuHttpChannelReceiver(), prepareRequest(), and start().
ws_url()
QString CuHttpChannelReceiver::ws_url () const
Referenced by start().
The documentation for this class was generated from the following files:
cuhttpchannelreceiver.h
cuhttpchannelreceiver.cpp