cumbia-http: CuHTTPActionA Class Reference
CuHTTPActionA Class Reference abstract
#include <cuhttpactiona.h>
Public Types
enum Type { Reader = 0, Writer, Config, ChannelReceiver }
Public Member Functions
CuHTTPActionA (QNetworkAccessManager *nam)
virtual ~CuHTTPActionA ()
virtual destructor, to make compilers happy
virtual HTTPSource getSource () const =0
return a HTTPSource object that stores information about the Tango source
virtual Type getType () const =0
returns the type of CuHTTPActionI implemented
virtual void addDataListener (CuDataListener *l)=0
insert a CuDataListener to the list of listeners of data updates
virtual void removeDataListener (CuDataListener *l)=0
remove a CuDataListener from the list of listeners of data updates
virtual size_t dataListenersCount ()=0
return the number of registered data listeners
virtual void start ()=0
virtual bool exiting () const =0
virtual void stop ()=0
virtual void decodeMessage (const QJsonDocument &json)=0
virtual void setHttpActionListener (CuHTTPActionListener *l)
virtual QNetworkRequest prepareRequest (const QUrl &url) const
virtual void notifyActionFinished ()
the default implementation calls onActionFinished on the registered CuHttpListener
Protected Slots
virtual void onNewData ()
virtual void onReplyFinished ()
virtual void onReplyDestroyed (QObject *)
virtual void onSslErrors (const QList< QSslError > &errors)
virtual void onError (QNetworkReply::NetworkError code)
virtual void startRequest (const QUrl &src)
virtual void stopRequest ()
CuHTTPActionListener * getHttpActionListener () const
QNetworkAccessManager * getNetworkAccessManager () const
Member Enumeration Documentation
Type
enum CuHTTPActionA::Type
Enumerator
Reader
Writer
Config
ChannelReceiver
Constructor & Destructor Documentation
CuHTTPActionA()
CuHTTPActionA::CuHTTPActionA (QNetworkAccessManager * nam)
~CuHTTPActionA()
CuHTTPActionA::~CuHTTPActionA () virtual
virtual destructor, to make compilers happy
Member Function Documentation
addDataListener()
virtual void CuHTTPActionA::addDataListener (CuDataListener * l) pure virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
Referenced by CumbiaHttp::addAction().
dataListenersCount()
virtual size_t CuHTTPActionA::dataListenersCount () pure virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
decodeMessage()
virtual void CuHTTPActionA::decodeMessage (const QJsonDocument & json) pure virtual
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
Referenced by onError(), and onSslErrors().
exiting()
virtual bool CuHTTPActionA::exiting () const pure virtual
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
Referenced by onReplyDestroyed().
getHttpActionListener
CuHTTPActionListener * CuHTTPActionA::getHttpActionListener () const protected slot
getNetworkAccessManager
QNetworkAccessManager * CuHTTPActionA::getNetworkAccessManager () const protected slot
Referenced by CuHTTPActionReader::stop().
getSource()
virtual HTTPSource CuHTTPActionA::getSource () const pure virtual
return a HTTPSource object that stores information about the Tango source
Returns
HTTPSource, an object storing information on the Tango source
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
Referenced by notifyActionFinished().
getType()
virtual Type CuHTTPActionA::getType () const pure virtual
returns the type of CuHTTPActionI implemented
Returns
one of the values from the Type enum
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
Referenced by notifyActionFinished(), and onReplyFinished().
notifyActionFinished()
void CuHTTPActionA::notifyActionFinished () virtual
the default implementation calls onActionFinished on the registered CuHttpListener
This is normally called from onReplyDestroyed, but CuHttpActionWriter can call this method to unregister tha action after the authentication fails
Reimplemented in CuHttpActionWriter.
References getSource(), and getType().
Referenced by CuHttpActionWriter::notifyActionFinished(), and onReplyDestroyed().
onError
void CuHTTPActionA::onError (QNetworkReply::NetworkError code) protected virtual slot
References decodeMessage().
Referenced by startRequest().
onNewData
void CuHTTPActionA::onNewData () protected virtual slot
Referenced by startRequest().
onReplyDestroyed
void CuHTTPActionA::onReplyDestroyed (QObject *) protected virtual slot
References exiting(), and notifyActionFinished().
Referenced by startRequest().
onReplyFinished
void CuHTTPActionA::onReplyFinished () protected virtual slot
References getType().
Referenced by startRequest().
onSslErrors
void CuHTTPActionA::onSslErrors (const QList< QSslError > & errors) protected virtual slot
References decodeMessage().
Referenced by startRequest().
prepareRequest()
QNetworkRequest CuHTTPActionA::prepareRequest (const QUrl & url) const virtual
Reimplemented in CuHttpActionWriter, and CuHttpChannelReceiver.
Referenced by CuHttpChannelReceiver::prepareRequest(), startRequest(), and CuHTTPActionReader::stop().
removeDataListener()
virtual void CuHTTPActionA::removeDataListener (CuDataListener * l) pure virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
setHttpActionListener()
void CuHTTPActionA::setHttpActionListener (CuHTTPActionListener * l) virtual
Referenced by CumbiaHttp::addAction().
start()
virtual void CuHTTPActionA::start () pure virtual
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
Referenced by CumbiaHttp::addAction().
startRequest
void CuHTTPActionA::startRequest (const QUrl & src) protected virtual slot
References onError(), onNewData(), onReplyDestroyed(), onReplyFinished(), onSslErrors(), and prepareRequest().
Referenced by CuHttpActionConf::start(), CuHttpChannelReceiver::start(), CuHTTPActionReader::start(), and CuHttpActionWriter::start().
stop()
virtual void CuHTTPActionA::stop () pure virtual
Implemented in CuHttpActionWriter, CuHTTPActionReader, CuHttpChannelReceiver, and CuHttpActionConf.
stopRequest
void CuHTTPActionA::stopRequest () protected virtual slot
Referenced by CuHttpChannelReceiver::stop().
The documentation for this class was generated from the following files:
cuhttpactiona.h
cuhttpactiona.cpp