cumbia-http: CuHTTPReaderFactory Class Reference
CuHTTPReaderFactory Class Reference
#include <cuhttpcontrolsreader.h>
Public Member Functions
CuHTTPReaderFactory ()
virtual ~CuHTTPReaderFactory ()
CuControlsReaderA * create (Cumbia *c, CuDataListener *l) const
creates and returns a new CuHttpControlsReader, configured with the given Cumbia and CuDataListener.
virtual void setOptions (const CuData &options)
CuControlsReaderFactoryI * clone () const
Constructor & Destructor Documentation
CuHTTPReaderFactory()
CuHTTPReaderFactory::CuHTTPReaderFactory ()
Referenced by clone().
~CuHTTPReaderFactory()
CuHTTPReaderFactory::~CuHTTPReaderFactory () virtual
Member Function Documentation
clone()
CuControlsReaderFactoryI * CuHTTPReaderFactory::clone () const
References CuHTTPReaderFactory(), and setOptions().
create()
CuControlsReaderA * CuHTTPReaderFactory::create (Cumbia * c, CuDataListener * l) const
creates and returns a new CuHttpControlsReader, configured with the given Cumbia and CuDataListener.
Call setOptions before create to configure the reader.
Parameters
c a pointer to the Cumbia object
l a pointer to an object implementing the CuDataListener interface
Returns
a CuHttpControlsReader, an implementation of CuControlsReaderA abstract class
Important note
The options are reset (to an empty CuData) after CuTControlsReader creation and initialization. This avoids applying the same options to subsequent create calls on the same factory
Important reading
Please see also the unsetSource documentation.
References CuHttpControlsReader::setOptions().
setOptions()
void CuHTTPReaderFactory::setOptions (const CuData & options) virtual
Referenced by clone().
The documentation for this class was generated from the following files:
cuhttpcontrolsreader.h
cuhttpcontrolsreader.cpp