cumbia-http: CuHTTPActionFactoryI Class Reference
CuHTTPActionFactoryI Class Reference abstract
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
#include <cuhttpactionfactoryi.h>
Public Member Functions
CuHTTPActionFactoryI ()
virtual CuHTTPActionA * create (const std::string &s, QNetworkAccessManager *nam, const QString &http_addr, CuHttpAuthManager *authman, CuHttpChannelReceiver *cr=nullptr) const =0
virtual CuHTTPActionA::Type getType () const =0
Return the type of action that the factory creates.
Detailed Description
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
Notable implementations
CuTangoReaderFactory
CuTangoWriterFactory
CuTangoAttConfFactory
Constructor & Destructor Documentation
CuHTTPActionFactoryI()
CuHTTPActionFactoryI::CuHTTPActionFactoryI () inline
Member Function Documentation
create()
virtual CuHTTPActionA* CuHTTPActionFactoryI::create (const std::string & s, QNetworkAccessManager * nam, const QString & http_addr, CuHttpAuthManager * authman, CuHttpChannelReceiver * cr = nullptr) const pure virtual
Pure virtual method that must be implemented by subclasses to return a valid CuHTTPActionA instance.
Implemented in CuHTTPActionConfFactory, CuHTTPActionWriterFactory, and CuHTTPActionReaderFactory.
Referenced by CuHTTPActionFactoryService::registerAction().
getType()
virtual CuHTTPActionA::Type CuHTTPActionFactoryI::getType () const pure virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implemented in CuHTTPActionConfFactory, CuHTTPActionWriterFactory, and CuHTTPActionReaderFactory.
Referenced by CumbiaHttp::addAction(), and CuHTTPActionFactoryService::registerAction().
The documentation for this class was generated from the following file:
cuhttpactionfactoryi.h