cumbia-http: CumbiaHTTPWorld Class Reference
CumbiaHTTPWorld Class Reference
#include <cumbiahttpworld.h>
Public Member Functions
CumbiaHTTPWorld ()
void setSrcPatterns (const std::vector< std::string > &pat_regex)
std::vector< std::string > srcPatterns () const
bool source_valid (const std::string &s)
bool json_decode (const QByteArray &ba, std::list< CuData > &out) const
bool json_decode (const QJsonValue &v, CuData &out) const
bool json_simple_decode (const QByteArray &jba, CuData &out) const
bool request_reverse_eng (const QString &json, QMap< QString, QString > &map, QString &channel) const
QJsonObject make_error (const QString &msg) const
QByteArray get_http_payload (const QByteArray &buf) const
Constructor & Destructor Documentation
CumbiaHTTPWorld()
CumbiaHTTPWorld::CumbiaHTTPWorld ()
Member Function Documentation
get_http_payload()
QByteArray CumbiaHTTPWorld::get_http_payload (const QByteArray & buf) const
json_decode() [1/2]
bool CumbiaHTTPWorld::json_decode (const QByteArray & ba, std::list< CuData > & out) const
Referenced by CuHttpChannelReceiver::decodeMessage(), and CumbiaHttp::onSrcBundleReplyReady().
json_decode() [2/2]
bool CumbiaHTTPWorld::json_decode (const QJsonValue & v, CuData & out) const
json_simple_decode()
bool CumbiaHTTPWorld::json_simple_decode (const QByteArray & jba, CuData & out) const
make_error()
QJsonObject CumbiaHTTPWorld::make_error (const QString & msg) const
request_reverse_eng()
bool CumbiaHTTPWorld::request_reverse_eng (const QString & json, QMap< QString, QString > & map, QString & channel) const
Referenced by CumbiaHttp::onSrcBundleReplyError().
setSrcPatterns()
void CumbiaHTTPWorld::setSrcPatterns (const std::vector< std::string > & pat_regex)
source_valid()
bool CumbiaHTTPWorld::source_valid (const std::string & s)
srcPatterns()
std::vector< std::string > CumbiaHTTPWorld::srcPatterns () const
The documentation for this class was generated from the following files:
cumbiahttpworld.h
cumbiahttpworld.cpp