cumbia-http: CuHttpAuthManager Class Reference
CuHttpAuthManager Class Reference
#include <cuhttpauthmanager.h>
Signals
void credentials (const QString &user, const QString &password)
void authReply (bool authorised, const QString &user, const QString &message, bool encrypted)
void error (const QString &msg)
Public Member Functions
CuHttpAuthManager (QNetworkAccessManager *netman, QObject *parent=nullptr)
~CuHttpAuthManager ()
void tryAuthorize (const QString &user, const QString &pass)
QByteArray getCookie () const
void authPrompt (const QString &auth_url, bool cli=false)
Constructor & Destructor Documentation
CuHttpAuthManager()
CuHttpAuthManager::CuHttpAuthManager (QNetworkAccessManager * netman, QObject * parent = nullptr)
~CuHttpAuthManager()
CuHttpAuthManager::~CuHttpAuthManager ()
Member Function Documentation
authPrompt()
void CuHttpAuthManager::authPrompt (const QString & auth_url, bool cli = false)
References CuHttpAuthInputFactory::create_prompt(), CuHttpAuthPrompt_I::getCreds(), and CuHttpAuthPrompt_I::qobj().
authReply
void CuHttpAuthManager::authReply (bool authorised, const QString & user, const QString & message, bool encrypted) signal
credentials
void CuHttpAuthManager::credentials (const QString & user, const QString & password) signal
error
void CuHttpAuthManager::error (const QString & msg) signal
Referenced by tryAuthorize().
getCookie()
QByteArray CuHttpAuthManager::getCookie () const
tryAuthorize()
void CuHttpAuthManager::tryAuthorize (const QString & user, const QString & pass)
References error().
The documentation for this class was generated from the following files:
cuhttpauthmanager.h
cuhttpauthmanager.cpp