cumbia-http: CuHttpCredInputCLIPrompt Class Reference
CuHttpCredInputCLIPrompt Class Reference
#include <cuhttpauthmanagertools.h>
Signals
void onCredsReady (const QString &u, const QString &pass)
Public Member Functions
CuHttpCredInputCLIPrompt (QObject *parent=nullptr)
~CuHttpCredInputCLIPrompt ()
void getCreds ()
QObject * qobj ()
bool inExecution () const
Public Member Functions inherited from CuHttpAuthPrompt_I
Protected Slots
void onInputFinished ()
Protected Member Functions
void run ()
Constructor & Destructor Documentation
CuHttpCredInputCLIPrompt()
CuHttpCredInputCLIPrompt::CuHttpCredInputCLIPrompt (QObject * parent = nullptr)
References onInputFinished().
~CuHttpCredInputCLIPrompt()
CuHttpCredInputCLIPrompt::~CuHttpCredInputCLIPrompt ()
Member Function Documentation
getCreds()
void CuHttpCredInputCLIPrompt::getCreds () virtual
Implements CuHttpAuthPrompt_I.
inExecution()
bool CuHttpCredInputCLIPrompt::inExecution () const virtual
Implements CuHttpAuthPrompt_I.
onCredsReady
void CuHttpCredInputCLIPrompt::onCredsReady (const QString & u, const QString & pass) signal
Referenced by onInputFinished().
onInputFinished
void CuHttpCredInputCLIPrompt::onInputFinished () protected slot
References onCredsReady().
Referenced by CuHttpCredInputCLIPrompt().
qobj()
QObject * CuHttpCredInputCLIPrompt::qobj () virtual
Implements CuHttpAuthPrompt_I.
run()
void CuHttpCredInputCLIPrompt::run () protected
References BUF_SIZ.
The documentation for this class was generated from the following files:
cuhttpauthmanagertools.h
cuhttpauthmanagertools.cpp