cumbia-component-config: Term Class Reference
Term Class Reference
#include <term.h>
Public Member Functions
void set_unbuf ()
void reset ()
Public Attributes
struct termios m_default_tio
Member Function Documentation
reset()
void Term::reset () inline
References m_default_tio.
Referenced by CuModuleComponent::menu_get_option(), and History::pick_entry().
set_unbuf()
void Term::set_unbuf () inline
References m_default_tio.
Referenced by CuModuleComponent::menu_get_option(), and History::pick_entry().
Member Data Documentation
m_default_tio
struct termios Term::m_default_tio
Referenced by reset(), and set_unbuf().
The documentation for this class was generated from the following file:
term.h