cumbia-component-config: ConfigComponent_A Class Reference
ConfigComponent_A Class Reference abstract
#include <configcomponent_a.h>
Public Member Functions
ConfigComponent_A (const std::string &confpath)
virtual ~ConfigComponent_A ()
virtual std::string name () const =0
Returns the name of the configuration component.
virtual std::string filenam () const
returns the filename made up of the path passed into the class constructor + name
virtual std::string process (int option)=0
processes the option obtained from menu_get_option
virtual int menu_get_option ()=0
returns the option from the user, typically chosen through a menu
virtual std::string update (const char *value)=0
update internal data without saving on configuration file
virtual bool save ()=0
write on filenam() the new contens
virtual void print ()=0
pretty print configuration component
virtual std::string error () const =0
get error message
virtual bool history_enabled () const =0
Constructor & Destructor Documentation
ConfigComponent_A()
ConfigComponent_A::ConfigComponent_A (const std::string & confpath) inline
~ConfigComponent_A()
virtual ConfigComponent_A::~ConfigComponent_A () inline virtual
Member Function Documentation
error()
virtual std::string ConfigComponent_A::error () const pure virtual
get error message
Returns
string with the error occurred or empty string
Implemented in CuModuleComponent.
Referenced by main().
filenam()
virtual std::string ConfigComponent_A::filenam () const inline virtual
returns the filename made up of the path passed into the class constructor + name
References name().
Referenced by CuModuleComponent::save().
history_enabled()
virtual bool ConfigComponent_A::history_enabled () const pure virtual
Implemented in CuModuleComponent.
menu_get_option()
virtual int ConfigComponent_A::menu_get_option () pure virtual
returns the option from the user, typically chosen through a menu
Returns
> 0 a valid option that will be passed to process
= 0 hand over processing to history
< 0 cancel
Implemented in CuModuleComponent.
Referenced by main().
name()
virtual std::string ConfigComponent_A::name () const pure virtual
Returns the name of the configuration component.
Implemented in CuModuleComponent.
Referenced by filenam(), and main().
print()
virtual void ConfigComponent_A::print () pure virtual
pretty print configuration component
Implemented in CuModuleComponent.
Referenced by main().
process()
virtual std::string ConfigComponent_A::process (int option) pure virtual
processes the option obtained from menu_get_option
Parameters
option result obtained from a previous call to menu_get_option
Returns
the new or updated line in the configuration file, that usually is the return value of update
Implemented in CuModuleComponent.
Referenced by main().
save()
virtual bool ConfigComponent_A::save () pure virtual
write on filenam() the new contens
Returns
true if successfully saved, false otherwise
Implemented in CuModuleComponent.
Referenced by main().
update()
virtual std::string ConfigComponent_A::update (const char * value) pure virtual
update internal data without saving on configuration file
Parameters
value the value, typically one line, to insert into the configuration. The component may update an existing line instead.
Returns
the line that was added or that replaced another configuration line
Implemented in CuModuleComponent.
Referenced by main().
The documentation for this class was generated from the following file:
configcomponent_a.h