cumbia-component-config: CuModuleComponent Class Reference
CuModuleComponent Class Reference
#include <cu-module-component.h>
Public Types
enum Mode { Generic , Url , EndModes }
Public Member Functions
CuModuleComponent (const std::string &cnfdir)
std::string update (const char *value)
update internal data without saving on configuration file
std::string process (int option)
processes the option obtained from menu_get_option
bool save ()
write on filenam() the new contens
std::string error () const
get error message
int menu_get_option ()
returns the option from the user, typically chosen through a menu
void print ()
pretty print configuration component
void list_modules () const
std::string name () const
Returns the name of the configuration component.
virtual bool history_enabled () const
Public Member Functions inherited from ConfigComponent_A
ConfigComponent_A (const std::string &confpath)
virtual ~ConfigComponent_A ()
virtual std::string filenam () const
returns the filename made up of the path passed into the class constructor + name
Public Attributes
const char * keywords [32] = { "native", "url:" }
Member Enumeration Documentation
Mode
enum CuModuleComponent::Mode
Enumerator
Generic
Url
EndModes
Constructor & Destructor Documentation
CuModuleComponent()
CuModuleComponent::CuModuleComponent (const std::string & cnfdir)
Member Function Documentation
error()
std::string CuModuleComponent::error () const virtual
get error message
Returns
string with the error occurred or empty string
Implements ConfigComponent_A.
history_enabled()
bool CuModuleComponent::history_enabled () const virtual
Implements ConfigComponent_A.
Referenced by menu_get_option().
list_modules()
void CuModuleComponent::list_modules () const
References name().
menu_get_option()
int CuModuleComponent::menu_get_option () virtual
returns the option from the user, typically chosen through a menu
Returns
> 0 a valid option that will be passed to process
= 0 hand over processing to history
< 0 cancel
Implements ConfigComponent_A.
References history_enabled(), Term::reset(), and Term::set_unbuf().
name()
std::string CuModuleComponent::name () const virtual
Returns the name of the configuration component.
Implements ConfigComponent_A.
Referenced by list_modules(), and print().
print()
void CuModuleComponent::print () virtual
pretty print configuration component
Implements ConfigComponent_A.
References name().
process()
std::string CuModuleComponent::process (int option) virtual
processes the option obtained from menu_get_option
Parameters
option result obtained from a previous call to menu_get_option
Returns
the new or updated line in the configuration file, that usually is the return value of update
Implements ConfigComponent_A.
References update().
save()
bool CuModuleComponent::save () virtual
write on filenam() the new contens
Returns
true if successfully saved, false otherwise
Implements ConfigComponent_A.
References ConfigComponent_A::filenam().
update()
std::string CuModuleComponent::update (const char * value) virtual
update internal data without saving on configuration file
Parameters
value the value, typically one line, to insert into the configuration. The component may update an existing line instead.
Returns
the line that was added or that replaced another configuration line
Implements ConfigComponent_A.
References EndModes, Generic, keywords, and Url.
Referenced by process().
Member Data Documentation
keywords
const char* CuModuleComponent::keywords[32] = { "native", "url:" }
Referenced by update().
The documentation for this class was generated from the following files:
cu-module-component.h
cu-module-component.cpp