cumbia-component-config: History Class Reference
History Class Reference
#include <history.h>
Public Member Functions
History (const std::string &fname)
std::string pick_entry ()
void add (const std::string &line)
Public Attributes
std::vector< std::string > entries
std::string m_fnam
const char * keywords [16] = { "url:" }
size_t history_max_entries
Constructor & Destructor Documentation
History()
History::History (const std::string & fname)
Member Function Documentation
add()
void History::add (const std::string & line)
References entries, history_max_entries, keywords, and m_fnam.
Referenced by main().
pick_entry()
std::string History::pick_entry ()
References entries, Term::reset(), and Term::set_unbuf().
Referenced by main().
Member Data Documentation
entries
std::vector<std::string> History::entries
Referenced by add(), and pick_entry().
history_max_entries
size_t History::history_max_entries
Referenced by add().
keywords
const char* History::keywords[16] = { "url:" }
Referenced by add().
m_fnam
std::string History::m_fnam
Referenced by add().
The documentation for this class was generated from the following files:
history.h
history.cpp