cumbia formula plugin: main.cpp File Reference
main.cpp File Reference
#include <quapplication.h>
#include "calculator.h"
#include <cumacros.h>
#include <cumbiapool.h>
#include <cuthreadfactoryimpl.h>
#include <qthreadseventbridgefactory.h>
Macros
#define CVSVERSION "$Name: $"
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
CVSVERSION
#define CVSVERSION "$Name: $"
Referenced by main().
Function Documentation
main()
int main (int argc, char * argv[])
References Calculator::code(), CVSVERSION, Calculator::hasFinished(), and Calculator::read().