cumbia formula plugin: CuFormulaParser Class Reference
CuFormulaParser Class Reference
#include <cuformulaparser.h>
Public Types
enum State {
Undefined = 0 , ReadingsIncomplete , CompileOk , CompileError ,
ValueNotScalar , ToDoubleConversionFailed , MaxState = 16
}
Public Member Functions
CuFormulaParser ()
~CuFormulaParser ()
bool parse (const QString &expression)
size_t sourcesCount () const
std::vector< std::string > sources () const
std::string joinedSources () const
std::string source (size_t i) const
void updateSource (size_t i, const std::string &s)
CuFormulaParser::updateSource updates the source at position i with the new source name s.
long indexOf (const std::string &src) const
QString expression () const
QString formula () const
QString preparedFormula () const
QString message () const
QString name () const
bool error () const
QString normalizedFormulaPattern () const
bool isNormalized (const QString &expr) const
bool isValid (const QString &expr) const
CuFormulaParser::isValid returns true if a formula is valid.
Public Attributes
const char states [MaxState][32]
const char * formula_regexp_pattern = FORMULA_RE
Member Enumeration Documentation
State
enum CuFormulaParser::State
Enumerator
Undefined
ReadingsIncomplete
CompileOk
CompileError
ValueNotScalar
ToDoubleConversionFailed
MaxState
Constructor & Destructor Documentation
CuFormulaParser()
CuFormulaParser::CuFormulaParser ()
References CuFormulaParserPrivate::error, and CuFormulaParserPrivate::normalized_pattern.
~CuFormulaParser()
CuFormulaParser::~CuFormulaParser ()
Member Function Documentation
error()
bool CuFormulaParser::error () const
References CuFormulaParserPrivate::error.
Referenced by CuFormulaReader::setSource().
expression()
QString CuFormulaParser::expression () const
References CuFormulaParserPrivate::expression.
formula()
QString CuFormulaParser::formula () const
References CuFormulaParserPrivate::formula.
Referenced by CuFormulaReader::onNewData(), and CuFormulaReader::setSource().
indexOf()
long int CuFormulaParser::indexOf (const std::string & src) const
References CuFormulaParserPrivate::srcs.
Referenced by CuFormulaReader::onNewData().
isNormalized()
bool CuFormulaParser::isNormalized (const QString & expr) const
References CuFormulaParserPrivate::normalized_pattern.
Referenced by isValid().
isValid()
bool CuFormulaParser::isValid (const QString & expr) const
Parameters
expr the expression to be matched against the FORMULA_RE regexp
Returns
returns isNormalized
Note
returns isNormalized
References isNormalized().
joinedSources()
std::string CuFormulaParser::joinedSources () const
References CuFormulaParserPrivate::srcs.
message()
QString CuFormulaParser::message () const
References CuFormulaParserPrivate::message.
name()
QString CuFormulaParser::name () const
References CuFormulaParserPrivate::name.
Referenced by CuFormulaReader::onNewData().
normalizedFormulaPattern()
QString CuFormulaParser::normalizedFormulaPattern () const
References CuFormulaParserPrivate::normalized_pattern.
parse()
bool CuFormulaParser::parse (const QString & expression)
References CuFormulaParserPrivate::error, CuFormulaParserPrivate::expression, CuFormulaParserPrivate::formula, CuFormulaParserPrivate::message, CuFormulaParserPrivate::name, CuFormulaParserPrivate::normalized_pattern, CuFormulaParserPrivate::prepared_formula, sources(), and CuFormulaParserPrivate::srcs.
Referenced by CuFormulaReader::setSource().
preparedFormula()
QString CuFormulaParser::preparedFormula () const
References CuFormulaParserPrivate::prepared_formula.
Referenced by CuFormulaReader::onNewData().
source()
std::string CuFormulaParser::source (size_t i) const
References CuFormulaParserPrivate::srcs.
Referenced by CuFormulaReader::combinedMessage(), and CuFormulaReader::setSource().
sources()
std::vector< std::string > CuFormulaParser::sources () const
References CuFormulaParserPrivate::srcs.
Referenced by CuFormulaReader::combinedSources(), CuFormulaReader::onNewData(), and parse().
sourcesCount()
size_t CuFormulaParser::sourcesCount () const
References CuFormulaParserPrivate::srcs.
Referenced by CuFormulaReader::combinedMessage(), CuFormulaReader::combinedSources(), CuFormulaReader::onNewData(), and CuFormulaReader::setSource().
updateSource()
void CuFormulaParser::updateSource (size_t i, const std::string & s)
Parameters
i the index of the source to be updated
s the new name
This can be used to update sources after wildcards ("$1, $2) have been replaced by engine specific readers.
Example
CuFormulaReader calls updateSource after QuWatcher::setSource so that CuFormulaParser contains the complete source name, after wildcards have been replaced by QuWatcher.
See also
CuFormulaReader::setSource
References CuFormulaParserPrivate::srcs.
Referenced by CuFormulaReader::setSource().
Member Data Documentation
formula_regexp_pattern
const char* CuFormulaParser::formula_regexp_pattern = FORMULA_RE
states
const char CuFormulaParser::states[MaxState][32]
Initial value:
= {
        "ReadingsIncomplete", "CompileOk", "CompileError", "ValueNotScalar",
        "ToDoubleConversionFailed", "", "", "", "", "", "", "", "MaxState"
    }
The documentation for this class was generated from the following files:
cuformulaparser.h
cuformulaparser.cpp