cumbia formula plugin: SimpleFormulaEval Class Reference
SimpleFormulaEval Class Reference
#include <simpleformulaeval.h>
Signals
void onCalcReady (const CuData &da)
Public Member Functions
SimpleFormulaEval (QObject *parent, const QString &formula)
Protected Slots
void publishResult ()
Protected Member Functions
void run ()
Constructor & Destructor Documentation
SimpleFormulaEval()
SimpleFormulaEval::SimpleFormulaEval (QObject * parent, const QString & formula)
References SimpleFormulaEvalPrivate::formula, and publishResult().
Member Function Documentation
onCalcReady
void SimpleFormulaEval::onCalcReady (const CuData & da) signal
Referenced by publishResult().
publishResult
void SimpleFormulaEval::publishResult () protected slot
References onCalcReady(), and SimpleFormulaEvalPrivate::result.
Referenced by SimpleFormulaEval().
run()
void SimpleFormulaEval::run () protected
References SimpleFormulaEvalPrivate::formula, and SimpleFormulaEvalPrivate::result.
The documentation for this class was generated from the following files:
simpleformulaeval.h
moc_simpleformulaeval.cpp
simpleformulaeval.cpp