cumbia formula plugin: CuFormulaReaderFactory Class Reference
CuFormulaReaderFactory Class Reference
#include <cuformulareader.h>
Public Member Functions
CuFormulaReaderFactory (CumbiaPool *cu_poo, const CuControlsFactoryPool &fpool)
CuFormulaReaderFactory::CuFormulaReaderFactory class constructor.
virtual ~CuFormulaReaderFactory ()
CuControlsReaderA * create (Cumbia *c, CuDataListener *l) const
create a new CuFormulaReader and forward options set on the factory by the CuFormulaReaderFactory client
void setOptions (const CuData &o)
CuFormulaReaderFactory::setOptions set options to be sent to the readers (QuWatcher)
CuData getOptions () const
CuControlsReaderFactoryI * clone () const
Constructor & Destructor Documentation
CuFormulaReaderFactory()
CuFormulaReaderFactory::CuFormulaReaderFactory (CumbiaPool * cu_poo, const CuControlsFactoryPool & fpool)
Parameters
cu_poo a pointer to a valid CumbiaPool
fpool a const reference to CuControlsFactoryPool
References CuFormulaReaderFactoryPrivate::cu_poo, and CuFormulaReaderFactoryPrivate::fpool.
Referenced by clone().
~CuFormulaReaderFactory()
CuFormulaReaderFactory::~CuFormulaReaderFactory () virtual
Member Function Documentation
clone()
CuControlsReaderFactoryI * CuFormulaReaderFactory::clone () const
References CuFormulaReaderFactoryPrivate::cu_poo, CuFormulaReaderFactory(), CuFormulaReaderFactoryPrivate::fpool, and CuFormulaReaderFactoryPrivate::options.
create()
CuControlsReaderA * CuFormulaReaderFactory::create (Cumbia * c, CuDataListener * l) const
Parameters
c a reference to a Cumbia implementation
l a CuDataListener
Returns
a new CuFormulaReader
Options
Options set on the CuControlsReaderFactoryI by the client are forwarded to the formula reader. CuFormulaReader employs QuWatcher to perform readings and options will be then sent to the watchers.
References CuFormulaReaderFactoryPrivate::cu_poo, CuFormulaReaderFactoryPrivate::fpool, getOptions(), and CuFormulaReader::setOptions().
getOptions()
CuData CuFormulaReaderFactory::getOptions () const
References CuFormulaReaderFactoryPrivate::options.
Referenced by create().
setOptions()
void CuFormulaReaderFactory::setOptions (const CuData & o)
Parameters
o CuData with key/value pairs
Options will be forwarded to the readers (CuFormulaReader employs QuWatcher)
References CuFormulaReaderFactoryPrivate::options.
The documentation for this class was generated from the following files:
cuformulareader.h
cuformulareader.cpp