cumbia formula plugin: Calculator Class Reference
Calculator Class Reference
#include <calculator.h>
Signals
void finished ()
Public Member Functions
Calculator (CumbiaPool *cu_p, QObject *parent=0, bool verbose=false)
~Calculator ()
void read (const QString &expr)
bool hasFinished () const
int code () const
void onUpdate (const CuData &data)
Constructor & Destructor Documentation
Calculator()
Calculator::Calculator (CumbiaPool * cu_p, QObject * parent = 0, bool verbose = false) explicit
~Calculator()
Calculator::~Calculator ()
Member Function Documentation
code()
int Calculator::code () const
Referenced by main().
finished
void Calculator::finished () signal
Referenced by onUpdate().
hasFinished()
bool Calculator::hasFinished () const
Referenced by main().
onUpdate()
void Calculator::onUpdate (const CuData & data)
References finished().
read()
void Calculator::read (const QString & expr)
Referenced by main().
The documentation for this class was generated from the following files:
calculator.h
moc_calculator.cpp
calculator.cpp