cumbia formula plugin: CuFormulaReader Class Reference
CuFormulaReader Class Reference
#include <cuformulareader.h>
Public Types
enum RefreshMode { RefreshModeUndefined = 0x1, Event = 0x2, Polled = 0x4, OneShot = 0x8 }
Public Slots
void onNewData (const CuData &da)
Public Member Functions
CuFormulaReader (Cumbia *c, CuDataListener *l, CumbiaPool *cu_poo, const CuControlsFactoryPool &fpool)
CuFormulaReader::CuFormulaReader class constructor.
~CuFormulaReader ()
bool error () const
QString message () const
CuDataQuality combinedQuality () const
std::string combinedMessage () const
std::string combinedSources () const
std::string combinedModes () const
std::vector< bool > errors () const
CuVariant fromScriptValue (const QScriptValue &v)
void setSource (const QString &s)
CuFormulaReader::setSource calls FormulaParser::parse to parse the input string and detect the sources and the formula. Sources can contain wildcards, so after readers have been set up, the free from wildcards source is updated on the FormulaParser.
QString source () const
void unsetSource ()
void sendData (const CuData &d)
void getData (CuData &d_ino) const
void setOptions (const CuData &opt)
CuFormulaReader::setOptions set options on the formula reader.
Protected Member Functions
bool event (QEvent *e)
Member Enumeration Documentation
RefreshMode
enum CuFormulaReader::RefreshMode
Enumerator
RefreshModeUndefined
Event
Polled
OneShot
Constructor & Destructor Documentation
CuFormulaReader()
CuFormulaReader::CuFormulaReader (Cumbia * c, CuDataListener * l, CumbiaPool * cu_poo, const CuControlsFactoryPool & fpool)
Parameters
c pointer to Cumbia (valid)
l CuDataListener that will receive updates
cu_poo pointer to CumbiaPool (valid)
fpool a const reference to CuControlsFactoryPool
The class is normally instantiated by CuFormulaReaderFactory
References CuFormulaReaderPrivate::cu_f, CuFormulaReaderPrivate::cu_poo, CuFormulaReaderPrivate::error, CuFormulaReaderPrivate::fpoo, CuFormulaReaderPrivate::listener, and CuFormulaReaderPrivate::single_display_unit.
~CuFormulaReader()
CuFormulaReader::~CuFormulaReader ()
Member Function Documentation
combinedMessage()
std::string CuFormulaReader::combinedMessage () const
References CuFormulaReaderPrivate::formula_parser, CuFormulaReaderPrivate::messages, CuFormulaReaderPrivate::qualities, CuFormulaParser::source(), and CuFormulaParser::sourcesCount().
Referenced by onNewData().
combinedModes()
std::string CuFormulaReader::combinedModes () const
References CuFormulaReaderPrivate::modes, Polled, and RefreshModeUndefined.
Referenced by onNewData().
combinedQuality()
CuDataQuality CuFormulaReader::combinedQuality () const
References CuFormulaReaderPrivate::qualities, and CuFormulaReaderPrivate::values.
Referenced by onNewData().
combinedSources()
std::string CuFormulaReader::combinedSources () const
References CuFormulaReaderPrivate::formula_parser, CuFormulaParser::sources(), and CuFormulaParser::sourcesCount().
Referenced by onNewData().
error()
bool CuFormulaReader::error () const
errors()
std::vector< bool > CuFormulaReader::errors () const
References CuFormulaReaderPrivate::errors.
event()
bool CuFormulaReader::event (QEvent * e) protected
References SetSrcFailedEvent::message, onNewData(), SetSrcFailedEvent::SetSrcFailedType, and SetSrcFailedEvent::source.
fromScriptValue()
CuVariant CuFormulaReader::fromScriptValue (const QScriptValue & v)
References CuFormulaReaderPrivate::error, and CuFormulaReaderPrivate::message.
Referenced by onNewData().
getData()
void CuFormulaReader::getData (CuData & d_ino) const
message()
QString CuFormulaReader::message () const
onNewData
void CuFormulaReader::onNewData (const CuData & da) slot
References combinedMessage(), combinedModes(), combinedQuality(), combinedSources(), CuFormulaReaderPrivate::display_unit, CuFormulaReaderPrivate::error, CuFormulaReaderPrivate::errors, CuFormulaParser::formula(), CuFormulaReaderPrivate::formula_parser, fromScriptValue(), CuFormulaParser::indexOf(), CuFormulaReaderPrivate::listener, CuFormulaReaderPrivate::message, CuFormulaReaderPrivate::messages, CuFormulaReaderPrivate::modes, CuFormulaParser::name(), CuFormulaParser::preparedFormula(), CuFormulaReaderPrivate::qualities, CuFormulaReaderPrivate::scriptEngine, CuFormulaParser::sources(), CuFormulaParser::sourcesCount(), and CuFormulaReaderPrivate::values.
Referenced by event(), and setSource().
sendData()
void CuFormulaReader::sendData (const CuData & d)
setOptions()
void CuFormulaReader::setOptions (const CuData & opt)
Parameters
opt CuData key/value bundle.
Options are sent to QuWatcher instances within setSource
References CuFormulaReaderPrivate::options.
Referenced by CuFormulaReaderFactory::create().
setSource()
void CuFormulaReader::setSource (const QString & s)
Parameters
s The source, in the form
{source0, source1} (expression(@0, @1)
{test/device/1/double_scalar test/device/1->DevDouble(10.1)}  ((@0+@1) * (@1 -sqrt(@0)))
References CuFormulaReaderPrivate::cu_poo, CuFormulaParser::error(), CuFormulaReaderPrivate::errors, CuFormulaParser::formula(), CuFormulaReaderPrivate::formula_parser, CuFormulaReaderPrivate::fpoo, CuFormulaReaderPrivate::messages, CuFormulaReaderPrivate::modes, onNewData(), CuFormulaReaderPrivate::options, CuFormulaParser::parse(), CuFormulaReaderPrivate::qualities, RefreshModeUndefined, CuFormulaParser::source(), CuFormulaReaderPrivate::source, CuFormulaParser::sourcesCount(), CuFormulaParser::updateSource(), and CuFormulaReaderPrivate::values.
source()
QString CuFormulaReader::source () const
References CuFormulaReaderPrivate::source.
unsetSource()
void CuFormulaReader::unsetSource ()
The documentation for this class was generated from the following files:
cuformulareader.h
cuformulareader.cpp