cumbia formula plugin: Ui_Testtest Class Reference
Ui_Testtest Class Reference
#include <ui_formulas.h>
Public Member Functions
void setupUi (QWidget *Testtest, CumbiaPool *cu_p, const CuControlsFactoryPool &m_ctrl_factory_pool)
void retranslateUi (QWidget *Testtest)
Public Attributes
QGridLayout * gridLayout
QuSpectrumPlot * quSpectrumPlot
Member Function Documentation
retranslateUi()
void Ui_Testtest::retranslateUi (QWidget * Testtest) inline
References quSpectrumPlot.
Referenced by setupUi().
setupUi()
void Ui_Testtest::setupUi (QWidget * Testtest, CumbiaPool * cu_p, const CuControlsFactoryPool & m_ctrl_factory_pool) inline
References gridLayout, quSpectrumPlot, and retranslateUi().
Referenced by Formulas::Formulas().
Member Data Documentation
gridLayout
QGridLayout* Ui_Testtest::gridLayout
Referenced by setupUi().
quSpectrumPlot
QuSpectrumPlot* Ui_Testtest::quSpectrumPlot
Referenced by retranslateUi(), and setupUi().
The documentation for this class was generated from the following file:
ui_formulas.h