qumbiaprojectwizard: MainWidgetCppCodeExtractor Class Reference
MainWidgetCppCodeExtractor Class Reference
#include <codeextractors.h>
Public Member Functions
virtual CodeExtractorA::Type type () const
virtual QList< Section > extract (CodeExtractorA::Type t)
Public Member Functions inherited from CodeExtractorA
bool error () const
QString errorMessage () const
Additional Inherited Members
Public Types inherited from CodeExtractorA
enum Type { MainCpp, MainWCpp, MainWH , Pro }
Protected Member Functions inherited from CodeExtractorA
QString m_get_file_contents (CodeExtractorA::Type t)
Protected Attributes inherited from CodeExtractorA
bool m_err
QString m_msg
Member Function Documentation
extract()
QList< Section > MainWidgetCppCodeExtractor::extract (CodeExtractorA::Type t) virtual
Implements CodeExtractorA.
References Section::EndOfCppConstructor, ExtractorHelper::extractCumbiaTangoSections(), Section::Includes, CodeExtractorA::m_err, CodeExtractorA::m_get_file_contents(), CodeExtractorA::m_msg, and Section::StartOfCppConstructor.
Referenced by CumbiaCodeInjectCmd::process().
type()
CodeExtractorA::Type MainWidgetCppCodeExtractor::type () const virtual
Implements CodeExtractorA.
References CodeExtractorA::MainWCpp.
The documentation for this class was generated from the following files:
codeextractors.h
codeextractors.cpp