qumbiaprojectwizard: TDialWrite Class Reference
TDialWrite Class Reference
#include <tdialwrite.h>
Public Slots
void setTarget (const QString &target)
Signals
void description (const QString &desc)
void description (const QString &desc)
void description (const QString &desc)
void description (const QString &desc)
Public Member Functions
TDialWrite (QWidget *parent=nullptr)
TDialWrite (QWidget *parent=nullptr)
TDialWrite (QWidget *parent=nullptr)
TDialWrite (QWidget *parent, Cumbia *cumbia, const CuControlsWriterFactoryI &w_fac)
QString target () const
virtual CuContext * getContext () const
virtual void onUpdate (const CuData &data)
Protected Slots
void autoConfigure (const TangoConfigurationParameters *cp)
void write (int val)
void autoConfigure (const TangoConfigurationParameters *cp)
void write (int val)
void autoConfigure (const TangoConfigurationParameters *cp)
void write (int val)
void write (int val)
Constructor & Destructor Documentation
TDialWrite() [1/4]
TDialWrite::TDialWrite (QWidget * parent = nullptr) explicit
References autoConfigure(), and write().
TDialWrite() [2/4]
TDialWrite::TDialWrite (QWidget * parent = nullptr) explicit
TDialWrite() [3/4]
TDialWrite::TDialWrite (QWidget * parent = nullptr) explicit
TDialWrite() [4/4]
TDialWrite::TDialWrite (QWidget * parent, Cumbia * cumbia, const CuControlsWriterFactoryI & w_fac) explicit
References write().
Member Function Documentation
autoConfigure [1/3]
void TDialWrite::autoConfigure (const TangoConfigurationParameters * cp) protected slot
References description().
Referenced by TDialWrite().
autoConfigure [2/3]
void TDialWrite::autoConfigure (const TangoConfigurationParameters * cp) protected slot
autoConfigure [3/3]
void TDialWrite::autoConfigure (const TangoConfigurationParameters * cp) protected slot
description [1/4]
void TDialWrite::description (const QString & desc) signal
Referenced by autoConfigure(), and onUpdate().
description [2/4]
void TDialWrite::description (const QString & desc) signal
description [3/4]
void TDialWrite::description (const QString & desc) signal
description [4/4]
void TDialWrite::description (const QString & desc) signal
getContext()
CuContext * TDialWrite::getContext () const virtual
onUpdate()
void TDialWrite::onUpdate (const CuData & data) virtual
References description().
setTarget
void TDialWrite::setTarget (const QString & target) slot
target()
QString TDialWrite::target () const
write [1/4]
void TDialWrite::write (int val) protected slot
Referenced by TDialWrite().
write [2/4]
void TDialWrite::write (int val) protected slot
write [3/4]
void TDialWrite::write (int val) protected slot
write [4/4]
void TDialWrite::write (int val) protected slot
The documentation for this class was generated from the following files:
src/tdialwrite.h
src/tdialwrite.cpp