cumbia-multiread plugin: QuMultiReader Class Reference
QuMultiReader Class Reference
#include <qumultireader.h>
Public Slots
void startRead ()
Signals
void onNewData (const CuData &da)
void onSeqReadComplete (const QList< CuData > &data)
Public Member Functions
QuMultiReader (QObject *parent=0)
virtual ~QuMultiReader ()
void init (Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac, int manual_mode_code=-1)
void init (CumbiaPool *cumbia_pool, const CuControlsFactoryPool &fpool, int manual_mode_code=-1)
void setSources (const QStringList &srcs)
void unsetSources ()
void insertSource (const QString &src, int i)
inserts src at index position i in the list. If i <= 0, src is prepended to the list. If i >= size(), src is appended to the list, whether or not src is already there.
void removeSource (const QString &src)
const QObject * get_qobject () const
returns a reference to this object, so that it can be used as a QObject to benefit from signal/slot connections.
QStringList sources () const
int period () const
void setPeriod (int ms)
void onUpdate (const CuData &data)
Constructor & Destructor Documentation
QuMultiReader()
QuMultiReader::QuMultiReader (QObject * parent = 0)
References QuMultiReaderPrivate::context, QuMultiReaderPrivate::manual_mode_code, QuMultiReaderPrivate::period, QuMultiReaderPrivate::sequential, and QuMultiReaderPrivate::timer.
~QuMultiReader()
QuMultiReader::~QuMultiReader () virtual
References QuMultiReaderPrivate::context.
Member Function Documentation
get_qobject()
const QObject * QuMultiReader::get_qobject () const
init() [1/2]
void QuMultiReader::init (Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac, int manual_mode_code = -1)
References QuMultiReaderPrivate::context, QuMultiReaderPrivate::manual_mode_code, and QuMultiReaderPrivate::sequential.
init() [2/2]
void QuMultiReader::init (CumbiaPool * cumbia_pool, const CuControlsFactoryPool & fpool, int manual_mode_code = -1)
References QuMultiReaderPrivate::context, QuMultiReaderPrivate::manual_mode_code, and QuMultiReaderPrivate::sequential.
insertSource()
void QuMultiReader::insertSource (const QString & src, int i)
See also
setSources
References QuMultiReaderPrivate::context, QuMultiReaderPrivate::manual_mode_code, QuMultiReaderPrivate::period, QuMultiReaderPrivate::readersMap, QuMultiReaderPrivate::sequential, and QuMultiReaderPrivate::srcs.
Referenced by setSources().
onNewData
void QuMultiReader::onNewData (const CuData & da) signal
Referenced by onUpdate().
onSeqReadComplete
void QuMultiReader::onSeqReadComplete (const QList< CuData > & data) signal
Referenced by onUpdate().
onUpdate()
void QuMultiReader::onUpdate (const CuData & data)
References QuMultiReaderPrivate::databuf, onNewData(), onSeqReadComplete(), QuMultiReaderPrivate::period, QuMultiReaderPrivate::readersMap, QuMultiReaderPrivate::sequential, QuMultiReaderPrivate::srcs, and QuMultiReaderPrivate::timer.
period()
int QuMultiReader::period () const
References QuMultiReaderPrivate::period.
removeSource()
void QuMultiReader::removeSource (const QString & src)
References QuMultiReaderPrivate::context, QuMultiReaderPrivate::readersMap, and QuMultiReaderPrivate::srcs.
setPeriod()
void QuMultiReader::setPeriod (int ms)
References QuMultiReaderPrivate::context, QuMultiReaderPrivate::period, and QuMultiReaderPrivate::sequential.
setSources()
void QuMultiReader::setSources (const QStringList & srcs)
References insertSource(), and unsetSources().
sources()
QStringList QuMultiReader::sources () const
References QuMultiReaderPrivate::srcs.
startRead
void QuMultiReader::startRead () slot
References QuMultiReaderPrivate::readersMap, and QuMultiReaderPrivate::srcs.
unsetSources()
void QuMultiReader::unsetSources ()
References QuMultiReaderPrivate::context.
Referenced by setSources().
The documentation for this class was generated from the following files:
qumultireader.h
qumultireader.cpp