cumbia-epics: CuMonitorActivity Class Reference
CuMonitorActivity Class Reference
#include <cumonitoractivity.h>
Public Types
enum Type { CuMonitorActivityType = CuActivity::User + 16 }
Public Member Functions
CuMonitorActivity (const CuData &token, CuEpCAService *ep_s, const CuVariant &argins=std::vector< std::string >())
~CuMonitorActivity ()
void setArgins (const CuVariant &argins)
void event_handler (evargs args)
void connection_handler (connection_handler_args args)
void exception_handler (struct exception_handler_args excargs)
bool matches (const CuData &token) const
void event (CuActivityEvent *e)
int getType () const
int repeat () const
Static Public Member Functions
static void event_handler_cb (evargs args)
static void connection_handler_cb (connection_handler_args args)
static void exception_handler_cb (struct exception_handler_args excargs)
Protected Member Functions
void init ()
void execute ()
void onExit ()
Member Enumeration Documentation
Type
enum CuMonitorActivity::Type
Enumerator
CuMonitorActivityType
Constructor & Destructor Documentation
CuMonitorActivity()
CuMonitorActivity::CuMonitorActivity (const CuData & token, CuEpCAService * ep_s, const CuVariant & argins = std::vector<std::string>())
References CuMonitorActivityPrivate::argins, CuMonitorActivityPrivate::device_srvc, CuMonitorActivityPrivate::errCnt, CuMonitorActivityPrivate::exiting, CuMonitorActivityPrivate::other_thread_id, and CuMonitorActivityPrivate::repeat.
~CuMonitorActivity()
CuMonitorActivity::~CuMonitorActivity ()
Member Function Documentation
connection_handler()
void CuMonitorActivity::connection_handler (connection_handler_args args)
References CuPV::ch_id, CuPV::dbfType, CuPV::dbrType, enumAsNr, event_handler_cb(), CuPV::nElems, CuPV::onceConnected, CuPV::reqElems, and CuPV::status.
Referenced by connection_handler_cb().
connection_handler_cb()
void CuMonitorActivity::connection_handler_cb (connection_handler_args args) static
References connection_handler(), and CuPV::monitor_activity.
Referenced by init().
event()
void CuMonitorActivity::event (CuActivityEvent * e)
References CuMonitorActivityPrivate::my_thread_id.
event_handler()
void CuMonitorActivity::event_handler (evargs args)
References CuPV::dbrType, CuEpicsWorld::error(), CuEpicsWorld::extractData(), CuEpicsWorld::fillThreadInfo(), CuEpicsWorld::getLastMessage(), CuPV::name, CuPV::nElems, CuPV::status, and CuPV::value.
Referenced by event_handler_cb().
event_handler_cb()
void CuMonitorActivity::event_handler_cb (evargs args) static
References event_handler(), and CuPV::monitor_activity.
Referenced by connection_handler().
exception_handler()
void CuMonitorActivity::exception_handler (struct exception_handler_args excargs)
References CuEpicsWorld::extractException().
Referenced by exception_handler_cb().
exception_handler_cb()
void CuMonitorActivity::exception_handler_cb (struct exception_handler_args excargs) static
References exception_handler().
Referenced by init().
execute()
void CuMonitorActivity::execute () protected
References CuMonitorActivityPrivate::my_thread_id.
getType()
int CuMonitorActivity::getType () const
References CuMonitorActivityType.
init()
void CuMonitorActivity::init () protected
References caTimeout, connection_handler_cb(), create_pvs(), DEFAULT_CA_TIMEOUT, exception_handler_cb(), CuPV::monitor_activity, CuMonitorActivityPrivate::my_thread_id, CuPV::onceConnected, CuMonitorActivityPrivate::other_thread_id, and CuMonitorActivityPrivate::repeat.
matches()
bool CuMonitorActivity::matches (const CuData & token) const
onExit()
void CuMonitorActivity::onExit () protected
References CuMonitorActivityPrivate::exiting, CuEpicsWorld::fillThreadInfo(), and CuMonitorActivityPrivate::my_thread_id.
repeat()
int CuMonitorActivity::repeat () const
References CuMonitorActivityPrivate::my_thread_id, and CuMonitorActivityPrivate::repeat.
setArgins()
void CuMonitorActivity::setArgins (const CuVariant & argins)
References CuMonitorActivityPrivate::argins.
The documentation for this class was generated from the following files:
cumonitoractivity.h
cumonitoractivity.cpp