cumbia-epics: CuMonitor Class Reference
CuMonitor Class Reference
#include <cumonitor.h>
Public Types
enum RefreshMode { MonitorRefresh = 0, Manual }
Public Types inherited from CuEpicsActionI
enum Type {
Reader = 0, Writer, MultiReader, MultiWriter,
AttConfig
}
Public Member Functions
CuMonitor (const EpSource &src, CumbiaEpics *ct)
~CuMonitor ()
void onProgress (int step, int total, const CuData &data)
void onResult (const CuData &data)
CuData getToken () const
EpSource getSource () const
CuEpicsActionI::Type getType () const
void sendData (const CuData &data)
void getData (CuData &inout) const
void setRefreshMode (RefreshMode rm)
RefreshMode refreshMode () const
void setPeriod (int millis)
int period () const
void start ()
void stop ()
void addDataListener (CuDataListener *l)
void removeDataListener (CuDataListener *l)
size_t dataListenersCount ()
Public Member Functions inherited from CuEpicsActionI
virtual ~CuEpicsActionI ()
Member Enumeration Documentation
RefreshMode
enum CuMonitor::RefreshMode
Enumerator
MonitorRefresh
Manual
Constructor & Destructor Documentation
CuMonitor()
CuMonitor::CuMonitor (const EpSource & src, CumbiaEpics * ct)
References CuMonitorPrivate::cumbia_e, CuMonitorPrivate::current_activity, CuMonitorPrivate::exit, CuMonitorPrivate::li, CuMonitorPrivate::log, MonitorRefresh, CuMonitorPrivate::period, CuMonitorPrivate::refresh_mode, and CuMonitorPrivate::tsrc.
~CuMonitor()
CuMonitor::~CuMonitor ()
Member Function Documentation
addDataListener()
void CuMonitor::addDataListener (CuDataListener * l) virtual
Implements CuEpicsActionI.
References CuMonitorPrivate::listeners.
dataListenersCount()
size_t CuMonitor::dataListenersCount () virtual
Implements CuEpicsActionI.
References CuMonitorPrivate::listeners.
getData()
void CuMonitor::getData (CuData & inout) const virtual
Implements CuEpicsActionI.
References CuMonitorPrivate::period, and CuMonitorPrivate::refresh_mode.
getSource()
EpSource CuMonitor::getSource () const virtual
Implements CuEpicsActionI.
References CuMonitorPrivate::tsrc.
getToken()
CuData CuMonitor::getToken () const
References EpSource::getName(), and CuMonitorPrivate::tsrc.
Referenced by stop().
getType()
CuEpicsActionI::Type CuMonitor::getType () const virtual
Implements CuEpicsActionI.
References CuEpicsActionI::Reader.
Referenced by onResult().
onProgress()
void CuMonitor::onProgress (int step, int total, const CuData & data)
onResult()
void CuMonitor::onResult (const CuData & data)
References CuActionFactoryService::CuActionFactoryServiceType, CuMonitorPrivate::cumbia_e, CuMonitorPrivate::current_activity, CuMonitorPrivate::exit, EpSource::getName(), getType(), CuMonitorPrivate::listeners, CuMonitorPrivate::tsrc, and CuActionFactoryService::unregisterAction().
period()
int CuMonitor::period () const
References CuMonitorPrivate::period.
refreshMode()
CuMonitor::RefreshMode CuMonitor::refreshMode () const
References CuMonitorPrivate::refresh_mode.
removeDataListener()
void CuMonitor::removeDataListener (CuDataListener * l) virtual
Implements CuEpicsActionI.
References CuMonitorPrivate::listeners, and stop().
sendData()
void CuMonitor::sendData (const CuData & data) virtual
Implements CuEpicsActionI.
References CuMonitorActivity::CuMonitorActivityType, CuMonitorPrivate::current_activity, CuMonitorPrivate::period, CuMonitorPrivate::refresh_mode, and setRefreshMode().
setPeriod()
void CuMonitor::setPeriod (int millis)
References CuMonitorPrivate::period.
Referenced by CuEpicsReaderFactory::create().
setRefreshMode()
void CuMonitor::setRefreshMode (CuMonitor::RefreshMode rm)
Referenced by CuEpicsReaderFactory::create(), and sendData().
start()
void CuMonitor::start () virtual
Implements CuEpicsActionI.
stop()
void CuMonitor::stop () virtual
Implements CuEpicsActionI.
References CuMonitorPrivate::cumbia_e, CuMonitorActivity::CuMonitorActivityType, CuMonitorPrivate::current_activity, CuMonitorPrivate::exit, getToken(), and CuMonitorPrivate::log.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cumonitor.h
cumonitor.cpp