cumbia-epics: cuepics-world.h File Reference
cuepics-world.h File Reference
#include <string>
#include <cudata.h>
#include <cadef.h>
#include <epicsTime.h>
Classes
struct CuPV
class CuEpicsWorld
Macros
#define stat_to_str(stat)
#define sevr_to_str(stat)
#define stat_to_str_unsigned(stat)
#define sevr_to_str_unsigned(stat)
#define DEFAULT_CA_PRIORITY 0 /* Default CA priority */
#define DEFAULT_CA_TIMEOUT 1.0 /* Default CA timeout */
Functions
char * val2str (const void *v, unsigned type, int index)
char * dbr2str (const void *value, unsigned type)
void print_time_val_sts (CuPV *CuPV, unsigned long reqElems)
int create_pvs (CuPV *pvs, int nPvs, caCh *pCB)
int connect_pvs (CuPV *pvs, int nPvs)
Variables
int tsSrcServer
int tsSrcClient
int enumAsNr
int charArrAsStr
double caTimeout
char dblFormatStr []
char fieldSeparator
capri caPriority
Macro Definition Documentation
DEFAULT_CA_PRIORITY
#define DEFAULT_CA_PRIORITY 0 /* Default CA priority */
DEFAULT_CA_TIMEOUT
#define DEFAULT_CA_TIMEOUT 1.0 /* Default CA timeout */
Referenced by CuMonitorActivity::init().
sevr_to_str
#define sevr_to_str (stat)
Value:
((stat) >= 0 && (stat) <= (signed)lastEpicsAlarmSev) ?  \
        epicsAlarmSeverityStrings[stat] : "??"
sevr_to_str_unsigned
#define sevr_to_str_unsigned (stat)
Value:
((stat) <= lastEpicsAlarmSev) ?         \
        epicsAlarmSeverityStrings[stat] : "??"
stat_to_str
#define stat_to_str (stat)
Value:
((stat) >= 0 && (stat) <= (signed)lastEpicsAlarmCond) ? \
        epicsAlarmConditionStrings[stat] : "??"
stat_to_str_unsigned
#define stat_to_str_unsigned (stat)
Value:
((stat) <= lastEpicsAlarmCond) ?        \
        epicsAlarmConditionStrings[stat] : "??"
Function Documentation
connect_pvs()
int connect_pvs (CuPV * pvs, int nPvs)
References caTimeout, and create_pvs().
create_pvs()
int create_pvs (CuPV * pvs, int nPvs, caCh * pCB)
References caPriority, and CuPV::status.
Referenced by connect_pvs(), and CuMonitorActivity::init().
dbr2str()
char* dbr2str (const void * value, unsigned type)
References DBR_PRINT_BUFFER_SIZE, PRN_DBR_CTRL, PRN_DBR_CTRL_PREC, PRN_DBR_GR, PRN_DBR_GR_PREC, PRN_DBR_STS, PRN_DBR_STSACK, PRN_DBR_TIME, PRN_DBR_X_ENUM, and TIMETEXTLEN.
print_time_val_sts()
void print_time_val_sts (CuPV * CuPV, unsigned long reqElems)
val2str()
char* val2str (const void * v, unsigned type, int index)
Variable Documentation
caPriority
capri caPriority
Referenced by create_pvs().
caTimeout
double caTimeout
Referenced by connect_pvs(), and CuMonitorActivity::init().
charArrAsStr
int charArrAsStr
dblFormatStr
char dblFormatStr[]
enumAsNr
int enumAsNr
Referenced by CuMonitorActivity::connection_handler().
fieldSeparator
char fieldSeparator
tsSrcClient
int tsSrcClient
tsSrcServer
int tsSrcServer