qumbia-epics-controls: TLabelBoolEditor Class Reference
TLabelBoolEditor Class Reference
#include <tlabelbooleditor.h>
Signals
void propertyChanged (const QString &propName, const QVariant &val)
Public Member Functions
TLabelBoolEditor (QString, QString, QColor, QColor, QWidget *=NULL)
virtual ~TLabelBoolEditor ()
Public Attributes
Ui::TLabelBoolEditor ui
Protected Slots
void accept ()
Constructor & Destructor Documentation
TLabelBoolEditor()
TLabelBoolEditor::TLabelBoolEditor (QString ts, QString fs, QColor tc, QColor fc, QWidget * parent = NULL)
References Ui_TLabelBoolEditor::lineEditFalse, Ui_TLabelBoolEditor::lineEditTrue, Ui_TLabelBoolEditor::pushColorFalse, Ui_TLabelBoolEditor::pushColorTrue, Ui_TLabelBoolEditor::setupUi(), and ui.
~TLabelBoolEditor()
virtual TLabelBoolEditor::~TLabelBoolEditor () inline virtual
Member Function Documentation
accept
void TLabelBoolEditor::accept () protected slot
References Ui_TLabelBoolEditor::lineEditFalse, Ui_TLabelBoolEditor::lineEditTrue, propertyChanged(), Ui_TLabelBoolEditor::pushColorFalse, Ui_TLabelBoolEditor::pushColorTrue, and ui.
propertyChanged
void TLabelBoolEditor::propertyChanged (const QString & propName, const QVariant & val) signal
Referenced by accept().
Member Data Documentation
ui
Ui::TLabelBoolEditor TLabelBoolEditor::ui
Referenced by accept(), and TLabelBoolEditor().
The documentation for this class was generated from the following files:
tlabelbooleditor.h
tlabelbooleditor.cpp