qumbia-epics-controls: CuEpReaderFactory Class Reference
CuEpReaderFactory Class Reference
#include <cuepcontrolsreader.h>
Public Member Functions
CuEpReaderFactory ()
virtual ~CuEpReaderFactory ()
CuControlsReaderA * create (Cumbia *c, CuDataListener *l) const
CuControlsReaderFactoryI * clone () const
void setOptions (const CuData &options)
Constructor & Destructor Documentation
CuEpReaderFactory()
CuEpReaderFactory::CuEpReaderFactory ()
Referenced by clone().
~CuEpReaderFactory()
CuEpReaderFactory::~CuEpReaderFactory () virtual
Member Function Documentation
clone()
CuControlsReaderFactoryI * CuEpReaderFactory::clone () const
References CuEpReaderFactory(), and CuEpReaderFactoryPrivate::r_options.
create()
CuControlsReaderA * CuEpReaderFactory::create (Cumbia * c, CuDataListener * l) const
References CuEpReaderFactoryPrivate::r_options, and CuEpControlsReader::setOptions().
setOptions()
void CuEpReaderFactory::setOptions (const CuData & options)
References CuEpReaderFactoryPrivate::r_options.
The documentation for this class was generated from the following files:
cuepcontrolsreader.h
cuepcontrolsreader.cpp