qumbia-epics-controls: TLedBoolEditor Class Reference
TLedBoolEditor Class Reference
#include <tledbooleditor.h>
Signals
void propertyChanged (const QString &propName, const QVariant &val)
Public Member Functions
TLedBoolEditor (QColor, QColor, QWidget *=NULL)
virtual ~TLedBoolEditor ()
Public Attributes
Ui::TLedBoolEditor ui
Protected Slots
void accept ()
Constructor & Destructor Documentation
TLedBoolEditor()
TLedBoolEditor::TLedBoolEditor (QColor tc, QColor fc, QWidget * parent = NULL)
References Ui_TLedBoolEditor::pushColorFalse, Ui_TLedBoolEditor::pushColorTrue, Ui_TLedBoolEditor::setupUi(), and ui.
~TLedBoolEditor()
virtual TLedBoolEditor::~TLedBoolEditor () inline virtual
Member Function Documentation
accept
void TLedBoolEditor::accept () protected slot
References propertyChanged(), and ui.
propertyChanged
void TLedBoolEditor::propertyChanged (const QString & propName, const QVariant & val) signal
Referenced by accept().
Member Data Documentation
ui
Ui::TLedBoolEditor TLedBoolEditor::ui
Referenced by accept(), and TLedBoolEditor().
The documentation for this class was generated from the following files:
tledbooleditor.h
tledbooleditor.cpp