qumbia-epics-controls: CuEpControlsReader Class Reference
CuEpControlsReader Class Reference
#include <cuepcontrolsreader.h>
Public Member Functions
CuEpControlsReader (Cumbia *cumbia_epics, CuDataListener *tl)
virtual ~CuEpControlsReader ()
void setSource (const QString &s)
QString source () const
void unsetSource ()
void setOptions (const CuData &o)
void sendData (const CuData &d)
void getData (CuData &d_ino) const
Constructor & Destructor Documentation
CuEpControlsReader()
CuEpControlsReader::CuEpControlsReader (Cumbia * cumbia_epics, CuDataListener * tl)
References CuEpControlsReaderPrivate::cumbia_ep.
~CuEpControlsReader()
CuEpControlsReader::~CuEpControlsReader () virtual
References unsetSource().
Member Function Documentation
getData()
void CuEpControlsReader::getData (CuData & d_ino) const
References CuEpControlsReaderPrivate::cumbia_ep, and CuEpControlsReaderPrivate::source.
sendData()
void CuEpControlsReader::sendData (const CuData & d)
References CuEpControlsReaderPrivate::cumbia_ep, and CuEpControlsReaderPrivate::source.
setOptions()
void CuEpControlsReader::setOptions (const CuData & o)
References CuEpControlsReaderPrivate::read_options.
Referenced by CuEpReaderFactory::create().
setSource()
void CuEpControlsReader::setSource (const QString & s)
References CuEpControlsReaderPrivate::cumbia_ep, CuEpControlsReaderPrivate::read_options, CuEpControlsUtils::replaceWildcards(), CuEpControlsReaderPrivate::source, and CuEpControlsReaderPrivate::tlistener.
source()
QString CuEpControlsReader::source () const
References CuEpControlsReaderPrivate::source.
unsetSource()
void CuEpControlsReader::unsetSource ()
References CuEpControlsReaderPrivate::cumbia_ep, CuEpControlsReaderPrivate::source, and CuEpControlsReaderPrivate::tlistener.
Referenced by ~CuEpControlsReader().
The documentation for this class was generated from the following files:
cuepcontrolsreader.h
cuepcontrolsreader.cpp