qumbia-epics-controls: TTableBoolEditor Class Reference
TTableBoolEditor Class Reference
#include <ttablebooleditor.h>
Signals
void propertyChanged (const QString &propName, const QVariant &val)
Public Member Functions
TTableBoolEditor (int, int, QString, QString, QString, QString, QString, QWidget *=NULL)
virtual ~TTableBoolEditor ()
Public Attributes
Ui::TTableBoolEditor ui
Protected Slots
void accept ()
Constructor & Destructor Documentation
TTableBoolEditor()
TTableBoolEditor::TTableBoolEditor (int rows, int columns, QString ts, QString fs, QString tc, QString fc, QString dm, QWidget * parent = NULL)
References Ui_TTableBoolEditor::eFlagFalse, Ui_TTableBoolEditor::eFlagTrue, Ui_TTableBoolEditor::lineEditFalse, Ui_TTableBoolEditor::lineEditTrue, Ui_TTableBoolEditor::lineMask, Ui_TTableBoolEditor::pushApply, Ui_TTableBoolEditor::pushColorFalse, Ui_TTableBoolEditor::pushColorTrue, Ui_TTableBoolEditor::setupUi(), Ui_TTableBoolEditor::spinColumn, Ui_TTableBoolEditor::spinNumColumns, Ui_TTableBoolEditor::spinNumRows, Ui_TTableBoolEditor::spinRow, and ui.
~TTableBoolEditor()
virtual TTableBoolEditor::~TTableBoolEditor () inline virtual
Member Function Documentation
accept
void TTableBoolEditor::accept () protected slot
References Ui_TTableBoolEditor::eFlagFalse, Ui_TTableBoolEditor::eFlagTrue, propertyChanged(), and ui.
propertyChanged
void TTableBoolEditor::propertyChanged (const QString & propName, const QVariant & val) signal
Referenced by accept().
Member Data Documentation
ui
Ui::TTableBoolEditor TTableBoolEditor::ui
Referenced by accept(), and TTableBoolEditor().
The documentation for this class was generated from the following files:
ttablebooleditor.h
ttablebooleditor.cpp