qumbia-epics-controls: MyReadLabel Class Reference
MyReadLabel Class Reference
#include <label.h>
Public Member Functions
MyReadLabel (QWidget *parent, Cumbia *cumbia, const CuControlsReaderFactoryI &r_fac)
virtual ~MyReadLabel ()
void setSource (const QString &src)
void contextMenuEvent (QContextMenuEvent *)
void onUpdate (const CuData &data)
Constructor & Destructor Documentation
MyReadLabel()
MyReadLabel::MyReadLabel (QWidget * parent, Cumbia * cumbia, const CuControlsReaderFactoryI & r_fac) inline
~MyReadLabel()
virtual MyReadLabel::~MyReadLabel () inline virtual
Member Function Documentation
contextMenuEvent()
void MyReadLabel::contextMenuEvent (QContextMenuEvent *) inline
References setSource().
onUpdate()
void MyReadLabel::onUpdate (const CuData & data) inline
setSource()
void MyReadLabel::setSource (const QString & src) inline
Referenced by contextMenuEvent(), and WidgetWithLabel::WidgetWithLabel().
The documentation for this class was generated from the following file:
label.h