qumbia-epics-controls: PointEditor Class Reference
PointEditor Class Reference
#include <pointeditor.h>
Public Member Functions
PointEditor (QWidget *parent, const QString &defaultTxt)
QString point ()
QLabel * textLabel () const
Protected Slots
void accept ()
void commandSwitch (bool)
void comboChanged (int)
Constructor & Destructor Documentation
PointEditor()
PointEditor::PointEditor (QWidget * parent, const QString & defaultTxt)
References accept(), comboChanged(), and commandSwitch().
Member Function Documentation
accept
void PointEditor::accept () protected slot
Referenced by PointEditor().
comboChanged
void PointEditor::comboChanged (int i) protected slot
References point().
Referenced by PointEditor().
commandSwitch
void PointEditor::commandSwitch (bool cmd) protected slot
References point().
Referenced by PointEditor().
point()
QString PointEditor::point () inline
Referenced by comboChanged(), commandSwitch(), and DropEventFilter::eventFilter().
textLabel()
QLabel * PointEditor::textLabel () const inline
Referenced by DropEventFilter::eventFilter().
The documentation for this class was generated from the following files:
pointeditor.h
pointeditor.cpp