qumbia-epics-controls: qrc_cutangoqtcontrolsplugin.cpp File Reference
qrc_cutangoqtcontrolsplugin.cpp File Reference
Macros
#define QT_RCC_PREPEND_NAMESPACE(name) name
#define QT_RCC_MANGLE_NAMESPACE(name) name
Functions
bool qRegisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
bool qUnregisterResourceData (int, const unsigned char *, const unsigned char *, const unsigned char *)
int QT_RCC_MANGLE_NAMESPACE() qInitResources_cutangoqtcontrolsplugin ()
int QT_RCC_MANGLE_NAMESPACE() qCleanupResources_cutangoqtcontrolsplugin ()
Variables
static const unsigned char qt_resource_data []
static const unsigned char qt_resource_name []
static const unsigned char qt_resource_struct []
Macro Definition Documentation
QT_RCC_MANGLE_NAMESPACE
#define QT_RCC_MANGLE_NAMESPACE (name) name
QT_RCC_PREPEND_NAMESPACE
#define QT_RCC_PREPEND_NAMESPACE (name) name
Function Documentation
qCleanupResources_cutangoqtcontrolsplugin()
int QT_RCC_MANGLE_NAMESPACE() qCleanupResources_cutangoqtcontrolsplugin ()
References QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, qt_resource_struct, and qUnregisterResourceData().
qInitResources_cutangoqtcontrolsplugin()
int QT_RCC_MANGLE_NAMESPACE() qInitResources_cutangoqtcontrolsplugin ()
References qRegisterResourceData(), QT_RCC_PREPEND_NAMESPACE, qt_resource_data, qt_resource_name, and qt_resource_struct.
qRegisterResourceData()
bool qRegisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qInitResources_cutangoqtcontrolsplugin().
qUnregisterResourceData()
bool qUnregisterResourceData (int , const unsigned char * , const unsigned char * , const unsigned char *)
Referenced by qCleanupResources_cutangoqtcontrolsplugin().
Variable Documentation
qt_resource_data
const unsigned char qt_resource_data[] static
Referenced by qCleanupResources_cutangoqtcontrolsplugin(), and qInitResources_cutangoqtcontrolsplugin().
qt_resource_name
const unsigned char qt_resource_name[] static
Referenced by qCleanupResources_cutangoqtcontrolsplugin(), and qInitResources_cutangoqtcontrolsplugin().
qt_resource_struct
const unsigned char qt_resource_struct[] static
Initial value:
= {
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x1,
  0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x5,0x0,0x0,0x0,0x2,
  0x0,0x0,0x0,0x48,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x7,0x25,
  0x0,0x0,0x0,0x6c,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x9,0x1b,
  0x0,0x0,0x0,0x30,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x3,0x80,
  0x0,0x0,0x0,0x14,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0x0,0x0,
  0x0,0x0,0x0,0x92,0x0,0x0,0x0,0x0,0x0,0x1,0x0,0x0,0xd,0x44,
}
Referenced by qCleanupResources_cutangoqtcontrolsplugin(), and qInitResources_cutangoqtcontrolsplugin().