cumbia-random: CuRNDReader Class Reference
CuRNDReader Class Reference
#include <curndreader.h>
Public Member Functions
CuRNDReader (Cumbia *cumbia_tango, CuDataListener *tl)
virtual ~CuRNDReader ()
void setSource (const QString &s)
QString source () const
void unsetSource ()
void setOptions (const CuData &o)
CuData getOptions () const
virtual void sendData (const CuData &d)
virtual void getData (CuData &d_ino) const
Constructor & Destructor Documentation
CuRNDReader()
CuRNDReader::CuRNDReader (Cumbia * cumbia_tango, CuDataListener * tl)
References CumbiaRandom::CumbiaRNDType.
~CuRNDReader()
CuRNDReader::~CuRNDReader () virtual
References unsetSource().
Member Function Documentation
getData()
void CuRNDReader::getData (CuData & d_ino) const virtual
References CuRNDActionI::getData(), and CuRNDActionI::Reader.
getOptions()
CuData CuRNDReader::getOptions () const
sendData()
void CuRNDReader::sendData (const CuData & d) virtual
References CuRNDActionI::Reader, and CuRNDActionI::sendData().
setOptions()
void CuRNDReader::setOptions (const CuData & o)
Referenced by CuRNDReaderFactory::create().
setSource()
void CuRNDReader::setSource (const QString & s)
References RndSourceBuilder::fromSource(), RndSourceBuilder::options, and CuRNDActionReaderFactory::setOptions().
source()
QString CuRNDReader::source () const
unsetSource()
void CuRNDReader::unsetSource ()
References CuRNDActionI::Reader.
Referenced by ~CuRNDReader().
The documentation for this class was generated from the following files:
curndreader.h
curndreader.cpp