cumbia-random: CuRNDActionReader Class Reference
CuRNDActionReader Class Reference
Low level class to read tango attributes and commands with output arguments.
#include <curndactionreader.h>
Public Types
enum RefreshMode { RandomGenerator = 0 }
The reader refresh mode.
Public Types inherited from CuRNDActionI
enum Type {
Reader = 0, Writer, AttConfig, DbReadProp,
DbWriteProp
}
Public Member Functions
CuRNDActionReader (const RNDSource &src, CumbiaRandom *ct)
~CuRNDActionReader ()
void onProgress (int step, int total, const CuData &data)
progress notification callback
void onResult (const CuData &data)
void onResult (const std::vector< CuData > &datalist)
void setOptions (const CuData &options)
CuData getToken () const
returns the CuData storing the token that identifies this action
RNDSource getSource () const
CuRNDActionI::Type getType () const
returns the type of CuRNDActionI implemented
void sendData (const CuData &data)
Send data with parameters to configure the reader.
void getData (CuData &inout) const
Get parameters from the reader.
void setRefreshMode (RefreshMode rm)
set or change the reader's refresh mode
std::string refreshModeStr () const
RefreshMode refreshMode () const
void setPeriod (int millis)
int period () const
void start ()
the method where activities are created and registered
void stop ()
the method where activities are unregistered from Cumbia
void addDataListener (CuDataListener *l)
insert a CuDataListener to the list of listeners of data updates
void removeDataListener (CuDataListener *l)
remove a CuDataListener from the list of listeners of data updates
size_t dataListenersCount ()
return the number of registered data listeners
bool exiting () const
returns true if the action has been stopped and it's exiting
bool isEventRefresh (RefreshMode rm) const
returns true if the parameter is an event driven RefreshMode, false otherwise.
Public Member Functions inherited from CuRNDActionI
CuRNDActionI ()
virtual ~CuRNDActionI ()
virtual destructor, to make compilers happy
Detailed Description
Low level class to read tango attributes and commands with output arguments.
This class implements the CuRNDActionI interface, which in turn implements CuThreadListener.
Programmers of graphical interfaces should employ cumbia-tango-controls CuTControlsReader higher level class to create and communicate with CuTReader.
Function
Instantiates and registers (i.e. starts) either a CuEventActivity or a CuPollingActivity, according to the desired RefreshMode. If the CuEventActivity fails subscribing to the Tango event system, it is replaced by CuPollingActivity (in CuTReader::onResult). In that case, no error event is delivered to CuDataListeners.
Note
CuTReader holds a pointer to the current activity (CuTReaderPrivate: current_activity). Activity and CuTReader's life are independent from each other: if the CuActivity::CuADeleteOnExit flag is active (as in CuPollingActivity), the activity is deleted by CuThread.
Important
As a consequence of the note above, activities must not exit before CuTReader::stop is called. The proper way to stop the activity associated to the reader is through CuTReader::stop.
Member Enumeration Documentation
RefreshMode
enum CuRNDActionReader::RefreshMode
The reader refresh mode.
Each refresh mode reflects the way a tango attribute can be read. Commands are always polled with a given period (default: 1000ms). The preferred read mode for attributes is by events (ChangeEventRefresh). If they are not available, the second choice mode is PolledRefresh.
Manual mode starts (or switches to) a polling activity that is immediately paused. A specific argument must be specified to sendData to trigger a manual reading.
Enumerator
RandomGenerator
Constructor & Destructor Documentation
CuRNDActionReader()
CuRNDActionReader::CuRNDActionReader (const RNDSource & src, CumbiaRandom * ct)
References RandomGenerator.
~CuRNDActionReader()
CuRNDActionReader::~CuRNDActionReader ()
Member Function Documentation
addDataListener()
void CuRNDActionReader::addDataListener (CuDataListener * l) virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implements CuRNDActionI.
dataListenersCount()
size_t CuRNDActionReader::dataListenersCount () virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implements CuRNDActionI.
exiting()
bool CuRNDActionReader::exiting () const virtual
returns true if the action has been stopped and it's exiting
Returns
true if the action is exiting (normally, stop has been called), false otherwise
Used by CuActionFactoryService::unregisterAction to check whether the action is still running before unregistering.
Implements CuRNDActionI.
getData()
void CuRNDActionReader::getData (CuData & d_inout) const virtual
Get parameters from the reader.
Parameters
d_inout a reference to a CuData bundle containing the parameter names as keys. getData will associate the values to the keys. Unrecognized keys are ignored.
Valid keys
"period": returns an int with the polling period
"refresh_mode": returns a CuRNDActionReader::RefreshMode that can be converted to int
"mode": returns a string representation of the CuRNDActionReader::RefreshMode
See also
sendData
Implements CuRNDActionI.
References refreshModeStr().
getSource()
RNDSource CuRNDActionReader::getSource () const virtual
returns the tango source (TSource)
Returns
a TSource object that describes the Tango source
Implements CuRNDActionI.
getToken()
CuData CuRNDActionReader::getToken () const virtual
returns the CuData storing the token that identifies this action
Returns
a CuData with the following key/value pairs
"source" --> the name of the source (string)
"type" --> a constant string: "reader"
Reimplemented from CuRNDActionI.
getType()
CuRNDActionI::Type CuRNDActionReader::getType () const virtual
returns the type of CuRNDActionI implemented
Returns
one of the values from the Type enum
Implements CuRNDActionI.
References CuRNDActionI::Reader.
Referenced by onResult().
isEventRefresh()
bool CuRNDActionReader::isEventRefresh (CuRNDActionReader::RefreshMode rm) const
returns true if the parameter is an event driven RefreshMode, false otherwise.
Parameters
rm a value picked from CuRNDActionReader::RefreshMode enumeration
Returns
true if rm is ChangeEventRefresh, PeriodicEventRefresh or ArchiveEventRefresh, false otherwise
onProgress()
void CuRNDActionReader::onProgress (int step, int total, const CuData & data) virtual
progress notification callback
Parameters
step the completed steps in the background
total the total number of steps
data CuData with data from the background activity
The current implementation does nothing
Reimplemented from CuRNDActionI.
onResult() [1/2]
void CuRNDActionReader::onResult (const CuData & data) virtual
Reimplemented from CuRNDActionI.
References CuRNDActionFactoryService::CuRNDActionFactoryServiceType, getType(), and CuRNDActionFactoryService::unregisterAction().
onResult() [2/2]
void CuRNDActionReader::onResult (const std::vector< CuData > & datalist) virtual
Reimplemented from CuRNDActionI.
period()
int CuRNDActionReader::period () const
refreshMode()
CuRNDActionReader::RefreshMode CuRNDActionReader::refreshMode () const
refreshModeStr()
string CuRNDActionReader::refreshModeStr () const
References RandomGenerator.
Referenced by getData().
removeDataListener()
void CuRNDActionReader::removeDataListener (CuDataListener * l) virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implements CuRNDActionI.
References stop().
sendData()
void CuRNDActionReader::sendData (const CuData & data) virtual
Send data with parameters to configure the reader.
Parameters
data a CuData bundle with the settings to apply to the reader.
Valid keys
"period": integer. Change the polling period, if the refresh mode is CuRNDActionReader::PolledRefresh
"refresh_mode". A CuRNDActionReader::RefreshMode value to change the current refresh mode.
"read" (value is irrelevant). If the read mode is CuRNDActionReader::PolledRefresh, a read will be performed.
See also
getData
Implements CuRNDActionI.
setOptions()
void CuRNDActionReader::setOptions (const CuData & options)
Referenced by CuRNDActionReaderFactory::create().
setPeriod()
void CuRNDActionReader::setPeriod (int millis)
setRefreshMode()
void CuRNDActionReader::setRefreshMode (CuRNDActionReader::RefreshMode rm)
set or change the reader's refresh mode
If the reading activity hasn't been started yet, the mode is saved for later. If an activity is already running and the requested mode is different, the current activity is unregistered and a new one is started.
Parameters
rm a value chosen from CuRNDActionReader::RefreshMode.
start()
void CuRNDActionReader::start () virtual
the method where activities are created and registered
This is the place where activities are created and registered to Cumbia through the method Cumbia::registerActivity.
Examples
CuTReader::start
CuTWriter::start
See also Cumbia::registerActivity
Implements CuRNDActionI.
stop()
void CuRNDActionReader::stop () virtual
the method where activities are unregistered from Cumbia
This is the place where activities are unregistered from Cumbia by the Cumbia::unregisterActivity method
Examples
CuTReader::stop
CuTWriter::stop
See also Cumbia::unregisterActivity
Implements CuRNDActionI.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
curndactionreader.h
curndactionreader.cpp