cumbia-random: CuRNDActionFactoryService Class Reference
CuRNDActionFactoryService Class Reference
implements CuServiceI interface and provides a service to register, unregister and find Websocket actions
#include <curndactionfactoryservice.h>
Public Types
enum Type { CuRNDActionFactoryServiceType = CuServices::User + 25 }
Public Member Functions
CuRNDActionFactoryService ()
the class constructor
virtual ~CuRNDActionFactoryService ()
CuRNDActionI * registerAction (const std::string &src, const CuRNDActionFactoryI &f, CumbiaRandom *ct)
Create and register a new action if an action with the same source and type is not already running.
CuRNDActionI * findActive (const std::string &name, CuRNDActionI::Type at)
find an active action given the source name and the action type
std::vector< CuRNDActionI * > find (const std::string &name, CuRNDActionI::Type at)
find an action given its source and type
size_t count () const
return the number of registered actions
void unregisterAction (const std::string &src, CuRNDActionI::Type at)
Unregister the action with the given source and type if the action's exiting() method returns true.
void cleanup ()
all registered actions are deleted and removed from the service internal list.
std::string getName () const
returns the service name
CuServices::Type getType () const
returns the service type
Detailed Description
implements CuServiceI interface and provides a service to register, unregister and find Websocket actions
Note
This service is internally used by CumbiaRandom and clients of the library should rarely need to use it.
This class is a cumbia service (implements getName and getType). It is registered by CumbiaTango at construction time through the cumbia service provider, namely CuServiceProvider:
getServiceProvider()->registerService(static_cast<CuServices::Type> (CuActionFactoryService::CuActionFactoryServiceType), new CuActionFactoryService());
A reference to the service can be obtained through the Cumbia::getServiceProvider method:
CuActionFactoryService *af =
         static_cast<CuActionFactoryService *>(getServiceProvider()->get(static_cast<CuServices::Type> (CuActionFactoryService::CuActionFactoryServiceType)));
Through the service provider, the service can be unregistered with CuServiceProvider::unregisterService
Once the service is registered, new CuRNDActionI (CuTReader, CuTWriter) can be added through registerAction, removed with unregisterAction and searched with find and findActive. The count method returns the number of registered actions.
Tango sources (for readers) and targets (for writers) with the same name and type, share the same CuRNDActionI. See the registerAction documentation for further details.
Member Enumeration Documentation
Type
enum CuRNDActionFactoryService::Type
Enumerator
CuRNDActionFactoryServiceType
Constructor & Destructor Documentation
CuRNDActionFactoryService()
CuRNDActionFactoryService::CuRNDActionFactoryService ()
the class constructor
~CuRNDActionFactoryService()
CuRNDActionFactoryService::~CuRNDActionFactoryService () virtual
Member Function Documentation
cleanup()
void CuRNDActionFactoryService::cleanup ()
all registered actions are deleted and removed from the service internal list.
All references to the registered actions are removed from the service internal list, whether or not CuRNDActionI::exiting returns true
Note
The action is deleted.
count()
size_t CuRNDActionFactoryService::count () const
return the number of registered actions
Returns
the number of registered actions.
Actions are added with registerAction and removed with unregisterAction
find()
std::vector< CuRNDActionI * > CuRNDActionFactoryService::find (const std::string & name, CuRNDActionI::Type at)
find an action given its source and type
Parameters
src the complete source (target) name (no wildcard)
at the action type (Reader, Writer, AttConfig, ...)
Returns
a list of actions with the given src and type.
Note
Multiple actions can be found with the given src and type. This is likely to happen when a new action is registered, stopped and registered again with the same src in a short time. In this case, we end up with a not active action and an active one with the same src.
Note
To find active actions (whose stop method hasn't been called yet), use findActive
Referenced by CumbiaRandom::unlinkListener().
findActive()
CuRNDActionI * CuRNDActionFactoryService::findActive (const std::string & name, CuRNDActionI::Type at)
find an active action given the source name and the action type
Parameters
src the complete source (target) name (no wildcard)
at the action type (Reader, Writer, AttConfig, ...)
Returns
the active action with the given src and type.
Note
An action is active as long as CuRNDActionI::exiting returns false. Usually, an action is marked as exiting when CuRNDActionI::stop is called. For example, see CuTReader::stop and CuTWriter::stop An action can be stopped when a data listener is removed, as in CuTReader::removeDataListener and CuTWriter::removeDataListener. CuTReader::removeDataListener and CuTWriter::removeDataListener are invoked by CumbiaTango::unlinkListener. qumbia-tango-controls CuTControlsReader (CuTControlsWriter) and qumbia-epics-controls CuEpControlsReader (CuEpControlsWriter) call CumbiaTango::unlinkListener from within unsetSource (unsetTarget for writers).
This sequence is an example if you ever need to deal with stopping and unregistering an action from a client.
Referenced by CumbiaRandom::addAction(), and CumbiaRandom::findAction().
getName()
std::string CuRNDActionFactoryService::getName () const
returns the service name
Returns
the constant string "*CuRNDActionFactoryService" identifying this type of service.
Implements CuServiceI::getName pure virtual method
getType()
CuServices::Type CuRNDActionFactoryService::getType () const
returns the service type
Returns
the value defined in cuactionfactoryservice.h by the enum Type (CuRNDActionFactoryServiceType = CuServices::User + 25)
See also
Type
Implements CuRNDActionI::getType pure virtual method
References CuRNDActionFactoryServiceType.
registerAction()
CuRNDActionI * CuRNDActionFactoryService::registerAction (const std::string & src, const CuRNDActionFactoryI & f, CumbiaRandom * ct)
Create and register a new action if an action with the same source and type is not already running.
Rules
same source, different CuRNDActionI type: two distinct actions.
Share actions of the same type among sources with the same name.
If an action with the same source and type exists, but is stopping, it is discarded and a new action is created.
See also
findAction
unregisterAction
References CuRNDActionFactoryI::create(), and CuRNDActionFactoryI::getType().
Referenced by CumbiaRandom::addAction().
unregisterAction()
void CuRNDActionFactoryService::unregisterAction (const std::string & src, CuRNDActionI::Type at)
Unregister the action with the given source and type if the action's exiting() method returns true.
Parameters
src the complete source name (no wildcards)
at the action type (Reader, Writer, AttConfig, ...)
if an action with the given source (target) and type is found and the action is exiting (CuRNDActionI::exiting returns false), it is removed from the internal list of actions.
If CuRNDActionI::exiting returns false, the action is not removed.
Note
The action is not deleted. CuTReader and CuTWriter auto delete themselves from within CuTReader::onResult and CuTWriter::onResult when the exiting flag is true.
Referenced by CuRNDActionReader::onResult().
The documentation for this class was generated from the following files:
curndactionfactoryservice.h
curndactionfactoryservice.cpp