cumbia-random: CuRNDReaderFactory Class Reference
CuRNDReaderFactory Class Reference
#include <curndreader.h>
Public Member Functions
CuRNDReaderFactory ()
virtual ~CuRNDReaderFactory ()
CuControlsReaderA * create (Cumbia *c, CuDataListener *l) const
virtual void setOptions (const CuData &options)
CuControlsReaderFactoryI * clone () const
Constructor & Destructor Documentation
CuRNDReaderFactory()
CuRNDReaderFactory::CuRNDReaderFactory ()
Referenced by clone().
~CuRNDReaderFactory()
CuRNDReaderFactory::~CuRNDReaderFactory () virtual
Member Function Documentation
clone()
CuControlsReaderFactoryI * CuRNDReaderFactory::clone () const
References CuRNDReaderFactory(), and setOptions().
create()
CuControlsReaderA * CuRNDReaderFactory::create (Cumbia * c, CuDataListener * l) const
References CuRNDReader::setOptions().
setOptions()
void CuRNDReaderFactory::setOptions (const CuData & options) virtual
Referenced by clone().
The documentation for this class was generated from the following files:
curndreader.h
curndreader.cpp