cumbia-random: CuRNDActionI Class Reference
CuRNDActionI Class Reference abstract
#include <curndactioni.h>
Public Types
enum Type {
Reader = 0, Writer, AttConfig, DbReadProp,
DbWriteProp
}
Public Member Functions
CuRNDActionI ()
virtual ~CuRNDActionI ()
virtual destructor, to make compilers happy
virtual RNDSource getSource () const =0
return a RNDSource object that stores information about the Tango source
virtual Type getType () const =0
returns the type of CuRNDActionI implemented
virtual void addDataListener (CuDataListener *l)=0
insert a CuDataListener to the list of listeners of data updates
virtual void removeDataListener (CuDataListener *l)=0
remove a CuDataListener from the list of listeners of data updates
virtual size_t dataListenersCount ()=0
return the number of registered data listeners
virtual void start ()=0
the method where activities are created and registered
virtual void stop ()=0
the method where activities are unregistered from Cumbia
virtual void sendData (const CuData &data)=0
subclasses will implement the necessary code to set data on themselves or to the activities
virtual void getData (CuData &d_inout) const =0
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
virtual bool exiting () const =0
returns true if the action has been stopped and it's exiting
virtual void onProgress (int step, int total, const CuData &data)
virtual void onResult (const CuData &data)
virtual void onResult (const std::vector< CuData > &datalist)
virtual CuData getToken () const
Member Enumeration Documentation
Type
enum CuRNDActionI::Type
Enumerator
Reader
Writer
AttConfig
DbReadProp
DbWriteProp
Constructor & Destructor Documentation
CuRNDActionI()
CuRNDActionI::CuRNDActionI ()
~CuRNDActionI()
virtual CuRNDActionI::~CuRNDActionI () inline virtual
virtual destructor, to make compilers happy
Member Function Documentation
addDataListener()
virtual void CuRNDActionI::addDataListener (CuDataListener * l) pure virtual
insert a CuDataListener to the list of listeners of data updates
Parameters
l a CuDataListener that receives notifications when data is ready, through CuDataListener::onUpdate
Implemented in CuRNDActionReader.
Referenced by CumbiaRandom::addAction().
dataListenersCount()
virtual size_t CuRNDActionI::dataListenersCount () pure virtual
return the number of registered data listeners
Returns
the number of data listeners currently installed
Implemented in CuRNDActionReader.
exiting()
virtual bool CuRNDActionI::exiting () const pure virtual
returns true if the action has been stopped and it's exiting
Returns
true if the action is exiting (normally, stop has been called), false otherwise
Used by CuActionFactoryService::unregisterAction to check whether the action is still running before unregistering.
Implemented in CuRNDActionReader.
getData()
virtual void CuRNDActionI::getData (CuData & d_inout) const pure virtual
subclasses will implement the necessary code to analyze the request stored in the input argument and fill it in with output data
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation as input argument. data will contain additional output fields filled in by the method when it returns.
note
getData must be synchronous: it's called with input arguments (d_inout) and they are filled in within the same method in the same thread. Asynchronous data fetch from an activity executed in a separate thread can be accomplished by sendData in combination with CuDataListener::onUpdate. There, received data will have to be recognised as coming from a specific request and treated accordingly.
Implemented in CuRNDActionReader.
Referenced by CuRNDReader::getData().
getSource()
virtual RNDSource CuRNDActionI::getSource () const pure virtual
return a RNDSource object that stores information about the Tango source
Returns
RNDSource, an object storing information on the Tango source
Implemented in CuRNDActionReader.
getToken()
CuData CuRNDActionI::getToken () const virtual
Reimplemented in CuRNDActionReader.
getType()
virtual Type CuRNDActionI::getType () const pure virtual
returns the type of CuRNDActionI implemented
Returns
one of the values from the Type enum
Implemented in CuRNDActionReader.
onProgress()
void CuRNDActionI::onProgress (int step, int total, const CuData & data) virtual
Reimplemented in CuRNDActionReader.
onResult() [1/2]
void CuRNDActionI::onResult (const CuData & data) virtual
Reimplemented in CuRNDActionReader.
onResult() [2/2]
void CuRNDActionI::onResult (const std::vector< CuData > & datalist) virtual
Reimplemented in CuRNDActionReader.
removeDataListener()
virtual void CuRNDActionI::removeDataListener (CuDataListener * l) pure virtual
remove a CuDataListener from the list of listeners of data updates
Parameters
l a CuDataListener that will be removed from the list of listeners
Implemented in CuRNDActionReader.
sendData()
virtual void CuRNDActionI::sendData (const CuData & data) pure virtual
subclasses will implement the necessary code to set data on themselves or to the activities
Parameters
data a CuData compiled with the necessary fields accepted by the specific implementation
The data can be set locally on the object implementing this interface or can be forwarded to the activity by means of Cumbia::postEvent carrying an argument derived from CuActivityEvent. See CuTReader::sendData for an example
Send a request and receive a response asynchronously
Use sendData in conjunction with CuDataListener::onUpdate, as described in the getData documentation.
Implemented in CuRNDActionReader.
Referenced by CuRNDReader::sendData().
start()
virtual void CuRNDActionI::start () pure virtual
the method where activities are created and registered
This is the place where activities are created and registered to Cumbia through the method Cumbia::registerActivity.
Examples
CuTReader::start
CuTWriter::start
See also Cumbia::registerActivity
Implemented in CuRNDActionReader.
Referenced by CumbiaRandom::addAction().
stop()
virtual void CuRNDActionI::stop () pure virtual
the method where activities are unregistered from Cumbia
This is the place where activities are unregistered from Cumbia by the Cumbia::unregisterActivity method
Examples
CuTReader::stop
CuTWriter::stop
See also Cumbia::unregisterActivity
Implemented in CuRNDActionReader.
The documentation for this class was generated from the following files:
curndactioni.h
curndactioni.cpp