cumbia-random: CuRNDActionFactoryI Class Reference
CuRNDActionFactoryI Class Reference abstract
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
#include <curndactionfactoryi.h>
Public Member Functions
CuRNDActionFactoryI ()
virtual CuRNDActionI * create (const std::string &source, CumbiaRandom *ct) const =0
virtual CuRNDActionI::Type getType () const =0
Return the type of action that the factory creates.
Detailed Description
Factory to instantiate CuTangoActionI implementations, such as readers, writers and attribute configuration actions.
Notable implementations
CuTangoReaderFactory
CuTangoWriterFactory
CuTangoAttConfFactory
Constructor & Destructor Documentation
CuRNDActionFactoryI()
CuRNDActionFactoryI::CuRNDActionFactoryI () inline
Member Function Documentation
create()
virtual CuRNDActionI * CuRNDActionFactoryI::create (const std::string & source, CumbiaRandom * ct) const pure virtual
Pure virtual method that must be implemented by subclasses to return a valid CuTangoActionI instance.
Parameters
source a string identifying a source to connect to
ct a pointer to a CumbiaRandom instance
Implemented in CuRNDActionReaderFactory.
Referenced by CuRNDActionFactoryService::registerAction().
getType()
virtual CuRNDActionI::Type CuRNDActionFactoryI::getType () const pure virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implemented in CuRNDActionReaderFactory.
Referenced by CumbiaRandom::addAction(), and CuRNDActionFactoryService::registerAction().
The documentation for this class was generated from the following file:
curndactionfactoryi.h