cumbia-random: CumbiaRandom Class Reference
CumbiaRandom Class Reference
#include <cumbiarandom.h>
Public Types
enum Type { CumbiaRNDType = Cumbia::CumbiaUserType + 12 }
Public Member Functions
CumbiaRandom (CuThreadFactoryImplI *tfi, CuThreadsEventBridgeFactory_I *teb)
~CumbiaRandom ()
CuThreadFactoryImplI * getThreadFactoryImpl () const
CuThreadsEventBridgeFactory_I * getThreadEventsBridgeFactory () const
virtual int getType () const
void addAction (const std::string &source, CuDataListener *l, const CuRNDActionFactoryI &f)
void unlinkListener (const string &source, CuRNDActionI::Type t, CuDataListener *l)
CuRNDActionI * findAction (const std::string &source, CuRNDActionI::Type t) const
Member Enumeration Documentation
Type
enum CumbiaRandom::Type
Enumerator
CumbiaRNDType
Constructor & Destructor Documentation
CumbiaRandom()
CumbiaRandom::CumbiaRandom (CuThreadFactoryImplI * tfi, CuThreadsEventBridgeFactory_I * teb)
~CumbiaRandom()
CumbiaRandom::~CumbiaRandom ()
Member Function Documentation
addAction()
void CumbiaRandom::addAction (const std::string & source, CuDataListener * l, const CuRNDActionFactoryI & f)
References CuRNDActionI::addDataListener(), CuRNDActionFactoryService::CuRNDActionFactoryServiceType, CuRNDActionFactoryService::findActive(), CuRNDActionFactoryI::getType(), CuRNDActionFactoryService::registerAction(), CumbiaRNDWorld::source_valid(), and CuRNDActionI::start().
findAction()
CuRNDActionI * CumbiaRandom::findAction (const std::string & source, CuRNDActionI::Type t) const
References CuRNDActionFactoryService::CuRNDActionFactoryServiceType, and CuRNDActionFactoryService::findActive().
getThreadEventsBridgeFactory()
CuThreadsEventBridgeFactory_I * CumbiaRandom::getThreadEventsBridgeFactory () const
getThreadFactoryImpl()
CuThreadFactoryImplI * CumbiaRandom::getThreadFactoryImpl () const
getType()
int CumbiaRandom::getType () const virtual
References CumbiaRNDType.
unlinkListener()
void CumbiaRandom::unlinkListener (const string & source, CuRNDActionI::Type t, CuDataListener * l)
References CuRNDActionFactoryService::CuRNDActionFactoryServiceType, and CuRNDActionFactoryService::find().
The documentation for this class was generated from the following files:
cumbiarandom.h
cumbiarandom.cpp