QTangoDBus: TAppInfoList Class Reference
TAppInfoList Class Reference
#include <tappinfolist.h>
Public Member Functions
TAppInfoList ()
void add (const TAppInfo &ai)
TAppInfo at (const int index) const
TAppInfo find (const QString &appName, const pid_t pid) const
void remove (const QString &appName, const pid_t pid)
void remove (const TAppInfo &ai)
void clear ()
bool contains (const QString &appName, const pid_t pid) const
int size () const
QList< TAppInfo > findWithName (const QString &name) const
Returns the list of AppInfo with the name provided.
TAppInfo findByNameArgs (const QString &name, const QStringList &args) const
Returns the TAppInfo matching name and args.
TAppInfo findByPid (pid_t pid) const
Returns the TAppInfo with process id equal to pid.
TAppInfo findByService (const QString &serviceName) const
returns TAppInfo associated to service serviceName
TAppInfoList & operator= (const TAppInfoList &ail)
Constructor & Destructor Documentation
TAppInfoList()
TAppInfoList::TAppInfoList ()
Member Function Documentation
add()
void TAppInfoList::add (const TAppInfo & ai) inline
Referenced by operator=().
at()
TAppInfo TAppInfoList::at (const int index) const inline
References find().
Referenced by operator=().
clear()
void TAppInfoList::clear () inline
References contains().
contains()
bool TAppInfoList::contains (const QString & appName, const pid_t pid) const
References TAppInfo::appName, and TAppInfo::pid.
Referenced by clear().
find()
TAppInfo TAppInfoList::find (const QString & appName, const pid_t pid) const
References TAppInfo::appName, and TAppInfo::pid.
Referenced by at(), TApplicationsPoolProxy::findApplication(), and remove().
findByNameArgs()
TAppInfo TAppInfoList::findByNameArgs (const QString & name, const QStringList & args) const
Note: does not return the TAppInfo with pid equal to getpid()
See also
TApplicationsPoolProxy::findApplicationByNameArgs
References TAppInfo::appName, TAppInfo::args, and TAppInfo::pid.
Referenced by TApplicationsPoolProxy::findApplicationByNameArgs(), and size().
findByPid()
TAppInfo TAppInfoList::findByPid (pid_t pid) const
References TAppInfo::pid.
Referenced by TApplicationsPoolProxy::findApplicationByPid(), and size().
findByService()
TAppInfo TAppInfoList::findByService (const QString & serviceName) const
Each TApplication is associated to an unique unambiguous service name, because it is made up of the application pid and the application name. So it is safe to search by service name.
References TAppInfo::dbusServiceName.
Referenced by size().
findWithName()
QList< TAppInfo > TAppInfoList::findWithName (const QString & name) const
Note: the AppInfo with pid equal to getpid() is not included in the return list.
See also
TApplicationsPoolProxy::findApplicationsWithName
References TAppInfo::appName, and TAppInfo::pid.
Referenced by TApplicationsPoolProxy::findApplicationsWithName(), and size().
operator=()
TAppInfoList & TAppInfoList::operator= (const TAppInfoList & ail)
References add(), at(), and size().
Referenced by size().
remove() [1/2]
void TAppInfoList::remove (const QString & appName, const pid_t pid)
References find().
remove() [2/2]
void TAppInfoList::remove (const TAppInfo & ai)
size()
int TAppInfoList::size () const inline
References findByNameArgs(), findByPid(), findByService(), findWithName(), and operator=().
Referenced by operator=().
The documentation for this class was generated from the following files:
tappinfolist.h
tappinfolist.cpp