QTangoDBus: TApplicationInterface Class Reference
TApplicationInterface Class Reference
#include <TApplicationInterface.h>
Public Slots
QDBusReply< QString > executable ()
QDBusReply< QDBusVariant > invokeMethod0 (const QString &widgetName, const QString &member)
QDBusReply< QDBusVariant > invokeMethod1 (const QString &widgetName, const QString &member, const QDBusVariant &val0)
QDBusReply< QDBusVariant > invokeMethod2 (const QString &widgetName, const QString &member, const QDBusVariant &val0, const QDBusVariant &val1)
QDBusReply< QDBusVariant > invokeMethod3 (const QString &widgetName, const QString &member, const QDBusVariant &val0, const QDBusVariant &val1, const QDBusVariant &val2)
QDBusReply< QDBusVariant > invokeMethod4 (const QString &widgetName, const QString &member, const QDBusVariant &val0, const QDBusVariant &val1, const QDBusVariant &val2, const QDBusVariant &val3)
QDBusReply< QDBusVariant > invokeMethod5 (const QString &widgetName, const QString &member, const QDBusVariant &val0, const QDBusVariant &val1, const QDBusVariant &val2, const QDBusVariant &val3, const QDBusVariant &val4)
QDBusReply< void > message ()
QDBusReply< QStringList > methods (const QString &widgetName)
QDBusReply< void > onSecondInstanceDetected ()
QDBusReply< QStringList > parameters ()
QDBusReply< QStringList > properties (const QString &widgetName)
QDBusReply< void > quit ()
QDBusReply< void > raise ()
QDBusReply< QDBusVariant > readProperty (const QString &objectName, const QString &propertyName)
QDBusReply< QString > version ()
QDBusReply< QStringList > widgetList ()
QDBusReply< void > writeProperty (const QString &objectName, const QString &propertyName, const QDBusVariant &value)
Signals
void applicationStarted ()
Public Member Functions
TApplicationInterface (const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent=0)
~TApplicationInterface ()
bool unique () const
void setUnique (bool value)
Static Public Member Functions
static const char * staticInterfaceName ()
Properties
bool unique
Constructor & Destructor Documentation
TApplicationInterface()
TApplicationInterface::TApplicationInterface (const QString & service, const QString & path, const QDBusConnection & connection, QObject * parent = 0)
Referenced by staticInterfaceName().
~TApplicationInterface()
TApplicationInterface::~TApplicationInterface ()
Referenced by staticInterfaceName().
Member Function Documentation
applicationStarted
void TApplicationInterface::applicationStarted () signal
Referenced by writeProperty().
executable
QDBusReply<QString> TApplicationInterface::executable () inline slot
invokeMethod0
QDBusReply<QDBusVariant> TApplicationInterface::invokeMethod0 (const QString & widgetName, const QString & member) inline slot
invokeMethod1
QDBusReply<QDBusVariant> TApplicationInterface::invokeMethod1 (const QString & widgetName, const QString & member, const QDBusVariant & val0) inline slot
invokeMethod2
QDBusReply<QDBusVariant> TApplicationInterface::invokeMethod2 (const QString & widgetName, const QString & member, const QDBusVariant & val0, const QDBusVariant & val1) inline slot
invokeMethod3
QDBusReply<QDBusVariant> TApplicationInterface::invokeMethod3 (const QString & widgetName, const QString & member, const QDBusVariant & val0, const QDBusVariant & val1, const QDBusVariant & val2) inline slot
invokeMethod4
QDBusReply<QDBusVariant> TApplicationInterface::invokeMethod4 (const QString & widgetName, const QString & member, const QDBusVariant & val0, const QDBusVariant & val1, const QDBusVariant & val2, const QDBusVariant & val3) inline slot
invokeMethod5
QDBusReply<QDBusVariant> TApplicationInterface::invokeMethod5 (const QString & widgetName, const QString & member, const QDBusVariant & val0, const QDBusVariant & val1, const QDBusVariant & val2, const QDBusVariant & val3, const QDBusVariant & val4) inline slot
message
QDBusReply<void> TApplicationInterface::message () inline slot
methods
QDBusReply<QStringList> TApplicationInterface::methods (const QString & widgetName) inline slot
onSecondInstanceDetected
QDBusReply<void> TApplicationInterface::onSecondInstanceDetected () inline slot
parameters
QDBusReply<QStringList> TApplicationInterface::parameters () inline slot
properties
QDBusReply<QStringList> TApplicationInterface::properties (const QString & widgetName) inline slot
quit
QDBusReply<void> TApplicationInterface::quit () inline slot
raise
QDBusReply<void> TApplicationInterface::raise () inline slot
readProperty
QDBusReply<QDBusVariant> TApplicationInterface::readProperty (const QString & objectName, const QString & propertyName) inline slot
setUnique()
void TApplicationInterface::setUnique (bool value) inline
staticInterfaceName()
static const char* TApplicationInterface::staticInterfaceName () inline static
References TApplicationInterface(), and ~TApplicationInterface().
unique()
bool TApplicationInterface::unique () const inline
version
QDBusReply<QString> TApplicationInterface::version () inline slot
widgetList
QDBusReply<QStringList> TApplicationInterface::widgetList () inline slot
writeProperty
QDBusReply<void> TApplicationInterface::writeProperty (const QString & objectName, const QString & propertyName, const QDBusVariant & value) inline slot
References applicationStarted().
Property Documentation
unique
bool TApplicationInterface::unique read write
The documentation for this class was generated from the following files:
TApplicationInterface.h
TApplicationInterface.cpp