QTangoDBus: DeviceThreadFactoryInterface Class Reference
DeviceThreadFactoryInterface Class Reference
#include <DeviceThreadFactoryInterface.h>
Public Member Functions
DeviceThreadFactoryInterface (const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent=0)
~DeviceThreadFactoryInterface ()
int threadCount () const
QStringList threads () const
Static Public Member Functions
static const char * staticInterfaceName ()
Properties
int threadCount
QStringList threads
Constructor & Destructor Documentation
DeviceThreadFactoryInterface()
DeviceThreadFactoryInterface::DeviceThreadFactoryInterface (const QString & service, const QString & path, const QDBusConnection & connection, QObject * parent = 0)
Referenced by staticInterfaceName().
~DeviceThreadFactoryInterface()
DeviceThreadFactoryInterface::~DeviceThreadFactoryInterface ()
Referenced by staticInterfaceName().
Member Function Documentation
staticInterfaceName()
static const char* DeviceThreadFactoryInterface::staticInterfaceName () inline static
References DeviceThreadFactoryInterface(), and ~DeviceThreadFactoryInterface().
threadCount()
int DeviceThreadFactoryInterface::threadCount () const inline
threads()
QStringList DeviceThreadFactoryInterface::threads () const inline
Property Documentation
threadCount
int DeviceThreadFactoryInterface::threadCount read
threads
QStringList DeviceThreadFactoryInterface::threads read
The documentation for this class was generated from the following files:
DeviceThreadFactoryInterface.h
DeviceThreadFactoryInterface.cpp