QTangoDBus: TApplicationsPoolProxy Class Reference
TApplicationsPoolProxy Class Reference
This class represents a Proxy to the pool of TApplications registered with the DBus session bus.
#include <tapplicationspoolproxy.h>
Public Slots
void refreshAppList ()
void dbusServiceOwnerChanged (const QString &, const QString &, const QString &)
Signals
void serviceRegistered (const TAppInfo &appInfo)
This signal is emitted when a new TApplication is launched.
void serviceUnregistered (const TAppInfo &appInfo)
This signal is emitted when a TApplication is closed and thus unregistering from DBus.
void error (const QString &s)
This signal is emitted when a DBus error happens.
Public Member Functions
TApplicationsPoolProxy (QObject *parent=0)
The constructor of the pool proxy.
QString errorMessage ()
TAppInfoList applicationsList ()
TAppInfo findApplicationByService (const QString &serviceName)
returns the TAppInfo object associated to the service name provided
TAppInfo findApplication (const QString &appName, int pid)
finds the application with appName name and pid
QList< TAppInfo > findApplicationsWithName (const QString &name)
finds the applications with the name provided
TAppInfo findApplicationByNameArgs (const QString &name, const QStringList &args)
Looks for TApplications with the name and arguments provided.
TAppInfo findApplicationByPid (pid_t pid)
Returns the TAppInfo running with the pid provided, or an empty TAppInfo if none was found.
Detailed Description
This class can be used to retrieve information about QTango applications registered with the DBus session bus. Through this object you can be notified when a new TApplication is launched or closed, via the serviceRegistered and serviceUnregistered signals. The object involved in this notification and representing the type of information exchanged with this class is TAppInfo. TApplicationsPoolProxy contains a list of TAppInfo, each one of them storing information about the application name (executable name, without path), the application pid, the application arguments and the service and paths registered with the session bus.
Once obtained the desired TAppInfo, you can interact with the running TApplication by means of the TApplicationInterface class.
See also
TApplicationInterface
TAppInfo
TAppInfoList
Since
QTango 4.2.0
Author
Giacomo Strangolino
Example.
Suppose we want to obtain the list of QTango applications currently connected to the DBus message bus, to be notified when a new applications registers with DBus and when an application unregisters. The list of TApplications may be organized in a tree view, while the TApplicationsPoolProxy can be used to store data in the model/view architecture.
#include <TApplicationsPoolProxy>
MainWindow::MainWindow(QWidget *parent) :
     QMainWindow(parent),
      ui(new Ui::MainWindow)
{
 ui->setupUi(this);
 TApplicationsPoolProxy *appsPoolProxy = new TApplicationsPoolProxy(this);
 appsPoolProxy->setObjectName("TAppsPoolProxy");
 connect(appsPoolProxy, SIGNAL(serviceRegistered(const TAppInfo&)), this, SLOT(addApplication(const TAppInfo&)));
 connect(appsPoolProxy, SIGNAL(serviceUnregistered(const TAppInfo&)), this, SLOT(removeApplication(const TAppInfo&)));
 connect(appsPoolProxy, SIGNAL(error(const QString&)), this, SLOT(showError(const QString&)));
}
In the addApplication slot you can extract data from the TAppInfo passed as argument, such as application name, pid and arguments. Then create an item in the view and add it to the view. In the removeApplication slot, you will look for items with the given application name and pid, for instance, and delete them from the view.
In the tdbus directory of the qtangocore distribution, you will find an example of using TApplicationsPoolProxy.
See also
TApplicationInterface
Constructor & Destructor Documentation
TApplicationsPoolProxy()
TApplicationsPoolProxy::TApplicationsPoolProxy (QObject * parent = 0) explicit
On construction, a read of the registered services is performed on the DBus session bus, and their list is available, for instance through applicationsList().
References refreshAppList().
Member Function Documentation
applicationsList()
TAppInfoList TApplicationsPoolProxy::applicationsList ()
Referenced by findApplication(), findApplicationByNameArgs(), findApplicationByPid(), and findApplicationsWithName().
dbusServiceOwnerChanged
void TApplicationsPoolProxy::dbusServiceOwnerChanged (const QString & name, const QString & oldOwner, const QString & newOwner) slot
References error(), TAppInfo::isEmpty(), serviceRegistered(), and serviceUnregistered().
error
void TApplicationsPoolProxy::error (const QString & s) signal
Parameters
s the error string.
Referenced by dbusServiceOwnerChanged(), and refreshAppList().
errorMessage()
QString TApplicationsPoolProxy::errorMessage ()
findApplication()
TAppInfo TApplicationsPoolProxy::findApplication (const QString & appName, int pid)
This is a shortcut for TAppInfoList::find()
References applicationsList(), and TAppInfoList::find().
findApplicationByNameArgs()
TAppInfo TApplicationsPoolProxy::findApplicationByNameArgs (const QString & name, const QStringList & args)
Parameters
name the application name to look for.
args the QStringList with the command line arguments to look for.
Returns an empty TAppInfo if no result was found. Shortcut for TAppInfoList::findByNameArgs()
Note: the AppInfo with pid equal to getpid() is not considered by TAppInfoList::findByNameArgs(). This means that the object referring to the running application is not returned by this method.
See also
TAppInfoList::findByNameArgs()
References applicationsList(), and TAppInfoList::findByNameArgs().
findApplicationByPid()
TAppInfo TApplicationsPoolProxy::findApplicationByPid (pid_t pid)
This is a shortcut for TAppInfoList::findByPid()
Note: the AppInfo with pid equal to getpid() is not included in the return list.
See also
TAppInfoList::findByNameArgs
References applicationsList(), and TAppInfoList::findByPid().
findApplicationByService()
TAppInfo TApplicationsPoolProxy::findApplicationByService (const QString & serviceName)
Parameters
serviceName the DBus service name
Returns
the TAppInfo associated to serviceName or an empty TAppInfo if none found
You can test the result with TAppInfo::isEmpty() before using the returned object.
findApplicationsWithName()
QList< TAppInfo > TApplicationsPoolProxy::findApplicationsWithName (const QString & name)
Returns
the list of applications registered with dbus having the name provided.
This is a shortcut for TAppInfoList::findWithName()
Note: the AppInfo with pid equal to getpid() is not included in the return list.
References applicationsList(), and TAppInfoList::findWithName().
refreshAppList
void TApplicationsPoolProxy::refreshAppList () slot
References error().
Referenced by TApplicationsPoolProxy().
serviceRegistered
void TApplicationsPoolProxy::serviceRegistered (const TAppInfo & appInfo) signal
Parameters
appInfo the data structure representing the remote TApplication which is going to be registered to the DBus session bus.
Referenced by dbusServiceOwnerChanged().
serviceUnregistered
void TApplicationsPoolProxy::serviceUnregistered (const TAppInfo & appInfo) signal
Parameters
appInfo the data structure representing the remote TApplication which is going to unregister from the DBus session bus.
Referenced by dbusServiceOwnerChanged().
The documentation for this class was generated from the following files:
tapplicationspoolproxy.h
tapplicationspoolproxy.cpp