QTangoDBus: ActionFactoryInterface Class Reference
ActionFactoryInterface Class Reference
#include <ActionFactoryInterface.h>
Public Slots
QDBusReply< QString > actionAsXml (const QString &point, const QStringList &args, int desiredRefreshMode)
Signals
void targetExecuted (const QString &point, int timestamp, bool success, const QString &exception, const QString &data)
Public Member Functions
ActionFactoryInterface (const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent=0)
~ActionFactoryInterface ()
QStringList actionsListAsXml () const
bool targetExecutionLogEnabled () const
Static Public Member Functions
static const char * staticInterfaceName ()
Properties
QStringList actionsListAsXml
bool targetExecutionLogEnabled
Constructor & Destructor Documentation
ActionFactoryInterface()
ActionFactoryInterface::ActionFactoryInterface (const QString & service, const QString & path, const QDBusConnection & connection, QObject * parent = 0)
Referenced by staticInterfaceName().
~ActionFactoryInterface()
ActionFactoryInterface::~ActionFactoryInterface ()
Referenced by staticInterfaceName().
Member Function Documentation
actionAsXml
QDBusReply<QString> ActionFactoryInterface::actionAsXml (const QString & point, const QStringList & args, int desiredRefreshMode) inline slot
References targetExecuted().
actionsListAsXml()
QStringList ActionFactoryInterface::actionsListAsXml () const inline
staticInterfaceName()
static const char* ActionFactoryInterface::staticInterfaceName () inline static
References ActionFactoryInterface(), and ~ActionFactoryInterface().
targetExecuted
void ActionFactoryInterface::targetExecuted (const QString & point, int timestamp, bool success, const QString & exception, const QString & data) signal
Referenced by actionAsXml().
targetExecutionLogEnabled()
bool ActionFactoryInterface::targetExecutionLogEnabled () const inline
Property Documentation
actionsListAsXml
QStringList ActionFactoryInterface::actionsListAsXml read
targetExecutionLogEnabled
bool ActionFactoryInterface::targetExecutionLogEnabled read
The documentation for this class was generated from the following files:
ActionFactoryInterface.h
ActionFactoryInterface.cpp