#ifndef QUMBIATANGOCONTROLS_GLOBAL_H
#define QUMBIATANGOCONTROLS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QUMBIATANGOCONTROLS_LIBRARY)
#  define QUMBIATANGOCONTROLSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QUMBIATANGOCONTROLSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QUMBIATANGOCONTROLS_GLOBAL_H
