/*----- PROTECTED REGION ID(CumbiaAbstractDeviceStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: CumbiaAbstractDeviceStateMachine.cpp,v 1.1 2017-03-14 11:25:46 giacomo Exp $";
//=============================================================================
//
// file :        CumbiaAbstractDeviceStateMachine.cpp
//
// description : State machine file for the CumbiaAbstractDevice class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author: giacomo $
//
// $Revision: 1.1 $
// $Date: 2017-03-14 11:25:46 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <CumbiaAbstractDevice.h>

/*----- PROTECTED REGION END -----*/	//	CumbiaAbstractDevice::CumbiaAbstractDeviceStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace CumbiaAbstractDevice_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(CumbiaAbstractDevice::CumbiaAbstractDeviceStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	CumbiaAbstractDevice::CumbiaAbstractDeviceStateAllowed.AdditionalMethods

}	//	End of namespace
