cumbia-epics: CuEpConfigActivity Class Reference
CuEpConfigActivity Class Reference
#include <cuepconfigactivity.h>
Public Types
enum Type { CuAttConfigActivityType = CuActivity::User + 5 }
Public Member Functions
CuEpConfigActivity (const CuData &tok, CuEpCAService *df)
void setDesiredAttributeProperties (const std::vector< std::string > &props)
virtual ~CuEpConfigActivity ()
int getType () const
void event (CuActivityEvent *e)
bool matches (const CuData &token) const
int repeat () const
Protected Member Functions
void init ()
void execute ()
void onExit ()
Member Enumeration Documentation
Type
enum CuEpConfigActivity::Type
Enumerator
CuAttConfigActivityType
Constructor & Destructor Documentation
CuEpConfigActivity()
CuEpConfigActivity::CuEpConfigActivity (const CuData & tok, CuEpCAService * df)
References CuEpConfigActivityPrivate::ep_service, CuEpConfigActivityPrivate::err, CuEpConfigActivityPrivate::exiting, and CuEpConfigActivityPrivate::other_thread_id.
~CuEpConfigActivity()
CuEpConfigActivity::~CuEpConfigActivity () virtual
Member Function Documentation
event()
void CuEpConfigActivity::event (CuActivityEvent * e)
execute()
void CuEpConfigActivity::execute () protected
References CuEpicsWorld::caget(), CuEpicsWorld::fillThreadInfo(), and CuEpConfigActivityPrivate::my_thread_id.
getType()
int CuEpConfigActivity::getType () const
References CuAttConfigActivityType.
init()
void CuEpConfigActivity::init () protected
References CuEpConfigActivityPrivate::my_thread_id, and CuEpConfigActivityPrivate::other_thread_id.
matches()
bool CuEpConfigActivity::matches (const CuData & token) const
onExit()
void CuEpConfigActivity::onExit () protected
References CuEpConfigActivityPrivate::err, CuEpConfigActivityPrivate::exiting, CuEpicsWorld::fillThreadInfo(), CuEpConfigActivityPrivate::msg, and CuEpConfigActivityPrivate::my_thread_id.
repeat()
int CuEpConfigActivity::repeat () const
setDesiredAttributeProperties()
void CuEpConfigActivity::setDesiredAttributeProperties (const std::vector< std::string > & props)
References CuEpConfigActivityPrivate::props.
The documentation for this class was generated from the following files:
cuepconfigactivity.h
cuepconfigactivity.cpp