cumbia-epics: CuEpicsActionFactoryI Class Reference
CuEpicsActionFactoryI Class Reference abstract
#include <cuepactionfactoryi.h>
Public Member Functions
CuEpicsActionFactoryI ()
virtual ~CuEpicsActionFactoryI ()
virtual CuEpicsActionI * create (const std::string &source, CumbiaEpics *ct) const =0
virtual CuEpicsActionI::Type getType () const =0
Return the type of action that the factory creates.
Constructor & Destructor Documentation
CuEpicsActionFactoryI()
CuEpicsActionFactoryI::CuEpicsActionFactoryI () inline
~CuEpicsActionFactoryI()
virtual CuEpicsActionFactoryI::~CuEpicsActionFactoryI () inline virtual
Member Function Documentation
create()
virtual CuEpicsActionI* CuEpicsActionFactoryI::create (const std::string & source, CumbiaEpics * ct) const pure virtual
Implemented in CuEpicsPropertyFactory, CuEpicsWriterFactory, and CuEpicsReaderFactory.
Referenced by CuEpicsActionFactoryService::registerAction().
getType()
virtual CuEpicsActionI::Type CuEpicsActionFactoryI::getType () const pure virtual
Return the type of action that the factory creates.
Returns
the type of action that the factory creates
Implemented in CuEpicsPropertyFactory, CuEpicsWriterFactory, and CuEpicsReaderFactory.
Referenced by CumbiaEpics::addAction(), and CuEpicsActionFactoryService::registerAction().
The documentation for this class was generated from the following file:
cuepactionfactoryi.h