cumbia-epics: CuPut Class Reference
CuPut Class Reference
#include <cuput.h>
Public Member Functions
CuPut (const EpSource &src, CumbiaEpics *ct)
virtual ~CuPut ()
void setWriteValue (const CuVariant &wval)
void onProgress (int step, int total, const CuData &data)
void onResult (const CuData &data)
CuData getToken () const
EpSource getSource () const
Type getType () const
void addDataListener (CuDataListener *l)
void removeDataListener (CuDataListener *l)
size_t dataListenersCount ()
void start ()
void stop ()
void sendData (const CuData &data)
void getData (CuData &d_inout) const
virtual bool exiting () const
virtual void onResult (const std::vector< CuData > &datalist)
Public Member Functions inherited from CuEpicsActionI
virtual ~CuEpicsActionI ()
Additional Inherited Members
Public Types inherited from CuEpicsActionI
enum Type {
Reader = 0, Writer, MultiReader, MultiWriter,
PropConfig
}
Constructor & Destructor Documentation
CuPut()
CuPut::CuPut (const EpSource & src, CumbiaEpics * ct)
References CuEpWriterPrivate::cumbia_ep, CuEpWriterPrivate::ep_src, CuEpWriterPrivate::exiting, CuEpWriterPrivate::li, and CuEpWriterPrivate::log.
~CuPut()
CuPut::~CuPut () virtual
Member Function Documentation
addDataListener()
void CuPut::addDataListener (CuDataListener * l) virtual
Implements CuEpicsActionI.
References CuEpWriterPrivate::listeners.
dataListenersCount()
size_t CuPut::dataListenersCount () virtual
Implements CuEpicsActionI.
References CuEpWriterPrivate::listeners.
exiting()
bool CuPut::exiting () const virtual
Implements CuEpicsActionI.
References CuEpWriterPrivate::exiting.
getData()
void CuPut::getData (CuData & d_inout) const virtual
Implements CuEpicsActionI.
getSource()
EpSource CuPut::getSource () const virtual
Implements CuEpicsActionI.
References CuEpWriterPrivate::ep_src.
getToken()
CuData CuPut::getToken () const
References CuEpWriterPrivate::ep_src, and EpSource::getName().
getType()
CuEpicsActionI::Type CuPut::getType () const virtual
Implements CuEpicsActionI.
References CuEpicsActionI::Writer.
Referenced by onResult().
onProgress()
void CuPut::onProgress (int step, int total, const CuData & data)
onResult() [1/2]
void CuPut::onResult (const CuData & data)
References CuEpicsActionFactoryService::CuActionFactoryServiceType, CuEpWriterPrivate::cumbia_ep, CuEpWriterPrivate::ep_src, CuEpWriterPrivate::exiting, EpSource::getName(), getType(), CuEpWriterPrivate::listeners, and CuEpicsActionFactoryService::unregisterAction().
onResult() [2/2]
void CuPut::onResult (const std::vector< CuData > & datalist) virtual
removeDataListener()
void CuPut::removeDataListener (CuDataListener * l) virtual
Implements CuEpicsActionI.
References CuEpWriterPrivate::listeners, and stop().
sendData()
void CuPut::sendData (const CuData & data) virtual
Implements CuEpicsActionI.
setWriteValue()
void CuPut::setWriteValue (const CuVariant & wval)
References CuEpWriterPrivate::write_val.
Referenced by CuEpicsWriterFactory::create().
start()
void CuPut::start () virtual
Implements CuEpicsActionI.
References CuEpWriterPrivate::activity, CuEpCAService::CuEpicsChannelAccessServiceType, CuEpWriterPrivate::cumbia_ep, CuEpWriterPrivate::ep_src, EpSource::getName(), EpSource::getPV(), CumbiaEpics::getThreadEventsBridgeFactory(), CumbiaEpics::getThreadFactoryImpl(), and CuEpWriterPrivate::write_val.
stop()
void CuPut::stop () virtual
Implements CuEpicsActionI.
References CuEpWriterPrivate::exiting.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cuput.h
cuput.cpp