cumbia-epics: CuPutActivity Class Reference
CuPutActivity Class Reference
#include <cuputactivity.h>
Public Member Functions
CuPutActivity (const CuData &token, CuEpCAService *df)
virtual ~CuPutActivity ()
void exception_handler (struct exception_handler_args excargs)
void event (CuActivityEvent *e)
bool matches (const CuData &token) const
Static Public Member Functions
static void exception_handler_cb (struct exception_handler_args excargs)
Protected Member Functions
void init ()
void execute ()
void onExit ()
Constructor & Destructor Documentation
CuPutActivity()
CuPutActivity::CuPutActivity (const CuData & token, CuEpCAService * df)
References CuPutActivityPrivate::epics_service, CuPutActivityPrivate::err, and CuPutActivityPrivate::other_thread_id.
~CuPutActivity()
CuPutActivity::~CuPutActivity () virtual
Member Function Documentation
event()
void CuPutActivity::event (CuActivityEvent * e)
exception_handler()
void CuPutActivity::exception_handler (struct exception_handler_args excargs)
References CuEpicsWorld::extractException().
Referenced by exception_handler_cb().
exception_handler_cb()
void CuPutActivity::exception_handler_cb (struct exception_handler_args excargs) static
References exception_handler().
Referenced by execute().
execute()
void CuPutActivity::execute () protected
References caTimeout, CuEpicsWorld::connect_pvs(), CuPutActivityPrivate::default_timeout, CuPutActivityPrivate::err, exception_handler_cb(), and CuPutActivityPrivate::my_thread_id.
init()
void CuPutActivity::init () protected
References CuPutActivityPrivate::my_thread_id, and CuPutActivityPrivate::other_thread_id.
matches()
bool CuPutActivity::matches (const CuData & token) const
onExit()
void CuPutActivity::onExit () protected
References CuPutActivityPrivate::err, CuEpicsWorld::fillThreadInfo(), CuPutActivityPrivate::msg, and CuPutActivityPrivate::my_thread_id.
The documentation for this class was generated from the following files:
cuputactivity.h
cuputactivity.cpp