cumbia-epics: EpSource Class Reference
EpSource Class Reference
#include <epsource.h>
Public Types
enum Type { PV = 0, Field }
Public Member Functions
EpSource ()
EpSource (const std::string s)
EpSource (const EpSource &other)
string getPV () const
string getName () const
std::vector< string > getArgs () const
string toString () const
Type getType () const
EpSource & operator= (const EpSource &other)
bool operator== (const EpSource &other) const
std::string getArgsString () const
Member Enumeration Documentation
Type
enum EpSource::Type
Enumerator
PV
Field
Constructor & Destructor Documentation
EpSource() [1/3]
EpSource::EpSource ()
EpSource() [2/3]
EpSource::EpSource (const std::string s)
EpSource() [3/3]
EpSource::EpSource (const EpSource & other)
Member Function Documentation
getArgs()
std::vector< string > EpSource::getArgs () const
References getArgsString().
getArgsString()
std::string EpSource::getArgsString () const
Referenced by getArgs(), and toString().
getName()
string EpSource::getName () const
Referenced by CuPut::getToken(), CuEpConfiguration::getToken(), CuMonitor::getToken(), CuPut::onResult(), CuEpConfiguration::onResult(), CuMonitor::onResult(), CuPut::start(), and CuEpConfiguration::start().
getPV()
string EpSource::getPV () const
Referenced by CuPut::start(), CuEpConfiguration::start(), and toString().
getType()
EpSource::Type EpSource::getType () const
References Field, and PV.
Referenced by CuEpConfiguration::start(), and toString().
operator=()
EpSource & EpSource::operator= (const EpSource & other)
operator==()
bool EpSource::operator== (const EpSource & other) const
toString()
std::string EpSource::toString () const
References getArgsString(), getPV(), getType(), and PV.
The documentation for this class was generated from the following files:
epsource.h
epsource.cpp