cumbia-epics: CuEpicsWorld Class Reference
CuEpicsWorld Class Reference
#include <cuepics-world.h>
Public Types
enum CaGetMode { DbrCtrl, DbrTime }
Public Member Functions
CuEpicsWorld ()
virtual ~CuEpicsWorld ()
void fillThreadInfo (CuData &d, const CuActivity *a)
bool source_valid (const std::string &s) const
void extractData (const CuPV *_pv, CuData &da) const
std::string extractException (struct exception_handler_args excargs, CuData &d) const
fills the input CuData with exception information.
template<class T >
void putTimestamp (void *ep_data, CuData &d) const
template<class T >
void putCtrlData (void *ep_data, CuData &d) const
void caget (const std::string &src, CuData &prop_res, double timeout=DEFAULT_CA_TIMEOUT)
void setSrcPatterns (const std::vector< std::string > &p)
std::vector< std::string > srcPatterns () const
int create_pvs (CuPV *pvs, int nPvs, caCh *pCB)
int connect_pvs (CuPV *pvs, int nPvs)
Member Enumeration Documentation
CaGetMode
enum CuEpicsWorld::CaGetMode
Enumerator
DbrCtrl
DbrTime
Constructor & Destructor Documentation
CuEpicsWorld()
CuEpicsWorld::CuEpicsWorld ()
References CuEpicsWorldPrivate::src_patterns.
~CuEpicsWorld()
CuEpicsWorld::~CuEpicsWorld () virtual
Member Function Documentation
caget()
void CuEpicsWorld::caget (const std::string & src, CuData & prop_res, double timeout = DEFAULT_CA_TIMEOUT)
References CuPV::ch_id, connect_pvs(), DbrCtrl, DbrTime, and extractData().
Referenced by CuEpConfigActivity::execute().
connect_pvs()
int CuEpicsWorld::connect_pvs (CuPV * pvs, int nPvs)
References caTimeout, and create_pvs().
Referenced by caget(), and CuPutActivity::execute().
create_pvs()
int CuEpicsWorld::create_pvs (CuPV * pvs, int nPvs, caCh * pCB)
References caPriority, and CuPV::status.
Referenced by connect_pvs(), and CuMonitorActivity::init().
extractData()
void CuEpicsWorld::extractData (const CuPV * _pv, CuData & da) const
References CuPV::ch_id, CuPV::dbrType, CuPV::nElems, and CuPV::value.
Referenced by caget(), and CuMonitorActivity::event_handler().
extractException()
std::string CuEpicsWorld::extractException (struct exception_handler_args excargs, CuData & da) const
fills the input CuData with exception information.
Returns
a string representation of the available error information
Referenced by CuPutActivity::exception_handler(), and CuMonitorActivity::exception_handler().
fillThreadInfo()
void CuEpicsWorld::fillThreadInfo (CuData & d, const CuActivity * a)
Referenced by CuMonitorActivity::event_handler(), CuEpConfigActivity::execute(), CuEpConfigActivity::onExit(), and CuPutActivity::onExit().
putCtrlData()
template<class T > void CuEpicsWorld::putCtrlData (void * ep_data, CuData & d) const
putTimestamp()
template<class T > void CuEpicsWorld::putTimestamp (void * ep_data, CuData & d) const
References TIMETEXTLEN.
setSrcPatterns()
void CuEpicsWorld::setSrcPatterns (const std::vector< std::string > & p)
References CuEpicsWorldPrivate::src_patterns.
source_valid()
bool CuEpicsWorld::source_valid (const std::string & s) const
Referenced by CumbiaEpics::addAction().
srcPatterns()
std::vector< std::string > CuEpicsWorld::srcPatterns () const
References CuEpicsWorldPrivate::src_patterns.
The documentation for this class was generated from the following files:
cuepics-world.h
cuepics-world.cpp