cumbia-epics: CuEpicsActionFactoryService Class Reference
CuEpicsActionFactoryService Class Reference
#include <cuepactionfactoryservice.h>
Public Types
enum Type { CuActionFactoryServiceType = CuServices::User + 21 }
Public Member Functions
CuEpicsActionFactoryService ()
virtual ~CuEpicsActionFactoryService ()
CuEpicsActionI * registerAction (const std::string &src, const CuEpicsActionFactoryI &f, CumbiaEpics *ce)
std::vector< CuEpicsActionI * > find (const std::string &name, CuEpicsActionI::Type at)
CuEpicsActionI * findActive (const std::string &src, CuEpicsActionI::Type at)
std::string getLastError () const
void unregisterAction (const std::string &src, CuEpicsActionI::Type at)
void deleteActions ()
std::string getName () const
CuServices::Type getType () const
Member Enumeration Documentation
Type
enum CuEpicsActionFactoryService::Type
Enumerator
CuActionFactoryServiceType
Constructor & Destructor Documentation
CuEpicsActionFactoryService()
CuEpicsActionFactoryService::CuEpicsActionFactoryService ()
References CuEpicsActionFactoryServicePrivate::log, and CuEpicsActionFactoryServicePrivate::logImpl.
~CuEpicsActionFactoryService()
CuEpicsActionFactoryService::~CuEpicsActionFactoryService () virtual
References CuEpicsActionFactoryServicePrivate::log, and CuEpicsActionFactoryServicePrivate::logImpl.
Member Function Documentation
deleteActions()
void CuEpicsActionFactoryService::deleteActions ()
References CuEpicsActionFactoryServicePrivate::actions, and CuEpicsActionFactoryServicePrivate::mutex.
Referenced by CumbiaEpics::~CumbiaEpics().
find()
std::vector< CuEpicsActionI * > CuEpicsActionFactoryService::find (const std::string & name, CuEpicsActionI::Type at)
References CuEpicsActionFactoryServicePrivate::actions, and CuEpicsActionFactoryServicePrivate::mutex.
Referenced by CumbiaEpics::unlinkListener().
findActive()
CuEpicsActionI * CuEpicsActionFactoryService::findActive (const std::string & src, CuEpicsActionI::Type at)
References CuEpicsActionFactoryServicePrivate::actions, and CuEpicsActionFactoryServicePrivate::mutex.
Referenced by CumbiaEpics::addAction(), and CumbiaEpics::findAction().
getLastError()
string CuEpicsActionFactoryService::getLastError () const
References CuEpicsActionFactoryServicePrivate::lastError.
getName()
std::string CuEpicsActionFactoryService::getName () const
getType()
CuServices::Type CuEpicsActionFactoryService::getType () const
References CuActionFactoryServiceType.
registerAction()
CuEpicsActionI * CuEpicsActionFactoryService::registerAction (const std::string & src, const CuEpicsActionFactoryI & f, CumbiaEpics * ce)
References CuEpicsActionFactoryServicePrivate::actions, CuEpicsActionFactoryI::create(), CuEpicsActionFactoryI::getType(), and CuEpicsActionFactoryServicePrivate::mutex.
Referenced by CumbiaEpics::addAction().
unregisterAction()
void CuEpicsActionFactoryService::unregisterAction (const std::string & src, CuEpicsActionI::Type at)
References CuEpicsActionFactoryServicePrivate::actions, and CuEpicsActionFactoryServicePrivate::mutex.
Referenced by CuPut::onResult(), CuEpConfiguration::onResult(), and CuMonitor::onResult().
The documentation for this class was generated from the following files:
cuepactionfactoryservice.h
cuepactionfactoryservice.cpp