cumbia-epics: CuEpConfiguration Class Reference
CuEpConfiguration Class Reference
#include <cuepconfiguration.h>
Public Member Functions
CuEpConfiguration (const EpSource &src, CumbiaEpics *ct)
virtual ~CuEpConfiguration ()
void setDesiredPVProperties (const std::vector< std::string > props)
void onProgress (int, int, const CuData &)
void onResult (const CuData &data)
CuData getToken () const
EpSource getSource () const
Type getType () const
void addDataListener (CuDataListener *l)
void removeDataListener (CuDataListener *l)
void sendData (const CuData &data)
void getData (CuData &d_inout) const
size_t dataListenersCount ()
void start ()
void stop ()
bool exiting () const
virtual void onResult (const std::vector< CuData > &datalist)
Public Member Functions inherited from CuEpicsActionI
virtual ~CuEpicsActionI ()
Additional Inherited Members
Public Types inherited from CuEpicsActionI
enum Type {
Reader = 0, Writer, MultiReader, MultiWriter,
PropConfig
}
Constructor & Destructor Documentation
CuEpConfiguration()
CuEpConfiguration::CuEpConfiguration (const EpSource & src, CumbiaEpics * ct)
References CuEpConfigurationPrivate::cumbia_epics, CuEpConfigurationPrivate::exit, and CuEpConfigurationPrivate::tsrc.
~CuEpConfiguration()
CuEpConfiguration::~CuEpConfiguration () virtual
Member Function Documentation
addDataListener()
void CuEpConfiguration::addDataListener (CuDataListener * l) virtual
Implements CuEpicsActionI.
References CuEpConfigurationPrivate::activity, CuEpConfigurationPrivate::conf_data, and CuEpConfigurationPrivate::listeners.
dataListenersCount()
size_t CuEpConfiguration::dataListenersCount () virtual
Implements CuEpicsActionI.
References CuEpConfigurationPrivate::listeners.
exiting()
bool CuEpConfiguration::exiting () const virtual
Implements CuEpicsActionI.
References CuEpConfigurationPrivate::exit.
getData()
void CuEpConfiguration::getData (CuData & d_inout) const virtual
Implements CuEpicsActionI.
getSource()
EpSource CuEpConfiguration::getSource () const virtual
Implements CuEpicsActionI.
References CuEpConfigurationPrivate::tsrc.
getToken()
CuData CuEpConfiguration::getToken () const
References EpSource::getName(), and CuEpConfigurationPrivate::tsrc.
getType()
CuEpicsActionI::Type CuEpConfiguration::getType () const virtual
Implements CuEpicsActionI.
References CuEpicsActionI::PropConfig.
Referenced by onResult().
onProgress()
void CuEpConfiguration::onProgress (int step, int total, const CuData & data)
onResult() [1/2]
void CuEpConfiguration::onResult (const CuData & data)
References CuEpConfigurationPrivate::conf_data, CuEpicsActionFactoryService::CuActionFactoryServiceType, CuEpConfigurationPrivate::cumbia_epics, CuEpConfigurationPrivate::exit, EpSource::getName(), getType(), CuEpConfigurationPrivate::listeners, CuEpConfigurationPrivate::tsrc, and CuEpicsActionFactoryService::unregisterAction().
onResult() [2/2]
void CuEpConfiguration::onResult (const std::vector< CuData > & datalist) virtual
removeDataListener()
void CuEpConfiguration::removeDataListener (CuDataListener * l) virtual
Implements CuEpicsActionI.
References CuEpConfigurationPrivate::listeners, and stop().
sendData()
void CuEpConfiguration::sendData (const CuData & data) virtual
Implements CuEpicsActionI.
setDesiredPVProperties()
void CuEpConfiguration::setDesiredPVProperties (const std::vector< std::string > props)
References CuEpConfigurationPrivate::desired_props.
Referenced by CuEpicsPropertyFactory::create().
start()
void CuEpConfiguration::start () virtual
Implements CuEpicsActionI.
References CuEpConfigurationPrivate::activity, CuEpCAService::CuEpicsChannelAccessServiceType, CuEpConfigurationPrivate::cumbia_epics, CuEpConfigurationPrivate::desired_props, EpSource::getName(), EpSource::getPV(), CumbiaEpics::getThreadEventsBridgeFactory(), CumbiaEpics::getThreadFactoryImpl(), EpSource::getType(), EpSource::PV, and CuEpConfigurationPrivate::tsrc.
stop()
void CuEpConfiguration::stop () virtual
Implements CuEpicsActionI.
References CuEpConfigurationPrivate::exit.
Referenced by removeDataListener().
The documentation for this class was generated from the following files:
cuepconfiguration.h
cuepconfiguration.cpp