#ifndef CUMBIARANDOM_GLOBAL_H
#define CUMBIARANDOM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CUMBIARANDOM_LIBRARY)
#  define CUMBIARANDOMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CUMBIARANDOMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CUMBIARANDOM_GLOBAL_H
