qumbia-tango-controls: CuTWriterFactory Class Reference
CuTWriterFactory Class Reference
implements CuControlsWriterFactoryI and creates Tango writers Given a pointer to a Cumbia object and a CuDataListener, the create method instantiates and returns a CuTControlsWriter, that implements CuControlsWriterA interface. If setOptions is called before create, the options are set on the CuControlsWriterA.
#include <cutcontrolswriter.h>
Public Member Functions
CuTWriterFactory ()
virtual ~CuTWriterFactory ()
the class destructor
CuControlsWriterA * create (Cumbia *, CuDataListener *l) const
creates and returns a new CuTControlsWriter, configured with the given Cumbia and CuDataListener.
CuControlsWriterFactoryI * clone () const
clones the writer factory, allocating a new one with the same options
void setOptions (const CuData &o)
set options through a CuData bundle. They are then passed to the CuTControlsWriter instantiated and returned by the create method
Detailed Description
implements CuControlsWriterFactoryI and creates Tango writers Given a pointer to a Cumbia object and a CuDataListener, the create method instantiates and returns a CuTControlsWriter, that implements CuControlsWriterA interface. If setOptions is called before create, the options are set on the CuControlsWriterA.
CuTWriterFactory can be cloned by means of the clone method.
Constructor & Destructor Documentation
CuTWriterFactory()
CuTWriterFactory::CuTWriterFactory ()
the class constructor
Referenced by clone().
~CuTWriterFactory()
CuTWriterFactory::~CuTWriterFactory () virtual
the class destructor
Member Function Documentation
clone()
CuControlsWriterFactoryI * CuTWriterFactory::clone () const
clones the writer factory, allocating a new one with the same options
Returns
a new CuTWriterFactory with options copied from this object
References CuTWriterFactory().
create()
CuControlsWriterA * CuTWriterFactory::create (Cumbia * c, CuDataListener * l) const
creates and returns a new CuTControlsWriter, configured with the given Cumbia and CuDataListener.
Call setOptions before create to configure the writer.
Parameters
c a pointer to the CumbiaTango object
l a pointer to an object implementing the CuDataListener interface
Returns
a CuTControlsWriter, an implementation of CuControlsWriterA abstract class
References CuTControlsWriter::setOptions().
setOptions()
void CuTWriterFactory::setOptions (const CuData & o)
set options through a CuData bundle. They are then passed to the CuTControlsWriter instantiated and returned by the create method
Parameters
o a CuData bundle of key/value pairs
See also
create
The documentation for this class was generated from the following files:
cutcontrolswriter.h
cutcontrolswriter.cpp